### ISSUE TITLE
Wrapped text within SVG causes an error

### ISSUE THREAD

**Issue by chriscfox** [niklasvh/html2canvas#1000]
I have some text generated using SVG, which wraps across two lines. If I try and convert a div containing this SVG to Canvas, it throws an error: "Uncaught TypeError: child.measureTextRecursive is not a function(…)"

Here is the SVG for the component which wraps:
`<text x="152.33333333333334" style="color:#696969;cursor:pointer;font-size:12px;font-weight:normal;font-family:Verdana, Tahoma, Arial, &quot;Helvetica Neue&quot; , Helvetica, Sans-Serif;fill:#696969;width:275px;text-overflow:clip;" text-anchor="middle" transform="translate(0,0)" y="468" opacity="1" id="70bf096f-60ca-4050-8888-4cce053e882c"><tspan>Factor 1 edit with a long name so that it</tspan><tspan dy="15" x="152.33333333333334">wraps onto the next line</tspan><title>Factor 1 edit with a long name so that it wraps onto the next line</title></text>`

If I shorten the text so that it does not wrap onto the next line, the SVG looks like:
`<text x="152.33333333333334" style="color:#696969;cursor:pointer;font-size:12px;font-weight:normal;font-family:Verdana, Tahoma, Arial, &quot;Helvetica Neue&quot; , Helvetica, Sans-Serif;fill:#696969;width:275px;text-overflow:clip;" text-anchor="middle" transform="translate(0,0)" y="483" opacity="1" id="70bf096f-60ca-4050-8888-4cce053e882c"><tspan>Factor 1</tspan></text>`
and no error is generated.

Note that the SVG is being created by HighCharts.

**Comment by sorb999** [comment]
Hi @chriscfox 
It does not work with SVG.

**Comment by chriscfox** [comment]
Is this an official response from html2canvas?

It clearly does work with SVG as it works as soon as I shorten the text to the point that it no longer wraps.

**Comment by chriscfox** [comment]
Has anyone found a solution for this?

I get an error: "Uncaught TypeError: child.measureTextRecursive is not a function" if the text in highcharts/SVG wraps onto a second line, but not if it is all contained in a single line.

This is a significant problem to me, to the extent that I am going to have to consider dropping html2canvas as a solution.

**Comment by chriscfox** [comment]
I eventually found out that the simplest way to solve this problem is to remove all the <title /> elements from my charts, using jquery: $("title").remove();
