### ISSUE TITLE
html2canvas issue with icons

### ISSUE THREAD

**Issue by sorb999** [niklasvh/html2canvas#1001]
Hi,
 I am trying to print some icon with some text on it. html2canvas hiding that text and icon starts looking too odd. All details about issue is [here](http://stackoverflow.com/questions/40677942/html2canvas-issue-with-icons) .
Thanks :)

**Comment by sorb999** [comment]
It was working fine in  html2canvas 0.4.1 but when I switched to  html2canvas 0.5.0-alpha1 then this issue appeared.

**Comment by sorb999** [comment]
Hi @niklasvh this is the issue with html2canvas 0.5.0 please see this [fiddle](https://jsfiddle.net/sorb999/j09qd4xm/3/) you will find the issue. I think its a bug with html2canvas 0.5.0.
But if you will see my this [fiddle](https://jsfiddle.net/sorb999/808nau10/) then you will its working fine.

**Comment by a312586670** [comment]
我画html内容到canvas中怎么设置它从左上角开始画起

**Comment by niklasvh** [comment]
Fixed in 1.0.0 https://jsfiddle.net/j09qd4xm/7/
