### ISSUE TITLE
html2canvas not working in  Server (chorme)

### ISSUE THREAD

**Issue by Alebqto** [niklasvh/html2canvas#1004]
LOCALHOST
[-Prueba Testing (4).pdf](https://github.com/niklasvh/html2canvas/files/612159/-Prueba.Testing.4.pdf)

SERVER O FIREFOX
[ Prueba Testing.pdf](https://github.com/niklasvh/html2canvas/files/612164/Prueba.Testing.pdf)

hi, I have worked with html2canvas for one more year. Excellent option for capturing images.

I have the following problem, in localhost with browser chorme works perfectly when capturing images of a div, now on the server (amazon) with browser chorme does not work correctly, ie some images come empty, this does not happen with firefox, someone else has Happened this?

**Comment by neilpato22** [comment]
Same issue https://github.com/niklasvh/html2canvas/issues/1008

Any fix?

**Comment by Alebqto** [comment]
For now, my solution has been to use another library when using firefox. While the solution is implemented.
