### ISSUE TITLE
Not Able to Load EC2 Images in html2canvas

### ISSUE THREAD

**Issue by wanikunj** [niklasvh/html2canvas#1005]
Hello,
I am have cofigured my web service over the amazon ec2 server.When I am making call to an api method, in response i am getting the image content. But, when I set this api request url to render  images into canvas using html2canvas, it does not allow to render on canvas.
it gives me this error 
"No 'Access-Control-Allow-Origin' header is present on the requested resource."

I had also set useCORS: true in options, then too the error remains the same.
So anyone can help me to figure out the problem?

**Comment by aadilp** [comment]
I had this issue too. In my case the images were being loaded from the s3 bucket. So I had to change the CORS policy for the s3 bucket in the AWS console, and that resolved it. Sounds like you have a similar issue, where the image content is being loaded from a different server.

**Comment by BaptWaels** [comment]
I've got the same issue ec2 images.

Could you please share your CORS Policy @aadilp ? I've tried to configure it on aws but unable to get the correct one.

**Comment by aadilp** [comment]
@BaptWaels Apologies, I no longer have access to that AWS user. You might find something in the documentation.

**Comment by chandan123sahoo** [comment]
i have same issue can you plesae give suggestions
