### ISSUE TITLE
SVG still doesnt show, same :before and :after

### ISSUE THREAD

**Issue by uragecz** [niklasvh/html2canvas#1007]
I have latest version 0.5 beta3, but still my svg is ignored, and same :before and :after, my code -
```
printOnePage(){
       document.getElementById('helpPage').style.display= 'none';
       let page = document.getElementById('appContainer');
       html2canvas(page).then(function(canvas){
           console.log(canvas.toDataURL("image/png"));
        });
        document.getElementById('helpPage').style.display= '';
 }
```

My image should looks like - https://postimg.org/image/53u2r3tql/
But it looks - https://postimg.org/image/ipfuvym8d/
Any tips what to do?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
