### ISSUE TITLE
html2canvas 0.5.0 messes with css

### ISSUE THREAD

**Issue by weissamit** [niklasvh/html2canvas#1014]
Hi,

After one execution of Html2Canvas, jquery selectors don't work like before. 
I've tried to use importNode instead of adoptNode() as seen here: http://tech.chitgoks.com/2015/08/08/html2canvas-messes-css-style-after-screenshot/
This has solved the issue but caused another issue: canvas element is not rendered and I see black image instead (after changing from adoptNode to importNode)
I also found out this issue in the forum: https://github.com/niklasvh/html2canvas/issues/504
But this also did not help because the code diff there refers to an older version (0.4). 
Does anyone know how to help? Thanks

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
