### ISSUE TITLE
unable to capture Hindi fonts

### ISSUE THREAD

**Issue by bydbest** [niklasvh/html2canvas#1017]
I am unable to capture hindi fonts. it distorts the text and its not readable
@niklasvh  
english works just fine
http://imgur.com/a/Vvepl

**Comment by Bhadresh000** [comment]
Please Use 
http://jsfiddle.net/ydeL72m8/97/

**Comment by bydbest** [comment]
Thanks.

can i capture smiley etc ?????

**Comment by Bhadresh000** [comment]
use latest html2canvas.js
