### ISSUE TITLE
z-index causes white text to render transparent

### ISSUE THREAD

**Issue by bryantmakesprog** [niklasvh/html2canvas#1018]
I am using html2canvas in Ionic to generate an image for a user to share over social media. This is the actual dom element displayed on screen:

![image](https://cloud.githubusercontent.com/assets/16889195/21273298/e337ba16-c390-11e6-8d18-90bddd7a543b.png)

But this is the element as displayed in the rendered image.

![image](https://cloud.githubusercontent.com/assets/16889195/21273270/bcab8a08-c390-11e6-85f6-f92b45bbe34b.png)

These are the computed styles for that span:

![image](https://cloud.githubusercontent.com/assets/16889195/21273333/0c6e9c56-c391-11e6-8e98-0ba2bb44c713.png)

**Comment by bryantmakesprog** [comment]
Hmmm.... Okay, can't explain _why_ this works, but there seems to be an issue with the z-index. Explicitly setting the text to a higher z-index fixed the issue:

```
position: relative;
z-index: 1000000000000;
```


_adding a few keywords so people with similar issues can find this comment: transparent text index button_

**Comment by alanhg** [comment]
@bryantmakesprog
how to save img in ionic-app?
