### ISSUE TITLE
When converting multiple html div to base64 string using Canvas2 it doesn't convert base64 string to Image. Some portion of div doesn't appeared in image.

### ISSUE THREAD

**Issue by Jaydeep28** [niklasvh/html2canvas#1019]
$("body").on("click", "#btnSave", function () {           
            html2canvas($("#dvTemplateData")[0]).then(function (canvas) {
                var base64 = canvas.toDataURL();               
            });
        });

When trying to convert base64 to image online using 'http://codebeautify.org/base64-to-image-converter' it doesn't render full content of div element.

Please help me out this.

**Comment by Yene-Me** [comment]
Why this is closed
