### ISSUE TITLE
Converting DIV+Canvas objects to image. Working for few but gives white box for canvas object

### ISSUE THREAD

**Issue by rajul81** [niklasvh/html2canvas#1020]
I am converting Div which is having 3-4 canvas objects. It is working more most of people but some of the clients reported that they are getting white box over the canvas objects. I have checked the browser settings but it not looks different than mine.
Any way I can debug or fix this issue

**Comment by sameer6347** [comment]
![image](https://cloud.githubusercontent.com/assets/4352106/21386094/24ff975c-c797-11e6-9c13-ffc1bb48ed66.png)

When I am capturing the canvas generated circles I am getting attached output but on the browser, it is looking very smooth. Also, the colour didn't get captured as expected.

Original Images 
![image](https://cloud.githubusercontent.com/assets/4352106/21386153/7debe50a-c797-11e6-8f47-473edc69bca4.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
