### ISSUE TITLE
include /src in npm package

### ISSUE THREAD

**Issue by spurreiter** [niklasvh/html2canvas#1021]
The current npm package does not include the src files. If using webpack as 
bundler it throws a warning because of the package being pre-built.

Can you please remove the `src/` folder from `.npmignore` file in your next release.
As christmas being close, it would be a great present e.g. for using `rollup` as bundler, to add a 

```
"jsnext:main": "src/core.js",
```

line to `package.json` as well.

Merry X-mas and thanks a lot for this great lib.

**Comment by bugduino** [comment]
any news on this?

**Comment by niklasvh** [comment]
Closing in favor of #749
