### ISSUE TITLE
Latest stable version of html2canvas

### ISSUE THREAD

**Issue by PrateekDeshpande** [niklasvh/html2canvas#1024]
As we see issues in beta and alpha versions of html2canvas, such as full screen is not captured after page is scrolled down and some of the css is not visible in the screenshot captured by html2canvas.

So kindly let us know when the latest stable version of htm2canvas will be released.

**Comment by PrateekDeshpande** [comment]
We are also not able to capture the inner scroll of the application. Here the hidden data is over lapped on the other data of page in screen shot.

**Comment by niklasvh** [comment]
#1167
