### ISSUE TITLE
Summary of issues with 0.5.0

### ISSUE THREAD

**Issue by andersborgabiro** [niklasvh/html2canvas#1025]
This is what I've noted when using html2canvas 0.5.0 in a new Web app I'm working on. I can provide the link via a direct message.

ul and ol should show bullets/numbers.

pre and code should use a fixed-spaced font.

In the app I've made it possible to see the intermediate HTML used to render the image, so it's easy to compare.

I'm still using the old "onrendered" method, despite being deprecated, as I don't know how to add options to the new approach. I haven't found any documentation for that, only a simple example without options.

Regards,
Anders

**Comment by andersborgabiro** [comment]
I handled pre and code by setting a style that affected the generated HTML directly, so that works now. It seems html2canvas doesn't lift out any such styles from the context.

**Comment by andersborgabiro** [comment]
Does/will lists work?Any bullet (no pun intended) proof solution for that?

**Comment by niklasvh** [comment]
Currently there is no support for them. Cleaning up the issues list for the next release, more info at #1167
