### ISSUE TITLE
Hindi Font Issue 

### ISSUE THREAD

**Issue by Bhadresh000** [niklasvh/html2canvas#1026]
While Capturing Image of Div tag. the hindi font are not capturing properly in htmk2canvas,

**Comment by NoFootDancer** [comment]
Can you show an example so people can help you out better?

**Comment by Bhadresh000** [comment]
I solved issue by self

**Comment by kapyaar** [comment]
Can you share how you solved this? I have issues with few other fonts :)

**Comment by Bhadresh000** [comment]
which font ?

**Comment by Bhadresh000** [comment]
http://jsfiddle.net/ydeL72m8/1/
