### ISSUE TITLE
capturing images and canvas with loaded images from other origin

### ISSUE THREAD

**Issue by chloeng** [niklasvh/html2canvas#103]
Hi Niklas,

Thank you so much for such wonderful code. It is such a great tool to solve my scenario. It worked fine in the beginning during local testing, but I encountered some issues while trying to deploy to our development server. The issues are:
1. Need a proxy to access content from other domain/origin: I solved this by creating my own Java proxy (converted from the Python code). Seems to be working fine for images with <img> tag.
2. Encountered this issue for <canvas> elements in my code which contains images loaded from other domain: [Unable to get image data from canvas because the canvas has been tainted by cross-origin data]. Is it due to the fact that the canvas element in my code contains drawn images from other domain/origin? Can this be solved? I have tried to set the header for "Access-Control-Allow-Origin" but seems like this won't solve the issue.

Have been searching for the solution for Issue 2 online for days but to no avail.

Hopefully you can enlighten me with a solution for this.

Thanks a lot.

**Comment by kevinchiu** [comment]
If the canvas contains both remote images and local blobs, the proxy option does not work correctly. 

#823

**Comment by vishal-px** [comment]
Hi @niklasvh 
   I am trying to capture web-page and send it to different domain,
   Its working fine but issue is that images are not getting.

   Here is my code.

  	jQuery(".screenshot_row_target").html2canvas({
	logging: true,
	useCORS : true,
	//taintTest : true,
	allowTaint : true,
	"onrendered": function (canvas) {
	  	jQuery('#screenshot_img_val').val(canvas.toDataURL("image/png"));
	 	//document.getElementById("screenshot_html_form").submit();  //  redirect to edit.php
          }
  });
   Do you have any solution?.
Thanks.

**Comment by shenzhuxi** [comment]
I tried to render a html with images in filesystem, and found "html2canvas: Finished loading 0 images" in the logs. 
Are they considered cross-origin data, though they have the same base URL like filesystem:http://localhost:8080?

**Comment by jlahare** [comment]
is there any update over this ?
