### ISSUE TITLE
removeAttribute of null error in line 1000 - html2canvas.js

### ISSUE THREAD

**Issue by glevinzon** [niklasvh/html2canvas#1030]
For some unknown reason, this line:
`document.querySelector(selector).removeAttribute(attributeName);`
returns an error since querySelector(selector) is null. Please fix this one.

**Comment by arsuceno** [comment]
I get that error if I do 2 snapshots at the same time, is that your case also?

**Comment by briankoech** [comment]
@niklasvh was this issue resolved? I am still getting the error.

**Comment by niklasvh** [comment]
@briankoech Are you using 1.0.0? If so, please share an example on jsfiddle where you are experiencing the issue and I'll take a look
