### ISSUE TITLE
dist/下打包文件   不是cmd amd 规范  webpack 无法使用 有警告

### ISSUE THREAD

**Issue by fengluhome** [niklasvh/html2canvas#1031]
webpack 打包提示
vendors.js:717 ./src/libs/html2canvas.js
Critical dependencies:
25:88-96 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/libs/html2canvas.js 25:88-96

**Comment by callmewhy** [comment]
duplicated with https://github.com/niklasvh/html2canvas/issues/749
