### ISSUE TITLE
Couldn't take screenshot of dynamically loaded div

### ISSUE THREAD

**Issue by beingbishwa** [niklasvh/html2canvas#1032]
I have the following code inside my div:
   ` <div>                  
         <?php echo "<img src='https://graph.facebook.com/481032075371655/picture'>";?>             
    </div>`
It just result me with blank image... Not the one with the image generated by php

**Comment by Bhadresh000** [comment]
store image on local server and than display from local server it. its working for me.

**Comment by beingbishwa** [comment]
can i get your facebook id or any connecting medium?? need to get some help from you :) :)

**Comment by Bhadresh000** [comment]
https://www.facebook.com/bhadresh.pipaliya.3

**Comment by Alexwrj** [comment]
Have the same problem: I cannot render content of dynamically generated <div>
