### ISSUE TITLE
White vertical line appearing on google map capture

### ISSUE THREAD

**Issue by kuroshhashemi** [niklasvh/html2canvas#1033]
Line does not appear on browser.  Only appears in html2canvas image
Google Maps
![image](https://cloud.githubusercontent.com/assets/16429402/21869507/ecd1ae34-d825-11e6-9dc6-802a486b0a24.png)

**Comment by markadrake** [comment]
@kuroshhashemi any luck?

**Comment by kuroshhashemi** [comment]
Hi @markadrake actually it seems to have solved itself.  I'll mark as closed.  Thanks
