### ISSUE TITLE
Rendering difference between Chrome and Firefox

### ISSUE THREAD

**Issue by metalhurlant364** [niklasvh/html2canvas#1040]
Hello,
I have a rendering issue with Firefox 50.0.1.
It's a schedule module pour our company.  The basic gui build on the server side (php).

Then, the data loaded by ajax request using jquery plugin (jquery.weekcalendar.js).

I tested earlier version of Firefox (38 and 47) and chrome (49), the rendering result was identical to the screen.  No error on the browser console.

Rarely, the Firefox 50 renders correctly the schedule (1 time on 50).  I repeat immediately the same action, and I obtain the wrong rendering.

It look like the css style is not loading during rendering or ignore by html2canvas to a certain degre.

If you have any tips, or clue,  I will be glad to test it.

Thanks and have a nice day.
Simon

Bad export on Firefox 50.0.1
![export1_firefox_50](https://cloud.githubusercontent.com/assets/25200888/22066260/2e2a4b32-dd5a-11e6-8d29-d67bc949a638.png)
Good export on Chrome 49
![export1_chrome_49](https://cloud.githubusercontent.com/assets/25200888/22066261/2e2ce676-dd5a-11e6-93fd-72ac12068942.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by metalhurlant364** [comment]
Hi Niklasvh,  I dont work anymore for this company.  I will send an email to a friend who is still working there to check if they still have this problem.
