### ISSUE TITLE
Issue with export on Firefox with GIF images

### ISSUE THREAD

**Issue by syrus44** [niklasvh/html2canvas#1041]
Hello,

I had an issue using html2canvas with a proxy (html2canvas-php-proxy). When exporting on Firefox, the GIF image from api.ign.fr (http://api.ign.fr/geoportail/api/js/2.0.0/theme/geoportal/img/loading.gif) is successfully added but not loaded by the library.

The GIF image is not present in the DOM, it loads from Cross Origin requests. In my code, the parameter "useCORS" is set to true and the proxy file is present in the app.

Here is the log message returned from the export : 
html2canvas: Failed loading image #1 Object { src: "http://api.ign.fr/geoportail/api/js…", image: load, tainted: null, promise: Promise } error { target: <img>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1485247498098000, originalTarget: <img>, explicitOriginalTarget: <img>, NONE: 0, CAPTURING_PHASE: 1 }
html2canvas: DummyImageContainer for "http://api.ign.fr/geoportail/api/js/2.0.0/theme/geoportal/img/loading.gif"

Here is the exception message returned from the export : 
html2canvas: TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.

Is there any solution to this problem ? Or can I ignore the GIF pattern from the export ?

I think this issue is related to the #556 ticket.

Here is the details on our test environment : 
Linux CentOS 6.5 / PHP 5.3.3 / html2canvas 0.5.0-beta3

Thanks in advance

Best regards

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
