### ISSUE TITLE
Large images are croped

### ISSUE THREAD

**Issue by wipflash** [niklasvh/html2canvas#1043]
I need to export a large chart. It always exporting window size. i was changed width manually but not working.
```
var chartContainer = $('#chart-container');
var sourceChart = chartContainer.find('.orgchart:visible').get(0);
html2canvas(sourceChart,
            {
                width: 2500,
                height: 500,
                onrendered: function (canvas) {
                    document.body.appendChild(canvas);
                }
            });
```
What I have
![somefilename 4](https://cloud.githubusercontent.com/assets/8122779/22394619/7758e36a-e54b-11e6-9bcc-af12c2c79eb7.jpg)

What I expect
![image](https://cloud.githubusercontent.com/assets/8122779/22394611/45e75ec4-e54b-11e6-9abd-05f79e385d8c.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
