### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by madsid** [niklasvh/html2canvas#1044]
Is anyone working on releasing any updates? @niklasvh

**Comment by templatetuners** [comment]
I don't think so

**Comment by mudcube** [comment]
Why bug the maintainer about whether it's alive? If the owner thought they were never going to update it again there would be a message in the README... We're talking about a very responsible and highly regarded developer here. The html2canvas website was updated 9-months ago, that seems pretty alive to me. The owner obviously has other things going on in their life.

Perhaps a more useful issue would be, "How can I help to sort through all these pull requests?" Perhaps the owner would be open to inviting others on the project as maintainers so the project could be updated more regularly? That would be very cool and beneficial too all.

Asking "Is this project still alive" to me serves no purpose other than to troll/guilt the owner into pushing an update which is not very inspiring. Please correct me if I'm missing something here...

**Comment by madsid** [comment]
@mudcube Thanks for the information. I was looking for some of the interesting projects to contribute to and being new to open source contribution I am not sure how to approach. I will try looking at the pull requests and see how I can be helpful. Thanks again!!

**Comment by marcandrews** [comment]
I also would like to help maintain this project. I think it would be cool if @eKoopmans also jumped on board too. There are a lot of great PRs ready to be merged in.

**Comment by eKoopmans** [comment]
I'd be happy to help maintain, it just depends what @niklasvh wants. I definitely appreciate the project and think it should continue to be developed!
