### ISSUE TITLE
IE Edge SVG rendering issue

### ISSUE THREAD

**Issue by fatangare** [niklasvh/html2canvas#1047]
Hi,

I was not able to render SVG on IE Edge even using promise.

I did following changes in code and it worked.

In function SVGNodeContainer(node, _native) of html2canvas.js
` self.image.src = "data:image/svg+xml;base64," + window.btoa((new XMLSerializer()).serializeToString(node));` is used.

In function initialize: function(path, options) of html2canvas.svg.js
`if (!path) {
        // throw new Error('`path` argument is required');
        path = [];
      }` is used.

Hope it helps others.

**Comment by yoler** [comment]
I also met this problem, In other browsers can normal rendering, but on the edge of the SVG can not be rendered

**Comment by niklasvh** [comment]
Closing in favor of #1051
