### ISSUE TITLE
License Text File

### ISSUE THREAD

**Issue by BMillsVT** [niklasvh/html2canvas#1049]
Hey Niklasvh,
I'd really like to use your code, but my company won't let me use projects that aren't clearly licensed.  It looks like you've licensed this software under the MIT license, but I wasn't able to locate the license text. Would you please consider adding a LICENSE file with your copyright information which includes the text of the MIT license?  The MIT license specifically states that the license text must accompany the source code. I'd be happy to do a pull request if you'll let me know what copyright information you want at the top of the LICENSE file.

Thanks,
Brian

**Comment by eKoopmans** [comment]
Hi @BMillsVT, there definitely is a license file attached to this repo, at the root level, called LICENSE. Here's a link:

https://github.com/niklasvh/html2canvas/blob/master/LICENSE

**Comment by BMillsVT** [comment]
No idea how I missed this file.  It's pretty obvious.  Thanks for point it out.

**Comment by eKoopmans** [comment]
No problem!
