### ISSUE TITLE
Rotated text is cropped

### ISSUE THREAD

**Issue by PhpSriptKiddie** [niklasvh/html2canvas#1052]
I am having some problem with rotated text, which ís cropped halfway, when using html2canvas. Please see the following fiddle for example:

http://jsfiddle.net/8dvy5Lke/2/

**Comment by niklasvh** [comment]
Still an issue in 1.0.0 http://jsfiddle.net/8dvy5Lke/21/

**Comment by niklasvh** [comment]
Fixed
