### ISSUE TITLE
c3 js chart text dubbling issue

### ISSUE THREAD

**Issue by DinakaranS** [niklasvh/html2canvas#1053]
Hi,

I am trying to convert c3js chart to png using html2canvas. But i am getting all the chart text doubling.
<img width="695" alt="screen shot 2017-02-13 at 5 42 22 pm" src="https://cloud.githubusercontent.com/assets/8424594/22883047/3e64b108-f214-11e6-9c8e-9b582d4dcfb8.png">

**Comment by madned** [comment]
This guy found a fix, but you are going to have to modify the source code: https://github.com/niklasvh/html2canvas/issues/734#issuecomment-158303134

**Comment by hyojin** [comment]
Yes, you can modify the code. Or just run build task and find the result from dist dir. I think it's easier.
