### ISSUE TITLE
Mobile Device Width Not Working Not Size

### ISSUE THREAD

**Issue by malikocak** [niklasvh/html2canvas#1055]
![2017-02-20_001422](https://cloud.githubusercontent.com/assets/18191647/23106646/319b4b64-f6f9-11e6-88a8-8bc61cc9d94d.jpg)

canvas.toDataURL() result width original size not match

**Comment by santanup789** [comment]
I faced this same problem. I noticed that when your creating pdf after hitting download button for device width some portion of your data is not displaying on your screen. That hidden data is showing black.
