### ISSUE TITLE
Resolution much better with Chrome in debug mode

### ISSUE THREAD

**Issue by jrobens** [niklasvh/html2canvas#1057]
I am trying to get the resolution of the download to be better and this has me confounded. 

Using debug mode I get 

![chart 18](https://cloud.githubusercontent.com/assets/169989/23151651/c2582066-f850-11e6-97ba-f9f590602ca2.png)

Turn off debug mode

![chart 19](https://cloud.githubusercontent.com/assets/169989/23151654/c9c0cca4-f850-11e6-8031-94fc14dc280a.png)

Is it because the window size is smaller? Resize window to be narrower. 

![chart 20](https://cloud.githubusercontent.com/assets/169989/23151661/dc6ced42-f850-11e6-9b38-ff5f9af7d790.png)

I'm raising this because the debug mode version is tantalisingly close to what I want. 

0.5.0-beta3. 

There doesn't seem to be a way to resize the created image in this version. The css width settings are not changing it and from my reading of the source code it is getting the size from the document. 

The source is a chart generated with angular-chart. 

  

    srcEl.style.backgroundColor = 'white';

    // Save original size of element
    var originalWidth = srcEl.offsetWidth;
    var originalHeight = srcEl.offsetHeight;
    // Force px size (no %, EMs, etc)
    srcEl.style.width = (originalWidth) + "px";
    srcEl.style.height = (originalHeight) + "px";
    // The bootstrap column classes have position relative.
    // relative to the viewport
    var viewportOffset = srcEl.getBoundingClientRect();
    var top = viewportOffset.top;
    var left = viewportOffset.left - 15;

    var moveSourceHorizontally = (left.toString().indexOf('-') === -1 ? '-' : '') + left + 'px';
    var moveSourceVertically = (top.toString().indexOf('-') === -1 ? '-' : '') + top + 'px';

    srcEl.style.position = 'absolute';
    srcEl.style.left = moveSourceHorizontally;
    srcEl.style.top = moveSourceVertically;

    var scaledCanvas = document.createElement("canvas");
    var scaledWidth = originalWidth * scaleFactor;
    var scaledHeight = originalHeight * scaleFactor;
    scaledCanvas.width = scaledWidth;
    scaledCanvas.height = scaledHeight;
    scaledCanvas.style.width = (originalWidth) + "px";
    scaledCanvas.style.height = (originalHeight) + "px";

    var scaledContext = scaledCanvas.getContext("2d");
    scaledContext.scale(scaleFactor, scaleFactor);

    // Height and width don't work with non string nodes passed.
    html2canvas(srcEl,
      {
       // type: 'view',
        canvas: scaledCanvas
      }).then(function (canvas) {
      var a = document.createElement("a");
      a.download = "chart.png";
      a.href = canvas.toDataURL("image/png");
      document.body.appendChild(a);
      a.click();

      srcEl.style.position = '';
      srcEl.style.left = '';
      srcEl.style.top = '';
    });

**Comment by niklasvh** [comment]
Fixed in 1.0.0
