### ISSUE TITLE
Background-size: px not working properly

### ISSUE THREAD

**Issue by maxipeli** [niklasvh/html2canvas#1060]
I want to congratulation you for your great  work with this library.

Recently I've found an issue. I am using background-size with pixel, like this example:

 `background-size: 100px;`

But the screenshots is deformed, but if I use this:

 `background-size: 100px cover`

The screenshot is taken properly, but the result for me there's not good.

I hope you can help me with this issue.

Thank you very much!

**Comment by nitink4472** [comment]
This is because by using the former the width sets to 100px and height is auto (it doesn't covers the whole section) and in the latter width is set to 100px but the height is being covered in the whole section and that's why you are able to take the screenshot clearly.
