### ISSUE TITLE
IE10 not working with 0.5 alpha version

### ISSUE THREAD

**Issue by richardwang232** [niklasvh/html2canvas#1061]
It seems like html2canvas doesn't work anymore on IE10 after I upgraded from 0.4.1 to 0.5.0-alpha1. I'm running the example in the readme and I see that the then() function doesn't get called. I made sure I was loading es6-promise before the html2canvas.js. I checked the Developer Tools console and I don't see any JS errors.

```
html2canvas(document.body).then(function(canvas) {
    document.body.appendChild(canvas);
});
```

Will IE10 still be supported in 0.5? Thanks for your help!

**Comment by fatangare** [comment]
Check this https://github.com/niklasvh/html2canvas/pull/1051

And also make sure svg.min.js is added after html2canvas.js is added in includes
