### ISSUE TITLE
Text out of div is being cropped

### ISSUE THREAD

**Issue by mzi137** [niklasvh/html2canvas#1063]
Hello, i have the following problem:
I have some divs with texts, and in some of them the texts are outer of the div.
The problem is, when the text is outer of the div, the text is cropped.
Ive debugged a little, and i think it is because the div is converted into canvas.
Any leads to solution in your opinion?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
