### ISSUE TITLE
Images are not rendring

### ISSUE THREAD

**Issue by AvanishKumar008** [niklasvh/html2canvas#1065]
I have a parent div. In this Div i have lots of div and some div have image but when i rendering that time i am not able to see image. What should i do.
I want like this

![demo](https://cloud.githubusercontent.com/assets/17271378/23545840/f995b9a6-0022-11e7-9a97-f8cc05ca22d9.png)

Show like this.
![dashboard](https://cloud.githubusercontent.com/assets/17271378/23545780/c569df36-0022-11e7-88ff-3e76893e7a5a.png)

**Comment by Riyaz0001** [comment]
same problem dude. how solve it?

**Comment by AvanishKumar008** [comment]
I use other API for this. Using that API you can create PNG, JPED and SVG image.

**Comment by KingGeneral** [comment]
may it work the same : #314  
https://github.com/niklasvh/html2canvas/issues/314

**Comment by AvanishKumar008** [comment]
@KingGeneral Both are not same. My issue with image.

**Comment by KingGeneral** [comment]
^see the second one, i edit the comment above

**Comment by AvanishKumar008** [comment]
Yes It's same

**Comment by KingGeneral** [comment]
have you try the proxy one ??? stated in issue [proxy](https://github.com/niklasvh/html2canvas/issues/145#issuecomment-34174752)
