### ISSUE TITLE
Html2Canvas not capturing whole html in IE11

### ISSUE THREAD

**Issue by ParthibanSugumar** [niklasvh/html2canvas#1069]
Hi @niklasvh ,

I am using HTML2Canvas to capture screenshot of my html page and save it as image in server. My Html contains a d3.js chart and html elements. d3.js chart is generated as svg. So to capture svg, I use Fabric.js to convert svg to canvas element. After this process is complete, I use Html2Canvas to capture the entire web page as image and save it in server.

The whole process is working fine in Chrome and FF. Problem is when using IE. In IE 11, everything else in the page is captured except the chart canvas element.

**Note**: I understand that in IE < Edge will taint the canvas as soon as an SVG image has been drawn to it.

Please help me to fix this issue.

Thanks,
Parthiban.S

**Comment by ParthibanSugumar** [comment]
I found the root cause for this issue to be another svg icon which was embedded inside the chart. Replacing the svg icon with png image fixed this issue.

Sorry for the inconvenience.
Hope it helps someone in future.

**Comment by ParthibanSugumar** [comment]
I found the root cause for this issue to be another svg icon which was embedded inside the chart. Replacing the svg icon with png image fixed this issue.

Sorry for the inconvenience.
Hope it helps someone in future.

**Comment by xianjin-xu** [comment]
@ParthibanSugumar  could you know where is the svg icon?  i have the same problem at IE11(win10), i can't find the svg icon, could you give me some guidence for the svg icon.
thanks for your great help!
