### ISSUE TITLE
Hidden Element Rendering

### ISSUE THREAD

**Issue by danaja** [niklasvh/html2canvas#107]
Hi,

Is it possible to use html2canvas for getting a hidden element on a page on to a canvas? I haven't gone through much of the code yet but just commenting the logic that skips hidden elements doesn't seem to work

**Comment by mrded** [comment]
What if I want to take a screenshot of really tall page? So far I managed to only take s screenshot of visible part.

**Comment by eKoopmans** [comment]
Hi @mrded, offscreen rendering is a known issue that I have tried to resolve in my pull request #1083. It hasn't been merged in yet, but if you want to try it out you can grab my latest build [here](https://github.com/eKoopmans/html2canvas/tree/develop/dist), which has that and a few other features/bugfixes merged in.
