### ISSUE TITLE
Angular2: Rendering an element and appending the canvas to the body?

### ISSUE THREAD

**Issue by da45** [niklasvh/html2canvas#1070]
Hi,

I am trying to use html2canvas in my angular2 project, I would create an element and append the canvas to the body as described below:
```

let newDiv = document.createElement("div"); 
let newContent = document.createTextNode("Hi there and greetings!"); 
newDiv.appendChild(newContent); 
html2canvas(newDiv).then(function(canvas) {
    document.body.appendChild(canvas);
});
```
but I got the below error:

EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'removeAttribute' of null TypeError: Cannot read property 'removeAttribute' of null

Any idea please to fix this error ?

thanks,

**Comment by chunyenHuang** [comment]
I think you will need to append the element to body. 
set z-index to -1 > append to body > render > remove from body.

**Comment by citerio** [comment]
Hey Guys, I have the same problem, Do I have to create a body element first, then append the div to the body and the content to the div, right?

**Comment by eKoopmans** [comment]
@citerio Yes, whatever element you are trying to capture with html2canvas must be a descendant of your webpage's body element. To other readers, this requirement has nothing to do with Angular2 specifically.
