### ISSUE TITLE
dropdown value not captured correctly in IE only

### ISSUE THREAD

**Issue by glennax** [niklasvh/html2canvas#1071]
This is an IE-only issue. I am on IE 11, and haven't tested it in other versions yet.
 
On my page I have a dropdown menu that has values of "No Response", "No" and "Yes". However, no matter what value I select, the capture always show "No" as selected and the dropdown arrow is omitted:

Like so:  
![image](https://cloud.githubusercontent.com/assets/6312966/23764249/1e689cee-04ba-11e7-9f2b-de61f584a6e3.png)

It looks like I got a "Permission denied" error on this line in jQuery:

![image](https://cloud.githubusercontent.com/assets/6312966/23764715/bff9809a-04bb-11e7-8252-5a4f29e92393.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
