### ISSUE TITLE
not capturing the modal in the body

### ISSUE THREAD

**Issue by shamis** [niklasvh/html2canvas#1072]
When trying to capture the whole body which contains a modal and if the modal overflows the body then the modal is not captured.
https://plnkr.co/edit/WxODWsutraVN9hjHXcHr?p=preview

**Comment by Brieg** [comment]
+1

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
