### ISSUE TITLE
Sending div to capture returns view instead

### ISSUE THREAD

**Issue by teknocreator** [niklasvh/html2canvas#1076]
The 0.5 alpha 1 version correctly captured the div or html element sent to html2canvas.  I saw that in 0.5 beta 4 there was a change so the scrolled window could be captured.  Unfortunately, that feature is on by default now with no option setting to return to capturing a complete div or element.  I'm sending an element id="contents" via jQuery to the function like so - html2canvas($('#contents'), {.  I have to scroll the window down a bit in order to activate the function that calls h2c.  When I do that and don't scroll back up, the resulting captured image is also scrolled down with the top of the contents element cut off.  This was not occurring in 0.5 alpha 1 and I've switched back to using it instead.  I reviewed the changed code in 0.5 beta 4 and it appears that options.type is never set.  There's a statement .... { type: "view"..., but that doesn't set options.type.  I attempted to modify the code accordingly, but the other part of the code that was changed still took the view rather than the div element.  In this if statement, 

 `if (options.type === "view") {
            canvas = crop(renderer.canvas, {width: renderer.canvas.width, height: renderer.canvas.height, top: 0, left: 0, x: 0, y: 0});
        } else if (node === clonedWindow.document.body || node === clonedWindow.document.documentElement || options.canvas != null) {
            canvas = renderer.canvas;
        } else {
            canvas = crop(renderer.canvas, {width:  options.width != null ? options.width : bounds.width, height: options.height != null ? options.height : bounds.height, top: bounds.top, left: bounds.left, x: 0, y: 0});
        }`

it appears that even if options.type is set to something other than "view", it will still return the view instead of the div contents as was the previous behavior...at least by the resulting rendered image that's returned.

Is there a way to ensure the html element I'm passing to h2c is rendered despite the window being scrolled like the behavior in 0.5 alpha 1?  This is for a web page on a desktop vs mobile device.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
