### ISSUE TITLE
How to save an image to folder?

### ISSUE THREAD

**Issue by takoy123** [niklasvh/html2canvas#1078]
Help me please. I convert html5 contents to an image and save it to some folder directly for example 'myFolder/image.png' , no need to download popup appeared using java only javscript or angularjs.
I can convert but I can not save it to my Folder path.
html2canvas([document.getElementById('mainDiv')], {
            background:'#fff',
            onrendered: function (canvas) {
              var myImage = new Image();
              var imageconvert=canvas.toDataURL('image/png',1);
              myImage.src =imageconvert;
}
}

**Comment by alanhg** [comment]
me too
