### ISSUE TITLE
Get full content of an overflow element

### ISSUE THREAD

**Issue by Maxence** [niklasvh/html2canvas#108]
Hello,

Is it possible to render a full element from an overflow element ?

I got something like this :

``` html
<div id="#overflow" style="overflow: auto; height: 200px;">
     <div id="content" style="height: 800px; background-color: #000">
           some text...
     </div>
</div>
```

My #content is taller than my #overflow.

``` javascript
thiscreen = $('#content');
thiscreen = thiscreen[0];

var options = options || {};
options.elements = [thiscreen];

html2canvas.logging = options && options.logging;
options.complete = function(images){
    var queue = html2canvas.Parse(thiscreen, images, options),
    $canvas = html2canvas.Renderer(queue, options);
    document.getElementById('imgtest').src = $canvas.toDataURL();
};
html2canvas.Preload(thiscreen,  options);
```

image got the right resolution, but its transparency

[edit]
Example : http://sweetweb.fr/demo/html2canvas_overflow.html

**Comment by ruthraprakash** [comment]
Hi All, I have div which is scrollable. When i send the div input as canvas parameter, it just rendering what is avialable in viewport. I gone through all solutions. I didnt understand. Can anyone tell how to take entire content in div as screenshot.

**Comment by ghalib2k11** [comment]
same issue here.. rendering what is visible i want to capture the tabs data which is not working at all in canvas2html

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });
