### ISSUE TITLE
How to set html2canvas div to shot

### ISSUE THREAD

**Issue by ckvtdn** [niklasvh/html2canvas#1081]
Hi everyone,

Sorry for my english :/

I'm working on an school project, and i want to know how to set what div will be shot by html2canvas ?

Currently, my button shot the whole page.

Here my script 

```
<script>html2canvas( $('table'), {
   onrendered: function( canvas ) {
        var img = canvas.toDataURL();
        $('#calendar_to_canvas').attr('src', img);
   }
});</script>
<script type="text/javascript">                         
function genScreenshot() {
html2canvas(document.body, {
  onrendered: function(canvas) {
  $('#box1').html("#shot_object");

  if (navigator.userAgent.indexOf("MSIE ") > 0 || 
                navigator.userAgent.match(/Trident.*rv\:11\./)) 
        {
    var blob = canvas.msToBlob();
    window.navigator.msSaveBlob(blob,'Test file.png');
  }
  else {
    $('#snap').attr('href', canvas.toDataURL("image/png"));
    $('#snap').attr('download','avatar.png');
    $('#snap')[0].click();
  }
  }
});
}  
</script>
```

Thx guys ! <3

**Comment by Romerski** [comment]
Yeah, it's shotting the whole page because your are refering to **document.body** as first element of html2canvas function what takes first argument as element you want to render it. 

`html2canvas(document.body, {`

Change it for element you want to render it, for example a div.

**Comment by ckvtdn** [comment]
Thx Romerski !

**Comment by ckvtdn** [comment]
Hi again !

Something like this would be okay, no ?

```
html2canvas(document.getElementById("snap-target"), {
  onrendered: function(canvas) {
  $('#box1').html("#shot_object");
```

**Comment by Romerski** [comment]
Yes, in that case **document.getElementById("snap-target")** will be rendered as canvas.

I dont know what is your purpose but if you want to print rendered canvas in **#box1** element it should be **$('#box1').html(canvas);**. 'canvas' taken from 'onrendered: function(**canvas**) {' is canvas rendered element you want.
