### ISSUE TITLE
后台传给我的微信头像生成图片后无法显示出来

### ISSUE THREAD

**Issue by ablikim915** [niklasvh/html2canvas#1082]
我的页面上总共三张图片是从后台传来的，都放在一个大的div里面，然后把这个div转换程图片，其中一个微信头像生成图片后无法显示出来，其他两张后台传来的图片没问题可以正常转换。谁遇到过这种问题，怎么解决的？

**Comment by JackYangFM** [comment]
> 我的页面上总共三张图片是从后台传来的，都放在一个大的div里面，然后把这个div转换程图片，其中一个微信头像生成图片后无法显示出来，其他两张后台传来的图片没问题可以正常转换。谁遇到过这种问题，怎么解决的？

我也遇到这样的问题，就是后台返回的某个图片截图完了之后不显示出来，img里的src属性我用的是vue动态赋值
