### ISSUE TITLE
Remove unsupported HTML/CSS before capturing

### ISSUE THREAD

**Issue by FranckSCTV** [niklasvh/html2canvas#1091]
Hi,
I'm looking for a way to remove any HTML/CSS that can't be properly captured by html2canvas before I actually capture the page. 
The goal is to "simplify" the HTML/CSS in order to prevent capture with faulty/partially rendered elements.
Thanks!

**Comment by chriscfox** [comment]
I use jquery for this purpose. You could add a class 'hideonhtml2canvas' to specific elements, then run $(".hideonhtml2canvas").hide(); before taking the image and $(".hideonhtml2canvas").show(); immediately after.

**Comment by FranckSCTV** [comment]
Hi Chris,
Sounds like a good approach.
But is there a list somewhere with all the elements/attributes that can't be captured nicely by html2canvas?
I'm under the impression that the "Limitations" section on the web page doesn't give them all since SVG isn't specified there.

**Comment by chriscfox** [comment]
I am not aware of a complete list. I had specific elements I wanted to exclude for more functional reasons - that is I wanted a screenshot showing an output, but not for example, the buttons and other controls to update it.

By the way, I was able to include SVG elements (I am using Highcharts, for example) based on the following instructions: http://stackoverflow.com/questions/34042440/using-html2canvas-to-render-a-highcharts-chart-to-pdf-doesnt-work-on-ie-and-fir

**Comment by FranckSCTV** [comment]
Okay!
And thanks for the useful additional piece of information.
Cheers
