### ISSUE TITLE
Version 0.5.0 alpha1 - defined width and height not working -> beta3 works!

### ISSUE THREAD

**Issue by juliosene** [niklasvh/html2canvas#1093]
Hi,
I'm using htlm2canvas to take some screenshots under a cordova / phonegap mobile app. 

First of all, are doing an amazing job on html2canvas! 

I was using 0.5.0 beta3 version to render a div with fixed width and height (greater than screen size) and it was working fine. However, when I upgraded to 0.5.0 alpha1, this feature crashed and are just capturing the part of this div that matches to the visible screen area. So, I've must downgraded to beta3.

I hope that this issue will be addressed as fast as possible. 

Thanks!

UPDATE: 

I did some comparison between the code that works and the code that fails, so i think that the difference is around line 603:

works:
`    return renderDocument(node.ownerDocument, options, options.width != undefined ? options.width : node.ownerDocument.defaultView.innerWidth, options.height != undefined ? options.height : node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {`

fail:
`    return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {`

**Comment by coolbombom** [comment]
Hi juliosene

alpha is a downgrade .... A (alpha) come before B (beta) .... so beta is the latest, it has not made it to the release though! Kind suspect that this project has died!

kind regards
c_bb
