### ISSUE TITLE
Will this work with Ipad/Android App?

### ISSUE THREAD

**Issue by prahladmishra** [niklasvh/html2canvas#1095]
Hi,

I have an app written in HTML/CSS/Jquery. That takes data in Json and show it as table based on user selection. I want to add functionality to send final selection to the customer as mail for this I was thinking of using this plugin to take screenshot and save in Photo library or iPad/tablet. Can this plugin do that? Once saved it can be sent via email to customer.

Regards,
Prahlad

**Comment by chriscfox** [comment]
You might need to save it to your server first and then email it from there.

**Comment by prahladmishra** [comment]
My app works even offline so server may not be available to user.
