### ISSUE TITLE
how to take screen shot of canvas element

### ISSUE THREAD

**Issue by chandandas** [niklasvh/html2canvas#1101]
Hi,

I have a html page which contains images, menus , html elements and a canvas where user can draw images. Now if i take screen shot of entire page , all elements on canvas are not gone, disappear.

Can anyone help me here?

**Comment by dorcohen8** [comment]
+1

**Comment by shehy** [comment]
I have the same problem

**Comment by niklasvh** [comment]
@shehy should be fixed with https://github.com/niklasvh/html2canvas/commit/38749bc4b6a861f778a915491fc7d84fea6e1a2f
