### ISSUE TITLE
Angular 2 Unable to get property 'svg' of undefined or null reference

### ISSUE THREAD

**Issue by chungtinhlakho** [niklasvh/html2canvas#1102]
Hi, I am using Angular 2 with html2canvas, I can get this to work in firefox, i do see the error in the console in firefox but it will work.

However, when in IE, i cannot get any further, this message stops it.  Even tho I do not have any svg in the element i'm trying to convert.  

Any tips is greatly appreciate it. 

Unhandled Promise rejection: Unable to get property 'svg' of undefined or null reference ; Zone: angular ; Task: Promise.then ; Value: TypeError: Unable to get property 'svg' of undefined or null reference TypeError: Unable to get property 'svg' of undefined or null reference

The code below will open a new window with the image in firebox, the same error will appear in the console.  but in firefox, no window opens.
let html2canvas = require('html2canvas');

html2canvas($('#test'), {
            onrendered: function(canvas) {
        var img = canvas.toDataURL()
        window.open(img);
            }
        })

**Comment by pareshnagore** [comment]
I'm also facing same issue in Internet Explorer 11. Any solution on this??
