### ISSUE TITLE
text are getting messed up after convert into canvas

### ISSUE THREAD

**Issue by rajkumargaur91** [niklasvh/html2canvas#1103]
I am using some HINDI Lenguage text and when i convert these text into canvas the dashed circles are appearing.
![download](https://cloud.githubusercontent.com/assets/26922385/25053977/472b13c0-2178-11e7-9ca4-7173d4f04e2e.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
