### ISSUE TITLE
Save only what appear inside view any scroll not appear 

### ISSUE THREAD

**Issue by amabdelmongy** [niklasvh/html2canvas#1104]
when the view has scroll and we use style as below 
height: calc(100vh - #{$mat-toolbar-height-desktop}); 

the part of view not appearing inside view that need scroll to show not save

**Comment by alanhg** [comment]
It's a problem.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
