### ISSUE TITLE
html2canvas does not support -webkit-text-stroke?

### ISSUE THREAD

**Issue by jonatanavital** [niklasvh/html2canvas#1108]
I'm using this css:
    -webkit-text-stroke-width: 1px;
    -webkit-text-stroke-color: white;
But it does not render the text with it.
Any ideas?

**Comment by kunal886496** [comment]
He does not care

**Comment by ivictbor** [comment]
Thanks a lot @arzynik , I've published your branch to npm: https://www.npmjs.com/package/html2canvas-stroke , it unblocked https://github.com/devforth/painterro text-stroke feature (though html2canvas-stroke is very updated, probably someone has time capacity to merge a new changes or needs this, poke me)

**Comment by KupinFB** [comment]
Hey, I forked the branch 1.0.0-rc.7 and implemented -webkit-text-stroke-width, -webkit-text-stroke-color, paint-order supporting (based on https://github.com/niklasvh/html2canvas/pull/1540).
Link: https://github.com/KupinFB/html2canvas
Also I've published it to be able to use.
Link: https://www.npmjs.com/package/html2canvas-stroke2
Can i keep it?
