### ISSUE TITLE
why render only what is visible?

### ISSUE THREAD

**Issue by rezagui** [niklasvh/html2canvas#1109]
i'm trying to capture a div but i only get what is visible on screen on that moment, i tried to set the actual size of the div but not working either just render what is visible on screen and fill the rest of the size with blank. any ideas here?

**Comment by Romerski** [comment]
I had a similar problem rendering my gantt chart. Can you show me your code?

**Comment by eKoopmans** [comment]
Hi @rezagui, offscreen rendering is a known issue with html2canvas. My recent pull request #1083 tries to solve that issue. You can try using [this build](https://github.com/eKoopmans/html2canvas/tree/develop/dist) which incorporates that pull request and a few other recent features/bug fixes - I believe it should solve your problem!

**Comment by venanciorodrigo** [comment]
@eKoopmans I still getting the same issue as @rezagui even with your last build `html2canvas.min.js` :(

**Comment by eKoopmans** [comment]
Okay, my first suggestion is to check the element you're using `html2canvas` on - use your browser's inspection tools and make sure that it has the width you expect. One common problem is that your element might be set to have the same width as its parent, so it's getting cut off before `html2canvas` even gets to it. You can see my comment [here](https://github.com/niklasvh/html2canvas/pull/1083#issuecomment-290940110) for a solution to that problem.

If that doesn't help, post a [jsFiddle](https://jsfiddle.net/69kc2t2y/) with some example code that shows the problem. [This link](https://jsfiddle.net/69kc2t2y/) already has the latest `html2canvas` included as an external resource, so all you need to do is put in your HTML/CSS/JS.

**Comment by leftdead7** [comment]
I had a similar issue while developing a cordova app, 
I was using position:fixed in the parent tag and the output image was clipped
Changed the same to position:static and it worked for me .

Thanks for the awesome plugin , really helped me in my hybrid cordova app(IOS specially)
