### ISSUE TITLE
CSS styles broken after export image

### ISSUE THREAD

**Issue by Krish2512** [niklasvh/html2canvas#1110]
Hi,
I have issue in exporting image. After image is exported using html2canvas, css of the page are missing. As a result, UI distortion is happening after we export to jpg. 

I saw workaround in https://github.com/niklasvh/html2canvas/issues/504 which helped to fix the issue. Can someone please suggest if this can be moved as a fix to html2canvas into Git

**Comment by tangshuang** [comment]
I meet the same situation.
#1123 is the same like question.

**Comment by mahadevshindhe** [comment]
I also faced the same problem. Still searching the solution. Is there any library extensions to avoid css issues?

**Comment by tangshuang** [comment]
Well, after researching, I found it is nomal problem dealing with svg text elements font style when using svg as html elements. 
A thinkful sulotion is to convert svg text as html text outside of svg tag and position absolute to make text style work.
Another sulotion is to render svg as image in backend side as a image, when rendering load font files.

**Comment by Xilver266** [comment]
@tangshuang hey, do you have an example about that to solve the problem?

**Comment by tangshuang** [comment]
@Xilver266 it is a large code solution, and impossible to paste my code here. 
You can just follow the idea to try by yourself.

**Comment by mahadevshindhe** [comment]
The solution is to remove the Unicode condition for CSS in canavas2html.js

**Comment by tangshuang** [comment]
@mahadevshindhe Could you please detail your solution?

**Comment by mahadevshindhe** [comment]
@tangshuang 

I am using html2canvas version 0.5.0-alpha1. 
download link https://github.com/niklasvh/html2canvas/releases/download/0.5.0-alpha1/html2canvas.js

Line no 2321 , remove the condition **!hasUnicode(container.node.data)**. I am able to get Unicode text properly. 

var textList = (!this.options.letterRendering || noLetterSpacing(container)) **&& !hasUnicode(container.node.data)** ? getWords(characters) : characters.map(function(character) {
        return window.html2canvas.punycode.ucs2.encode([character]);
    });

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by chulander** [comment]
i'm experiencing this issue

**Comment by Saabertooth** [comment]
I am also experiencing this issue on 1.0.0-alpha.4

**Comment by kv4nt** [comment]
i'm experiencing this issue too

**Comment by mofo-is-guilty** [comment]
alpha 12 shows this issue too...

**Comment by saksham-sg01** [comment]
Why is this closed? I'm still facing this issue in the latest version. Can someone please suggest any fix or workaround they're using?

**Comment by haloriyan** [comment]
it has been 3 years, and still I didn't find solution from this issue

**Comment by KevinCepria** [comment]
Any news on this?

**Comment by raorabi-askus** [comment]
Any Solution?

**Comment by ZeeshanAhmadKhalil** [comment]
For me its adding margin-top to all text itself.

**Comment by iamparthaonline** [comment]
> For me its adding margin-top to all text itself.

was facing the same issue, after breaking my head over this for some time, went with `https://www.npmjs.com/package/dom-to-image-more` package, its producing nice images.
