### ISSUE TITLE
Multiple text shadow support?

### ISSUE THREAD

**Issue by chadananda** [niklasvh/html2canvas#1111]
We seem to have support for multiple text-shadow in the code for a while but I can't figure out how. I have control over the source HTML so I can make changes to get it working.

Here's a fiddle showing my text-shadow being stripped out of the html2canvas result:
https://jsfiddle.net/chadananda/z5fowfrt/5/

**Comment by niklasvh** [comment]
Fixed to some extent in https://github.com/niklasvh/html2canvas/tree/v1.0.0, opacity is not supported on text with text shadows.

**Comment by nicholasgonzalezsc** [comment]
@niklasvh can you link the commit or PR here with the fix?

**Comment by idolizesc** [comment]
@niklasvh I see there are tests for multi text shadow in the pre-1.0.0 code. Was it fixed in this PR? https://github.com/niklasvh/html2canvas/pull/908 Or was there another one? Thanks
