### ISSUE TITLE
html2canvas issue with ckeditor

### ISSUE THREAD

**Issue by sunichand2000** [niklasvh/html2canvas#1113]
I am trying to capture  screenshot of ckeditor .But it is not getting background image.Please give me a solution.

![ckeditor-screenshot](https://cloud.githubusercontent.com/assets/19513274/25606543/9c459046-2f2f-11e7-8cb5-dc22d5760097.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by ajaygrandhi** [comment]
I'm still facing the same issue. Could you please let me know what is the solution or fix for this

<img width="680" alt="image" src="https://github.com/niklasvh/html2canvas/assets/40726736/c6cfc817-c533-4532-8f2b-9e72a4fc809a">
