### ISSUE TITLE
Ellipses in saved converted canvas not displayed correctly

### ISSUE THREAD

**Issue by cbayleyball** [niklasvh/html2canvas#1114]
Hello.  The element that I am trying to capture to a canvas includes ellipses.  These ellipses are created using the HTML figure tag.  When I display the saved canvas, these ellipses are not being displayed correctly.  What is being displayed is a rectangle with rounded corners.  This rectangle seems to be the bounding box around the original ellipse.  What can I do to fix this problem since I need to have actual ellipses saved?  Any help will be greatly appreciated.  Thank you.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by selva-tuva** [comment]
@niklasvh please see this...


http://jsfiddle.net/L3ckmr1a/5/
