### ISSUE TITLE
cdnjs.com: 0.5.0-beta4 is in fact beta3

### ISSUE THREAD

**Issue by alundiak** [niklasvh/html2canvas#1115]
I copied url from https://cdnjs.com/libraries/html2canvas, and not even looked to content.
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.min.js"></script>
```
I play right now with `html2pdf`, and using mentioned above url as dependency I faced with bug ("unexpected black box on white page"). Almost wanted to create PR to @eKoopmans, but then I looked to content of html2canvas.min.js and it's about beta3.

<img width="708" alt="screen shot 2017-05-04 at 02 14 33" src="https://cloud.githubusercontent.com/assets/2131633/25686554/9c6b98fe-306f-11e7-8ccb-f0551e6b7a35.png">
<img width="809" alt="screen shot 2017-05-04 at 02 14 43" src="https://cloud.githubusercontent.com/assets/2131633/25686557/a1b76978-306f-11e7-94a2-a1bfec7d0865.png">

**Comment by eKoopmans** [comment]
Yeah, the file you have **is** 0.5.0-beta4, it's just an incorrect header in the file. You can see in the [commit history](https://github.com/niklasvh/html2canvas/commits/master) that the `0.5.0-beta4` commit updated the version number in `package.json` but didn't update the dist files. Take a look at the current version of [`html2canvas.min.js`](https://github.com/niklasvh/html2canvas/blob/master/dist/html2canvas.min.js), you'll see it still says 0.5.0-beta3, but it's definitely beta4.

There was a [pull request](https://github.com/niklasvh/html2canvas/pull/799) a while ago to update the header in one of the two dist files, but it was closed. If you download the source and build it yourself, you get the correct beta4 version number in dist.

**Comment by alundiak** [comment]
> but didn't update the dist files.

Someone responsible for the module should do this. imho.

**Comment by eKoopmans** [comment]
Yeah probably, you may notice though the latest commit was over a year ago, in January 2016.

**Comment by FlorianLeitgeb** [comment]
I have tried this release where in the header it says "beta 3" and then tried the minified version from eKoopmans html2pdf in the vendor folder, where the header says "beta 4". There is definitely a difference, because when I exchange them, my screenshots only show the viewport with the beta 3 and the "real" beta 4 screenshots render well.

**Comment by eKoopmans** [comment]
Hi @FlorianLeitgeb, the release you've linked is a custom build that I have made *on top* of beta4. You'll notice in the header it says:
`2017-05-13 Custom build by Erik Koopmans, featuring latest bugfixes and features`

The version here, that (accidentally) says beta3 in the header, is in fact the true beta4. I'm sorry if my custom build has caused any confusion.

**Comment by FlorianLeitgeb** [comment]
No problem. But you should really release your custom build as the true beta4 or also as beta5, doesnt matter :D
