### ISSUE TITLE
Such a rubbish library 

### ISSUE THREAD

**Issue by kunal886496** [niklasvh/html2canvas#1117]
It does not support:-
Strike tags
Div dashed or dotted borders
Css line through.

Like are you serious? 
We work for hours and then we get to know such limitations 
Useless you are

**Comment by kunal886496** [comment]
instead of giving thumbs down be a man and give a solution

**Comment by eKoopmans** [comment]
@kunal886496 you are welcome to work toward a solution to the problems you mentioned. This is a big repository with a lot of challenging pieces, it always helps to have more people contributing. As it is, your comments aren't very helpful.

**Comment by niklasvh** [comment]
@kunal886496 next time start by reading the readme so you and your rubbish won't have to waste anyone's time.
