### ISSUE TITLE
canvas to image live url not support in firebase image

### ISSUE THREAD

**Issue by harilalpatel** [niklasvh/html2canvas#1120]
function convertCanvasToImage(canvas) {
        var image = new Image();
        img.crossOrigin = ''; 
        // var canvas=<HTMLCanvasElement>document.getElementById(canvasId);
        image.src = canvas.toDataURL("image/png");
        return image;
      }

      var f = convertCanvasToImage("myCanvas");
      console.log(f); // blank image

**Comment by navclothing** [comment]
@harilalpatel , did you find any solution

**Comment by SalahAdDin** [comment]
I'm looking for a solution yet.
