### ISSUE TITLE
CSS classes not applied to d3 graph in Angular2

### ISSUE THREAD

**Issue by hitesh153** [niklasvh/html2canvas#1123]
Hello
I'm using html2canvas to convert my d3 graph into and image so that it can be downloaded if required in future. However, I'm not able to get the css classes applied to svg, it shows only black color on the image. 
![graph_svg](https://cloud.githubusercontent.com/assets/28588350/25886285/88d0699a-357a-11e7-8021-d42cbd078123.JPG)
![graph_cnvas](https://cloud.githubusercontent.com/assets/28588350/25886299/94ef4bba-357a-11e7-853d-01409792f43f.JPG)

**Comment by tangshuang** [comment]
I meet the same problem.
FYI: window.getComputedStyle
Hope html2canvas to support css.

**Comment by Manaskumar119** [comment]
@niklasvh  why it not resolved yet  ?

**Comment by RacketyWater7** [comment]
why??
