### ISSUE TITLE
Divs overlapping or with Positive Z - index are not rendering correctly in html2Canvas

### ISSUE THREAD

**Issue by sudheer524** [niklasvh/html2canvas#1125]
I have 2 divs over lapping each other with different background font and colors. When I converted the html2image the parent div content is also getting visible with the child div content and content is getting over lapped. Tried with Z-index but no luck. How to handle the Div over div cases in html2canvas.

![image](https://cloud.githubusercontent.com/assets/28654582/26004615/6944cd4c-3704-11e7-9c1b-cec36814a388.png)

I wan the red content which is parent div to be covered by the green content.

**Comment by eKoopmans** [comment]
Hi @sudheer524, I believe overlapping divs should normally be handled correctly. I'd recommend you post a [jsFiddle](https://jsfiddle.net/69kc2t2y/) with example code that illustrates the problem - the jsFiddle link I've included has the current version of html2canvas already attached as an external resource.

**Comment by sudheer524** [comment]
Hi @eKoopmans  

Here is my Js Fiddle linek.

https://jsfiddle.net/69kc2t2y/15/

When clicked on to Image check there is overlapping issue for html content and image generated.

**Comment by sudheer524** [comment]
Hi @eKoopmans 

Intially I used addhtml to download the image to pdf. I have changed my code to use your html2pdf and added z-index to my child div. It got worked. 

Thanks a lot :)

**Comment by eKoopmans** [comment]
Great, you're welcome! Yeah on your initial problem it looks like `z-index` was all you needed. Sorry I couldn't help earlier, it's been a busy few days.

P.S. Looks like your problem is resolved, if it is then don't forget to close it.
