### ISSUE TITLE
Is there any way I can retain a grayscale filter applied to an image?

### ISSUE THREAD

**Issue by JamesDonnelly** [niklasvh/html2canvas#1127]
I've been using this for a while now and I think it's awesome, but I've come across a small issue which I'm hoping there's a simple solution for.

Here is an example of some content which is rendered within my application:

![Example 1](http://i.imgur.com/UvCBUQF.png)

Notice the grayscale effect applied to the second _obtained_ image.

Here's how it looks when rendered through html2canvas:

![Example 2](http://i.imgur.com/nOzhXoy.png)

Notice how the grayscale effect isn't applied any more?

The effect is applied with:

```css
-webkit-filter: grayscale(100%);
filter: grayscale(100%);
```

Is there any way I can retain this grayscale effect?

**Comment by JamesDonnelly** [comment]
I've created a CodePen example of this in action: https://codepen.io/inb4/pen/LyBLeq.

## Code
```html
<figure class="grayscale"></figure>
```
```css
.grayscale {
  -webkit-filter: grayscale(100%);
  filter: grayscale(100%);
}
```
```javascript
html2canvas(..., {
  allowTaint: true
});
```

## Output
![Image](http://i.imgur.com/LkiC3fX.png)

**Comment by eKoopmans** [comment]
Hi @JamesDonnelly, html2canvas doesn't currently support the `filter` CSS. Support for each feature has to be coded individually, and it looks like [`filter`](https://developer.mozilla.org/en/docs/Web/CSS/filter?v=example) has a lot of pieces and not great browser support, so unless an ambitious coder feels up to the challenge, I don't expect it will be supported in the near future.

**Comment by niklasvh** [comment]
Closing in favor of #493

**Comment by cyan33** [comment]
I wrote a small library which resolves this issue, hope it helps:
https://github.com/cyan33/image-screenshot
