### ISSUE TITLE
 blurry canvas  in IE

### ISSUE THREAD

**Issue by liuning108** [niklasvh/html2canvas#1129]
blurry canvas  in IE
![image](https://cloud.githubusercontent.com/assets/1883206/26233532/a58291fe-3c90-11e7-9fc3-764dec8af3c3.png)

how to solve?

**Comment by eKoopmans** [comment]
Hi @liuning108, I'm not sure about your specific case, but you could take a look at #576 for some solutions to blurry images. There's also #1087 to increase the resolution of the image, but I don't think that would solve your problem.
