### ISSUE TITLE
Could you provide a version without Promise?

### ISSUE THREAD

**Issue by tangshuang** [niklasvh/html2canvas#1131]
I do not know why html2canvas use Promise to return canvas. Canvas is supported in IE9, however Promise is not. Is it necessary to use Promise?
Maybe I request to much, but could you provide a version without Promise?

**Comment by eKoopmans** [comment]
Hi @tangshuang, html2canvas also uses promises internally (not just when returning the canvas), so unfortunately there's no avoiding them. In [the readme](https://github.com/niklasvh/html2canvas#usage) you'll see that to support older browsers you will need to include a Promise polyfill like [es6-polyfill](https://github.com/jakearchibald/es6-promise) before including html2canvas.

**Comment by tangshuang** [comment]
Thanks, I have seen this.
