### ISSUE TITLE
Rendering error for background images in Edge

### ISSUE THREAD

**Issue by Regicollis** [niklasvh/html2canvas#1137]
I have a series of divs with background images on a :before and an :after pseudo-class. The css is as follows:
```
.sticker .background:after {
	content: '';
	height: 60px;
	width: 100%;
	position: absolute;
	bottom: -60px;
        background-image: url(someImage);
	background-size: 100% 60px;
	background-position: bottom;
	-webkit-transition: 0.3s ease;
		-ms-transition: 0.3s ease;
			transition: 0.3s ease;
}
```
When viewed as HTML in Microsoft Edge the site looks like this
![expected](https://cloud.githubusercontent.com/assets/10154582/26671860/5279f584-46b7-11e7-98c7-18d3a4514f83.jpg)
But html2canvas gives this output in Microsoft Edge
![output](https://cloud.githubusercontent.com/assets/10154582/26671899/6b54ccb4-46b7-11e7-9296-890088a8a8ac.jpg)
The positioning of background images is completely off.
This is an issue with Edge only. The plugin works as expected in Chrome and Firefox. Can I do something to fix this error?

**Comment by niklasvh** [comment]
Could you show an example on jsfiddle?
