### ISSUE TITLE
Please publish version 0.4.1 to npm

### ISSUE THREAD

**Issue by SatoshiKawabata** [niklasvh/html2canvas#1143]
@niklasvh 
I met this problem that `word-wrap` isn't working. #664 [As this comment](https://github.com/niklasvh/html2canvas/issues/664#issuecomment-167440913), this is resolved to use version `0.4.1`.

I want to use it by npm. Please publish `0.4.1` to npm.

**Comment by gelinger777** [comment]
I can confirm that on latest beta the word-wrap:break-word is not working. Please could you patch the current beta to fix this?

**Comment by SatoshiKawabata** [comment]
@gelinger777 Do you confirm that  the `word-wrap:break-word` is working at `v0.4.1`? Do you know how to realize `word-wrap:break-word` in `v0.4.1`? I don't know that.

**Comment by gelinger777** [comment]
in v0.4.1 it works .  You can load  it from cdn instead of npm install. Just include the old lib from the cdnjs and you are ready to go. But v0.4.1 has not support for making screenshots of svg objects. They just get  disappear from the shots.

**Comment by SatoshiKawabata** [comment]
I resolved it by another way. I implemented word-wrap by myself. Thanks.
