### ISSUE TITLE
Browser crash when trying to convert html + svg to scaled image

### ISSUE THREAD

**Issue by tanzid203** [niklasvh/html2canvas#1145]
![image](https://user-images.githubusercontent.com/13332775/27115194-a1b46d4e-50e6-11e7-853a-a7d8354442f4.png)

I am using [Treant.js](http://fperucic.github.io/treant-js/) javascript library to create an organisational chart. 
I used the following code to convert the SVG elements (the lines that connect the boxes) and HTML contents (the boxes):

```
	var useWidth = $( '#orgchart' ).prop( 'scrollWidth' ); 
	var useHeight = $( '#orgchart' ).prop( 'scrollHeight' ); 

	var scaleBy = 5;

	var w = useWidth;
	var h = useHeight;
	var scaledCanvas = document.createElement( 'canvas' );
	scaledCanvas.width = w * scaleBy;
	scaledCanvas.height = h * scaleBy;
	var scaledContext = scaledCanvas.getContext( '2d' );
	scaledContext.scale( scaleBy, scaleBy );

	html2canvas( $( "#orgchart" ), {
		canvas : scaledCanvas,
		logging : false,
		onrendered : function ( canvas ) {

			$( "#orgChartSketchDivBody" ).html( "<canvaS id=\"orgChartSketch\"></canvas>" );

			var sketchCanvas = document.getElementById( 'orgChartSketch' );
			var sketchContext = sketchCanvas.getContext( '2d' );
			sketchCanvas.width = w * scaleBy;
			sketchCanvas.height = h * scaleBy;
			sketchContext.drawImage( canvas, 0, 0 );
			sketchContext.scale( ( w * scaleBy ) / ( h * scaleBy ), ( w * scaleBy ) / ( h * scaleBy ) );

			var imgData = sketchCanvas.toDataURL( 'image/png' );
			}
	} );
```
This works fine as long as the chart is small. But for large charts, when rendered, the browser freezes and crashes (I am using latest Chrome). I know the scale value 5 is high, but I need high quality images so as to get readable images of large charts. Is there any solution to stop the browser from crashing?

**Comment by eKoopmans** [comment]
Hi @tanzid203, looking at your code I'm a bit confused why you've created `sketchCanvas`. If your goal is to get `imgData`, you can use `.toDataURL()` directly on the canvas given by the `onrendered` function. Also, your final scale could simplify to `sketchContext.scale(w/h, w/h)`, though I'm not sure the purpose of that scale, since it only affects drawing done on it after the scale.

Other than that, I'm not sure about your performance issues, sorry!

**Comment by tanzid203** [comment]
@eKoopmans Thank buddy. That `sketchCanvas` bit of code was unnecessary. I was trying to achieve something with that sketchCanvas way long back. Forgot to remove that code.
 I will try the `sketchContext.scale(w/h, w/h)` bit and will let you know the results!

**Comment by ashitvora** [comment]
@eKoopmans 
I'm trying to do something similar.
My DOM element is of smaller size but I want final image to be of size 1280x720.
If I pass width and height property to html2canvas options, it doesn't stretch the DOM content and hence image is not in proportion to what user sees on the page.

The argument passed to onrendered does not have "scale" method on it to scale the canvas before exporting an image from it.

Any idea how to get the image of 1280x720 even if DOM element is smaller?

**Comment by eKoopmans** [comment]
Hi @ashitvora! If you try out the scale/dpi feature I submitted in #1087 (or grab [this build](https://github.com/eKoopmans/html2canvas/tree/develop/dist) which has that feature and a few others merged in), then you can pass a `scale` option to html2canvas.

What that does is creates a higher-resolution canvas, which is in fact just a larger canvas that has been scaled down (with CSS) to appear smaller. If you use `.toDataURL()` on that canvas, it will create a larger image, by whatever scale you specified. Right now you can only specify one scale for horizontal/vertical, so the aspect ratio will need to stay the same, but it should get you a larger image!

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
