### ISSUE TITLE
Fails when document already has canvas

### ISSUE THREAD

**Issue by atodd-geoplan** [niklasvh/html2canvas#1148]
```
function labelCanvasElements(ownerDocument) {
    [].slice.call(ownerDocument.querySelectorAll("canvas"), 0).forEach(function(canvas) {
        canvas.setAttribute(html2canvasCanvasCloneAttribute, "canvas-" + html2canvasCanvasCloneIndex++);
    });
}
```

requires a selector  - if the html document already has canvas elements this function includes and ultimately tries to write it to the new canvas.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
