### ISSUE TITLE
How to store the rendered image from canvas ?

### ISSUE THREAD

**Issue by mrsrinivas** [niklasvh/html2canvas#115]
Hi niklasvh,
 I am developing a website on PHP(Codeigniter). In that i am using html2canvas tool to capture screen shot of a website. Its working fine. But need to to store the image in my web server ?

Is it possible with this tool?

**Comment by deb54** [comment]
I have used your code. It shows:
Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at http://localhost/Blog/:313:24
    at <anonymous>

**Comment by eKoopmans** [comment]
Hi @deb54, "tainted canvases" are a result of [cross-domain images](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image). For Internet security reasons, trying to use an image from a different domain in a canvas causes problems. There are two html2canvas options, useCORS and proxy, which are designed to try to get around that problem. They're not perfect solutions though - you can read more over at #951 and #592.

**Comment by deb54** [comment]
Thanks, eKoopmans. Actually, me trying to save the total div as an image. Now I have faced two new problems, after converting Html to canvas the image size is fixed, i can't resize the canvas, if I resize then it appears blank.

**Comment by Mvhd** [comment]
Hi all, storing canvas.toDataUrl() in CodeIgniter:

Jquery, Ajax, download [htm2canvas.min.js](https://html2canvas.hertzen.com/)

      ```
  html2canvas($('#targetDiv')[0]).then(function(canvas) {
            var dataUrl = canvas.toDataURL();
            var newDataURL = dataUrl.replace(/^data:image\/png/, "data:application/octet-stream"); //do this to clean the url.
            $("#saveBtn").attr("download", "your_pic_name.png").attr("href", newDataURL); //incase you want to create a download link to save the pic locally.
      
        $.ajax({
            'type': 'post',
            'url': 'link_to_function_in_controller',
            data: {
                //you can more data here
                'img':newDataURL
            },
            success: function(data){
                console.log(data);
            },
            error: function(data){
                console.log(data);
            }
        });
        
        });


// in your codeigniter controller
            $img = $this->input->post('img'); //get the image string from ajax post
            $img = substr(explode(";",$img)[1], 7); //this extract the exact image
            $target=time().'_img.png'; //rename the image by time
            $image = file_put_contents($_SERVER['DOCUMENT_ROOT'].'/imagefolder/'.$target, base64_decode($img)); //put the image where your image folder directory is located
            
            $data = array(
                'Image' => $target, //note you can add more data
                'date_inserted' => mdate('%Y-%m-%d %H:%i:%s', now())
            );
            
            $result = $this->model_image->post_image($data); //post_image() here should be your function in codeigniter model layer that handles the database, while the model_image is the model name itself where post_image() draws its properties from
            
```
