### ISSUE TITLE
Generated Image with bug on circle edge, not render properly as on page.

### ISSUE THREAD

**Issue by tejastank** [niklasvh/html2canvas#1150]
Orginial page where cirlce show properly.

![arm s reach clear-vue co-sleeper review babygearspot best baby product reviews](https://user-images.githubusercontent.com/311413/27474715-66b5bdc4-5820-11e7-9481-491bc46dc34e.png)

When use lib and generate output will break the circle.

![issue-report](https://user-images.githubusercontent.com/311413/27474829-c42c91da-5820-11e7-9c12-1af29a3b9d91.png)

Everthing great with page but only issue with generated image.

Kinldy guide how to resolve this or patch the issue quicker.

**Comment by niklasvh** [comment]
Should be fixed in 1.0.0

**Comment by tejastank** [comment]
Not yet, same problem with new version
