### ISSUE TITLE
Became very laggy after rendered multiple times

### ISSUE THREAD

**Issue by Raolibec** [niklasvh/html2canvas#1156]
this is my way to use html2canvas
there is a container which i want to put the thumbnail in;
i cloned the content(not pure text) into the container (to solve the off-screen rendering) and scale it  smaller width css(transform:scale)
then i use html2canvas to get the canvas.todataurl (png)  and save the  image data to my session object.
after this i remove the cloned content and append a <img> tag with dataurl to  the box .

the performance is good rendering second  thumbnail ;
but it become very laggy after rendered about 5 times, not the browser,even the computer.
is there any problems in this way?or just the lib have no performance optimization?

here is my code : 

`                            $('#thumbnail_'+e+' div').append(pnid(e).html());//clone the element
                            html2canvas($('#thumbnail_'+e+' .toe_res'),{width:f*8,height:f*8}).then(function (canvas) {
                                $('#thumbnail_' + e +' .crs_bmk_tmb').append('<img src="'+(session.config.book[e].image=canvas.toDataURL('image/png'))+'">').find('.toe_res').remove();//append the img and remove the cloned element
                            });
`

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
