### ISSUE TITLE
Element node is missing

### ISSUE THREAD

**Issue by moonbreezee** [niklasvh/html2canvas#1157]
# Element node is missing
Hello, I have a problem, that is, in the use of plug-ins (version: 0.5.0-beta3) when the page generated by the process of the picture, there will be some elements of the node is missing, and each loss is not the same location. The page is made up of an element node that is dynamically added by an underlying image and js.
## The code is as follows:
`    // html转图片
    function cutPageAndSave(targetElement,pageHeight,left,top,width,height,imgName){
        var $myDatePick = $($("body > div")[2]).remove(); // myDatePick移除，不然会出问题
        var pageWidth = width;// 设置生成图片的宽度，高度需要配置        
        // html生成图片并且把结果图片传给drawImage组合图片
        console.log(targetElement);

        function htmlToCanvas() {
            // $(targetElement).scrollTop(0);            
            html2canvas(targetElement, { 
                allowTaint : true,              
                onrendered: function(canvas) {            
                    var dataUrl = canvas.toDataURL(); 
                    var newImg = document.createElement("img");  
                    newImg.src =  dataUrl;
                    newImg.onload = function(){
                        // debugger
                        // The picture saved here is missing
                        saveFile(dataUrl,'123.png')
                        drawImage(newImg);
                    }
                },
                // 生成的图片宽高
                width: pageWidth, 
                height: pageHeight
            });
        }   `
### The resulting picture is like this
![image](https://user-images.githubusercontent.com/9795348/27848095-16b50c7c-6175-11e7-9b84-c18cb25a2255.png)
### code as follow
![image](https://user-images.githubusercontent.com/9795348/27848163-b37e7278-6175-11e7-9cbb-870cdd81b613.png)

### The original html is like this
![image](https://user-images.githubusercontent.com/9795348/27848184-d19b4f4c-6175-11e7-8ba1-d3f7b76154bb.png)

Who can help look at， thank you

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
