### ISSUE TITLE
Problem with ckeditor RichFaces on chrome

### ISSUE THREAD

**Issue by micheltlutz** [niklasvh/html2canvas#1159]
I'm using the html2canvas version 0.5.0-beta3

This is the system screen
![captura de tela de 2017-07-06 11-14-02](https://user-images.githubusercontent.com/536630/27915351-6a8957e6-623c-11e7-84f9-cc46fdfaa42d.png)

When I print it stays like this
![captura de tela de 2017-07-06 11-14-31](https://user-images.githubusercontent.com/536630/27915352-6a8dd582-623c-11e7-9b00-7f2b80306639.png)

Removing case "IFRAME" from line 1246 ImageLoader.prototype.findImages print gets better but the iframe content does not appear

![captura de tela de 2017-07-06 11-15-18](https://user-images.githubusercontent.com/536630/27915353-6a9d5c8c-623c-11e7-83d2-c02467afd35a.png)

I've tried to enable useCORS and allowTaint but unsuccessfully

Any tips on what I can do?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
