### ISSUE TITLE
css clip-path not rendered

### ISSUE THREAD

**Issue by abdullahknz** [niklasvh/html2canvas#1160]
`<img id="image" style="width: 100%; height: auto; clip-path: polygon(141px 0px, 67px 78px, 100px 300px, 290px 286px, 355px 60px, 336px 12px);" ng-reflect-src="assets/images/placeholder.png" src="assets/images/placeholder.png">` 

I want render image to canvas but clip-path css is not rendering

**Comment by niklasvh** [comment]
Clip paths aren't currently supported.

**Comment by olivermen** [comment]
I have the same issue.
