### ISSUE TITLE
html2canvas is not working after clearing the browser history

### ISSUE THREAD

**Issue by ZTAP0011** [niklasvh/html2canvas#1163]
I used html2canvas in creating a png image and then export it to pdf. It works fine unitll I clear the history. But html2canvas is not working after clearing the browser history. I debug it and find that It stops on this line
container.contentWindow.onload = container.onload = function () {
                var interval = setInterval(function () {
                    if (documentClone.body.childNodes.length > 0) {
                        cloneCanvasContents(ownerDocument, documentClone);
                        clearInterval(interval);
                        if (options.type === "view") {
                            container.contentWindow.scrollTo(x, y);
                        }
                        resolve(container);
                    }
                }, 50);
            };

The onload function is not called, i.e. iframe onload event is not fired after clearing he history.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
