### ISSUE TITLE
How can I set the background colour to transparent?

### ISSUE THREAD

**Issue by ZTAP0011** [niklasvh/html2canvas#1164]
After setting the background in options to #ffffff, the colour of my canvas is white, it is okay, but the remaining area other than canvas image is transparent, how can I set that remaining area also to a colour e.g a white colour?

**Comment by niklasvh** [comment]
Still an issue in 1.0.0 https://jsfiddle.net/m0fk6mme/

**Comment by niklasvh** [comment]
You can set `backgroundColor` to `null`

**Comment by iamgoodbytes** [comment]
Here, changing the backgroundColor option has effect, but changing it to null creates a black background in the canvas, while there's no black background in my CSS.

**Comment by LeeDavidPriest** [comment]
I am also getting the canvas render a black background when setting backgroundColor to null

**Comment by weekitmo** [comment]
`html2canvas(canvasDom, {
        allowTaint: true,
        useCORS: true,
        backgroundColor: "rgba(0,0,0,0)",
        removeContainer: true,
        x: 0,
        y: 0,
        width: 374,
        height: 722
      })`

**Comment by am-awais** [comment]
`allowTaint: true` with `backgroundColor: "rgba(0,0,0,0)"` Solved the problem

**Comment by Pawel-Janik** [comment]
I don't think `allowTaint` helps in any way with this issue. For me 
`        
backgroundColor: 'rgba(0, 0, 0, 0)',
removeContainer: true,
`
settings were the ones needed.

**Comment by saransh0730** [comment]
How can I show my background image in the screenshot? The screenshot that it captures shows bg white. I've tried all the options for it, please suggest other libraries or something. The image is stored in my public folder of reactJS app and I've used backgroundImage tag in the body{}

**Comment by Rohit02Jaiswal** [comment]
![image](https://github.com/user-attachments/assets/5899757b-19ae-4ae7-92ab-ab706534ed9d)


I have tried all the above options but still getting black background color.


![image](https://github.com/user-attachments/assets/e915820a-f2f2-4e95-9d4e-78a2beb38df1)
