### ISSUE TITLE
Render off-screen elements

### ISSUE THREAD

**Issue by itsravenous** [niklasvh/html2canvas#117]
First - thanks for your hard work - this is an extremely useful library :)

I'm looking to render an offscreen element onto canvas, but this just results in a blank image. I assume this is because html2canvas renders the whole (visible) page and then crops down to the specified element, meaning anything that's outside the page boundaries is missed.

I suspect this requires a rewrite of how html2canvas handles rendering a specific element as opposed to the whole page, so I appreciate it's a big ask.

Cheers
Tom

**Comment by ejlocop** [comment]
hi im facing the same problem, but the above solution didnt work for me..
i have a scrollable div content and i want to capture the whole content. not the one in the viewport only.. can someone help me ?

**Comment by ejlocop** [comment]
![1](https://cloud.githubusercontent.com/assets/12082880/7411159/dbff7e7c-ef67-11e4-92f0-62e7a39e759e.jpg)
![2](https://cloud.githubusercontent.com/assets/12082880/7411160/dc685348-ef67-11e4-9fe4-4910d5f94337.jpg)

why is mine is like this ? T_T

**Comment by eworksmedia** [comment]
We solved this by changing line 604 from 
```
return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {
```
to
```
return renderDocument(node.ownerDocument, options, options.width != undefined ? options.width : node.ownerDocument.defaultView.innerWidth, options.height != undefined ? options.height : node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {
```
Basically force it to respect the width/height arguments set during setup rather than getting the viewable area according to the document.. No weird positioning hacks necessary..

**Comment by ioRekz** [comment]
Hello, I'm trying to render an element that is offscreen (need to scroll to see it). 
Should it work or I need to tweak some things ?

**Comment by btm1** [comment]
+1 this is the issue i'm having

**Comment by jhitchcock** [comment]
@eworksmedia solution above worked for me. Great stuff thanks

**Comment by jordan314** [comment]
I had to put my canvas in an iframe, run html2canvas inside the iframe, run toDataURL(), and pass the image back to the parent.

**Comment by OscarAgreda** [comment]
@eworksmedia
Thank you , good code. works like a charm.

**Comment by gregoryduckworth** [comment]
@eworksmedia your fix worked for me as well.

**Comment by Trexology** [comment]
@eworksmedia MAGIC! it works perfectly!!

**Comment by codebyuma** [comment]
Is the fix that @eworksmedia mentioned (to line 604) in any of the available releases? Or is this a manual change everyone's making to get this to work?

**Comment by gururajmca** [comment]
Thanks @eworksmedia for solution, I am able to see the canvas getting rendered, but it's very small in size, I have tried giving width and height params but still image is very small, is there any way we could scale the image?

**Comment by gururajmca** [comment]
@codebyuma this change we need to update manually.

**Comment by AlexGrump** [comment]
My fix is strange, but it work
`.html2canvas-container {
	width: 3000px !important;
	height: 3000px !important;
}`

**Comment by Brieg** [comment]
+1

**Comment by Romerski** [comment]
@eworksmedia I can not find that code in my html2canvas.js. Where is it?

**Comment by Romerski** [comment]
@eworksmedia not working for me :( Still not rendering off-screen width gantt chart who im wanting to render.

**Comment by gururajmca** [comment]
@Romerski make sure your container is set  visibility: visible;

**Comment by Romerski** [comment]
@gururajmca thanks but still not working :( Here is an image: http://i.imgur.com/EE8GyHD.png

Green: Popup when I click print button on Gantt chart.
Blue: HTML gantt chart who I want to render.
Red: What is rendering html2canvas from html (only screen visible part of html)

Canvas is rendering inside a div with visibility and overflow set to 'visible'.

Thanks again!!

**Comment by gururajmca** [comment]
@Romerski  Can you try this one, which worked me.

//Default  css 
#hidden_div {
    display: none;
    visibility: hidden;
    position: absolute;
    top: 0;
    left: 0;
}


function HtmltoImage() {
    $('#hidden_div').css("display" , "block");
    $('#hidden_div').css("visibility" , "visible");
    
    var defer = $q.defer();
    html2canvas($('#hidden_div'), 
    {
        useCORS: true,
        allowTaint: true,
        letterRendering: true,
        logging:true,
        onrendered: function (canvas) {
            $('#hidden_div').css("overflow" , "hidden");
            var quality =[0.0,1.0];
            img = canvas.toDataURL('image/png',quality);
            var data = {
                "pngdata" : img,
            };
            defer.resolve(data);
        }
    });
    return defer.promise;
}

**Comment by Romerski** [comment]
@gururajmca thanks for your help but unfortunately still not working... I have no problem with the height, is rendering well but the problem is with the width, which is not rendering off-screen width of gantt chart.

Appreciate it any help.

**Comment by battlesteel** [comment]
@eworksmedia solution didn't work for me.

I fixed mine with this code.

```
function generateToPdf(element, fileName, method) {
    var c = document.getElementById(element);
    // overwrite owner doc inner height with your div clientHeight
    c.ownerDocument.defaultView.innerHeight = c.clientHeight;
    c.ownerDocument.defaultView.innerWidth = c.clientWidth;
    if (method === 'canvas') {
        html2canvas(c, {
            onrendered: function (canvas) {
                document.body.appendChild(canvas);
                // scale paper height based on ratio new canvas height and width
                var paperHeight = 210 * (canvas.height / canvas.width);
                var paperFormatInMm = [210, paperHeight];
                var doc = new jsPDF('p', 'mm', paperFormatInMm);
                doc.addImage(canvas, 'PNG', 2, 2);
                doc.save(fileName + '.pdf');
            }
        });
    }
}
```

**Comment by wotomas** [comment]
Its a closed issue, but some people like me could searching for the same issue, so i'll just add an comment in here. Solution as suggested by @eworksmedia, I created an npm module for personal use, but feel free use.
```
npm install --save html2canvas-render-offscreen
```
and use it just like html2canvas

**Comment by baylock** [comment]
I'm not a developper or anything but I had the same issue and none of your  fixes worked for me.
But then I tried something very simple: instead of putting the container off screen, I just "z-indexed" it below everything else.
This way, it was technically on screen for the script to work, even though it was not visible to the final user.
I'm pretty sure there are some side effects to this, according to your own layout but in my case, it worked just fine.

**Comment by rickli1989** [comment]
@eworksmedia You are legend !!!!!!

**Comment by DougHenrique** [comment]
The solution below worked for me, but it works only in the web browser, if I try to download the pdf through the mobile application (using WebView) does not work, someone else has gone through something similar and know a way to correct?

Note: sorry my English I am using Google Translate

**Comment by foxhehehe** [comment]
@battlesteel Your solution worked for me, others didn't
> 
> 
> @eworksmedia solution didn't work for me.
> 
> I fixed mine with this code.
> 
> ```
> function generateToPdf(element, fileName, method) {
>     var c = document.getElementById(element);
>     // overwrite owner doc inner height with your div clientHeight
>     c.ownerDocument.defaultView.innerHeight = c.clientHeight;
>     c.ownerDocument.defaultView.innerWidth = c.clientWidth;
>     if (method === 'canvas') {
>         html2canvas(c, {
>             onrendered: function (canvas) {
>                 document.body.appendChild(canvas);
>                 // scale paper height based on ratio new canvas height and width
>                 var paperHeight = 210 * (canvas.height / canvas.width);
>                 var paperFormatInMm = [210, paperHeight];
>                 var doc = new jsPDF('p', 'mm', paperFormatInMm);
>                 doc.addImage(canvas, 'PNG', 2, 2);
>                 doc.save(fileName + '.pdf');
>             }
>         });
>     }
> }
> ```

**Comment by andylighthouse** [comment]
> We solved this by changing line 604 from
> 
> ```
> return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {
> ```
> 
> to
> 
> ```
> return renderDocument(node.ownerDocument, options, options.width != undefined ? options.width : node.ownerDocument.defaultView.innerWidth, options.height != undefined ? options.height : node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {
> ```
> 
> Basically force it to respect the width/height arguments set during setup rather than getting the viewable area according to the document.. No weird positioning hacks necessary..

What is line 604? can you give some context? I can't find line 604 anywhere

**Comment by andreasvirkus** [comment]
@andylighthouse see 5 comments above: https://github.com/niklasvh/html2canvas/issues/117#issuecomment-323076300

**Comment by ProteanDev** [comment]
Still having this issue

**Comment by jeffg2k** [comment]
Was having this issue still on version 1.0.0-rc.7.  My element to convert is at the top of the page.  If html2canvas is run when the user has scrolled down, it would crop the top of the image off.  I tried @wotomas / @eworksmedia solution and while it fixed the cropping, the captured text was improperly positioned (as if it was forced down similar to the crop).  `window.scrollTo(0, 0)` did the trick, but I didn't want to jump the user back up to the top.  @AlexGrump's solution did worked for me, but I modified it a little bit. Not sure if creating a 3000x3000 canvas creates any extra lifting or not, but I just decided to try and grab what scrollable space was accessible.  I currently running this before calling html2canvas.
```
  $(".html2canvas-container").css("height", document.documentElement.scrollHeight + "px !important");
  $(".html2canvas-container").css("width", document.documentElement.scrollWidth + "px !important");
```

Honestly, I'd like to get the entire thing working without any visibility as I'm using it in an Electron app, generating thumbnail images on the fly based on changes made.

**Comment by HenrijsS** [comment]
This has been an issue for 6-8 years and still isn't fixed. 
Gosh. There are multiple solutions posted above. Why aren't they being implemented?

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });
