### ISSUE TITLE
html2canvas can not display Svg and Path tags of jsPlumb plugin

### ISSUE THREAD

**Issue by salehmosleh** [niklasvh/html2canvas#1179]
here is real image : 
![real image](https://user-images.githubusercontent.com/3959998/28960018-2ec0b122-7912-11e7-9369-204b7739e0b8.JPG)

and here is html2canvas capture : 
![html2canvas capture](https://user-images.githubusercontent.com/3959998/28960068-6de85a6c-7912-11e7-9fa5-d2e86e0d6653.jpg)
 
here is html codes of Svg and Path tags that html2canvas can not display it : 
![codes of path](https://user-images.githubusercontent.com/3959998/28960169-d3288fd2-7912-11e7-992d-f7663bdad293.JPG)

**Comment by davloperez** [comment]
Hi @salehmosleh , I wrote a post about this problem in my blog: http://eatandcode.es/2017/08/12/Soluciones-a-la-captura-de-svg-con-html2canvas/ 
It is in spanish, but it provides you a workaround to get nice Svg image from JsPlumb.
I hope it is useful for you!

**Comment by BobLuo** [comment]
Pls review https://github.com/niklasvh/html2canvas/issues/95, similar issue.

include extrenal library:
[https://github.com/canvg/canvg](url)

combine @gifarangw, @steren and @remiremi solution, my solutin as below:

```javascript
function take_second(targetElem){
    // First render all SVGs to canvases
    var elements = targetElem.find('svg').map(function() {
        var svg = $(this);
        var canvas = $('<canvas></canvas>').css({position: 'absolute', left:svg.css('left'), top: svg.css('top')});

        svg.replaceWith(canvas);

        // Get the raw SVG string and curate it
        var content = svg.wrap('<p></p>').parent().html();
        svg.unwrap();

        canvg(canvas[0], content);

        return {
            svg: svg,
            canvas: canvas
        };
    });

    // At this point the container has no SVG, it only has HTML and Canvases.
    html2canvas(targetElem[0], {
      onrendered: function(canvas) {
          // Put the SVGs back in place
          elements.each(function() {
              this.canvas.replaceWith(this.svg);
          });

          $("#previewImage").append(canvas);
      }
    });
}
```

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by mhlm71** [comment]
> 
> 
> Hi @salehmosleh , I wrote a post about this problem in my blog: http://eatandcode.es/2017/08/12/Soluciones-a-la-captura-de-svg-con-html2canvas/
> It is in spanish, but it provides you a workaround to get nice Svg image from JsPlumb.
> I hope it is useful for you!

[Here ](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Featandcode.es%2F2017%2F08%2F12%2FSoluciones-a-la-captura-de-svg-con-html2canvas&edit-text=) is that article in English language, thanks to google translator.

**Comment by LanjianNUll** [comment]
> Hi @salehmosleh , I wrote a post about this problem in my blog: http://eatandcode.es/2017/08/12/Soluciones-a-la-captura-de-svg-con-html2canvas/
> It is in spanish, but it provides you a workaround to get nice Svg image from JsPlumb.
> I hope it is useful for you!

Thank you very much, I have already solved it. After reading your blog, I found the problem that svg has absolute positioning. Thanks again!
Also, cite your blog post (google translation)

> SVG positioning is not absolute. If you have a SVG with an absolute location
Elements cannot be drawn correctly using html2canvas. To fix this, you
You can wrap SVG elements with absolute positioning <span> (copy the top of the SVG,
Position the bottom, left or right) and remove the SVG position: absolute, top, bottom,
The style corresponding to the left side or he has. To wrap SVG, you can use jQuery's .wrap() function to help them.

I hope I can help others, thank you again. @mhlm71
