### ISSUE TITLE
When image too large, base64 code run in parseBackgrounds will crash

### ISSUE THREAD

**Issue by bruce1i** [niklasvh/html2canvas#1182]
I have a problem that div's background-image with base64(convert from Image bigger than 1.5M+) will crash in parseBackgrounds function.

Because the code 'backgroundImage.split("").forEach(function(c) {' do many loop(> 20998621 times). This let memory rise up quickly and crash(memory usage > 3G).

I want to know what does parseBackgrounds to do? And can I simplify the code do less loop?

**Comment by niklasvh** [comment]
It is used to parse the background images, which could be multiple images, gradients etc. Considering your example, there probably needs to be some improvements on how its performed. 

If you never use gradients or multiple background images, you could simplify that to just return a single image directly.
