### ISSUE TITLE
“Error: SecurityError: The operation is insecure” in Firefox Extension- html2canvas.js

### ISSUE THREAD

**Issue by angelovstanton** [niklasvh/html2canvas#1184]
Hi,

I read the FAQ and I know your opinion that you believe that your library shouldn't be used in extensions. However, I want to integrate it for UI testing with WebDriver and it will be quite useful if the script is loaded in extension. I created the extension and it is working in Chrome and Edge. However, there is some kind of security issue in Firefox. You can check the detailed info[ here](https://stackoverflow.com/questions/45569771/error-securityerror-the-operation-is-insecure-in-firefox-extension-html2can):
**Any help will be much appreciated!**

This is the error stacktrace:

createWindowClone/<@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/html2canvas.js:754:13
createWindowClone@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/html2canvas.js:732:16
renderDocument@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/html2canvas.js:616:16
window.html2canvas@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/html2canvas.js:603:16
@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/html2canvas.js:3386:20
@jar:file:///C://TestExetensions/InjectJsExtensionMessagingFirefox/injects.xpi!/contentScript.js:2:3

**Comment by niklasvh** [comment]
Without addressing the issue you have with html2canvas, out of curiosity why aren't you using the webdriver screenshot capability or the extension native grab screenshot capabilities which would actually produce real screenshots?

**Comment by angelovstanton** [comment]
I forgot to mention it in my post. I started to research html2canvas because the WebDriver native support for screenshots captures only the visible part of the tabs which makes them completely useless. It is working only in IE. 
About the extension native grab, I initially created an extension for Chrome. I researched lots of API methods, and I found two methods **captureVisibleTab** and **chrome.tabCapture.capture**. However, as far as I found out they capture only the visible part of the tabs, not the full page.

If you know some other ways, I will be thrilled if you can share them with me.

These are the two methods:
[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab)
[https://developer.chrome.com/extensions/tabCapture](https://developer.chrome.com/extensions/tabCapture)

**Comment by SudDevPP** [comment]
@angelovstanton  have you extended module on your firefox installation ? Like ghostery or add block plus or other ? 
Because i'have the "Error: SecurityError: The operation is insecure" when ghostery module was enabled and when i disabled this the html2canvas code work great. 
It's can be a way .

**Comment by angelovstanton** [comment]
I should try, Thanks.

**Comment by valdaiko** [comment]
It's a Ghostery issue. Adding site to trusted doesn't help. Works only if total disable Ghostry.

**Comment by dvalter** [comment]
I have the same issue trying to port [TheGreatSuspender](https://github.com/deanoemcke/thegreatsuspender) to Firefox. In my case it's clearly not related to Ghostery, any kind of Ad Blocker or togglable tracking protection because I have none.

By the way actual cause is `documentClone.open();` at `DocumentCloner`, which seem to fail for some unknown reason.

**Comment by dvalter** [comment]
According to response on [Mozilla's #1613779](https://bugzilla.mozilla.org/show_bug.cgi?id=1613779), there's sort of workaround to this bug: 
using `documentClone.wrappedJSObject.open()` instead of `documentClone.open()`.

It works for me this way, but I hope it'll be fixed by Mozilla eventually.
