### ISSUE TITLE
When "background: url ()" is included, "toDataURL ()" has encountered an error

### ISSUE THREAD

**Issue by BigQ517** [niklasvh/html2canvas#1187]
When css contains the background: url('img/text.png') style,canvas.toDataURL("image/png") An error occurred.
Error message:
Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
How can i solve it?
Thanks！！

**Comment by niklasvh** [comment]
Which browser?

**Comment by BigQ517** [comment]
Google Chrome 
I use your "demo.html" to add "background:url('test.jpg')" on body, but also an error.
Thank you very much for your reply

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by BigQ517** [comment]
I`m sorry to say, this is still an issue with v1.0.0.
[jsfiddle](http://jsfiddle.net/bigq/az5j0766/3/) 
Thank you for your attention.

**Comment by niklasvh** [comment]
The example you gave works fine on Chrome. If you set the option `allowTaint` to `false`, which browser does it not work on?
