### ISSUE TITLE
Does your project support ie11?

### ISSUE THREAD

**Issue by DickLicha** [niklasvh/html2canvas#1189]
I found that your project cannot be screenshot under ie11. Does html2canvas support ie11?

**Comment by niklasvh** [comment]
It should. If it isn't working, could you share an example in jsfiddle?

**Comment by DickLicha** [comment]
I open the existing_canvas.html file in your project with chrome, and he can show the screenshot properly. Screenshots do not appear when I change to  ie11.
![11](https://user-images.githubusercontent.com/21870645/29443543-79b52b6e-840b-11e7-8a8c-2b33c319d84a.png)
