### ISSUE TITLE
Cannot export in Edge

### ISSUE THREAD

**Issue by toshetoo** [niklasvh/html2canvas#1190]
When trying to export html as canvas in Edge, the browser becomes laggy and the export does not proceed. When logging is turned on, the last log that appears is the "Starting node parser" or "Rendered with N elements". 

Is this a known issue?

**Comment by salmonmoose** [comment]
The plugin seems to slow down in non-chrome browsers, Firefox is slow, Edge is painful - I've got successful exports working in Edge, with some issues surrounding background images.

**Comment by sgsmittal** [comment]
In edge it is just exporting small portion of page.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
