### ISSUE TITLE
How to convert dom element to multiple canvas element based on height 

### ISSUE THREAD

**Issue by sibinx7** [niklasvh/html2canvas#1191]
I have a HTML element, it's height may be vary dynamically. If it height  more than the page size of `pageSize` or default pdf page size, i need to convert this html element to multiple canvas based on height of pdf's page size, so remaining parts i can show on another page. Currently some of content  not visible 
on pdf.

**Comment by niklasvh** [comment]
You can crop/resize/modify the outputted canvas to any size(s)/shapes you want.
