### ISSUE TITLE
why 0.5.0-beta4 get worser?

### ISSUE THREAD

**Issue by roviury** [niklasvh/html2canvas#1193]
in 0.5.0-alpha1, you mention that "Uses hidden iframe window to perform rendering, allowing async rendering and doesn't force the viewport to be scrolled to the top anymore."

Yes. it is solved in 0.5.0-alpha1
but this scroll top bug appears again in 0.5.0-beta4

why?

**Comment by niklasvh** [comment]
Is it still an issue in 1.0.0?
