### ISSUE TITLE
Uncaught TypeError: Cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by eugeneford** [niklasvh/html2canvas#1195]
I'm getting a TypeError 
```
html2canvas.js:2264 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at html2canvas (html2canvas.js:2264)
    at demo.html:176
```

while trying to call 
```
html2canvas(document.body).then(function(canvas) {
    document.body.appendChild(canvas);
});
```

as described in the documentation

**Comment by niklasvh** [comment]
Which version are you using?

**Comment by eugeneford** [comment]
@niklasvh v1.0.0. But it is a common problem with master branch too

**Comment by niklasvh** [comment]
Neither of those are stable yet. Releases can be found under https://github.com/niklasvh/html2canvas/releases or npm

**Comment by eugeneford** [comment]
@niklasvh, if i want to contribute, what branch should i use?

**Comment by niklasvh** [comment]
For contributing, the master branch is the way to go as the whole library has been rewritten
