### ISSUE TITLE
error in building dist file when running 'npm run build:browser'

### ISSUE THREAD

**Issue by southeastcon2017** [niklasvh/html2canvas#1196]
ERROR in ./tests/testrunner.js
    Module not found: Error: Can't resolve './reftests' in '/Users/...'
@ ./tests/testrunner.js 9:16-37
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! html2canvas@1.0.0-alpha.1 build:browser: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the html2canvas@1.0.0-alpha.1 build:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by niklasvh** [comment]
Run `npm run build`
