### ISSUE TITLE
fieldsets getting a background

### ISSUE THREAD

**Issue by fede-green** [niklasvh/html2canvas#1198]
Hello, 

i'm using html2canvas to create a PDF out of a webform. Unfortunately the generated PDF adds a strange background on my fieldsets. I can't understand why this happens... Does the library use a different CSS than the one i see the site with? Could it be it loads another CSS, or it uses an old version of my css?

thanks, 

federico

**Comment by niklasvh** [comment]
Can you show an example on jsfiddle?
