### ISSUE TITLE
Why new release (v0.5.0-beta4) has the same files as (v0.5.0-beta3)?

### ISSUE THREAD

**Issue by fiantsev** [niklasvh/html2canvas#1199]
I have compared file  html2canvas.js in my project (last modified 7 months ago) and new release file (released this 10 days ago): they have no difference!

New release file (**version v0.5.0-beta4**) has description:

/*
  html2canvas **0.5.0-beta3** <http://html2canvas.hertzen.com>
  Copyright (c) 2016 Niklas von Hertzen

  Released under  License
*/

Cant understand that. Whats wrong?!

**Comment by niklasvh** [comment]
Fixed with 1.0.0
