### ISSUE TITLE
Use computed style

### ISSUE THREAD

**Issue by megabast23** [niklasvh/html2canvas#1200]
Hello,

I am new on html2canvas library.
I've seen that you are doing a GET method on all css static files.
I was wondering why you don't use window.getComputedStyle function to set the exact current style ?

Thanks for your answer

**Comment by niklasvh** [comment]
The library does use computedStyle and does not compute styles itself.

**Comment by megabast23** [comment]
Hello,
If you do a document.clone, this not uses getComputedStyle from origin page, but it does a GET request on css sources. Am I wrong ?

**Comment by megabast23** [comment]
I'm currently reading your code.
You call getComputedStyle inside nodeContainer, not the origin document. Then for css properties created manually (addCssRule) this can't work I think

**Comment by megabast23** [comment]
I did some tests,
If you call renderWindow with document.body 
return renderWindow(document.body, container, options, windowWidth, windowHeight);
You will get the correct computed style (including css created dynamically)
