### ISSUE TITLE
Uncaught ReferenceError: Promise is not defined at htmI2canvas.js : 592

### ISSUE THREAD

**Issue by yyx1111** [niklasvh/html2canvas#1201]
Uncaught ReferenceError: Promise is not defined at htmI2canvas.js : 592

???

**Comment by eKoopmans** [comment]
Hi @yyx1111, see the [readme](https://github.com/niklasvh/html2canvas#usage). html2canvas uses Promises, which aren't natively supported in older browsers, so you'll need to use a polyfill (like es6-promise).

**Comment by yyx1111** [comment]
for example
