### ISSUE TITLE
html2canvas  Setting  width: 3600,height: 5200  return   Blank

### ISSUE THREAD

**Issue by flyjennyetn** [niklasvh/html2canvas#1205]
html2canvas  Setting  width: 3600,height: 5200  return   Blank

**Comment by niklasvh** [comment]
Which browser/OS are you using? Canvas elements have certain size restrictions that vary depend on the platform: https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

**Comment by flyjennyetn** [comment]
@niklasvh   iphone

**Comment by niklasvh** [comment]
Check out https://stackoverflow.com/a/23391599
