### ISSUE TITLE
html2canvasproxy php not working in angular2

### ISSUE THREAD

**Issue by NikhilRadadiya** [niklasvh/html2canvas#1206]
I'm using html2canvas for generating pdf from html. All working fantastic but the only problem is images from other server.

Tried using `html2canvasphp` proxy but its not working for me.

Here is my code
```
html2canvas(element,{"logging": true,)
                    "proxy": "../assets/html2canvasproxy.php"
                }).then(function(canvas) {
              element.appendChild(canvas);
              elem  = canvas.toDataURL();
              return {
               image:elem,
               width:595
             };
           }) )
```

I'm using this code in one of angular `component`.
What I'm missing?
Please help

**Comment by niklasvh** [comment]
Please share an example on jsfiddle on whats not working
