### ISSUE TITLE
can html2canvas run in jquery beforeunload function?

### ISSUE THREAD

**Issue by MulderLiu** [niklasvh/html2canvas#1207]
can html2canvas run in jquery beforeunload function?
like this:

$( window ).bind( 'beforeunload', function ()
    {
 html2canvas( document.body, {
        allowTaint: true,
        taintTest: false, async: false,
        onrendered: function ( canvas )
        {
         // can't in
      });
 } );

**Comment by niklasvh** [comment]
´Nope, it won't be able to run as it isn't blocking due to loading asynchronous resources.
