### ISSUE TITLE
SVG on firefox

### ISSUE THREAD

**Issue by mahmoodchowdhury** [niklasvh/html2canvas#1212]
Hi,
i tried html2canvas and it works fine on chrome, safari but not on firefox. I'm using inline svg and I've been trying to figure out why it won't work on firefox. Any idea?

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by mahmoodchowdhury** [comment]
Thanks for your quick response. Here's the jsfiddle
https://jsfiddle.net/mahmoodchowdhury/nt6v24wa/

**Comment by gpatki** [comment]
html2canvas works like a charm for chrome! But facing issues with firefox and IE. Any planned resolution date for above firefox issue?
Thanks!

**Comment by kgcroteau** [comment]
Same issue with IE - using mahmoodchowdhury example and with our app (Leaflet mapping) - SVG elements working great in Chrome, not in IE or FF.  

Thanks.

**Comment by mahmoodchowdhury** [comment]
Just wondering if there's an ETA on a fix?

**Comment by CelesterSpencer** [comment]
Same for me. While html2canvas seems to work in Chrome and IE (with an distorted Pie chart) , in FF it sometimes displays only text but often doesn't render any svg. I made an example in [JSFiddle](https://jsfiddle.net/CelesterSpencer/2nu3zanr/) that illustrates the issue. I tested it with all alpha and beta versions of version 0.5.0 . None of them seem to work under FF.

**Comment by mahmoodchowdhury** [comment]
Hi guys,

So I managed to get this working. There are two main things I had to add:
1) call the svg image as an external image source
2) Add "allowTaint", "useCORS", "taintTest" properties to the html2canvas function

Here is the working fiddle: https://jsfiddle.net/mahmoodchowdhury/x0724yj3/2/
If you guys want to compare the original fiddle I posted, here's the link: https://jsfiddle.net/mahmoodchowdhury/nt6v24wa/

Hope this help.

**Comment by niklasvh** [comment]
Fixed in v1.0.0-alpha.1 https://jsfiddle.net/nt6v24wa/3/
