### ISSUE TITLE
Can't work with latest version with error: "l.setAttribute is not a function"

### ISSUE THREAD

**Issue by Andrewyg** [niklasvh/html2canvas#1214]
![image](https://user-images.githubusercontent.com/20808546/30240445-2b4d17f8-95a3-11e7-9c39-9ba8190a4b91.png)

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by Andrewyg** [comment]
Sorry my fault
I set htnl2canvas as rupture to select #output but the HTML code is .output bit #output
