### ISSUE TITLE
IE 11 cannot render svg when html2canvas.svg.js loaded with require

### ISSUE THREAD

**Issue by kgcroteau** [niklasvh/html2canvas#1218]
We are dynamically loading html2canvas.js and html2canvas.svg.js with dojo require.   Works well
in Chrome and Firefox, but in IE we get receive error "html2canvas.svg.js is not loaded, cannot render svg".

Is there a correct way to do the dynamic load for IE, or is there a combined .js file with contents of  html2canvas.js and html2canvas.svg.js?

Thank you.

**Comment by kevin074** [comment]
I am trying to figure out how to render svg on IE too. What's the error message that you are seeing?

**Comment by kgcroteau** [comment]
Hi.

 

For me, IE works fine if I load the script files using the <script> tag.   If I try to load the html2canvas files using Require (DOJO implementation),

then I get “Error: html2canvas.svg.js is not loaded, cannot render svg”   I need to go back retest this in FF and Chrome as well.

 

However – one thing to note for IE, is that I also needed to load bluebird.js – IE cannot use the Promise implementation used by html2canvas, but can use

the one in bluebird.

 

 

Hope this helps.

 

Keith

**Comment by kevin074** [comment]
thanks for the reply! I had to do that blue bird thing for promise too. 

Are you guys using highcharts for SVG? html2canvas seems to have problems with highchart and I am trying to work it out.

**Comment by kgcroteau** [comment]
Great!  Glad that helped.  

 

Sorry, no , we are working with maps – MapBox, Leaflet, Esri – trying to get a snapshot of the map area.

 

…not sure if it relates to Highcharts -  but the other big hurdle we bumped into was when “ tansform translate3d “ style was being used – that caused

all sorts of headaches – so if that’s your situation, let me know and I’ll forward what we discovered.

 

best,

 

Keith

**Comment by kgcroteau** [comment]
Solved - using the following format with dojo require to load html2canvas with svg.

  require(['/resources/html2canvas/html2canvas.min.js',
               'resources/html2canvas/html2canvas.svg.min.js'], 
                    function (html2canvas,svg) {
                        // make html2canvas with svg available globally
                        html2canvas.svg = svg;  
                        window.html2canvas =  html2canvas;
                        
                    });

...and if browser is IE (at ie 11), you can use bluebird to handle Promise:

 require(['/resources/html2canvas/bluebird.js'], function (promise) {
                            //for IE
                            window.Promise = promise;
                        });
