### ISSUE TITLE
does't work in IE11 with ES6. Unable to get property 'svg' of undefined or null reference

### ISSUE THREAD

**Issue by 13Yuan** [niklasvh/html2canvas#1219]
**it doesn't work in IE11 with ES6.**

`
import html2canvas from "html2canvas";
return html2canvas(node, { allowTaint: true }).then((canvas) => {
        return Promise.resolve(canvas.toDataURL());
    });
`

Unhandled rejection TypeError: **Unable to get property 'svg' of undefined or null reference**
   at SVGContainer.prototype.hasFabric
   at SVGNodeContainer
   at ImageLoader.prototype.loadImage 
   at Anonymous function
   at Anonymous function
   at ImageLoader.prototype.findImages
   at ImageLoader.prototype.fetch
   at NodeParser
   at renderWindow
   at Anonymous function

`
function Support(document) {
    this.rangeBounds = this.testRangeBounds(document);
    this.cors = this.testCORS();
    this.svg = this.testSVG();
}
`

**I found it was broken by the property of 'svg', this value is judge whether canvas can draw the image of SVG. In IE11, it always return false.**

`
function SVGNodeContainer(node, _native) {
    this.src = node;
    this.image = null;
    var self = this;

    this.promise = _native ? new Promise(function(resolve, reject) {
        self.image = new Image();
        self.image.onload = resolve;
        self.image.onerror = reject;
        self.image.src = "data:image/svg+xml," + (new XMLSerializer()).serializeToString(node);
        if (self.image.complete === true) {
            resolve(self.image);
        }
    }) : this.hasFabric().then(function() {
        return new Promise(function(resolve) {
            window.html2canvas.svg.fabric.parseSVGDocument(node, self.createCanvas.call(self, resolve));
        });
    });
}
`

**as the '_native' from 'this.svg' is false, then go through the this.hasFabric and window.html2canvas.svg which are 'undefined', I don't know why. 

when I change this.svg =  true, it can work. Thus, could you help resolve it or set the 'svg' to higher level so that I can change this value and its behavior?**

**Comment by kgcroteau** [comment]
Hello, I was able to get SVG to work with IE when by using bluebird.js for Promise.

**Comment by 13Yuan** [comment]
@kgcroteau Hi , could you provide more detail of how to resolve the issue of 'this.support.svg is always false' due to the html2canvas.svg.js is not loaded in IE11? Only change the promise from ES6 to bluebird?

**Comment by kgcroteau** [comment]
Sure  - I’ve attached a doc – just some quick notes with info on 3 different ways I’ve loaded html2canvas (with svg).  The method used depends on the type

of application you are incorporating html2canvas into.   

 

Hope this helps.

 

best, Keith

**Comment by DanLatimer** [comment]
@kgcroteau could you include the doc or the information here too? I'm having the same issue

**Comment by kgcroteau** [comment]
Sure.  Doc is attached.
[loading html2canvas js files - options.pdf](https://github.com/niklasvh/html2canvas/files/1338071/loading.html2canvas.js.files.-.options.pdf)
