### ISSUE TITLE
Zoomed pages are extremely slow & memory intensive

### ISSUE THREAD

**Issue by Pascal666** [niklasvh/html2canvas#1220]
If you zoom in or out on a webpage, html2canvas takes a lot longer and uses a lot more memory than normal.  This is easiest to see on long webpages like http://www.illinoiscourts.gov/SupremeCourt/Rules/Art_III/ArtIII.htm

ctrl-+ zooms in
ctrl-- zooms out
ctrl-0 sets zoom to 100%
ctrl with the mouse scroll wheel zooms in or out depending upon direction
The Chrome menu also has +/- for zooming in/out.

This problem was originally noticed when using The Great Suspender on Google Chrome: https://github.com/deanoemcke/thegreatsuspender/issues/503

**Comment by jvschiavo** [comment]
Does this still happen with the latest version, Pascal?
