### ISSUE TITLE
generated a blank page！no use Iframe！

### ISSUE THREAD

**Issue by w1027405658** [niklasvh/html2canvas#1223]
Hello, can i ask a question?
I have a page with 60(or more)  images (each picture resolution 1200px * 500px), put them into the div, div between the Id from the increase (from 0)
example:
`<div id="pic_0">`
`<img src="...">`
`</div>`
.....
`<div id="pic_59">`
` <img src="...">`
`</div>`
But I used the following method, but generated a blank page
`html2canvas(document.getElementById("pic_20"), {`
	`  onrendered: function(canvas) {`
		`document.body.appendChild(canvas);`
	 ` },`
	 ` width: 300,`
	`  height: 300`
	`});`
And when I reduced the number of images on the page to 30 (or less), it's OK!
Can you help me. Thank you!

**Comment by Sritharan-racap** [comment]
I am also getting the same issue. Html2Canvas is generating blank pages for certain div components. Please advise. When i did a trace of the code, I am seeing the issue in this line of code,

`var width = options.type === "view" ? windowWidth : documentWidth(clonedWindow.document);
    var height = options.type === "view" ? windowHeight : documentHeight(clonedWindow.document);
    var renderer = new options.renderer(width, height, imageLoader, options, document);
    var parser = new NodeParser(node, renderer, support, imageLoader, options);`

When in the option, i set the type = 'view' the blank pages are gone, but the snapshot is taken only for the visible page and not the entire div content. This is little weird. Also when I enable the logging, I am seeing the height to an extremely high value. (**Initialized CanvasRenderer with size 2558 x 72392**)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
