### ISSUE TITLE
Problem With Text

### ISSUE THREAD

**Issue by gipsydangerv2** [niklasvh/html2canvas#1225]
Hi niklasvh. I have drawn d3 charts in my project. When I take screenshot using html2canvas some texts/legends in the charts come blurry.

I used beta4, beta3, beta2, beta1, alpha1 versions of html2canvas. The same issue is coming with all the versions. 
The issue is coming with many charts. I am sharing the link of one of the charts I am drawing.
![issue1](https://user-images.githubusercontent.com/8556506/30692809-bc01f4da-9eea-11e7-83fe-1564639f45ea.png)
![issue2](https://user-images.githubusercontent.com/8556506/30692810-bc055972-9eea-11e7-917c-609d4c5756be.png)

Link : https://jsfiddle.net/gipsydangerv2/4geokqLj/14/

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by chaoli920029342** [comment]
I have the same problem,when my font-size is under 8px~
