### ISSUE TITLE
Creating canvas of element that render later in angular generates blank page

### ISSUE THREAD

**Issue by suzondas** [niklasvh/html2canvas#1226]
Hi,
last few days I was struggling for creating canvas image of that element that basically renders later. This area is not rendered on load. When user edit some texts in that area and then the user clicks on convert , the canvas is blank. is there any workaround?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
