### ISSUE TITLE
Cloned element isn't removed after html elements get converted to canvas

### ISSUE THREAD

**Issue by NikhilRadadiya** [niklasvh/html2canvas#1228]
I'm passing some html elements to `html2canvas` it works very well but the only problem is element cloned and in view it shows 2 times.(same div shows 2 times);

here is my code,
```
html2canvas(element).then(function(canvas) {
	console.log(element);
	element.appendChild(canvas);
	elem  = canvas.toDataURL();
	return {
		image:elem,
		width:595
	};
})
```

Am I missing something here?

**Comment by niklasvh** [comment]
`element.appendChild(canvas);` you are adding the canvas to the document?

**Comment by NikhilRadadiya** [comment]
@niklasvh here in above function `element` is a `div` , Is that mean I'm adding canavs to document?

**Comment by niklasvh** [comment]
You are adding the canvas to the div. Try removing that line.

**Comment by NikhilRadadiya** [comment]
@niklasvh But I need canvas of that div

**Comment by niklasvh** [comment]
But you don't need a `canvas` *in the div* right? Just try removing the `element.appendChild(canvas);` line and see if it fixes your issue.

**Comment by NikhilRadadiya** [comment]
@niklasvh Ok, So where do I append canavs?

**Comment by NikhilRadadiya** [comment]
@niklasvh  Thank You so much, I didn't understand what you said. but, now it solved my problem.

I don't need to append canvas to element
