### ISSUE TITLE
width/height option lost in 1.0.0-alpha.1 ?

### ISSUE THREAD

**Issue by MikeBroders** [niklasvh/html2canvas#1230]
hey,

how to set width & height of the rendered canvas?

in 1.0.0-alpha.1 these options show no effect... the canvas is always rendered with the size of the window

are there new options to define width/height of the rendered canvas?

thx
mike

**Comment by niklasvh** [comment]
They are currently missing (it's still WIP, and some other features are also missing), but will be part of the 1.0.0 release.

**Comment by MikeBroders** [comment]
hey,

all right… but i can say already that this version is working very well.

- offscreen rendering is working
- colors, shadows are working

thanks for your effort
mike
