### ISSUE TITLE
getComputedStyle for backgroundSize

### ISSUE THREAD

**Issue by eggers** [niklasvh/html2canvas#1231]
Different browsers handle getComputedStyle differently for percent backgroundSize:

For example:

http://jsfiddle.net/ax0f9sz5/

* For chrome (mac & windows) & safari it returns: `80%`
* For firefox it returns `80% auto`
* For Edge & IE 11 it returns a size in pixels. e.g.: `392px` (which is the width, but not the height of the background image)

This was causing an issue with the version of html2canvas that I am using because it'll only specify the height as auto in the case of percent sizes:

```js
NodeContainer.prototype.cssList = function(property, index) {
    var value = (this.css(property) || '').split(',');
    value = value[index || 0] || value[0] || 'auto';
    value = value.trim().split(' ');
    if (value.length === 1) {
        value = [value[0], isPercentage(value[0]) ? 'auto' : value[0]];
    }
    return value;
};
```

It looks like the code has changed quite a bit, so I'm not sure if it is still an issue with the latest version (There are other issues that prevent me from using the latest version, so I'm using a fork: eKoopmans/html2canvas, in addition to adding some fixes svgs for firefox, duplicate textnodes for svg, and miss-sized backgroundImages for scaled images.)

**Comment by niklasvh** [comment]
As you mentioned, the library has been rewritten for 1.0.0. I'll have a test to make sure this issue is addressed and fixed there.

**Comment by Seasonley** [comment]
`background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAgAQMAAADpK4BZAAAAA3NCSVQICAjb4U/gAAAABlBMVEX////x3dUj61eQAAAAAnRSTlMA/1uRIrUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzbovLKMAAAAFnRFWHRDcmVhdGlvbiBUaW1lADA2LzIxLzE4qLFfLAAAAA1JREFUCJljYKAINAAAAMAAgZEu7L0AAAAASUVORK5CYII=);
background-size: auto 7vw;` not work.
