### ISSUE TITLE
Align the official documentation with current codebase

### ISSUE THREAD

**Issue by tan9** [niklasvh/html2canvas#1234]
Current official documentation https://html2canvas.hertzen.com/documentation.html
Advertised the usage of `onrendered` callback, leading users to use the function will be be removed soon (e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20189 ).

**Comment by niklasvh** [comment]
@tan9 You are right. The documentation is outdated on the website and needs to be updated (it is even outdated for v0.5.0). The whole website will get updated before 1.0.0 will get released.

**Comment by niklasvh** [comment]
The documentation has been updated
