### ISSUE TITLE
Problem with rendering offscreen div

### ISSUE THREAD

**Issue by Metrevelli** [niklasvh/html2canvas#1236]
im making this comic like thing where i must save images transofrmed and resized inside div... but when i for example scroll down and try to render, it only renders the part which is on the screen.

here is the code [https://jsfiddle.net/928x51p6/](https://jsfiddle.net/928x51p6/)

**Comment by marketingakra** [comment]
Incredible coincidence. I have this exact (same) problem right now! And you posted this message 4 hours ago... Wow!

Well, is there any solution to this issue? Thanks in advance.

**Comment by marketingakra** [comment]
This is not a real solution, but... if you make zoom-out with the browser until you can fit the div into the window and call the function, it will export the canvas perfectly.

**Comment by clem91** [comment]
There are some issues about this subject in the repo and someone made a PR but it's not already merged. I'm using this PR in my project without any problems but it could be great to have a merge in the future.

here is the link: https://github.com/niklasvh/html2canvas/pull/1083

**Comment by Metrevelli** [comment]
u mean this PR? [https://github.com/niklasvh/html2canvas/pull/1083/commits/62b6973b5a4ba7376367bb090424066a374abe9e](https://github.com/niklasvh/html2canvas/pull/1083/commits/62b6973b5a4ba7376367bb090424066a374abe9e)

**Comment by marketingakra** [comment]
I've applied the changes of that PR and the canvas limits still are cut by the window view.

**Comment by clem91** [comment]
It's been a while I have done these modifications but now i remembered that I use the custom build of eKoopmans (the guy who made the PR) in his 0.5.0-beta4 release.  https://github.com/eKoopmans/html2canvas
This custom build make my app work like I want and render offscreen elements

**Comment by Metrevelli** [comment]
i copied this version but int wont work... im doing it like this `        html2canvas($('#containment-wrapper'),{
          letterRendering: true,
          logging:true,
            onrendered: function (canvas) {
                //Set hidden field's value to image data (base-64 string)
                $('#img_val').val(canvas.toDataURL("image/png"));
                //Submit the form manually
                document.getElementById("myForm").submit();
            }
        });`

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
