### ISSUE TITLE
Unable to copy canvas content from <canvas> Cannot read property 'getImageData' of null

### ISSUE THREAD

**Issue by goldengrisha** [niklasvh/html2canvas#1239]

**Comment by goldengrisha** [comment]
Please, explain why did you close it ?

**Comment by DavidLore** [comment]
@goldengrisha @niklasvh Can you explain why did you close the issue ?
I got exactly the same error when I'm trying to get snapshot of the DOM contains <canvas> element, I'm logging the operation, so the error I got : 

> 18ms html2canvas: Unable to copy canvas content from <canvas height=​"769" width=​"1267" id=​"kl" style=​"display:​ block;​ touch-action:​ none;​ outline:​ none;​ background:​ rgb(247, 247, 247)​;​ cursor:​ auto;​" tabindex=​"8888">​ TypeError: Cannot read property 'getImageData' of null

This is the code :
`html2Canvas( [ document.body ], {
      "proxy": "http://anfo.pl/jw/widget/proxy/proxy.php",
      "allowTaint": true,
      "useCORS": true,
      "logging": true,
      "onrendered": (canvas) => {
        document.body.insertBefore(canvas, document.body.childNodes[0]);
      }
   });`
