### ISSUE TITLE
does it support import API

### ISSUE THREAD

**Issue by leeseean** [niklasvh/html2canvas#1240]
"import htmltocanvas form htmltocanvas" does not work

**Comment by amenadiel** [comment]
What are you using to transpile that code? If you wanted to resolve html2canvas from your `node_modules` folder using, for example, rollup.js, you'd need to do something like

```js
import html2canvas from 'html2canvas';
```
and use a resolver like `rollup-plugin-node-resolve` (if using [Rollup.js](https://rollupjs.org/)) to tell the transpiler where to look for `html2canvas`. Other builders/bundlers like  [JSPM](https://jspm.io/) will already have a mapping for this, so it would be managed transparently.

If you had `html2canvas` script in a relative path, you could also do

```js
import html2canvas from './html2canvas.js';
```
