### ISSUE TITLE
Can i render the page on what the user can only see?

### ISSUE THREAD

**Issue by keldino** [niklasvh/html2canvas#1242]
Hi i just want to ask if there's a way to render only what user can see? Because the canvas is not working when the page is more than 30000 pixels length and its too slow. 

Thanks.

**Comment by niklasvh** [comment]
You can define what to render by setting width, height, x, y etc.

See the upto date options for 1.0.0 at https://github.com/niklasvh/html2canvas/blob/master/docs/configuration.md
