### ISSUE TITLE
Unable to copy canvas content from <canvas> Cannot read property 'getImageData' of null

### ISSUE THREAD

**Issue by DavidLore** [niklasvh/html2canvas#1243]
I'm trying to get screenshot of page that the DOM contains <canvas> element, logging the operation, so the error I got :

> 18ms html2canvas: Unable to copy canvas content from <canvas height=​"769" width=​"1267" id=​"kl" style=​"display:​ block;​ touch-action:​ none;​ outline:​ none;​ background:​ rgb(247, 247, 247)​;​ cursor:​ auto;​" tabindex=​"8888">​ TypeError: Cannot read property 'getImageData' of null

The code :
`
html2canvas( [ document.body ], { 
    "proxy": "http://anfo.pl/jw/widget/proxy/proxy.php", 
    "allowTaint": true, 
    "useCORS": true, 
    "logging": true, 
    "onrendered": (canvas) => { 
          document.body.insertBefore(canvas, document.body.childNodes[0]); 
    } 
});
`

**Comment by DanielZhao1990** [comment]
https://github.com/niklasvh/html2canvas/pull/1037/commits/7ca94348bc1f81d752a7b0ba64d77146a8ec528e     try this way, it fixed my bug.
