### ISSUE TITLE
How to enhance performance?

### ISSUE THREAD

**Issue by jyguyomarch** [niklasvh/html2canvas#1250]
Hi,

I understand that the performance of html2canvas depends a lot on the size of the DOM tree that you need to parse. In the example below, 883 nodes took 8 seconds to process, while 2660 nodes took 66 seconds.

I was wondering if you had any suggestions on how to improve performances? I am currently using 0.5 beta4.

Thx!

![image](https://user-images.githubusercontent.com/3885578/31912929-6ca324f8-b7fa-11e7-9a10-4176cdf91b22.png)

**Comment by niklasvh** [comment]
The amount of text you have on the page is probably the biggest performance factor. If you enable `letterRendering` it will have a significant performance impact as well. The 60 second render does sound a bit too much though for the amount of content you are rendering.

**Comment by jyguyomarch** [comment]
@niklasvh thx for the quick reply. I'll give a try to letterRendering.
