### ISSUE TITLE
Is v0.4.1 production-ready?

### ISSUE THREAD

**Issue by wittibs** [niklasvh/html2canvas#1251]
> The script is still in a very experimental state, so I don't recommend using it in a production environment nor start building applications with it yet, as there will be still major changes made.

Regarding v0.4.1, is this still true? (I noticed this part of the README was 5 years old)
If not, I'd like to update the README to specify which version is production-ready.

**Comment by niklasvh** [comment]
1.0.0 is closer to production read than 0.4.1 (which is probably about 5 years old)
