### ISSUE TITLE
Border-radius 100% bug

### ISSUE THREAD

**Issue by renankaic** [niklasvh/html2canvas#1255]
Hi.

I'm having problem when rendering with 100% border-radius in DIV and IMGs tags. See below

This is how looks in the browser
![screenshot_1](https://user-images.githubusercontent.com/26421325/32186314-e93b5790-bd88-11e7-9804-a87696dc5fb2.png)

This is how looks when I use the HTML2CANVAS to take a screenshot
![screenshot_2](https://user-images.githubusercontent.com/26421325/32186510-62afd4b6-bd89-11e7-9997-6c34b61c741f.png)

Is there any fix?

**Comment by niklasvh** [comment]
Is this issue still present in v1.0.0-alpha.1?
