### ISSUE TITLE
scroll position can't be captured in 1.0.0-alpha.1

### ISSUE THREAD

**Issue by AlphaDu** [niklasvh/html2canvas#1259]
in 0.5.0, scroll position can be captured but it lose efficacy in new version 1.0.0-alpha.1.
because if some layout bug, I cant use old version. but new version can't capture the element scroll postition

**Comment by AlphaDu** [comment]
https://github.com/AlphaDu/Html2canvasExample 
I scroll wrapper to bottom then do capture.the picture don't reflect scrollTop。 and in firefox。 scroll content will overflow in display

**Comment by niklasvh** [comment]
Thanks, will take a look at it shortly

**Comment by GuoYingxu** [comment]
It still not work in chrome.
