### ISSUE TITLE
Preventing some elements from being rendering

### ISSUE THREAD

**Issue by tiagobt** [niklasvh/html2canvas#126]
Is it possible to prevent a few elements from being rendered? I'd like to renderer the entire page (`document.body`) except for a few specific `div`s, which are there to help the user take the screenshot. I tried to use the `ignoreElements` option, but it seems to ignore all elements of a type, which is not really what I want.

I was checking http://experiments.hertzen.com/jsfeedback/ and they seem to do what I want. As far as I can tell, they have modified `html2canvas.js` in order to do so. It would be interesting if this feature existed in the original code.

Thanks a lot.

**Comment by junibrosas** [comment]
ALL HAIL! I just found "data-html2canvas-ignore" to ignore element from rendering. It saved my career. Thanks!

**Comment by Sonamkhurana** [comment]
Thanks @niklasvh ! "data-html2canvas-ignore" was the simplest solution.
