### ISSUE TITLE
Upload multiple pictures，bug

### ISSUE THREAD

**Issue by Tomny2016** [niklasvh/html2canvas#1262]
`html2canvas.js:974 Uncaught (in promise) TypeError: Cannot read property 'removeAttribute' of null
    at html2canvas.js:974
    at <anonymous>`；
there are some codes in here;
`  $('.shopsetting_dress_block').on('click', ".carselconborder", function () {
            console.log($(this).index(".carselconborder"));
//            console.log($('.carselconborder'));
            console.log($('.shopsetting_dress_block .shopsetting_show_privew'));
            let index=$(this).index(".carselconborder")-1;
            let shoDresdom=$('.shopsetting_dress_block .shopsetting_show_privew')[index];
            console.log(shoDresdom);
            var shoDres = new Sxc(1, 1, "");
            shoDres.opencutWin();
            $('body').on('click', '#takeScreenshot', function () {
                html2canvas(document.getElementById('cropper-preview'), {
                    allowTaint: true,//允许跨域
                    taintTest: true,//是否在渲染前测试图片
                    onrendered: function (canvas) {
                        if ($(canvas).attr('height') == 0) {
                            layer.msg('您还没有选择任何图片哦！');
                            return false;
                        } else {
                            //生成base64图片数据
                            var dataUrl = canvas.toDataURL("image/jpeg");
//                            $(shoDresdom).attr('src', dataUrl)
                            $(shoDresdom)[0].src=dataUrl;
                        console.log(dataUrl);
                        }
                        $('.cropper-Pupop').remove();  //关闭弹窗
                    },
                });
            })
//            takeScreenshot($(shoDresdom));
        })`

**Comment by haohangan** [comment]
源代码里面 
if(attributeName!==null){
            document.querySelector(selector).removeAttribute(attributeName); 
          }
