### ISSUE TITLE
Cannot import html2canvas module

### ISSUE THREAD

**Issue by qiluo** [niklasvh/html2canvas#1265]
Hi all, I'm building an app with Ionic & typescript, when I tried to add html2canvas , I added following import
```
import * as html2canvas from 'html2canvas'
```

I got error `cannot find module html2canvas` for 1.0.0-alpha1, but it worked for 0.5.0-beta, what should I do for import? Thanks

**Comment by niklasvh** [comment]
How are you fetching/building html2canvas 1.0.0-alpha.1 into your project?

**Comment by qiluo** [comment]
@niklasvh  I `npm install git+https://....`, no error output, then I found it's only a few files under `node_modules/html2canvas`, missing `src` folder, quite weird, don't know it's npm bug or whatelse. Had to manually clone the repo now

**Comment by niklasvh** [comment]
Are you still having the issue with the release on npm?

**Comment by qiluo** [comment]
@niklasvh the same, here's what I've done
```
→ npm i git+https://github.com/niklasvh/html2canvas.git
my-app@0.0.1 /Users/qiluo/Dev/ionic-apps/my-app
└── html2canvas@1.0.0-alpha.4  (git+https://github.com/niklasvh/html2canvas.git#2237e8e230da2a4bf807484529c5d46223913f8c)

#  in ~/Dev/ionic-apps/my-app on git:dev 
→ ls node_modules/html2canvas
CHANGELOG.md      README.md         docs              node_modules      package.json
LICENSE           bower.json        flow-typed        package-lock.json www
```

anything I missed?

**Comment by niklasvh** [comment]
If you install it through git, you will need to build the library before you can use it. What I meant though that you install it directly from npm, `npm install html2canvas@1.0.0-alpha.3`
