### ISSUE TITLE
HTML2Canvas cutting off parts of image

### ISSUE THREAD

**Issue by Loki180** [niklasvh/html2canvas#1266]
Hello!

I'm building a Canvas tool and I'm having an issue with HTML2Canvas where its cutting off part of the image inside of the div when the image is moved to the left or right using jquery's Drag function.

The issue seems to be with a zoom function that I have, the zoom scales the image using transform. Even though the image is seen inside of the div HTML2Canvas still cuts parts of it out.

The Code that I've used for HTML2Canvas is pretty simple, I've also tried making sure the page is at the top of the page but it still doesn't work.

`$(function() {
    $(".button-2").click(function() {
$('html,body').scrollTop(0);
        html2canvas($(".canvas-cut"),  {

            onrendered: function(canvas) {
                theCanvas = canvas;
                canvas.toBlob(function(blob) {
                    saveAs(blob, "Dashboard.png");
                    alert("Done");
                });
            }
        });
    });
});`

The image is within a few divs

`    <div class="column-2 w-col w-col-10">
      <div class="canvas-cut">
        <div class="image-container">
          <div class="border"></div>
          <img id="drag" src="uploads/<?php echo $_SESSION['image']; ?>" class="image-2">
        </div>
      </div>
    </div>`

The div is captured well but the image is sometimes cut off. 

Here is the issue
![screenshot from 2017-11-14 12-43-46](https://user-images.githubusercontent.com/12372894/32780805-88e6f166-c93a-11e7-9b89-555e4e7e9f88.png)

Also

![screenshot from 2017-11-14 12-50-12](https://user-images.githubusercontent.com/12372894/32780820-953d7ca0-c93a-11e7-9024-a4699ecf3423.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by kakkaraashish** [comment]
@Loki180  Hi did you find the solution for that... I was also facing same problem..

**Comment by RahulDudharjiya** [comment]
hey i have same issue can anybody find any solution ?

**Comment by nikhilpatel7** [comment]
> 
> 
> Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

Yes it is happening in latest version too... :(

**Comment by mark1828** [comment]
me too in 2019, can't find the solution

**Comment by mlfactory** [comment]
Same here..

**Comment by exeleon** [comment]
Same problem with version 1.0.0-rc.5

**Comment by ttoliveira** [comment]
Same problem version 1.0.0-rc.5

**Comment by jatindumka** [comment]
Same problem version 1.0.0-rc.5

**Comment by phuquoc164** [comment]
Same problem version 1.0.0-rc.5

**Comment by mlfactory** [comment]
In my Chase - this worked : https://github.com/niklasvh/html2canvas/issues/265

```
i could not render background images and it seemed to be cover or contain background size, so i've changed line 350 in 0.4.1 version to:

topPos = isNaN(parseInt(bgposition[1], 10)) ? topPos : parseInt(bgposition[1], 10);

and it works!
```

**Comment by mnedelkoski** [comment]
Even this did not help me. I got the left part of my image cut off, randomly without any pattern. Anyone managed to fix the issues? My version is 1.0.0-rc.5.

**Comment by kimnewbie** [comment]
same here in 2023 :'(

**Comment by MrQinYQ** [comment]
same here in 2025, version: 1.4.1
