### ISSUE TITLE
html2canvas not compatible with prototype.js

### ISSUE THREAD

**Issue by keldino** [niklasvh/html2canvas#1270]
```
Uncaught (in promise) TypeError: this.getChildren is not a function
    at html2canvas.js:2012
    at prototype.js:297
    at prototype.js:266
    at Array._each (prototype.js:459)
    at Array.each (prototype.js:264)
    at Array.collect (prototype.js:296)
    at NodeParser.getChildren (html2canvas.js:2010)
    at new NodeParser (html2canvas.js:1859)
    at renderWindow (html2canvas.js:1018)
    at html2canvas.js:1005

```

i got this error. im using prototype.js  version 1.5.0_rc0
and html2canvas 0.5.0-beta4
i need to make it compatible to each other please help

**Comment by niklasvh** [comment]
That's a bug with prototype.js and not html2canvas. html2canvas uses the standard ES5 Array methods and prototype.js breaks them that's not something html2canvas will address. Besides, the 1.5.0 version is over 10 years old.

**Comment by keldino** [comment]
Okay, thanks for the response.
