### ISSUE TITLE
text overlap  and space gets truncated in firefox and list index not working when used as counter 

### ISSUE THREAD

**Issue by ahmadfaizalbh** [niklasvh/html2canvas#1276]
Error (this error occur in Firefox) 
![error](https://user-images.githubusercontent.com/4068789/33160291-09bed486-d041-11e7-9386-651ba7fb4544.png)

Correct
![correct](https://user-images.githubusercontent.com/4068789/33160292-0ac1c460-d041-11e7-83af-893f8749da6e.png)
for the above each of text inside p tag

Error (all browsers)
![error_list_index](https://user-images.githubusercontent.com/4068789/33160524-2a0b5334-d043-11e7-89de-0a6f575179b4.png)

correct
![coorect_list_index](https://user-images.githubusercontent.com/4068789/33160525-2a0d0918-d043-11e7-80e9-29ec887b3788.png)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by ahmadfaizalbh** [comment]
link to jsfiddle http://jsfiddle.net/ahmadfaizalbh/az5j0766/11/
You can see only first message gets rendered properly.
Firefox version 57.0.4+build1-0ubuntu0.16.04.1
![resultant image](https://user-images.githubusercontent.com/4068789/34813804-5c4f46de-f6d1-11e7-8f0f-f1d147035134.png)

**Comment by GerkinDev** [comment]
@ahmadfaizalbh I can't see anything particular you did for the 1st message... Are you saying that the lib works properly only for the 1st one, then render wrongly all others?

**Comment by ahmadfaizalbh** [comment]
you are right

**Comment by nishant-appvent** [comment]
![image_2024_09_02T11_35_06_317Z](https://github.com/user-attachments/assets/bb109689-7cf5-4068-bb86-a0770784d5f0)
The actual correct HtmlElement

![image_2024_09_02T11_35_38_902Z](https://github.com/user-attachments/assets/6abffc22-5e4c-49bc-923d-1f46f0374d33)
The image after converting it through html2canvas version "^1.4.1".

I am facing this issue in latest chrome version i.e. 128.0.6613.84. While it was working fine with chrome version 127.0.6533.119. Can any one please suggest any solution for this?
Can you please look into it, @niklasvh?
