### ISSUE TITLE
html2canvas: Error loading Image

### ISSUE THREAD

**Issue by vishal-px** [niklasvh/html2canvas#1279]
Hi @niklasvh ,
      I want to capture webpage using htmltocanvas all is working fine but when i am trying to capture webpage then i not getting images.
Can you help me?
Here is my code
`function capture(div_id=null) { 
  	jQuery(".screenshot_row_target").html2canvas({
	logging: true,
	//taintTest : true,
	//proxy: "https://skeleton-21.myshopify.com",
	onrendered: function (canvas) {
	  	jQuery('#screenshot_img_val').val(canvas.toDataURL("image/png"));
	 	//document.getElementById("screenshot_html_form").submit();
    }
  });
}`

Thanks.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by huanhuanhome** [comment]
@vishal-px 你这个问题解决了么？或者找到什么替代的问题了么？ 遇到了相同的问题，因为图片的资源在第三方的cdn上

**Comment by Fun005** [comment]
> @vishal-px 你这个问题解决了么？或者找到什么替代的方案了么？ 我遇到了相同的问题，因为图片的资源在第三方的cdn上

请问解决了吗

**Comment by charlottexa** [comment]
@huanhuanhome 请问问题解决了吗，或者有什么替代的方案
