### ISSUE TITLE
HTML2Canvas not capturing EXIF orientation

### ISSUE THREAD

**Issue by Loki180** [niklasvh/html2canvas#1282]
Hello,

This has been asked a few times but nothing as of yet has helped me.

I've ran into the devil that is iOS EXIF. HTML2Canvas is not capturing the image as it appears but with the orientation of the EXIF. 

How do I get around this annoying addition by Apple?

**Comment by Loki180** [comment]
It appears to be Apple that is causing the problem, the images are rotated.

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by joelnz** [comment]
same issue...
HTML2Canvas displays iOS photos taken in portrait as landscape.

Try this fiddle on your phone:
https://jsfiddle.net/0f0evru0/

**Comment by smalike** [comment]
same issue...
