### ISSUE TITLE
Recharts chart rendered with double lable?

### ISSUE THREAD

**Issue by justduy** [niklasvh/html2canvas#1285]
Using this code 

```
exportGraph = () => {
    const target = document.getElementById("graph");
    html2canvas(target, {
      onrendered: function(canvas) {
        document.body.appendChild(canvas);
      }
    });
  };
```
gives this:

![image](https://user-images.githubusercontent.com/8453104/33388244-bdfaceb2-d52f-11e7-9121-904a482effb0.png)

![image](https://user-images.githubusercontent.com/8453104/33388353-0acdb63c-d530-11e7-861a-f65e44134055.png)

Only problem is as you can see the weird lables.

**Comment by niklasvh** [comment]
Are you still having same issue with 1.0.0?
