### ISSUE TITLE
basic example on site does not work properly

### ISSUE THREAD

**Issue by bmoren** [niklasvh/html2canvas#1290]
1.0.0 vs 0.5.0b5 

when using 1.0.0 the example on the site does not work with a single image, it does work in 0.5.0b5

when I try to use the 1.0.0a, I get the following feedback:

html2canvas.min.js:6 html2canvas 1.0.0-alpha.1
html2canvas.min.js:6 24ms html2canvas: Document cloned, using foreignObject rendering
html2canvas.min.js:6 61ms html2canvas: Finished loading 1 images [img]
html2canvas.min.js:6 63ms html2canvas: ForeignObject renderer initialized (1607x702 at 0,0) with scale 1

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <img src="200.jpg" alt="">

    <script src="https://github.com/niklasvh/html2canvas/releases/download/v0.5.0-beta4/html2canvas.min.js" charset="utf-8"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="app.js" charset="utf-8"></script>
  </body>
</html>

``` 

```javascript
  html2canvas(document.body, {
    onrendered: function(canvas) {
      document.body.appendChild(canvas);
    }
  });

```

**Comment by eKoopmans** [comment]
Hi @bmoren, the docs aren't updated yet, but the `onrendered` option has been removed and replaced with promises. Try this:

```js
html2canvas(document.body).then(function(canvas) {
    document.body.appendChild(canvas);
});
```
