### ISSUE TITLE
Uncaught TypeError on making an image out of iframe which contains a canvas.

### ISSUE THREAD

**Issue by siddisking** [niklasvh/html2canvas#1297]
Hi,

I am trying to create a canvas out of iframe which contains canvas which contains images and objects (3d obj models) which are being downloaded from s3.

Most of the times it is able to render everything properly but sometimes it is not able to load all the objs and throws this error:

`Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.`

Is there any way to handle this error so that it does not keep on looping in the console?

If I could catch it or fix it, it would be a huge help.

here is how I am generating the image:

I generate the image with this code.

```
html2canvas(document.getElementById('result-iframe').contentDocument.childNodes[0].childNodes[1], {
				  onrendered: function(canvas) {
					canvas.style.width='112px';
					canvas.style.height='112px';
					document.getElementById('project-thumb').appendChild(canvas);
					document.getElementById('pushProjectButton').removeAttribute('disabled');
				  },
					letterRendering:false,
					taintTest:false
				});


```I tried using promise and catching the error but no luck:

```
```
try{
				html2canvas(document.getElementById('result-iframe').contentDocument.childNodes[0].childNodes[1]
				).then(function(canvas,err){	
					try{
						canvas.style.width='112px';
						canvas.style.height='112px';
						document.getElementById('project-thumb').appendChild(canvas);
						document.getElementById('pushProjectButton').removeAttribute('disabled');
					}
					catch(e){console.log('caught nested error');}
				});
				}
				catch(e){console.log('error caught!');}


``````

b/w document.getElementById('result-iframe').contentDocument.childNodes[0].childNodes[1] is the canvas inside the iframe.

thanks...

**Comment by niklasvh** [comment]
Which version of html2canvas are you testing with? Could you replicate the error on jsfiddle as it is quite difficult to try and figure out what the problem is from what you shared?

**Comment by siddisking** [comment]
I am using 0.5.0-beta4.

I am trying to take a picture of scene (which is in canvas) in aframe (https://aframe.io) if you go to this link you can find a canvas inside an Iframe.

I won't be able to reproduce it but from above link, I think you can make out the issue.

Let me know I can do anything else to make it more clear

also is there any way to catch it so then for now I can atleast stop it looping all over the console.

-Thanks
