### ISSUE TITLE
offset in rendered img

### ISSUE THREAD

**Issue by jolan78** [niklasvh/html2canvas#1298]
* html2canvas version tested with: 63377d4
 * Browser & version: Chrome 62.0.3202.94 and Firefox 57.0  
 * Operating system: MacOS 10.11.6

When capturing an image below another one, the rendered image has an offset. the upper part is blank and the lower part is truncated.
this occurs wether foreignObjectRendering is used or not.

in this exemple, the canvas rendered by html2canvas from the second image has a red border to make the bug more obvious:
![imgoffset](https://user-images.githubusercontent.com/29343/33773404-06399884-dc38-11e7-914f-20bb8b44213f.png)

test case (would not work in jsfiddle due to cross origin issues): 
[testcase.zip](https://github.com/niklasvh/html2canvas/files/1543117/testcase.zip)

**Comment by jolan78** [comment]
the problem occurs because foreignObject is rendered as xhtml strict and do not use doctypes. if the original document's doctype is different (ex: html4 transitional) the images will be spaced differently. here is another testcase demonstrating the issue: 
[testcase.zip](https://github.com/niklasvh/html2canvas/files/1555847/testcase.zip)

**Comment by jolan78** [comment]
the issue has two causes : 
* when the foreignObject rendering is used, here : https://github.com/niklasvh/html2canvas/blob/45519762468fc26d101b4fbe768c74d761d81e84/src/renderer/ForeignObjectRenderer.js#L79
 the generated svg inherits the document doctype while the image with the serialized svg as a dataURL apparently does not.
as xhtml strict is the only doctype available to foreignObject. the only options here are to either modify vertical-align as in commit https://github.com/niklasvh/html2canvas/commit/5c6c17d6f4e74790e4bcab867767e90edcc4808d, or to render the svg with another mechanism allowing doctype inheritance.

* when the computed rendering is used, the iframe is generated with a HTML5 doctype here :https://github.com/niklasvh/html2canvas/blob/45519762468fc26d101b4fbe768c74d761d81e84/src/Clone.js#L581
copying the element's ownerDocument's documentType to the iFrame's document solves the issue and potentially other issues related to doctype-dependent rendering

commit https://github.com/niklasvh/html2canvas/commit/5c6c17d6f4e74790e4bcab867767e90edcc4808d solves the issue for both renderers, but only for images. I'm not aware of any other issuer related to doctype-dependent rendering but they may exist

**Comment by niklasvh** [comment]
Foreign object rendering has a number of issues, so will not be fixing this for it for now.
