### ISSUE TITLE
logging:false not work

### ISSUE THREAD

**Issue by keyiis** [niklasvh/html2canvas#1302]
when i set `logging`in options,but no effect!
```
html2canvas(element, {logging:false}).then(canvas => {

})
```
![qq 20171211151002](https://user-images.githubusercontent.com/7766085/33819442-6a3d7d10-de85-11e7-9da4-63e21a32a255.png)

 * html2canvas version tested with:v1.0.0-alpha.3
 * Browser & version:chrome 37
 * Operating system:win10

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/d87fef11a4561b64d8c3f75b18efa25aa353fac9
