### ISSUE TITLE
Large images are rendered choppy when resized via css or html

### ISSUE THREAD

**Issue by seularts** [niklasvh/html2canvas#1303]
I am trying to save this little business card that I manually generate via html and css: http://tzr.ro/x/x/

The issue is that when the logo is rendered it goes all choppy because I have resized it using css. If I create a logo with the exact width and height then it renders alright. I have seen some tutorials online showing that this could be fixed with canvas2image, but none of them work, probably because they are really old versions of those scripts. Could you give me a solution or a guide to fix this please!?

**Comment by niklasvh** [comment]
Please [read the troubleshooting](https://github.com/niklasvh/html2canvas/blob/master/.github/ISSUE_TEMPLATE.md) steps before opening an issue. If the issue still persists after that, please follow the same instructions on what information to provide when opening an issue.

I am fairly certain if you test it with the latest version, your issue will be resolved.
