### ISSUE TITLE
生成一张图片之后，手机保存在本地，打开一片黑，怎么解决？

### ISSUE THREAD

**Issue by DuJunX** [niklasvh/html2canvas#1306]
![tim 20171211165650](https://user-images.githubusercontent.com/34463656/33863370-57435b24-df22-11e7-9b1d-b5252038ce8c.png)

![tim 20171211165715](https://user-images.githubusercontent.com/34463656/33863365-50f875e2-df22-11e7-9c0f-6711295f24c7.png)
我现在做一个报表的功能，展示的时候是看的到的，保存到本地的图片缩略图也是看得到的，但是点开的话就是一片黑。用我朋友的手机也只能显示一些数据少一点的图，数据多一点保存之后打开也是一片黑，有没有人遇到过？怎么解决呢?就像这样一张报表，在网页可以正常显示

**Comment by zdl958112850** [comment]
设个背景 #fff
