### ISSUE TITLE
Not working perfectly in Internet Explorer 

### ISSUE THREAD

**Issue by kushthakkar08** [niklasvh/html2canvas#1307]
Hey, I update the html2canvas it is not working in Internet explorer correctly before update to new version it worked fine.

**Comment by niklasvh** [comment]
Please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by kushthakkar08** [comment]
public print(): void {
        gantt.config.autosize = 'xy';
        gantt.render();
        var node = document.getElementById('print-section');
        let img;
        this.service.setLoader('table');
        let self = this;
        html2canvas(node).then(function (canvas: any) {
            img = canvas.toDataURL();
            var doc = new jsPDF('landscape', 'mm', 'a4');
            doc.text(10, 20, 'Timeline Report');
            doc.text('Year: ' + self.year.toString(), 285, 20, 'right');
            var position = 0;
            var imgWidth = doc.internal.pageSize.width;
            var pageHeight = doc.internal.pageSize.height;
            var imgHeight = parseInt(node.style.height) * imgWidth / parseInt(node.style.width);
            var heightLeft = imgHeight;
            doc.addImage(img, 'PNG', 10, 30, 275, 0);
            heightLeft = heightLeft - pageHeight + 30;
            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                doc.addPage();
                doc.addImage(img, 'PNG', 10, position, 275, 0);
                heightLeft -= pageHeight;
            }
            doc.save('TimelineReport.pdf');
            setTimeout(function () { window.location.reload(); }, 1000);
        })
            .catch(function (error) {
                console.error('oops, something went wrong!', error);
                this.service.setLoader('none');
            });
    }

**Comment by niklasvh** [comment]
Please setup a working example to replicate the issue on jsfiddle

**Comment by kushthakkar08** [comment]
Sorry but I am using angular 4 so it is not possible to show you in jsFiddle it working in chrome and firefox only it is not working in IE.

**Comment by kushthakkar08** [comment]
I have created jsfiddle is still not working check it http://jsfiddle.net/az5j0766/5/. It is work in chrome but not in IE .

**Comment by niklasvh** [comment]
@kushthakkar08 What Promise polyfill are you using for IE?
