### ISSUE TITLE
can i immediately change element after executive function

### ISSUE THREAD

**Issue by WebGuHui** [niklasvh/html2canvas#1308]
version: v0.5.0-beta4

```
code:
document.body.style.color = '#000'
html2canvas(document.body, {
  onrendered(canvas){

}})
document.body.style.color = '#fff'
```
canvas color is '#000'

 ---

version: v1.0.0-alpha.4

```
code:
document.body.style.color = '#000'
html2canvas(document.body).then(canvas=>{})
document.body.style.color = '#fff'
```
canvas color is '#fff'

How can use v1.0.0 get the same results as v0.5.0

I hope the dom color changes will not be seen

**Comment by niklasvh** [comment]
Are you trying to set the font color to black or the background color?
