### ISSUE TITLE
image rendering problem

### ISSUE THREAD

**Issue by bjakicS7** [niklasvh/html2canvas#1309]
version:   v1.0.0-alpha.4

html2canvas(document.body, {'allowTaint': false}).then(function(canvas) {
                localStorage.canvasUri = canvas.toDataURL("image/png");
            });

toDataURL() doesn't render image. 
On desktop (chrome: Version 62.0.3202.94) generated divs are blurry ( I am using standard CSS properties and none of these are listed in unsuported ).
On android 5.1.1 (chrome ) generated base64 code is totally unusable, Image is fully yellow, with no elements.

android base64 image: 
![flkdz5](https://user-images.githubusercontent.com/26868076/33899823-f3f58db2-df6c-11e7-9493-5fc9e6387570.jpg)

pc base64 image:
![kon9qn](https://user-images.githubusercontent.com/26868076/33899825-f41602cc-df6c-11e7-9b53-912bc59bf41f.jpg)

html: 
![dffqbp](https://user-images.githubusercontent.com/26868076/33899826-f4351450-df6c-11e7-97f3-61118874740e.jpg)

**Comment by niklasvh** [comment]
Could you share the html/css on jsfiddle and I'll try and replicate the issue.

**Comment by NormanTUD** [comment]
For anyone experiencing the same: the problem seems to be that the canvas.toDataURL function doesnt work as expected on android. A solution around this is using toBlob:

```
        var canvas = document.getElementById(id + "_canvas");

        canvas.toBlob(function(blob) {
                var img_tag = document.getElementById(id + '_img');

                const url = URL.createObjectURL(blob);
                //log(url);

                img_tag.onload = function() {
                        // no longer need to read the blob so it's revoked
                        URL.revokeObjectURL(url);
                };

                img_tag.src = url;
        });
```

Maybe this can help someone someday.

**Comment by lebnd** [comment]
Thank you @NormanTUD, it did help!

In case anyone needs the output of the toDataURL method, here is my full workaround:

```
        function getDataUrlPngFromCanvas(canvas, callback) {
            // iOS
            if (navigator.platform.substr(0,2) === 'iP' ) {
                return callback(canvas.toDataURL());
            }

            // Android workaround for quirky devices
            canvas.toBlob((blob) => {
                var reader = new FileReader();
                reader.readAsDataURL(blob);
                reader.onloadend = function() {
                    callback(reader.result);
                }
            });
        }
```
