### ISSUE TITLE
how to solve this problem for crossdomain?

### ISSUE THREAD

**Issue by sqlora** [niklasvh/html2canvas#1310]
our web include the js，just like so:
`<script src="//widget.manychat.com/324379134573193.js" async="async">`
we use html2canvas.js that cannot capture the result, But It show the blank. in fact，when you have logined facebook, the js will show the usename。we want to capture the web image include the usename。
 Is it ok?  thanks a lot!

**Comment by niklasvh** [comment]
Please share an example on jsfiddle
