### ISSUE TITLE
Uncaught (in promise) Provided element is not within a Document

### ISSUE THREAD

**Issue by cjcortez** [niklasvh/html2canvas#1313]
What is the meaning of this error? and how to fix it

**Comment by niklasvh** [comment]
The element you are trying to render is not within the Document DOM

**Comment by cjcortez** [comment]
So how to fix this issue?

0.5 is fine but when I upgrade to 1 I got this error

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by abdellatif05** [comment]
html2canvas.min.js?734316149:6 Uncaught (in promise) Provided element is not within a Document

**Comment by RaghavPrabhu** [comment]
I have tried to load the html2canvas js (version 1) and my app js after the HTML body and this issue got fixed for me.

**Comment by Digambarmalla** [comment]
Does anyone got a fix for this issue, I have the same problem.

**Comment by smartbepl** [comment]
If you use jQuery to find DIV use 
html2canvas($("#element")[0]).then(function(canvas) {
    $("#element-out").append(canvas);
});

**Comment by Digambarmalla** [comment]
But I am unable to take image of google map using html2canvas, Can anyone help me out how to do the same in cshtml ???

**Comment by niklasvh** [comment]
@cjcortez @RaghavPrabhu  does smartbepl's solution above fix it for you presuming you are using jQuery or some other library that provides a list of elements instead of a single `Element`?

**Comment by jeremielodi** [comment]
This works for me!
 html2canvas($('#div').get(0)).then( function (canvas) {
   console.log(canvas);
});

**Comment by m2shash** [comment]
thanks it worked

**Comment by lorkel** [comment]
@jeremielodi Thank you, this was driving me nuts!

**Comment by schrepel** [comment]
I tried code similar to the above, but maybe the error I'm getting isn't quite related: Uncaught (in promise) undefined... Promise rejected (async)

**Comment by ikemike** [comment]
I was having the exact same problem - I wanted to call HTML2Canvas on button click. No matter how I wrote the HTML2Canvas call, I would get an "Uncaught (in promise) undefined...Promise rejected (async)" error. Finally, I learned a little bit about how promises work and found the solution was adding a catch:

```
function myFunction() {
    html2canvas(document.querySelector("#capture")).then(canvas => {          
        	var base64encodedstring = canvas.toDataURL("image/jpeg", 1).replace("data:image/jpeg;base64,", "");
        	j$("[id$='inputHidden']").val(base64encodedstring);
        	console.log('Saving...');
        	mySaveFunction();
        })
    	.catch(function (error) {
        	/* This is fired when the promise executes without the DOM */    
    	});
}
```
Word of warning, I'm a total javascript novice and understand very little about how promises work. My code worked fine without the .catch() if I used it outside of a function. I'm assuming that somehow, when you encapsulate it, it no longer has the correct DOM access and the promise fails.

**Comment by jeremielodi** [comment]
@ikemike this can help you
```html
<html>

<head>
  <title>html2canvas</title>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>

</head>
<style type='text/css'>
  #test {
    height: 40px;
    border: 1px solid #001;
    width: 40px;
    background: red
  }
</style>

<body>

  <div id='test' style=''>


  </div>

  <img src='' alt='' id='img' />


  <script>
    html2canvas($('#test').get(0)).then(function (canvas) {

      var base64encodedstring = canvas.toDataURL("image/jpeg", 1);

      $('#img').attr('src', base64encodedstring);
    });
  </script>

</body>

</html>

**Comment by bandacs** [comment]
@niklasvh with latest version of html2canvas I am getting Uncaught (in promise): undefined error. Can you please help me.

![image](https://user-images.githubusercontent.com/11038829/38072771-8b255f0e-32ed-11e8-856d-5f07dc0b9726.png)

![image](https://user-images.githubusercontent.com/11038829/38072801-aed3a582-32ed-11e8-9f70-371ef8a35233.png)

**Comment by yihuiluo235** [comment]
ths，it works

**Comment by leandrocgsi** [comment]
This works fine for me:

    function downloadURI(uri, name) {
        var link = document.createElement("a");

        link.download = name;
        link.href = uri;
        document.body.appendChild(link);
        link.click();
        clearDynamicLink(link); 
    }

    function DownloadAsImage() {
        var element = $("#table-card")[0];
        html2canvas(element).then(function (canvas) {
            var myImage = canvas.toDataURL();
            downloadURI(myImage, "cartao-virtual.png");
        });
    }

**Comment by joniel** [comment]
in chrome, it works fine, but in IE10, doesn't work... T_T;

> Uncaught (in promise): undefined error

**Comment by impactcolor** [comment]
I'm using 1.0 alpha 12 release and I'm having the same problem.  I've tried all of these solutions.

I've tried this solution by @smartbepl
html2canvas($("#element")[0]).then(function(canvas) {
$("#element-out").append(canvas);
});

I tried this by @jeremielodi
html2canvas($('#div').get(0)).then( function (canvas) {
console.log(canvas);
});

I also tried leandrocgsi solution and tried adding a catch as @ikemike  suggest.

To simplify it and ensure all elements are loaded on the DOM, I place a function called take_screenshot().   

function take_screenshot()
{
  html2canvas($(".image__container")[0]).then(canvas => {
      console.log('please work I am loosing my mind');
      });
}

I get the same error Uncaught (in promise) undefined.

**Comment by rashidhamid21** [comment]
I have exactly the same issue that faced by https://github.com/niklasvh/html2canvas/issues/1313#issuecomment-377132089

**Comment by dryqiao** [comment]
why i failed in cheerio? 
```
 superagent
   .get(url)
   .end((err, res) => {
       cheerio.load(res.text)
       html2Canvas($('#statuses').get(0), {
           allowTaint: true
       }).then(function(canvas) {})
})
Uncaught (in promise) Error: Element is not attached to a Document
```

**Comment by 1der1** [comment]
There is another calling convention now.
Version 0.5 expected the node in an array, while you now give it directly.
Version 0.5 had the "onrendered" option, while you now use the "then" construct.
