### ISSUE TITLE
Exclude elements from rendering

### ISSUE THREAD

**Issue by ividyon** [niklasvh/html2canvas#1316]
html2canvas version tested with: 1.0.0-alpha.4
Browser & version: Google Chrome 63.0.3239.84 64-bit
Operating system: Windows 10

Hey,

the old version of this script used to have an option to exclude certain elements from being rendered by html2canvas, which was useful for admin menus & other static stuff. Now, it's gone. Anything I can do to replicate the functionality?

**Comment by ividyon** [comment]
Nevermind, this is still present through the attribute `data-html2canvas-ignore`! However, it should at least be documented (again) or something.

**Comment by niklasvh** [comment]
Yep, it should get documented. Will get that fixed asap
