### ISSUE TITLE
element-ui 1.x table border been lost

### ISSUE THREAD

**Issue by guoyongqiang** [niklasvh/html2canvas#1317]
version: 1.0.0-alpha.4
<img width="536" alt="2017-12-15 10 58 58" src="https://user-images.githubusercontent.com/17866784/34024823-4d9bc5f4-e187-11e7-8294-93927b1474e7.png">

Question:
1. table cell border has gone
2.can not take cell contents to next line properly

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/ea6062c85b5b9f4cc6f7da7591f164737d8889f6
