### ISSUE TITLE
Chrome: Uncaught (in promise)

### ISSUE THREAD

**Issue by stevenliebregt** [niklasvh/html2canvas#1319]
Tested in:
 * Latest Chrome (stable)
 * Latest Chromium
 * Latest Firefox Developer Edition

I made a little something using html2canvas ([stevenliebregt.github.io/html2png](stevenliebregt.github.io/html2png)). I use html2canvas to create a png of the preview window. Locally this works great, but when hosted on GitHub Pages, the image is cut of at the bottom and the console gives me an `Uncaught (in promise)` without any further info.

It does work fine hosted on GitHub Pages on Firefox Developer Edition though.

**Comment by niklasvh** [comment]
It's working fine for me in Chrome. To get more detailed info about the error, use the non-minified version of the library.

**Comment by StevenLiebregt** [comment]
I now use the non-minified version, the error message says: unable to load image. Once again, it works fine in firefox-developer, but fails in google-chrome-stable

**Comment by niklasvh** [comment]
Are you using any browser extensions? If so, could you try turning them off?

**Comment by StevenLiebregt** [comment]
Found out the issue, the Chrome Grammarly Plugin probably does something to the textareas, which breaks the image capturing.

**Comment by niklasvh** [comment]
Ideally, extensions wouldn't break the rendering though. Will keep this open as something to look into.

**Comment by LasithaPrabodha** [comment]
I also get this error.

**Comment by LasithaPrabodha** [comment]
There should be a catch handler in the promise call in line 166 in Clone.js. 

`this.resourceLoader.cache[iframeKey] = getIframeDocumentElement(node, this.options).then(function (documentElement) {`

Fixed it by adding it. @niklasvh @StevenLiebregt

**Comment by sebastiendan** [comment]
@LasithaPrabodha 's solution works for me as well. Is there any chance to push a new tag with the fix?
