### ISSUE TITLE
Cross Domain images not rendering (No CORS or proxy)

### ISSUE THREAD

**Issue by Onlylonger** [niklasvh/html2canvas#1323]
@niklasvh Here is my example on codepen with v1.0.0:
https://codepen.io/Onlylonger/pen/ppjPKX
the same quesiton . thx you

**Comment by niklasvh** [comment]
useCORS: true

https://codepen.io/anon/pen/LeGzPP

**Comment by Onlylonger** [comment]
![image](https://user-images.githubusercontent.com/19505200/34136490-14965dc4-e4a1-11e7-8899-631d78ea3d61.png)

**Comment by Onlylonger** [comment]
oh, sry, i found that by search;
![image](https://user-images.githubusercontent.com/19505200/34136624-c97a23e2-e4a1-11e7-9a77-cbb927bd8c0c.png)

**Comment by niklasvh** [comment]
Your are right, the documentation should get updated

**Comment by Hanzofm** [comment]
This not work on safari browser(ios)?
