### ISSUE TITLE
IE & FireFox Issues: Rendering 

### ISSUE THREAD

**Issue by Nuttiwut-Simsiri** [niklasvh/html2canvas#1326]
I try export Tree chart using treant-js to pdf files. Your library is working well on Chrome  but Not working on IE and Firefox.Problem is the line in tree chart is missing. 
Chrome:
![image](https://user-images.githubusercontent.com/13976676/34153826-056f48c0-e4e6-11e7-8941-43abe858844f.png)
RESULT: PDF FILE
![image](https://user-images.githubusercontent.com/13976676/34153893-3adace30-e4e6-11e7-9c21-a33632be0f39.png)

RESULT ON FIREFOX AND IE:
 ![image](https://user-images.githubusercontent.com/13976676/34153949-6b0c907a-e4e6-11e7-848f-539228954b0e.png)

 IE:
![image](https://user-images.githubusercontent.com/13976676/34188130-4f1d0788-e567-11e7-882e-564952ab271f.png)
FireFox:
![image](https://user-images.githubusercontent.com/13976676/34187200-c75e1d9a-e562-11e7-9cd5-a63282a0f321.png)
Chrome:
![image](https://user-images.githubusercontent.com/13976676/34187170-9b52ccd2-e562-11e7-9d69-7c505a87ce20.png)

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues 

### Bug reports:
http://jsfiddle.net/hv5yfe3c/3/
### Specifications:
 * html2canvas version tested with: v1.0.0-alpha.4
 * Browser & version: IE updated verisons 11.0.49,Chrome Version 63.0.3239.108,Firfox 57.0.2
 * Operating system: Windows 8.1 Pro

**Comment by vincekd** [comment]
I'm having the same issue with svg.

Chrome:
![comparison](https://user-images.githubusercontent.com/641433/34220993-7b678f58-e584-11e7-9e00-ed39f0a96049.png)

Firefox:
![comparison](https://user-images.githubusercontent.com/641433/34221005-835fc2e8-e584-11e7-9891-bc919d2238eb.png)

**Comment by vincekd** [comment]
Fixed when I upgraded to version `1.0.0-alpha.4`. Thanks!

**Comment by DodoSerebro** [comment]
I am having a similar problem. I have a card which has 2 svgs. One on top and one on the bottom (as shown).

On Firefox, whenever I generate the Canvas, the BOTTOM svg, is NOT being rendered at all. on Opera / Chrome / Edge, all svgs / images are being rendered correctly. I am using the latest version but with no avail.

Any ideas?
This is the Original (Chrome / Opera / Edge all perfect) 
![Original](https://user-images.githubusercontent.com/6806641/34299118-84c1d362-e721-11e7-8668-d2783e20c703.jpg)

What is being rendered on Firefox 
![Firefox](https://user-images.githubusercontent.com/6806641/34299119-84dd9548-e721-11e7-8339-a2b147020c62.jpg)

**Comment by JEEVANJGA** [comment]
Facing the same issue mentioned by @Nuttiwut-Simsiri .
In chrome its working perfect, In IE 10 it's not rendering the tree node connectors.

using npm package => "html2canvas": "^1.0.0-alpha.12"
