### ISSUE TITLE
I can't take a screenshot changed iframe.

### ISSUE THREAD

**Issue by jinkyun** [niklasvh/html2canvas#1327]
* html2canvas version tested with: 0.5.0-beta4
 * Browser & version: 60.0.3112.113
 * Operating system: ubuntu

I modify tag in iframe.

example, 
I add display none in tag
I change value in textarea.

but I can't take a screenshot changed iframe.
I can only take a screenshot the first loaded iframe.

**Comment by niklasvh** [comment]
Issues for < 1.0.0 won't be addressed.

**Comment by robinjos333** [comment]
- Version : html2canvas 1.0.0-rc.5
- Firefox version : 71.0 (64-bit)
- Ubantu 18

Issue still exist in case of iframe. I have typed values in text fields inside iframe after page load, but the screenshot doesn't contain the changed text values or frame content.
While using multiple iframes as tabs, it can't identify the current active tab while taking the screenshot. Screenshots are captured with the default tab even if it is hidden in current screen.
