### ISSUE TITLE
Content after image is false rendered

### ISSUE THREAD

**Issue by TrivoXx** [niklasvh/html2canvas#1328]
Hi,
I have tried to create an screen of an site where an image is in header and a form is below the image.
But this don't work if there is an image before the inputs. On rendering the input field are allways empty.
If I remove the image all is good. I have tested it with local image and also with remote image.

You can test it self here:
https://liveweave.com/cJykDi

**Comment by niklasvh** [comment]
This was fixed with https://github.com/niklasvh/html2canvas/commit/79e1c857e63837e4459ba9c82d1c5f3a25beb48c
