### ISSUE TITLE
Google Street View renders black

### ISSUE THREAD

**Issue by iti888** [niklasvh/html2canvas#1330]
### Bug reports:
Could not do screenshot of Google Street View. Example in jsfiddle below:

https://jsfiddle.net/iti888/cro7fvz5

Just click on the screenshot button.

It does not looks like it is a CORS issue. (Have used proxy, and same problem)
Changed foreignObjectRendering to true or false, same issue.
Looks to me that html2canvas just does not know how to download StreetView images.

### Specifications:

 * html2canvas version tested with: 0.5 beta4, 1.0 alpha 4
 * Browser & version: Firefox 57.02, Chrome 63.0.3239.84  IE 11.0.96

**Comment by iti888** [comment]
Just an update of this Issue. 
This is definitely a BUG of 1.0 apha4.
I tried DanielZhao1990's fix in https://github.com/niklasvh/html2canvas/issues/1243 for 0.50 Beta4 (with Zhao's modification)
It renders the street view correctly.  
I modify 1.0 Alpha 4 the same way, but it does not work.

**Comment by iti888** [comment]
Any solution yet? 
It works on Edge only now for https://jsfiddle.net/iti888/cro7fvz5
It was working for 1.0 Alpha 5+ in IE 11 and Chrome 63 for a few days and not working again. Anyone know what is the reason for this to be working one day and not the other?

**Comment by XaphanBael** [comment]
I'm having the exact same issue, subscribed

**Comment by iti888** [comment]
still not working with 1.0 Alpha 10

**Comment by torresdaniel11** [comment]
Has anyone been able to solve this?

**Comment by torresdaniel11** [comment]
i found a solution using the static street view api

[https://developers.google.com/maps/documentation/streetview/intro?hl=es-419](url)

what i do is create a listener on the pitch and the heading of the street view, and right in the moment i need to take a screenshot i change streetview for the image returned in the api ( which is a static image), take the screenshot and after that i swap again the image for streetview

**Comment by percperc** [comment]
We also had this issue. Its not ideal but disabling Hardware Acceleration in Chrome fixed this issue.

**Comment by IDC-Farhan** [comment]
has someone found the solution yet?

**Comment by hedani** [comment]
It's 2019, this issue still open! 
Because this doesn't fixed yet, I made some workaround to capture street view image, this how do I do that and this may help someone has the same issue:
I used the static street view of google map 
https://developers.google.com/maps/documentation/streetview/intro
and save the image that I want, by passing the position, pitch and heading
https://maps.googleapis.com/maps/api/streetview?size=600x300&location=46.414382,10.013988&heading=151.78&pitch=-0.76&key=YOUR_API_KEY&signature=YOUR_SIGNATURE

**Comment by iti888** [comment]
@HossamCould you provide an example in jsfiddle.netThanks

    On Sunday, September 1, 2019, 11:48:40 PM PDT, Hossam <notifications@github.com> wrote:  
 
 
It's 2019, this issue still open!
Because this doesn't fixed yet, I made some workaround to capture street view image, this how do I do that and this may help someone has the same issue:
I used the static street view of google map
https://developers.google.com/maps/documentation/streetview/intro
and save the image that I want, by passing the position, pitch and heading
https://maps.googleapis.com/maps/api/streetview?size=600x300&location=46.414382,10.013988&heading=151.78&pitch=-0.76&key=YOUR_API_KEY&signature=YOUR_SIGNATURE

**Comment by aecuman** [comment]
Has anyone fixed this issue yet.... Having the same problem
![marble-diagram (4)](https://user-images.githubusercontent.com/12677832/80034133-97b0f780-84f6-11ea-80d1-b53a6b5333e0.png)

**Comment by tequilacat** [comment]
As I understand after stumbling upon the issue:
Turning hardware acceleration off fixes the issue but forces one's users to degrade overall performance for a particular webapp sake. I could not find how to force GoogleMaps to use older approach (pre-webgl).

Looks like when browser acceleration is ON, the background is rendered on WebGL canvas which has 2 interchangeable buffers, and the current one contains meaningful data only right after rendering (done by Google libs). If accessed later it's all zeroes. Unless it's possible to hook on google renderer it seems problematic to resolve the issue.

If anyone knew how to disable the webgl in google street view, it would help immensely.

**Comment by tequilacat** [comment]
The fix #2661 does not actually fix the bug, but explains why the map is not rendered.

I found a solution that works in my case (inlining the snippet in head/script tag on the page containing street view that was rendered black):
https://github.com/greggman/webgl-helpers#webgl-force-preservedrawingbufferjs

**Comment by niklasvh** [comment]
Thanks for the link @tequilacat, that can be a useful method in many cases where you don't control the creation of the webgl context. 

For clarity, there is nothing this library can do to fix this issue. Even an override like the one you linked would have to be executed before the webgl is created, which isn't in html2canvas control.

**Comment by tequilacat** [comment]
> Thanks for the link @tequilacat, that can be a useful method in many cases where you don't control the creation of the webgl context.
> 
> For clarity, there is nothing this library can do to fix this issue. Even an override like the one you linked would have to be executed before the webgl is created, which isn't in html2canvas control.

Absolutely. It's a complementary method to work around this specific issue. The html2canvas works when the context is already created and cannot be configured. Also this workaround affects all the 3d rendering on the page, that's why "works in my case".

Thanks for the library, this helped me immensely.

**Comment by cturan** [comment]
> The fix #2661 does not actually fix the bug, but explains why the map is not rendered.
> 
> I found a solution that works in my case (inlining the snippet in head/script tag on the page containing street view that was rendered black): https://github.com/greggman/webgl-helpers#webgl-force-preservedrawingbufferjs

This one work perfectly.
