### ISSUE TITLE
XSS Scripting issues in the version 0.5-0.Beta4

### ISSUE THREAD

**Issue by RCBAN** [niklasvh/html2canvas#1334]
Hi,
We've been using the version 0.5-0.Beta4

Error Description : 
"The method l() in html2canvas.min.js sends unvalidated data to a web browser on line 14, which can result in the browser executing malicious code"
Due to our organization rules, this version does not pass the DOM cross site scripting issues...

Do you know any version addresses this concern ?

**Comment by niklasvh** [comment]
Could you share the unminified function name? I presume it's for loading the proxy content.

**Comment by RCBAN** [comment]
function absoluteUrl(url) {
    var link = document.createElement("a");
    link.href = url;
    **link.href = link.href**;
    return link;
}
the 4th bold line has the issue..

**Comment by niklasvh** [comment]
In which situation does assigning the href property of an anchor element introduce XSS, from a value which already exists in the current DOM?

**Comment by RCBAN** [comment]
link.href = link.href;
as info..removing above line worked for us..
