### ISSUE TITLE
OrgChart renders lost border

### ISSUE THREAD

**Issue by spiritree** [niklasvh/html2canvas#1336]
### Bug reports:

https://jsfiddle.net/spiritree/74df4hnp/

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.5
 * Browser & version: Chrome64
 * Operating system: macOS 10.13

It worked well with version 0.5.0-beta.4

**Comment by spiritree** [comment]
That works for me #1339

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/ea6062c85b5b9f4cc6f7da7591f164737d8889f6
