### ISSUE TITLE
Chrome / Opera - Weird letter spacing for long-text split into 2+ lines? 

### ISSUE THREAD

**Issue by DodoSerebro** [niklasvh/html2canvas#1337]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)

I have a card which is 8.6cm x 5.4cm consisting of multiple divs / images / svgs. 

I have noticed that sometimes, when I'm at 100% zoom and I export the Canvas to PDF using jsPDF, the "letter-spacing" is a bit abnormal as shown below. I do not know if this is a html2canvas issue or jspdf but this particular issue only happens on Chrome-based Browsers.  This does not happen to all text within the document. What MAY be the cause is that this is a **long line of text which is automatically being split into two lines due to overflow**. Could this be the issue?

PS - I have NOT set any Letter spacing css or styling wise. 

This is what happens at 100% zoom:
![test3](https://user-images.githubusercontent.com/6806641/34299537-d228a822-e723-11e7-9bf6-183ad4a78f77.PNG)

When I Browser zoom at for e.g. 110% or over, the spacing are better as shown below
![image](https://user-images.githubusercontent.com/6806641/34299549-e94595ec-e723-11e7-90b4-9cdfe41eae1b.png)

 Any idea how I can solve it please? 

### Specifications:

 * html2canvas version tested with: v1.0.0-alpha.5
 * Browser & version: Latest Stable Opera  / Latest Stable Chrome
 * Operating system: Windows 10

**Comment by andreasvirkus** [comment]
@niklasvh  I think this issue is related to https://github.com/niklasvh/html2canvas/issues/1849
