### ISSUE TITLE
Blank input fields

### ISSUE THREAD

**Issue by jelkins8** [niklasvh/html2canvas#1338]
In the current alpha the input fields are showing empty in the image:

![image](https://user-images.githubusercontent.com/15841487/34306569-856ee218-e709-11e7-953f-2bec1bb758b4.png)

Specifications:
html2canvas version tested with: v1.0.0-alpha.5
Browser & version: Chrome
Operating system: Windows 10

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by jelkins8** [comment]
I created a plunker and in testing I find that with half the form commented out the fields are saving with data but with the whole form they are not:
https://plnkr.co/edit/JRd1NISDazVhbHDQa0Oc?p=preview

**Comment by niklasvh** [comment]
Thanks for the example and the detail regarding the form size, helped a lot to narrow down the issue.
