### ISSUE TITLE
style "border-bottom" lose

### ISSUE THREAD

**Issue by suyingtao** [niklasvh/html2canvas#1339]
Does the style "border-bottom" is supported?

### Specifications:
html2canvas version tested with: v1.0.0-alpha.5
Browser & version: Chrome
Operating system: macOS

**Comment by suyingtao** [comment]
### solution: 

replace the code 

```
var renderableBorders = container.style.border.filter(function (border) {
                return border.borderStyle !== _border.BORDER_STYLE.NONE && !border.borderColor.isTransparent();
            });
```

to 

`var renderableBorders = container.style.border;`

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/ea6062c85b5b9f4cc6f7da7591f164737d8889f6
