### ISSUE TITLE
list-style:none  show decimal in canvas created by html2canvas  but normal in browser

### ISSUE THREAD

**Issue by bailihua93** [niklasvh/html2canvas#1340]
the latest version；
+ html
   ul>li*10      
+  css
   li{ list-style-type:none}

result  just like
   li{list-style-type:decimal}

**Comment by digitalkrafter** [comment]
Dear Team

i am using latest version of html2canvas for making HTML save as PDF , in that HTML i am using tabs those tabs rendered as list items in canvas
but in your recent commit you told lists are render properly
Can you please look over it once again
for your reference here i attach image

![resultsfile](https://user-images.githubusercontent.com/8259634/34385183-f5865b26-eb46-11e7-8719-f55f5074eaeb.png)
