### ISSUE TITLE
Uncaught (in promise) Provided element is not within a Document

### ISSUE THREAD

**Issue by yuanye097** [niklasvh/html2canvas#1341]
`var $poster = $("#poster");
var $shareImage = $("#shareImage");
var $generate = $("#generate");
var $generateClose = $("#generateClose");
var $msgImage = $("#msgImage");
var $saveImage = $("#saveImage");

$poster.on('click', function(event) {
    event.preventDefault();
    var width = $msgImage.outerWidth();
    var height = $msgImage.outerHeight();
    var type = "png";
    var canvas = document.createElement('canvas');
    var context = canvas.getContext('2d');
    var ratio = getPixelRatio(context);
    canvas.width = width * ratio;
    canvas.height = height * ratio;
    canvas.style.width = width * ratio + 'px';
    canvas.style.height = height * ratio + 'px';
    context.scale(ratio, ratio);
    console.log(width, height,ratio);
    html2canvas($msgImage, {
        canvas: canvas,
        useCORS: true,
        scale: 2,
        allowTaint:true,
        height: height,
        width: width,
        onrendered: function(canvas) {
            var dataUrl = canvas.toDataURL();
            console.log(dataUrl);
            $shareImage.attr("src", dataUrl);
            $generate.show();
        }
    });

});`Click the button error

**Comment by niklasvh** [comment]
`$msgImage` is not an `Element`. https://developer.mozilla.org/en-US/docs/Web/API/Element
