### ISSUE TITLE
How do you optimize HTML2Canvas output images?

### ISSUE THREAD

**Issue by 1-2-1** [niklasvh/html2canvas#1342]
I'm sure this isn't a bug and instead an end-user lack of knowledge issue.

Here's the scenario, I create an image (I've tried png (8 & 24 bit), jpg (various quality levels) and gif (dithered and non dithered) as the source images on a webpage.  

In practice I overlay text and then use HTML2canvas to create an image with the text.  However the image produced is multiple times larger in KB than the initial image.  

To isolate, I did no text overlay and just let HTML2Canvas save the image.  I did a series of tests with no text and varying the source image type (all the same size, eg. 200x600).

However, I ended up with files that originally were 6KB becoming 14.1KB and 46KB file bloating to 265KB.

If I take the output image from Html2Canvas and process via Photoshop 'save for web' then I get the image size back to essentially the same as the source with no visual degradation.

Is there a way to do this already in html2canvas that I am overlooking?

If not, is this something that is best to via a separate method?

Thank you

**Comment by niklasvh** [comment]
Are you using `scale: 1`? For jpeg output, you can define the quality level (as you mentioned), but apart from that I don't really know what else can really be done, (or is in the scope of html2canvas).

**Comment by 1-2-1** [comment]
Thank you for your feedback. 

We should be using scale 1, so I will look for another way to process the images after HTML2Canvas produces them.

Thank you again
