### ISSUE TITLE
html2canvas is not working in Ipad/iPhone iOS 11.2.1 Safari borwser

### ISSUE THREAD

**Issue by chetanwaghfx** [niklasvh/html2canvas#1344]
Hi,

I have use html2canvas function for capturing screen shot from div its working fine on web but its not working in Ipad iOS 11.2.1 Safari browser getting blank response.
I have using Ipadair2 with iOS 11.2.1

Include JS Version:
jQuery v1.7.1 jquery.com
html2canvas 0.4.1 <http://html2canvas.hertzen.com>
html2canvas 0.5.0-alpha1 <http://html2canvas.hertzen.com>

Here the HTML code:

```
<div id="pdfContent" class="pdfContent" style="transform-origin: left top 0px; transform: scale(1);" crossOrigin="Anonymous">
        <img id="hotspotimg" src="img.jpg" cropwidth="1000" cropheight="600"/>
        <div id="editor"></div>
</div>

```

Here the JS code:

```
html2canvas(document.querySelector('#pdfContent'), {useCORS: true}).then(function (canvas) {
		    try {
		        var imgageData = canvas.toDataURL("image/png");
                          } catch (err) {
		      console.log(err)
		      alert(err)
		    }
        }).catch(function onRejected(error) {
        	alert(error);
}); 
```

I have tried multiple github solution like
[](http://avarachan.com/test2.html)
and other links but not working on Ipad/iPhone

**Please help me:**

Contact us: wagh.chetan@fxbytes.com

**Comment by niklasvh** [comment]
> Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

**Comment by chetanwaghfx** [comment]
I have added latest version v1.0.0-alpha.6 but getting same problem in Ipad

**Comment by chetanwaghfx** [comment]
Hi @niklasvh 

I have added latest version of v1.0.0-alpha.7 html2canvas but getting problem in Ipad  iOS 11.2.1 for second time use html2canvas function getting blank response.
