### ISSUE TITLE
Safari loses styling after screenshot

### ISSUE THREAD

**Issue by chulander** [niklasvh/html2canvas#1346]
The issue was solved by the solution [here](https://github.com/niklasvh/html2canvas/issues/504) by @cloakedninjas. It took me a while to find the solution and am reposting this for anyone else searching for an answer.

My question is why was the solution never merged into master when replaceChild is causing an issue in Safari?

**Comment by niklasvh** [comment]
All the Safaris I've tested with work fine, so I'd need more details on how to actually replicate the issue. 

Which Safari versions, on what OS? Do you have an example HTML/CSS where this occurs?

**Comment by chulander** [comment]
Thanks for response @niklasvh. i'll create a sample / demo to illustrate

**Comment by eKoopmans** [comment]
Hi @chulander @niklasvh, I had a closer look at the fix from @cloakedninjas in #504, which replaces:
```js
documentClone.replaceChild(documentClone.adoptNode(documentElement), documentClone.documentElement);
```
with
```js
documentClone.write(documentElement.outerHTML);
```

Unfortunately it's not a viable solution. Using `outerHTML` loses any element attributes that aren't hard-coded into the HTML. Here's a simple illustration (try changing the text in the input field, then hitting clone): [Fiddle](https://jsfiddle.net/9oujuyee/)

Please do provide an example so we can see what's going on - you can start by forking [this Fiddle](https://jsfiddle.net/v6bgw5y5/), which has the latest html2canvas loaded as an external resource.

**Comment by eKoopmans** [comment]
For what it's worth, I did a bit of research but didn't find much:

- related issues: #504, #1014, #1110
- from [@cloakedninjas comment](https://github.com/niklasvh/html2canvas/issues/504#issuecomment-70106751), issue is related to pseudo-elements:
   > document.replaceChild and document.adoptNode causing the original DOM to lose style context, some :before and :after nodes would be lost because the CSS that created them was no longer present, even though the HEAD element remains unchanged.
- it [seems like](https://github.com/Polymer/polymer/issues/2157) there's some Polymer/webcomponents issue with Safari, `importNode`, and `<template>`, but I don't think it's related
- haven't found anything else with `replaceChild` or `adoptNode` causing styling to break

**Comment by niklasvh** [comment]
@eKoopmans Thanks for the additonal details!

@chulander An example that I could replicate the issue with would help me try and find a working fix (including which versions/OS to use).

**Comment by niklasvh** [comment]
@chulander An unrelated fix was made for copying styles (https://github.com/niklasvh/html2canvas/commit/4c14894a0a314d65b7c02860fa809dbae57d563d). This could however have an impact on your issue.

**Comment by hasanAli9t** [comment]
I am facing same issue with the safari browser. After dragging image and capture screen shot it breaks the layout and does not maintain aspect ratio on image as well. however it is working fine on chrome. Is there any solution ?
Thank you.
