### ISSUE TITLE
Text in input or textarea not capturing text. 

### ISSUE THREAD

**Issue by hasanAli9t** [niklasvh/html2canvas#1347]
Hello, 
I am trying to capture div with image and textarea text(user input) in it. but it show me only image which is in div and showing blank text which is inside the same div. Cannot able to figure out how to capture text with latest version.
Thank you for any help!

I am trying to capture that on blur. when user input and focus out/blur it should capture text.

Here is code i am trying :
$(document).on('blur', '.image-text', function(event) {
        var divTakeSnapshot = '.book-layouts';
        var setTakenSnapshot = '.thumbnail-preview';
        html2canvas($('.class').find('.div-class-to-take-snapshot').then(function(canvas) {
            $('.class').find('.div-class-to-set-snapshot').attr('src', canvas.toDataURL("image/png"));
    });

it capturing blank textarea. but showing image.

**Comment by zhoubin-gz** [comment]
I used the latest version of the test there is the same problem

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/79e1c857e63837e4459ba9c82d1c5f3a25beb48c

**Comment by hasanAli9t** [comment]
yes @hacknug  it was fixed and still working for me. Please show us your snippet so that we can help you better.

**Comment by fetishcoin** [comment]
Hi, @hasanAli9t 
I also face with same problem now with 1.0.0-alpha.11.
Both input type="text" and textarea cannot rendered correctly.

JS
```
function screenshot(selector) {
    var element = $(selector)[0]; // get target element (div)
    html2canvas(element).then(function(canvas) {
    var imgData = canvas.toDataURL();
    $('#screen_image')[0].src = imgData;
    $('#download')[0].href = imgData;
    $('#download')[0].innerHTML = "Download";
    });
}
```

Full code is [here](https://github.com/fetishcoin/fetishcoin.github.io/blob/master/partners.html):

Perhaps, canvas.toDataURL() should not be used?
same origin image cannot render too.

Thanks.

**Comment by aarangara** [comment]
This not working for me as well, it captures the screenshot of input box but that does have the value typed into the box. As a workaround, I get the value from input box into a div and then capture that div

**Comment by senaytekle** [comment]
> 
> 
> This not working for me as well, it captures the screenshot of input box but that does have the value typed into the box. As a workaround, I get the value from input box into a div and then capture that div

hey aarangara, can you please share more on how you were able to achieve the workaround? having the same issue in angular perhaps because angular is sanitizing the input text.

**Comment by AnatuGreen** [comment]
Please what exactly is the solution to this?

**Comment by AnatuGreen** [comment]
I checked that Github link provided but did not find the solution. However, I checked my CSS file and it happened that I gave a styling like this to my images:

```
 img {
  width: 100%;
  height: 100%;
}.
```

When I removed this styling, I started seeing the text on the capture.
