### ISSUE TITLE
border css is not appearing when converted to canvas with latest library file.

### ISSUE THREAD

**Issue by raghav141988** [niklasvh/html2canvas#1349]
Hi,
I was trying to experiment with html2canvas and earlier build was converting an HTML element to canvas successfully with all CSS applied, but with latest build quality of the converted canvas has improved significantly, however some of the CSS is not available in the finally converted canvas.

Working fiddle with earlier library version(https://cdn.rawgit.com/niklasvh/html2canvas/0.5.0-alpha2/dist/html2canvas.min.js) : http://jsfiddle.net/bLommeak/

Not working fiddle with latest library : http://jsfiddle.net/rjk3qqbd/.

Thanks for looking in to this.

**Comment by raghav141988** [comment]
Thanks for fixing this so quick ! it works fantastic 👍

**Comment by Necriis** [comment]
Is the bug back ?
http://jsfiddle.net/u8hL5tjg/

**Comment by rovanu** [comment]
> Is the bug back ?
> http://jsfiddle.net/u8hL5tjg/
any workaround for this bug in the last version?

**Comment by rovanu** [comment]
Yes, the bug is back
any workaround for this bug in the last version?

**Comment by dbalders** [comment]
Looks like it might have broken in rc2. I specified rc1 and the borders show in the image.

**Comment by srinivaselp** [comment]
Is this issue solved? I'm using https://www.npmjs.com/package/html2pdf.js which depends on html2canvas and I have no way to alter html2canvas version directly.

**Comment by Thyiad** [comment]
@dbalders It works for me, rc1 border-bottom is show in the image.

**Comment by Jerther** [comment]
Fix for rc3 is here: https://github.com/niklasvh/html2canvas/pull/1952
