### ISSUE TITLE
No support for Retina display on iPhone?

### ISSUE THREAD

**Issue by Adc100** [niklasvh/html2canvas#135]
On iPhone and Safari I'm using html2canvas to take a screenshot of a div with text and images.  It works but it's very blurry due to the retina display on iPhones.  This problem is usually easily corrected for images and canvases by using the technique below but I can't get it to work with html2canvas.  I've been modifying the canvas.width, height, and ctx.scale in Canvas.js but it's always blurry.

This works on all other canvases but not with html2canvas
var canvas = document.getElementById('pic');
canvas.width = 640;
canvas.height = 960;
canvas.style.width = "320px";
canvas.style.height = "480px";

For more information on canvas and retina see
http://zsprawl.com/iOS/2012/03/html5-canvas-and-retina-displays/
and
http://blog.iwalt.com/2010/08/generating-highresolution-graphics-with-html5s-canvas-element.html

**Comment by usmonster** [comment]
@niklasvh can this be closed in favor of #390?
