### ISSUE TITLE
html2canvas is not working in Ipad/iPhone iOS 11.2.1 and iPhone X Safari borwser

### ISSUE THREAD

**Issue by chetanwaghfx** [niklasvh/html2canvas#1350]
Hi,

I have use html2canvas function for capturing screen shot from div its working fine on web but its not working in Ipad iOS 11.2.1 Safari browser getting blank response.
I have using Ipadair2 with iOS 11.2.1 and iPhone X

Include JS Version:
jQuery v1.7.1 jquery.com
[html2canvas v1.0.0-alpha.7 ](https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-alpha.7)

Here the HTML code:

```
<div id="pdfContent" class="pdfContent" style="transform-origin: left top 0px; transform: scale(1);" crossOrigin="Anonymous">
        <img id="hotspotimg" src="img.jpg" cropwidth="1000" cropheight="600"/>
        <div id="editor"></div>
</div>

```

Here the JS code:

```
html2canvas(document.querySelector('#pdfContent'), {useCORS: true}).then(function (canvas) {
		    try {
		        var imgageData = canvas.toDataURL("image/png");
                          } catch (err) {
		      console.log(err)
		      alert(err)
		    }
        }).catch(function onRejected(error) {
        	alert(error);
}); 
```

I have tried multiple github solution like
[](http://avarachan.com/test2.html)
and other links but not working on Ipad/iPhone

**Please help me:**

Contact us: wagh.chetan@fxbytes.com

**Comment by niklasvh** [comment]
Does it work if the `img.jpg` is small? For example 100x100px

**Comment by chetanwaghfx** [comment]
It does work on the first time by Ajax call but second time by Ajax call getting blank response

**Comment by niklasvh** [comment]
Can you setup an example on jsfiddle?

**Comment by chetanwaghfx** [comment]
Ok, I will create setup on jsfiddle. And send you a link.

**Comment by jasonz1987** [comment]
i got this error on my ios devices @niklasvh 

> [Error] ERROR – TypeError: reader.addEventListener is not a function. (In 'reader.addEventListener('load', function () {
>                             return resolve(reader.result);
>                         }, false)', 'reader.addEventListener' is undefined) — vendor.js:75599
> TypeError: reader.addEventListener is not a function. (In 'reader.addEventListener('load', function () {
>                             return resolve(reader.result);
>                         }, false)', 'reader.addEventListener' is undefined) — vendor.js:75599
> 	defaultErrorLogger (vendor.js:1782)
> 	handleError (vendor.js:1843)
> 	handleError (vendor.js:145468)
> 	next (vendor.js:5853:148)
> 	（匿名函数） (vendor.js:4694)
> 	__tryOrUnsub (vendor.js:18082)
> 	next (vendor.js:18029)
> 	_next (vendor.js:17969)
> 	next (vendor.js:17933)
> 	next (vendor.js:21646)
> 	emit (vendor.js:4674)
> 	run (polyfills.js:3:10150)
> 	onHandleError (vendor.js:5130)
> 	runTask (polyfills.js:3:10900)
> 	invokeTask (polyfills.js:3:16802)
> 	p (polyfills.js:2:27655)
> 	v (polyfills.js:2:27895)
>

**Comment by chetanwaghfx** [comment]
Hi @niklasvh 
Please check this link [click](http://www.fxbytes.com/Client/markup/)

**Comment by chetanwaghfx** [comment]
Hi @niklasvh 
Please check this link and reply 
 [jsfiddle](https://jsfiddle.net/chetanfx/9mw4cd5a/)

**Comment by devxpertyst** [comment]
Hi Chetan I am also facing the same issue can you please help me out..
Here is my code :
```
function capture() 
  {
    html2canvas(document.querySelector('#target')).then(function(canvas) {
        var imgpath=canvas.toDataURL("image/png");
        document.getElementById("img_val").value = imgpath;
        document.getElementById("myForm").submit();    
    });
  }
```

**Comment by kzkhykw** [comment]
I'm also dealing with the same issue in Safari browser. I think that the problem might be caused by CORS option. Basically it works well without CORS option even though Safari.

Related articles
https://stackoverflow.com/questions/53374756/html2canvas-not-rendering-image-in-safari-browser/59512643#59512643
https://helperbyte.com/questions/277332/as-safari-to-make-it-work-with-cors-html2canvas-correctly

**Comment by pukara-prabhu** [comment]
The main problem is if you have driven the image from css class. 
example :
background: url("../assets/images/"). 

Remove this reference and add it as image tag in the html it will work

**Comment by lukesebastian** [comment]
i'm having the same issue, it works fine on any desktop browser and android devices, but not in safari. I'm using cropper.js to crop an uploaded image and preview to another image template. When i use safari it draw nothing.

**Comment by ayohewitt** [comment]
Same issue... on safari it downloads a txt file sometimes... and when it does download on safari all of the elements a messed up... Please help!
