### ISSUE TITLE
Plotly annotations are not rendered

### ISSUE THREAD

**Issue by dmorrison42** [niklasvh/html2canvas#1356]
### Bug reports:

Plotly annotations are not rendered when using html2canvas.

See https://jsfiddle.net/hsu7jnar/.

### Specifications:

 * html2canvas version tested with: v1.0.0-alpha.8
 * Browser & version: Google Chrome 63.0.3239.108
 * Operating system: Windows 7

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/4c14894a0a314d65b7c02860fa809dbae57d563d (https://jsfiddle.net/6ny1b352/)
