### ISSUE TITLE
html2canvas在截图的时候，img 的src属性值是服务器下发，导致截图不显示图片，有什么好的解决办法吗？

### ISSUE THREAD

**Issue by Realybig** [niklasvh/html2canvas#1357]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by zhuSass** [comment]
我是通过Image对象，赋值到Images的src里头，然后htmlcanvas库逻辑写在ImagesObj的onload事件里

**Comment by zhaozhuoboy** [comment]
@zhuSass 
配置项里加这个试试
useCORS: true,//允许访问服务器资源

**Comment by JackYangFM** [comment]
> @zhuSass
> 配置项里加这个试试
> useCORS: true,//允许访问服务器资源

我的画布里面有好几张图片，在浏览器上都可以显示，但是页面嵌入到iOS和Android的webview里生成截图的时候，一张后台返回的头像图片就是显示不了，不知道您有解决方案吗?我用的是vue动态渲染的img标签里的src属性

**Comment by momo-Iwillquit** [comment]
我也遇到了相同的问题，请问有方法吗？

**Comment by Fengdongxing** [comment]
图片让后端转为base64格式返回

**Comment by Fengdongxing** [comment]
图片让后端转为base64格式返回
