### ISSUE TITLE
releation to cpu or monitor resolution？

### ISSUE THREAD

**Issue by keyiis** [niklasvh/html2canvas#1360]
If i use html2canvas generator canvas with CPU(amd A8) and  monitor(1920*1280),the canvas's width always big than body actual width,even though I have set body's width
`<body style="margin:0;width:384px;height:auto;overflow:hidden;">....</body>`
so what is the impact of  canvas's width?
 * html2canvas version tested with:1.0.0-alpha.3
 * Browser & version:electron 1.7.5
 * Operating system:win10

**Comment by niklasvh** [comment]
The option `scale` is by default `window.devicePixelRatio` which may vary depending on your hardware / settings.

**Comment by keyiis** [comment]
@niklasvh thks reply!
