### ISSUE TITLE
version is logged to console

### ISSUE THREAD

**Issue by FDIM** [niklasvh/html2canvas#1363]
https://github.com/niklasvh/html2canvas/blob/b7c7464c5f19404959ea169046c5fd1b1ac357ed/src/index.js#L38

could the above line use the logger and not console directly? 

I can submit a PR if you'd like to :)

**Comment by mc-suchecki** [comment]
I was thinking about PR to that, when I saw your issue I decided to do it. 👍

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/da2794f7f773e9f4a18f6b00ba5129988610e81a
