### ISSUE TITLE
text-decoration underline is misplaced

### ISSUE THREAD

**Issue by FDIM** [niklasvh/html2canvas#1364]
### Bug reports:

http://jsfiddle.net/8rjbyqgj/

As you can see in jsfiddle, links that have a `text-decoration: underline` rule renders with a line above it

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha-8
 * Browser & version: chrome 63 & IE 11
 * Operating system: Windows 7

**Comment by niklasvh** [comment]
Related: https://github.com/niklasvh/html2canvas/pull/1292

**Comment by FDIM** [comment]
So I've looked at the values before rectangle / line is rendered and if I set baseline to 0, it renders correctly (or close enough).
https://github.com/niklasvh/html2canvas/blob/b7c7464c5f19404959ea169046c5fd1b1ac357ed/src/renderer/CanvasRenderer.js#L253

I am not certain about details, but could the fix be `Math.round(text.bounds.top + baseline)` ? bounds.height was 19 and baseline value was 17 in my case

**Comment by eKoopmans** [comment]
Hey @FDIM, thanks for finding the problem, you're right that 0c8d38d ended up causing the very error it was meant to fix. I explained a bit more [here](https://github.com/niklasvh/html2canvas/pull/1292#issuecomment-360700136).

**Comment by edguz2408** [comment]
I recently started using the last version of HTML2Canvas which should include the fix described above, however I kept getting a misplaced underline when I used text-decoration: underline just like it's mentioned at the beginning of this thread, I managed to fix the issue by modifying Math.round(text.bounds.top + text.bounds.height - baseline) to Math.round(text.bounds.top + text.bounds.height) in CanvasRenderer.js file
