### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by Realybig** [niklasvh/html2canvas#1367]
why? ![_20180105115327](https://user-images.githubusercontent.com/10878451/34594961-14fbf442-f20f-11e7-9097-b4c0d22b2d99.png)

**Comment by niklasvh** [comment]
https://github.com/niklasvh/html2canvas/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by iqmeta** [comment]
Some error here... looks like absolute div not in body cause this.
Little demo attached:
[errorExample.zip](https://github.com/niklasvh/html2canvas/files/1758613/errorExample.zip)

**Comment by mogularpb** [comment]
I am getting this problem when I pass in an element id to the function that is running html2canvas.
`const printDocument = (element) => {
  const source = document.getElementById(element)
}`

![image](https://user-images.githubusercontent.com/9523595/36708665-265f057a-1bc8-11e8-8590-d1049b037d30.png)

When I hard code the element name `const source = document.getElementById('elementId')`,  I don't get the issue

**Comment by setarbgram** [comment]
it still has problem. i replaced the new version but because of "onrendered" function i have the same problem,however i have followed this address:  https://github.com/niklasvh/html2canvas/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by vipaka** [comment]
I had this same error and it looks like its just a load order issue. Move the <div> element (whatever you're targeting) above the script call (where you load in html2canvas) and it resolves the bug.

**Comment by manikandan1987** [comment]
give us sample

**Comment by Lx15** [comment]
i have this same error now and how to fixed it , i only find the problem in Android phone

**Comment by osirion** [comment]
This was my code and I was getting this error.
`function pdfprint(selector,export_filename,quality = 1) {
    const filename  = export_filename+'.pdf';

    html2canvas(document.querySelector(selector),
        {scale: quality}
    ).then(canvas => {
        let pdf = new jsPDF('p', 'mm', 'a4');
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 211, 298);
        pdf.save(filename);
    });
}`

For me, the issue went away when i stopped used a class as a query selector - eg: ".kt-report" and used and id instead, eg: "#report-wrapper"

**Comment by alokpath-sanyal-au5** [comment]
let moveLeft = () => {
        $('#container div').last().fadeOut(1000, () => {
            $(this).insertBefore($('#container div').first()).show()
        })
    }

this is my code and I got the same error. how do i fix it?

**Comment by leqnam** [comment]
closed without solution?

**Comment by mohamedHedi1990** [comment]
I had the same problem.
I resolved it by checking the element id (I put a wrong one).

**Comment by nassamkpela** [comment]
Finally found an issue to this problem by changing this line

--> `var canvas = this.canvas.ownerDocument.createElement('canvas');`
to
--> `var canvas = this.canvas.ownerDocument?this.canvas.ownerDocument.createElement('canvas'):document.createElement('canvas');`
in the source code at line 6587 of **html2canvas.js**

I used **id selector** instead of **class** for element to print in pdf.

**Comment by 20gordone** [comment]
I had the same problem using an id: I fixed it by including '#' before the id

**Comment by Saitejad007** [comment]
> I had the same problem using an id: I fixed it by including '#' before the id

Thank you it worked. You are a lifesaver.
