### ISSUE TITLE
Can't fetch resource with file protocol

### ISSUE THREAD

**Issue by alexisrobin** [niklasvh/html2canvas#1368]
### Bug reports:

Hi guys !
I've a js app running in an Android WebView and I would like to get a sceenshot of a specific DOM element. The thing is I got troubles using html2canvas with foreignObjectRendering option activated. The DOM element's images aren't displayed in my generated image.

I've noticed that the issue's coming from XHR. The html2canvas library tries to get image through the "file://" protocol and then waits for a XHR 200 status code. The problem is that XHR status code is always 0 using the  file protocol.

So, I'm currently using a workaround by updating ResourceLoader.js (line 84):
` if (xhr.status !== 200 && xhr.status !== 0) { ... }`

Is a library update's planned to fix this issue ?

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.8
 * Browser & version: WebChromeClient in Android
 * Operating system: Android

**Comment by niklasvh** [comment]
Does the webpage have resources loaded from file://?

**Comment by alexisrobin** [comment]
Yes, it does ! That's the reason of my issue I guess.

**Comment by alexisrobin** [comment]
So @niklasvh do you think you could do a fix about this file protocol issue?
