### ISSUE TITLE
Left blank space

### ISSUE THREAD

**Issue by YoannClech** [niklasvh/html2canvas#1369]
Hi guys !

When I use html2Canvas to create a div to canva I've always a blank space on the left and the canva is truncate on the right. Anyone have this issue too and know how to solve it ?

**Specifications:**
html2canvas version tested with: 1.0.0-alpha.8
Browser & version: Chrome 63.0.3239.84
Operating system: Windows 10

**Comment by YoannClech** [comment]
Ok I find the problem. There a conflict with bootstrap classes, "content-wrapper' in my case.

**Comment by hillarykrutzsch** [comment]
Hi there, can I ask how you solved it?  I have the same issue, and a conflict with my own wrapper class, seemingly related to the wrapper class having a margin-left: auto;

**Comment by YoannClech** [comment]
Before use html2canvas I parse the dom and remove the class. After canvas creation I put back the class in the div.

**Comment by sagrawal-idrc** [comment]
@hillarykrutzsch Were you able to solve your issue? If yes, how were you? I have a left space on rendering only some of my divs and I am just not able to figure out what must be causing it.  Thanks much!

**Comment by amenadiel** [comment]
I solved it setting `margin-left` to my desired setting explicitly. It seems that using, for example `margin: 0 auto` wont do.
