### ISSUE TITLE
Test shifted in screenshot

### ISSUE THREAD

**Issue by yukkon** [niklasvh/html2canvas#1371]
I try to use your library but get text shifted on input elements on canvas, also table cells collapsed, please note that when screenshot was created page was scaled on 80%
![image](https://user-images.githubusercontent.com/5148877/34640995-4c15999c-f30e-11e7-996a-44db973031a0.png)
 
### Bug reports:
https://jsfiddle.net/tuktuk99/hncvrh8m/1/

### Specifications:

 * html2canvas version tested with: html2canvas 1.0.0-alpha.8
 * Browser & version: Google Chrome 63.0.3239.132 (Официальная сборка), (64 bit)
 * Operating system: Windows 7 64bit

**Comment by pssgo** [comment]
I also meet this question, try set line-height to fixed this;

**Comment by pssgo** [comment]
I also meet this question, try set line-height to fixed this; @yukkon
