### ISSUE TITLE
html2canvas Not working in IE 11

### ISSUE THREAD

**Issue by Prabhat2404** [niklasvh/html2canvas#1373]
Tested with latest release but still not working in IE 11. 

Trying with sample code: 

html2canvas(document.body).then(canvas => {
            document.body.appendChild(canvas)
        });

 Tested on :  Operating system: window10
  jsfiddle link: [Link](https://jsfiddle.net/prabhat2404/htm0ok32/)

**Comment by niklasvh** [comment]
IE 11 doesn't support arrow functions. Transpile your code to ES5 compliant.

**Comment by inaki-ortizdelandaluce** [comment]
You can use an online JavaScript transpiler like BableJS (https://babeljs.io/), resulting into:

"use strict";

html2canvas(document.body).then(function (canvas) {
  document.body.appendChild(canvas);
});
