### ISSUE TITLE
Can not transform a svg into canvas

### ISSUE THREAD

**Issue by 673800357** [niklasvh/html2canvas#1379]
### Bug reports:

My web page consists some svg. But when i transformit into canvas using the html2canvas, the svg can't be seen in the canvas.How can i fix it or are there some helpful methods? Thanks a lot

### Specifications:

 * html2canvas version tested with: latest
 * Browser & version: electron 1.7
 * Operating system:windows 10

**Comment by 673800357** [comment]
It seems can't transform the svg into canvas in electron?How can i fix it,thanks

**Comment by 673800357** [comment]
![tim 20180113194405](https://user-images.githubusercontent.com/20512530/34905741-21d56946-f89a-11e7-9c4e-b30dcf290d04.png)
Here is the network about the svg when transforming

**Comment by 673800357** [comment]
Sorry I have fixed it using the latest html2canvas

**Comment by guoranliaoran** [comment]
> Sorry I have fixed it using the latest html2canvas

which version ?
