### ISSUE TITLE
SVG class styles are not rendered

### ISSUE THREAD

**Issue by Saabertooth** [niklasvh/html2canvas#1380]
Version: 1.0.0-alpha.9
Issue: It seems that classes applied to SVG elements (and their children) are not applied to exported images.
However, if those styles are applied in an inline "style" attribute, they are applied correctly.

I have noticed that font, color, and fill to be problematic.

fiddle: http://jsfiddle.net/patgoins/2d90yop3/

--Examples--
Exported Image:
![exportusinghtml2canvas](https://user-images.githubusercontent.com/10930289/34788272-0d1ad106-f608-11e7-9739-c88fd0c4d1a3.png)

HTML View:
![ui_screenshot](https://user-images.githubusercontent.com/10930289/34788103-a117ff06-f607-11e7-8271-e08b45453a1f.png)

**Comment by PoeDameron** [comment]
I am having a very similar issue with some SVG charts that I have in my application as well.

**Comment by PoeDameron** [comment]
I was just wondering if anyone from the HTML2Canvas team or anyone on this forum has any idea why this issue is occurring?

**Comment by Saabertooth** [comment]
I don't know that I would call this a "fix" by any means but I have come up with a workaround for this issue.

The gist of this workaround consists of identifying problematic CSS properties that are not being rendered and then scanning the dom and inlining those styles wherever they are found on an element. 

The following code is TypeScript but one could easily modify it for vanilla JS.  I am calling this method just before calling the html2canvas(..) method:

`private setInlineStyles(targetElem: HTMLElement) {

        const transformProperties = [
            'fill',
            'color',
            'font-size',
            'stroke',
            'font'
        ];

        let svgElems = Array.from(targetElem.getElementsByTagName("svg"));

        for (let svgElement of svgElems) {
            recurseElementChildren(svgElement);
        }

        function recurseElementChildren(node: SVGSVGElement | HTMLElement) {
            if (!node.style)
                return;

            let styles = getComputedStyle(node);

            for (let transformProperty of transformProperties) {
                node.style[transformProperty] = styles[transformProperty];
            }

            for (let child of Array.from(node.childNodes)) {
                recurseElementChildren(child as SVGSVGElement);
            }
        }
    }`

**Comment by Roy1990** [comment]
I have a similar problem but the difference is that the svg content which is spilling out of the svg element is not visible, by default the "user agent stylesheet" says svg overflow hidden, but I have a class to the svg element where I have overwritten the overflow property to "overflow: visible !important;". but still ever though I have tried to apply the overflow property on runtime just before I call the html2canvas(...) function, this doesn't seem to work.

**Comment by ronny1020** [comment]
same problem here. firefox and chrome are OK. But safari have this issue.

**Comment by christopherball** [comment]
Please re-open this ticket and implement this workaround into the core library.
