### ISSUE TITLE
custom class instead of data-html2canvas-ignore

### ISSUE THREAD

**Issue by xr0master** [niklasvh/html2canvas#1386]
Feature required.

We often have the third-party code in projects, so sometimes it's not possibility to append the data-html2canvas-ignore attribute. It will be very helpful if we can set a list of classes for ignoring.

Thank you for your good job and project.

**Comment by niklasvh** [comment]
Probably won't be implementing any other attributes/classes etc for ignoring elements, but open to introducing a predicate function option which takes as an argument the `Element` to the predicate and it returns whether it should get rendered, so you could have a predicate function something like:

`element => !element.classList.contains('classNameToIgnore')`

**Comment by xr0master** [comment]
Exactly that I mean. It will be nice to have it as list, because sometime the one class for filtering won't be enough.

`!element.classList.some(cls => ignoreClassesArray.indexOf(cls) >= 0);`

**Comment by niklasvh** [comment]
https://github.com/niklasvh/html2canvas/commit/fad4f837c95ef3e07e69a9ab5e543e46049ee909

**Comment by bhoomikamaheshwari20** [comment]
hi, @niklasvh i'm using SDK and have self made html tags which html2canvas is not able to render and shows ** Not able to find element in cloned IFrame ** error always.. Please suggest some solution in order to include these tags ASAP
