### ISSUE TITLE
Can`t make canvas.toDataURL() work with v1.0.0-alpha.9

### ISSUE THREAD

**Issue by OlegShklyarov** [niklasvh/html2canvas#1387]
My working code now is:

```
<script type="text/javascript">
window.takeScreenShot = function() {
html2canvas(document.getElementById("masterslider"), {
allowTaint: true,
backgroundColor: null
  }).then(function(canvas) {
document.body.appendChild(canvas);
});
}
</script>
```

How to make it download the image by hitting that button? I am JS-newbie, please help.

**Comment by xr0master** [comment]
You can't. You can use the A element with download attribute, but it can't be async, so you need to prepare the image before a click event.

**Comment by OlegShklyarov** [comment]
Thank you for answer, xr0master , I will look further for image preparing.

**Comment by niklasvh** [comment]
With `allowTaint: true` you are permitting the canvas to be tainted, meaning any cross origin image drawn on it will make it unreadable with toDataURL
