### ISSUE TITLE
svg fill and color

### ISSUE THREAD

**Issue by golches** [niklasvh/html2canvas#1389]
hi everyone
i wanna thanks the developers for this library first, and i dowbloade this library since 4 days, i work with the last version of html 2canvas, and i have some difficulty, and i try to solve them, but this one i parsed google for 10 hours no solution, so the problem is in picture wich an svg, from stackoverflow logo, html2canva render it but with the wrong color

orginal picture 

![image](https://user-images.githubusercontent.com/12893743/34920536-b10eb092-f974-11e7-89cd-39b730af831b.png)

rendered picture with html2canvas

![image](https://user-images.githubusercontent.com/12893743/34920562-f31e6b80-f974-11e7-8c06-ee6b15a00c38.png)

**Comment by Saabertooth** [comment]
Are you setting the "fill" and "color" attributes on the SVG element or setting them in a "style" attribute?

**Comment by Yuiffy** [comment]
I have the same question.
a svg with a class, there is "color: red;" in the class, but in the html2canvas result the svg is black color.
If I put a attr 'style="color: red"'， it will be right.

**Comment by blendsdk** [comment]
I have the same issue. My SVG is a child element of a div. The CSS looks like:
```css
.div-element svg {
    /* fill the nested SVG element within the DIV with red */
    fill: red
}
```

The rended images truns black. 

Any advice?

**Comment by meehaws** [comment]
Has anyone found a workaround for this?

**Comment by Saabertooth** [comment]
Yes. I posted a workaround somewhere...I'll try to dig it up

**Comment by Saabertooth** [comment]
Here you go:
https://github.com/niklasvh/html2canvas/issues/1380#issuecomment-361611523

**Comment by BobaGuaca** [comment]
I get the same issue when trying to render PNGs. It's not quite as noticeable as the stackoverflow example above, but it does taint the original image enough to be obvious.

**Comment by niklasvh** [comment]
This should be fixed in the latest version

**Comment by GoChartingAdmin** [comment]
I dont think it is fixed
![white](https://user-images.githubusercontent.com/20324844/134770279-5c481b3d-8204-46c4-99dc-c774aeb6196e.png)
![black](https://user-images.githubusercontent.com/20324844/134770285-60a6870f-7e47-48ac-a5be-12fadbb4886b.png)

Unless I am doing anything wrong, the stroke and fill of svg icons are taking black color instead of currentColor
