### ISSUE TITLE
image generation is too slow

### ISSUE THREAD

**Issue by anil26** [niklasvh/html2canvas#1391]
testing on latest html2canvas build (minified)

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).
can we have an option to take specific fontsize and other unnessary thing from dom like color, shadow e.t.c Its taking more than 1 second even for a small section. Just want the minimal data representation. 

### Specifications:

 * html2canvas version tested with:
 * Browser & version:chrome 60.x
 * Operating system:linux mint

**Comment by jonahlibrach** [comment]
Has this issue been resolved? It still is too slow on every browser I've tried and just on minimal examples it blocks
