### ISSUE TITLE
Not rendering live images

### ISSUE THREAD

**Issue by yudircks** [niklasvh/html2canvas#1393]
The images calling directly from live are not getting rendered in canvas.

**Comment by OlegShklyarov** [comment]
From live? What is this?

**Comment by yudircks** [comment]
My issue was that its not rendering images if i am putting any live url like for facebook profile piture i am using facebook url but now found fix for this by using `useCORS:true` but this is not working in safari and if i use `allowtaint:true` then i am not able to use toDataURL function

**Comment by niklasvh** [comment]
Please familiarize yourself with how CORS works and what sort of restrictions it imposes on `canvas` rendering.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
