### ISSUE TITLE
AWS s3 proxy for ReactJS

### ISSUE THREAD

**Issue by furedal** [niklasvh/html2canvas#1397]
I am using html2canvas together with a `ReactJS` application and I am trying to load images from a `AWS s3` but struggling with the cors origin problem.

I have added `useCORS: true` to html2canvas and i have accepted cord-origin + cors-headers, using wildcards on AWS. Still no success.
As I understand it, I need to use a proxy to change the origin of the image that I want to load.

I am having troubles of find examples where ReactJS is using proxies. Do anyone have a complete example where they are using `ReactJS` + `AWS s3 ` + `html2canvas`?

Or at least some guiding for creating the proxy?

**Comment by yrodrigez** [comment]
Please i need this 2

**Comment by yrodrigez** [comment]
We fixed this, the problem with this is that you need a middleware (server if you want) to receive a in a queryParam the image url and return a blob as plain text
something like this 
``` http://url_To_Your_Server/URL_TO_YOUR_PROXY?url=IMAGE_URL ```

**Comment by elizabeth-chan** [comment]
@yrodrigez do you have an example you can show? I'm having the same problem

**Comment by furedal** [comment]
To answer my own question:

- For NextJS, follow these [instructions](https://nextjs.org/docs/api-reference/next.config.js/rewrites)
- For Gatsby, follow these [instructions](https://www.gatsbyjs.com/docs/api-proxy/)

If you are using express i would recommend writing something like this inside your server.ts:

```
import express from 'express';
import { Server } from 'http';
import { createProxyMiddleware } from 'http-proxy-middleware';

const app = express();
const server = new Server(app);

app.use(
  createProxyMiddleware('/images', {
    target: process.env.IMAGES_BASE_URL,
    secure: true,
    changeOrigin: true,
  }),
);

...
```

**Comment by alemosa** [comment]
> To answer my own question:
> 
> * For NextJS, follow these [instructions](https://nextjs.org/docs/api-reference/next.config.js/rewrites)
> * For Gatsby, follow these [instructions](https://www.gatsbyjs.com/docs/api-proxy/)
> 
> If you are using express i would recommend writing something like this inside your server.ts:
> 
> ```
> import express from 'express';
> import { Server } from 'http';
> import { createProxyMiddleware } from 'http-proxy-middleware';
> 
> const app = express();
> const server = new Server(app);
> 
> app.use(
>   createProxyMiddleware('/images', {
>     target: process.env.IMAGES_BASE_URL,
>     secure: true,
>     changeOrigin: true,
>   }),
> );
> 
> ...
> ```

Hey Furedal, could you explain with an example how you solved this? I'm using Next.js, and don't know how to get this to work... thanks.

**Comment by furedal** [comment]
@alemosa I think the documentation about [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites) from NextJS own website are pretty clear and provides enough examples.

**Comment by alemosa** [comment]
@furedal Yes, the documentation is clear. Still, I'm trying to guess how you finally solved it. I guess you ended up using the proxy option on html2canvas, but then, if you want to process multiple images from amazon s3 on that html2canvas function, how you rewrite the url's of all of them with that method?
Could you explain how you used proxy with the next.js rewrite methods? It's not that clear... maybe I'm confused on something, but you will help me a lot if you give me more info.

Thanks in advance!
