### ISSUE TITLE
Production version required for 0.5.0-x 

### ISSUE THREAD

**Issue by upadsha** [niklasvh/html2canvas#1400]
Hi

Can you please release a 'PRODUCTION' version without the tag of **alpha** or **beta** at the earliest as in some environments these are not permitted. Available production version is 0.4.1 which do not export Charts (SVG) where as any version above this works fine like 0.5.0-alpha1 and above.

Thanks 
Regards
Shashi

**Comment by niklasvh** [comment]
Will do once it is ready to be used in a production environment.

**Comment by upadsha** [comment]
Hi 

Thanks for your quick response, shows your commitment.

Can you give a rough date / ETA on this, so that i can wait for it.
It would be great be a great help if you can share ETA.

Regards
Shashi

**Comment by niklasvh** [comment]
Don't have any ETA for it.
