### ISSUE TITLE
a little space in after canvas rendering

### ISSUE THREAD

**Issue by yudircks** [niklasvh/html2canvas#1401]
when i am rendering canvas its giving me unexpected white space on left on my system and unexpected white space on top and some other system its not fixed where the white space will come. Using latest version `1.0.0 alpha 9`. Sharing image with issue in my system
![1973605365989135_1_1516263534](https://user-images.githubusercontent.com/20438598/35089175-273ea88c-fc5c-11e7-9980-c91d68b5d457.png)

In above image the white space in image was not in the div

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by yudircks** [comment]
It will be huge thing for me to generate on jsfiddle as i am fetching all the details on runtime then converting div to canvas

**Comment by OlegShklyarov** [comment]
Same thing was for me. Fixed it by moving rendering div to the left side of the screen. With no margins, padding. http://ecard.enter-media.org/poster-maker/2154796/

**Comment by yudircks** [comment]
moving div to left is not working for me.

**Comment by OlegShklyarov** [comment]
Can you show your page?

**Comment by hArieLx** [comment]
Yes, I am having same problem on certain computers...  However, newer MacBook Pro renders perfectly in all browsers

**Comment by hArieLx** [comment]
Small white space (or transparent if I set background to transparent) in every png generated along the left side, but I have only seen this on PC not MacBook

**Comment by yudircks** [comment]
@niklasvh do u have any fix for this or any workaround???

**Comment by niklasvh** [comment]
@yudircks Unless I have a reproducible test case, there isn't much to go on. 

The project is full of examples without any spacing issues, so unless you can illustrate with a simple case that there is an issue, there isn't much to go on, and I don't have the time either to spend to try and reproduce errors present in your environment.

**Comment by OlegShklyarov** [comment]
@niklasvh nobody cares about white spaces, screw them, make background-clip: text support plz )

**Comment by OlegShklyarov** [comment]
@yudircks @hArieLx I just solved this problem by removing <header> section in my template. Dunno what css style or JS script stored there was making white space problem but this worked for me. Try to remove some html elements above your canvas.

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/a3e25d71cb39eb295fc9bee94712be03a6e71204
