### ISSUE TITLE
Bring back onclone callback

### ISSUE THREAD

**Issue by arsnyder16** [niklasvh/html2canvas#1403]
Trying to upgrade to the latest version but it look as if onclone callback was removed.

**Comment by noelzubin** [comment]
will this be added soon?

**Comment by HarlesPilter** [comment]
Why was this removed? Really need a way to alter the cloned document since I don't want tamper with the actual document and then have to reset when html2canvas returns a promise.

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/9fb9898894bb6fa36ca0f63d0b98520f0d6eac7c
