### ISSUE TITLE
Issue with Responsive SVG and getImage method

### ISSUE THREAD

**Issue by miniben-90** [niklasvh/html2canvas#1406]
- [X] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [X] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Example : https://jsfiddle.net/9dhs999e/9/

when you have a SVG element responsive with height and width define to 100% at the transformation to picture the result is not correct due to the dynamic size of the element and it result with a deformation of the render.
The solution is to pickup the clientWidth and clientHeight to the node and edit height width attributes with the corrects values.

`        if (
          /[0-9]{1,}\%/i.test(node.getAttribute('width')) ||
          /[0-9]{1,}\%/i.test(node.getAttribute('height')) ||
          /[0-9]{1,}\%/i.test(node.style.width) ||
          /[0-9]{1,}\%/i.test(node.style.height)
      ) {
        if (!node.clientWidth && !node.clientHeight && node.parentNode) {
          node.setAttribute('width', window.getComputedStyle(node.parentNode).width);
          node.setAttribute('height', window.getComputedStyle(node.parentNode).height);
        } else {
          node.setAttribute('width', node.clientWidth);
          node.setAttribute('height', node.clientHeight);
        }
      }`

Example : https://jsfiddle.net/4fxwwbh8/1/

### Specifications:

 * html2canvas version tested with: latest version (1.0.0-alpha.9)
 * Browser & version: Chrome (Version 63.0.3239.132 (Build officiel) (64 bits)), Edge, Firefox (57.0.4 (64 bits))
 * Operating system: Linux, Windows

**Comment by miniben-90** [comment]
Hello,
I didn't make a pull request if I have some time this week I will do it.

**Comment by rshelnutt** [comment]
Getting this exact same issue as well - been 3 years now, is this be something that's on radar to be resolved?
