### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by JagdishThavasi** [niklasvh/html2canvas#1409]
Am always getting the below issue, though I gave allow taint and use cors as false. How would i restrict my canvas to not to be tainted. 

Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by JagdishThavasi** [comment]
Please find the code snippet below, 

html2canvas(document.body, {
		allowTaint: false,
		useCORS: false
	}).then(function(canvas) {
	console.log(canvas.toDataURL());
		
    
});

**Comment by niklasvh** [comment]
Please share an example on jsfiddle

**Comment by Chryseis** [comment]
i meet the same issues,canvas has generated,but canvas.toDataURL() can't work,it will report an error.
![image](https://user-images.githubusercontent.com/13757352/40046782-5d6d1ac8-5860-11e8-9f8f-45bcb22a9374.png)

**Comment by vijayrajsg** [comment]
same issue i'm got
 what to do?
