### ISSUE TITLE
Screenshot of a page with Bing Maps V7 Map Control

### ISSUE THREAD

**Issue by alee8** [niklasvh/html2canvas#141]
I am using the html2canvas library to try to capture the map element (Bing Maps ajax control).  
After my page loads the map, I have a button that I use to capture the screen.  The event handler is:
          function captureScreen() {
              var target = $("#myMap");
              console.log("called captureScreen: " + target);
              html2canvas(target, {
                  proxy:"",
                  logging: true,
                  useCORS: true,
                  onrendered: function (canvas) {
                      var data = canvas.toDataURL();
                      console.log("rendered: " + data);
                      $('#screen').attr('src', data);
                      $('#thumbnail').attr('src', data);
                  },
                  complete: function(images) {
                      console.log("captureScreen: " + JSON.stringify(images));
                      console.log("done with console log of images object");
                  }
              });
          }

Setting proxy, useCORS options, I am able to capture the map element.  However, I noticed that many times, the rendered canvas that html2canvas builds is not always able to load all the map tiles (perhaps due to timeout).  I have seen times when it manages to completely create the canvas with all the tiles after reloading the page several times.

My question is whether there are ways to inquire of html2canvas about images that it failed to load in constructing the canvas (enabling logging shows me what html2canvas prints) and/or retry to load failed images before finalizing rendered canvas. Your Documentation page suggests that Preload returns some helper methods that load more images or clean the DOM but the information is incomplete and it looks like from your current JS file, the API has changed.

Here are the snippets of Bing Maps Control code to load the Bing Map in my test page:
Bing Maps API:
          <script type="text/javascript" src="http://dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>
CSS:
        #thumbnail { 
            width: 200px; 
            height: 150px;
        }
        .mapstyle {
            position: relative;
            width: 800px;
            height: 600px;
        }
 JS:
          function GetMap() {
              var mapOptions = {
                  credentials: "<get Bing Maps Key from https://www.bingmapsportal.com/>",
                  mapTypeId: Microsoft.Maps.MapTypeId.road,
                  //center: new Microsoft.Maps.Location(37.77637, -122.42212),              // San Francisco, CA
                  //center: new Microsoft.Maps.Location(37.417447799999998, -122.1338166),  //"562 Kendall Ave, Palo Alto, CA 94306, USA"
                  center: new Microsoft.Maps.Location(36.6002388000, -121.8946762085),      // Monterey Ca
                  zoom: 14
              };
              var map = new Microsoft.Maps.Map(document.getElementById('myMap'), mapOptions);
          }
HTML:
   <body onload="GetMap();">
      <input id="aButton" type="button" onclick="captureScreen()" value="Capture Screen"/>
      <div><img id="thumbnail" src="images/borneo.png"/></div>
      <div><img id="screen" src="images/borneo.png"/></div>
     <div id="myMap" class="mapstyle"></div>
   </body>

**Comment by truetopwebghost** [comment]
I tried to get screen shot of Bing Map v8 and I had a error on console.
![image](https://user-images.githubusercontent.com/35195476/38144451-071df46a-3445-11e8-9447-0e599f8d9b17.png)
Any Idea to solve this issue?

**Comment by dev-deepak-soni** [comment]
I am also unable to get screenshot of the bing map.
check the link, here is the map is missing. its a screenshot generated by the html2canvas library.
https://prnt.sc/piwnlp
