### ISSUE TITLE
Does html2canvas support "webgl" (or "experimental-webgl") context ?

### ISSUE THREAD

**Issue by 91c5ex** [niklasvh/html2canvas#1420]
Hi,

I have a scenario where my html page contain canvas with webgl context. When we take screenshots of that html page dom with webgl enable canvas is represented as white area

For canvas with 2d context it is working perfectly.

I am using html2canvas 0.4.1  version
I tried testing on 1.0.0-alpha.9 version but I am getting below error

> Uncaught TypeError: Cannot read property 'childNodes' of null  at html2canvas.js:6574

**Comment by niklasvh** [comment]
It is supported in 1.0.0

**Comment by ifzm** [comment]
v1.0.0-alpha.11 not supported?

**Comment by vivek1395068** [comment]
Hi, 
      I am also facing the same issue. I am trying to export the  Please find my code : - 
html2canvas(document.querySelector('.main'), { logging: false }).then((canvas) => {
      const element = document.getElementById('snapshot');
      const ctx = canvas.getContext('2d');

      ctx.font = '20px Ossb';
      ctx.fillStyle = 'red';
      ctx.fillText(this.props.appName, 80, 100);

      element.setAttribute('href', canvas.toDataURL('image/jpg'));
      element.setAttribute('download', 'snapshot.jpg');
      element.click();
    });



This is how it looks like when I export the screenshot into jpeg : -
![snapshot (1)](https://user-images.githubusercontent.com/22879580/72320938-aeaaa700-36c8-11ea-9509-aef8216590d7.jpg)


and this is how it should be : -
![snapshot](https://user-images.githubusercontent.com/22879580/72320769-5a072c00-36c8-11ea-8ab8-334258b8752a.jpg)

**Comment by vishnusureshperumbavoor** [comment]
It is not supported in 1.4.1
