### ISSUE TITLE
Unable to disable logging of html2Canvas

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [niklasvh/html2canvas#1421]
Newest version of html2canvas ("html2canvas": "^1.0.0-alpha.9")
Whenever I use html2canvas in it's promiselike version, I get in my logging:
html2canvas $npm_package_version

in the code I see:
    // eslint-disable-next-line no-console
    if ((typeof console === 'undefined' ? 'undefined' : _typeof(console)) === 'object' && typeof console.log === 'function') {
        // eslint-disable-next-line no-console
        console.log('html2canvas ' + "$npm_package_version");

I suppose this is a bug? That these lines should have been disabled then?

**Comment by solutweb** [comment]
I had this same problem and I resolved after commenting on this line:
`console.log('html2canvas ' + "$npm_package_version");`

Really weird stuff
