### ISSUE TITLE
Captured screenshot does not take underline properly

### ISSUE THREAD

**Issue by the-golden-girl** [niklasvh/html2canvas#1423]
I am using Html2Canvas 1.0.0-alpha.9 . 

The captured screenshot does not take underline properly.

![fiddle](https://user-images.githubusercontent.com/33143841/35565050-16e7504e-05e2-11e8-824e-bf30622f214c.PNG)

Here, First image is the original image and second image is the captured screenshot.

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/d023de0b9906cd46b6bd2b7fd2398e5e82b0ad35
