### ISSUE TITLE
'HTMLCanvasElement': Tainted canvases may not be supported.

### ISSUE THREAD

**Issue by viktorleschuk** [niklasvh/html2canvas#1427]
In my case I have a non-static page, with images from our API.
I need to capture this page and save as image.

For capturing I'm using code below:

> html2canvas(document.body, {allowTaint : true, useCORS: false})
>         .then(function(canvas) {
>           let data = canvas.toDataURL();
>           //next stuff
>         });

And I have an error 'Tainted canvases may not be supported.'
What should I do to make this work? 
I've tried crossOrigin="Anonymous" property in images, also tried 'useCORS' option, but it still does not work, with the same error.

Thanks for your answer

**Comment by niklasvh** [comment]
You are explicitly allowing the canvas to get tainted with `allowTaint : true`

**Comment by chuhanan** [comment]
if set `allowTaint : false`, cause another error
