### ISSUE TITLE
html2canvas v0.4.1  version do not export SVG charts to PDF

### ISSUE THREAD

**Issue by upadsha** [niklasvh/html2canvas#1430]
Hi

We are using html2canvas v0.4.1 for exporting both HTML and SVG charts, but found that it only exports HTML contents and not SVG charts(we use c3 chart). Is it possible to export using this version, if not is there any work around or alternative for exporting SVG charts using v0.4.1

Regards
Shashi

**Comment by Mani2693** [comment]
Facing same issue , It doesn't render highcharts which is SVG

**Comment by niklasvh** [comment]
You are welcome to discuss any work arounds you may find, but 0.4.1 won't be updated anymore (it's 5 yrs old) and the library has been rewritten since.

**Comment by Mani2693** [comment]
@niklasvh Even in our latest version we face the issue , Here is the issue reported by another using 

[https://github.com/niklasvh/html2canvas/issues/1426](url)

**Comment by maurocasas** [comment]
Check you're not using % widths for the SVGS, I had the same issue and I've changed things to fixed widths, that fixed it.
