### ISSUE TITLE
when font-size is under 8px ,word crowded together

### ISSUE THREAD

**Issue by chaoli920029342** [niklasvh/html2canvas#1433]
Hi niklasvh. I have drawn table charts in my project. When I take screenshot using html2canvas some texts/legends in the charts come blurry.

I used  0.5.0-beta3  versions of html2canvas.

when my font-size is under 8px ,word crowded together, line-height with multiple is invalid also,must like that "line-height:10px;"

normal is like that
![image](https://user-images.githubusercontent.com/21034009/35895772-e3e11186-0bf3-11e8-8a73-255bbff9b32b.png)

problem:
![image](https://user-images.githubusercontent.com/21034009/35895780-f1d7f3b8-0bf3-11e8-9e0c-a7d7b63353e7.png)

Thank you

**Comment by niklasvh** [comment]
< 1.0.0 versions won't be getting any more updates
