### ISSUE TITLE
Canvas rendered initialized with 1.5 scale

### ISSUE THREAD

**Issue by gabibraharu** [niklasvh/html2canvas#1436]
Hello,
I used succesfully html2canvas but suddenly it scales my canvas at 1.5 and I do not know why because I did not specify this. I just want a normal render. So when I use Inspect tool on Chrome it shows me the message below. I do not want any scale.

148ms html2canvas: Canvas renderer initialized (1512x1133 at 943.1469116210938,323.84869384765625) with scale 1.5

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.9
 * Browser & version: Chrome
 * Operating system: Windows 10

**Comment by jamespantalones** [comment]
I believe that's because the default render scale is your device pixel ratio, which in your case seems to be 1.5. you can pass in `{scale: 1}` in the config

**Comment by niklasvh** [comment]
Exactly what jamespantalones said.
