### ISSUE TITLE
Extra white space on the left and lost part on the right

### ISSUE THREAD

**Issue by DavidDiao** [niklasvh/html2canvas#1438]
### Bug reports:

https://jsfiddle.net/8dwmbwke/

The width of extra and lost part seems always 8px
It happends when the picture height > browser height (document.body.clientHeight ?) and margin is 0 auto
And if picture width > browser width, it became normal again

(I'm not good at English, so there may be strange places in my expression)

### Specifications:

 * html2canvas version tested with: Newest version
 * Browser & version: Chrome 63.0.3239.132 (32bit)
 * Operating system: Windows 7 Ultimate

**Comment by niklasvh** [comment]
Thanks for the detailed info, without really debugging too much it sounds that it is an issue with scrollbars showing up / not showing up. Will try and work out a fix for it asap

**Comment by des4hosting** [comment]
I am having the same issue and indeed it looks like it is related to scrollbars. In chrome I can hide the scrollbars using webkit and it works fine but not the case for other browsers.

**Comment by andersborgabiro** [comment]
Confirmed. In my case always 7px (Chrome for Windows). Padding adds to this.

As I don't use jQuery I did this instead:
                    document.documentElement.classList.add("hide-scrollbar");
                    document.documentElement.classList.remove("hide-scrollbar");

But a real solution would of course be preferred and appreciated.

**Comment by dappstatus** [comment]
I use the newest version with the following settings and i still get the scroll bar padding problem, without scrollbar it works perfect, in a screen size with scrollbar it has a padding which cuts the img.

backgroundColor: null, 
scrollX: 0, 
scrollY: -window.scrollY, 
scale: 1

**Comment by WebBlockChainDev** [comment]
I use the newest version with the following settings and i still get the scroll bar padding problem, without scrollbar it works perfect, in a screen size with scrollbar it has a padding which cuts the img.

backgroundColor: null,
scrollX: 0,
scrollY: -window.scrollY,
scale: 1

**Comment by k-gintaras** [comment]
One of my solutions.
html2canvas(element, {
      width: $(element).width(), //problem is that canvas is slightly larger than element, so you need to set it here
    })

**Comment by ahmedfeyzi** [comment]
> **I solved all possible problems as follows..**

```
html2canvas(element , {
        scrollX: -window.scrollX,
        scrollY: -window.scrollY,
        windowWidth: document.documentElement.offsetWidth,
        windowHeight: document.documentElement.offsetHeight
})
```

**Comment by Muneem** [comment]
I have tried almost all solutions but still not working.

**Comment by okumo** [comment]
I am having the same issue right here 
![image](https://user-images.githubusercontent.com/44917174/117375372-7702d800-ae94-11eb-8abf-d5c259367574.png)

**Comment by saikun0293** [comment]
> > **I solved all possible problems as follows..**
> 
> ```
> html2canvas(element , {
>         scrollX: -window.scrollX,
>         scrollY: -window.scrollY,
>         windowWidth: document.documentElement.offsetWidth,
>         windowHeight: document.documentElement.offsetHeight
> })
> ```

windowHeight: element.scrollHeight worked for me

**Comment by thevinaysomawat** [comment]
> windowWidth: document.documentElement.offsetWidth,

worked for me!

**Comment by ayagaidi** [comment]
> > **I solved all possible problems as follows..**
> 
> ```
> html2canvas(element , {
>         scrollX: -window.scrollX,
>         scrollY: -window.scrollY,
>         windowWidth: document.documentElement.offsetWidth,
>         windowHeight: document.documentElement.offsetHeight
> })
> ```

 this  fix my issue

**Comment by mohitWebcontxt** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/100257396/163537596-4caa9620-deb4-480e-96aa-f66c33facdad.png">
after download image showing some white space from right and bottom

**Comment by drew-thorson** [comment]
@mohitWebcontxt this seems to have fixed that issue with the whitespace on the same edges for me on mobile devices.

```
html2canvas(element, {
  width: element.clientWidth,
  height: element.clientHeight,
})
```

> <img alt="image" width="834" src="https://user-images.githubusercontent.com/100257396/163537596-4caa9620-deb4-480e-96aa-f66c33facdad.png">
> 
> after download image showing some white space from right and bottom

**Comment by VanshShInt** [comment]
Issue is not yet resolved
