### ISSUE TITLE
Html2Canvas Exception after modal window has been launched

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [niklasvh/html2canvas#1439]
Hello,

I'm using the latest version of Html2Canvas in a project of mine and I have a firebase authentication integration issue.

 * html2canvas version tested with: v1.0.0-alpha.9 - 7.1.2018
 * Browser & version: Chrome 64
 * Operating system: Windows 10

See the video I made:
https://www.youtube.com/watch?v=kwJ7LGTwltI&feature=youtu.be

So before signing out, I don't have any issues.
However, after signing in (I'm guessing that it has to do with the modal pop-up which is launched when signing in) all calls to Html2Canvas give the shown exception.

I've looked through the code of Html2Canvas but I'm not familiar with it. Didn't get too far into it.
Would be great if you could take a look!

Kind regards,

Lander

**Comment by niklasvh** [comment]
Hey @LanderBeeuwsaert 

If you add a `catch(e => console.log(e))` handler for the html2canvas Promise, what does it log?

**Comment by LanderBeeuwsaert** [comment]
Hello @niklasvh ,

well, that's it, I already have:

```
    return html2canvas(this.createTableContainerRef.nativeElement, {logging: false}).then((canvas) => {
      return this.compressPassedCanvas(canvas);
    }).catch((error) => {
      console.log(error);
      throw error;
    });
```

But that actually doesn't catch anything.
The exception isn't passed through there. Which has something to do with zones of angular I think.
But (see the video) although the exception is not passed through there it is still logged in the console. (by other code).

I think it has something to do with the iframe which is added to the body during the login. (see the DOM in the video).
Could it be that Html2Canvas fails on trying to get that iframe somehow?

**Comment by LanderBeeuwsaert** [comment]
Solved by adding:

        ignoreElements: function(element) {
          return element.nodeName === 'IFRAME';
        }
