### ISSUE TITLE
Chart not converting to image and opening in new window

### ISSUE THREAD

**Issue by ABHIKSINGHH** [niklasvh/html2canvas#1442]
Function called on button click:
    
function convertToCanvasAndPrint() {
    html2canvas(document.getElementById("PositionChartMainDiv"), {
    "useCORS": true, "allowTaint": true, "logging": true, "onrendered": function (canvas) {
    var base64image = canvas.toDataURL("image/png"); 
     window.open(base64image , "_blank");
    };
    });
    }

On button click I am trying to capture a <DIV id="PositionChartMainDiv"> content which is an organization chart and open the snapshot in new browser window. But somehow nothing is happening on button click. I am using version html2canvas 1.0.0-alpha.10. In browser window console I see "Canvas renderer initialized" message. But nothing is happening? Can somebody help me on this please?

**Comment by niklasvh** [comment]
Please read the documentation

**Comment by ABHIKSINGHH** [comment]
@niklasvh : What wrong am I doing here, could you please let me know?
