### ISSUE TITLE
Possible remove parent transform

### ISSUE THREAD

**Issue by balkarov** [niklasvh/html2canvas#1448]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
 [my example on jsfiddle](https://jsfiddle.net/ra1h2ob4/1/).

### Specifications:

 * html2canvas version tested with: v1.0.0-alpha.10
 * Browser & version: Google Chrome  64.0.3282.167
 * Operating system: Windows 8 x64

My node (which I want capture) is located in div with transform (scale translate). I want capture my node without parent tranform. Is it possible? You can see [my example](https://jsfiddle.net/ra1h2ob4/1/)

**Comment by niklasvh** [comment]
You can use the `onclone` option to remove the transform https://jsfiddle.net/g9eb7hy2/

**Comment by balkarov** [comment]
But in you example the same.640x426
but my img has 
width: 1280px;
 height: 852px;

**Comment by balkarov** [comment]
I passed width and height to html2canvas and got normal result.
Thank you!

**Comment by balkarov** [comment]
@niklasvh 
I have problem with transform translate.
Look please [example](https://jsfiddle.net/g9eb7hy2/9/)

Canvas render with white space in right. (you can save img and will see)

I tried: left and top set to 0. But nothing changed
