### ISSUE TITLE
Uncaught ReferenceError: html2canvas is not defined.

### ISSUE THREAD

**Issue by tousif12** [niklasvh/html2canvas#1449]
Hi , I am using html2canvas to convert html to jpg. When I am using  

> https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js

this 0.4.1 cdn its working fine. But On 

> https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta4/html2canvas.js

or larger then 0.4.1 its giving error 
Uncaught ReferenceError: html2canvas is not defined.

**Comment by tousif12** [comment]
I am using on Magento 2

**Comment by niklasvh** [comment]
Latest version is 1.0.0
