### ISSUE TITLE
Image tag is not capturing

### ISSUE THREAD

**Issue by gitbala** [niklasvh/html2canvas#145]
Hi,

I tried to convert html to image using html2canvas, its working fine. But the image tag inside html elements is not converting, Given below one example:

<span class="color-lines">
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/red.png" alt="red"/>
                <img src="assets/images/icons/color-line/red.png" alt="red"/>
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
</span> 
## Working HTML Element

<table class="calender-table">

        <tr class="cldr-row-heading">
                <th>Mo</th>
                <th>Tu</th>
                <th>We</th>
                <th>Th</th>
                <th>Fr</th>
                <th>Sa</th>
                <th class="last">Su</th>
            </tr>
            
            <tr class="cldr-row-date">
                <td class="disable"><div class="date-box"><span class="date">26</span></div></td>
                <td class="disable"><div class="date-box"><span class="date">27</span></div></td>
                <td class="disable"><div class="date-box"><span class="date">28</span></div></td>
                <td class="disable"><div class="date-box"><span class="date">29</span></div></td>
                <td class="disable"><div class="date-box"><span class="date">30</span></div></td>
                <td class="disable"><div class="date-box"><span class="date">31</span></div></td>
                <td class="last"><div class="date-box"><span class="date">1</span></div></td>
            </tr>

           <tr class="cldr-row-date">
            
                <td>
                <div class="date-box"><span class="date">2</span>
                
                <span class="color-lines">
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/red.png" alt="red"/>
                <img src="assets/images/icons/color-line/red.png" alt="red"/>
                <img src="assets/images/icons/color-line/blue.png" alt="yellow"/>
                <img src="assets/images/icons/color-line/green.png" alt="green"/>
                </span> 
                
                <span class="bell">bell</span> 
                <span class="calsnap">snap</span>
                </div>
                </td>

</table>

Here is my script for converting html2canvas:

var html2obj = html2canvas($('table'));
var queue  = html2obj.parse();
var canvas = html2obj.render(queue);
var img = canvas.toDataURL();
$('#calendar_to_canvas').attr('src', img);

PFA screenshot
![calendar](https://f.cloud.github.com/assets/3063076/16687/63aa501c-484a-11e2-8d83-f002f86a8d12.png)

Thanks,
Bala

**Comment by rashmee** [comment]
Hello, 
I want same the image once it is converted. I tried canvas.toDataURL("image/png"); but that did not work for me. I tried the code below and while it created an img, it didn't display the screenshot. I am a newbie using javascript. Can you help please. 

function showImage() {
		html2canvas($('#hpImplement'), {
			onrendered: function(canvas) {
				var elem = document.createElement("img");
					elem.setAttribute("src", canvas);
					elem.setAttribute("alt", "Flower");
					document.getElementById("hpShare").appendChild(elem);
            
			},
		});	
}

I even tried: 

function showImage() {
		html2canvas($('#hpImplement'), {
			onrendered: function(canvas) {
                              var theCanvas = canvas.toDataURL("image/png");
				var elem = document.createElement("img");
					elem.setAttribute("src", theCanvas);
					elem.setAttribute("alt", "Flower");
					document.getElementById("hpShare").appendChild(elem);
            
			},
		});	
}

**Comment by linigithub** [comment]
Im using the html2canvas - local image not rendering in pdf. whats the solution for this?

**Comment by linigithub** [comment]
@niklasvh please help - the logo image in html is not rendering in pdf

**Comment by qiuyaofan** [comment]
how to use "proxy": "http://localhost/myproject/proxy.jsp", I use vue,without jsp ,where to put this jsp and i don't know how to use @niklasvh can you help?

**Comment by NikhilRadadiya** [comment]
@qiuyaofan having same issue did you get the solution? I'm using it with angular2

**Comment by maghidini** [comment]
+1 BTW the logs looks good (`html2canvas: Images loaded, starting parsing`) but I still don't see the images on the pdf.

**Comment by pablocuca** [comment]
Im using

allowTaint: true,
useCORS: true,
taintTest: false,

**Comment by creepteed** [comment]
@NikhilRadadiya @qiuyaofan guys, also been looking for a just client side solution. Using vue js and getting image from a giphy. So here is the one worked well for me:
```
html2canvas(element, {
        "logging": true, //Enable log (use Web Console for get Errors and Warings)
        useCORS: true,
        taintTest: false,
        onrendered: function(canvas) {
          var img = new Image();
          img.onload = function() {
            document.body.appendChild(img);
          };
          img.error = function() {
            if(window.console.log) {
              window.console.log("Not loaded image from canvas.toDataURL");
            } else {
              alert("Not loaded image from canvas.toDataURL");
            }
          };
          img.src = canvas.toDataURL("image/png");
        }
      });

```

So no proxy been used.

**Comment by NikhilRadadiya** [comment]
@creepteed I have others element which I need to convert to canvas and then save to pdf, my html doesn't contain only images, if this is the case then how can I use above function you have posted?

**Comment by vishal-px** [comment]
Hi @niklasvh ,
I want to capture webpage using htmltocanvas all is working fine but when i am trying to capture webpage then i not getting images.
Can you help me?
Here is my code
function capture(div_id=null) { jQuery(".screenshot_row_target").html2canvas({ logging: true, //taintTest : true, //proxy: "https://skeleton-21.myshopify.com", onrendered: function (canvas) { jQuery('#screenshot_img_val').val(canvas.toDataURL("image/png")); //document.getElementById("screenshot_html_form").submit(); } }); }

In console, I getting this 
`
html2canvas: Preload starts: finding background-images
html2canvas.js:19 html2canvas: Preload: Finding images
html2canvas.js:19 html2canvas: Preload: Done.
html2canvas.js:19 html2canvas: start: images: 0 / 0 (failed: 0)
html2canvas.js:19 Finished loading images: # 0 (failed: 0)
html2canvas.js:19 html2canvas: Error loading <img>://cdn.shopify.com/s/files/1/2186/4293/files/user2_300x300.png?v=1503661428
html2canvas.js:19 html2canvas: Error loading background:
html2canvas.js:19 html2canvas: Error loading <img>://cdn.shopify.com/s/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c_300x300.gif
html2canvas.js:19 html2canvas: Renderer: Canvas renderer done - returning canvas obj
`
Thanks.
