### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by SeongMinBae** [niklasvh/html2canvas#1457]

**Comment by msphn** [comment]
It's nothing wrong with html2canvas. You just missed the fact that your origin is nagosoft.com and you try to load a picture from recruit.kdb.co.kr. You need to allow your application to load images from this domain.

**Comment by msphn** [comment]
Just as a hint, if you need to fetch images from random locations, you need to set up a proxy, just google html2canvas and proxy :-)
