### ISSUE TITLE
Icon Font not captured under Windows7 & IE11

### ISSUE THREAD

**Issue by yessky** [niklasvh/html2canvas#1458]
### Bug reports:

Font Icon does not display under Windows7 & IE11. 

it works well under Windows7 & IE9/10 and Windows10 IE11/Edge.

here is  an [demo](http://imux.gitee.io/screenshot/demo.html) to reproduce the issuse.

I tried anthor [test](http://imux.gitee.io/screenshot/canvas.html), found that canvas element render font icon well under Windows7 & IE11.

so, I guess it should be a html2canvas issuse or sth related or IE11 issuse.

### Specifications:

 * html2canvas version tested with: latest release, 1.0-alpha
 * Browser & version: IE11
 * Operating system: Windows7

Please help to solve it. Also thanks your great work.

**Comment by yessky** [comment]
spend a few hours, the problem was located. so I note it here.

NOTE: this issuse only reproduce under windows7 + IE11.

CASE 1:
if your css code is:
```css
font-family: "FontAwesome";
...
```

then you should modify the source code at src/renderer/CanvasRender.js line:216,
```javascript
font.fontFamily.replace(g['"]/g, '')
```

CASE 2:
if your css code is:
```css
font-family: FontAwesome;
...
```

then you should modify the source code at src/renderer/CanvasRender.js line:216,
```javascript
JSON.stringify(font.fontFamily)
```

**Comment by foxworth42** [comment]
We are running into the same issue where the font-family in IE11 are not properly rendered.  This fix from @yessky seems to resolve the issue for us.
