### ISSUE TITLE
Corrupted Unjoint Arabic Font Rendering

### ISSUE THREAD

**Issue by tarekeldeeb** [niklasvh/html2canvas#1460]
- [X] You are using the latest [version]
- [X] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Arabic text is rendered bad. All letters are not joint and misplaced.
The bug -->
![somefilename](https://user-images.githubusercontent.com/90985/37084240-9e6c5e72-21fa-11e8-9da8-2f3642190a91.jpg)
The correct -->
![somefilename-correct](https://user-images.githubusercontent.com/90985/37084244-a2b11a68-21fa-11e8-881c-39ae1be0ce0d.jpg)

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.10
 * Browser & version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
 * Operating system: Windows 10 64-bit

**Comment by hadihashem** [comment]
Hello
I'm facing the same issue
Did you find a workaround?
Many thanks
Regards

**Comment by tarekeldeeb** [comment]
Not yet.

**Comment by hadihashem** [comment]
Hello @niklasvh 
Can you please advise what is the status of this bug?
Many thanks
Kind regards

**Comment by tarekeldeeb** [comment]
Hello @niklasvh , any updates regarding this issue?

**Comment by mohafouad** [comment]
any updates ?

**Comment by hadihashem** [comment]
Hi @niklasvh 
It would be very nice from you to update the people facing this issue if there is a bug 
This bug was already solved in a previous release but showed-up again the latest versions
It is a bit disappointing as html2canvas is a great tool and would be even greater when it is used in a wider scale
Thank you in advance for your feedback
Regards

**Comment by 2xSamurai** [comment]
I'm also facing the same issue. Somebody, please provide a solution. Thank you.

**Comment by yassM** [comment]
@tarekeldeeb are you using html2canvas along with [jsPDF](https://github.com/MrRio/jsPDF)?

**Comment by 2xSamurai** [comment]
@yassM No, I am not using jsPDF.

**Comment by tarekeldeeb** [comment]
@yassM No, I'm not using js PDF.

**Comment by yassM** [comment]
Actually the version (1.0.0-rc.1) is rendering Arabic normally in my case, the only issue was when using it alongside jsPDF.

**Comment by tarekeldeeb** [comment]
I tried v0.5.0-beta4, v1.0.0-alpha.10(reported) and  v1.0.0-rc.1, they all have the same issue with my arabic app.

Can ionic framework be the root cause?

**Comment by yassM** [comment]
It can be, but it's probably the CSS, the library is really fragile when handling Arabic letters, any small thing can break the rendering like in your case, can you share a jsfiddle?

**Comment by tarekeldeeb** [comment]
After many searches and trials. I concluded that v 0.4.1 is ok with arabic under the condition that:
- All Divs with arabic text must have the style: text-align:right; (This is not intuitive)
- This does not even work with v 1.x
- http://jsfiddle.net/8ypxW/2022/

Can there be a fix for this? 
[1] Implicit assumption of text right alignment when RTL is defined?
[2] Regression from 0.x to 1.x

Regards,

**Comment by tarekeldeeb** [comment]
I find the same behavior with the latest release 1.3.2

**Comment by harisui** [comment]
@tarekeldeeb I had the same issue but if you remove the jsPDF library, the font will work fine. it's just the combination that is creating the problem.

**Comment by TarekAlQaddy** [comment]
I faced the same issue in version 1.4.1 and fixed it by using 
```
letter-spacing: normal;
```
in the wrapping element

**Comment by mohameddhussien** [comment]
@tarekeldeeb This worked for me as well, thanks a lot for sharing that!🙏
