### ISSUE TITLE
Feature Request: Canvas png compression

### ISSUE THREAD

**Issue by weilinzung** [niklasvh/html2canvas#1480]
Is possible to include PNG compression option to html2canvas?

The `Canvas Jpeg` output to as an image is losing a lot of details and pixelated, I think `png format ` with index color space would be the better & small output.

The big reason that I ask for it is I want to keep the image quality, details and also be able to control the PNG image size. Like [Google Adword](https://support.google.com/adwords/answer/1722096?hl=en#nonani_ads), the ad size is not allowed to over 150Kb, a lot of sizes are small, so would be better to use png format to keep the sharpening of the images.

Thanks!

https://github.com/ShyykoSerhiy/canvas-png-compression

**Comment by niklasvh** [comment]
You can use the provided library (or any other compression library for that matter) outside of html2canvas and as such, won't be bundled with html2canvas.
