### ISSUE TITLE
html2canvas not working for canvas in Dom on Dom clone

### ISSUE THREAD

**Issue by HarishSonar** [niklasvh/html2canvas#1489]
### Bug reports:
html2canvas not working for canvas in Dom When we do cloneNode for dom.
It works fine without clone. It also works fine for other div elements prenent in dom but fails for canvas.

https://jsfiddle.net/jjk3khc3/54/

### Specifications:

 * html2canvas version tested with: v1.0.0-alpha.11
 * Browser & version: Google Chrome (65.0.3325.181)
 * Operating system: Windows10 (64 bit)

**Comment by niklasvh** [comment]
This isn't an issue in html2canvas but in your code. When you perform the cloneNode, it does not clone the contents of the canvas. If you remove the `$container.remove();` you can see that the cloned node does not have the contents of the canvas. See https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode, specifically under Notes:
>> Cloning a node copies all of its attributes and their values, including intrinsic (in–line) listeners. It does not copy event listeners added using addEventListener() or those assigned to element properties (e.g. node.onclick = fn). **Moreover, for a <canvas> element, the painted image is not copied**.
