### ISSUE TITLE
windowWidth not picking up on media queries

### ISSUE THREAD

**Issue by chadlamson** [niklasvh/html2canvas#1491]
I have a site where several PNG images are stacked and positioned using "transform: translate(-50%,0);" to center them in the window. Using this method for positioning, the images are getting cut off for the rendering. So, as a fix, I was going to position all of the images at one width (1500px) without using the transform property and then set the windowWidth property in html2canvas to 1500px. 

The iframe is loaded at 1500px, but the styles for that width are ignored. If I set my browser window to 1500px, the rendering comes out perfect. Is there anyway to pass styles to html2canvas only? Or have the iframe pickup on the media queries, regardless of the browser width?

I am using the latest, non-minified version of html2canvas... in Safari. The site is below. The get a rendering, click the contact dealer/get price button. Use the zip code "78602" so you don't actually get contacted by a real dealer. On form completion, the rendering is made. You will get an email with the image. I also have removeContainer set to false so you can see the iframe there as well.

http://www.shallowsportx3.com

**Comment by chadlamson** [comment]
So looking into this further.... looks like the rendering is completely dependent on the actual browser width. I get completely different renderings when I resize my browser window, even though I have the windowWidth set to a fixed width. 

Is this expected behavior?

**Comment by calebwelch1** [comment]
@chadlamson did you ever find the solution to this problem? I'm getting the same issue where it seems windowWidth is being ignored and it defaults to window.innerWidth

**Comment by chadlamson** [comment]
@calebwelch1 Not really. I ended up using the onclone param to make adjustments to the elements I needed for the screenshot to look right.

**Comment by calebwelch1** [comment]
@chadlamson Replying so quickly to one of your two year old questions, thank you sir! I found by adding the 'x' x-crop param it seems to respect the windowWidth value. I hadn't thought of trying onclone though i'll definitely look into using that as a fix. Cheers!

**Comment by chadlamson** [comment]
@calebwelch1 No problem! Glad you got it working.
