### ISSUE TITLE
CSS transform: translate support

### ISSUE THREAD

**Issue by chadlamson** [niklasvh/html2canvas#1492]
I have several images that stack on top of each other, and are positioned absolutely. They are centered in the browser window by using: 

top:50%;
left:50%;
transform: translate(-50%, -50%);

I want to capture the div they are positioned inside of, but it appears html2canvas does not support the transform: translate property. The rendering has all of the images positioned outside of the window, and are cut off.

See site here: http://www.shallowsportx3.com

Is it possible to add support for this property?

**Comment by gqbre** [comment]
how did you fixed it ?
