### ISSUE TITLE
video Tag | iframe[ YouTube ] | embade Tag

### ISSUE THREAD

**Issue by vishal-px** [niklasvh/html2canvas#1499]
Hello @niklasvh 
The video, iframe with youtube and embed tag are not getting captured.

[Please see this video.](https://www.useloom.com/share/2313c2b212b245d0a43bb836b6764f2a)

Is there any solution for this issue?

### Specifications:

 * html2canvas version tested with: **1.0.0-alpha.12**
 * Browser & version: **Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)**
 * Operating system: **Ubuntu 16.04 LTS**

**Comment by nsmith1024** [comment]
Is this fixed now?
