### ISSUE TITLE
html2canvas.js:373 Invalid value given for Length: "auto"

### ISSUE THREAD

**Issue by xreign** [niklasvh/html2canvas#1514]
Error: `html2canvas.js:373 Invalid value given for Length: "auto"`
and
Error2:` localhost:8080/#!/Reports:1 Uncaught (in promise) invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)`

my controller contains

```
  $scope.export = function() {
        html2canvas(document.getElementById('balanceSheet')).then(function (canvas) {
            document.body.appendChild(canvas);
            var data = canvas.toDataURL();
            var docDefinition = {
                content: [{
                    image: data,
                    width: 500,
                }]
            };
            pdfMake.createPdf(docDefinition).download("test.pdf");
        });
    }
```

I already imported [pdfmake.min.js](https://raw.githubusercontent.com/bpampuch/pdfmake/master/build/pdfmake.min.js)
and [html2canvas.js](https://html2canvas.hertzen.com/dist/html2canvas.js)

any help here?

**Comment by berooney** [comment]
i also see the error :(

**Comment by herbertchow** [comment]
i see the error too...

**Comment by herbertchow** [comment]
i see the error too...  but it can render the pic correctly....-.-

**Comment by MikeBroders** [comment]
i see the message too. it's not really an error... it's just a console.log if the margin-styles of an element are neither "%" nor "px"

**Comment by naylee** [comment]
me too

**Comment by digitalkrafter** [comment]
Me too...got this one,Can any one have solution

**Comment by balkarov** [comment]
I have the same problem. Any solution?

**Comment by CrandellWS** [comment]
@MikeBroders at least best I know to help point ...

seems it is happening when used in connection with something like https://github.com/amiletti/spapp

**Comment by CrandellWS** [comment]
This might receive a better failure and or log event, otherwise I see no reason to keep this issue open

**Comment by CrandellWS** [comment]
I was able to work around the issue by moving the html content into a container on the document root (hard coded div loaded with dynamic content) take image move content back to original location...  

no not ideal but it worked...

**Comment by CrandellWS** [comment]
Well at least it works with my edits you can find at 
https://github.com/niklasvh/html2canvas/pull/374#issuecomment-436193769

```
var src_html = $('#src-child')[0];
var capture_container =$('#empty-container')[0];

 html2canvas(capture_container, {allowTaint : false, useCORS: true})
 .then(function(canvas) {console.log(canvas);});

$('#src-parent').append(src_html)
```

**Comment by saptaru** [comment]
Hello,
For me it was happening when an empty content html tag had `margin: 0 auto;`.
In my opinion the Length function should not print anything with console.error or any other log in case the value isNaN even in non production envs. Errors are logged in order to be fixed, but in this case the "auto" value is a valid css value for margins (in my case) so nothing has to be fixed.

Check https://github.com/niklasvh/html2canvas/blob/41eb8ab22fe9906824a9f03976c91f27a384bf72/src/Length.js#L24

Thanks!

**Comment by illusionized10** [comment]
@saptaru 

Can you please further explain your solution? I am currently in the process of integration a custom plugin I had created into another client's website. The second website is running a custom theme which may potentially have CSS attributes which might be breaking the html2canvas functionality.

I also have ensured the main wrapper which is being called by html2canvas is not empty which even on load the wrapper itself is not empty. I am perplexed by this problem and am wondering if perhaps a parent wrapper outside of what's being called by html2canvas could be causing the issue.

Main wrapper has following CSS:
``
max-width: 1200px;
background-color: #ffffff;
width: 1200px;
``

Ironically the framework and plugin runs completely fine on my local copy, it is only when moving it over to the client's website do problems arise. Would be great to hear some insight with respect to the annoying | Invalid value given for Length: "auto" | error.

**Comment by meyer20** [comment]
Hi, 

I'm having this problem by running my application as a custom-element. The problem does'n occur when I am using the application on my static content server.

`Invalid value given for Length: ""`

Details: https://imgur.com/a/1MWrtp2

**Comment by keyiis** [comment]
i see the error too... with angular 7.2/chrome73.0.3683.103/html2canvas v1.0.0-rc.1
but same code work well with electron

**Comment by TingNLP** [comment]
Is there a complete solution?
