### ISSUE TITLE
html2canvas still log  time/render info/$npm_package_version

### ISSUE THREAD

**Issue by realdennis** [niklasvh/html2canvas#1546]
### Bug reports:

html2canvas still log  time/render info/$npm_package_version from Logger.js
I think that log of html2canvas must not print in default 

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Chrome v66
 * Operating system: MacOS

**Comment by realdennis** [comment]
More info of this issue

<img width="472" alt="2018-06-01 3 03 18" src="https://user-images.githubusercontent.com/26633162/40826374-070a4b2e-65ad-11e8-9947-e463b326f0ec.png">

**Comment by gkontokotsios** [comment]
@realdennis: If what you want is to completely disable logging, you can do the following:
```javascript
window.html2canvas(
  document.getElementById('some-id'),
  {logging: false}
).then(function(canvas) {
  ...
});
```

**Comment by realdennis** [comment]
@gkontokotsios It works, thanks!
