### ISSUE TITLE
Help with DOMException error

### ISSUE THREAD

**Issue by vguenichon** [niklasvh/html2canvas#1548]
### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Firefox 60.0.1
 * Operating system: Mac OS 10.12.6

The console report these things (no image is generated) :
`JQMIGRATE: Migrate is installed, version 1.4.1
jquery-migrate.min.js:2:542
1ms html2canvas: html2canvas 1.0.0-alpha.12
html2canvas.js:2674:17
158ms html2canvas: Document cloned, using computed rendering
html2canvas.js:2674:17
158ms html2canvas: Starting node parsing
html2canvas.js:2674:17
159ms html2canvas: Added image http://com.antidot.net/wp-content/uploads/sites/9/2018/05/img5.jpg
html2canvas.js:2674:17
166ms html2canvas: Added image http://com.antidot.net/wp-content/themes/toilets/images/gradient10.svg
html2canvas.js:2674:17
172ms html2canvas: Added image http://com.antidot.net/wp-content/themes/toilets/images/fluidtopics.svg
html2canvas.js:2674:17
192ms html2canvas: Finished parsing node tree
html2canvas.js:2674:17
199ms html2canvas: Finished loading 3 images 
Array(3) [ img, img, img ]
html2canvas.js:2674:17
200ms html2canvas: Starting renderer
html2canvas.js:2674:17
200ms html2canvas: Canvas renderer initialized (1400x800 at 0,160) with scale 1
html2canvas.js:2674:17
201ms html2canvas: 
DOMException: An attempt was made to use an object that is not, or is no longer, usable
html2canvas.js:2688:17
error
http://com.antidot.net/wp-content/themes/toilets/js/html2canvas.js:2688:17
html2canvas/<
http://com.antidot.net/wp-content/themes/toilets/js/html2canvas.js:3389:13
`

If the console is opened, it refers to the line 2541 in the script : 
`            this.ctx.fillStyle = this.ctx.createPattern(this.resizeImage(image, imageSize), 'repeat');
`

Here's the page : http://com.antidot.net/snimage/ua-reloaded/
Could you help me finding where's my mistake ?
Thanks a lot

**Comment by odisleysi** [comment]
Same problem here.

**Comment by vguenichon** [comment]
Ok it was because of an unsupported CSS property : background-blend-mode
Shame :(
