### ISSUE TITLE
h2ml to canvas not working in firefox

### ISSUE THREAD

**Issue by GauravAjmera25** [niklasvh/html2canvas#1549]
h2ml to canvas is giving me this error in firefox.

> Invalid x value given for Vector
> DOMException: An attempt was made to use an object that is not, or is no longer, usable.
> 

html2canvas version: 1.0.0-alpha.12

code:
`  const input = document.getElementById('root');
html2canvas(input).then(canvas => {
      const imgData = canvas.toDataURL('image/png', 0.7);
    });
`

The code is working in chrome, but while running in firefox, it's giving me the above error.

<img width="841" alt="html2canvaserror" src="https://user-images.githubusercontent.com/22279719/40823288-7c2151b6-658d-11e8-993b-a4e430a641ec.png">

**Comment by barnamumtyan** [comment]
hey @GauravAjmera25, I am having the same issue you had on firefox, I see you closed the issue, I can you closed the issue. Can you please provide some information as to how you solved it? Thanks
