### ISSUE TITLE
rect fill value not recognized, results in black background

### ISSUE THREAD

**Issue by hnitzsche** [niklasvh/html2canvas#1551]
# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

The fill value, when set to a color or to none is not recognised by html2canvas. It results in a black color of this element rather than white or transparent.

I'm displaying several charts with ngx-charts in Angular and render these to a canvas with html2canvas. With one of the charts which contains an inside rect element as a bar chart background, I see this issue.

See this Stackblitz where I compare the rendering of a chart that contains this rect background (Grouped Bar Chart) and another chart that doesn't (Bar Chart).
[https://vertical-bar-chart-smoh7c.stackblitz.io/](https://vertical-bar-chart-smoh7c.stackblitz.io/)
[https://stackblitz.com/edit/vertical-bar-chart-smoh7c](https://stackblitz.com/edit/vertical-bar-chart-smoh7c)

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Chrome 66.0.3359.181
 * Operating system: macOS 10.13.4

**Comment by hnitzsche** [comment]
Just noticed that renaming the `g` element that is used to wrap some charts graphics that are svg elements, will also remove the black background.

So my bug report is slightly changing to a feature request for `g` element support.

[https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g)

**Comment by hnitzsche** [comment]
Forget about this issue. It is related to the computed/dynamic styles of ngx-charts. After applying the styles to the svg manually, html2canvas renders the svg correctly.

**Comment by sagarp2901** [comment]
This is how I ended up solving it, surprisingly it works:

 let rectElements = Array.from(document.getElementsByTagName('rect'));
  if (rectElements.length > 0) {
    rectElements.forEach(rect => {
      rect.setAttribute('fill', '#ffffff');
    });
  }

**Comment by subodhk01** [comment]
I gave white background to all the rect elements on my page and it fixed that
