### ISSUE TITLE
html2canvas option type: 'view' still render full body

### ISSUE THREAD

**Issue by mprabu0104** [niklasvh/html2canvas#1566]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by mprabu0104** [comment]
I would like to get only viewport screenshot from the library html2canvas.js, set option type to 'view' should do the trick but i'm still getting the entire body.
Don't really get why this is not working actually.
Here is the code i'm currently running:
html2canvas(document.body, { type: 'view' }).then(function(canvas) {
    var img = canvas.toDataURL("image/png");
    $('.ticket-img').attr('src', img);
});

**Comment by nishanthan89** [comment]
> I would like to get only viewport screenshot from the library html2canvas.js, set option type to 'view' should do the trick but i'm still getting the entire body.
> Don't really get why this is not working actually.
> Here is the code i'm currently running:
> html2canvas(document.body, { type: 'view' }).then(function(canvas) {
> var img = canvas.toDataURL("image/png");
> $('.ticket-img').attr('src', img);
> });

Did you find solution ?

**Comment by mklahorst** [comment]
> I would like to get only viewport screenshot from the library html2canvas.js, set option type to 'view' should do the trick but i'm still getting the entire body.
> Don't really get why this is not working actually.
> Here is the code i'm currently running:
> html2canvas(document.body, { type: 'view' }).then(function(canvas) {
> var img = canvas.toDataURL("image/png");
> $('.ticket-img').attr('src', img);
> });

Yeah, I am experiencing the same issue. Makes a huge file. I just want the current view

**Comment by mklahorst** [comment]
I went ahead and just added some code in my script that accomplishes this. You probably want to review it a bit or suit it for your needs, but it basically just crops the canvas object to the portion in the viewable area in your browser.


`html2canvas(document.body, {type: 'view'}).then(canvas => {

     
        var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
        var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);


        var offset = $(window).scrollTop();

        var cropX=0;
        var cropY=offset;
        var cropWidth=w;
        var cropHeight=h;

        var cropped = document.createElement('canvas');
        cropped.width=cropWidth;
        cropped.height=cropHeight;
        var ctxCropped=cropped.getContext('2d');
        ctxCropped.drawImage(canvas,cropX,cropY,cropWidth,cropHeight,0,0,cropWidth,cropHeight);

    
        var screenshot = cropped.toDataURL('image/jpeg');

    });`

**Comment by rayoz12** [comment]
It looks like 'type' hasn't been an option in a while and isn't in the documentation.

Instead it seems like options were added in that allowed the same flexibility.

The above comment can be optimized down to just using html2Canvas options rather than creating a new canvas and cropping the image.

		await html2canvas(document.body,
			x: window.scrollX,
			y: window.scrollY,
			width: window.innerWidth,
			height: window..innerHeight,
			logging: true,
		});

html2canvas might also take advantage of this and only need to render within the offset you give it instead of the whole document making it magnitudes faster.

**Comment by mklahorst** [comment]
@rayoz12 - thanks for the share! Code works great.

The rendering is faster, but since I am using proxy and some of the pages have tons of 2rd parts images on them, it still appears it needs to run proxy on all those images first, whether or not they are in the current viewable area. (it appears that way anyways).

You know of any workarounds for that? Basically only run proxy on images that are in the viewable area?

Either way - thanks for the code simplification!

**Comment by rayoz12** [comment]
@mklahorst You can possibly try using the ignoreElements option by checking if the image position is within the current viewport? However if the proxy runs before the ignoreElements function is called then this won't work.

**Comment by mklahorst** [comment]
@rayoz12 will definitely check it out if it continues to be a problem in the future and will post an update here

**Comment by joostvanhoof** [comment]
@mklahorst I'm running into the same thing (proxy loading all images instead of only the ones that you want to have rendered). Did you figure out a solution? Would be interesting to hear what you've tried!

**Comment by mklahorst** [comment]
@joostvanhoof We actually stopped using this library, and don't remember what we did!

**Comment by joostvanhoof** [comment]
Thanks. Did you end up using something different?

**Comment by mklahorst** [comment]
@joostvanhoof Actually transition to full PHP image generation instead of using canvas!

**Comment by joostvanhoof** [comment]
Interesting to do this server side. Any links or docs? Would love to read up on it. 

I managed to get ignoreImages working but although that makes images skip the proxy the problem is that it also removes those images from the DOM making the page shift up (because the images are now removed) and thus the capture inaccurate.

**Comment by tech-doctor** [comment]
> It looks like 'type' hasn't been an option in a while and isn't in the documentation.
> 
> Instead it seems like options were added in that allowed the same flexibility.
> 
> The above comment can be optimized down to just using html2Canvas options rather than creating a new canvas and cropping the image.
> 
> ```
> 	await html2canvas(document.body,
> 		x: window.scrollX,
> 		y: window.scrollY,
> 		width: window.innerWidth,
> 		height: window.innerHeight,
> 		logging: true,
> 	});
> ```
> 
> html2canvas might also take advantage of this and only need to render within the offset you give it instead of the whole document making it magnitudes faster.

This works fine. Thank you!
