### ISSUE TITLE
SecurityError when using Data URI background-image in Safari 11.1

### ISSUE THREAD

**Issue by ryenbeatty** [niklasvh/html2canvas#1575]
Hi there,

When trying to render a div with a background-image property set to a Data URI in Safari, html2canvas is throwing an Unhandled Promise Rejection:
`Unhandled Promise Rejection: SecurityError: The operation is insecure.`

This happens after the 'Render complete' phase happens, example console logs:

![image](https://user-images.githubusercontent.com/4946418/41924803-3aae75a0-796b-11e8-94b9-db9eb32e067b.png)

Example source html:
`<div style="background-image: url('data:image/svg+xml;base64,...');" />`

Seems to be a duplicate of [this issue](https://github.com/niklasvh/html2canvas/issues/1151)

Thanks,
Ryen

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Safari 11.1
 * Operating system: macOS Sierra 10.12.16

**Comment by Mivnv** [comment]
I've got the same error. Any updates here ?

**Comment by kxgio** [comment]
Same here
