### ISSUE TITLE
Transform:translate() not supported yet?

### ISSUE THREAD

**Issue by Joci933** [niklasvh/html2canvas#1601]
Hi,

Html2canvas will support transform:translate() css property? Now it isn't working well.

Thanks,

**Comment by alessandrobelli** [comment]
Still a problem.

**Comment by MatthiasSaihttam** [comment]
I just ran into this issue. Translations aren't taken into account when calculating overflow, and in my case, text was cut off where it would have been without a translation.

**Comment by Ricardo-Mochila-Bluesoft** [comment]
> I found a solution in my case: the container of the elements with transform:translate() had
> 
> ```
> overflow: hidden;
> ```
> 
> I changed it in
> 
> ```
> overflow: show;
> ```
> 
> and now my image is shown completely.

This only happened because overflow: show; is not valid CSS. 
That said, it solved your issue because html2canvas doesn't work well with overflow property yet.
