### ISSUE TITLE
Is it fine to use this script in prod environment!!

### ISSUE THREAD

**Issue by ABHIKSINGHH** [niklasvh/html2canvas#1619]
Sorry, rather I just need a confirmation here. I am not having any issue using this script. It works great. But just needed a quick confirmation as to whether it's safe to use this script in production environment? Because I still see on github home page mentioning "**The script is still in a very experimental state, so I don't recommend using it in a production environment nor start building applications with it yet, as there will be still major changes made.**" And also not sure since the latest release/update is still an alpha release.
Please confirm.

**Comment by ABHIKSINGHH** [comment]
@niklasvh - Could you please confirm on this?

**Comment by val1984** [comment]
We've been using this lib in production for a while and it seems fine.
Getting an approximate screenshot of what the user sees is a big help for support requests.

**Comment by ABHIKSINGHH** [comment]
If that's the case the content on github needs to be updated to avoid confusion.

**Comment by val1984** [comment]
I think that this warning is fine being there since the maintainer works on it on his free time as far as I know so you shouldn't expect fixes for your problems with this library being resolved in a timely manner unless you provide a pull request fixing it.
