### ISSUE TITLE
Support for css box-shadow - Generated Screenshot doesn't have box-shadow applied.

### ISSUE THREAD

**Issue by kcak11** [niklasvh/html2canvas#1622]
### Bug reports:

When elements on the page have box-shadow applied, then capturing the screenshot with html2canvas produces a screenshot _without_ the box-shadow.
However, text-shadow works fine. The issue is noticed only for **box-shadow**.

Please support **box-shadow** for the generated screenshots.

**Note**: I have tested on the homepage https://html2canvas.hertzen.com/ by applying box-shadow to certain elements and then captured the screenshot and noticed the issue.

### Specifications:

 * html2canvas version tested with: https://github.com/niklasvh/html2canvas/releases/download/v1.0.0-alpha.12/html2canvas.js
 * Browser & version: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 * Operating system: Mac OS X 10.13.5 (17F77)

**Comment by MaRuiL** [comment]
@kcak11 Box-shadow still won't work. When will this problem be fixed? It seems that this problem has been around for a long time.

**Comment by kcak11** [comment]
@MaRuiL just wanted to let you know, that I do not maintain this library. You may need to get in touch with @niklasvh (owner of this library) for feature requests.

I had this requirement during one of my projects earlier for rendering box-shadow screenshots, but then looks like this library is not being actively maintained, hence we came up with an in-house implementation for capturing screenshots with box-shadow.

I do see an open pull-request for box-shadow https://github.com/niklasvh/html2canvas/pull/1086  waiting from 27-March-2017 to get merged . . .

I am afraid, I cannot help much here as I am neither the admin for the repo nor have the merge rights.

**Comment by Muneem** [comment]
@kcak11 can you please share your soluton? As this library is outdated and there is no support available so its better to help other guys

**Comment by kcak11** [comment]
> @kcak11 can you please share your soluton? As this library is outdated and there is no support available so its better to help other guys

@Muneem I am afraid, I don't have that source code with me now as I have moved to a different project. When I last checked around October 2019, the box-shadow feature was working fine with the html2canvas library. There were couple of minor bugs which we had to work-around internally. 

Also there was these related PRs (https://github.com/niklasvh/html2canvas/pull/1653) and (https://github.com/niklasvh/html2canvas/pull/1795)

So I think you should try getting the latest version and check if it caters to your needs. 

Thanks.
