### ISSUE TITLE
文本<br />超过2个以上 生成图片后缺字

### ISSUE THREAD

**Issue by zhuchaoyang** [niklasvh/html2canvas#1627]
例如 文字 '一天很短短得来<br />不及拥抱清晨就已经手<br />握黄昏拥抱清晨就已经手握黄昏拥抱清晨就已经手握黄昏'。

转成图片后 ，iphone 会缺字， android正常

**Comment by Bruce-zxy** [comment]
**Translation:**
_Title_:**Text <br /> more than 2 images generated after word missing**
_Content_:
Such as:
'一天很短短得来
不及拥抱清晨就已经手
握黄昏拥抱清晨就已经手握黄昏拥抱清晨就已经手握黄昏'
When this text is turned into a picture, it will be **short of words** in **IOS** but **Android** is **normal**.

There are some questions here(我有一些疑问):
What does "<br />" mean in the title?(标题中<br />是啥意思啊？)
@zhuchaoyang

**Comment by Bruce-zxy** [comment]
I create a demo in [jsfiddle.net](jsfiddle.net), here's link:
[Demo](https://jsfiddle.net/w90erdL6/11/)

But I didn't found this problem you described.
@zhuchaoyang 

You can try it in [jsfiddle.net](jsfiddle.net), and put your code that has problem in the comments.

**Comment by gonghengda** [comment]
I had the same problem in ios 11.4.1

**Comment by wenruigao** [comment]
so, how to fix it?

**Comment by BettyWong256** [comment]
> I create a demo in [jsfiddle.net](https://jsfiddle.net), here's link:
> [Demo](https://jsfiddle.net/w90erdL6/11/)
> 
> But I didn't found the problem you described.
> @zhuchaoyang
> 
> You can try it in [jsfiddle.net](https://jsfiddle.net), and put your code that has problem in the comments.
if
<span>
  一天很短短得来<br/>
  不及拥抱清晨就已经手<br/>
  握黄昏拥抱清晨就已经手握黄昏拥抱清晨就已经手握黄昏<br/>
</span>

> I create a demo in [jsfiddle.net](https://jsfiddle.net), here's link:
> [Demo](https://jsfiddle.net/w90erdL6/11/)
> 
> But I didn't found the problem you described.
> @zhuchaoyang
> 
> You can try it in [jsfiddle.net](https://jsfiddle.net), and put your code that has problem in the comments.
like:
<div id="capture" style="padding: 10px;font-family: PingFang SC">
<p>
  一天很短短得来<br/>
  不及拥抱清晨就已经手<br/>
  握黄昏拥抱清晨就已经手握黄昏拥抱清晨就已经手握黄昏<br/>
</p>
<script src="https://unpkg.com/html2canvas@1.0.0-alpha.12/dist/html2canvas.min.js"></script>
