### ISSUE TITLE
svg not rendered correctly

### ISSUE THREAD

**Issue by zetaab** [niklasvh/html2canvas#1629]
two examples:
http://jsfiddle.net/hjd104co/
http://jsfiddle.net/L8279n3z/

for me it looks like that if html has some styles, it is ignoring whole css file.

### Specifications:

 * html2canvas version tested with: latest
 * Browser & version: chrome 67
 * Operating system: mac

**Comment by zetaab** [comment]
smaller example: http://jsfiddle.net/vbfrc1aw/ so css fill does not work at least in css file. However, if that css is inserted to element itself it works: http://jsfiddle.net/ew5nfckb/

**Comment by procoder-net** [comment]
if we are creating generic html2canvas, then how can insert css in element itself..

**Comment by zetaab** [comment]
this bug still exist in latest (1.0.0-rc3) version
