### ISSUE TITLE
When i try to screen an iframe with internal ip camera, it return a void image

### ISSUE THREAD

**Issue by AntonioDilorenzo** [niklasvh/html2canvas#1633]
i use the latest version

### Bug reports:

it return a blank image on rendered 

### Specifications:
 * Browser & version: Google Chrome  Version 67.0.3396.99 
 * Operating system: mac os high sierra 10.13.5

**Comment by m33ts4k0z** [comment]
This library is for creating screenshots from HTML content. If you mean that you are trying to create a screenshot from live streaming content from an IP camera then this will not work since the live stream is a video file and has nothing to do with HTML
