### ISSUE TITLE
applying text-shadow is generating incorrect screenshot

### ISSUE THREAD

**Issue by kcak11** [niklasvh/html2canvas#1638]
### Bug reports:
Applying text-shadow on a element is also applying text-shadow and box-shadow for other elements on the page. See attached PDF file. 

Page 1 describes the real page, and Page 2 shows the generated screenshot.

### Issues noticed in the Screenshot:

- Issue 1: **_All_** the text elements on the page have text-shadow applied.
- Issue 2: **_All the elements with a border_** also have the **box-shadow** applied.

Attachment:
[buggy_screenshot.pdf](https://github.com/niklasvh/html2canvas/files/2317797/buggy_screenshot.pdf)

### Specifications:

 * html2canvas version tested with: https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-alpha.12
 * Browser & version: Google Chrome 68.0.3440.106 (Official Build) (64-bit)
 * Operating system: macOS High Sierra 10.13.5

**Comment by kcak11** [comment]
Pull Request for the current issue: https://github.com/niklasvh/html2canvas/pull/1653
waiting for merge . . .

**Comment by niklasvh** [comment]
Fix merged with https://github.com/niklasvh/html2canvas/pull/1795

**Comment by kcak11** [comment]
> Fix merged with #1795

Thanks !!

**Comment by vincentcox** [comment]
@niklasvh Is this fix also expandable to this issue? https://github.com/niklasvh/html2canvas/issues/1622

It's box-shadow, so I don't know if it's the same method you used here.
