### ISSUE TITLE
Firefox relative position ignored

### ISSUE THREAD

**Issue by adjdred** [niklasvh/html2canvas#164]
I am currently using Leafletjs map with the marker cluster plugin. When i attempt to export the map we now get all the map tiles and markers as expected and save the image. The only thing that is missing is the number inside the marker cluster (example URL below). When using chrome the text is rendered perfectly but when using Firefox the text is no where to be seen. If I set "position:relative" on the marker then "position:absolute; top:0; left:0;" the relative position is ignored on the marker and bases its position off the map container which also has "position:relative" style. It would appear that any nested "position:relative" is ignored when using Firefox.

Example of map: http://leaflet.github.com/Leaflet.markercluster/example/marker-clustering-realworld.388.html

**Comment by shanggqm** [comment]
thanks to @programmin1 , it's really help me a lot

**Comment by prz3m3q** [comment]
@programmin1 it works! thanks :)
