### ISSUE TITLE
font-size don't take effect

### ISSUE THREAD

**Issue by nazhenhuiyi** [niklasvh/html2canvas#1664]
I use html2canvas latest version, but I find that if body is set 

```
body {
  font-variant: tabular-nums;
}
```
in my example, it display as 
![image](https://user-images.githubusercontent.com/11942909/46012695-9a6e1f80-c0fc-11e8-9e38-cd1a7e9958cf.png)

but the image that html2canvas create is
![image](https://user-images.githubusercontent.com/11942909/46012750-c8ebfa80-c0fc-11e8-940c-19ded6fc40a6.png)

the  font-size don't take effect, but in firefox it's okay
### Bug reports:

https://codesandbox.io/s/1y1xr1xjm4

### Specifications:

 * html2canvas version tested with: latest
 * Browser & version: chrome 69.0.3497.100
 * Operating system: mac os 10.13.6

**Comment by axy541877028** [comment]
I have encountered the same problem and hope that the author will solve it.

**Comment by axy541877028** [comment]
https://github.com/niklasvh/html2canvas/issues/1661 @nazhenhuiyi

**Comment by jackYouth** [comment]
你可以放大你的字体。 transform: scale(2.2);

**Comment by xfcdxg** [comment]
> 你可以放大你的字体。 transform: scale(2.2);

真的吗

**Comment by 827652549** [comment]
font-variant: normal;

**Comment by niklasvh** [comment]
Unable to repro this with 1.0.0
