### ISSUE TITLE
Cannot render iframe content

### ISSUE THREAD

**Issue by markb-trustifi** [niklasvh/html2canvas#1668]
version: 1.0.0-alpha.12
browser: chrome 69
os: Mac

The process is stuck when I add to the rendered element one of these iframes: 
`<iframe src="images/logo-icon.svg"></iframe>`
`<iframe src="data:text/html,<p>Some HTML</p>"></iframe>`

As far as I see it is stuck at function ResourceLoader.ready, line 187
Some of the promises remains pending forever and line `return Promise.all(values)` never reached.
If I change the original code to this one:
```JS
var values = keys.map(function (str) {
    return Promise.race([_this5.cache[str].catch(function (e) {
        if (process.env.NODE_ENV !== 'production') {
            _this5.logger.log('Unable to load image', e);
        }
        return null;
    }), new Promise(function(resolve, reject) {
        setTimeout(resolve, 5000, null);
    })]);
});
```
the file is rendered but the iframe area remains blank.

**Comment by tangdw** [comment]
+1

**Comment by rzontar** [comment]
Had the same problem in Firefox 65 on Windows. 1 promise never resolved or rejected.

Our solution was to add an `data-html2canvas-ignore="true"` attribute to all iframes before calling html2canvas.
