### ISSUE TITLE
capture starts only after the scrollTop 

### ISSUE THREAD

**Issue by filipegarcia** [niklasvh/html2canvas#167]
With v6.0.2 (8536.26.17) of Safari the capture of $('body') starts only after the viewport.

Instead of the hole body, is starts in $(window).scrollTop(), goes to the end of the document and adds blank space to make the image the height of the document.

I have a demo in http://jsbin.com/ociriy/2 ,try not to have the browser bigger than the document height.
The bug doesn't work with http://jsbin.com/ociriy/2/edit , maybe because is in iframe?

**Comment by sjamaan** [comment]
Perhaps this is the same issue as #333 - look there for a workaround

**Comment by usmonster** [comment]
@filipegarcia You using Safari on Mac OS or mobile Safari? Also, this is a very old bug.. Does the newest version from the master branch fix it for you?
