### ISSUE TITLE
When trying to get an image for a google map, I get it incomplete

### ISSUE THREAD

**Issue by AhmadMansour** [niklasvh/html2canvas#1674]
`
html2canvas(document.querySelector("#log-map"), { 
useCORS: true, 
useTainted: false 
}).then(function (canvas) {
var base64Map = canvas.toDataUrl('image/png');
});
`
I get an image like the following
![sample](https://user-images.githubusercontent.com/14887405/46479387-37ad1000-c7ef-11e8-8fde-694891c39e39.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Chrome
 * Operating system: Windows 10

**Comment by jbransf** [comment]
1674

**Comment by AhmadMansour** [comment]
Any help to resolve this issue?!
Thanks in advance.

**Comment by outerbound** [comment]
I am facing same issue.
AhmadMansour, since you closed this issue, what was the fix?

**Comment by AhmadMansour** [comment]
@outerbound 
It was fixed by changing the selector to '.gm-style'

`html2canvas(document.querySelector('.gm-style'), {
      useCORS: true
})`

then it worked well. 👍 

Thanks My Brother Anil :)
