### ISSUE TITLE
uncaught promise undefined

### ISSUE THREAD

**Issue by impactcolor** [niklasvh/html2canvas#1678]
I tried posting this in a closed comment and haven't received any responses so giving it a try here:
I'm using 1.0 alpha 12 release and I'm having the same problem. I've tried all of these solutions.

I've tried this solution by @smartbepl
html2canvas($("#element")[0]).then(function(canvas) {
$("#element-out").append(canvas);
});

I tried this by @jeremielodi
html2canvas($('#div').get(0)).then( function (canvas) {
console.log(canvas);
});

I also tried leandrocgsi solution and tried adding a catch as @ikemike suggest.

To simplify it and ensure all elements are loaded on the DOM, I place a function called take_screenshot().

function take_screenshot()
{
html2canvas($(".image__container")[0]).then(canvas => {
console.log('please work I am loosing my mind');
});
}
I then call take_screenshot() directly from the javascript console to ensure everything loaded.
I get the same error Uncaught (in promise) undefined.

**Comment by agleverone** [comment]
I'm also having this issue, only if I load the .js or .min.js file onto a live server. If I include the file using an html script tag, everything works as normal. Guess I'll be using the link for now.

**Comment by niklasvh** [comment]
This should be resolved in 1.1.1
