### ISSUE TITLE
Problem with color rendering

### ISSUE THREAD

**Issue by vguenichon** [niklasvh/html2canvas#1685]
### Bug reports:

I know it's a Firefox related thing but maybe someone here does yet have met the issue.
The generated image (saved as) from the canvas does not have the same colors in Firefox than in Chrome. Chrome is in the right colors.

![figure-out-who-is-using-your-technical-content-how-and-how-often_youtube](https://user-images.githubusercontent.com/1157822/47091209-ae510100-d224-11e8-9ba2-02643aff10f1.png)
![figure-out-who-is-using-your-technical-content-how-and-how-often_youtube 1](https://user-images.githubusercontent.com/1157822/47091211-aee99780-d224-11e8-85b7-de78854a8163.png)

I need help with this if there's a solution.

Thanks a lot

### Specifications:

 * html2canvas version tested with:
 * Browser & version: Firefox 62 & Chrome 70
 * Operating system: Mac OS 10.12.6

**Comment by vguenichon** [comment]
Firefox has default color management set. And it should remain as is.
Background color has now embed ICC profile (sRGB). The result give differences again.
As you can see, the background is an image and the ring around the picture of the guy is a pure CSS colored border, and the final rendered image does have differences for the background image.
![figure-out-who-is-using-your-technical-content-how-and-how-often_youtube](https://user-images.githubusercontent.com/1157822/47092987-78158080-d228-11e8-8b05-58b6eabfd387.png)
![figure-out-who-is-using-your-technical-content-how-and-how-often_youtube 1](https://user-images.githubusercontent.com/1157822/47092989-78158080-d228-11e8-8d47-8aeff977d864.png)

**Comment by vguenichon** [comment]
Well, subject closed. I won't take time to investigate and it's a recurrent issue in many posts and forums. The main issue is probably due the lack of color space definition (as there's no properties yet) in canvas AND the way the browsers convert these data.

**Comment by BobaGuaca** [comment]
I've had a similar problem while trying to render heat map data. The saved PNG is noticeably different in colour saturation levels than the original image, producing the same result in Firefox and Chrome.
