### ISSUE TITLE
1.0.0-alpha.12 Canvas not included and generates "Unable to load image " error 

### ISSUE THREAD

**Issue by rbartley** [niklasvh/html2canvas#1686]
### Bug reports:

The following (value below) generates an error "Unable to load image " at line 2667. (in browser image and result image attached)

![in browser](https://user-images.githubusercontent.com/35139536/47216028-d4e97600-d3a3-11e8-9ae1-cf7f6f0bd04f.PNG)

![html2canvas result - missing map](https://user-images.githubusercontent.com/35139536/47216045-eb8fcd00-d3a3-11e8-93dc-bfbe3aaaccd5.png)

"line-break: auto; caret-color: rgb(89, 89, 89); ry: auto; rx: auto; r: 0px; y: 0px; x: 0px; cy: 0px; cx: 0px; d: none; paint-order: fill; vector-effect: none; writing-mode: horizontal-tb; text-anchor: start; dominant-baseline: auto; baseline-shift: 0px; alignment-baseline: auto; stroke-width: 1px; stroke-opacity: 1; stroke-miterlimit: 4; stroke-linejoin: miter; stroke-linecap: butt; stroke-dashoffset: 0px; stroke-dasharray: none; stroke: none; shape-rendering: auto; mask-type: luminance; marker: none; fill-rule: nonzero; fill-opacity: 1; fill: rgb(0, 0, 0); color-rendering: auto; color-interpolation-filters: linearRGB; color-interpolation: sRGB; stop-opacity: 1; stop-color: rgb(0, 0, 0); lighting-color: rgb(255, 255, 255); flood-opacity: 1; flood-color: rgb(0, 0, 0); filter: none; mask: none; clip-rule: nonzero; clip-path: none; buffered-rendering: auto; -webkit-app-region: no-drag; -webkit-writing-mode: horizontal-tb; user-select: auto; -webkit-user-modify: read-only; -webkit-user-drag: auto; transform-style: flat; transform-origin: 0px 0px 0px; transform: none; -webkit-text-stroke: 0px rgb(89, 89, 89); -webkit-text-security: none; -webkit-text-orientation: vertical-right; -webkit-text-fill-color: rgb(89, 89, 89); -webkit-text-emphasis: none rgb(89, 89, 89); -webkit-text-emphasis-position: over right; -webkit-text-decorations-in-effect: none; -webkit-text-combine: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); shape-margin: 0px; shape-image-threshold: 0; shape-outside: none; -webkit-rtl-ordering: logical; -webkit-print-color-adjust: economy; perspective-origin: 0px 0px; perspective: none; order: 0; -webkit-mask: none 0% 0% / auto repeat border-box border-box; -webkit-mask-composite: source-over; -webkit-mask-box-image-width: initial; -webkit-mask-box-image-source: none; -webkit-mask-box-image-slice: initial; -webkit-mask-box-image-repeat: initial; -webkit-mask-box-image-outset: initial; -webkit-margin-collapse: collapse collapse; -webkit-locale: "en-US"; -webkit-line-break: auto; -webkit-hyphenate-character: auto; hyphens: manual; -webkit-highlight: none; grid-gap: 0px 0px; grid-area: auto / auto / auto / auto; grid-template-rows: none; grid-template-columns: none; grid-template-areas: none; grid-auto-rows: auto; grid-auto-flow: row; grid-auto-columns: auto; -webkit-font-smoothing: antialiased; place-content: normal; flex-flow: row nowrap; flex: 0 1 auto; place-self: auto; place-items: normal; columns: auto auto; column-span: none; column-rule: 0px none rgb(89, 89, 89); column-gap: normal; -webkit-box-pack: start; -webkit-box-orient: horizontal; -webkit-box-ordinal-group: 1; -webkit-box-lines: single; -webkit-box-flex-group: 1; -webkit-box-flex: 0; -webkit-box-direction: normal; -webkit-box-decoration-break: slice; -webkit-box-align: stretch; border-spacing: 0px; -webkit-border-image: none; backface-visibility: visible; -webkit-appearance: none; zoom: 1; z-index: auto; word-wrap: normal; word-spacing: 0px; word-break: normal; will-change: auto; width: 0px; widows: 2; white-space: normal; visibility: visible; vertical-align: baseline; unicode-bidi: normal; transition: all 0s ease 0s; touch-action: auto; top: -1000px; text-transform: none; text-overflow: clip; text-size-adjust: 100%; text-shadow: none; text-rendering: optimizeLegibility; text-indent: 0px; text-underline-position: auto; text-decoration-skip-ink: auto; text-decoration: none solid rgb(89, 89, 89); text-align-last: auto; text-align: start; tab-size: 8; table-layout: auto; speak: normal; scroll-behavior: auto; right: 2231px; resize: none; position: absolute; pointer-events: auto; padding: 0px; overflow: visible; overflow-wrap: normal; overflow-anchor: auto; outline: rgb(89, 89, 89) none 0px; outline-offset: 0px; orphans: 2; opacity: 1; offset: none 0px auto 0deg; object-position: 50% 50%; object-fit: fill; mix-blend-mode: normal; min-width: 0px; min-height: 0px; max-width: none; max-height: none; margin: 0px; list-style: disc outside none; line-height: 25.7143px; letter-spacing: normal; left: -1000px; isolation: auto; image-rendering: auto; height: 0px; font-weight: 400; font-variant: normal; font-style: normal; font-stretch: 100%; font-size: 18px; font-kerning: auto; font-family: sans-serif; float: none; empty-cells: show; display: block; direction: ltr; cursor: auto; color: rgb(89, 89, 89); clip: auto; clear: none; caption-side: top; break-inside: auto; break-before: auto; break-after: auto; box-sizing: border-box; box-shadow: none; bottom: 1940px; border: 0px none rgb(89, 89, 89); border-radius: 0px; border-collapse: separate; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); background-blend-mode: normal; animation: none 0s ease 0s 1 normal none running;

### Specifications:

 * html2canvas version tested with: 1.0.0-alpha.12
 * Browser & version: Version 64.0.3282.119 (Official Build) (64-bit)
 * Operating system: Windows 7 Enterprise SP 1

**Comment by ShawLyon** [comment]
我也遇到这个问题
