### ISSUE TITLE
error on line 1 at column 158: Specification mandates value for attribute h

### ISSUE THREAD

**Issue by ayadavkrt** [niklasvh/html2canvas#1716]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
 I am using HTML2Canvas for quite a long time now, for downloading c3 charts, in my react application.
When I tried to implement a download option for the multiline chart (time series chart), I get this error 

![image](https://user-images.githubusercontent.com/29532064/49513689-d5888e00-f8b7-11e8-9081-a691a9c62ab3.png)

console:
```
5049ms html2canvas: Document cloned, using computed rendering
Logger.js:36 5054ms html2canvas: Starting node parsing
Logger.js:36 5067ms html2canvas: Added image data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2261785%22%20height%3D%22420%22%20style%3D%22overflow%3A%20hidden%3B%22%3E%3Cdefs%3E%3CclipPath%20id%3D%22c3-1544012385483-clip%22%3E%3Crect%20width%3D%2261733%22%20h
Logger.js:36 5097ms html2canvas: Finished parsing node tree
Logger.js:36 5111ms html2canvas: Finished loading 1 images [img]
Logger.js:36 5113ms html2canvas: Starting renderer
Logger.js:36 5115ms html2canvas: Canvas renderer initialized (61950x427 at 281,-206) with scale 1
Logger.js:36 5147ms html2canvas: Render completed
```

### Specifications:

 * html2canvas version tested with: Latest
 * Browser & version: Chrome Latest
 * Operating system: Ubuntu

**Comment by singhsterabhi** [comment]
Please provide a solution for this error. I am facing this issue right now.
