### ISSUE TITLE
Capture nested <canvas> tags with HTML2Canvas

### ISSUE THREAD

**Issue by scgough** [niklasvh/html2canvas#1721]
I'm wondering - using Html2Canvas if I capture a containing `<div>` then is there a way to also include a nested `<canvas>` tag within said div?

I have my capture working but there is essentially a gap where the nested canvas sits on-screen.

Example code:
```
<div id="my-container">
   <h2>my title</h2>
   <p>Some other content here</p>
   <canvas id="existing-canvas" height="270" style="height:270px;"></canvas>
   <p>Some more content</p>
</div>

<script>
html2canvas(document.getElementById("my-container")).then(function(canvas) {
    var dataUrl = canvas.toDataURL();
    //do something with the base64 image data here...
</script>

```
I can capture `my-container` and it's contents _but_ the captured image has a blank space where the nested canvas element is.

**Comment by scgough** [comment]
Ignore me - this is a timing issue on my part. The nested canvas element in question is saved but i'm doing so before its contents have been rendered to the DOM.

**Comment by MrJiDong** [comment]
> Ignore me - this is a timing issue on my part. The nested canvas element in question is saved but i'm doing so before its contents have been rendered to the DOM.


hi,I have same question. The nested canvas have been rendered but it's black.

![image](https://user-images.githubusercontent.com/48897264/97946909-a55d0900-1dc6-11eb-8f7f-95026306e696.png)
![image](https://user-images.githubusercontent.com/48897264/97946419-5662a400-1dc5-11eb-9e23-fba863645607.png)
![image](https://user-images.githubusercontent.com/48897264/97946954-bf96e700-1dc6-11eb-8a18-7ef3b2a6a1f2.png)
![image](https://user-images.githubusercontent.com/48897264/97946965-ca517c00-1dc6-11eb-8bdf-1c392fa073c8.png)
