### ISSUE TITLE
canvas.toDataURL("image/png")

### ISSUE THREAD

**Issue by yrl** [niklasvh/html2canvas#1725]
canvas.toDataURL("image/png") ;
 i find result is "data:,";
pelease tell me why，thank you 。
the result is in ios and Android；

**Comment by ikumaran** [comment]
when result is  "data:," - it means the canvas doesnt have any image content.

**Comment by Przeblysk** [comment]
This problem also appeared in my work, but not all devices have this problem, only my boss's iPhone7plus has this problem, I returned 0.5.0-beta4 problem was solved. The canvas in the callback function is empty.

**Comment by esoyke** [comment]
I also am experiencing this issue on my iPhone 7. The problem goes back to v1.0.0-alpha.1. Unfortunately 0.5.0-beta4 has other issues for me, so I'm kind of stuck.

**Comment by feidao158** [comment]
i'm find this problem too on my Iphone 7 plus,so how should i do

**Comment by Przeblysk** [comment]
> i'm find this problem too on my Iphone 7 plus,so how should i do
 I returned 0.5.0-beta4 version

**Comment by Przeblysk** [comment]
> i'm find this problem too on my Iphone 7 plus,so how should i do

@feidao158  I returned 0.5.0-beta4

**Comment by amqqliang** [comment]
> i'm find this problem too on my Iphone 7 plus,so how should i do

The default scale is window.devicePixelRatio
iphone7's window.devicePixelRatio is 3
so set the maximum scale 2

```
html2canvas(document.body, {
    scale: window.devicePixelRatio > 2 ? 2 : window.devicePixelRatio
}).then(...);
```
