### ISSUE TITLE
Custom elements ( web components ) get rendered again when passed as content to html2canvas

### ISSUE THREAD

**Issue by rcsatheeshkumar** [niklasvh/html2canvas#1726]
- [x] You are using the latest [1.0.0-alpha 12](https://github.com/niklasvh/html2canvas/releases/download/v1.0.0-alpha.12/html2canvas.js)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

When the content passed to  html2canvas contains a [custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) it is getting rendered again in the actual DOM itself. It could be visually seen getting re-rendered. Please find the sample in the below jsfiddle. How could I stop it from being re-rendered?

[jsfiddle](http://jsfiddle.net/rcsatheeshkumar/kpb7s20j/2/).

### Specifications:

 * html2canvas version tested with:  1.0.0-alpha 12
 * Browser & version:   Chrome 71.0.3578.98
 * Operating system:    Mac OS Mojave

**Comment by rcsatheeshkumar** [comment]
@niklasvh Please give your opinion on this issue. Your help is highly appreciated.

**Comment by iyangsheng** [comment]
Has it been solved? I have the same problem.

**Comment by rajsite** [comment]
I'm also seeing similar types of issues with custom elements. The same problems don't seem to happen with [html-to-image](https://github.com/bubkoo/html-to-image) but unfortunately html-to-image does not support Safari because it relies on foreignObject.
