### ISSUE TITLE
image not capturing while using Electron

### ISSUE THREAD

**Issue by naxiemolv** [niklasvh/html2canvas#1727]
First - thanks for your hard work - this is an extremely library :)

a scrollable div with 5 same  <img>(local file) ,it works .(height:825px )        
a scrollable div with 6 same <img>(local file) ,i got empty image only.(height:1035px )

**Comment by naxiemolv** [comment]
sorry,my fault,nothing error with this.
window.open() does'n support  jpeg with (1715x1715).
finally I write to a file successfully .

**Comment by burakkp** [comment]
Hi @naxiemolv ,
If this issue was solved or You found problem. You can close this issue. This is more useful for developers.
