### ISSUE TITLE
Performance issue with IE11

### ISSUE THREAD

**Issue by ikumaran** [niklasvh/html2canvas#1731]
Version: v1.0.0-alpha.12

I have a page with quite a number of divs and text contents. When i try to capture screenshot,
*  from Chrome and FF - it works better - say - 4-5 seconds.
* But from IE11 - it takes more than 15 seconds. 

Please note, there are no problem with screenshot quality - but only problem is the amount of time to capture the screenshot in IE11 is a big concern.

**My code:**
var captureScreenshotData = function (event, message) {
        if (message && !message.domElement) {
            return;
        }
        // start timer
        html2canvas(message.domElement, {
            useCORS: true,
            imageTimeout: 3000,
            width: 800, height: 1000
        }).then(function (screenshotCanvas) {
        // end timer - it takes 10-15 sec to enter this loop in IE11, but only 4-5 sec in Chrome/FF.
            var base64ImageUrl = screenshotCanvas.toDataURL();
            $scope.myArray.push({
                image: base64ImageUrl, otherData: "dummy"
            });
        }, function (error) {
            console.log(error);
        });
    };

Any best practices to ensure - to improve the performances during screen capture in IE11 (or any browser).

Logs from IE11 for reference:
[html2canvas_IE11.txt](https://github.com/niklasvh/html2canvas/files/2721083/html2canvas_IE11.txt)

Note, I used imageTimeout as 3000 - but even then its not timing out in Chrome or in IE11.

Please let me know, whether additional details required.

**Comment by ikumaran** [comment]
Able to resolve issue with usage of "ignoreElements" config option. Its pretty fast now.

After the change, Chrome takes 1-2 seconds and IE11 takes 5-7 seconds. Thats managable for now.

Thanks!

**Comment by vinodkrishnamps** [comment]
HI Kumaran,

I am creating 6 pages of PDF using Image and it is taking 3+ minutes whereas in Chrome it is taking only 15 seconds. Please let me know how you used the ignoreElements

Thanks
vinod.

**Comment by ikumaran** [comment]
Hi Vinoth - you can configure options something like,
                ignoreElements : function(elem) {
                    return <true - incase you need the element to be ignored>;
                };

Hence, returned true for dom elements not in my dom tree, and set false for required dom elements.
