### ISSUE TITLE
How to remove certain element from being cloned when using onClone?

### ISSUE THREAD

**Issue by ibrahimYahoo** [niklasvh/html2canvas#1732]
when the onClone  is called for the document, I have an iframe in my document, which starts to reload with all its scripts every time onClone is called which significantly increases the time to complete the cloning of the document.

 Is there a way I can remove certain element from being cloned?  and I cannot remove the iframe or remove the src of the iframe before it is cloned.
thank you.

**Comment by mmahlies** [comment]
@ibrahimYahoo  
By default, Html2canvas will ignore any Html element with  data-html2canvas-ignore attribute.

if you have specific logic you want to apply before ignoring the element you can use ignoreElements function from option that passed to Html2canvas , for more information please read
https://html2canvas.hertzen.com/configuration

**Comment by ibrahimYahoo** [comment]
@mmahlies i know about the ignore attribute,but the iframe is not part of the element to be rendered, it is just part of the document that is to be cloned, .
