### ISSUE TITLE
css lost

### ISSUE THREAD

**Issue by lxt410725** [niklasvh/html2canvas#1745]
When using react for single-page project, when using html2Canvas to save the image, the saved image style was somewhat lost.

**Comment by chenfenggiser** [comment]
well, i have the same problem, when i  use the html2canvas to generate image, all css styles are lost.
The version i used is "html2canvas": "^1.0.0-alpha.12", my codes are something like:

html2canvas(document.getElementById('inspection-pdf')
           ).then((canvas) => {
            let contentWidth = canvas.width;
            let contentHeight = canvas.height;
  
            let pageHeight = contentWidth / 595.28 * 841.89;
           
            let leftHeight = contentHeight;
            
            let position = 30;
            
            let imgWidth = 555.28;
            let imgHeight = 555.28/contentWidth * contentHeight;
            let pageData = canvas.toDataURL('image/jpeg', 1.0);
          
            let pdf = new jsPDF('','pt', 'a4');
         
            if (leftHeight < pageHeight) {
                pdf.addImage(pageData, 'JPEG', 30, 30, imgWidth, imgHeight );
            } else {
                while(leftHeight > 0) {
                    pdf.addImage(pageData, 'JPEG', 30, position, imgWidth, imgHeight)
                    leftHeight -= pageHeight;
                    position -= 841.89;
                    if(leftHeight > 0) {
                        pdf.addPage();
                    }
                }
            }
            pdf.save('Inspection.pdf');
        });

Some can help me? Please:)
