### ISSUE TITLE
Cross-origin image load denied by Cross-Origin Resource Sharing policy.

### ISSUE THREAD

**Issue by archbayleef** [niklasvh/html2canvas#175]
While using html2canvas in Chrome, function methods.loadImage crashes after img.crossOrigin="anonymous" and img.src=src
![bug](https://f.cloud.github.com/assets/3855088/254295/853bf476-8bf0-11e2-829d-13f782db1757.png)

**Comment by usmonster** [comment]
Those following this issue may also want to follow #509.
