### ISSUE TITLE
Securityerror (dom exception 18) the operation is insecure - Safari

### ISSUE THREAD

**Issue by jgrDev** [niklasvh/html2canvas#1758]
Hi, 

the elements type select cause the following error in safari:

`Securityerror (dom exception 18) the operation is insecure.`

The error is produced when canvas.toDataURL is called, because the object canvas is corrupted.

Thanks!

**Comment by jenilChristo** [comment]
Was facing the same issue in safari . Setting the `useCORS:false` , solved the issue for me

`
html2canvas(document.body,{useCORS:false}).then(function(canvas){
        window.screenshot = canvas.toDataURL('image/png');
   });
`
