### ISSUE TITLE
html2canvas not working with highcharts svg

### ISSUE THREAD

**Issue by wencelf** [niklasvh/html2canvas#1765]
### Bug reports:

When converting html2canvas from a highcharts graph, the graph is not rendered on the canvas. This was working a while ago but now it is not working. Here is an example of the issue, as you can see the canvas generated does not have the graph.

https://jsfiddle.net/n0qwevd8/3/

### Specifications:

 * html2canvas version tested with: Plain Javascript
 * Browser & version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
 * Operating system: Windows 10

**Comment by cristomc** [comment]
I think that is not an issue, As fiddle works, you have an animation and the plugin start to render canvas at the same time, so the image generated is correct. 

Maybe you should disable highcharts animations or add a delay/timeout in the call of the plugin method

**Comment by fredmartinssilva** [comment]
Hi everyone, i tested with Timeout on the 2s and run correct the canvas.

**Comment by ZeeshanAhmadKhalil** [comment]
For me, it's not working with any SVG don't know why

**Comment by rt83FMR** [comment]
Hi,

I am also facing the issue in html2canvas in LWC. for more details please check below link where I post my LWC code : https://stackoverflow.com/questions/77363410/html2canvas-is-throwing-error-when-passing-the-element-to-it-in-lwc
