### ISSUE TITLE
compilation issue with html2canvas version 1.0.0-alpha.12 with angular 6 || error - can't find module 'css-line-break'

### ISSUE THREAD

**Issue by rochakravi** [niklasvh/html2canvas#1766]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by jopankaj89** [comment]
i am using html2canvas version 1.0.0-alpha.12 with React.js v16. In local it is working fine but in prod it says **Forbidden: css-line-break@1.0.1**. please guide to deal with this.
