### ISSUE TITLE
Text overlap on iOS browser.

### ISSUE THREAD

**Issue by phyopwint1912** [niklasvh/html2canvas#1767]
Hi, 
I've been using this library for generating canvas from my #div. Every content are generating fine as I've shown in my #div except from iOS browser. I've tried with android and desktop also. they are working fine. only iOS have problem. Is there any limitation for this library.

**Comment by timeTravelCYN** [comment]
@phyopwint1912  hello,I have encountered the same problem.Have you solved this problem yet?looking forward to your reply.thanks
