### ISSUE TITLE
Async flag does not work

### ISSUE THREAD

**Issue by alimovz** [niklasvh/html2canvas#1769]
`html2canvas(document.body, {async: false, logging: true}).then(function(canvas){...`

The async flag, whether set to true or false, does not seem to change the behavior. Any way to actually make it run in synchronous mode?

**Comment by niklasvh** [comment]
Fixed the documentation regarding the `async` option, which doesn't exist anymore. Due to the async nature of what html2canvas, it is not feasible to do it `async`.
