### ISSUE TITLE
Bullets are not rendered

### ISSUE THREAD

**Issue by christian8287** [niklasvh/html2canvas#177]
If i have an unordered or ordered list in my html markup, the bullets are not rendered by html2canvas. I think this is quite an important issue because this is a standard feature of html supported in all browsers since a long time ago.

**Comment by brandonkboswell** [comment]
Just curious if this is being considered, or if there is anything I can do to help move this feature along.

**Comment by niklasvh** [comment]
It is considered and will be implemented at some point. PR #486 was made for it, and I gave some feedback on it. Once those are resolved, it could get merged.

**Comment by andersborgabiro** [comment]
Any likelihood this will be solved in html2canvas in the near future?

I looked for "ul", "ol", "li" in the code and found nothing, yet <li>'s are indented, so there must be some logic for it. Anyone that could point to where this would be located in the code, if it's now at all there?

**Comment by Kevinlearynet** [comment]
It's a hack for sure, but I was able to support a bulleted `<ul>` in the PDF with this approach:

**HTML**
~~~
<ul>
	<li><span class="bullet">&bull;</span>Replace your income, with a {{ output.monthlyIncome | currency }} monthly check</li>
	<li><span class="bullet">&bull;</span>Pay down your mortgage to zero</li>
	<li><span class="bullet">&bull;</span>Pay down your debt to zero</li>
	<li><span class="bullet">&bull;</span>Pay 100% of your kids’ education in a public college or university</li>
	<li><span class="bullet">&bull;</span>Remain covered until your spouse/partner turns 65 or your youngest child turns 23, whichever comes first</li>
</ul>
~~~

**LESS/CSS**
~~~
#pdf-canvas ul {
	list-style: none;
	padding: 0;
}

#pdf-canvas ul li {
	margin: 0 0 0 35px;
	list-style: none;

	.bullet {
		display: inline-block;
		opacity: 0.85;
		font-size: 1.1em;
		text-indent: -22px;
	}
}
~~~

Where `#pdf-canvas` is the name of a hidden DIV with the PDF template in it. Hope this helps anyone else trying to do this.

**Comment by andersborgabiro** [comment]
I use TinyMCE for the editing, and users must not see any of the "inner workings", but there might be a way to extend so that a span is inserted.

Why doesn't it work with applying the bullet characteristics directly to ul li?

**Comment by narvalblog** [comment]
An other simple hack:

**HTML**
`<ul>
  <li>item 1</li>
  <li>Item 2</li>
</ul>`

**SCSS**
`ul li {
ul li {
  list-style-type: none;
  &:before {
    content: '• ';
    margin-left: -1em;
  }
}
}`

**Comment by andersborgabiro** [comment]
I wonder though, why can't this be solved in html2canvas?

**Comment by vagvaf** [comment]
My approach to by-pass this was to create a table with 2 columns and put • in the first column and the text in the second. It was the only way that it was rendered correctly

**Comment by andersborgabiro** [comment]
I tested right now, and HTML lists work fine in 1.0.0 alpha 10.

**Comment by tininess** [comment]
https://jsfiddle.net/boLxkgj8/264/ I can't render Bullet :( How could you do that

**Comment by RUSSCITY** [comment]
> https://jsfiddle.net/boLxkgj8/264/ I can't render Bullet :( How could you do that

ok, you was not using the latest version, now it looks like it works:
https://jsfiddle.net/jeavhg05/4/

**Comment by porbis-rmishra** [comment]
Can some share me HTML and JS used on for this JS. I am using same but PDF file is not created.
https://jsfiddle.net/jeavhg05/4/

**Comment by policiadestiny** [comment]
ul li { list-style-type: none;}
ul li:before { content: '• '; margin-left: -1em; }

ol li { list-style-type: none;}
ol li:before { content: '- '; margin-left: -1em; }
