### ISSUE TITLE
Creating Image PDF is very slow taking 5 minutes to create Image pdf of page size 6

### ISSUE THREAD

**Issue by vinodkrishnamps** [niklasvh/html2canvas#1771]
Hi,

I am creating a pdf from the UI and page size is 5 to 6 pages. I am experiencing two issues particularly in IE 11
1) Creation of PDF is very slow for 6+ pages and below are the readings from console.

428900ms html2canvas: Document cloned, using computed rendering
428903ms html2canvas: Starting node parsing
514786ms html2canvas: Finished parsing node tree
514790ms html2canvas: Finished loading 0 images 
   "514790ms"
   "html2canvas:"
   "Finished loading 0 images"
   [
      length: 0
   ]

514797ms html2canvas: Starting renderer
514800ms html2canvas: Canvas renderer initialized (1319x3056 at -5,6201.60009765625) with scale 1
514944ms html2canvas: Render completed

2) If the page size is more that 5 then in IE 11 i am seeing black screen. 

Please let me know how to reduce my timing in IE. In Chrome it takes 10-15 seconds whereas in IE11 it is taking 6 to 7 minutes for the same PDF.

Thanks
vinod.

**Comment by snimmagadda1** [comment]
@niklasvh dropping in late - were you ever able to increase performance?

**Comment by vinodkrishnamps** [comment]
Hi

We dropped that approach and used Java to create pdf.

Thanks
Vinod
