### ISSUE TITLE
@zhuSass

### ISSUE THREAD

**Issue by JackYangFM** [niklasvh/html2canvas#1774]
@zhuSass 
配置项里加这个试试
useCORS: true,//允许访问服务器资源

_Originally posted by @zhaozhuoboy in https://github.com/niklasvh/html2canvas/issues/1357#issuecomment-369478215_

**Comment by maicWorkGithub** [comment]
丢不丢人，人家又不是中国人开的仓库，你用中文聊天就算了，你这是问题吗，你为啥不直接在他那个问题下回复别人？

@niklasvh please close this. This is a spam. He is talk to someone, not even a question. And I suggest to block someone like this.
