### ISSUE TITLE
header in multiple page for pdf not generated

### ISSUE THREAD

**Issue by tarangSachdev92** [niklasvh/html2canvas#1776]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by tarangSachdev92** [comment]
I need header in all pages of the generated pdf.
import html2canvas from 'html2canvas';

declare let jsPDF;

`generate = () => {
        const data = document.getElementById('axesReport');
        const doc = new jsPDF('p', 'pt', 'a4');
        doc.internal.scaleFactor = 1.55;
        doc.context2d.pageWrapY = doc.internal.pageSize.height - 20;

        html2canvas(data).then(canvas => {
            const imgWidth = 210;
            const pageHeight = 295;
            const imgHeight = canvas.height * imgWidth / canvas.width;
            const heightLeft = imgHeight;

            const doc = new jsPDF('p', 'mm', 'a4'); // A4 size page of PDF
            let position = 0;

            const contentDataURL = canvas.toDataURL('image/png');
            doc.addImage(contentDataURL, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= pageHeight;
            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                doc.addPage();
                doc.addImage(contentDataURL, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pageHeight;
            }
            doc.save('sample-file.pdf');
        })
    };`

I am able to get 2 pages but i need header in all the pages
here is my html code

`<div id="axesReport" style="background: #fff; padding: 50px;">
    <header>
        <div style="float: left; width:50%;">
            <img width="200" src="assets/images/login-logo.png" alt="">
        </div>
        <div style="float: left; width:50%; text-align: right">
            <img width="125" src="assets/images/logo.png" alt="">
        </div>
    </header>

    <div>
        <div style="clear: both;"></div>

        <div>
            <div style="text-align: center">
                <h1 style="font-weight: normal; font-size: 50px; margin-bottom: 15px">Self-Assessment Report</h1>
                <h3 style="font-weight: normal; font-size: 28px; margin-bottom: 15px">Self-Assessment :
                    5c91326cab7bf00017a03a52</h3>
                <h5 style="font-weight: normal; font-size: 28px">Date : 20/03/2019 18:59:30</h5>
            </div>
        </div>

        <div style="margin-top: 30px;">
            <h4 style="font-weight: 400; color: #3f51b5; font-size: 36px; text-decoration: underline; margin-bottom: 25px">
                Self-Assessment:</h4>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;">
                <span style="color: #3f51b5;">ID : </span>5c91326cab7bf00017a03a52
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;">
                <span style="color: #3f51b5;">Description : </span>5c91326cab7bf00017a03a52
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;">
                <span style="color: #3f51b5;">Created By : </span>Name- Email
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;"><span
                    style="color: #3f51b5;">Assessment Plan : </span>AssessmentPlan Code
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;"><span
                    style="color: #3f51b5;">Entity : </span>Entity
                Code
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;"><span
                    style="color: #3f51b5;">Created On : </span>CreatedOn
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 30px;"><span
                    style="color: #3f51b5;">Status : </span>Status
                (0: In progress, 1: Finished, 2: Published)
            </div>
            <div style="color: #333; font-size: 28px; margin-bottom: 70px;"><span
                    style="color: #3f51b5;">Number of Axes : </span>3
            </div>

            <h4 style="font-weight: 400; color: #3f51b5; font-size: 36px; text-decoration: underline; margin-bottom: 25px">
                Axes:</h4>

            <div *ngFor="let i of [1,2,3,4]; let i = index;" style="margin-bottom: 80px;">
                <div style="color: #333; font-size: 28px; margin-bottom: 20px;"><span
                        style="color: #3f51b5; text-decoration: underline">Axe {{i}}</span></div>
                <div style="color: #333; font-size: 28px; margin-bottom: 20px;"><span
                        style="color: #3f51b5;">Description : </span>E01 Organisation et R&R
                </div>
                <div style="color: #333; font-size: 28px; margin-bottom: 20px;"><span
                        style="color: #3f51b5;">Score : </span>3
                </div>
                <div style="color: #333; font-size: 28px; margin-bottom: 20px;"><span
                        style="color: #3f51b5;">Goal : </span>3.7
                </div>

                <table style="width:100%; display: table; border-collapse: collapse;">
                    <thead style="background: #959595;">
                    <tr>
                        <th width="20%"
                            style="font-size: 24px; padding: 20px; color: #fff; font-weight: 600; border: 2px solid #fff">
                            Elements <br/>
                            (Description)
                        </th>
                        <th width="20%"
                            style="font-size: 24px;padding: 20px; color: #fff; font-weight: 600; border: 2px solid #fff">
                            Goal
                        </th>
                        <th width="20%"
                            style="font-size: 24px;padding: 20px; color: #fff; font-weight: 600; border: 2px solid #fff">
                            Score (the
                            attributed score)
                        </th>
                        <th width="40%"
                            style="font-size: 24px;padding: 20px; color: #fff; font-weight: 600; border: 2px solid #fff">
                            Comment
                        </th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr *ngFor="let i of [1,2,3,5,6]; let i = index;" style="background: #dfdfdf">
                        <td style="background: #959595; padding: 14px; font-size: 24px; color: #fff; font-weight: 600; text-align: center; border: 2px solid #fff">
                            Element {{i}}</td>
                        <td style="text-align: center; font-size: 24px; color: #333; font-weight: 500; border: 2px solid #fff">
                            4
                        </td>
                        <td style="text-align: center; font-size: 24px; color: #333; font-weight: 500; border: 2px solid #fff">
                            3
                        </td>
                        <td style="text-align: center; font-size: 24px; color: #333; font-weight: 500; border: 2px solid #fff">
                            element.Comment
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
`

here is my out put pdf 

![Screenshot from 2019-03-21 16-56-33](https://user-images.githubusercontent.com/43231377/54749466-a1cd3c00-4bfa-11e9-9a33-7f317eec3ba9.png)
![Screenshot from 2019-03-21 16-56-36](https://user-images.githubusercontent.com/43231377/54749471-a4c82c80-4bfa-11e9-9ebc-6b0608a4c84f.png)

how to resolve this issue?

**Comment by niklasvh** [comment]
html2canvas does not generate pdfs, your issue is with jspdf
