### ISSUE TITLE
Keeps recreating the elements and loads them again for the whole page

### ISSUE THREAD

**Issue by shaji-Dev** [niklasvh/html2canvas#1779]
Everytime I try this, even for small elements:

`html2canvas($("#localDiv")[0], {
                    logging: true,
                    useCORS: true,
                }).then(canvas => {
                });`

All the elements in the html gets duplicated on top of the current ones and reloads everything in the page, it doesn't refresh the page as if with F5, it just reloads the elements again, I get all the logs in the console for those elements being initialized again with the previous log still there. And it doesn't get to the result in then nor get an error.

Does anyone knows why this happens?

Thank you.

**Comment by linlif** [comment]
It happens to me too

**Comment by Eptech-Danish** [comment]
@shaji-Dev did you find the bug? please share solution. Thanks

**Comment by Eptech-Danish** [comment]
@linlif
