### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by kolo-ky** [niklasvh/html2canvas#1784]
hi!
When i do this:
html2canvas(document.querySelector('#picture'), {
        allowTaint: true,
        logging: false,
        taintTest: false,
      }).then((canvas) => {
        try {
          this.canvasPictureImg.src = canvas.toDataURL('image/png');
          this.print();
        } catch (e) {
          console.log(e);
        }
      });
I get an error in safari

SecurityError: The operation is insecure.

how to solve it? Converting the canvas that was already in the page - there are no such errors, but the converted html into the canvas by the library - causes an error

**Comment by scottblinch** [comment]
@niklasvh How did you solve this?

**Comment by peng666** [comment]
Hi, i have the same problem, how to resolve this problem？

**Comment by dragon-war** [comment]
We are facing the same problem, please suggest a workaround

**Comment by fiSCIENCES** [comment]
I have the same issue, Chrome and Edge (Chrome clone) are fine. Only Safari complained with this.
I have also tried to use only : useCORS:false, but facing the same problem.

window.getImage = function() {
        html2canvas(document.body,{allowTaint:true,useCORS:true}).then(function(canvas) {
            var convertedImage = canvas.toDataURL(); // !!! SecurityError !!!
        });
}

**Comment by hhhpw** [comment]
> I have the same issue, Chrome and Edge (Chrome clone) are fine. Only Safari complained with this.
> I have also tried to use only : useCORS:false, but facing the same problem.
> 
> window.getImage = function() {
> html2canvas(document.body,{allowTaint:true,useCORS:true}).then(function(canvas) {
> var convertedImage = canvas.toDataURL(); // !!! SecurityError !!!
> });
> }

brother,how to slove this issue. thank you

**Comment by BradleyVangelder** [comment]
did someone solved the problem, I have the same problem on safari and the mobile chrome app

**Comment by abdurrahmanyildirim** [comment]
I also having same issue. I have a solution but i dont know it is best way. You can use different width and height than icons has original width and height. When you use same width and height, html2canvas use it as image and it gives security error in safari.  
They tried solve this problem with `crossOrigin` attribute but it doesnt work anymore. you can understand what i mean when you check below code. When you use same width and height html2canvas return image and it gives error in safari

```
        CanvasRenderer.prototype.resizeImage = function (image, width, height) {
            var _a;
            if (image.width === width && image.height === height) {
                return image;
            }
            var ownerDocument = (_a = this.canvas.ownerDocument) !== null && _a !== void 0 ? _a : document;
            var canvas = ownerDocument.createElement('canvas');
            canvas.width = Math.max(1, width);
            canvas.height = Math.max(1, height);
            var ctx = canvas.getContext('2d');
            ctx.drawImage(image, 0, 0, image.width, image.height, 0, 0, width, height);
            return canvas;
        };
```

**Comment by montheryounis** [comment]
I have solved this issue finally with a help of @abdurrahmanyildirim code above. and what I did is I added `image.crossOrigin = 'Anonymous';` inside the if condition in **CanvasRenderer.prototype.resizeImage** function.

Also, just in case you are facing an issue with the same element in Firefox then go to **CanvasRenderer.prototype.renderBackgroundImage** function and change this condition if(image) to if (image && image.width > 0 && image.height > 0). 

Hope this helped...

**Comment by fiSCIENCES** [comment]
In my case the problem is still there even with @montheryounis suggested code fix.

window.getImage = function() {
html2canvas(document.body,{allowTaint:true,useCORS:true}).then(function(canvas) {
**var convertedImage = canvas.toDataURL(); // !!! SecurityError !!!**
});
}

**Comment by shangwenhe** [comment]
Version 17.4.1 (19618.1.15.11.14)
Execute `canvas.toDataURL('image/jpeg', 0.8)`
It still reports the error `the operation is insecure.`

**Comment by fiSCIENCES** [comment]
Hi,

Please add your issue to my new Issue on GitHub.
And give some more details.
This would help us.

Cordialement,
 <http://www.fisciences.com/>	
Martin Pineault
iConsultant (analyste/programmeur)
Développement f.i.SCIENCES inc.
m:	418-808-4839
w:	www.fisciences.com <http://www.fisciences.com/>
 <https://ca.linkedin.com/in/martinpineault>  <https://www.claris.com/partners/profile/company.10000007774/?lang=fr>

**Comment by jiuyi919** [comment]
I also encountered the same problem. How to solve it

**Comment by creationlogicom** [comment]
Here the solution: https://github.com/yorickshan/html2canvas-pro

They have taken the code to a new level without any issue.

**Comment by jiuyi919** [comment]
> 这里是解决方案：https://github.com/yorickshan/html2canvas-pro
> 
> 他们毫无问题地将代码提升到了一个新的水平。

I use https://github.com/yorickshan/html2canvas-pro report the same error

**Comment by fiSCIENCES** [comment]
Report to them the error you have.

Cordialement,
 <https://www.fisciences.com/>	
Martin Pineault
iConsultant (analyste/programmeur)
Développement f.i.SCIENCES inc.
m:	418-808-4839
w:	www.fisciences.com <https://www.fisciences.com/>
 <https://ca.linkedin.com/in/martinpineault>  <https://www.claris.com/partners/profile/company.10000007774/?lang=fr>

**Comment by pei625569** [comment]
`<img>` should add `crossOrgin='anonymous'`can solve the issue，such as： `<img crossOrgin='anonymous' src='xxx' />`。
