### ISSUE TITLE
npm loads 0.5.0betа2 sources when I install the 0.5.0betа3

### ISSUE THREAD

**Issue by vectorov** [niklasvh/html2canvas#1789]
Hello.
I want to use version 0.5.0beta3 of the html2canvas in my project. I want to load it by npm and I add version 0.5.0beta3 into dependencies. But npm install downloads version 0.5.0beta2. 
Is it possible to align artifacts for the 0.5.0beta3 ?

**Comment by niklasvh** [comment]
0.5.0 is ~4 years old and won't be getting any more updates.
