### ISSUE TITLE
use toDateURL lose some img

### ISSUE THREAD

**Issue by web-five** [niklasvh/html2canvas#1811]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by wenwu55** [comment]
当页面有多张图片，转化为base64格式时丢失了最后几张图片，前面的图片能够显示。

**Comment by zoubeihua** [comment]
怎么解决的呢？我也遇到同样的问题
