### ISSUE TITLE
the <img> tag wont render to final canvas object

### ISSUE THREAD

**Issue by captkamikaze** [niklasvh/html2canvas#1818]
I read the issue  #722 ( html2canvas does not render images located in the element) and 
i found out adding Insert **the option** allowTaint to view all images into a screenshot.

but for the script below, im not sure where i can insert "allowTaint: True" so that i can save the content directly to desktop.

document.getElementById("download").addEventListener("click", function() {

    html2canvas(document.querySelector('#boundary')).then(function(canvas) {

        console.log(canvas);
        saveAs(canvas.toDataURL(), 'file-name.png');
    });
});

thank you

**Comment by liyiche** [comment]
You can try like this.
``
html2canvas(document.querySelector('#boundary'),{allowTaint: True}).then(function(canvas) {

    console.log(canvas);
    saveAs(canvas.toDataURL(), 'file-name.png');
});

**Comment by liyiche** [comment]
You can try like this.

`html2canvas(document.querySelector('#boundary'),{allowTaint: True}).then(function(canvas) {

    console.log(canvas);
    saveAs(canvas.toDataURL(), 'file-name.png');
});`

**Comment by liyiche** [comment]
You can try like this.


`html2canvas(document.querySelector('#boundary'),{allowTaint: True}).then(function(canvas) {

console.log(canvas);
saveAs(canvas.toDataURL(), 'file-name.png');

});`

**Comment by liyiche** [comment]
You can try like this.
`
html2canvas(document.querySelector('#boundary'),{allowTaint: True}).then(function(canvas) {

console.log(canvas);
saveAs(canvas.toDataURL(), 'file-name.png');

});
`

**Comment by liyiche** [comment]
You can try like this.
``
html2canvas(document.querySelector('#boundary'),{allowTaint: True}).then(function(canvas) {

console.log(canvas);
saveAs(canvas.toDataURL(), 'file-name.png');

});
``

**Comment by captkamikaze** [comment]
thanks for the help, 
i added the ,{allowTaint: True} but seems like it does not work...

without the ,{allowTaint: True}) element, the code works fine, but some how when i added the allowtaint element, i does not initiate downloading...



document.getElementById("download").addEventListener("click", function() {

    html2canvas(document.getElementById("halfpage"),{allowTaint: true}).then(function(canvas){
        console.log(canvas);
        saveAs(canvas.toDataURL(), 'file-name.png');
    });  });


function saveAs(uri, filename) {

    var link = document.createElement('a');

    if (typeof link.download === 'string') {

        link.href = uri;
        link.download = filename;

        //Firefox requires the link to be in the body
        document.body.appendChild(link);

        //simulate click
        link.click();

        //remove the link when done
        document.body.removeChild(link);

    } else {

        window.open(uri);

    }
}

**Comment by captkamikaze** [comment]
thank you for the help,

i replaced the code above but it does not initiate the downloading...
without the {allowTaint: True} in the script, it works and the image downloads.

attaching my entire code:

document.getElementById("download").addEventListener("click", function() {

    html2canvas(document.querySelector('#halfpage')).then(function(canvas){
        console.log(canvas);
        saveAs(canvas.toDataURL(), 'file-name.png');
    });
});


function saveAs(uri, filename) {

    var link = document.createElement('a');

    if (typeof link.download === 'string') {

        link.href = uri;
        link.download = filename;

        //Firefox requires the link to be in the body
        document.body.appendChild(link);

        //simulate click
        link.click();

        //remove the link when done
        document.body.removeChild(link);

    } else {

        window.open(uri);

    }
}

**Comment by niklasvh** [comment]
You need to either use a proxy or send the images with cors headers if they do not reside under the same origin.

**Comment by mwaleed0517** [comment]
i am trying to use html2canvas for jsPDF but with allowTaint i get this error:
core.mjs:6495 ERROR Error: Uncaught (in promise): SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
