### ISSUE TITLE
Can it support the video tag and take  a screenshot?

### ISSUE THREAD

**Issue by switer** [niklasvh/html2canvas#182]
Can it support render video tag and take a screenshot ?

**Comment by GoogolHz** [comment]
I have not tried this out yet, but just found this reference to a javascript method to grab video frames to canvas. perhaps this method could be combined with html2canvas?  
http://www.kaizou.org/2012/09/frame-by-frame-video-effects-using-html5-and/

**Comment by mudcube** [comment]
Once a video is loaded, videos are handled the same as images in regards to drawing onto a canvas. 

Since HTML2Canvas creates a new frame to render all pages, you'd need to clone the video, wait for "oncanplaythrough" to be fired, transfer over the currentTime on the video, and then you could draw to the canvas.  You would want to look at imagecontainer.js and imageloader.js for reference in /src/

As far as rendering the actual controls of the video/audio (as per brcontainer's issue), they'd need to be manually drawn, which seems out of specs for this project.

**Comment by brig002** [comment]
+1 for adding this feature

**Comment by lu-zero** [comment]
+1 as well

**Comment by Paratron** [comment]
This would be great. The area of a video just appears as empty - even if a poster image has been provided.

**Comment by erorrov** [comment]
3 years later it's still not supported :(

**Comment by lu-zero** [comment]
Replacing a video with a canvas is documented now, just the code is quite a bit of pain and probably the browsers could provide better interfaces for it all over...

**Comment by Paratron** [comment]
There is no need to replace the video tag with a canvas. You can treat the video tag very much just like an img tag. The context2d method drawImage() supports video tags as a source just like an image tag. It will render the current frame of the video then. html2canvas would need to wait for the "[loadeddata](https://developer.mozilla.org/de/docs/Web/Events/loadeddata)" event which is fired when the first frame has been loaded. Thats much like the "load" event for images.

**Comment by tshanchuan** [comment]
let video = document.getElementsByTagName('video')[0];
        let canvas = document.getElementById('canvas');
        let ctx = canvas.getContext('2d');
        ctx.drawImage(video, 0, 0, 1280, 720);
        video.style.backgroundImage = "url("+canvas.toDataURL()+")";
        html2canvas(document.getElementById('video')).then(function(canvas) {
            document.body.appendChild(canvas);
        });

**Comment by Rahul-Sagore** [comment]
@tshanchuan in case of video, you don't even need html2canvas. You can use `canvas.toDataURL()` to set image src:
```js
var image = new Image();
image.src = canvas.toDataURL();
document.body.appendChild(image);
```

I am also having same issue. I have a 1 full page video tag. When I use html2canvas to  capture screen. It is getting empty screen. Is video tag still not supported?
I have usecase where there are other elements as well with video tag and I want to capture all using parent tag, but no luck.

**Comment by youngjuning** [comment]
can you support it?

**Comment by shrimpbighead** [comment]
canvas.toDataURL work well in pc,but it is not work in mobilephone

**Comment by ioprotium** [comment]
Hi everyone.
I had this problem two and as some of you pointed out, it can work using canvas. [Here](https://dev.to/protium/javascript-rendering-videos-with-html2canvas-3bk) a little explanation with some code.

**Comment by paperluigis** [comment]
`ctx.drawImage(ThatVideoTag, x, y, w, h)`
