### ISSUE TITLE
<base> element of document not respected.

### ISSUE THREAD

**Issue by burtonator** [niklasvh/html2canvas#1822]
I have an iframe which I'm building internally to represent external documents.

It has a <base> for all the elements inside it and the <img> is loaded with respect to that base but html2canvas doesn't support it.

It actually loads with the href of the parent.

This breaks images and loading external resources.

The solution is to respect the base element of course or allow us to specify a URL.

**Comment by leoj3n** [comment]
@niklasvh Can you give context on why not respect base and issue closed?
