### ISSUE TITLE
thumb of input type="range" not showing in html2canvas

### ISSUE THREAD

**Issue by nomanaamir** [niklasvh/html2canvas#1826]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by nomanaamir** [comment]
before download
![beforeExport](https://user-images.githubusercontent.com/31151920/56959151-ee932380-6b65-11e9-8a64-ee81596f6335.PNG)
after download through html2canvas
![afterExport](https://user-images.githubusercontent.com/31151920/56959166-01a5f380-6b66-11e9-9867-30b31b0358db.jpg)

I am using 1.0.0-alpha.12 version of html2canvas

**Comment by ollieyeahlong** [comment]
Hi was this fixed as I have come across the same error when using the latest version of html2canvas on Chrome.

**Comment by bveeni** [comment]
Hi,
I came through same issue for input type range with latest html2canvas.
Did anyone solved this?
Thanks
