### ISSUE TITLE
safari pseudo element content requires a space to show up

### ISSUE THREAD

**Issue by kevin074** [niklasvh/html2canvas#1827]
* html2canvas version: 1.0.0-rc.1
 * Browser & version: Safari Version 11.1.2 (13605.3.8) 
 * Operating system: MacOs High Sierra 10.13.6

Was gonna file a "can't render :before pesudo element in safari" ticket, but then when I was trying to find a way to consistently recreate for you guys, I found that if the content value has a space anywhere, then the pseudo element would be recognized by the code and rendered on the image.

please note the footer in the images below:

<img width="1000" alt="Screen Shot 2019-05-01 at 11 44 45 AM" src="https://user-images.githubusercontent.com/5018687/57035335-9a8c4b80-6c06-11e9-9099-8d684f67d1a0.png">

<img width="1000" alt="Screen Shot 2019-05-01 at 11 47 46 AM" src="https://user-images.githubusercontent.com/5018687/57035478-feaf0f80-6c06-11e9-8798-c42a1cb1aa6b.png">

this is the element on the footer I was changing.

```
.css-ubgfn1:before {
content: 'test with a space';
}
```

Please let me know if I can do a better job with documenting this bug.
I have also confirmed this with our own app with the version documented above (Just in case the version on the website is different).

For anyone who's might also use my "fix", we had to add in display:inline block to avoid the trailing/leading spaces to be rendered.

**Comment by niklasvh** [comment]
hey @kevin074, I am not sure I understand what the issue is. I can see the pseudo element content rendered on both images?

**Comment by kevin074** [comment]
Hi, so the pseudo :before element was added to the html in the footer of the website before the “created by” part of the footer. My screenshots are after html2canvas is done. You can see in the upper photo that the before element was added without a space and the rendered picture has no pseudo element. 

However in the picture below the pseudo element has a space and it’s shown in the rendered image. 

Note that this is a safari only bug.

**Comment by niklasvh** [comment]
@kevin074 Ah yes, I see it now. Thanks for the clarification, ill take a look at this
