### ISSUE TITLE
Uncaught Error: IndexSizeError: DOM Exception 1 

### ISSUE THREAD

**Issue by switer** [niklasvh/html2canvas#183]
`Uncaught Error: IndexSizeError: DOM Exception 1` 
 when it execute 
`ctx.drawImage(canvas, bounds.left, bounds.top, bounds.width, bounds.height, 0, 0, bounds.width, bounds.height);`  
while my code  want to html2canvas.render a `display:none` element;

What causes this error ? 

The error track :
`(anonymous function) html2canvas.js:2828
_html2canvas.Renderer html2canvas.js:2552
options.complete html2canvas.js:2667
start html2canvas.js:2082
img.onload`

**Comment by janainaemilia** [comment]
I get this error in Microsoft Edge. I noticed that I got this error because of the padding-left in the element that I was selecting to render.
