### ISSUE TITLE
CSSKeyframesRule cssText Permission Denied on Internet Explorer 11

### ISSUE THREAD

**Issue by Lemonilla** [niklasvh/html2canvas#1830]
# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

When running on Internet Explorer 11 the reduce anonymous function in Clone.js on line 235 throws an "Error: Member not Found" when processing a rule of type CSSKeyframesRule.  These have cssText of <Permission Denied> when output to the console.  This does not seem to effect Chrome as the cssText is not denied.

Screenshot of the error logs:
![html2canvas error text](https://user-images.githubusercontent.com/6193684/57458709-cc716380-723f-11e9-935c-7f080dc47038.png)

[html2canvas_with_extra_logging.txt](https://github.com/niklasvh/html2canvas/files/3162418/html2canvas_with_extra_logging.txt) is the doctored file that provides the logging shown in the screenshots.  This error also occurs without the edits. 

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.1
 * Browser & version: Internet Explorer 11 (11.706.17134.0)
 * Operating system: Windows 10
 * Angular version: 6.1.1
 * Packages: [package.txt](https://github.com/niklasvh/html2canvas/files/3162524/package.txt)

**Comment by niklasvh** [comment]
fixed with https://github.com/niklasvh/html2canvas/commit/bc270bb2116480a8ae08d3d9601f2b6118b44da3
