### ISSUE TITLE
Getting blank image with foreignObjectRendering and an error without it

### ISSUE THREAD

**Issue by shaji-Dev** [niklasvh/html2canvas#1834]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [+] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [+] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Using `foreignObjectRendering`:
`html2canvas($(this.$.mapcanvas)[0], {
            logging: true,
            useCORS: true,
            foreignObjectRendering: true,
            async: true,
        }).then(canvas => {
        });`

Reproduces this:
`Access to fetch at 'https://www.gstatic.com/charts/46.2/css/util/util.css' from origin 'https://staging-mmonline.firebaseapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

And gives a blank empty image.

Without `foreignObjectRendering`:
`html2canvas($(this.$.mapcanvas)[0], {
            logging: true,
            useCORS: true,
            foreignObjectRendering: true,
            async: true,
        }).then(canvas => {
        });`

Reproduces this:
All elements are redrawn and recreated on top of the current element kind of line loading an iFrame with all the current elements on top of the current page.

### Specifications:

 * html2canvas version tested with: Firebase Hosting and Polymer 
 * Browser & version: Google Chrome 74.0.3729.131 (Official Build) (64-bit)
 * Operating system: Windows 10

**Comment by niklasvh** [comment]
You need to serve your external resources with CORS headers if you have `useCORS`

**Comment by zmzimpl** [comment]
same problem,when i using` foreignObjectRendering: true`, it render all content unless background image, and render error when i set ` foreignObjectRendering: false`, some content will be missing

**Comment by rahul10198** [comment]
same problem facing

**Comment by rms-shinse** [comment]
same problem :( any updates?
