### ISSUE TITLE
Can't capture the contents of a iframe

### ISSUE THREAD

**Issue by tianxia0079** [niklasvh/html2canvas#1837]
html2canvas 1.0.0-rc.1 

`
 <div id="iframe_box" class="Hui-article">
        <div class="show_iframe">
            <div style="display:none" class="loading"></div>

            <iframe scrolling="yes" frameborder="0" data-html2canvas-ignore="true"
                    src="<c:out value="${sysContextPath}"></c:out>/loginLog/getList.do"></iframe>

        </div>
    </div>
`
thanks

**Comment by niklasvh** [comment]
With the information you've provided there is nothing we can triage
