### ISSUE TITLE
Linear-gradient not working if color stop percentage defined

### ISSUE THREAD

**Issue by gergof** [niklasvh/html2canvas#1838]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [X] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [X] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

If you set color stops using percentage/pixel/em, it will render only one of the colors.
[jsfiddle](http://jsfiddle.net/8nrkt9u4/)

If you set multiple color stops of the same color, it will render only two of them.
[jsfiddle](http://jsfiddle.net/8nrkt9u4/1/)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.1
 * Browser & version: Chromium 73.0.3683.75 (Developer Build) built on Debian 9.8
 * Operating system: Debian 9.8

**Comment by niklasvh** [comment]
this is fixed in https://github.com/niklasvh/html2canvas/pull/1828
