### ISSUE TITLE
Suspected IE regression in latest RC - "member not found error"

### ISSUE THREAD

**Issue by m-rutter** [niklasvh/html2canvas#1839]
In v1.0.0-alpha.11 an IE bug was reported as fixed in the changelog:

> Fix IE11 member not found error

In the latest RC, 1.0.0-rc.1, there appear to be a regression. Downgrading to v1.0.0-alpha.11 or v1.0.0-alpha.12 appears to fix the issue. I have not attempted trace which version the regression first occurs in.

**Comment by AleeAwan** [comment]
+1

**Comment by niklasvh** [comment]
Theres a fix pending in https://github.com/niklasvh/html2canvas/pull/1828
