### ISSUE TITLE
rotated text by CSS cannot be captured by html2canvas

### ISSUE THREAD

**Issue by xiangcao** [niklasvh/html2canvas#184]
I used css 
.heading1 {
   -moz-transform: rotate(270deg);
   -webkit-transform: rotate(270deg) ;
   -o-transform: rotate(270deg) ;
   -ms-transform: rotate(270deg) ;
   transform: rotate(270deg);
   filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=4);
}
to display a rotated headline for a chart. then i use html2cavas to 'screenshot' the page, this rotated text cannot be proper displayed.  It become a vertical text in which each letter is placed horizontally but aligned with each other vertically. and it looks ugly.

![1](https://f.cloud.github.com/assets/3782367/314447/5220b55e-97cb-11e2-8530-d9b5f67bf9ee.png)
![2](https://f.cloud.github.com/assets/3782367/314449/5a7ced6c-97cb-11e2-8e3d-8e1ca5657fd0.png)

**Comment by luck2011** [comment]
@MaitreyJukar wrap text content into a span does not work for me, sad

**Comment by checking12** [comment]
Does anyone find any solution for rotated divs screenshot?

**Comment by jjoe64** [comment]
workaround:
http://www.jjoe64.com/2015/10/html2canvas-and-css-transform-rotate.html

**Comment by brcontainer** [comment]
@jjoe64 https://github.com/niklasvh/html2canvas/issues/209#issuecomment-152904727

**Comment by amenadiel** [comment]
I'm displaying an infographic which contains images, charts and text. Since vertical text in the charts doesn't work, what I'm doing is using [canvg](https://github.com/gabelerner/canvg) to convert each of those charts (which are in [c3](http://c3js.org/) SVG) to a canvas, o even going one step further to convert said canvas to an image. This can be done recursively for any SVG group in the DOM.

**Comment by Drons2p** [comment]
How can i save div with CSS transform: perspective ?

**Comment by zk7035** [comment]
How i can save div with CSS -webkit-mask-box-image: url(http://kz-c2.qiniudn.com/a.svg); ?

**Comment by brcontainer** [comment]
@zk7035 As each CSS property needs to be manually built to be supported, there are a number of properties that are not yet supported. (https://github.com/niklasvh/html2canvas#browser-compatibility)

Details: https://github.com/niklasvh/html2canvas/issues/246

**Comment by joseiriarte1982** [comment]
Rotate worked form me but with a span I used one of the answers above. Here is what I did in my style I put a class

.vertical {
position: absolute;
left: -50px;
top: 0px;
width: 120px;
height: 20px;
font-size:12px;
color:#333;
transform: rotate(270deg);
}

the in my element a div position inline styled relative and whithin the div a span with class vertical.

`<div style="width:100%;float:left;text-align:left;height: 80px;margin-left:25px;border-left:1px solid #000;/*writing-mode: tb-rl;transform: rotate(-180deg);*/height: 100px;font-size:12px;position:relative;"><span class="vertical" style="top:20px;">Articulo No.</span></div>
`

Hope it helps someone, saludos

**Comment by samira-nrl** [comment]
hi,  I take a screenshot in chrome show, my style disordered but in firefox don't show them!! can help me?!

**Comment by hassaanhaider88** [comment]
i also face the problem of rotating the img
