### ISSUE TITLE
capture elements failed when html2canvas work in low chrome version

### ISSUE THREAD

**Issue by clannadmayongjun** [niklasvh/html2canvas#1843]
### Bug reports:
When I call a multi html2canvas function in the low chrome version, the returned canvas can sometimes be empty. code like the following:
```
var promise1 = html2canvas(dom1).then(function(canvas){
    document.body.appendChild(canvas);
})
var promise2 = html2canvas(dom2).then(function(canvas){
    document.body.appendChild(canvas);
})
var promise3 = html2canvas(dom3).then(function(canvas){
    document.body.appendChild(canvas);
})
Promise.all([promise1, promise2, promise3]).then(function(canvases){
    // the canvases's item can sometimes be empty
})
```

### Specifications:

 * html2canvas version tested with:1.0.0-rc.1
 * Browser & version: Chrome 47.0.2526.80
 * Operating system: Window 10

**Comment by hakimio** [comment]
Better question might be why do you expect a browser released in 2015 to be still supported in 2019.

**Comment by niklasvh** [comment]
There isn't really anything in this bug report that is actionable. If you have an example of something that can be replicated on jsfiddle, please make a new ticket with that, but I'll close this for now.
