### ISSUE TITLE
SVG capture status 

### ISSUE THREAD

**Issue by sdraper69** [niklasvh/html2canvas#1846]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)

- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

 * html2canvas version tested with:
 * Browser & version: Chome + Firefox latest
 * Operating system: Windows 10

Can confirm the status of using this library to capture inline SVG elements correctly?
Some open issues suggest it should work in the latest release, others suggest I need to use html2canvas.svg.js (if that's is true where is it?) and others say to use canvg or fabric.js first.

Can anybody confirm?  I currently get my svgs "squashed" when captured

original svg 
![image](https://user-images.githubusercontent.com/25779335/58125664-fdbb3d80-7c08-11e9-93c7-92186b495de6.png)

resultant from html2canvas
![image](https://user-images.githubusercontent.com/25779335/58125703-0f9ce080-7c09-11e9-8ecc-c53a03aea51b.png)

If using another library such as fabric or canvg is the answer, is there a reason why html2canvas doesn't implement whatever either of they are doing to make it an all in one solution?

**Comment by hakimio** [comment]
Does you SVG include dimensions (width and height) int its SVG tag like in the following example:
```svg
<svg version="1.1" width="57.6px" height="56.9px" viewBox="0 0 57.6 56.9"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" xml:space="preserve">
```
Can you post your SVG here?

**Comment by sdraper69** [comment]
Thanks for the response.  My svg does have a width and height, here's an example..

`<svg width="230px" height="204.19px" style="filter: drop-shadow(rgba(0, 0, 0, 0.4) 3px 3px 2px); fill: rgb(255, 255, 255); stroke: rgb(0, 0, 0); stroke-width: 9px; stroke-dasharray: 0; opacity: 1;"><path d="M0 15 A15 15 0 0 1 15 0L185 0A15 15 0 0 1 200 15L200 159.2188A15 15 0 0 1 185 174.2188L15 174.2188A15 15 0 0 1 0 159.2188L0 15" style="fill: rgb(255, 255, 255); stroke: rgb(0, 0, 0); stroke-dasharray: 0; opacity: 1;"></path></svg>`


From your response, I take it you would expect SVGs to work ok? It would be great if you spot I'm doing something wrong!

**Comment by hakimio** [comment]
It seems the problem is with the SVG not with html2canvas:
http://jsfiddle.net/z46q0omx/

**Comment by hakimio** [comment]
Following is the fixed version of your SVG which renders just fine:
```svg
<svg width="230px" height="204.19px" fill="rgb(255, 255, 255)" filter="drop-shadow(rgba(0, 0, 0, 0.4) 3px 3px 2px)" stroke="rgb(0, 0, 0)" stroke-dasharray="0" stroke-width="9px" version="1.1" viewBox="0 0 230 204.19" xmlns="http://www.w3.org/2000/svg"><path d="m16 31a15 15 0 0 1 15 -15h170a15 15 0 0 1 15 15v144.22a15 15 0 0 1 -15 15h-170a15 15 0 0 1 -15 -15v-144.22" fill="#fff" stroke="#000" stroke-dasharray="none"/></svg>
```

**Comment by sdraper69** [comment]
@hakimio  thanks so much for your assistance, it got me somewhere.  I could get the previous example  I gave you working but it was a cut down/simplified version of my real svgs and when implementing with my correct svgs I realised where my main problem has always been, html2canvas doesn't seem to like SVGs with a style "overflow: visible"

I have knocked up a quick fiddle which hopefully explains:
http://jsfiddle.net/5p38o1xh/

don't suppose you(or anyone) has any thoughts on this?

**Comment by niklasvh** [comment]
@sdraper69 your example is rendering what it is supposed to. You are targeting the #target element, which has a certain dimension and x, y coordinate, as you can see my inspecting your DOM:

![image](https://user-images.githubusercontent.com/551347/58610560-b2380d80-8260-11e9-92d7-02e162b2ca9d.png)

The rendered image matches the highlighted portion.

**Comment by sdraper69** [comment]
I appreciate your feedback, however I'm not sure this is closed as if target the body, or a larger parent container you get the same results...

http://jsfiddle.net/0zse2u6j/
