### ISSUE TITLE
Element with style 'overflow: hidden auto' will fail rendering

### ISSUE THREAD

**Issue by daniel-hauser** [niklasvh/html2canvas#1850]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Trying to export an element with style `overflow: hidden auto`

**v1.0.0-rc.0:** works as expected [see here](https://jsfiddle.net/ddhauser/2uzm3afs/).
**v1.0.0-rc.1:** will fail with `Error parsing CSS component value, multiple values found when expecting only one` [see here](https://jsfiddle.net/ddhauser/d2y9u73b/).

### Specifications:

 * html2canvas version tested with:
   * Browser & version: Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)
   * Operating system: MacOS Mojave 10.14.5

**Comment by niklasvh** [comment]
Thanks for providing everything necessary to replicate the issue, I have a fix in #1851
