### ISSUE TITLE
Unable to specify options with html2canvas in TypeScript after recent release

### ISSUE THREAD

**Issue by rathodsanjay** [niklasvh/html2canvas#1854]
I am using html2canvas in an Angular application based on TypeScript. I am unable to specify options with html2canvas since recent release. It expects some `id` property in the options provided.

Following is my code:
```
var options = { logging: false };
html2canvas(element, options);
```

**Error:**
`Property 'id' is missing in type '{ logging: false }' but required in type 'CloneOptions'`

### Specifications:

 * html2canvas version tested with: **v1.0.0-rc.2**
 * Browser & version: Google Chrome v70.0.3538.77
 * Operating system: Windows 10

**Comment by hakimio** [comment]
As a workaround you can cast to any:
```ts
await html2canvas(htmlEl, <any>{
    windowWidth: htmlEl.clientWidth,
    windowHeight: htmlEl.clientHeight,
    scale: 2,
    logging: false
});
```

**Comment by rathodsanjay** [comment]
@hakimio thanks, but for time being, I just downgraded the version in my package.json to use rc.1 and the builds are passing!

**Comment by val1984** [comment]
My workaround for the time being is to cast my options as `Options`:
```typescript
const opts: Partial<Options> = {
  logging: false,
};
html2canvas(body, opts as Options);
```

**Comment by ovidioreyna** [comment]
Can confirm that Angular 7 build is failing with 1.0.0-rc.2. Just resolved this issue for our team. 1.0.0-rc.1 worked for us, but we're playing it safe and went back to our initial version of 1.0.0-alpha.12.

Error we received seems to have to do with `options`.

Error produced:
```
Argument of type '{ windowWidth: number; }' is not assignable to parameter of type 'Options'.
  Property 'id' is missing in type '{ windowWidth: number; }' but required in type 'CloneOptions'.
```

Code for html2canvas is as follows:
```
html2canvas(data, {windowWidth: 1500}).then()
```
