### ISSUE TITLE
Issue with TypeScript type definitions

### ISSUE THREAD

**Issue by hakimio** [niklasvh/html2canvas#1855]
Pretty much all CloneOptions, RenderOptions and Options interface properties should be **optional** or at least when declaring Options type you should use "|" instead of "&"
```ts
export declare type Options = CloneOptions | RenderOptions | {
    allowTaint: boolean;
    backgroundColor: string;
    foreignObjectRendering: boolean;
    imageTimeout: number;
    logging: boolean;
    proxy?: string;
    removeContainer?: boolean;
    useCORS: boolean;
};
```

**Comment by val1984** [comment]
`html2canvas` should definitely accept `Partial<Options>` as its second argument.

**Comment by ovidioreyna** [comment]
Can confirm that Angular 7 build is failing with 1.0.0-rc.2. Just resolved this issue for our team. 1.0.0-rc.1 worked for us, but we're playing it safe and went back to our initial version of 1.0.0-alpha.12.

Error we received seems to have to do with `options`.

Error produced:
```
Argument of type '{ windowWidth: number; }' is not assignable to parameter of type 'Options'.
  Property 'id' is missing in type '{ windowWidth: number; }' but required in type 'CloneOptions'.
```

Code for html2canvas is as follows:
```
html2canvas(data, {windowWidth: 1500}).then()
```
