### ISSUE TITLE
html2canvas@1.0.0-rc.2 makes Angular project build failed,html2canvas@1.0.0-rc.1 is ok.

### ISSUE THREAD

**Issue by 10222927** [niklasvh/html2canvas#1857]
npm install html2canvas@1.0.0-rc.2 sucessfull ,than call 'ng build'.
In the end, it failed.
I guess it because of html2canvas@1.0.0-rc.2,maybe .

Summary log:
Node#moveTo was deprecated. Use Container#append.
[0mDate: [1m[37m2019-05-29T07:47:36.387Z[39m[22m[0m
[0mHash: [1m[37m3fa4b589eb9668899fde[39m[22m[0m
[0mTime: [1m[37m73413[39m[22mms[0m
[0mchunk {[1m[33mscripts[39m[22m} [1m[32mscripts.78f0bdbed29811d920e0.bundle.js[39m[22m (scripts) 2.06 MB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33m0[39m[22m} [1m[32mstyles.8855f6bd28d07ac6a4de.bundle.css[39m[22m (styles) 485 kB [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33m1[39m[22m} [1m[32mpolyfills.3bc34265385d52184eab.bundle.js[39m[22m (polyfills) 86 bytes [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33m2[39m[22m} [1m[32mmain.e402deade8b026b7d50e.bundle.js[39m[22m (main) 84 bytes [1m[33m[initial][39m[22m[1m[32m [rendered][39m[22m[0m
[0mchunk {[1m[33m3[39m[22m} [1m[32minline.5bdc54bbc6535e2d60f2.bundle.js[39m[22m (inline) 1.45 kB [1m[33m[entry][39m[22m[1m[32m [rendered][39m[22m[0m
[0m[0m
[0m[1m[31mERROR in node_modules/html2canvas/dist/types/css/index.d.ts(43,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(45,22): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(46,23): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(47,25): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(48,23): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(49,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(54,26): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(55,27): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(56,30): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(57,29): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(58,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(59,23): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(60,24): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(61,22): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(62,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(63,23): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(64,24): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(65,22): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(66,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(68,14): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(69,12): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(70,17): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(72,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(73,18): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(74,17): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(75,20): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(76,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(78,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(79,24): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(80,20): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(85,14): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(88,19): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(93,15): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(94,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(96,25): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(97,17): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(98,20): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(99,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(100,22): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(101,17): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(102,16): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(103,13): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(114,14): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(115,13): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(119,23): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m
[0m[1m[31mnode_modules/html2canvas/dist/types/css/index.d.ts(120,19): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m

### Specifications:

 * html2canvas version tested with:
 * Browser & version:1.0.0-rc.2
 * Operating system:Linux

**Comment by danielquijada** [comment]
Yes, had the same problem today.

rc.2 fails but rc.1 works perfectly

**Comment by rqton** [comment]
Hello, had same problem with alpha-13, trying to ugrade in rc.1 same error.
If it's working for you guys in rc.1, it's certainly because of your dependency caching.

**Comment by danielquijada** [comment]
Are you 100% sure about that? I forced rc.1 on the package.json `    "html2canvas": "1.0.0-rc.1"`, and made a clean install (deleted **node_modules** and **package-lock** and then `npm install`) and it works.. Also just checked on my **node_modules** and I indeed have rc.1 instaled...

If you have the same problem and are absolutely sure you have that version then the error might be trickier to catch, but it's most likely not about dependency caching

**Comment by rqton** [comment]
I never used rc.1 before and i got the same error after updating to this version. If it's not depency caching it's something else, but idk what ^^

**Comment by hakimio** [comment]
It is an issue with RC2 and RC1 does not have the issue. @rqton you must be installing using caret (^) prefix, not exact version.
Related issues:
https://github.com/niklasvh/html2canvas/issues/1854
https://github.com/niklasvh/html2canvas/issues/1855

**Comment by rqton** [comment]
![image](https://user-images.githubusercontent.com/11751889/58548443-9f461e80-8209-11e9-8cbe-e3a62ddabf60.png)

Not working for my on rc-1 at all.
Anyway, if we can fix it on rc-2, it's fine for me :)

**Comment by ss7758258** [comment]
提示window is not defined

**Comment by hakimio** [comment]
@rqton As I have told you already: you are still using RC2, because you are installing using caret (^) version prefix not EXACT version.

**Comment by rqton** [comment]
You're right i read your post to fast, my bad, thanks again @hakimio

**Comment by val1984** [comment]
Seems that you're using an old version of Typescript. ReturnType<T> was introduced in [`typescript@2.8`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html).
You should upgrade.

**Comment by manishmkr45** [comment]
Getting Error - ERROR in node_modules/html2canvas/dist/types/css/index.d.ts(43,21): error TS2304: Cannot find name 'ReturnType'.[39m[22m[0m.
i am using hml2pdf and that is using html2canvas as dependencies .

**Comment by ovidioreyna** [comment]
Can confirm that Angular 7 build is failing with 1.0.0-rc.2. Just resolved this issue for our team. 1.0.0-rc.1 worked for us, but we're playing it safe and went back to our initial version of 1.0.0-alpha.12.

Error we received seems to have to do with `options`.

Error produced:
```
Argument of type '{ windowWidth: number; }' is not assignable to parameter of type 'Options'.
  Property 'id' is missing in type '{ windowWidth: number; }' but required in type 'CloneOptions'.
```

Code for html2canvas is as follows:
```
html2canvas(data, {windowWidth: 1500}).then()
```

**Comment by val1984** [comment]
@ovidioreyna You're having a different issue which was caused by html2canvas parameters typing.
Since you're using Angular 7 which pulls `typescript@3.1`, you don't have the same issue as @10222927, issue which stems from `ReturnType<T>` having being introduced in `typescript@2.8` and not being available when using an older version of Angular.

**Comment by niklasvh** [comment]
+1 to what @val1984 

Currently don't have any plans on starting to support older typescript type definitions.

**Comment by deepaks4** [comment]
Facing same problem and rc.1 , rc.2 both are not working for me

**Comment by MithunDk** [comment]
@val1984  .. Installed latest html2canvas rc.5 version . Got the same node_modules/html2canvas/dist/types/css/index.d.ts(120,19): error TS2304: Cannot find name 'ReturnType' error.   
And installed rc.1 version as discussed in above comments ,issue gets resolved but which is causing issues to Existing Observable functionalities(property map doesnt exist in observable) (using angular 5) .Also using typescript 3.6.4 latest.

**Comment by pabloubal** [comment]
Same issue here. Tried rc5 with @types/html2canvas": "0.0.35" and rc1 with @types/html2canvas":"0.0.33", both with the same result

**Comment by metinsevindik** [comment]
Have a solution ?
I taking same error as using 1.0.0-rc.1
I tried to using 1.0.0-rc.7 but error continue

**Comment by val1984** [comment]
@metinsevindik See my reply from last year:
> Seems that you're using an old version of Typescript. `ReturnType<T>` was introduced in [`typescript@2.8`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html).
> You should upgrade.
