### ISSUE TITLE
Uncaught (in promise) RangeError: Maximum call stack size exceeded - 1.0.0-rc.2 

### ISSUE THREAD

**Issue by pupunzi** [niklasvh/html2canvas#1858]
- Using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- Testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Updating to the latest 1.0.0-rc.2 version, DOM elements with a base64 background-image generate a blocking error (the previous 1.0.0-rc.1 didn't) :
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Tokenizer.write (html2canvas.js:1019)
    at parse (html2canvas.js:4105)
    at new CSSParsedDeclaration (html2canvas.js:3998)
    at new ElementContainer (html2canvas.js:4138)
    at createContainer (html2canvas.js:4485)
    at parseNodeTree (html2canvas.js:4438)
    at parseTree (html2canvas.js:4490)
    at html2canvas.js:6937
    at step (html2canvas.js:83)
    at Object.next (html2canvas.js:64)
```

You can test yourself the issue here: 
https://open-lab.com/storyboarder/test/test.html

At this page, you can also see that the image has an "object-fit: cover" CSS property that is ignored and that if you scroll the page the capture of the image is white.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.2
 * Browser & version: Chrome 74.0.3729.169
 * Operating system: Mac OSX 10.14.5

**Comment by pupunzi** [comment]
@niklasvh : Thank you for the fast support!

**Comment by marshallino16** [comment]
Still happening on mobile devices

**Comment by JerryLMJ** [comment]
@marshallino16 Have you solved the problem yet？

**Comment by marshallino16** [comment]
My workaround was to stop using the image as a background-image of my div and use it in an **img** tag. 

To get rid of the `object-fit` CSS property I used two classes : one **portrait** and one **landscape** to alternate width or height to 100%. 

ex : 

```
.background-image.portrait {
            height: auto;
            width: 100%;
        }
```

**Comment by z1haze** [comment]
Can we get a fix for this on safari?

**Comment by fabiankoebel** [comment]
for me the issue is resolved by reducing the SLICE_STACK_SIZE from 60000 to 30000 (see https://github.com/niklasvh/html2canvas/blob/master/src/css/syntax/tokenizer.ts#L660).
Maybe @niklasvh could add some technical background regarding SLICE_STACK_SIZE.
