### ISSUE TITLE
'backgroundColor' name collision in Options & CloneOptions intersection

### ISSUE THREAD

**Issue by gregwm** [niklasvh/html2canvas#1866]
### Bug reports:

Cannot provide `backgroundColor: string` as an option as type `Options` is an intersection type with `CloneOptions` which also contains a var `backgroundColor: number | null`.

### Fix:

Change intersection to union type. Or make it clear to get around this do the following:

`const opts: any = {
      backgroundColor
    };`
    `html2canvas(element, opts as Options).then((canvas) => {
      ...
    });`

**Comment by niklasvh** [comment]
This should be fixed, let me know if you are still running into this issue.
