### ISSUE TITLE
render empty while created canvas node not in visible area

### ISSUE THREAD

**Issue by ooyuanoo** [niklasvh/html2canvas#1872]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Render empty while DOM node not in visible area. While render canvas list full page,  u scroll result page to the bottom and wait a minute, scroll page to the top, u can see page render emtpy canvas.
[jsfiddle](https://jsfiddle.net/0b84cj3L/).

### Specifications:

 * html2canvas version tested with:  1.0.0-rc.3
 * Browser & version: chrome
 * Operating system: windows

**Comment by hakimio** [comment]
Seems to be an issue introduced in RC2. RC1 doesn't seem to be effected by this issue.
