### ISSUE TITLE
[Bug] Logging option ignored in 1.0.0-rc.3 version

### ISSUE THREAD

**Issue by jmesa-sistel** [niklasvh/html2canvas#1874]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Logging option ignored in 1.0.0-rc.3 version

```
     html2canvas(iframeHtml, { logging: false }).then(
                (canvas) => {
                   .....
                }
            );
```
I can see a lot of debug info in console

### Specifications:

 * html2canvas version tested with: angular webapp
 * Browser & version: Chrome 
 * Operating system: Windows 10

**Comment by jpateusa** [comment]
I am also experiencing this.

**Comment by Maushundb** [comment]
It looks like all the options I tried (logging, backgroundColor, and canvas) are all ignored in rc3.

**Comment by jmesa-sistel** [comment]
@niklasvh Can you take a look?
I can try to do a pull request if you are too busy.

**Comment by IanVS** [comment]
It looks like logging does work in firefox and safari, but I don't see any logs in chrome.

**Comment by SupJoeeeeeey** [comment]
Downgrading to rc1 could get rid of these logs unless you have any requirement for new features inside rc3. (rc2 has issues on `option` parameter)
