### ISSUE TITLE
Issue rendering Font Awesome 5 in Chrome

### ISSUE THREAD

**Issue by LillaLillian** [niklasvh/html2canvas#1881]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I have an issue with rendering of font awesome 5 icons, they will only show up as squares. I'm using Google Chrome and Font Awesome 5 Pro. 
![2019-06-11 14_59_28-Performance Report Post TG 2](https://user-images.githubusercontent.com/32553357/59273944-93227e00-8c59-11e9-8320-24a0dd69a7ec.png)
![2019-06-11 14_59_41-Performance Report Post TG 2](https://user-images.githubusercontent.com/32553357/59273951-961d6e80-8c59-11e9-889e-54020c65ce92.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.3
 * Browser & version: Google Chrome 75.0.3770.80
 * Operating system: Windows 10

**Comment by ngspinu** [comment]
Same issue here. Any updates on this one? Thank you

**Comment by queejie** [comment]
Same issue.

**Comment by dheerajkumarmadaan** [comment]
Exactly the same issue. Any updates so far? Thanks.

**Comment by grahamkane** [comment]
I did some digging around and think this is down to the number within the CSS font family value (e.g. "Font Awesome 5 Free"). This causes an issue in the canvas renderer, since it uses the short-hand CSS syntax for setting the canvas context font.

Wrapping the font names in quotes fixed the issue for me. Submitted a PR for it.

**Comment by ghafooridev** [comment]
hey, I have the same issue, I tried many solutions that exist in Github reported the issue but it still the same. any practical solution?

**Comment by hedi-edelbloute** [comment]
@ghafooridev use [this](https://github.com/niklasvh/html2canvas/pull/1948) PR (thank you @grahamkane)

**Comment by aaroncrawford** [comment]
For those having issues with this, also try to remove the spaces from your all.min.css file in Font awesome.  Your classnames should be this, for example `FontAwesome5Pro`, `FontAwesome5Brands`, etc.

My class names were in quotes and still not working, but after changing them to be without space my icons started rendering in html2canvas.

**Comment by Chandand76** [comment]
same issue for me? 
using  html2canvas 1.0.0-rc.5  version.
