### ISSUE TITLE
Individual borders not working for child elements 

### ISSUE THREAD

**Issue by kmayur35** [niklasvh/html2canvas#1883]
.parent {
        position: absolute;
        display: flex;
    }

    .child{
        flex: 1;
        border-left: 1px solid black; // does not work after converting
        // border: 1px solid black; // this works

        .grandchild {
            position: relative;
            width: 100%;
            border-bottom: 1px solid black; // again this does not work
            // border :  1px solid black; // this works
        }
}

same issue with table element, td and th
checked with version 1.0.0-rc.3 and version ^1.0.0-alpha.12

it was working before but suddenly stopped, can't figure out why?

**Comment by Hennadiy** [comment]
I have faced the same issue. 
Any updates?

**Comment by kmayur35** [comment]
> I have faced the same issue.
> Any updates?

Yes!

replace 

.className {
    border-left: 1px solid black;
    border-bottom: 1px solid black;
}

with

.className {
    border-style: solid;
    border-width:  0px 0px 1px 1px;
    border-color: black;
}

you can pass top, right, bottom, left in border-style and border-color too.

**Comment by hh29077106** [comment]
> > I have faced the same issue.
> > Any updates?
> 
> Yes!
> 
> replace
> 
> .className {
> border-left: 1px solid black;
> border-bottom: 1px solid black;
> }
> 
> with
> 
> .className {
> border-style: solid;
> border-width: 0px 0px 1px 1px;
> border-color: black;
> }
> 
> you can pass top, right, bottom, left in border-style and border-color too.

this works for me and thanks a lot

**Comment by iceash** [comment]
Ah! It works!!!!!
It has bothered me for 2 days!!
thanks a lot!!!!
