### ISSUE TITLE
IE11 Not responding and/or long running script

### ISSUE THREAD

**Issue by snimmagadda1** [niklasvh/html2canvas#1889]
### Bug reports:

This works great in Firefox and Chrome; however, in internet explorer 11 the process takes a very long time and results in the browser reporting not responding. If the user waits enough (anywhere from 30s-2 minutes) the process resolves. 

I am trying to capture a PNG of a portion of the DOM using html2canvas and afterwards convert the PNG to PDF via jsPDF. Essentially I have elements with IDs that correspond to a page. I capture the page in a PNG, then expand the PNG to a full page in the PDF conversion step by adding each PNG as a page to the PDF. My code for doing so is shown below:

```
            // Default to GMSRD1
            var fileName = "record-of-discussion-form.pdf";
            var pages = ["GMSRD1_page1", "GMSRD1_page2", "GMSRD1_page3", "GMSRD1_page4"]

            if (this.state.parsed.formId === "GMSC1") {
                fileName = "consultee-form.pdf"
                pages = ["GMSC1_page1", "GMSC1_page2", "GMSC1_page3"];
            }
            if (this.state.parsed.formId === "GMSA1") {
                fileName = "assent-form.pdf"
                pages = ["GMSA1_page1", "GMSA1_page2"];
            }
            if (this.state.parsed.formId === "GMSW2" ) {
                fileName = "withdraw-form.pdf"
                pages = ["GMSW2_page1", "GMSW2_page2", "GMSW2_page3"];
            }

            // Objct to build 
            var pdf = new jsPDF({
                orientation: "p",
                unit: "pt",
                format: "a4",
                compression: true
            });

            // Canvas creation promises
            let promises = [];

            // Capture canvas for each page 
            pages.forEach(page => {
                let element = document.getElementById(page);
                promises.push(this.getCanvasData(element));
            });

            Promise.all(promises).then(dataUrls => {
                dataUrls.forEach((dataUrl, i) => {
                    pdf.addImage(dataUrl, "PNG", 45, 40, 800 * .63, 980 * .7, undefined, "FAST");

                    pdf.addPage();
                });

                let testOutput = pdf.output('arraybuffer'); // arraybuffer 
                var uint8Array = new Uint8Array(testOutput);
                var array = Array.from(uint8Array)

                // <DO something w/ data below>
```
Has anyone seen this behavior or have any workarounds? Wondering if there is there a way to release the current state of the process to the browser via timeouts to avoid this behavior?
### Specifications:

 * html2canvas version tested with: v1.0.0-rc.3
 * Browser & version:  IE11
 * Operating system: Windows 10

**Comment by Cplacke** [comment]
Also have been seeing this issue, any progress?

**Comment by ravi6565** [comment]
I am seeing the same issue in IE11, it works perfectly in Chrome and Firefox(No Hung/ Long running script error). Could anyone please share the conclusion on the above issue discussion?

Converting Graph component(12+ graph views) -> Canvas(Canvg) -> html2canvas(In my investigation I found script is blocking/freezes the UI for 30+ seconds) -> JSPDF.
