### ISSUE TITLE
html2canvas why not support ssr ，nuxt?

### ISSUE THREAD

**Issue by angleneo** [niklasvh/html2canvas#1901]
rt
![image](https://user-images.githubusercontent.com/20380882/59912520-c8dd1900-9448-11e9-8683-1c03bbd19ace.png)
![image](https://user-images.githubusercontent.com/20380882/59912573-e14d3380-9448-11e9-9fe1-26929cdf3f2e.png)

**Comment by hakimio** [comment]
It states clearly in the README `as it is heavily dependent on the browser, this library is not suitable to be used in nodejs`. If you need server-side PDF rendering, use Puppeteer.

**Comment by wee911** [comment]
> rt
> ![image](https://user-images.githubusercontent.com/20380882/59912520-c8dd1900-9448-11e9-8683-1c03bbd19ace.png)
> ![image](https://user-images.githubusercontent.com/20380882/59912573-e14d3380-9448-11e9-9fe1-26929cdf3f2e.png)

```
let html2canvas = null
if (process.browser) {
  html2canvas = require('html2canvas')
}
```
it helps.
