### ISSUE TITLE
Incorrect canvas size

### ISSUE THREAD

**Issue by MikeKotte** [niklasvh/html2canvas#1904]
# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

The canvas that gets outputted from the html2canvas method is exactly twice as large in size. I've tried giving the actual width and height of the element as options but this gives me the same result. 

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.3
 * Browser & version: latest non-beta releases of Chrome and Safari
 * Operating system: macOs Mojave 10.14.5

**Comment by IanVS** [comment]
If you're on a macbook with a retina screen, the `scale` will be set to `2`, as explained in https://html2canvas.hertzen.com/configuration.

**Comment by MikeKotte** [comment]
This was indeed the issue. Solved it just before going on vacation and I just got back so my apologies for the late answer.

Fixed it by using:
```
 html2canvas([the element], {
        scale: 1
      })
```

Still, thank you for the answer!
