### ISSUE TITLE
html2canvas not working [multiple images on same div]

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [niklasvh/html2canvas#1905]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

```html
<div id="scream">
  <img id="corps" class="corps" src="asset1.png"/>
  <img id="visage" class="visage" src="asset2.png"/>
  <img id="yeux" class="yeux" src="asset3.png"/>
</div>
```
when i select the div which includes multiple images:  not working
```jsx
// div select which include multiple images 
html2canvas(document.querySelector("#scream")).then(canvas => {
          document.body.appendChild(canvas)
      });
// result: dont work
// Starting DOM parsing
// Added image asset1
// Added image asset2
// Added image asset3
// Added image
// Starting renderer 
// Canvas renderer initialized (485x0 at 1542.9375,-13) with scale 0.5
// Finished rendering
 
// Nothing displayed 
```
when i select one image from the div:  working
```jsx
// single image select
html2canvas(document.querySelector("#corps")).then(canvas => {
          document.body.appendChild(canvas)
      });
// result: works
// image loaded successfully
 ```

***jsfiddle:*** [https://jsfiddle.net/tfr59Ls1/](https://jsfiddle.net/tfr59Ls1/)

### Specifications:

* vuejs : ^2.6.10,
 * html2canvas version tested with: 1.0.0-rc.3
 * Browser & version: chromium v73
 * Operating system: Elementary Juno

**Comment by hakimio** [comment]
Can you create jsfiddle showing the issue?

**Comment by mIcHyAmRaNe** [comment]
updated

**Comment by hakimio** [comment]
The images are just getting blocked by CORS. Set "useCORS: true" and see the errors in the console. Also, your fiddle has a bug which prevents "capture" button from working.

**Comment by mIcHyAmRaNe** [comment]
in my localhost project (http://localhost/cabine) , i had the images in an assets folder that i can access using `http://localhost/cabine/assets/../asset1.png`... so i think in this case no need useCORS (same domain) 

for the second point: in jsfiddle, the button works when console.log('something') ... but not when html2canvas code :/ 

but in [my localhost project](https://github.com/mIcHyAmRaNe/cabine/tree/htmltocanvas), the [capture](https://github.com/mIcHyAmRaNe/cabine/blob/htmltocanvas/src/components/mainLay.vue#L579) function works well when i edit `document.querySelector("#scream")` to `document.querySelector("#corps")`  where `#scream` is the id of the [div](https://github.com/mIcHyAmRaNe/cabine/blob/htmltocanvas/src/components/mainLay.vue#L492) which have lot of img 
and `corps` is the id of [one img](https://github.com/mIcHyAmRaNe/cabine/blob/htmltocanvas/src/components/mainLay.vue#L495) from div imgs

**Comment by hakimio** [comment]
Put base64 encoded images in the fiddle.

**Comment by mIcHyAmRaNe** [comment]
something like this [https://jsfiddle.net/wzfmb8xp](https://jsfiddle.net/wzfmb8xp) ?
if so, it didn't change anything, 
& i tried useCORS then allowTaint but nothing

**Comment by hakimio** [comment]
It says "error loading image". Have you tried to use jpegs or pngs instead of webp?

**Comment by mIcHyAmRaNe** [comment]
it says `error loading image` for not selected elements 
& yeah, i tried pngs but same thing

**Comment by hakimio** [comment]
Maybe just don't include the image tag in DOM if source is unresolvable?

**Comment by hakimio** [comment]
@mIcHyAmRaNe 
RC3 seems to be broken, but RC1 works as intended:
https://jsfiddle.net/qf4ru85g/1/

**Comment by mIcHyAmRaNe** [comment]
@hakimio thank you bro :)

**Comment by andreasvirkus** [comment]
@mIcHyAmRaNe did you get it working? I'm also having trouble in a Vue app when the image's source is bound via `v-bind:src="dynamicImage"`
