### ISSUE TITLE
Image blob isn't captured

### ISSUE THREAD

**Issue by bookluvr416** [niklasvh/html2canvas#1908]
- [ X ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ X ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

I'm upgrading a project from a very old version (0.4) to the current version, and now have issues with html2canvas converting a CORS image. The canvas size is correct, but the canvas itself is blank.

The image source is a blob, such as 

`<img src="blob:C480B50A-0F8B-43B2-BC54-042C8248A53D" />`

The below code works in codepen with a standard image url source, but doesn't work in my project with the blob source. I'm not sure how to provide an example since the URL the blob is returned from is only available on an intranet.

```
html2canvas($(htmlDiv).get(0), {
            allowTaint: true,
            taintTest: false,
            useCORS: true,
            scale: 1
        }).then(function(canvas) {

            console.log("html2canvas conversion :: " + htmlDiv + " converted successfully");

            
            $('#html-wrapper').append(canvas);
        });
```

There are no issues in the console.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc2 and 1.0.0-rc3
 * Browser & version: IE 11

**Comment by wufeng87** [comment]
I got the same problem with img src like this: `blob:http://47.96.87.25:48080/2e59d299-956e-4001-81e8-080540fd0f17`
