### ISSUE TITLE
Rendering transparency with settings backgroundColor: null is not working in rc.3

### ISSUE THREAD

**Issue by fakob** [niklasvh/html2canvas#1910]
In my [electron desktop application](https://movieprint.fakob.com/) I am using the html2canvas npm package.

After updating from `v1.0.0-rc.2` to `v1.0.0-rc.3` the transparency rendering with settings `backgroundColor: null` did not work anymore.

Looking at the logs I saw that get the following warning:
`[Violation] Avoid using document.write(). html2canvas.js:5043`
Not sure if this is related as in `v1.0.0-rc.2` rendering transparency worked fine. Despite the warning.

The warning about document.write seemed to have come with `v1.0.0-rc.0`. I had not noticed it before today.

### Specifications:
 * html2canvas version tested with: `v1.0.0-rc.3`
 * Browser & version: Chromium 69
 * Operating system: Mac and Windows

**Comment by TuffyLiu** [comment]
you can set  backgroundColor: 'rgba(0,0,0,0)', to fix this

**Comment by fakob** [comment]
@TuffyLiu thanks for the tip! I will give it a try.

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/pull/2012
