### ISSUE TITLE
Resizing image before drawing on to existing canvas

### ISSUE THREAD

**Issue by jlin816** [niklasvh/html2canvas#1912]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console
----
Is there a way to get the width and height of the image html2canvas has produced, so I can rescale it before drawing on to an existing canvas?

Right now, if I do `html2canvas(divToDraw, { canvas: document.getElementById("canvas") });`, the image is cropped to the canvas size. I'd like to do something like `ctx.drawImage(htmlImg, 0, 0, htmlImg.width, htmlImg.height, canvas.width, canvas.height)`, but from my reading of the docs I'm not sure if/where the image (instead of the new canvas) is returned from `html2canvas`. What's the proper way to resize the image to fit an existing canvas?

Thanks in advance!

**Comment by jlin816** [comment]
Self-resolved.

**Comment by tielushko** [comment]
How did you resolve it? What did you end up using to resize the image?
