### ISSUE TITLE
border-bottom 不显示

### ISSUE THREAD

**Issue by ShnHz** [niklasvh/html2canvas#1916]
截图时 border-bottom 不显示在图片上

**Comment by zhongziqi** [comment]
add the following code before border style

border-style: solid;
border-width: 0;

**Comment by zxl56123** [comment]
亲测可用，针对table布中，td 中隐藏的某一个边框，会影响其他边框的显示
 如果代码里面有设置边框隐藏的，使用宽度设置就可以，不要使用border-top-style: none
border-top-width: 0px; 
border-top-style: none;    (需要删除)

**Comment by niklasvh** [comment]
Possibly fixed with https://github.com/niklasvh/html2canvas/pull/2010
