### ISSUE TITLE
Inconsistent border when some of side border is 'none'

### ISSUE THREAD

**Issue by vasylHordynskyy** [niklasvh/html2canvas#1920]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [X ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [X ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Not all borders are present on dive when some border side is set to 'none'.
I have div in my application with following styles:
    <div 
       style={{
           border: '1px solid green',
           borderBottom: 'none',
       }}
    >
        Test screenshot
    </div>
Then I use html2canvas to create screenshot of it:
    html2canvas(document.body, {}).then(canvas => {
      document.body.appendChild(canvas);
     });

As result I got screenshot where bottom and left border is missing.

I have checked on version 1.0.0-rc1 and it works as expected.

Also I found workaround for this issue. I have to specify following style for div:
    borderBottom: '0px solid', instead of 'none'.
then I get correct screenshot on 1.0.0-rc3.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc3
 * Browser & version: Chrome 75, Firefox 67.0.4
 * Operating system: Windows 10

**Comment by mazin5** [comment]
参照这个终于可以了，https://github.com/masak64/html2canvas
![image](https://user-images.githubusercontent.com/17469911/63858153-9830d700-c9d7-11e9-9ae3-eabd53b605f3.png)
