### ISSUE TITLE
截取的dom元素高度超出一定范围后会出现canvas绘画失败的情况

### ISSUE THREAD

**Issue by dingxiaokai** [niklasvh/html2canvas#1929]
截取的dom元素高度超出一定范围后会出现canvas绘画失败的情况

**Comment by a37610** [comment]
> 截取的DOM元素高度超出一定范围后会出现帆布绘画失败的情况

大佬，请问你这个问题解决了吗？？？

**Comment by dingxiaokai** [comment]
限制canvas画布的高度可以暂时解决，不同的浏览器canvas高度限制不一样




在2019年07月12日 14:37，a37610 写道：

截取的DOM元素高度超出一定范围后会出现帆布绘画失败的情况

大佬，请问你这个问题解决了吗？？？

**Comment by a37610** [comment]
> 限制帆布画布的高度可以暂时解决，不同的浏览器canvas高度限制不一样在2019年07月12日14：37，a37610写道：截取的DOM元素高度超出一定范围后会出现帆布绘画失败的情况大佬，请问你这个问题解决了吗??? - 你收到这个是因为你写了这个帖子。直接回复此电子邮件，在GitHub上查看，或将该线程静音。

好吧，那只能多画几个了
