### ISSUE TITLE
Getting context

### ISSUE THREAD

**Issue by adam-cyclones** [niklasvh/html2canvas#1932]
I am making composite UI effects such as realtime blur using the latest version.

Example: https://codepen.io/acronamy/pen/XLoVbR

I am looking for a way to apply ctx.filter blur to the canvas context before rendering. How can I get the 2d context?

**Comment by niklasvh** [comment]
You could create the `canvas` yourself, and pass it as an option to html2canvas. https://github.com/niklasvh/html2canvas/pull/2017 fixes the use of that option
