### ISSUE TITLE
No css border appearing when converting to canvas

### ISSUE THREAD

**Issue by rovanu** [niklasvh/html2canvas#1939]
### Bug reports:

Hi
This bug is back in the last Version
No border appearing when converting to canvas

http://jsfiddle.net/u8hL5tjg/

 * html2canvas version tested with: v 1.0.0-rc.3

**Comment by sezmars** [comment]
@rovanu 
Hi.
You can try this https://github.com/sezmars/angular-print. 
See the demo.

**Comment by hakimio** [comment]
As a workaround you can add the following before `border-left`:
```css
border-style: solid;
border-width: 0;
```
Fiddle: http://jsfiddle.net/ktcqm9hs/

**Comment by rovanu** [comment]
> As a workaround you can add the following before `border-left`:
> 
> ```css
> border-style: solid;
> border-width: 0;
> ```
> 
> Fiddle: http://jsfiddle.net/ktcqm9hs/
