### ISSUE TITLE
Uncaught (in promise) Error: Element is not attached to a Document in chrome console

### ISSUE THREAD

**Issue by 0xCTF** [niklasvh/html2canvas#1946]
In this website https://www4.inscription.tn/ORegMx/servlet/AuthentificationEtud?ident=cin
i'm trying to get an omage data url of the captcha, the current shown one
so i wrap <img to a div
```
<div id="divPage">
<img src="https://www1.inscription.tn/ORegMx/capito.png"/></div>
```
don't know why it's not working without div, anyway
this test code in jsfiddle working fine

> http://jsfiddle.net/hmj1cby4/1/

but in chrome console and firefox console using this code 
```
$.getScript("https://html2canvas.hertzen.com/dist/html2canvas.js", function() {
        html2canvas($("#divPage"), {
            onrendered: function(canvas) {
                document.body.appendChild(canvas);
               },
                       allowTaint: true,
                    taintTest: false
         });
  
});
```

i got these errors
firefox: Error: Element is not attached to a Document
chrome: Uncaught (in promise) Error: Element is not attached to a Document

What the issue here?
i will inject this code to an anroid webview to get an image data url of the captcha and put it in imageView

Hope someone help, i'm out of ideas, i spent many hours trying to take that screenshot of the captcha without success

**Comment by Vandesm14** [comment]
I have the same issue. Do you mind sharing your solution? (I assume you have a solution as this is closed)

**Comment by Svendolin** [comment]
Same issue here hahaha. But whats the solution for?! oO Cant find it xD
