### ISSUE TITLE
Working differently in chrome than firefox

### ISSUE THREAD

**Issue by 0xCTF** [niklasvh/html2canvas#1947]
Hi,

this code is to get the captcha data url

```
var div = document.createElement("div");
div.id = "divPage";
var img = document.querySelector("body > table.troisbords > tbody > tr > td > table > tbody > tr > td > div > blockquote > table > tbody > tr:nth-child(2) > td > form > table > tbody > tr:nth-child(4) > td:nth-child(2) > img");
img.parentNode.insertBefore(div, img);
div.appendChild(img);

$.getScript("https://pastebin.com/raw/dRap1YD8",  function() {

html2canvas($("#divPage")[0], {
            onrendered: function(canvas) {
                var m=canvas.toDataURL("image/png")
console.log(m);
               },
                       allowTaint: true,
    taintTest: false
         });
		 
		 });
```

the website is https://www4.inscription.tn/ORegMx/servlet/AuthentificationEtud?ident=cin

it work fine in firefox but it get different image in google chrome

please how can i fix that ?

i'm using html2canvas 0.4.1, 0.5 gives many errors

**Comment by hakimio** [comment]
Why would you use 4 year old release of html2canvas release and expect support for it?

**Comment by 0xCTF** [comment]
why not ?
i used html2canvas 1.0.0-rc.3 but it have a problem with my code, 
anyway, i fixed the problem of google chrome, i changed ` var m=canvas.toDataURL("image/png")` to  `var m=canvas.toDataURL("image/jpeg")` with filling the empty pixels with white instead of black because the png image is black text,

if you can change this code to work properly with 1.0.0-rc.3, i'll be glad

```
var div = document.createElement("div");
div.id = "divPage";
var img = document.querySelector("body > table.troisbords > tbody > tr > td > table > tbody > tr > td > div > blockquote > table > tbody > tr:nth-child(2) > td > form > table > tbody > tr:nth-child(4) > td:nth-child(2) > img");
img.parentNode.insertBefore(div, img);
div.appendChild(img);

$.getScript("https://pastebin.com/raw/dRap1YD8",  function() {

html2canvas($("#divPage")[0], {
            onrendered: function(canvas) {
			var ctx=canvas.getContext("2d");
			var w=canvas.width;
  var h=canvas.height;
  ctx.fillStyle = "#FFF";
    ctx.fillRect(0, 0, w, h);
  ctx.drawImage(img,0,0);
  var imgData=canvas.toDataURL('image/jpeg',1.0);
console.log(imgData);
               },
                       allowTaint: true,
    taintTest: false
         });
		 
		 });
```

the website is https://www4.inscription.tn/ORegMx/servlet/AuthentificationEtud?ident=cin

also i have the problem of getting half of the image, check the image 

`data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAyAKADAREAAhEBAxEB/8QAHgABAAIDAQADAQAAAAAAAAAAAAgKBwkLBgIDBQT/xAA7EAABAwMDAAcHAgMIAwAAAAAGBAUHAgMIAAEJChQVGVmY1xESExY5eLghQRcmMyMlMTI0NjdhGBok/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALDXGTxk8bZ7xt8fJ0dcfOEBobGmEGKBYYmJZihAxGVFhURwMAvBCTExC8AKx3fiB9d1ix0eXl0WKnF0cVSlcuU31N+7dqCb/dO8WXhp4AeTfHX050DuneLLw08APJvjr6c6B3TvFl4aeAHk3x19OdA7p3iy8NPADyb46+nOgd07xZeGngB5N8dfTnQO6d4svDTwA8m+OvpzoIgZrQlwA8dsWME15i4U4AQ/GRRIDVFrETd37H0gdeO3scKyxsYuxotgg2IE3WR8JJ3DtNY1J2ez2Z1VQ4Wlq1vTKwYUwlwA8iUWP814dYU4ATBGQvIDrFr6Td37H0f9RO2QcFSxzYuxpSggJIFPVh82GHDtNG1KGe92n1VO4XVqJwTJAl/3TvFl4aeAHk3x19OdBqByjyJ6KhhdOxzjRkvj/gBGs2xr8s/OoV3Yigx7F+cQ4ePxz+YwDFcqEnHtESKmF2/ul+X9T6/1Bf1VzSrUScNv3dO8WXhp4AeTfHX050GP5Z47+HeDoskua5S48MABeMofj8ylKRSb/wAI4Ne/l0Ej8cciwufexh2KHcgd+yB9ocHDsxianN4X9X6q2N61bdsJroQAwpN+jF8iUpv8KYdYx4ATBJovH7rKT6M92u3x/wBRBGQjFRNzfe2ZSxnCR9T1YgNhhv7MRuqh4vdp9aTt91EicFKQNn/dO8WXhp4AeTfHX050DuneLLw08APJvjr6c6B3TvFl4aeAHk3x19OdA7p3iy8NPADyb46+nOgd07xZeGngB5N8dfTnQQg5NuMnjbAuNvkGOgXj5wgCzYLwgyvLA4xE8UIGHCoTKhyBj54HiYZIWcBRu7CQMTujRujM8taxK4tbilTLkKmwpsWrtITf4nfpZcaf2AYb/jrHOgzBNebuF+NZU3guRmXeMEAmzsPpSxrDprn2KYrKnIVXOLqzoSZvHjosYXdYPrHdifGtK8p0dxuUOLM6obKmtS3LLVkPblGSGO4RFTDOxpPcLiEIFTMxEQvMhRKQOwRUSD5S12nwZfWGQ3Z9SCLwzETLfsu7E5t7uoRO7XetODffUJLlF7cP04hneD8gxms1gSZYpm8NtLK2+4WxDIYjJQzbX26aa7iGt+DHh6aqFlFFVNdaapXteppqpqqo223230GO5LzUw3hc3SRnMWWmM0TyOv3S7IY/kueIsBDdbuu2tVItkgoUFTU/Kd1lN6zul2soK+sbXbW9n39rlHtCkh0lTmOyLcM6BbisxuyJ2xIiFvuww0ZDZAtj89C6ha6zs2C5UmcSE+ErSkqZITAIzNxskJUwRVS4FFK4mTO9D23oWpq2CNGY/RUso8KsaJQzwhDkd2lyRIPjsgnc1TtoSWwyRXg8KYbxoakIHL7ZMx64ELy0sbc4PrTbcGoYrIbSCjZKvTOSlIjuBriyY5R8iuQXgc/hRlAUOknSRiVyQ4ut7TMZBXTfKziP5axkzkrGms1c/wCsSlok4xqRJ1hau27WfmZ1Yan285PqRyenQLVnQwnpmHOJvI5/IXZsYWJmzylxyd3p5XpWtpam5HjhivfVr3JyXXbCNCiS2aK7ylUqvWrFi1RVcu3KaKd99gsyx5ndg/LpErEIozJxUk8tQbX91wvHmQ8RGpEi2S7Xd1O6tkGy9yck2yfaxf3v73k1HwtrN3e57u1uv2Bynek6vbMRc42bzwPu7Y+tCqrG6hK6My9I5tymtJiLAaJVTYXIrt9NeqTLE6hIopt3at7KmxesXNqbtquikOo2Rcp3GUJb3KCTkQweZ79vbfepGsyrgyhfv7v6Ve43UnVS67vTv+m+1tPXvtv+m+3t30Gr7k85muK0249c84nCc78dTaRJLwzyhjwDFQw5SljgTmhpCJwNC4+21j1pxSVLHp8ckLckquqbSf46m3vdv27XvXKQo7dGCz2xR4689pim7MOUqokjQkw9P4wYiCgIkQ+uOR29TTj+VtY/bZo0EzF8T1q2AKJl+zkubUrNY2bN06pysK1aGwqC7ORdLS4V2T4nZk2SwX+57fd+XcfpRTfF9n+Hw/m1kF/Z737fF+H/AN+zQYIIemX8TDLvXs2A2ZxfvT7dqPl6H41TbXd/29z5rnAZ329v7e/tRv8A9e39NB43/wBwrGcm/wCJuPvP6Q/if6b+SABF8f2/5P8AbRsce7736f0/jf4/p737g36UNlAS/wDE3Ajn9IfxP9L7U8hIfj+3/J/trG459nvfp/T+N7Pb+nvfuFj/AAKyOlPLXFCK8gZrxmP8O5OPvnbcmxylH5iqOI6+WZELQ9lperhWCxq+3disdYGg3bri0JY/7rJEVNi2rT02nBWGP+WL6WXJZ9gGZH46yNoHE79LLjT+wDDf8dY50FAPpq31TYD+wCLPyKyq0GT4K4HeTXmiwohLJyf8lmOEwuKMWY3ifAHHF7EHwgbSeMYjjFhCQ0icU9JeOtcSIZqui6AiVSFdbzwmLu0rZJeHkQMnBkVQVm8DOQ/KXjokA/P8W5HuR8/SlFxVEhOoVW1Liy2m8mRXLDOY9iU7KEV8ujl4uWSoHeFLY6XGd0sKLOyBe2ujs1uIYrl2J5VcRavJ9Sz5CnsUnBcjYn7JGWYxfxwcLZpKEBETuw6kkFWUHLUbP7hYHCd7tL1ZPYKHlG2Obs6jzVXavW9gkK0Yansu4Fk/IRIGUmPIiJRlI6nFoEiiUy81t5DSy8xmBxsUpxyLB1jj4kSlTMJiEniLG1rX4obW0QYGmwxujgMCzMLWlIeVQci2dpRCrFh4R5tzky4wLG9pjxcBPshHLhHLDH1xclsVNDwzMVt4IXICYElNNyoQbUDzZoZkVLQzD6m3QlbKw2p8kHDgO4JcXMJZhQtyXpsyYByOyPjcdRx7HEevANDt4vVRFOL1Yka7fUzEXWnc4BLAeTx7SnIo8FjIfslJK0Oew6rsu7AqDF/Dbwp5jcvLKZtIDKCyCcRAU2qRSXJpSpfiMIXyPeZh5fQNg8RtbqwpDqSGxgvMTwRKnB9H2xoHlgzs5EDesVD6B6D6+azgTmThxuxUWOkvsGQsIS84u4wwyY0BayN3pjOmVBad74sWg6snNrDdu7M9StyGXJqMHyy52WV+oX2Ga8hS23ANELmpQqlNu63NuzUnpb2lNcS0q763a6uRtSNI6OPxlP8AaUbvDlYVu9SSn+wQVLt0KX/5k1nQXRMb+ht5NZFxMsm+ZZxBMIyyQevmMeYvUxuWTK5AQ++XFDkNB0lGbtJgw6CDs2I7yJCqQ/AkwibEe1HzOppKrLqypQq0TPD8jcfuUU+44TkAARXIMYWZYhIrZ3xHSRi+y8rC3gdGZQCXC+nROSVeydvDstRi/wBu00uVKtEw0vSGhCreWJQG7Hoqce4oHGdmTb3mfG8HSNBkQ8fcyzK+7ZBAAdIoADVhUy46bL5CqaDdlfmpudB8WcyVPaekqHZ0TNjm6okl33HC/ZvBP3jsxEAOkA8uch5aWcco8gzi4xHIWlvDYeCIwEI3D5B7BVXl0axwQsAi0NbC9lJ9foqlGebt229Xm0VvNUZX19tkdwpWmDotDccR4HU2qBADDBWixTTTZoGxdjY6bNNG221NNqlsQpdrdN`

Thanks for help

**Comment by hakimio** [comment]
Try RC1 and create a jsfiddle reproducing the issue.

**Comment by 0xCTF** [comment]
first time using RC1
 i got 

> html2canvas: onrendered option is deprecated, html2canvas returns a Promise with the canvas as the value

i think it's better to use chrome console in this situation
Also jsfiddle use html2canvas 0.4.1, i don't know how to change it 

so i need to use .then i think, but last time using RC3 not RC1 i got different image then the shown one, 
anyway, i spent couple hours just to change onrendered with .then 
hope you can edit the code in try it in chrome console using the website in my previous comments

```
var div = document.createElement("div");
div.id = "divPage";
var img = document.querySelector("body > table.troisbords > tbody > tr > td > table > tbody > tr > td > div > blockquote > table > tbody > tr:nth-child(2) > td > form > table > tbody > tr:nth-child(4) > td:nth-child(2) > img");
img.parentNode.insertBefore(div, img);
div.appendChild(img);

$.getScript("https://pastebin.com/raw/zuN14v7G",  function() {

html2canvas($("#divPage")[0], {
            onrendered: function(canvas) {
			var ctx=canvas.getContext("2d");
			var w=canvas.width;
  var h=canvas.height;
  ctx.fillStyle = "#FFF";
    ctx.fillRect(0, 0, w, h);
  ctx.drawImage(img,0,0);
  var imgData=canvas.toDataURL('image/jpeg',1.0);
console.log(imgData);
               },
                       allowTaint: true,
    taintTest: false
         });
		 
		 });
```

Please let me know if any part of the code you didn't understand 
also, pastebin is just temporary, i will use local file in the final release of my android app

Thank you

**Comment by hakimio** [comment]
It seems to be working as intended in Chrome. I don't see any issue. Anyway, why do you need html2canvas when you are  just replacing the generated canvas' contents with an image taken directly from your site? Doesn't make any sense.

**Comment by 0xCTF** [comment]
how the code worked in your side ? because it not working when i tried it,
also, the captcha is not a simple image to take it by it link, it will regenerate, so i need to use html2canvas for that purpose
anyway, i fixed the problem using this code

```
var imported = document.createElement('script');
imported.onload = function(){
var str=document.querySelector("body > table.troisbords > tbody > tr > td > table > tbody > tr > td > div > blockquote > table > tbody > tr:nth-child(2) > td > form > table > tbody > tr:nth-child(4) > td:nth-child(2)").innerHTML.length
if(str<=43){
  var div = document.createElement("div");
div.id = "divPage";
var img = document.querySelector("body > table.troisbords > tbody > tr > td > table > tbody > tr > td > div > blockquote > table > tbody > tr:nth-child(2) > td > form > table > tbody > tr:nth-child(4) > td:nth-child(2) > img");
img.parentNode.insertBefore(div, img);
div.appendChild(img);

}
html2canvas($("#divPage")[0], {
            onrendered: function(canvas) {
			var ctx=canvas.getContext("2d");
			var w=canvas.width;
  var h=canvas.height;
  ctx.fillStyle = "#FFF";
    ctx.fillRect(0, 0, w, h);
  var cap = document.querySelector("#divPage > img")
  ctx.drawImage(cap,0,0);
  var imgData=canvas.toDataURL('image/webp',1.0);
console.log(imgData);
               },
                       allowTaint: true,
    taintTest: false
         });
}
imported.src = 'https://pastebin.com/raw/dRap1YD8';
document.head.appendChild(imported);
```

Thanks for help
