### ISSUE TITLE
Issue with positive z-index computation while preparing the stack tree

### ISSUE THREAD

**Issue by rahulkatikineni** [niklasvh/html2canvas#1949]
### Bug reports:

Issue with positive z-index computation while preparing the stack tree

### Specifications:

 * html2canvas version tested with: 1.0.0-rc3
 * Browser & version: Chromium 74.0.3729.108 
 * Operating system: Windows 10

I have been able to debug the issue to the computation of "positiveZIndex" array. 

Unless, a higher z-index is found, we are simply adding the element to the beginning of the array. Instead, shouldn't we add it post all existing elements with the same z-index to preserve dom order since elements with same z-index are rendered in the dom order?

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/commit/00555cf1efddfed5877811d8a03a326f9943ab06
