### ISSUE TITLE
cannot paint properly for viewport screenshot after scroll

### ISSUE THREAD

**Issue by jdsxzhao** [niklasvh/html2canvas#1951]
### Bug reports:

I have a long page with nearly 2000px height and want to screen shot for only viewport.  In this page, there is a fixed navigation bar so I set scrollY following the direction in h2c homepage.

All the config about postion and coordinate are like below:
```
            width: document.body.clientWidth,
            height: document.body.clientHeight,
            windowWidth: document.body.clientWidth,
            windowHeight: document.body.clientHeight,
            x: document.documentElement.scrollLeft,
            y: document.documentElement.scrollTop,
            scrollX: document.documentElement.scrollLeft,
            scrollY: document.documentElement.scrollTop,
```
With this config, I get a canvas with clientWidth and clientHeight, but only content before `(document.body.clientHeight - document.documentElement.scrollTop)` is painted (just same as the body's position in document because the body's height in captured page is set '100%' so in this situation, the body element is from `-scrollTop` to `clientHeight  - scrollTop`). Then I revised my config to below:

```
            width: document.body.clientWidth,
            height: document.body.clientHeight,
            windowWidth: document.body.clientWidth + document.documentElement.scrollLeft,
            windowHeight: document.body.clientHeight + document.documentElement.scrollTop ,
            x: document.documentElement.scrollLeft,
            y: document.documentElement.scrollTop,
            scrollX: document.documentElement.scrollLeft,
            scrollY: document.documentElement.scrollTop,
```
In this situation, I can get a canvas  with clientWidth and clientHeight and in most instances，I can get the screenshot consistent with the actual. But still one problem remains, when I scroll more, the offset compared to the actual will become bigger, the screenshot is getting closer to the top of the page. Finally when I scroll to the bottom, the screenshot becomes the toppest content. The specific regular I am still studying.

 * html2canvas version tested with: 1.0.0-rc3
 * Browser & version: Chrome
 * Operating system: Win10

**Comment by jdsxzhao** [comment]
I tried to revise body's height to 'auto' and the first config works properly. But I still cannot understand when my body's height is '100%' and scrollTop=200px e.g. why I can get the overflow content of body with second config? How windowHeight works in this situation?

**Comment by GerardoFurtado** [comment]
Have you seen this issue? https://github.com/niklasvh/html2canvas/issues/1878

**Comment by ahmedfeyzi** [comment]
> **I solved all possible problems as follows..**

```
html2canvas(element , {
        scrollX: -window.scrollX,
        scrollY: -window.scrollY,
        windowWidth: document.documentElement.offsetWidth,
        windowHeight: document.documentElement.offsetHeight
})
```
