### ISSUE TITLE
1.0.0-rc.3 regression error - backgroundColor: null doesnt make canvas background transparent

### ISSUE THREAD

**Issue by glomotion** [niklasvh/html2canvas#1957]
### Bug reports:

Transparent background works just fine in 1.0.0-rc.2. In 1.0.0-rc.3 it's rendering out a canvas with a white bg. 

Repro:
https://codepen.io/glomotion/pen/JgyMdK

 * html2canvas version tested with: 1.0.0-rc.3
 * Browser & version: Chrome 76
 * Operating system: MacOS 10.14.6 (18G84)

**Comment by Suntgr** [comment]
it same to me. set `backgroundColor: transparent` is ok, but `Uncaught ReferenceError: transparent is not defined`. set `backgroundColor: nul`l is not work

**Comment by RyoheiTomiyama** [comment]
@glomotion 
I resolved this way.

```
html2canvas(node, { backgroundColor: 'transparent' })
```

**Comment by glomotion** [comment]
@RyoheiTomiyama thanks! that works. :)

**Comment by lwpassvoice** [comment]
Or this strange way:
```
html2Canvas(elem, { backgroundColor: 'null' })
```
