### ISSUE TITLE
How I stop console logging when foreign object redendering is true

### ISSUE THREAD

**Issue by FineStrokes** [niklasvh/html2canvas#1963]
How I stop console logging when foreign object redendering is true
I have set logging as false and foreign object redendering as true in config 
But It logs messages in console related to foreign object rendering.
How do I prevent it

### Specifications:

 * html2canvas version tested with: "^1.0.0-rc.3",
 * Browser & version: All
 * Operating system:MacOS

**Comment by hakimio** [comment]
This is duplicate of issue #1874.

**Comment by subramanya4shenoy** [comment]
@FineStrokes  Okay, I would suggest you to take this JS and use it as a script in your angular project. then u will be able to edit it and comment the console. fixed for me.
