### ISSUE TITLE
How to add loading icon after copying dom

### ISSUE THREAD

**Issue by jdsxzhao** [niklasvh/html2canvas#1966]
# Question:

### Specifications:

I want to add a loading spinner when h2c rendering the canvas because this step takes some time in which the page has no response. However, if I add the spinner just when I click the trigger button, the spinner will also be rendered into the canvas. What I understand is that the spinner should be added after the dom elements are copied. But I don't know when dom element copy finish. Can anyone help me? Thanks a lot.

 * html2canvas version tested with: 1.0.0-rc3
 * Browser & version: Chrome
 * Operating system: Win10

**Comment by hakimio** [comment]
Have you tried `onclone` config?

**Comment by jdsxzhao** [comment]
Oh, just not notice that. Thank you so much!
