### ISSUE TITLE
Disable proxy for data url

### ISSUE THREAD

**Issue by surunzi** [niklasvh/html2canvas#1967]
I'm using proxy options for loading cross-origin images and I found out it also takes effect for data url which is not necessary.

```html
<img src="data:img/jpg;base64,xxxxx"/>
<script>
html2canvas(document.body, {
  proxy: 'https://example.com/'
}).then(function(canvas) {
  document.body.appendChild(canvas);
});
</script>
```

The code above makes a request with url `https://example.com/?url=data%3Aimg%2Fjpg%3Bbase64%2xxxxx&responseType=blob` when running.

**Comment by niklasvh** [comment]
The correct mime type for an inline image would be `image/*`, which would correctly be ignored by the proxy https://github.com/niklasvh/html2canvas/blob/master/src/core/cache-storage.ts#L200
