### ISSUE TITLE
Fix Textarea break line 

### ISSUE THREAD

**Issue by maxeemov** [niklasvh/html2canvas#1970]
html2canvas version tested with: 0.4.1
Browser & version: 0.4.1
Operating system: ubuntu 18.04
For text in textarea wrapped on a new line (bleak line) I've added 'word-wrap' to cssPropertyArray.
Added textarea break line css property:
```
 var valueWrap = 
  doc.createElement('valuewrap'), 
  cssPropertyArray = 
['lineHeight','textAlign','fontFamily','color','fontSize','paddingLeft','paddingTop','width','height','border','borderLeftWidth','borderTopWidth', 'word-wrap'],

textValue,
textNode;

    cssPropertyArray.forEach(function(property) {
      try {
        valueWrap.style[property] = getCSS(el, property);
      } catch(e) {
        // Older IE has issues with "border"
        Util.log("html2canvas: Parse: Exception caught in renderFormValue: " + e.message);
      }
    });
```

**Comment by zhoujun494** [comment]
hello!
i have the same problem，the textarea was not break line，Have you solved it?

**Comment by maxeemov** [comment]
> hello!
> i have the same problem，the textarea was not break line，Have you solved it?

You can past css styles to the list cssPropertyArray.
Like: "overflow-wrap"

**Comment by niklasvh** [comment]
versions prior to <1.0 won't be getting any updates any more.
