### ISSUE TITLE
Data uri and same origin

### ISSUE THREAD

**Issue by plufz** [niklasvh/html2canvas#1972]
### Bug reports:

I have img:s with datauri as src that are dynamically created by javascript. The images wont render (or a very small part of the image renders at a weird location). Are those images considered non-origin (or something) or is it supposed to function to render this?

### Specifications:

 * html2canvas version tested with: 
 * Browser & version: Chrome 75.0.3770.100
 * Operating system: macos 10.14.5

**Comment by ZemezLab** [comment]
Do you have a linear html gradient that you are converting? i think the problem is this thing

**Comment by niklasvh** [comment]
Could you share an example?
