### ISSUE TITLE
Image size is incorrect when there is page scaling

### ISSUE THREAD

**Issue by jdsxzhao** [niklasvh/html2canvas#1975]
### Bug reports:

I use html2canvas to take screenshot. The screenshot is basically correct when there is no scaling. But when I zoom in (window.devicePixelRatio = 1.5 e.g.), the generated image's size is not changed.

Here is my config:
```
width: document.documentElement.clientWidth,
height: document.documentElement.clientHeight,
windowWidth: document.documentElement.clientWidth,
windowHeight: document.documentElement.clientHeight,
x: document.documentElement.scrollLeft,
y: document.documentElement.scrollTop,
scrollX: document.documentElement.scrollLeft,
scrollY: document.documentElement.scrollTop, 
scale: $window.devicePixelRatio || 1,
```
The original screen size is 1903 * 937, after zooming in, the `document.documentElement.clientWidth = 1269` and `document.documentElement.clientHeight = 625`. But the size of generated image is still 1903 * 937.

### Specifications:

 * html2canvas version tested with:1.0.0-rc3
 * Browser & version: Chrome
 * Operating system: Win10

**Comment by niklasvh** [comment]
Could you please share an example on jsfiddle

**Comment by Avinier** [comment]
Having a similar issue, using Nextjs. and the screenshot is basically correct, but the image in it is scaled wrong

**Comment by kzkhykw** [comment]
Having a similar issue using Next.js as well
