### ISSUE TITLE
Cannotfind name 'ReturnType'.How to Solve this Problem?

### ISSUE THREAD

**Issue by snake3201** [niklasvh/html2canvas#1982]
using the latest [version] 1.0.0-rc.3
node_modules/html2canvas/dist/types/css/index.d.ts : error TS2304: Cannot find name 'ReturnType'.
Cannot invoke an expression whose type lacks a call signature. Type 'typeof "eclipse:fusion/node_modules/html2canvas/dist/types/index"' has no compatible call signatures.

**Comment by goors** [comment]
same here

**Comment by niklasvh** [comment]
Update to ts 2.8 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

**Comment by snake3201** [comment]
thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Niklas von Hertzen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月22日(星期天) 中午12:16
收件人:&nbsp;"niklasvh/html2canvas"<html2canvas@noreply.github.com&gt;;
抄送:&nbsp;"笑熬浆糊"<33974223@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [niklasvh/html2canvas] Cannotfind name 'ReturnType'.How to Solve this Problem? (#1982)




Update to ts 2.8 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

**Comment by YesicaMacias14** [comment]
@niklasvh  I already update to TS 2.8, but the issue persist, any alternative option or it is the only one??
