### ISSUE TITLE
How to take screenshot of overflow element ?

### ISSUE THREAD

**Issue by HiraveBapu** [niklasvh/html2canvas#199]
OR is it possible to pass an URL of page and take screenshot of whole page ? How are you doing it on Test Console ?

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });
