### ISSUE TITLE
Transparent border render error

### ISSUE THREAD

**Issue by wztscau** [niklasvh/html2canvas#1990]
### Bug reports:

User transparent to achieve a triangle. e.g.
```
border-style: solid;
border-width: 5px;
border-color: transparent transparent #030303 transparent;
```
Expected ▲ but the result is ▼.
Then I saw the source (line 6735) `this.renderBorder(border.color, side++, paint.curves)` . I doubt the reason is this line.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.3
 * Browser & version: chrome 76.0.3809.100
 * Operating system: windows10

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/pull/2010
