### ISSUE TITLE
html2canvas doesn't render some css properties

### ISSUE THREAD

**Issue by ahmedmansour1997** [niklasvh/html2canvas#1994]
i am using the script i have downloaded from your site https://html2canvas.hertzen.com

## Bug reports:

hey guys,, 
i have a problem with html2canvas .. 
it deosn't render the borders nor the background colors ... that is my code .. 
    
$(".btn_for_print_out").on("click" , function(){
    window.scrollTo(0,0); 
   html2canvas(document.querySelector("#capture")).then(function(canvas) {
        canvas.toBlob(function(blob) {
            window.saveAs(blob, "my_Corsorr_CV.png");
        });
    });
})

it doesn't read those css properties :: border-bottom / background-color / text-transform
although it reads the rest of css just fine!!!!!!!!!!!

### Specifications:
 * Browser & version: Chrome last version

**Comment by niklasvh** [comment]
Supported CSS properties http://html2canvas.hertzen.com/features
