### ISSUE TITLE
my image screenshot in ios webview is occasionally white,

### ISSUE THREAD

**Issue by boboZh** [niklasvh/html2canvas#1995]
### Bug reports:

my image screenshot in ios webview is occasionally white,
 it acts like this "https://img4.easypass.cn/das/carsource1/origin/cac62901-8930-47e3-ac1d-cca42b9e64cc.png", 
when add a border to the image, it acts like this, "https://img4.easypass.cn/das/carsource1/origin/d6ea23c2-5f88-44ed-ac74-d2b3c6a73dbd.png"

and here is my code:
Html2Canvas(poster, {
          dpi: window.devicePixelRatio * 2,
          useCORS: true, // 允许跨域图片
          logging: false,
          width: width,
          height: height,
          scale: scale,
          canvas: canvas
        })
          .then(function (canvas) {
            let imgBlob = canvas.toDataURL('image/jpg', 1.0)
            that._uploadImg(imgBlob)
            let shareBase64 = imgBlob.match('data:image/png;base64,') && imgBlob.split('data:image/png;base64,')[1]
            that.base64Url = shareBase64
            that.$refs.shareWrapper.show(that.shareTextOrigin)
            
          })
          .catch(err => {
            showToast(this, err.message)
          })

thank you

### Specifications:

 * html2canvas version tested with: "^1.0.0-rc.3"
 * Browser & version: ios webview
 * Operating system:  ios

**Comment by icksky** [comment]
the same. try to transform the source image's src to base64, then use html2canvas to generate your image.
I debug the html2canvas, and found out that the image's `complete` is `false`, but never dispatch `load` event. So the `intrinsicWidth` and `intrinsicHeight` is `0` when `new ImageElementContainer`.
I don't know if this cause the bug. Hope a little help.

**Comment by boboZh** [comment]
> the same. _**try to transform the source image's src to base64, then use html2canvas to generate your image**_.
> I debug the html2canvas, and found out that the image's `complete` is `false`, but never dispatch `load` event. So the `intrinsicWidth` and `intrinsicHeight` is `0` when `new ImageElementContainer`.
> I don't know if this cause the bug. Hope a little help.

awsome! it works! thanks a lot!

**Comment by Viin-zx** [comment]
兄台，请问下如何处理的在ios手机下渲染白屏问题。有点没理解。

**Comment by boboZh** [comment]
> 兄台，请问下如何处理的在ios手机下渲染白屏问题。有点没理解。

我的问题是渲染没毛病，但是截图有毛病，上面这位sky网友的意思是你把图片地址转为base64再放上去，试一下看行不行，我的OK

**Comment by Viin-zx** [comment]
@boboZh 哥，请教下您知道为什么在ios上渲染不出来dom中的图片么，概率性事件，概率还挺大的。web和安卓都没问题。找了几天都没找到解决方法。

**Comment by boboZh** [comment]
> @boboZh 哥，请教下您知道为什么在ios上渲染不出来dom中的图片么，概率性事件，概率还挺大的。web和安卓都没问题。找了几天都没找到解决方法。

这个不清楚诶，没有遇到过

**Comment by Cjhome** [comment]
After testing the above scheme will still appear

**Comment by bfek** [comment]
> @boboZh 哥，请教下您知道为什么在ios上渲染不出来dom中的图片么，概率性事件，概率还挺大的。web和安卓都没问题。找了几天都没找到解决方法。

the same problem!

**Comment by boboZh** [comment]
> > @boboZh 哥，请教下您知道为什么在ios上渲染不出来dom中的图片么，概率性事件，概率还挺大的。web和安卓都没问题。找了几天都没找到解决方法。
> 
> the same problem!

不太清楚，我这边截图ios又有问题了，考虑自己写不用作者组件了

**Comment by boboZh** [comment]
> the same. _**try to transform the source image's src to base64, then use html2canvas to generate your image**_.
> I debug the html2canvas, and found out that the image's `complete` is `false`, but never dispatch `load` event. So the `intrinsicWidth` and `intrinsicHeight` is `0` when `new ImageElementContainer`.
> I don't know if this cause the bug. Hope a little help.

but now, it can reproduce occassionally with base64 src, do you know how to do with this?

**Comment by icksky** [comment]
> but now, it can reproduce occassionally with base64 src, do you know how to do with this?

I also found out this, but sorry, I also have no idea

**Comment by mliotinoca** [comment]
I solved it by increasing value of `imageTimeout`.

**Comment by wenlittleoil** [comment]
2023, the problem still exist in some iphone.
