### ISSUE TITLE
v1.0.0-rc.4 release

### ISSUE THREAD

**Issue by mcolemanNOW** [niklasvh/html2canvas#2003]
@niklasvh Could you please release a v1.0.0-rc.4 build so we can have a released version with the fixes and features that have been merged since v1.0.0-rc.3?

**Comment by glomotion** [comment]
yes please! this would be awesome. ATM we're having to use v1.0.0-rc.1 to avoid TS build errors and other problems

**Comment by niklasvh** [comment]
Added/merged some more fixes and published rc.4. Sorry for the delay.
