### ISSUE TITLE
html2canvas:Error loading image

### ISSUE THREAD

**Issue by shuai7** [niklasvh/html2canvas#2019]
```
case 7:
 e_1 = _b.sent();
 Logger.getInstance(this.options.id).error("Error loading image " + container.src);
  return [3 /*break*/, 8];
```
The project uses html2canvas. js, which is very powerful, but there is a user avatar that sometimes does not exist. Check the print log error Error loading image, what is the reason?

**Comment by niklasvh** [comment]
Without more information on how to replicate the issue there is really nothing I can do to help.

**Comment by 592192890** [comment]
in iphone 5c, if img is base64, the pages will report the error:Error loading image

**Comment by Crazycheng** [comment]
below iOS 10.2.x will report the error: Error loading image data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAAAXNSR0IArs4c6QAAD1xJREFUeAHtnYFqHUsOBeMl///LXg+swc…

**Comment by wenyiweb** [comment]
you can use the version 0.5.0-beta4.this version is ok.

**Comment by newfan** [comment]
> you can use the version 0.5.0-beta4.this version is ok.

it's work for me . nice :)

**Comment by FantasyGao** [comment]
Use online links or img  binary format

**Comment by aisagacious** [comment]
> > 您可以使用0.5.0-beta4版本。可以使用此版本。
> 
> 这对我有用。不错:)

我生成出来是空白的

**Comment by ht159357** [comment]
> in iphone 5c, if img is base64, the pages will report the error:Error loading image

iPhone OS is IOS8 - 10 ?
