### ISSUE TITLE
Same origin images not loading when using Laravel and Vue with jsPlumb

### ISSUE THREAD

**Issue by rhaicode** [niklasvh/html2canvas#2040]
Here is a jsPlumb surface. I want to download the surface by using html2canvas followed by  snippets of code. All of the images on the palette are from the public/images. It should fall under same origin resource which should allow the images to be used, but unfortunately, no images are shown.

![Capture](https://user-images.githubusercontent.com/22829115/67159123-2dff3780-f373-11e9-998d-e8dcfe150f7e.PNG)

![Capture](https://user-images.githubusercontent.com/22829115/67159156-9f3eea80-f373-11e9-8d92-756866d14b04.PNG)

![Capture](https://user-images.githubusercontent.com/22829115/67159174-c39ac700-f373-11e9-85ef-16eff0b464b7.PNG)

![Capture](https://user-images.githubusercontent.com/22829115/67159183-edec8480-f373-11e9-94ce-4fd7fb5bd4bf.PNG)

![Capture](https://user-images.githubusercontent.com/22829115/67159207-4d4a9480-f374-11e9-986c-75ac43eaab44.PNG)

The only workaround I can only think of is to deeply access the jsPlumb surface just to get the nodes and connectors details, which would be an exhaustive work to do.

Specifications:
 - html2canvas version tested with: latest
 - Browser & version: Chrome 77.0.3865.120
 - Operating system: Windows 10

**Comment by sporritt** [comment]
@rhaicode Please don't forget that the Toolkit license does not permit you to share links that would expose the unobfuscated Toolkit source code.  It seems perhaps unlikely the maintainers of this project will be able to assist you with this issue.
