### ISSUE TITLE
vue框架 返回的canvas为空

### ISSUE THREAD

**Issue by songyu0122** [niklasvh/html2canvas#2041]
<template>
    <div class="imageWrapper" ref="imageWrapper">
        <img style="width:100px;height:100px" class="real_pic" :src="dataURL" />
        <img src="@/assets/poster.png">
    </div>
</template>
<script>
import html2 from 'html2canvas'
export default {
    data(){
        return{
            dataURL: ''
        }
    },
    mounted() {
        html2(this.$refs.imageWrapper,{
            backgroundColor:null
        }).then(canvas=>{
            let dataURL = canvas.toDataURL("image/png");
            this.dataURL = dataURL;
        })
    },
}

最简单的用法，但是class="real_pic" img里面现实为空

**Comment by tonymiao2012** [comment]
> <script> import html2 from 'html2canvas' export default { data(){ return{ dataURL: '' } }, mounted() { html2(this.$refs.imageWrapper,{ backgroundColor:null }).then(canvas=>{ let dataURL = canvas.toDataURL("image/png"); this.dataURL = dataURL; }) }, }
> 最简单的用法，但是class="real_pic" img里面现实为空

1. Use google or read html2canvas configures carefully first before submitting an issue.
2. Please format your words
3. Please use **ENGLISH**
