### ISSUE TITLE
parseDisplayValue doesnt support "-webkit-box" styles 

### ISSUE THREAD

**Issue by ChrisMiaoMiao** [niklasvh/html2canvas#2068]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

parseDisplayValue function in src/css/property-descriptors/display.ts doesn't support "-webkit-box" styles.
I am testing with Google Chrome and have an element with display value as "-webkit-box". But parseDisplayValue returns Display.None since it's not in the supported list. And later, that element won't be rendered on the canvas since it is "invisible".

Open it in Google Chrome, you will only see one red square. But I expect to see 2.
Please see the example on [here](https://jsfiddle.net/chrisXiong/uapb5vxq/9/).
### Specifications:

 * html2canvas version tested with: html2canvas 1.0.0-rc.5
 * Browser & version: Google Chrome & 78.0.3904.97(64)
 * Operating system: macOS Mojave(10.14)

**Comment by cloydlau** [comment]
Follow up on this

**Comment by MichaelDessureault** [comment]
Also would like a follow up on this
