### ISSUE TITLE
How can i save rotate image?

### ISSUE THREAD

**Issue by daochung** [niklasvh/html2canvas#209]
Hi everyone!
I have a question, can i save image has transform: rotate(23deg); ?
Many thanks

**Comment by jjoe64** [comment]
you can do a workaround which is told here:
http://www.jjoe64.com/2015/10/html2canvas-and-css-transform-rotate.html

**Comment by brcontainer** [comment]
Thanks by link @jjoe64 but does not make sense to html2canvas.

html2canvas is a lib for render (redraw) DOM elements (or fullpage) in canvas and no render canvas tag.

Your solution work only for one element with rotation.

**Comment by jjoe64** [comment]
yes it's not a solution that works perfect but it is a *workaround* for the problem, if you have to render rotated text or images. And for this use case it works perfectly in our project where we used it.

**Comment by Dayjo** [comment]
Guessing this still hasn't been looked at.

Kind of needed translateY to work for vertical aligning (would have hoped this would have been a simple implementation but obviously not). 

👍

**Comment by Drons2p** [comment]
How can i save div with  CSS transform: perspective ?
