### ISSUE TITLE
Unable to take screen shot of video playing

### ISSUE THREAD

**Issue by sadashivm** [niklasvh/html2canvas#2094]
Hello,
I want to take screen shot of playing video. But it is coming as blank, please find the attached file.
I have given ID attribute to the main container and playing video inside. May i missed anything?

`<div id="videoPlayer">`
`  <VideoPlayer />`
`</div>`

`const elem = document.querySelector('#videoPlayer');`
`      html2canvas(elem).then(canvas => {`
 `    const link = document.createElement('a');`
  `     link.download = 'screenshot.png';`
  `link.href = canvas.toDataURL();`
  `link.click();`
  `link.remove();`
` });`

![screenshot](https://user-images.githubusercontent.com/10355473/71185580-b92c7900-22a1-11ea-85b0-57f339cd168f.png)

Can you please help me , how to take screenshot of live video playing?

**Comment by orochitian** [comment]
我认为你的问题是无法解决的。
官方文档中说明了，这个插件并不是真正的截屏。
它是基于dom，通过canvas还原dom的一种操作。
视频的播放画面是无法获取的。

**Comment by unnown** [comment]
This library recreates all elements on a page, rendering a video will never be possible
