### ISSUE TITLE
border:dashed renders as solid

### ISSUE THREAD

**Issue by TryAgainLater** [niklasvh/html2canvas#210]
I'm using version 0.4 and all dashed borders are rendered as solid.

Tried your border test case (https://github.com/niklasvh/html2canvas/blob/master/tests/cases/border/dashed.html) and got the same result.

Tested in latest versions of FF/Chrome/Opera/IE.

**Comment by Zaccheo** [comment]
I Got the same problem.     <div class="pd10" style="border:4px dashed #B9BFD1;">   
dashed convert to solid style.  Please.

**Comment by lgellert** [comment]
Same problem here.

**Comment by brcontainer** [comment]
Maybe this link helps to create a pullrequest http://www.rgraph.net/blog/2013/january/html5-canvas-dashed-lines.html

**Comment by takien** [comment]
I have this problem too, using latest version

**Comment by Hemant-yadav** [comment]
[Changes.txt](https://github.com/niklasvh/html2canvas/files/114199/Changes.txt)


I have modified some functions. Now dashed and dotted lines are coming but when border is having a radius than its not rendering properly. Can use these modified functions if border is straight.

**Comment by Rodris** [comment]
Solved by drawing the borders myself, over the canvas returned by html2canvas.

Here are the steps:

1. Collect all border data in the HTML;
2. Remove the borders from the HTML, so the html2canvas wont draw them;
3. Call the html2canvas;
4. In the onrendered callback, draw the borders and restore the borders in the HTML.

Here is a [fiddle](https://jsfiddle.net/snu9xs73/).

**Comment by eKoopmans** [comment]
Nice @Rodris! Looks like a good solution as long as the borders are straight/rectangular.

I dug into the source code and worked out a way to fix things internally, see #1146. I haven't done too much testing but hopefully it solves the issue! You can grab a version of `html2canvas` with that merged in [here](https://github.com/eKoopmans/html2canvas/tree/develop/dist).

**Comment by agrawroh** [comment]
@eKoopmans Thanks for the fix! It works great for the dashed borders but now my images seems a bit chopped from the bottom. Is there a way to fix this?

**Comment by eKoopmans** [comment]
Can you give me an example?

**Comment by sadanandkenganal** [comment]
Hi @eKoopmans ,

Still border-radius is not working with latest release of html2canavs. I am using html2canvs in react app. Is there support for border-radious latest version ? Can you please suggest how to fix this ?

**Comment by animesh84** [comment]
same problem here "boder: 2px dashed #9b9b9b" converted into solid. did any one got answer?

**Comment by eKoopmans** [comment]
Hi, sorry the changes I spoke of in 2017 weren't merged. It would take someone reworking #1146 to work with the latest version of html2canvas.

**Comment by jasperplender** [comment]
Hi guys,

This is a dirty fix but I used this and it worked for me:

.whateveryouwant:before {
    content: "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _";
    letter-spacing: 4px;
}

**Comment by animesh84** [comment]
Thanks for your help. I will implement it.

**Comment by bUbUsHeD** [comment]
I have experienced a more severe version of this problem with none of the above solutions working.

In the end I solved the issue by simply making a <div> full of dashes and cycling through a lot of fonts until I found a font for which the dashes would be rendered.

**Comment by johnray016** [comment]
I encountered the same problem.

it took me a while to solve it, instead of using dashed border, I remove the border of the div. Then I add polyline SVG and act as a border. Then it fix my problem

**Comment by nguyenminhtien1411** [comment]
> I encountered the same problem.
> 
> it took me a while to solve it, instead of using dashed border, I remove the border of the div. Then I add polyline SVG and act as a border. Then it fix my problem

@johnray016 Nice it works. Thank you!
