### ISSUE TITLE
z-index is not considered

### ISSUE THREAD

**Issue by pupunzi** [niklasvh/html2canvas#2114]
- [x] I'm using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] I'm testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

It doesn't matter what is the z-index assigned to each dom element; the rendered image has the wrong elements' order.

You can see an example here: 
[https://www.open-lab.com/storyboarder/footballdrama/](https://www.open-lab.com/storyboarder/footballdrama/)
From the right column add different "sprites"; you'll see that the generated thumbnail is wrong. 
And if you save the image it will be more evident.

This is how it looks in the editor:
<img width="1356" alt="Schermata 2020-01-21 alle 11 07 31" src="https://user-images.githubusercontent.com/56659/72795711-5f232880-3c3e-11ea-8a4d-34c3cd93c606.png">

And this is the generated image:
![Board 0](https://user-images.githubusercontent.com/56659/72795833-909bf400-3c3e-11ea-8f2b-a6c0b4afdcb3.jpeg)

### Specifications:

 * html2canvas version tested with:  v1.0.0-rc.5
 * Browser & version: Chrome, Safari, Firefox, Opera (all latest versions)
 * Operating system: macOS 10.15.2

**Comment by unnown** [comment]
Your example links isn't using the latest version
also, z-index is honored as seen here: https://jsfiddle.net/d47nj31p/1/

**Comment by pupunzi** [comment]
Although the online version was not updated with the latest version of html2canvas (html2canvas-rc5.js), the test I did locally was done with the latest, but the result is the same. The z-index order is not correct.
I've now updated the online editor with the rc5 version and the problem is still there.

Here you can see a short screencast where the problem is evident:
https://open-lab.com/out/z-index-htmltocanvas.mp4

The code first convert the container to canvas using **htmltocanvas.js** then convert the canvas to jpg using **canvas2image.js**

Thank you,
Matteo

**Comment by unnown** [comment]
Ah yes that would be equal z-index, this PR should fix that #2089

**Comment by pupunzi** [comment]
I can confirm that it works setting a different z-index value for each element.
Thank you for the advice.
All the best,
Matteo
