### ISSUE TITLE
The latest version of html2canvas make wrong screenshots

### ISSUE THREAD

**Issue by Tholem98** [niklasvh/html2canvas#2119]
When I use the new version of html2canvas( http://html2canvas.hertzen.com/dist/html2canvas.min.js ) i obtain a bad screenshot, but if i use another version i obtain a good screenshot.
![imagen](https://user-images.githubusercontent.com/50252490/73595377-ce2e3600-44f6-11ea-8cca-99773ed670fd.png)
Like you can see in the example above, the image is posted down that it should be post, and the down part is cropped. (I let bigger to show that the image is cropped and don't start since the beggining)

the code:
`html2canvas(document.querySelector('#portaCanvas')).then(
                        canvas => {
                            let pdf = new jsPDF('p', 'mm',[8650,12900]); //10 times more to show that the image is cropped at the end
                            pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0); //the screenshot have a  blank space above
                            pdf.save(filename);
                        })`

![imagen](https://user-images.githubusercontent.com/50252490/73595392-00d82e80-44f7-11ea-8839-2da75d2e61d9.png)
When I use a version before it work good. (This have not space in blank around because it's not necessary)

the code:
`html2canvas(document.querySelector('#portaCanvas'),{
                    onrendered:
                        canvas => {
                            let pdf = new jsPDF('p', 'mm',[865,1290]);
                            pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0);
                            pdf.save(filename);
                        }
                });`

I need to use the new version to can scale it but i face to with this issue

**Comment by Tholem98** [comment]
I found that the position in the html page at the moment of press the button and the zoom of the browser change the canvas

**Comment by Tholem98** [comment]
Is the same issue that #117 #461 #622 #836 #837
All this fixes solve the problem on desktop but is different on mobile
https://github.com/niklasvh/html2canvas/issues/461#issuecomment-148715975

**Comment by VenkatSarvesh** [comment]
@Tholem98 I am also having the same issue with 1.0.0-rc.5 version. What version is giving the right screenshot?

**Comment by Tholem98** [comment]
@VenkatSarvesh The 0.4.1( https://cdnjs.com/libraries/html2canvas ), but in that version the attribute scale isn't supported. So, the screenshot is blurred and if there is images it look worst

**Comment by Grovkillen** [comment]
#2096 is probably also related. I made it work sometimes by flushing out my html code.

**Comment by Tholem98** [comment]
@Grovkillen I have no empty divs, but I have some divs commented, some modals, and some iframes of google adsense. I don't know if that could be causing problems. Do you know if the comment code, or hidden divs could make bugs?

**Comment by Grovkillen** [comment]
Yeah, I just tried and it seems like my fix isn't fixing the bug for my 100% of the time.

**Comment by Tholem98** [comment]
This look like it solve my problem
https://github.com/niklasvh/html2canvas/issues/1979#issuecomment-527775450

add a
`if(screen.width < 1024) {
        document.getElementById("viewport").setAttribute("content", "width=1200px");
    }`

To change the content of the viewport seems to work
