### ISSUE TITLE
html2canvas css problem.

### ISSUE THREAD

**Issue by q2a-html2canvas** [niklasvh/html2canvas#213]
hello,
I'm facing a problem. The plugin works fine with "img" tag, but fails to render image included by background:url() property via css. The problem is it takes the absolute path from the url() (for instance: localhost://folder/img/photo.jpg), but it should take the src as 'img/photo.jpg'. For the absolute path, the file is not found while it creates the canvas.

In css, image included- body{ background-image:url(../img/photo.jpg); }
Example of error:
http://localhost/folder/ "http://localhost/folder/img/photo.jpg".

On above, inside the double quotes, the path should be '/img/photo.jpg', but it takes the absolute path, which leads to "file not found" problem.

Any ideas how to solve this?

I guess this plugin has a BUG as it can't load the images included via CSS-background-url. HELP.

**Comment by fatemehgholampour** [comment]
@ostumpfs could you explain me what did you do at for this problem

**Comment by shannon-fluellen-aurea** [comment]
I've been researching the problem of using html2canvas to convert image elements with a src other than the current domain and haven't been able to find a solution. Is it just not possible to take images coming from another domain and convert them into a canvas? Is there no way around the CORS issue?

**Comment by ostumpfs** [comment]
I fixed it by loading the image via ajax and creating a new Image DOM
element from that source, like:

$.get(‘url to image’, function(response) {
 $(body).append($(‘</img >’).attr(‘src’, response));
});

**Comment by shannon-fluellen-aurea** [comment]
@ostumpfs I tried that and am still running into the same access control issues. It seems that the html2canvas can't draw an image that has a src value outside of the current domain. I'm already forming the image tag with the src attribute in the HTML that I need to convert to a canvas.

**Comment by ostumpfs** [comment]
Have you tried encoding to base64 and make a ‘load’ call on the image
element?

Maybe you can try by setting this attribute to the image:
image.crossOrigin = “Anonymous”

**Comment by shannon-fluellen-aurea** [comment]
> Have you tried encoding to base64 and make a ‘load’ call on the image element? Maybe you can try by setting this attribute to the image: image.crossOrigin = “Anonymous”
> […](#)

I still couldn't get it to work but I no longer need to explore this approach, thanks anyway for your help @ostumpfs !

**Comment by lmendoza27** [comment]
Dumb

**Comment by areeb90** [comment]
used html2canvas but cant able to include the inline css styling,  but it only includes the html content in the generating pdf.

tried many approaches using from jquerry but noting worked, also tried this way but still finds nothing
  html2canvas(xyz).then((canvas) => {
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF();
        pdf.addImage(imgData, 'PNG', 10, 10);
        pdf.save('sectionA.pdf');
    });

but the issue persists.
