### ISSUE TITLE
Why is my page so affected by scrollbars that I have to set it “ window.scrollTo(0, 0)” first?

### ISSUE THREAD

**Issue by zxflslzyx** [niklasvh/html2canvas#2173]
Firstly,I'm sure that I'm using the lastest version of html2canvas.

The reason why I'm writing this issue is that  I convert my web page's dom to canvas's base64 by html2canvas with blank space especially when I slide the page.

My solution is as the following:
   Before I convert web page's dom ,I set '   window.scrollTo(0, 0)' first, it seems to be solved perfectly, but I  can't understant it .

  May I have your answer about it? Of course, we will appreciate it very much if you can solve this issue,
   expect your early reply.
   Best wishes~

**Comment by zxflslzyx** [comment]
No replay,sir? Help me ,please!!!

**Comment by zxflslzyx** [comment]
Can you see my issue  ,guy.

**Comment by wayward-man** [comment]
why did you close the issue,?

**Comment by niklasvh** [comment]
Should be resolved with https://github.com/niklasvh/html2canvas/pull/2625
