### ISSUE TITLE
Tainted canvases may not be exported issue

### ISSUE THREAD

**Issue by gvsakhil** [niklasvh/html2canvas#2176]
I searched all over the google but none of the answers were working :(. I want to generate a pdf with some content on my page. I am using html2canvas and jspdf to acheive that, I am using s3 to store the images, added cors configuration to s3 but still I keep on getting the error:

`Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

I tried adding crossOrigin="anonymous" but it still didn't help me to get over this error

Here is my [jsfiddle](https://jsfiddle.net/gvsakhil/7s3myzto/11/)

You can check error in console of jsfiddle

https://i.stack.imgur.com/5IYPi.png

**Comment by yzkno1** [comment]
hi,I had the same problem。Have you solved it

**Comment by niklasvh** [comment]
This isn't related to html2canvas, but how canvas works in general. Drawing cross origin images will taint the canvas unless the images are loadable by that origin (just like with xhr)
