### ISSUE TITLE
html2canvas not wrapping text well in Safari

### ISSUE THREAD

**Issue by fds-github** [niklasvh/html2canvas#2177]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

As discussed on [StackExchange](https://stackoverflow.com/questions/60635788/html2canvas-not-wrapping-text-well-in-safari) text wrapping is not working correctly in either Catalina or iOS Safari, whereas it's fine in Chrome and Firefox.  [jsFiddle](https://jsfiddle.net/sferrari63/ykbc57u3/20/)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.5
 * Browser & version: Safari 13.0.5 and iOS Safari 13.3.1
 * Operating system: Catalina and iOS

**Comment by fds-github** [comment]
I tried to make some progress on this, and maybe this is all obvious to you, but:  It seems that Safari's getClientBoundingRect is returning the incorrect values to getRangeBounds in some cases.  For some words near the end of the line, the rectangle starts at the left side of the parent and includes two lines instead of one, as if the text is actually split across lines.  I was hoping that this was the problem solved by [this](https://github.com/edg2s/rangefix), but it doesn't seem to be.

In both Safari and Chrome I set a breakpoint when the rectangle for the text "Italy, " was being checked.  It should be entirely on the first line.  The first screenshot shows Safari reporting this incorrectly (and RangeFix not helping), the second shows Chrome reporting it correctly.
![image](https://user-images.githubusercontent.com/1485393/76437392-ca28ea00-63b9-11ea-990a-c5755df121c8.png)

![image](https://user-images.githubusercontent.com/1485393/76437900-8aaecd80-63ba-11ea-9411-88badc6ee9c9.png)

**Comment by fds-github** [comment]
I see that it is working correctly in Safari Technology Preview Release 102 WebKit 15610.1.5.2.  Perhaps this is related to "Fixed text string range from index and length in text controls when there are newlines" in Release 24.

Unfortunately, this doesn't help me and probably many others much, since I don't have any idea when this will come to iOS (where I need it), and I need to run on older versions of iOS.  It would be great if a work-around could be added to html2canvas, perhaps best by improving RangeFix to also fix this bug and having html2canvas use it.

**Comment by fds-github** [comment]
I notice that by changing testRangeBounds() to always return false, at least my test case seems to work for me.

- Is this harmless, except for perhaps a performance impact?
- Is there a better way for me to do this and simply editing my copy of html2canvas?  For example, should that routine perform a different test that detects this problem in Safari?

**Comment by niklasvh** [comment]
Quite late to this, so not sure if this is at all relevant to you anymore.

> Is this harmless, except for perhaps a performance impact?

Should be just a performance impact. However, due to this being a safari issue only that's not a fix I would be merging into here (if it resolves the issue for you, should be fairly harmless for you to apply that fix locally, but I'd limit it to safari browsers, through user agent sniffing etc). 

> Is there a better way for me to do this and simply editing my copy of html2canvas? For example, should that routine perform a different test that detects this problem in Safari?

The tests run on PRs in this repo do an image diff on all major browsers (including ios safari 12, 13, 14 and safari osx stable), which checks any rendering differences between what's in master and your PR.
