### ISSUE TITLE
 Arabic support  + scale/dpi  alongside with  JSpdf ?

### ISSUE THREAD

**Issue by mokmok55** [niklasvh/html2canvas#2185]
I can't find any version that supports Arabic + scale/dpi alongside with JSpdf  , always getting right arabic text but scale is not working , or rubbish arabic text with scale working fine , can you help please ?
![Untitled-2](https://user-images.githubusercontent.com/49613863/77078724-a68c2200-69ff-11ea-8733-47ff479a7361.jpg)

**Comment by MuizMahdi** [comment]
Hello, how did you solve this?
