### ISSUE TITLE
ios 系统中出现bug

### ISSUE THREAD

**Issue by davy-gan** [niklasvh/html2canvas#2200]
* html2canvas version tested with: rc.4
 * Browser & version: 微信浏览器
 * Operating system: 13.4
使用 rc.5根本不能绘制图片 

使用rc.4不能加载字体文件。导致字体图标都不能显示

**Comment by kingport** [comment]
rc.4 部分IOS系统也不能绘图

**Comment by jayaddison** [comment]
Maybe #1881 ?
