### ISSUE TITLE
this.canvas.ownerDocument is undefined

### ISSUE THREAD

**Issue by nassamkpela** [niklasvh/html2canvas#2241]
I encoutered this error when using html2canvas :
**this.canvas.ownerDocument is undefined**

Solved by changing this line :
--> `var canvas = this.canvas.ownerDocument.createElement('canvas');`
to
--> `var canvas = this.canvas.ownerDocument?this.canvas.ownerDocument.createElement('canvas'):document.createElement('canvas');`
in the source code at line 6587 of html2canvas.js latest version

**Comment by Yogoort** [comment]
I created fork and applied fix for this issue.
Here is fix: https://github.com/Yogoort/html2canvas/commit/061c6ecdb627c0b3dcc4cf895b9552a5706117dd

command for installing **forked html2canvas** package 
`npm install https://github.com/Yogoort/html2canvas/tarball/master`
