### ISSUE TITLE
Strange vertical offset after several renders

### ISSUE THREAD

**Issue by pcla56** [niklasvh/html2canvas#2244]
I am using V1 rc 5, on ubuntu 16.04, and firefox 76.0.1 (64-bit).
I can successfully render my canvas, post the base64 string to my server, and then retrieve it for another page and it all works fine. My first attached screenshot shows the successfully created canvas.
![Screenshot from 2020-05-26 13-35-00](https://user-images.githubusercontent.com/22328463/82902287-24682e80-9f57-11ea-8de2-e10c053a843d.png)
However, after several (random) attempts the canvas slips down the page and gets truncated. Its as if something is remaining on the previous canvas? My next screenshot shows the effect:
![Screenshot from 2020-05-26 13-37-34](https://user-images.githubusercontent.com/22328463/82902437-5bd6db00-9f57-11ea-8554-4ba0c3b9a73f.png)
I have spent days on this, trying to work out whether there are any js side effects, or modal creation problems and have run out of ideas!
I watch the console logging and without fail it "renders ok" (ie no errors. I can also see that the code correctly identifies differing heights and widths correctly.
I have also verified this behaviour on Chrome.
Please can someone have a look at this and possibly save my sanity?
Thx Paul
paul@vicjen.co.uk

**Comment by pcla56** [comment]
Dear Team - is there any chance someone can have a look at this?
Its such an elegant solution but I need it to be reliable please? Could it be something else happening in the browser that it causing the vertical shift?

**Comment by pcla56** [comment]
OK - clearly no-ones priority!
I have tried "removeContainer: true", but that didn't make any difference. The other thing I tried was defining my own canvas (so I could clean up the DOM) and make sure the next invocation was as clean as possible. But that didn't work either. The instructions are a little terse (or perhaps its just me) - when I specify my own canvas do I simply create an object or do I have to prepare it in some way (context?). Perhaps a few more pointers might help me to resolve. OR can you suggest a different tool I could use to create a canvas for my purposes? I dont think the native browser "scrrenshot" functions can be used from js? Well I'm no expert anyway .....

Helllllloooooooooooo.............

**Comment by saucylegs** [comment]
Happens to me as well

**Comment by Anubiso** [comment]
Can confirm,
happens in a cordova project, sometimes result is correct, sometimes there is a vertical offset.
![image](https://user-images.githubusercontent.com/7769367/84932440-93f3b880-b0d4-11ea-84cc-1521eaa94f5c.png)
![image](https://user-images.githubusercontent.com/7769367/84932505-ae2d9680-b0d4-11ea-8734-072a4bf25ca0.png)

**Comment by promotion-xu** [comment]
reset your scroll to the origin ,maybe could do this

**Comment by groenroos** [comment]
I had the same issue; resetting the scroll with `window.scrollTo(0, 0)` and/or temporarily setting the canvas to `position: fixed` before capture fixed this for me.

**Comment by pcla56** [comment]
Hi groenroos, I have tried the scrollTo option and its still not quite right. Could you explain a bit further about how you set the canvas to fixed please? There doesn't appear to be an option for that and I have tried creating my own canvas without success. I am so close and would be delighted to get this sorted!
Cheers

**Comment by groenroos** [comment]
@pcla56 Sure - it's quite simple. My code is something like so (where `#stage` is the container I want to turn into the canvas):

	let stage = document.getElementById("stage");
	stage.style.position = 'fixed';

	setTimeout(function(){
		html2canvas(stage).then(function(canvas) {
			// ...

			canvas.toBlob(function(blob: any){
				// ...

				stage.style.position = 'static';
			});
		});
	}, 1);

Essentially, I'm setting `position: fixed` in plain JS just prior to calling the plugin. I noticed I needed the 1ms timeout to wait for the browser to redraw before calling it.

Once I'm done with the canvas (converted to a file etc), I set the `position` back to `static` (or whatever it was before).

The side effect is of course that by setting the position to fixed, the page will reflow and elements might move around, but I found this to be a totally acceptable caveat in my use case.

Good luck!

**Comment by xr-hui** [comment]
@pcla56 It works! Thank you very much. By the way, it need to set `stage.style.left = 0` and `stage.style.top = 0` too in some cases.

**Comment by xr-hui** [comment]
@groenroos  It works! Thank you very much. By the way, it need to set `stage.style.left = 0` and `stage.style.top = 0` too in some cases.

**Comment by ahmedfeyzi** [comment]
> **I solved all possible problems as follows..**

```
html2canvas(element , {
        scrollX: -window.scrollX,
        scrollY: -window.scrollY,
        windowWidth: document.documentElement.offsetWidth,
        windowHeight: document.documentElement.offsetHeight
})
```

**Comment by GigaMick** [comment]
> > **I solved all possible problems as follows..**
> 
> ```
> html2canvas(element , {
>         scrollX: -window.scrollX,
>         scrollY: -window.scrollY,
>         windowWidth: document.documentElement.offsetWidth,
>         windowHeight: document.documentElement.offsetHeight
> })
> ```

Thank you X 100000

**Comment by pcla56** [comment]
Hi Team, I have been playing with this for a long time and *almost* have it working. The vertical offset is no longer a problem, and I finally fixed the canvas being truncated by inserting a 1s delay after rendering my bootstrap modal, before oding the html2canvas operation. My guess is the browser has to update the DOM completely to ensure it can try to render the canvas successfully. However, my last issue (and my initial post actually shows the problem) is that a jdenticon object (which we use for gender/ethnic neutrality) is getting distorted by html2canvas. I have tried both a svg and canvas construction for the graphic, and both seem to suffer the same result. I can live with it but would dearly like to get a better copy on my canvas. So the following images hopefully show the problem:
First the correctly rendered image
![image](https://user-images.githubusercontent.com/22328463/104134695-3e8a3c00-5383-11eb-971a-71bf7cb73ae2.png)
and then the squashed version
![image](https://user-images.githubusercontent.com/22328463/104134733-785b4280-5383-11eb-975b-e4dc24e33196.png)

If anyone has any suggestions I would love to hear them please?
Thx Paul
