### ISSUE TITLE
图片底部的阴影渲染不完全

### ISSUE THREAD

**Issue by Dinert** [niklasvh/html2canvas#2253]
导出的图片
![1591611941(1)](https://user-images.githubusercontent.com/35824497/84020498-7d06e500-a9b5-11ea-979c-880518955344.jpg)
原图
![Uploading 2020年AQI日历 (16).jpeg…]()

**Comment by xt2018** [comment]
Please speak English 
我看不到你上传的图片，不知道是什么效果

**Comment by pengdingkan** [comment]
![1](https://user-images.githubusercontent.com/35824497/84479498-a087a380-acc5-11ea-8d61-3dc3d8fa3864.png)

**Comment by pengdingkan** [comment]
Did you see it? The lowest shadow

**Comment by mgsod** [comment]
前两天也遇到这个问题(也看到了这个issues)
当一个容器底部box-shadow触碰到canvas画布底部时,底部阴影会被拉长.
截图前:

![before](https://ae01.alicdn.com/kf/H0d20473dcc534a399baaad9ff4efd14fh.jpg)

截图后

![after](https://ae01.alicdn.com/kf/H03af0ffdc8754ad9887c0717f48d99707.jpg);

多次尝试发现如果阴影不碰到canvas画布底部是不会出现这种情况的

所以我目前的解决方案是,先将画布高度拉长,然后截图,最后再把画布缩小

代码如下:

```js
	// 创建一个较大的canvas
	let bigCanvas = document.createElement('canvas');
	// 因为我的画布很高,所以+2000,这里可以随意,只要加上让拉长阴影的高度即可
	bigCanvas.height = dashboard_canvas.offsetHeight + 2000;
	bigCanvas.width = dashboard_canvas.offsetWidth;
	html2canvas(document.getElementById('container'), {canvas: bigCanvas}).then(canvas => {						
        let ctx = canvas.getContext('2d');
        // copy一下原有画布信息
        let imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        // 高度 - 2000 上面加上的高度
        canvas.height = canvas.height - 20000;
        // 再画上去
        ctx.putImageData(imgData, 0, 0);                        
	let imgUrl = canvas.toDataURL();						
    });
```

**Comment by pengdingkan** [comment]
好的，谢谢！解决了
