### ISSUE TITLE
svg elements do not render

### ISSUE THREAD

**Issue by saucylegs** [niklasvh/html2canvas#2255]
### Bug reports:

\<svg\> elements do not seem to render at all. Not on my website, not on the html2canvas website either.

### Specifications:

 * html2canvas version tested with:
 * Browser: Chrome, Firefox 
 * Operating system: Windows 10

**Comment by comparlimage** [comment]
Hello !
it could be work if you substitute the svg width % for px
var widthv = ($(svg).width()); // return value in px
var heightv = ($(svg).height()); // return value in px
$(svg).attr('width', widthv).attr('height', heightv);

But I don't find any solution for svg charged as img. not inline.
If you have any solution ? or found alternative ???
Chris

**Comment by saucylegs** [comment]
#2583 fixes this issue
