### ISSUE TITLE
Renders get offset/cut off

### ISSUE THREAD

**Issue by saucylegs** [niklasvh/html2canvas#2264]
Latest version. Renders get offset/cut off. This seems to change from platform to platform; the content gets shifted to the right on my desktop, and shifted up on my phone. I've played around with the options a bit, but nothing I did really fixed the problem.
![html2canvas report 1](https://user-images.githubusercontent.com/37064488/84564694-68f61700-ad18-11ea-962f-f0c0bd30d910.png)

**Comment by mnedelkoski** [comment]
I got the same issue except that the offset/cut off is on the left side of the rendered image. It happens randomly, meaning it might happen 10 times in a row and than not occur the next 20 times and that be on and off for the next x times. Also, the scroll to top fix did not work.

**Comment by shanggqm** [comment]
I got the same issue with you @mnedelkoski ，Have you solved this problem?
