### ISSUE TITLE
向左偏移

### ISSUE THREAD

**Issue by shirley-mm** [niklasvh/html2canvas#2265]
我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津

**Comment by isszz** [comment]
试试加这2个参数
`{scrollX: 0,scrollY: 0}`

**Comment by polliaC** [comment]
我也有这个问题，请问你解决了么

**Comment by geasscai** [comment]
我也有这个问题，本地截图正确,测试环境每次重新生成都会随机偏移,截图不全,试过1.0.0-rc.0,   1.0.0-rc.1   1.0.0-rc.5, {scrollX: 0,scrollY: 0} 都没效果

**Comment by geasscai** [comment]
> 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津

找到问题了,是因为我要截的图在popup层内,而popup层用了css:transform是不支持的.
我的解决方式是自己实现一个弹出层,不使用transform

**Comment by ZZsimon** [comment]
我也遇到了这个问题，解决办法和楼上的一样。 

因为使用了css:transform实现水平垂直居中导致设置 scrollX 无效。 使用其他的css样式就正常了

**Comment by shiguangpaoqini** [comment]
外层的css:transform影响，我在dom最外层clone节点绘制，解决了问题。

**Comment by zetanvi** [comment]
> 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津

请问，找到解决方法了么？

**Comment by Peizy** [comment]
我也遇到了这个问题，最后发现是整个项目的layout组件里面，有一个组件用了transition属性影响了，在下载的时候把这个属性覆盖掉，下好了再恢复，就解决这个问题了

**Comment by haohaoEe** [comment]
> transition

请问如何覆盖transition属性

**Comment by zongpengz** [comment]
> 我也遇到了这个问题，最后发现是整个项目的layout组件里面，有一个组件用了transition属性影响了，在下载的时候把这个属性覆盖掉，下好了再恢复，就解决这个问题了
感谢！确实外层的transition会导致向左偏移。奇怪的是本地开发环境不会出现，打包上线后才出现

**Comment by zongpengz** [comment]
> 我也遇到了这个问题，最后发现是整个项目的layout组件里面，有一个组件用了transition属性影响了，在下载的时候把这个属性覆盖掉，下好了再恢复，就解决这个问题了

感谢！确实外层的transition会导致此问题。奇怪的是打包上线后才会出现，本地开发环境不存在这个问题。

**Comment by cuiyiming1998** [comment]
可能是使用了不支持的css3样式导致的，可以在调用方法前，将要截图的dom复制一份插入到body里，display设置成none，在调用完后再删除。就能解决了

**Comment by lijin1111** [comment]
> 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津

这个解决了吗？

**Comment by lijin1111** [comment]
> > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> 
> 一样，找到解决方法了么？

解决了吗？

**Comment by cuiyiming1998** [comment]
> > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > 
> > 
> > 一样，找到解决方法了么？
> 
> 解决了吗？

是不是有transition 看一下

**Comment by lijin1111** [comment]
> > > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > > 
> > > 
> > > ，找到解决方法了么？
> > 
> > 
> > 解决了吗？
> 
> 是不是有过渡 看一下

没有transition  本地都没有问题 测试环境左偏移

**Comment by lijin1111** [comment]
> > > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > > 
> > > 
> > > 一样，找到解决方法了么？
> > 
> > 
> > 解决了吗？
> 
> 是不是有transition 看一下

![image](https://user-images.githubusercontent.com/67891438/126476459-fc51e3e3-10d5-453a-b19d-49060405f142.png)
![image](https://user-images.githubusercontent.com/67891438/126476511-54190b08-bc2f-410e-834e-af5a00cfd47e.png)
这是样式

**Comment by cuiyiming1998** [comment]
> > > > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > > > 
> > > > 
> > > > ，找到解决方法了么？
> > > 
> > > 
> > > 解决了吗？
> > 
> > 
> > 是不是有过渡 看一下
> 
> 没有transition 本地都没有问题 测试环境左偏移

我之前是因为 页面切换的时候会有一个过渡动画 在转canvas的时候 过渡动画没有完成，所以偏移了

**Comment by zongpengz** [comment]
> > > > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > > > 
> > > > 
> > > > 一样，找到解决方法了么？
> > > 
> > > 
> > > 解决了吗？
> > 
> > 
> > 是不是有transition 看一下
> 
> ![image](https://user-images.githubusercontent.com/67891438/126476459-fc51e3e3-10d5-453a-b19d-49060405f142.png)
> ![image](https://user-images.githubusercontent.com/67891438/126476511-54190b08-bc2f-410e-834e-af5a00cfd47e.png)
> 这是样式

看看外层父级有没有过渡动画，我之前是这个原因导致的。

**Comment by lijin1111** [comment]
> > > > > > 我截图本地正确，测试环境向左偏移，截图不全，完全没找到解决思路，求大佬指点迷津
> > > > > 
> > > > > 
> > > > > 一样，找到解决方法了么？
> > > > 
> > > > 
> > > > 解决了吗？
> > > 
> > > 
> > > 是不是有transition 看一下
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/67891438/126476459-fc51e3e3-10d5-453a-b19d-49060405f142.png)
> > ![image](https://user-images.githubusercontent.com/67891438/126476511-54190b08-bc2f-410e-834e-af5a00cfd47e.png)
> > 这是样式
> 
> 看看外层父级有没有过渡动画，我之前是这个原因导致的。

最外层有
![image](https://user-images.githubusercontent.com/67891438/126477374-10fbd7b4-275e-4490-b938-3ad7c227d538.png)
