### ISSUE TITLE
Arabic words with no spacing

### ISSUE THREAD

**Issue by MuizMahdi** [niklasvh/html2canvas#2271]
### Bug reports:
Using html2canvas messes up the spacing between Arabic words as you could see in this [JSFiddle](https://jsfiddle.net/r3zL624f/).
Note: html2canvas 0.4.1 works, but the quality isn't good enough, since v1.0.0 has the Scale option.

### Specifications:

 * html2canvas version tested with: v1.0.0-rc.5
 * Browser & version: Firefox v77.0.1 - Google Chrome v83.0.4103.116
 * Operating system: Windows 10

**Comment by mhasnainraza001** [comment]
@niklasvh I am also facing issue with Arabic. The last two words lose space between them. I have tried 0.5.0 but that version has quality issue and result is of poor quality.

**Comment by MuizMahdi** [comment]
> @niklasvh I am also facing issue with Arabic. The last two words lose space between them. I have tried 0.5.0 but that version has quality issue and result is of poor quality.

You need to scale up the canvas, check my previous comment

**Comment by mhasnainraza001** [comment]
@MuizMahdi  unfortunately I can't. I want this fix in latest without scaling the content. Reason is that we already have input control with default font size. If we scale than size of default font size increases. 

Any plan for this fix in future?

![image](https://user-images.githubusercontent.com/73573808/97539984-c0093980-19e4-11eb-9c12-ddcc0c7b41b2.png)

**Comment by BKDzTV** [comment]
> @MuizMahdi unfortunately I can't. I want this fix in latest without scaling the content. Reason is that we already have input control with default font size. If we scale than size of default font size increases.
> 
> Any plan for this fix in future?
> 
> ![image](https://user-images.githubusercontent.com/73573808/97539984-c0093980-19e4-11eb-9c12-ddcc0c7b41b2.png)

Did you figure this out?

**Comment by mhasnainraza001** [comment]
> > @MuizMahdi unfortunately I can't. I want this fix in latest without scaling the content. Reason is that we already have input control with default font size. If we scale than size of default font size increases.
> > Any plan for this fix in future?
> > ![image](https://user-images.githubusercontent.com/73573808/97539984-c0093980-19e4-11eb-9c12-ddcc0c7b41b2.png)
> 
> Did you figure this out?

No still no update.

**Comment by mhasnainraza001** [comment]
@niklasvh need update on this issue because, its affecting the use case.

**Comment by ghonchesefidi** [comment]
![image](https://user-images.githubusercontent.com/30124243/124131508-1e674a00-da95-11eb-851e-30e474150630.png)
I have the same problem.
