### ISSUE TITLE
fuck  It's been killing me for two days 

### ISSUE THREAD

**Issue by wdcsoul** [niklasvh/html2canvas#2277]
Recommended ：  https://github.com/tsayen/dom-to-image

**Comment by mehmetyagci** [comment]
> Recommended ： https://github.com/tsayen/dom-to-image

me too, but I used the old version.  
It seems OK.

**Comment by cloud1250x4** [comment]
what happened? i fixed a weird export problem by changing the content of 
`'onclone': function (cloneDoc)`
to 
`$(cloneDoc).css('transform', '');`

**Comment by niklasvh** [comment]
Happy that you found a solution

**Comment by wy1009** [comment]
So rude.

**Comment by gudblkd** [comment]
Sup
