### ISSUE TITLE
html2canvas printing previous render

### ISSUE THREAD

**Issue by ocaiquemello** [niklasvh/html2canvas#2283]
- [ X] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ X] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I'd like to html2canvas print the div when user adds something. My application has an post-it system just like Trello and I'd like to show some preview to the user. But when the user adds an post-it, it's not printed, but what's been printed is the previous render, without the new post-it...

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.5
 * Browser & version: Opera latest version, Firefox latest version and Chrome latest version
 * Operating system: Windows 10 pro

**Comment by ocaiquemello** [comment]
Solved. At the end of the day, it was only cache.... :(

**Comment by Modestiny** [comment]
i know that it was only cache; but  in case of using in mobile; how can i solve it; there is no control of disable cache in console panel like pc；
