### ISSUE TITLE
Proxy cannot process multiple images

### ISSUE THREAD

**Issue by Wmmmeng** [niklasvh/html2canvas#2291]
### Bug reports:

Proxy is the only one. I need to draw multiple images in my project.
In ie10, cross domain images cannot be drawn (useCORS: true), so I use the proxy, but the proxy can only draw one image.

`xhr.open('GET', proxy + "?url=" + encodeURIComponent(src) + "&responseType=" + responseType);`

I want to request multiple images, or can the proxy be the same as ‘src’?
Because I can see that as long as the proxy is set, each image will trigger. Do different images have different proxies?

### Specifications:

 * html2canvas version tested with:  1.0.0-rc.5
 * Browser & version: IE10
 * Operating system: Windows

**Comment by niklasvh** [comment]
The request image is in the query param `encodeURIComponent(src)`
