### ISSUE TITLE
Text Overlapped

### ISSUE THREAD

**Issue by deshario** [niklasvh/html2canvas#2298]
### ** It's my modal and I render modal-content into canvas**

<img width="964" alt="modal" src="https://user-images.githubusercontent.com/11426727/88451616-38aaa800-ce82-11ea-9c2f-b6a0c953f619.png">

--------------------
### **It's my exported image and it overlapped in line 10. I'm not sure why**
--------------------

<img width="964" alt="overlapped" src="https://user-images.githubusercontent.com/11426727/88451621-4829f100-ce82-11ea-9af5-bd81aa3b1abf.png">

### **Is there any solution to this! #Thanks**

**Comment by duyhung85** [comment]
Hi, 
I experience the same bug. It's not happening all the time though, sometime text gets overlap, sometime text of first line replace the text of second line. 
I'm not sure if its only happening for foreign language utf-8 characters or English also.
Any way we can fix this? Thanks

**Comment by wufeng87** [comment]
try set `word-break: break-all` to the child

**Comment by Raj-kishore** [comment]
> try set `word-break: break-all` to the child

Thanks dude. It works.
