### ISSUE TITLE
html2canvas not working in mobile devices

### ISSUE THREAD

**Issue by DigiAsus** [niklasvh/html2canvas#2301]
Hello devs o/

 I'm having a problem at the exact moment I call html2canvas via javascript, it works on some mobile devices and when it works it creates an extra white border, but on my iPhone it doesn't work. It does not give any error in the console, for the simple fact that it does not perform. Can you tell me if html2canvas is already in a stable version that works on all devices

**Comment by niklasvh** [comment]
Can you share a repro on jsfiddle?
