### ISSUE TITLE
Image with loading attribute as "lazy" not shown in Firefox

### ISSUE THREAD

**Issue by frandemona** [niklasvh/html2canvas#2312]
### Bug reports:

I've been trying to get images to show on Firefox and found out that if the img has a loading attribute with lazy it will not show in the canvas as shown in this [jsfiddle](https://jsfiddle.net/sj4Lo08c/).

It's not a problem of the library per se, just wanted to explain it here for anyone who has been having the same problem as us, because I suppose lots of developers will be adding this new attribute for optimization of their sites :)

### Specifications:

 * html2canvas version tested with: vtest2 
 * Browser & version: Firefox 79.0
 * Operating system: Ubuntu 18.04 & Mac OS Catalina

**Comment by niklasvh** [comment]
Thanks for the repro! I was able to verify this not working as intended as well.

**Comment by lili21** [comment]
Run into the similar issue with safari 15.5. 

the canvas generator just keep pending. the promise never fulfilled.
