### ISSUE TITLE
Capturing only the first section, not including the near sections

### ISSUE THREAD

**Issue by raja2raj02** [niklasvh/html2canvas#2318]
In my angular application, dashboard widgets are loading dynamically and using html2canvas i am trying to capture, but it captures  the first widget only and others are omitted. Is it known issue or is there any work around? Adding images below. 
![Dashbord](https://user-images.githubusercontent.com/22573352/89707186-88609780-d989-11ea-97ee-902988481f03.png)
![Dashbord_pdf](https://user-images.githubusercontent.com/22573352/89707225-e1303000-d989-11ea-8965-5ff098ab5014.png)

**Comment by niklasvh** [comment]
Please share a repro on jsfiddle
