### ISSUE TITLE
Options being ignored

### ISSUE THREAD

**Issue by MestreKarin** [niklasvh/html2canvas#2323]
My code:

![image](https://user-images.githubusercontent.com/19618186/89957802-befb1400-dc0e-11ea-8e96-82b037a4cb8a.png)

My console output:

![image](https://user-images.githubusercontent.com/19618186/89957838-d89c5b80-dc0e-11ea-92ce-7a1f86c1dd1a.png)

Rendered image size:

![image](https://user-images.githubusercontent.com/19618186/89957871-f49ffd00-dc0e-11ea-9ccd-208f8b572414.png)

It looks like it's ignoring the entire options object (since it's not logging). It's weird, when I use on jsfiddle, it works.

**html2canvas version**: ^1.0.0-rc.7
**Browser**: Opera 70.0.3728.95
**OS**: Windows 10

**Comment by niklasvh** [comment]
You presumably are on a `scale: 3` (it defaults to `devicePixelRatio`)
