### ISSUE TITLE
Div with Nested div and svg

### ISSUE THREAD

**Issue by JamesHandshoe** [niklasvh/html2canvas#2326]
### Bug reports:
Version 1.0.0-rc.7

Issue: I was using @latest from unpkg and got bumped to 1.0.0-rc.7 and had an issue with an app.  I'm using React and iframing in another app that has a div with a nested div and svg.  When trying to target the SVG to convert to a dataUrl, I was getting unable to find element in cloned iframe in the catch from the html2canvas promise.  Rolling back to 1.0.0-rc.7 fixed this issue for me.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Chrome - 84.0.4147.105 
 * Operating system: iOS Catalina 10.15.6

**Comment by niklasvh** [comment]
> Rolling back to 1.0.0-rc.7 fixed this issue for me.

Which version did you rollback to?

Would you be able to create a small repro of the issue on jsfiddle?

**Comment by yyISACoder** [comment]
> > Rolling back to 1.0.0-rc.7 fixed this issue for me.
> 
> Which version did you rollback to?
> 
> Would you be able to create a small repro of the issue on jsfiddle?

i encountered the same problem, i rolled back to 1.0.0-rc.6 and solved this problem,hope solve it as soon as possible
good luck to u ^-^
