### ISSUE TITLE
生成的图片是空白

### ISSUE THREAD

**Issue by hyl1374961656** [niklasvh/html2canvas#2334]
"html2canvas": "^1.0.0-rc.7"

图片成功生成，但是图片没有内容，只是一张白图，不涉及任何跨域  

页面
<div className="csbox">
    111111111111111
    <div onClick={this.exportImage}>
        提交
    </div>
</div>

**Comment by xiaoFeng5210** [comment]
同样是这个问题

**Comment by hyl1374961656** [comment]
> 同样是这个问题

你可以尝试把页面的样式注释下再使用，我的问题是iframe样式影响了生成的图片

**Comment by xiaoFeng5210** [comment]
我是无论截取文字还是图片拿到todataurl的时候去测试  都是一张白图。。我去试试 注释掉

**Comment by hyl1374961656** [comment]
> 我是无论截取文字还是图片拿到todataurl的时候去测试 都是一张白图。。我去试试 注释掉

你还可以尝试调整一下options的参数，我在使用时布局用了很多的{ ? : }导致生成的图片内容偏移问题，也是最后慢慢调整的

**Comment by dfz-dfz** [comment]
> > 我是无论截取文字还是图片拿到todataurl的时候去测试 都是一张白图。。我去试试 注释掉
> 
> 你还可以尝试调整一下options的参数，我在使用时布局用了很多的{ ? : }导致生成的图片内容偏移问题，也是最后慢慢调整的

是怎么解决生成图片空白的问题的，我怎么样尝试生成的图片都是空白的
