### ISSUE TITLE
image missing in Safari

### ISSUE THREAD

**Issue by wengcan** [niklasvh/html2canvas#2343]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

if invoke the html2canvas function immediately after the page loaded, some image will be missing in the screenshot

[codesandbox](https://2clrb.csb.app)

![Simulator Screen Shot - iPhone 11 - 2020-09-06 at 23 33 51](https://user-images.githubusercontent.com/4007458/92329456-1cfa0a80-f09a-11ea-9dda-ecb008459aef.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Safari
 * Operating system: iOS (13.6)

**Comment by wengcan** [comment]
![微信截图_20200906234656](https://user-images.githubusercontent.com/4007458/92329641-4cf5dd80-f09b-11ea-8cbb-73c3df9685e6.png)


in Safari, the contentBox size  maybe not correct when the image not fully loaded, so the image elements would not render correctly in the canvas.

**Comment by niklasvh** [comment]
This is working as intended - it is rendering what the state of the page is at the time html2canvas is called
