### ISSUE TITLE
Can not create the image of the DIV element

### ISSUE THREAD

**Issue by r4surfer** [niklasvh/html2canvas#235]
$(document).ready(function () {
            html2canvas($('.dvImageToSave'), {
                onrendered: function (canvas) {  
                    var img = canvas.toDataURL()
                    window.open(img);
                }
            });
        });

In above code there is a div with class dvImageToSave and I want to capture the image of that DIV element. But Now I'm getting this error :

Timestamp: 27-Jun-13 6:13:47 PM
Error: IndexSizeError: Index or size is negative or greater than the allowed amount
Source File: http://localhost/blablabla/html2canvas/build/html2canvas.js
Line: 2832

BUT this code works fine for the document.body element.
This is strange.!

**Comment by Satyajit143** [comment]
I used this libary and code . It  Works on my first server but when I put it on second serve it does not create the image...

after inspect element the result is 
 <div class="satyajit">
<canvas width="183" height="225"></canvas>
</div>... but there is a blank image...

<script type="text/javascript" src="<?php echo esc_url( get_template_directory_uri() ); ?>/js/html2img/html2canvas.js"></script>

$(document).ready(function(){  
var element = $(".img-main-one-rtop"); // global variable
var getCanvas; // global variable
   $(".img-main-one-rtop").on('click', function () {
      
      $(".satyajit canvas").remove();
         html2canvas(element, {
         onrendered: function (canvas) {
                $(".satyajit").append(canvas);
                getCanvas = canvas;
             }
         });
    });
});

**Comment by brcontainer** [comment]
@Satyajit143 It does not look like a **bug**, it seems difficult to use the library, I recommend you ask here:

http://stackoverflow.com/questions/ask?tags=html2canvas

**Comment by Satyajit143** [comment]
thank u

**Comment by Satyajit143** [comment]
@brcontainer 
Previous code work on our server but it does not work on client server. 
Is there any server related issue or else?
Please help

**Comment by brcontainer** [comment]
@Satyajit143 Clearly is a problem in your specific code or with your server and not a bug. Please direct your question to http://stackoverflow.com/questions/ask?tags=html2canvas
