### ISSUE TITLE
The rendered text has an error offset 

### ISSUE THREAD

**Issue by kooriookami** [niklasvh/html2canvas#2354]
![image](https://user-images.githubusercontent.com/38392315/93192526-586e9600-f778-11ea-8911-272c853854d9.png)
![image](https://user-images.githubusercontent.com/38392315/93192538-5c021d00-f778-11ea-89ef-9f8b3b6d4fd2.png)
First original image is correct, second rendered image has an error offset. It happens in some font-family

**Comment by 7revor** [comment]
If you loaded fonts by JavaScript, add thoose to iframe document during onclone hook.

**Comment by kooriookami** [comment]
> If you loaded fonts by JavaScript, add thoose to iframe document during onclone hook.
> 
> ```js
> const fonts = document.fonts;
> html2canvas(target, {
>   onclone: (document) => fonts.forEach(font => document.fonts.add(font));
> }
> ```

Thank, but it is useless. I guess it can be the baseline problem.

**Comment by 7revor** [comment]
Look this:[issue#2107](https://github.com/niklasvh/html2canvas/issues/2107)

both ideographic textBaseline and adjust text’ top work for me

**Comment by 7revor** [comment]
> > If you loaded fonts by JavaScript, add thoose to iframe document during onclone hook.
> > ```js
> > const fonts = document.fonts;
> > html2canvas(target, {
> >   onclone: (document) => fonts.forEach(font => document.fonts.add(font));
> > }
> > ```
> 
> Thank, but it is useless. I guess it can be the baseline problem.

Look this:[issue#2107](https://github.com/niklasvh/html2canvas/issues/2107)

both ideographic textBaseline and adjust text nodes’s top work for me

**Comment by kooriookami** [comment]
My fool way is to adjust the offset manually.
```js
html2canvas(element, {
                    onclone: (doc) => {
                        let dom= doc.querySelector('.dom');
                        if (dom) {
                            dom.style.top = '100px';
                        }
                    }
                })
```
