### ISSUE TITLE
'webgl' context still not working

### ISSUE THREAD

**Issue by ChenGuanglin0924** [niklasvh/html2canvas#2362]
When I use html2canvas to parse canvas with 'webgl' or 'webgl2' context, the generated image is empty.

**Comment by Kriticals** [comment]
It's possible that WebGL cleared your canvas' buffer before html2canvas can access it. Try to use the WebGLContextAttribute `preserveDrawingBuffer = true`. Note that you'll have to clear the buffer yourself before rendering the next frame then, if necessary.

Another way could be to take the screenshot exactly after rendering. So exactly after each other
`renderToCanvas()`
`takeScreenshot()`

**Comment by MyShallowTime** [comment]
![image](https://user-images.githubusercontent.com/20198963/97130868-94d0e100-177d-11eb-8fef-11e6ea495f4f.png)
Canvas generated by third-party plugins with 'webgl2' context, the generated image is empty.
