### ISSUE TITLE
An issue with Arabic punctuation marks

### ISSUE THREAD

**Issue by naseemln** [niklasvh/html2canvas#2369]
There is an issue with the Arabic punctuation mark, as its location is incorrect, as in the following picture:
[https://imgur.com/AsYfDej](url)
orignal text
`قال الله تعالى: { أَفَحَسِبْتُمْ أَنَّمَا خَلَقْنَاكُمْ عَبَثًا وَأَنَّكُمْ إِلَيْنَا لَا تُرْجَعُونَ ﴿١١٥﴾ فَتَعَالَى اللَّهُ الْمَلِكُ الْحَقُّ ۖ لَا إِلَٰهَ إِلَّا هُوَ رَبُّ الْعَرْشِ الْكَرِيمِ ﴿١١٦﴾ وَمَن يَدْعُ مَعَ اللَّهِ إِلَٰهًا آخَرَ لَا بُرْهَانَ لَهُ بِهِ فَإِنَّمَا حِسَابُهُ عِندَ رَبِّهِ ۚ إِنَّهُ لَا يُفْلِحُ الْكَافِرُونَ ﴿١١٧﴾ وَقُل رَّبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ ﴿١١٨﴾ }صدق الله العظيم [المؤمنون].`

**Comment by naseemln** [comment]
☹️

**Comment by evisat** [comment]
I am having a similar issue, Does anyone have a fix for this?

**Comment by naseemln** [comment]
Fixed
