### ISSUE TITLE
Empty screen on mobile

### ISSUE THREAD

**Issue by Polm90** [niklasvh/html2canvas#238]
I've tried your library and I've created a script using it. It works properly when I use it from a desktop browser; when I try it from a mobile browser (in Android or iOs) it doesn't.
In particular, it usually makes an empty screen or without some parts.

I've also tried you examples (http://html2canvas.hertzen.com/examples.html) but they don't work properly: in the rendered images, there are not texts and some images.

I hope you can help me as quickly as you can, because I really need it works :)

Thank you

**Comment by sjamaan** [comment]
Maybe you're running into issue #333

**Comment by usmonster** [comment]
Maybe fixed in 98ee306 ?

**Comment by ragefuljoe** [comment]
I'm running into this issue on iPhone only. iPad works, and chrome/safari/ff on desktop all work. I drawImage using the returned canvas and on iPhone it's just blank. checked that I have the latest 0.5 alpha2.

**Comment by Polm90** [comment]
Looks like last version (the alpha-1) doesn't have the bug

**Comment by ragefuljoe** [comment]
I've tried with both alpha1 and alpha2, both exhibit similar blank behavior on an iphone6. If the div I pass to html2canvas is wide than the device width, I get blank result. Interestingly, if I set the width to 750 (the width of iphone in portrait) then run the export with phone in landscape, everything works fine.

**Comment by utsavanand** [comment]
Same issue here. The complete image doesn't get rendered on iOS. Some parts get missed. Is there any workaround for this?

**Comment by Ojes** [comment]
i have the same issue in Ipad and Android 4.2.1

**Comment by grjones123** [comment]
I have same problem. I can get html2canvas snapshot of an img on wifi. As soon as I switch on to cellular network - blank canvas. This is an iphone5s on 4g.
Am currently using the 050 alpha1 ver
Gary

**Comment by yesvods** [comment]
I have same problem in Android4.2.2 .

**Comment by andreasvirkus** [comment]
@yesvods I had the same issue on iOS Chrome and Safari - what worked for me was downgrading to `1.0.0-rc.1`, see this issue for more info: https://github.com/niklasvh/html2canvas/issues/1900#issuecomment-504422179

**Comment by nwestendorf** [comment]
I ran into the same problem on certain device & browser combinations.
To resolve this, before running html2canvas on the given div, I use JS to assign it a special class.  In my CSS file, I make the special css class position fixed, top 0, left 0, height 100%, width 100%, z-index 9999, background-color white (or whatever is appropriate for your app).

Afterwards, I remove the class.  Your specific needs may vary, but that pops the div above everything else and at the top of the page.  In my experience, the blank images or incomplete images have to do with your scroll position at the time of the screenshot.
