### ISSUE TITLE
ios手机显示截图的图片伪元素没有生效，安卓手机是正常的

### ISSUE THREAD

**Issue by xiaoxiaoyisheng** [niklasvh/html2canvas#2383]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports: ios手机显示截图的图片伪元素没有生效，安卓手机是正常的，微信浏览器直接生成不了

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system: ios13.6

**Comment by Leekiwi** [comment]
啊啊啊,我也遇到了,后续呢?
