### ISSUE TITLE
Image cut from the top

### ISSUE THREAD

**Issue by gaik04** [niklasvh/html2canvas#2386]
I am creating a multi page PDF from html using jspdf and html2canvas but my image is getting cut off little from top side. I tried all possible solutions from different forums but no success. below is the code

var data = document.getElementsByClassName('divtocapture');
for(let content=0;content<data.length;content++)
{
html2canvas(data[content] as HTMLElement,{scale: 2,width:1150,scrollX: 0,scrollY: 0, allowTaint: true, backgroundColor: '#fff'}).then(canvas => {
var imgWidth = pdf.internal.pageSize.getWidth()
var imgHeight = canvas.height * imgWidth / canvas.width;
const contentDataURL = canvas.toDataURL('image/JPEG',1.0)
pdf.addImage(contentDataURL, 'JPEG', 5, 10, imgWidth, imgHeight)
pdf.save('mypdf.pdf');
})
}

I have tried with pdf.addImage(contentDataURL, 'JPEG', 0, 0, imgWidth, imgHeight) but facing same issue after 3rd page.
Tried with multiple versions of Hhml2Canvas. using current version  1.0.0-rc.7

**Comment by NurulAlomAdor** [comment]
You can try by using ```scrollX: -window.scrollX``` and ```scrollY: -window.scrollY``` instead of 0

**Comment by nikolaynikolaevn** [comment]
I am also having an issue with exported images being cropped (the canvas moved away to the right and bottom).

**Comment by gaik04** [comment]
> scrollY: -window.scrollY

Still the same result

**Comment by IhorKobylinskiy** [comment]
> > scrollY: -window.scrollY
> 
> Still the same result

And for me too

**Comment by ivanmayes** [comment]
Same result

**Comment by YoujeongPark** [comment]
same result
