### ISSUE TITLE
Salesforce Marketing Cloud Cloudpages No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by ellier7** [niklasvh/html2canvas#2394]
I am using html2canvas on Salesforce Marketing Cloud Cloudpages Landing Page and receiving the issue:
_Access to image at <src> from origin <src> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

I have included "useCORS: true" in order to display an image in my screenshot and I have set the HTTPHeaders in Salesforce to accept "*". This has not solved the issue

**Comment by Stavtastic** [comment]
Try this on your  cloud page

`<script runat="server">
  Platform.Load("Core","1");
  HTTPHeader.SetValue("Access-Control-Allow-Methods","GET, POST");
  HTTPHeader.SetValue("Access-Control-Allow-Origin","*");
</script>`
