### ISSUE TITLE
Error when drawing images with fractional heights that scale to less than 1px

### ISSUE THREAD

**Issue by cheapsteak** [niklasvh/html2canvas#2408]
### Bug reports:

When drawing a background image with an intrinsic width of `1300` and height of `1`, scaled down to a width of `650` (using background-size), the height of the image becomes `0.5`, which once assigned to canvas.height, gets rounded to `0`

https://github.com/niklasvh/html2canvas/blob/3982df1492bdc40a8e5fa16877cc0291883c8e1a/src/render/canvas/canvas-renderer.ts#L535-L537

This then triggers an error of

```
Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
```

## possible solution  

Switch to use `canvas.height = Math.max(1, height); ` in `CanvasRenderer.resizeImage`

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Chrome Version 86.0.4240.111 (Official Build) (x86_64)
 * Operating system: MacOS

**Comment by Rax-Pc** [comment]
I do agree, but the branch of master hasn't deal it .
