### ISSUE TITLE
cant render div creating blank canvas

### ISSUE THREAD

**Issue by darkworks** [niklasvh/html2canvas#2411]
Am using latest build of html2canvas however its creating blank canvas of div , sometime it render half of the div content and sometime blank  and sometime full , mostly like luck ? 

### Bug reports:

JSfiddle : https://jsfiddle.net/darkworks/h1sgL8mw/2/

screenshots 👍 

![image](https://user-images.githubusercontent.com/12841788/98543132-d56b4700-22b3-11eb-8015-f0c64dd15729.png)

### Specifications:

 * html2canvas version tested with: latest chrome browsers
 * Browser & version: 86
 * Operating system: win 10

**Comment by kevinmao96** [comment]
HI, do you find solution? i'm getting the same problem

**Comment by darkworks** [comment]
ya i give up on this lib and started using https://github.com/tsayen/dom-to-image

**Comment by niklasvh** [comment]
The above fiddle seems to work fine with the latest version
