### ISSUE TITLE
Is There A Way to Save Element Which Has 'transform: rotate' Css?

### ISSUE THREAD

**Issue by dev-whoan** [niklasvh/html2canvas#2412]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [v] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with: https://html2canvas.hertzen.com/dist/html2canvas.js
 * Browser & version: Chrome
 * Operating system: Android

Hi there.
Is there a any way to save an element which has 'transform: rotate' css?
The element is not saving well, and I searched about it about 3 days, but I cannot find any solution for it.

So, still now, there is no way to save transformed element?

**Comment by prokulit06** [comment]
Any reply for this issue I encounter also this one

**Comment by dev-whoan** [comment]
@prokulit06 use just like this: `transform: scaleX(DEG)` or `transform: scaleY(DEG)`
Then it works.
