### ISSUE TITLE
FontAwesome 5 SVGs appears huge

### ISSUE THREAD

**Issue by Dror-Bar** [niklasvh/html2canvas#2413]
### Bug reports:

For some reason, SVGs from FontAwesome 5 library are rendered absolutely huge, ignoring their real size. I tried giving the SVGs specific size (for example, width: 50px, height: 50px) but that did nothing. Tried both from code and from inspector.

Original canvas:

![Screen Shot 2020-11-10 at 12 38 08](https://user-images.githubusercontent.com/34343333/98664015-80cad900-2352-11eb-9910-531db6d93b37.png)

Result:

![data_image_jpeg;base64,_9j_4AAQSkZJRgABAQAAAQABAAD_2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH_2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH_ (1)](https://user-images.githubusercontent.com/34343333/98664034-87595080-2352-11eb-872a-8e1eefbb7cac.jpeg)

### Specifications:

 * html2canvas version tested with: I started with rc.5 but tried with rc.6 and rc.7 as well
 * Browser & version: Chrome latest
 * Operating system: macOS

**Comment by Dror-Bar** [comment]
Managed to solve this using [Muratcatal's](https://github.com/niklasvh/html2canvas/issues/1578#issuecomment-412796286) solution. This still seems like a bug though, as settings width and height on the SVG directly still did not help.

**Comment by niklasvh** [comment]
This should be fixed
