### ISSUE TITLE
Icons from "Eva" icon pack are not visible

### ISSUE THREAD

**Issue by antoshens** [niklasvh/html2canvas#2414]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I'm using "Eva" icons pack and when I capture the "screenshot" there are no icons on the given image.
I think this is because I use an icon-pack. Also I'm using some custom SVGs and everything is fine with them.

#### Real section with icons:
![image](https://user-images.githubusercontent.com/19598988/98832054-075fe300-2445-11eb-8a34-235f5d9ed1ae.png)

#### Screenshot:
![image](https://user-images.githubusercontent.com/19598988/98832152-252d4800-2445-11eb-8b0a-fdedfac4b1ca.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Chrome Version 86.0.4240.193 (Official Build) (64-bit)
 * Operating system: Windows 10

**Comment by c0d3-ninja** [comment]
Give foreignObjectRendering value as true. That is working for me.
 Example:
html2canvas(node,
		{
            foreignObjectRendering:true
        }).then((canvas) => {
            document.body.appendChild(canvas);
        });

**Comment by antoshens** [comment]
> Give foreignObjectRendering value as true. That is working for me.
> Example:
> html2canvas(node,
> {
> foreignObjectRendering:true
> }).then((canvas) => {
> document.body.appendChild(canvas);
> });

Hooray! Thanks @c0d3-ninja for this setting.
Issue fixed.
