### ISSUE TITLE
SyntaxError: Error parsing CSS component value, unexpected EOF

### ISSUE THREAD

**Issue by lnadudva** [niklasvh/html2canvas#2416]
Hi everyone,

I have an Angular application which is compiled into a web component using `@angular/elements`. I have an error for the following use-case:

- I have a chart rendered with `highcharts`, which should be added to a pdf that is created using `pdfmake`
- I used `html2canvas` to grab the chart from the DOM and turn it into a JPEG
- It works when the application is ran locally but `html2canvas` fails with the error `SyntaxError: Error parsing CSS component value, unexpected EOF` when it is ran in a web component

The `highcharts` chart is an SVG element, and it has multiple CSS rules applied to it by the library itself. My guess is that when it gets compiled to a web component the CSS rules get messed up somehow or the charting library binds some messy CSS to the charts, but in the second case it shouldn't work in "non web component" mode either.

I appreciate all the help I can get, thank you.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Google Chrome v86
 * Operating system: macOS

**Comment by lnadudva** [comment]
I fixed this issue by using CANVG, a requirement for our project was compatibility with IE11 (while using a web component..) canvg managed to satisfy everything. Keep an eye out for canvas width/height ratio and scaling because I had trouble debugging blurry canvases on my retina macbook pro.

**Comment by LazeBear** [comment]
Hi @lnadudva ,
I'm facing the exact same issue as you did. I want to save a d3 chart as images with angular web component. Do you mind sharing some code snippets on how you solved it with canvg?
Thanks

**Comment by lnadudva** [comment]
hi @LazeBear,

here are the snippets of the script I've written with canvg, hope this helps!
```
import { Canvg } from 'canvg';

const getSvgElement = (elementToCheck: Element): Element => {
  if (elementToCheck.nodeName === 'svg') {
    return elementToCheck;
  } else {
    // in our use case there are only single children in the chart components
    const svg = elementToCheck.getElementsByTagName('svg');
    if (!svg.length) {
      throw Error('No SVG element found!');
    }
    return getSvgElement(svg[0]);
  }
};

export const createImageForPdfFromSvg = (chartElement: Element): Promise<{ url: string; ratio: number }> => {
  return new Promise<{ url: string; ratio: number }>(async (resolve, reject) => {
    try {
      const svgElement = getSvgElement(chartElement);
      const { width, height } = svgElement.getBoundingClientRect();
      // in IE outerHTML is undefined, so we need to serialize the SVG source and the serializer puts a new xlmns attribute in
      const svgSource =
        svgElement.outerHTML || new XMLSerializer().serializeToString(svgElement).replace('xmlns="http://www.w3.org/2000/svg"', '');

      const canvas = document.createElement('canvas');
      // under 3 pixelratio canvases look blurry on Retina Mac displays..
      const pixelRatio = 5;
      canvas.width = width;
      canvas.height = height;

      canvas.style.width = `${canvas.width}px`;
      canvas.style.height = `${canvas.height}px`;
      canvas.width *= pixelRatio;
      canvas.height *= pixelRatio;

      const context = canvas.getContext('2d');
      context.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);

      const svgToCanvasRender = await Canvg.from(context, svgSource, {
        scaleWidth: width,
        scaleHeight: height,
        ignoreDimensions: true,
      });

      svgToCanvasRender.start();
      resolve({ url: canvas.toDataURL('image/jpg', 1), ratio: width / height });
      svgToCanvasRender.stop();
    } catch (e) {
      reject(e);
    }
  });
};
```
This function should be wrapped in an Observable I know, but when I implemented it I was in a rush.. For the `chartElement` input you should pass in the `nativeElement` of the chart ViewChild.

**Comment by LazeBear** [comment]
Thank you very much, @lnadudva.
I will give a try
