### ISSUE TITLE
当需要导出的页面长度超过1.5Wpx时，导出的数据丢书

### ISSUE THREAD

**Issue by calvinchan22** [niklasvh/html2canvas#2426]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by calvinchan22** [comment]
when i trying to export a node which is longer than 15000 px,the pdf will lose some data

**Comment by zoubeihua** [comment]
怎么解决呢 我也遇到同样的问题

**Comment by niklasvh** [comment]
See https://html2canvas.hertzen.com/faq regarding maximum canvas size.
