### ISSUE TITLE
Icon tag having custom font-family isn't getting rendered

### ISSUE THREAD

**Issue by vivek091195** [niklasvh/html2canvas#2429]
I have an icon tag like this - `<i class="icon icon-1" role="button" aria-hidden="true"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>`
The styles given to this icon tag are - 
```
@font-face {
font-family: "custom-font";
src: url(url) format(format)
}
[class^='icon-'] {
font-family: "custom-font"!important;
    font-style: normal;
    font-weight: 400;
    font-feature-settings: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
}
```

But when I try to capture this icon tag, I am getting blank space. I tried with the latest version(`v1.0.0-rc.7`), but still facing the issue. I even tried passing the styles directly as inline styles but still facing the issue. Is there a way in which we can successfully parse custom font with html2canvas?

**Comment by mkubdev** [comment]
I'm facing the same issue with the custom `icomoon` font.

Generally, custom font can be injected with this snippet that i call before the html2canvas call:
```js
 const svgToCanvas = (targetElem) => {
    var svgElem = targetElem.getElementsByTagName('svg');
    for (const node of svgElem) {
      node.setAttribute(
        'font-family',
        window.getComputedStyle(node, null).getPropertyValue('font-family') + ', icomoon'
      );
      node.replaceWith(node);
    }
  };
  
  const generatePDF = () => {
     // pdf options
    
    // [Workaround] add custom font
    svgToCanvas(canvasRef);
    
    // Call html2canvas
    // ....
  }
  ```
  
  I'm importing the font the same way as @vivek091195. I'm a bit lost about how I can fix it! I got only blank square.
