### ISSUE TITLE
Canvas overlay png works in chrome and IE but not in firefox.

### ISSUE THREAD

**Issue by patriceckhart** [niklasvh/html2canvas#2430]
If you scroll down on the mentioned link you can upload a logo and place it on a doormat. When you click on Add to cart, the canvas is uploaded. In Chrome, the correct image is displayed in the shopping cart, including the uploaded logo. Not in Firefox.

To test, I also have the image generated when you click on the label "Schritt 3: Wunschgröße auswählen". I logged the url in the console.

https://bit.ly/37vYApE

**Comment by patriceckhart** [comment]
CORS Problem

**Comment by cookcc** [comment]
> CORS Problem

so, how to fix this problem
