### ISSUE TITLE
html2canvas 1.0.0-rc.7  setProperty("all", "") has compatibility issues in Safari

### ISSUE THREAD

**Issue by Markyeahjr** [niklasvh/html2canvas#2433]
### Bug reports:

Code `window.getComputedStyle(node)` return 
![image](https://user-images.githubusercontent.com/28997576/101455116-026f5000-396d-11eb-95fc-f530d12e261b.png)

Code `target.style.setProperty("all", "") ` in Safari causes inline styles to fail

Chrome:
![image](https://user-images.githubusercontent.com/28997576/101456109-8544da80-396e-11eb-97de-274d63f44cb7.png)
Safari:
![image](https://user-images.githubusercontent.com/28997576/101456241-bb825a00-396e-11eb-96b8-7471e678969b.png)

So it is advisable to add this judgment
`if (property !== 'content' && style.getPropertyValue(property)) {`
`    target.style.setProperty(property, style.getPropertyValue(property));`
`}`
### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by Markyeahjr** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/28997576/101456408-f5536080-396e-11eb-9caf-4cc7ac9e8c7e.png)

Safari:
![image](https://user-images.githubusercontent.com/28997576/101456434-fedcc880-396e-11eb-8642-26ee6b8b9157.png)

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/pull/2586
