### ISSUE TITLE
onclone is not working

### ISSUE THREAD

**Issue by utkarsh22garg** [niklasvh/html2canvas#2436]
### Bug reports:

I want to change the display property of myDiv from `none` to `block` inside the cloned document. The reason to do this is that I want to hide my div in the actual dom. When I am trying to use onclone option of html2canvas, to change the property it is not reflecting. Can someone please check if I am missing something here? Please find below the link to the reproducer.

[Codesandbox](https://codesandbox.io/s/elated-mcclintock-umt5w?file=/src/App.js)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Chrome 87
 * Operating system: Windows 10

**Comment by LuoRiWuSheng** [comment]
建议，将你的内容，放在整个页面的下面  z-index: -1 上面再盖一层， 推测是   html2canvas 不能识别 display: none 的元素

**Comment by LuoRiWuSheng** [comment]
> 建议，将你的内容，放在整个页面的下面 z-index: -1 上面再盖一层， 推测是 html2canvas 不能识别 display: none 的元素

@utkarsh22garg

**Comment by renzoiscalma** [comment]
Happens to me as well. `onclone` is indeed being called yet nothing is happening. Ended up downgrading to version `1.0.0-alpha.12`.

**Comment by LorenzoDelpi** [comment]
I have the same problem, any news about this?

**Comment by niklasvh** [comment]
The `onclone` is working, but as you are rendering an element with `display:none`, it has no width/height. Changing it to use `visibility` and it works justs fine: https://codesandbox.io/s/xenodochial-northcutt-002g6?file=/src/App.js

**Comment by lighthaus205** [comment]
Using the visibility property worked me for me as well! Using the display property was causing some issues, for example sometimes the font was not correctly rendered.
