### ISSUE TITLE
Google maps API v3 (still tainted with proxy and markers missing)

### ISSUE THREAD

**Issue by oktav** [niklasvh/html2canvas#244]
Hello,

I managed to make this partially work with google maps. I'm also using a proxy I wrote in Ruby (Rails).

Here's the code of my proxy (it's very basic and it's actually a controller action within my application):

```
class ProxyController < ApplicationController
  def get_image
    url = URI.parse(params[:url] || "")
    callback = params[:callback]

    response = Net::HTTP.start(url.host, use_ssl: true, verify_mode: OpenSSL::SSL::VERIFY_NONE) do |http|
      http.get url.request_uri
    end

    bin_body = response.body

    base64 = [bin_body].pack("m0")
    responseData = 'data:' + response.header.content_type + ';base64,' + base64

    output = "#{callback}(#{responseData.to_json})"
    send_data output, type: 'application/javascript', disposition: 'inline'
  end
end
```

I'm pretty sure the proxy is working because I'm getting the same output as the one in node.js.

This is the JS that I use to render the canvas

```
$("a.export-map").click ->
  html2canvas $("div#map"),
    proxy: "/proxy/get"
    onrendered: (canvas) ->
      console.log(canvas.toDataURL())
  false
```

Now, It kinda works... I'm attaching the output of the function as well as how it should be.

This is my result:
![image](https://f.cloud.github.com/assets/550799/804868/8882a4ee-ee1b-11e2-91a7-55eaa225f830.png)

This is how it should be:
![desired](https://f.cloud.github.com/assets/550799/804877/daf33d7e-ee1b-11e2-950e-874abfd23a08.png)

As you can see, some thing are missing. Like the marker and the left side controls. 

Also I'm getting between 3 and 4 console errors when I try to convert. The errors are always the same: 

```
Unable to get image data from canvas because the canvas has been tainted by cross-origin data. html2canvas.js?body=1:2735
    safeImage html2canvas.js?body=1:2735
    renderItem html2canvas.js?body=1:2769
    (anonymous function) html2canvas.js?body=1:2819
    _html2canvas.Renderer html2canvas.js?body=1:2562
    options.complete html2canvas.js?body=1:2677
    start html2canvas.js?body=1:2209
    img.onload
```

**Comment by Viscis** [comment]
Workaround:

(Source#1) : http://humaan.com/custom-html-markers-google-maps/
(Source#2) : http://jsfiddle.net/BCr2B/99/

Its quick and quite simple to implement your own markers, which then circumvents the tainted problems.

```
function HTMLMarker(lat, lng, col) {
		this.lat = lat;
		this.lng = lng;
		this.col = col;
		this.pos = new google.maps.LatLng(lat, lng);
	}
	HTMLMarker.prototype = new google.maps.OverlayView();
    HTMLMarker.prototype.onRemove = function() {}
    HTMLMarker.prototype.onAdd = function() {}
    HTMLMarker.prototype.draw = function() {
		var self = this;
		var div = this.div;
		
		if(!div) {
			div = this.div = document.createElement('div');
			div.className = 'marker';
			div.style.position = 'absolute';
			div.style.width = '32px';
			div.style.height = '32px';
			
			switch(this.col) {
				case "green":
					div.innerHTML = '<img src="/images/green-dot.png">';
					break;
				case "yellow":
					div.innerHTML = '<img src="/images/yellow-dot.png">';
					break;
				case "red":
					div.innerHTML = '<img src="/images/red-dot.png">';
					break;
			}
			
			var panes = this.getPanes();
			panes.overlayImage.appendChild(div);
		}
		
					
		var position = this.getProjection().fromLatLngToDivPixel(this.pos);
		div.style.left = position.x - 16 + "px";
		div.style.top = position.y - 32 + "px";
    }
```

Then just add:

```
var htmlMarker = new HTMLMarker(data[gps].Latitude, data[gps].Longitude, "green");
markersArray.push(htmlMarker.setMap(map));
```

**Comment by btoueg** [comment]
Have you tried setting `optimized: false` in the markers options?

It will make google maps render every marker as a DOM element, thus enabling `html2canvas` to find them and render them.

Worked for me.

**Comment by TehNrd** [comment]
@btoueg This save me hours of frustration, thank you! When `optimized` is set to `true` google maps will still render the actually dom elements up to a certain number of makers. Was this number is passed, around 200, it will then convert the images to canvas elements which prevent the markers from rendering.
