### ISSUE TITLE
Blank image displaying

### ISSUE THREAD

**Issue by Mrbeyond** [niklasvh/html2canvas#2440]
It works fine on desktops but shows white blank image on mobile devices.

**Comment by dming4** [comment]
I just have a try, on desktops also display blank image, how to solve this issue?

**Comment by IT-xu** [comment]
me too

**Comment by zhangporco** [comment]
me too

**Comment by M1123581E** [comment]
me too

**Comment by Mrbeyond** [comment]
I really need help with this issue, somebody should please help.

**Comment by Bukunmikuti** [comment]
I discovered this happens when scroll position is altered. So, in my case, scroll position has to be 0, 0 to prevent the white image.

I'm using `window.scrollTo(0, 0)` for a temporary fix
