### ISSUE TITLE
Does not render full div on Safari 

### ISSUE THREAD

**Issue by enkr1** [niklasvh/html2canvas#2446]
> > > **I solved all possible problems as follows..**
> > 
> > 
> > ```
> > html2canvas(element , {
> >         scrollX: -window.scrollX,
> >         scrollY: -window.scrollY,
> >         windowWidth: document.documentElement.offsetWidth,
> >         windowHeight: document.documentElement.offsetHeight
> > })
> > ```
> 
> Thanks but it did not fix the issue with iOS unfortunately, still you have to scroll to the top of the page, capture the screen and then scroll back!

In my case, it happens in a pop-up modal on the Safari browser. 

The full div can be rendered (in the modal) on Chrome and Firefox. On Safari, when u scroll down of the modal, the bottom part of the captured element will be cut off.

_Originally posted by @enkr1 in https://github.com/niklasvh/html2canvas/issues/1878#issuecomment-747328254_

**Comment by shinokada** [comment]
For me adding `window.scrollTo(0,0);` solved the problem.

```
$(function () {
    $("#btnSave").click(function () {
          window.scrollTo(0, 0);// you need to scrool to top for safari hack
          html2canvas($("#screen")[0]).then(canvas => {
                $("#img-out").append(canvas);
                canvas.toBlob(function (blob) {
                    saveAs(blob, "cecilieo_color_picker.png");
                });
          });
     });
});
```

**Comment by enkr1** [comment]
> For me adding `window.scrollTo(0,0);` ~solved the problem~. I thought it did, but it didn't work some times.
> 
> ```
> $(function () {
>     $("#btnSave").click(function () {
>           window.scrollTo(0, 0);// you need to scrool to top for safari hack
>           html2canvas($("#screen")[0]).then(canvas => {
>                 $("#img-out").append(canvas);
>                 canvas.toBlob(function (blob) {
>                     saveAs(blob, "cecilieo_color_picker.png");
>                 });
>           });
>      });
> });
> ```

I tested it without `window.scrollTo(0, 0);` in Bootstrap modal on Chrome and Firefox, it worked fine. 

Only for Safari, the div is cropped off, as there is a huge white space on top of the captured image (div)

**Comment by chrisheseltine** [comment]
@Leographik did you find a fix for this? I am having the same issue. When I capture a HTML SVG element with html2canvas on Chrome or Firefox everything works fine. When I switch to Safari it doesn't capture properly but instead translates and crops the image. Stuck on this and any help you may have found would be appreciated! Thanks.

**Comment by chrisheseltine** [comment]
Tried to bypass html2canvas using raw canvas as described here: https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser/64800570#64800570

Didn't work, just hung forever loading, no error output. Leads me to believe this is an issue with newer versions of Safari and the canvas DOM element.
