### ISSUE TITLE
给几个文字添加背景颜色，自动折行，同一行的文字会被当前文字的背景颜色遮盖

### ISSUE THREAD

**Issue by Angelia0302** [niklasvh/html2canvas#2452]
![QQ截图20201230172426](https://user-images.githubusercontent.com/30562707/103342216-ebcb9d00-4ac3-11eb-9596-3b18e4290847.png)
![image](https://user-images.githubusercontent.com/30562707/103342285-13226a00-4ac4-11eb-919d-b6aeec3b2be7.png)

**Comment by FlashTang** [comment]
可能是不支持某些功能
https://github.com/niklasvh/html2canvas/issues/1994
看看是不是用到了不支持的css功能，用其他办法代替一下这个文本背景?
也或许这是一个bug?
 P.S. 我没用过html2canvas

**Comment by niklasvh** [comment]
Duplicate of #2558

**Comment by sundenglong** [comment]
我遇到了同样的问题，请问这个是怎么解决的

**Comment by JavonLuo** [comment]
解决了吗

**Comment by zhang-zhang-hao** [comment]
解决了吗
