### ISSUE TITLE
移动端上生成的base64 图片过大，出现.txt文件 

### ISSUE THREAD

**Issue by websmallrabbit** [niklasvh/html2canvas#2463]
移动端项目，vue+vantui   生成的base64图片 6.4M 图片很大， 高度很长，下载 时出现.txt文件。 而且生成的文件，宽度变窄。

**Comment by PyForMcj** [comment]
您好，我这边也是移动端，目前只要内容高度超过4400px之后，下面就显示空白了，这个有什么办法吗？
scale已经设置为1了，没设置之前只能截图2200px，所以怀疑大小问题

**Comment by websmallrabbit** [comment]
我是html放大2倍，然后生成的png 图片就正常了
