### ISSUE TITLE
Icons Not Showing

### ISSUE THREAD

**Issue by anniehsp** [niklasvh/html2canvas#2466]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Hi! I am trying to use html2canvas for my feedback capture option! It captures well and it shows the image well on my popup, but the icons(which I am using it from material-ui) were not showing in the capture image.

Thanks for reading and will be waiting for your feedback! Thanks!

### Specifications:

 * html2canvas version tested with: ^1.0.0-rc.7
 * Browser & version: Chrome & 87.0.4280.88(official build) (x86_64)
 * Operating system: Mac OS

**Comment by eseQ** [comment]
Same here

**Comment by gaelperon** [comment]
same here

**Comment by anniehsp** [comment]
I solved this problem by giving height and width of svgElement before calling html2canvas to capture the image, and it works fine!
