### ISSUE TITLE
Table is not getting rendering to image if the rows has rowspan attribute

### ISSUE THREAD

**Issue by Chandand76** [niklasvh/html2canvas#2471]
when we have rowspaning in table and given tr background-color, table is not rendered.

table tr {
  background-color: #ccc;
}

Fiddle link - http://jsfiddle.net/az5j0766/230/

table in HTML
![image](https://user-images.githubusercontent.com/61581640/104883811-ee831a80-592a-11eb-9d1c-d42c2a03b7fe.png)

Preview
![image](https://user-images.githubusercontent.com/61581640/104883904-13778d80-592b-11eb-9727-76b1433a3262.png)

Specifications:
html2canvas version tested with: 1.0.0-rc.7
Browser & version: chrome 87
Operating system: win10

**Comment by Chandand76** [comment]
Anyways, I found a solution for this. 

Thanks

**Comment by lIAn0110** [comment]
Hello, can you tell me how to solve it?

**Comment by lIAn0110** [comment]
> Anyways, I found a solution for this.
> 
> Thanks

Hello, can you tell me how to solve it?

**Comment by Chandand76** [comment]
Added this piece of code in ElementContainer function and it works fine for me.

 if(element.tagName == "TD" && element.rowSpan){
				this.flags = 2;
			}
			else{           
				this.flags = 0;
			}
![image](https://user-images.githubusercontent.com/61581640/106860839-8f433b00-668a-11eb-985b-c2936a34a99e.png)

**Comment by lIAn0110** [comment]
Thanks

> Added this piece of code in ElementContainer function and it works fine for me.
> 
> if(element.tagName == "TD" && element.rowSpan){
> this.flags = 2;
> }
> else{
> this.flags = 0;
> }
> ![image](https://user-images.githubusercontent.com/61581640/106860839-8f433b00-668a-11eb-985b-c2936a34a99e.png)

Thanks.

**Comment by Ihuangmi** [comment]
Hello, can you see all the code you called? I don’t know where the ElementContainer function is placed

**Comment by saito03x** [comment]
I fixed it this way:

td[rowspan] {
  z-index: 50;
  background-color: white;
  position:relative; 
}

**Comment by DominikKor** [comment]
> td[rowspan] {
> z-index: 50;
> background-color: white;
> position:relative;
> }

Thank you Thank you! That's the only solution that worked for me. Actually, I only needed to set position: relative.

```
td[rowspan] {
    position: relative;
}
```

**Comment by Andrux51** [comment]
> > td[rowspan] {
> > z-index: 50;
> > background-color: white;
> > position:relative;
> > }
> 
> Thank you Thank you! That's the only solution that worked for me. Actually, I only needed to set position: relative.
> 
> ```
> td[rowspan] {
>     position: relative;
> }
> ```

This was so hard to find. I'm using this as part of jsPDF and I was spinning my wheels on it for half of forever. FWIW I'm on jsPDF v2.3.1 which is the latest version that's still compatible with the ancient version of Angular I'm stuck with (for now) Thank you!!!
