### ISSUE TITLE
Error loading image

### ISSUE THREAD

**Issue by useryechen** [niklasvh/html2canvas#2473]
### Specifications:

 * html2canvas version tested with: `1.0.0-rc.7`
 * Browser & version: `Opera Mobile` & `12.57.0.2`
 * Operating system: `Funtouch OS`

- 我在PC端浏览器模拟H5端没有问题
- 但是在H5端浏览器生成图片的时候，`oss`上的图片加载会报错，`oss`已经配置过跨域规则了，并且`html2canvas`也已经配置过`useCORS`了
- 会报错`577ms Error loading image`
- 尝试过先将`oss`上的图片转换成`base64`，但是`Image`对象不触发`onload`事件，因此这个方法也失败了，不清楚该用那个方式了

**Comment by zhengmenghuang** [comment]
+1

**Comment by useryechen** [comment]
目前通过后端配置`oss`跨域规则，前端通过获取到当前图片的`dom`元素，判断当前图片加载完成，使用`canvas`读取图片，然后再生成`base64`重新赋值给图片`src`解决，或者通过`canvas`的`toBlob`方法，转换成`blob`临时访问地址赋值给图片`src`。但是转换成`blob`有部分移动端浏览器会出现无法下载图片问题，如果涉及到图片下载或者分享的话，推荐使用`base64`,也就是`canvas.toDataURL()`
