### ISSUE TITLE
Cropped images when data-html2canvas-ignore is used

### ISSUE THREAD

**Issue by fifal** [niklasvh/html2canvas#2480]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug report:
I have stumbled upon the following bug when I forgot the `data-html2canvas-ignore` attribute at the wrong location in the HTML.
The problem occurs when you use the `data-html2canvas-ignore` outside of the element which you want to render to the canvas, e.g.:

```html
<body>
    <div data-html2canvas-ignore="true">...</div>
    <div id="element-to-canvas">...</div>
</body>
```
With this code the resulting image is cropped, because the offsets are wrongly calculated as the div with `data-html2-canvas-ignore` is ignored.

An example can be seen in the following image. The resulting image has red border around the canvas, and as you can see it is cropped.
![image](https://user-images.githubusercontent.com/54062667/106923268-2e5d4680-670e-11eb-9505-28700c9c877e.png)

The working example of the problem: [jsfiddle](https://jsfiddle.net/5ay2x6v3/5/)

### Solution
I guess the solution would be to ignore presence of the `data-html2canvas-ignore` attribute when it is outside of the target element.

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Firefox 85.0, Chromium 88.0.4324.146, Edge 88.0.705.56
 * Operating system: Linux, Windows 10

**Comment by charlesprescottcollins** [comment]
Confirmed this issue still occurs and affects our use case in 1.0.0
