### ISSUE TITLE
Just a question: HTML2Canvas on Ios...

### ISSUE THREAD

**Issue by GigaMick** [niklasvh/html2canvas#2482]
I implemented my HTML2Canvas and was very pleased with the result. Deployed to production, all works perfect. Tested on my phone and... Nope... Just renders out a white image.

I've spent the best part of a day Googling and there about a billion threads, posts, articles relating to that fact that HTML2Canvas doesn't work on mobiles.

Is there something I'm missing? is there a solution to this?

FWIW my implementation looks like this:

```
 $(document).ready(function () {
            $('#save').on('click', function () {
                var div = document.querySelector('#yermaw');
                html2canvas(div, {
                    allowTaint: true,
                    useCORS: true,
                    scale: 2,
                    scrollX: -window.scrollX,
                    scrollY: -window.scrollY,
                    windowWidth: document.documentElement.offsetWidth,
                    windowHeight: document.documentElement.offsetHeight
                }).then(function (x) {
                    div.style.position = 'static';
                    var imgData = x.toDataURL('image/jpg');
                    $('#image').attr('src', imgData);
                    $('#imagesrc').attr('value', imgData);

                });
            });
        })
```

and I'm using RC7

**Comment by GigaMick** [comment]
I've since discovered that this is only an issue on iPhones.

**Comment by crb596** [comment]
I have a very similar issue. I call a "window.scrollTo(0, 0);" right before invoking html2canvas to avoid the common clipping issue. This works on all my tests thus far, even Google Chrome's phone screen size emulator. But on the phones themselves the address bar that collapses causes problems. When the bar is collapsed it works perfectly and scrolls to the top. But when the bar is not collapsed like on an initial load the scroll to 0,0 is lower than it would be if the bar was collapsed and causes a white offset on the bottom of the new canvas.

**Comment by weifengsmile** [comment]
> I've since discovered that this is only an issue on iPhones.

Do you solve this problem now ?
