### ISSUE TITLE
RTL direction problem

### ISSUE THREAD

**Issue by Revisto** [niklasvh/html2canvas#2488]
Hi, there is a problem with Arabic/Farsi characters and RTL direction,
the correct HTML file picture:
![image](https://user-images.githubusercontent.com/60847212/109361052-81559400-789d-11eb-85ca-b5dfc38890f0.png)

html2canvas render result:
![image](https://user-images.githubusercontent.com/60847212/109361110-a2b68000-789d-11eb-87e0-0e96aa05d101.png)

**Comment by shwaeki** [comment]
sorry but !
do you found the solution ?

**Comment by Revisto** [comment]
Hello, unfortunately no.

**Comment by ikilane** [comment]
do you know any other library ?

**Comment by Revisto** [comment]
unfortunately no, I had to use a browser extension and manually take a picture of the element.

**Comment by hasanparasteh** [comment]
I have the same problem with html2canvas! Somebody pleaseee just fix this issue

**Comment by erfanmola** [comment]
Any updates ?

**Comment by hasanparasteh** [comment]
We just need to add the direction property to `CanvasRenderingContext2D.direction` and then it maybe can merge into the main branch if the maintainer accepts the PR #2529

**Comment by erfanmola** [comment]
> We just need to add the direction property to `CanvasRenderingContext2D.direction` and then it maybe can merge into the main branch if the maintainer accepts the PR #2529

Can you send me a build version of your fixed file ? I built your version PR #2529 , But it still has the same problem
Can u build and test and share it in this topic ? It would be very nice
Also #2556 issue is still the same problem

**Comment by erfanmola** [comment]
No progress yet ?

**Comment by hasanparasteh** [comment]
@erfanmola No progress yet. I'm waiting for just `CanvasRenderingContext2D.direction` approval...This is my [forked repo](https://github.com/hasanparasteh/html2canvas)! I would be glad if you can just check or maybe make a fix for `CanvasRenderingContext2D.direction` problem in my repo.

**Comment by MESepehr** [comment]
Hi guys,
I still had this problem. so I fetched into source code and do more updates on the main source and now my problem is solved completely. you could check this:

https://github.com/niklasvh/html2canvas/pull/2756

**Comment by Yahhya-Akram-Ayoub** [comment]
try to add this style to the text  ,
 in my case it solved my problem  


word-wrap: normal;
letter-spacing: normal;

**Comment by mustn** [comment]
> try to add this style to the text , in my case it solved my problem
> 
> word-wrap: normal; letter-spacing: normal;

That's also fixed my problem. Thaaaanks
