### ISSUE TITLE
SVG is blank on Firefox for d3 and nvd3 charts

### ISSUE THREAD

**Issue by csliangy** [niklasvh/html2canvas#2489]
### General description:
* It works well on Chrome expect one leaflet chart
* All charts cannot work on Firefox, also test with other websites, the same issue

### Specifications:

 * html2canvas version tested with: Latest version from https://html2canvas.hertzen.com/dist/html2canvas.js
 * Browser & version: Firefox 86.0(64bit)
 * Operating system: Windows

### How to reproduce:
Test with https://nextstrain.org/ncov/global, run the following script on console:

```
var script = document.createElement("script");  
script.src = "https://html2canvas.hertzen.com/dist/html2canvas.js"
document.head.appendChild(script); 
html2canvas(document.querySelector("#root")).then(function(canvas) {console.log(canvas); url = canvas.toDataURL(); link=document.createElement('a'); link.href=url; link.download="file.png"; document.body.appendChild(link); link.click(); document.body.removeChild(link)});
```

### What I got:
![file-9](https://user-images.githubusercontent.com/515787/109870471-0215f500-7ccf-11eb-8329-ee7ca7a2310f.png)

### What I expected:
![Capture55](https://user-images.githubusercontent.com/515787/109870639-38ec0b00-7ccf-11eb-84fb-8c5c25206ba5.PNG)

**Comment by lucbelliveau** [comment]
I am seeing the same behavior.

**Comment by niklasvh** [comment]
Getting with the latest:
![file](https://user-images.githubusercontent.com/551347/128285873-342d3794-0f39-45e5-9b3e-425a0439ce70.png)
