### ISSUE TITLE
canvas.toDataURL()  data:,

### ISSUE THREAD

**Issue by JokerPawn** [niklasvh/html2canvas#2490]
### Specifications:

 * html2canvas version tested with: "^1.0.0-rc.7"
 * Browser & version: chrome 89.0.4389.82
 * Operating system: win7

**Comment by Gstring-w** [comment]
If the height or width of the canvas is 0 or larger than the maximum canvas size, the string "data:," is returned.

[https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL](url)
