### ISSUE TITLE
Homepage Demo Not Working

### ISSUE THREAD

**Issue by PanopticaRising** [niklasvh/html2canvas#2491]
### Bug reports:

The [homepage](https://html2canvas.hertzen.com/) to this has a demo on the frontpage. The demo does not work and throws a CORS error.

DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet in example.js:194

### Specifications:

 * html2canvas version tested with:
 * Browser & version: Firefox 86
 * Operating system: Windows 10

**Comment by niklasvh** [comment]
Im unable to repro this
