### ISSUE TITLE
Half up the generated picture

### ISSUE THREAD

**Issue by zhixialihan** [niklasvh/html2canvas#2493]
![图片](https://user-images.githubusercontent.com/56864653/111724192-c9b21180-889f-11eb-94f3-920b7d4ad914.png)
![图片1](https://user-images.githubusercontent.com/56864653/111724252-e4848600-889f-11eb-8314-a2a7869fd283.png)

**Comment by niklasvh** [comment]
This should be fixed in 1.2.1
