### ISSUE TITLE
Help !  My svg image cannot render success with html2canvas

### ISSUE THREAD

**Issue by OnePsycho** [niklasvh/html2canvas#2506]
before use html2canvas
![9aea838e11814e8fc241b770a84a85f](https://user-images.githubusercontent.com/43296632/114689709-90f34400-9d48-11eb-8aba-bd89c63c6d58.png)

after user html2canvas
![d7fafeffa905514bc1617cb562717d0](https://user-images.githubusercontent.com/43296632/114689740-98b2e880-9d48-11eb-8dba-f0b9cbc19931.png)

**Comment by OnePsycho** [comment]
![image](https://user-images.githubusercontent.com/43296632/114689828-b1bb9980-9d48-11eb-85c4-e56b5bcad8fc.png)

**Comment by niklasvh** [comment]
If you are still running into this issue, please create a new ticket with a repro
