### ISSUE TITLE
Unable to render chartist-js SVG on Bar

### ISSUE THREAD

**Issue by cychongaspevo** [niklasvh/html2canvas#2508]
I using Pie Chart and Bar Chart, but only Bar chart unable render.

it just show 'Error loading svg' for the Bar chart.

**In Html:**
[![Screenshot-2021-04-15-at-11-40-57-PM.png](https://i.postimg.cc/Kvk1L87m/Screenshot-2021-04-15-at-11-40-57-PM.png)](https://postimg.cc/LnS4FR0W)

**After Export**
[![Screenshot-2021-04-15-at-11-40-41-PM.png](https://i.postimg.cc/3rbydvvL/Screenshot-2021-04-15-at-11-40-41-PM.png)](https://postimg.cc/vDf8KDX9)

```
    let view = document.getElementById('chart-view-item');  

    html2canvas(view, {

    }).then(canvas => {
      const contentDataURL = canvas.toDataURL('image/jpeg')  
      const pdf = new jsPDF('l');
      var width = pdf.internal.pageSize.getWidth();
      var height = pdf.internal.pageSize.getHeight();
      pdf.addImage(contentDataURL, 'PNG', 0, 0, width, height);  
      pdf.save('Filename.pdf');   
    }); 
```

**Comment by niklasvh** [comment]
If you are still experiencing this issue, please make a new ticket with a repro
