### ISSUE TITLE
word-spacing with space

### ISSUE THREAD

**Issue by kooriookami** [niklasvh/html2canvas#2526]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I used css `word-spacing: 12px`, the text is `[AB / CD]`.

This is the original html.
![image](https://user-images.githubusercontent.com/38392315/117566097-38b12700-b0e7-11eb-9518-fd293976760c.png)

This is the converted canvas, the space ran to the back.
![image](https://user-images.githubusercontent.com/38392315/117566109-449ce900-b0e7-11eb-9f51-f4d40025daa4.png)

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: Chrome 90
 * Operating system: win10 x64

**Comment by kooriookami** [comment]
@niklasvh Can you look at this when you are free?

**Comment by niklasvh** [comment]
@kooriookami Can you create a repro of the issue on jsfiddle?

**Comment by kooriookami** [comment]
> @kooriookami Can you create a repro of the issue on jsfiddle?

@niklasvh Yes, here it is. https://codesandbox.io/s/distracted-keldysh-pklti?file=/src/App.vue
![image](https://user-images.githubusercontent.com/38392315/125717847-2fd1be2e-2604-48fd-be9c-b84b7d739170.png)
