### ISSUE TITLE
Is it possible to take screenshot of the whole page which contains video with static divs?

### ISSUE THREAD

**Issue by developerdesigner18** [niklasvh/html2canvas#2536]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.7
 * Browser & version: chrome Version 90.0.4430.212
 * Operating system: windows 7

I have a requirement to display the host video and subscribe videos can be taken as a screenshot with a static header and sidebar.
So Is it possible to achieve this with this library?

Please help me out!! Any help will be appreciated. 

Thank you!

**Comment by AgentSmith0** [comment]
Have a look at these two links, maybe they are helpful:
https://stackoverflow.com/questions/36213275/html2canvas-does-not-render-full-div-only-what-is-visible-on-screen
https://github.com/niklasvh/html2canvas/issues/117
