### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by encod** [niklasvh/html2canvas#2540]
Uncaught (in promise) DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

**Comment by encod** [comment]
Specifications:
html2canvas version tested with: 1.0.0-rc.2
Browser & version: chromium latest release

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/bb9237155cf0ec090432ee6c5d9c555eb6ffa81f
