### ISSUE TITLE
Invalid code point NaN

### ISSUE THREAD

**Issue by FeSeason** [niklasvh/html2canvas#2545]
use latest [release of html2canvas] 1.0.0-rc.7

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

style use `counter-reset`

when use html2canvas to make a snapshot, exception occurred

```
Uncaught (in promise) RangeError: Invalid code point NaN
```

### Specifications:

 * html2canvas version tested with:  `1.0.0-rc.7`
 * Browser & version:  `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1`
 * Operating system: `Mac os`

**Comment by niklasvh** [comment]
Can you provide a repro?
