### ISSUE TITLE
ios15 截图失败

### ISSUE THREAD

**Issue by mixin1997** [niklasvh/html2canvas#2547]
iOS15截图失败了，有大佬遇到过吗

**Comment by a502430135** [comment]
IOS14.6 有滚动条的H5页面截图不全，上方会有空白

**Comment by china-fed** [comment]
iOS15.6生成二维码失败

**Comment by china-fed** [comment]
Ios15.6 failed to generate QR code

**Comment by foooooouny** [comment]
Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.

**Comment by niklasvh** [comment]
@foooooouny Can you provide a repro of this in jsfiddle?

**Comment by zhouxiaona** [comment]
ios15 生成失败+1

**Comment by dinhvandai63** [comment]
ios15 生成失败+1

**Comment by YolandaQingniu** [comment]
font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',
    SimHei;

**Comment by YolandaQingniu** [comment]
> ios15 生成失败+1

font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',
    SimHei;

**Comment by h330894169** [comment]
same, how to fix?

**Comment by dinhvandai63** [comment]
> I am unable to repro this on an iOS15 simulator #2645

Can you take a look at IOS14, I see it render not correct the width of elements, it's here https://codepen.io/dinhvandai63/pen/OJmQVRg
