### ISSUE TITLE
mac和win10系统截图的清晰度问题

### ISSUE THREAD

**Issue by zoubeihua** [niklasvh/html2canvas#2555]
- [ 1.0.0-rc.7] 
### Bug reports:
mac使用谷歌浏览器截图然后通过jsPdf 保存pdf清晰度正常 生成pdf大小是10M
win10系统 分辨率是1600*900 同样的页面但是生成pdf 很模糊  pdf大小是3M 请问是什么原因造成呢？

### Specifications:

 * html2canvas version tested with:
 * Browser & version:谷歌浏览器
 * Operating system:mac/win10

**Comment by hellohejinyu** [comment]
![image](https://user-images.githubusercontent.com/8766034/124766065-26c5f600-df69-11eb-944d-412b9b5b22ac.png)
Because Mac is Retina Screen.

**Comment by zoubeihua** [comment]
> ![图像](https://user-images.githubusercontent.com/8766034/124766065-26c5f600-df69-11eb-944d-412b9b5b22ac.png)
> 因为 Mac 是 Retina 屏幕。

您好 那我怎么解决win系统生成pdf模糊问题呢？ 加scale属性吗？

**Comment by hellohejinyu** [comment]
> > ![图像](https://user-images.githubusercontent.com/8766034/124766065-26c5f600-df69-11eb-944d-412b9b5b22ac.png)
> > 因为 Mac 是 Retina 屏幕。
> 
> 您好 那我怎么解决win系统生成pdf模糊问题呢？ 加scale属性吗？

Yes, you can set the scale property to 2 or 3

**Comment by zoubeihua** [comment]
> ![图像](https://user-images.githubusercontent.com/8766034/124766065-26c5f600-df69-11eb-944d-412b9b5b22ac.png)
> 因为 Mac 是 Retina 屏幕。

非常感谢已经解决了
