### ISSUE TITLE
Problem with Persian/Arabic fonts

### ISSUE THREAD

**Issue by erfanmola** [niklasvh/html2canvas#2556]
Hi, Im using the latest version available right now, It has problem with persian charachters and fonts, it misplaces dots and commas, spaces and etc

It also stretches some words like : 
سلام
to : 
ـسلامـ

Here is how it should look like (HTML) :
![](https://s19.picofile.com/file/8437744242/Smushed_Untitled.png)

And here is how it looks like (HTML2Canvas) :
![](https://s18.picofile.com/file/8437744234/Smushed_Story_1_.png)

**Comment by niklasvh** [comment]
Can you please retest with 1.3.1 which has RTL support. If the issue still persists, please make a new ticket and include a repro on jsfiddle.
