### ISSUE TITLE
The picture is misplaced and the picture does not display

### ISSUE THREAD

**Issue by Tzyito** [niklasvh/html2canvas#2557]
* html2canvas version tested with: 1.0.0
 * Browser & version: chrome 91.0.4472.114
 * Operating system: mac
 Q:
After opening the disabled cache of the console to download the picture, the picture will be displayed normally, but the picture downloaded without turning on the disabled cache will be misplaced
not only that
The pictures downloaded locally and online are different

**Comment by Modestiny** [comment]
i have the same problem
