### ISSUE TITLE
Html2canvas returning blank white image when taking a screenshot

### ISSUE THREAD

**Issue by imabhijith25** [niklasvh/html2canvas#2560]
I have nested divs, but when I try to take a screenshot of the outermost div, it just returns a blank white screen with the size of the outer div.
This is the div that I have
I am trying to take the screenshot of tweetcorner div.
(PS) It works fine on mobile devices but on larger screens it just gives blank white image

The HTML:

    <div id="tweetcorner">
        <div id="infopanel">
            <div id="dp" class="dp">
            <div id="usernames">
                <div id="namefield">
                    <p id="name">Name</p>
                    <div id="valid">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M22.5 12.5C22.5 10.92 21.625 9.55 20.352 8.9C20.506 8.465 20.59 7.995 20.59 7.5C20.59 5.29 18.88 3.502 16.772 3.502C16.302 3.502 15.852 3.586 15.436 3.752C14.818 2.415 13.51 1.5 12 1.5C10.49 1.5 9.18402 2.417 8.56302 3.75C8.14802 3.585 7.69702 3.5 7.22702 3.5C5.11702 3.5 3.40902 5.29 3.40902 7.5C3.40902 7.994 3.49202 8.464 3.64602 8.9C2.37402 9.55 1.49902 10.918 1.49902 12.5C1.49902 13.995 2.28102 15.298 3.44102 15.986C3.42102 16.156 3.40902 16.326 3.40902 16.5C3.40902 18.71 5.11702 20.5 7.22702 20.5C7.69702 20.5 8.14702 20.414 8.56202 20.25C9.18202 21.584 10.488 22.5 11.999 22.5C13.511 22.5 14.817 21.584 15.436 20.25C15.851 20.413 16.301 20.498 16.772 20.498C18.882 20.498 20.59 18.708 20.59 16.498C20.59 16.324 20.578 16.154 20.557 15.985C21.715 15.298 22.5 13.995 22.5 12.501V12.5ZM15.884 9.166L11.55 15.666C11.405 15.883 11.168 16 10.925 16C10.782 16 10.637 15.96 10.509 15.874L10.394 15.78L7.97902 13.365C7.68602 13.072 7.68602 12.597 7.97902 12.305C8.27202 12.013 8.74702 12.011 9.03902 12.305L10.809 14.072L14.634 8.332C14.864 7.987 15.33 7.896 15.674 8.125C16.02 8.355 16.114 8.821 15.884 9.165V9.166Z" fill="#1DA1F2"/>
                            </svg>
                    </div>
                </div>
              
                    
                <p id="atname"> @username</p>
            </div>
        </div>

        <div id="tweetpanel">
            <p id="tweet">This is the sample tweet </p>
        </div>

        <div id="dateandtime">12 PM 4 July</div>
        <div id="likes">

            <div class="likemenu">
                <div id="hearts">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12 21.638H11.986C9.40295 21.59 1.94995 14.856 1.94995 8.478C1.94995 5.414 4.47495 2.724 7.35295 2.724C9.64295 2.724 11.183 4.304 11.999 5.454C12.813 4.306 14.353 2.724 16.644 2.724C19.524 2.724 22.048 5.414 22.048 8.479C22.048 14.855 14.594 21.589 12.011 21.636H12V21.638ZM7.35395 4.225C5.27395 4.225 3.45095 6.213 3.45095 8.48C3.45095 14.22 10.485 20.076 12.001 20.138C13.519 20.076 20.551 14.221 20.551 8.48C20.551 6.213 18.728 4.225 16.648 4.225C14.12 4.225 12.708 7.161 12.696 7.19C12.466 7.752 11.54 7.752 11.309 7.19C11.295 7.16 9.88395 4.225 7.35495 4.225H7.35395Z" fill="#b5b3b3"/>
                        </svg>
                    <p id="num1">12</p>
                        
                </div>

            </div>
            <div class="likemenu">
                <div id="hearts">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M14.0459 2.24199L9.89795 2.23199H9.89595C5.52195 2.23199 2.09595 5.65899 2.09595 10.034C2.09595 14.132 5.28195 17.24 9.56095 17.404V21.232C9.56095 21.34 9.60495 21.518 9.68095 21.635C9.82295 21.86 10.0649 21.982 10.3129 21.982C10.4509 21.982 10.5899 21.944 10.7149 21.864C10.9789 21.696 17.1879 17.724 18.8029 16.358C20.7049 14.748 21.8429 12.388 21.8459 10.046V10.029C21.8399 5.66199 18.4159 2.24199 14.0459 2.24099V2.24199ZM17.8329 15.214C16.6989 16.174 12.9709 18.619 11.0609 19.857V16.67C11.0609 16.256 10.7259 15.92 10.3109 15.92H9.91495C6.25495 15.92 3.59695 13.444 3.59695 10.034C3.59695 6.49999 6.36495 3.73199 9.89695 3.73199L14.0439 3.74199H14.0459C17.5779 3.74199 20.3459 6.50799 20.3479 10.038C20.3449 11.948 19.4059 13.882 17.8339 15.214H17.8329Z" fill="#b5b3b3"/>
                        </svg>
                        
                    <p id="num2">34</p>
                        
                </div>

            </div>
            <div class="likemenu">
                <div id="hearts">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M17.53 7.46999L12.53 2.46999C12.237 2.17699 11.762 2.17699 11.47 2.46999L6.47001 7.46999C6.17601 7.76299 6.17601 8.23799 6.47001 8.52999C6.76401 8.82199 7.23701 8.82399 7.53001 8.52999L11.25 4.80999V15C11.25 15.414 11.586 15.75 12 15.75C12.414 15.75 12.75 15.414 12.75 15V4.80999L16.47 8.52999C16.616 8.67699 16.808 8.74999 17 8.74999C17.192 8.74999 17.384 8.67799 17.53 8.52999C17.823 8.23699 17.823 7.76299 17.53 7.46999V7.46999Z" fill="#b5b3b3"/>
                        <path d="M19.708 21.944H4.292C3.028 21.944 2 20.916 2 19.652V14C2 13.586 2.336 13.25 2.75 13.25C3.164 13.25 3.5 13.586 3.5 14V19.652C3.5 20.089 3.855 20.444 4.292 20.444H19.708C20.145 20.444 20.5 20.089 20.5 19.652V14C20.5 13.586 20.836 13.25 21.25 13.25C21.664 13.25 22 13.586 22 14V19.652C22 20.916 20.972 21.944 19.708 21.944V21.944Z" fill="#b5b3b3"/>
                        </svg>
                        
                    <p id="num">Share this Tweet</p>
                        
                </div>

            </div>

        </div>

These are the javascript code:

function takescreenshot(){

     let div = document.getElementById("tweetcorner")
    console.log(div.clientHeight)
    console.log("sdsd")
    html2canvas(div,{
        // width:1000,
        //  height:1000,

        allowTaint:true,
        useCORS:true
    }).then(
        function (canvas) {
            
          //  console.log(canvas)

    
            saveAs(canvas.toDataURL(),'tweet.png')
        })
}

**Comment by torrobinson** [comment]
I was just dealing with this recently and came across a random bug: if there's a custom element (web component) anywhere on my screen, html2canvas starts returning blank images from the canvas (but only in Chrome/Edge, not Firefox). I tried another dom-to-image library and the same issue occurred. I was forced to hide and then show the custom element before and after html2canvas use, which worked-around the issue. I guess check if you have any custom elements or web components on screen, because that was my problem!

**Comment by niklasvh** [comment]
`allowTaint:true` and `canvas.toDataURL()` are conflicting options, please see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by imabhijith25** [comment]
> `allowTaint:true` and `canvas.toDataURL()` are conflicting options, please see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
Even When I remove allowtaint, it gives the same blank image.

**Comment by imabhijith25** [comment]
> I was just dealing with this recently and came across a random bug: if there's a custom element (web component) anywhere on my screen, html2canvas starts returning blank images from the canvas (but only in Chrome/Edge, not Firefox). I tried another dom-to-image library and the same issue occurred. I was forced to hide and then show the custom element before and after html2canvas use, which worked-around the issue. I guess check if you have any custom elements or web components on screen, because that was my problem!

What is this web component that you are talking about? Can you please elaborate. Its also important to note that it works fine on mobile devices.

**Comment by torrobinson** [comment]
> > I was just dealing with this recently and came across a random bug: if there's a custom element (web component) anywhere on my screen, html2canvas starts returning blank images from the canvas (but only in Chrome/Edge, not Firefox). I tried another dom-to-image library and the same issue occurred. I was forced to hide and then show the custom element before and after html2canvas use, which worked-around the issue. I guess check if you have any custom elements or web components on screen, because that was my problem!
> 
> What is this web component that you are talking about? Can you please elaborate. Its also important to note that it works fine on mobile devices.

[Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) are custom elements with their own encapsulated DOM, styling, and javascript. I suspect the [shadow dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) is messing something up in libraries that attempt to copy elements and their styles out of a website. 

For example, in my case, my company is using a common shared web component of a navbar to ensure all of our apps use the same navbar that looks and behaves the same in every app.

By simply setting this navbar to `display: none`, even when it was nowhere close to (or overlapping in any way) what I was trying to "snapshot" with html2canvas, it fixed my "everything is blank white" issue.

**Comment by niklasvh** [comment]
@imabhijith25 can you create a repro on jsfiddle?

**Comment by imabhijith25** [comment]
@niklasvh https://jsfiddle.net/5Lhjuez8/. The screenshot depends on screen size and browsers. In JSFIddle it gives out partial screenshot. But in my browser, its blank

**Comment by niklasvh** [comment]
@imabhijith25 https://jsfiddle.net/et7rzkLb/ (with `useCors: false`, as the image isn't served with cors headers) renders it correctly on chrome - are you getting a different result, which browser are you using?

**Comment by imabhijith25** [comment]
@niklasvh Im stil getting a partial image. I am using chrome.

**Comment by ttthub** [comment]
@imabhijith25 Please could you confirm what was the final solution that worked for you?

**Comment by imabhijith25** [comment]
@ttthub   changed code to these




```

  let div = document.getElementById("tweetcorner")
    console.log(div.clientHeight)
    console.log("sdsd")
    html2canvas(div,{
        allowTaint: true,
        useCORS: true,
        scrollX: -window.scrollX,
        scrollY: -window.scrollY,
        windowWidth: document.documentElement.offsetWidth,
        windowHeight: document.documentElement.offsetHeight,
    }).then(
        function (canvas) {
            // console.log(canvas)
           saveAs(canvas.toDataURL(),'tweet.png')
        })
}
```

added scrollX ,scrollY, windowWidth and windowHeight
