### ISSUE TITLE
reder canvas element using html2canvas

### ISSUE THREAD

**Issue by samael205** [niklasvh/html2canvas#2561]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I am trying to create a pdf, containing an image of my application screen containing a canvas element, that you can work with.

Every time I print the screen, the canvas looks blank, for example and I also have a map, which is loaded on the page itself from an iframe and is not visible either.

My code is the following

`contenedorCanvas = document.querySelector("#contenting");
       html2canvas(document.body) // Llamar a html2canvas y pasarle el elemento
.then(htmltwocanvas => {
      contenedorCanvas.appendChild(htmltwocanvas); // Lo agregamos como hijo del div
    });`

### Specifications:

 * html2canvas version tested with: 1.0.0
 * Browser & version: Chrome  91.0.4472.124
 * Operating system: Windows 10 64Bit
![LplTF](https://user-images.githubusercontent.com/649740/124775340-d5a10c80-df3e-11eb-90e4-58395f6dde3b.png)

**Comment by niklasvh** [comment]
Without a repro steps and logs there really isn't anything that I can do to triage this further
