### ISSUE TITLE
html2canvas returns a cached value in a loop

### ISSUE THREAD

**Issue by WillHaRSI** [niklasvh/html2canvas#2562]
Using version 1.0.0, 

When using html2canvas on the same div, each time after making changes to the div in a loop (changing text and image) the output is always the same as the first instance. Console logged the div to make sure changes were implemented. 

example:

for (let divText of divTexts) {
  document.getElementById('printViewLocationName').innerHTML = 'A' + Math.random().toString(36).substring(2);
  html2canvas(document.getElementById('printViewLocation')); 
  // only renders the first time and stores it, returning first render on sequential requests.
}

**Comment by niklasvh** [comment]
Im unable to repro: https://jsfiddle.net/p9zdhu3b/

If you are experiencing different results, please make a runnable example.
