### ISSUE TITLE
iphone12 14.6 toDataURL data:,

### ISSUE THREAD

**Issue by yuandalu** [niklasvh/html2canvas#2563]
对于短图，toDataURL 正常
对于长图，toDataURL生成无效的data:,
大约高度在10000就不行了，
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size
按规范 268,435,456 pixels (i.e., 16,384 x 16,384)  但是远远没达到

**Comment by niklasvh** [comment]
See https://html2canvas.hertzen.com/faq#why-is-the-produced-canvas-empty-or-cuts-off-half-way-through
