### ISSUE TITLE
for循环多次调用html2canvas，引起报错

### ISSUE THREAD

**Issue by xu1227063131** [niklasvh/html2canvas#2570]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

![image](https://user-images.githubusercontent.com/32931014/125307339-8efa4a80-e362-11eb-99b1-d998d8482c1a.png)
使用for循环多次创建html元素并调用html2canvas，当for循环在60次以上，就会引起报错【Uncaught (in promise) Error: No logger instance found with id 17a9b291a64】、【 at Function.Logger.getInstance (D:\_dev\BOSGeo_deving\node_modules\html2canvas\dist\html2canvas.js:2413)】并且报错的那一次返回的promise状态为reject；

for循环调用html2canvas的代码如下：
` let ele = document.createElement('div');
    // let id = createGuid();
    let id = 'test' + num;
    ele.id = id;

    ele.style.width = width + 'px';
    ele.style.height = height + 'px';

    let text = `<div class='PointContainer' style="width: 256px; height:64px; position: absolute; z-index:1000;">
                    <span class="pointIcon"></span>
                    <span class="pointText">王府井123王府</span>
                </div>`;
    ele.innerHTML = html || text;
    document.getElementById('html2canvasCollection').appendChild(ele);
    document.body.style.overflow = 'hidden';

    html2canvas(document.querySelector('#' + id), {
        backgroundColor: "transparent"
    }).then(canvas => {

        console.log(canvas.toDataURL());

    });`

   Thank You So Much ！
### Specifications:

 * html2canvas version tested with: 1.1.1
 * Browser & version: chrome 91.0.4472.124 (正式版本) （64 位）
 * Operating system: win10

**Comment by niklasvh** [comment]
Fixed in #2575

**Comment by xu1227063131** [comment]
thank u so so much,  when will fix this bug in new release version?

**Comment by niklasvh** [comment]
Ill cut a new release tonight

**Comment by xu1227063131** [comment]
so great

**Comment by xu1227063131** [comment]
您好，当我使用for循环调用该接口500次的时候，会很慢，有时候会发生浏览器卡死的现象，请问应该怎么处理呢？ win10， chrome

Hello, when I use the for loop to call this interface 500 times, it will be very slow, and sometimes the browser may freeze. What should I do? win10, chrome
