### ISSUE TITLE
The text in the drop-down list box cannot be captured normally

### ISSUE THREAD

**Issue by davidwhite-www** [niklasvh/html2canvas#2578]
### Bug reports:
The text in the drop-down list box cannot be captured normally.
![bug](https://user-images.githubusercontent.com/61372816/125589177-d621d4f1-f8b2-48f0-a221-12c3ef79bb61.png)

### Specifications:
 * html2canvas version tested with: 1.10, 1.11 and 1.12
 * Browser & version:  chrome
 * Operating system:  Windows 10

**Comment by chixin06** [comment]
i have same issues, how to fixed

**Comment by arshad457** [comment]
i used 1.1.0 virson and solved my problem i ting html2canve team working to upgrade it but it showing issue old virson is good working perfectly

**Comment by davidwhite-www** [comment]
The problem still exists in 1.1.4
