### ISSUE TITLE
Mobile browser will add line feed

### ISSUE THREAD

**Issue by kooriookami** [niklasvh/html2canvas#2597]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

This bug can be reproduced in **mobile browsers**. I tried to make a minimal demo but failed. Also I found version **1.0.0** is OK.

![image](https://user-images.githubusercontent.com/38392315/126029941-4d9c06f4-8cd8-459f-9236-36794862615d.png)

![image](https://user-images.githubusercontent.com/38392315/126029927-6a50eefe-d7d7-471e-8eec-cff46c48ea95.png)

### Specifications:

 * html2canvas version tested with: 1.1.0~1.1.4
 * Browser & version: Edge 45
 * Operating system: Android 11

**Comment by niklasvh** [comment]
Can you share an example on jsfiddle?

**Comment by kooriookami** [comment]
> Can you share an example on jsfiddle?

I have no idea to reproduce this issue. I tried to make a minimal demo, but it's not work.

**Comment by AgentSmith0** [comment]
Is it possible to share a link of the page you have tried this on? Or can you send the pages source code?

**Comment by kooriookami** [comment]
> Is it possible to share a link of the page you have tried this on? Or can you send the pages source code?

Yes, here is the link. But the page is in Chinese, please understand :D. **It only reproduces in mobiles. Such as android system.**
https://tools.kooriookami.top/#/yugioh
![image](https://user-images.githubusercontent.com/38392315/126337585-7aab5ab9-4fb5-4373-b3fd-044d4d77fcc8.png)
Also, here is the code.
https://github.com/kooriookami/tools-vue/blob/master/src/views/yugioh/Yugioh.vue
The export function is in line 590.

**Comment by xiaoguoaa** [comment]
I also have this problem. I found that this problem occurs when the fontsize setting is relatively large.
This problem also occurs when I try this on the official website (H1 "h2ml2canvas" adds the style "font size: 72px")：
![image](https://user-images.githubusercontent.com/24502798/128666481-a24f2a97-ea36-47d9-9b46-e908ebca3340.png)
![image](https://user-images.githubusercontent.com/24502798/128666549-aabf47b2-453b-484a-9870-8aa9915d0004.png)

**Comment by kooriookami** [comment]
> I also have this problem. I found that this problem occurs when the fontsize setting is relatively large.
> This problem also occurs when I try this on the official website (H1 "h2ml2canvas" adds the style "font size: 72px")：
> ![image](https://user-images.githubusercontent.com/24502798/128666481-a24f2a97-ea36-47d9-9b46-e908ebca3340.png)
> ![image](https://user-images.githubusercontent.com/24502798/128666549-aabf47b2-453b-484a-9870-8aa9915d0004.png)

@niklasvh Hi, can you look at this. May be this is a good example.

**Comment by daniel-dia** [comment]
Also having same problem

https://codepen.io/daniel-dia/pen/KKmjwEw

Image comparing "original" to "screenshot"

![image](https://user-images.githubusercontent.com/2263037/129822628-5de09d9d-92d1-4e05-9b01-2278839b41f3.png)

**Comment by daniel-dia** [comment]
I temporarily solved the problem for me 'forcing' screen width to a higher value while taking the screenshot, THEN unset later.

```
const canvas = await html2canvas(element, { onclone: (doc, el) => { document.body.style.width = '1024px';  }});
document.body.style.width = 'unset';
```

the screen do a little glitch when screenshotting. but solves the problem 

I consider this problem as a 'dirty workaround' to solve this bug

**Comment by kooriookami** [comment]
> I also found that at the function `parseMetrics` the line `const baseline = img.offsetTop - span.offsetTop + 2;` changes the `baseline` variable depending on the window width.

I have no idea why `const baseline = img.offsetTop - span.offsetTop + 2;` needs `+2`. It will cause texts a little offset.
