### ISSUE TITLE
Problems with mdb input component

### ISSUE THREAD

**Issue by AgentSmith0** [niklasvh/html2canvas#2601]
### Bug reports:

MDB input component not drawn correctly: https://mdbootstrap.com/snippets/standard/agentsmith/3198947

### Specifications:

 * html2canvas version tested with: 1.1.4 (latest)
 * Browser & version: Firefox ESR (78.12.0esr (64-Bit))
 * Operating system: Linux

**Comment by niklasvh** [comment]
This appears to be fixed with https://github.com/niklasvh/html2canvas/pull/2659
