### ISSUE TITLE
Problem with mdb form-outline textarea

### ISSUE THREAD

**Issue by AgentSmith0** [niklasvh/html2canvas#2608]
### Bug reports:

The textarea with floating label inside a form-outline class is not drawing correctly: https://mdbootstrap.com/snippets/standard/agentsmith/3204104

### Specifications:

 * html2canvas version tested with: 1.1.4 (latest)
 * Browser & version: Chromium 90.0.4430.212 and latest Firefox ESR
 * Operating system: Linux

**Comment by niklasvh** [comment]
This his fixed with https://github.com/niklasvh/html2canvas/pull/2659
