### ISSUE TITLE
 Error loading image

### ISSUE THREAD

**Issue by Julycc41** [niklasvh/html2canvas#2609]
When I use the screenshot tool, I find an Error loading image.  
 
![image](https://user-images.githubusercontent.com/80231740/126450997-733b7162-2d9c-41f5-a2ec-b066ec255eb3.png)
![image](https://user-images.githubusercontent.com/80231740/126451045-98745cd7-5762-4132-a2aa-e690c1937216.png)

**Comment by niklasvh** [comment]
Please provide a repro on jsfiddle. I suspect your server isn't sending the images with cors headers, but you are using `useCORS`

**Comment by Hhpon** [comment]
> Please provide a repro on jsfiddle. I suspect your server isn't sending the images with cors headers, but you are using `useCORS`

How to detect whether the server sends headers with cors?
html2canvas is working on my macos, but it's not work in my iphone 11 ios 14.4
Error message "Error loading background-image" "Error loading image"

**Comment by li1753846989** [comment]
> > 请提供关于 jsfiddle 的重现。我怀疑您的服务器没有发送带有 cors 标头的图像，但您正在使用`useCORS`
> 
> 如何检测服务器是否发送带有cors的标头？ html2canvas 在我的 macos 上工作，但在我的 iphone 11 ios 14.4 中不起作用 错误消息“加载背景图像时出错”“加载图像时出错”

I also encountered this problem, did you solve it?

**Comment by Alone-2** [comment]
> > Please provide a repro on jsfiddle. I suspect your server isn't sending the images with cors headers, but you are using `useCORS`
> 
> How to detect whether the server sends headers with cors? html2canvas is working on my macos, but it's not work in my iphone 11 ios 14.4 Error message "Error loading background-image" "Error loading image"

I also encountered this problem, did you solve it?

**Comment by Hhpon** [comment]
> > > Please provide a repro on jsfiddle. I suspect your server isn't sending the images with cors headers, but you are using `useCORS`
> > 
> > 
> > How to detect whether the server sends headers with cors? html2canvas is working on my macos, but it's not work in my iphone 11 ios 14.4 Error message "Error loading background-image" "Error loading image"
> 
> I also encountered this problem, did you solve it?

I later checked that it was indeed a cross-domain problem.
It should solve the problem of cross-domain. My solution is to use Nginx to proxy image requests

**Comment by Alone-2** [comment]
> > > > Please provide a repro on jsfiddle. I suspect your server isn't sending the images with cors headers, but you are using `useCORS`
> > > 
> > > 
> > > How to detect whether the server sends headers with cors? html2canvas is working on my macos, but it's not work in my iphone 11 ios 14.4 Error message "Error loading background-image" "Error loading image"
> > 
> > 
> > I also encountered this problem, did you solve it?
> 
> I later checked that it was indeed a cross-domain problem. It should solve the problem of cross-domain. My solution is to use Nginx to proxy image requests
thanks，The problem has been solved in your way
