### ISSUE TITLE
The picture is not complete

### ISSUE THREAD

**Issue by Julycc41** [niklasvh/html2canvas#2610]
Convert canvas to base64 image ,When rendered on the page, it is not completely displayed
![image](https://user-images.githubusercontent.com/80231740/126453454-04f21510-bccd-47c5-a808-ae3f3dd9954c.png)

**Comment by ihavecoke** [comment]
base64 string too big?

**Comment by Julycc41** [comment]
I think it should be, the problem is not solved, I changed a plug-in implementation

**Comment by Julycc41** [comment]
> base64 字符串太大？

I think it should be, the problem is not solved, I changed a plug-in implementation

**Comment by niklasvh** [comment]
Can you provide a repro on jsfiddle? There are plenty of examples of base64 images rendering just fine...
