### ISSUE TITLE
html2canvas display resolution

### ISSUE THREAD

**Issue by okeoke85** [niklasvh/html2canvas#2614]
When i set my display resolution to 800x600 i have corrupted results, actualy results change according to resolution is there a way to stabilaze results with f.e scale option, and like %10 of attempts i have corrupted results with same inputs

Results with 1920x1080(which is desired);

![image](https://user-images.githubusercontent.com/15729538/127331881-6df93bfd-b3f0-46ed-b763-773679561f45.png)

Result with 800x600;

![image](https://user-images.githubusercontent.com/15729538/127331778-d82fc161-34da-4963-9c15-86bc9d50b0ca.png)

You can reproduce by changeing your screen resolution.

Best.

**Comment by Rudii2115** [comment]
Following

**Comment by niklasvh** [comment]
Without a jsfiddle repro, it's hard to say what the issue is (it could be that your css/dom doesn't for example with into 800x600)
