### ISSUE TITLE
How to improve clarity

### ISSUE THREAD

**Issue by godwei123** [niklasvh/html2canvas#2619]
* html2canvas version tested with:  version 1.1.4
 * Browser & version: google chrome 
 * Operating system: Mac M1

**I do not want to enlarge the generated image, how to improve the sharpness, dPI seems to have no this configuration item.** 

```js
html2canvas(targetElement.value, {
        allowTaint: false,
        useCORS: true,
        taintTest: false,
        letterRendering: true,
        imageTimeout: 0,
        scale: 1,
      })
        .then((canvas) => {
         //...
        })
        .catch((err) => {
          console.log(err);
        });
```

**Comment by biel-fyq** [comment]
Have you solved this problem yet
