### ISSUE TITLE
文字重叠

### ISSUE THREAD

**Issue by hejun311** [niklasvh/html2canvas#2623]
文本超过两行时，使用组件生成图片时，第二行的首个字会重叠在第一行上  这个问题在手机浏览发生  在谷歌浏览器没问题

"html2canvas": "^1.1.5",

**Comment by String1991** [comment]
我也遇到了，换1.0.0版本，设置letter-spacing: 1px就好了

**Comment by hejun311** [comment]
1.0.0

> 我也遇到了，换1.0.0版本，设置letter-spacing: 1px就好了

我昨天也已经切回来了  目前来看没问题

**Comment by JohnNashs** [comment]
我也遇到了，我把每个字符取出来都套了个span标签，然后正常了

**Comment by xiewl** [comment]
> 我也遇到了，我把每个字符取出来都套了个span标签，然后正常了

Thanks a lot

**Comment by gerow-hi** [comment]
+1

**Comment by flwzz** [comment]
1.0.0版本有透明度的问题。。。

**Comment by pxmage** [comment]
> 我也遇到了，我把每个字符取出来都套了个span标签，然后正常了

兄弟，太好使了，you just saved my ass！

**Comment by LaiLa06** [comment]
我将版本回退了，好使了，每个字符都是span标签 是不是先很慢啊

**Comment by JohnNashs** [comment]
您的邮件已收到，谢谢——傅宇敏
