### ISSUE TITLE
html2canvas started throwing build error since its latest release

### ISSUE THREAD

**Issue by ujjwal2190** [niklasvh/html2canvas#2628]
We use "html2canvas": "^1.1.4" and Node-14.15
in our package.json and not sure if this has to do with latest 1.2.0 version released three hours ago but since then we are seeing build failures with below errors :-
ERROR in [96mnode_modules/html2canvas/dist/types/core/cache-storage.d.ts[0m:[93m1[0m:[93m13[0m - [91merror[0m[90m TS1005: [0m'=' expected.

[7m1[0m import type { Context } from './context';
[7m [0m [91m            ~[0m
[96mnode_modules/html2canvas/dist/types/core/cache-storage.d.ts[0m:[93m1[0m:[93m30[0m - [91merror[0m[90m TS1005: [0m';' expected.

[7m1[0m import type { Context } from './context';
[7m [0m [91m                             ~~~~~~~~~~~[0m

Any idea why this could be?

**Comment by niklasvh** [comment]
Type imports are only supported by[ TypeScript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) or higher.
