### ISSUE TITLE
Bad performances ?

### ISSUE THREAD

**Issue by ghost** [niklasvh/html2canvas#263]
Hello, I found your repository 2 days ago and I integrated into an open-source webserver website.

When I click on the menu in the header, the rendering is slow. Sometimes the browser (Chrome for me) randomly crash after I clicked on the button.

This is normal ?

URL:
http://xzero.io

Thanks,

**Comment by ArcaneEngineer** [comment]
I'm genuinely intrigues that googling "html2canvas slow" turns up several results at once, and yet this has never actually been _properly_ addressed by the author, at least through looking into culprit code and understanding why it takes so long and what can be done about it. Is it just me that thinks this is strange? I would think you would take pride in an otherwise very useful library, and want to improve it.

**Comment by niklasvh** [comment]
@ArcaneEngineer I am not sure where you gathered that it wouldn't be clear where the bulk of the time for creating a render goes. The reason why it is slow is **very clear**, that doesn't mean that it could be properly addressed. Firstly, unless you want html2canvas to manipulate almost every single DOM node on your document, it requires the whole DOM to be cloned to a seperate window context where it can freely mutate it without requiring the original to be touched, which in itself already can take ~100ms. Parsing every single DOM node/pseudonode and their computed CSS values and the position on the document takes some time as well, but what really is the performance killer is measuring/rendering text. There are no proper low level APIs that allow you to properly measure text wrapping, or even render with letter spacing, which means that to do letter based rendering you may potentially be required to measure the bounds of every single letter on the document. You could potentially start parsing font files manually and calculate the size of glyphs yourself, but then you would get more issues about why the library is half a mb in size and why the author hasn't properly addressed the size of it.

**Comment by ArcaneEngineer** [comment]
OK. So the software rendering is the real killer here... is this a per-pixel cost?

I have a minimal test case set up with a single <p> tag of 300x75 pixel and it takes between 200-400ms to render to canvas on an old E2160 dual core system.

**Comment by raphaelfavier** [comment]
For those stumbling upon this thread years later, consider using html-to-image instead

https://betterprogramming.pub/heres-why-i-m-replacing-html2canvas-with-html-to-image-in-our-react-app-d8da0b85eadf

**Comment by webpig** [comment]
> For those stumbling upon this thread years later, consider using html-to-image instead
> 
> https://betterprogramming.pub/heres-why-i-m-replacing-html2canvas-with-html-to-image-in-our-react-app-d8da0b85eadf

html-to-image is good, but it will load all fonts.
