### ISSUE TITLE
iOS15 failed to generate picture

### ISSUE THREAD

**Issue by H-Sven** [niklasvh/html2canvas#2633]
iOS15 failed to generate picture

In iOS15 system, it takes a long time to generate pictures, and the generated pictures lack content.

Lost all text and some pictures

**Comment by H-Sven** [comment]
Find the cause of the problem, because the HTML contains Chinese. Replace the Chinese with numbers or words to render normally

I hope to fix this bug as soon as possible

**Comment by H-Sven** [comment]
@niklasvh    Please look at this question

**Comment by H-Sven** [comment]
My project is about to be published. This problem makes it impossible to publish

**Comment by niklasvh** [comment]
I don't have an iOS 15 device to test with and github actions don't support [macos 11 / ios 15 simulators yet.](https://github.com/niklasvh/html2canvas/pull/2564), so without being able to repro this it's quite difficult to start fixing it.

**Comment by niklasvh** [comment]
@H-Sven The iOS 15 simulator tests work fine with Chinese, see for example https://html2canvas.hertzen.com/tests/?browser=Safari_IOS_15&test=/tests/reftests/text/lang/chinese.html. Could you provide a repro of the bug on jsfiddle?

**Comment by H-Sven** [comment]
@niklasvh The simulator cannot reproduce this problem. You need to check the phenomenon on the real device

**Comment by H-Sven** [comment]
@niklasvh  I have found the reason for the bug!
This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
```
#app {
  font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
}
```

**Comment by h330894169** [comment]
> @niklasvh I have found the reason for the bug!
> This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> 
> ```
> #app {
>   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> }
> ```

[https://github.com/niklasvh/html2canvas/issues/2547](url)

Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.

**Comment by H-Sven** [comment]
> > @niklasvh I have found the reason for the bug!
> > This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> > ```
> > #app {
> >   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> > }
> > ```
> 
> [https://github.com/niklasvh/html2canvas/issues/2547](url)
> 
> Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.

thank

**Comment by h330894169** [comment]
> > > @niklasvh I have found the reason for the bug!
> > > This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> > > ```
> > > #app {
> > >   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> > > }
> > > ```
> > 
> > 
> > [https://github.com/niklasvh/html2canvas/issues/2547](url)
> > Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.
> 
> thank

是这个原因吗？我也不确定，是不是把 -apple-system 字体干掉就行了？

**Comment by H-Sven** [comment]
> > > > @niklasvh I have found the reason for the bug!
> > > > This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> > > > ```
> > > > #app {
> > > >   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> > > > }
> > > > ```
> > > 
> > > 
> > > [https://github.com/niklasvh/html2canvas/issues/2547](url)
> > > Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.
> > 
> > 
> > thank
> 
> 是这个原因吗？我也不确定，是不是把 -apple-system 字体干掉就行了？

是的，我是vue项目，引入了vant组件， vant组件的样式里面设置了-apple-system字体，我给根元素设置了font family覆盖vant组件的font family就好了

**Comment by helsonxiao** [comment]
It's really working after `-apple-system` is removed!

**Comment by BradleyVangelder** [comment]
where can I remove the -apple-system

**Comment by wyysf123** [comment]
> > > > > @niklasvh I have found the reason for the bug!
> > > > > This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> > > > > ```
> > > > > #app {
> > > > >   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > [https://github.com/niklasvh/html2canvas/issues/2547](url)
> > > > Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.
> > > 
> > > 
> > > thank
> > 
> > 
> > 是这个原因吗？我也不确定，是不是把 -apple-system 字体干掉就行了？
> 
> 是的，我是vue项目，引入了vant组件， vant组件的样式里面设置了-apple-system字体，我给根元素设置了font family覆盖vant组件的font family就好了

在mac上safari15的预览版上，html2canvas会导致页面挂掉，我的代码里面也没有-apple-system字体。

**Comment by amqqliang** [comment]
> > @niklasvh I have found the reason for the bug!
> > This is a bug caused by IOS 15 system font. The solution is to set "font family" in the root node
> > ```
> > #app {
> >   font-family: Helvetica, Tahoma, Arial, 'PingFang SC', 'Hiragino Sans GB', 'Heiti SC', STXihei, 'Microsoft YaHei',SimHei;
> > }
> > ```
> 
> [https://github.com/niklasvh/html2canvas/issues/2547](url)
> 
> Check "-apple-system" in "Font Family". In iOS 15, using "-apple-system" will cause canvas rendering to fail.

Could you tell me how you found out?

**Comment by qsjc** [comment]
楼上的全局搜索一下呀  -apple-system 以及system-ui 这俩都要去掉 然后在ios15上就好使了

**Comment by ArtemisGraphic** [comment]
I'm using an old version and I have this issue, I'm not using chinese fonts however, how do I fix this?

**Comment by gauravkeerthi** [comment]
This fix doesn't seem to work for me.
I don't have `-apple-system` declared as a font anywhere. Just in case, I set the root font-family for #app as a Google Font that I imported in the same css file.  Still didn't work. I'm only using english fonts.
The function works fine on Android and Desktop, but fails on IOS15 (Chrome and Safari). 

Any other ideas?

**Comment by hansanwok** [comment]
In my case, I define other font-family, I just remove 'san-serif'
  font-family: 'Mulish', sans-serif;
=>>  font-family: 'Mulish'
