### ISSUE TITLE
ios15系统下，似乎不支持中文

### ISSUE THREAD

**Issue by H-Sven** [niklasvh/html2canvas#2634]
在ios15版本，如果元素中有中文，会导致生成图片的时间非常慢，并且生成的图片不会显示所有中文，并且img图片也会丢失

 in iOS15

**Comment by H-Sven** [comment]
确定了！！  如果dom中有中文，在iOS15系统下， 将导致无法渲染文字和图片！！！！

**Comment by H-Sven** [comment]
这个BUG排斥了我6个小时， 一次偶然的情况下，我把标签中的中文全部删掉缓存了一串11111111，就正常渲染了

**Comment by niklasvh** [comment]
The CI with iOS 15 simulator renders chinese just fine https://html2canvas.hertzen.com/tests/?browser=Safari_IOS_15&test=/tests/reftests/text/lang/chinese.html, could you please provide a repro of where it doesn't work.

**Comment by tianlei1990** [comment]
我也遇到这个问题，有中文直接会自动刷新页面
