### ISSUE TITLE
Unhandled Rejection (RangeError): Invalid code point NaN

### ISSUE THREAD

**Issue by ye33** [niklasvh/html2canvas#2639]
<li> with pseudo-elements(like: ::before) will cause this error
![error](https://user-images.githubusercontent.com/42855949/128680326-6d1cea45-cb9a-4ad7-a449-ba22f9f6d52e.jpg)

**Comment by niklasvh** [comment]
Can you please share a repro. [There are plenty of pseudo elements working just fine](https://html2canvas.hertzen.com/tests/?browser=Chrome_Stable&test=/tests/reftests/pseudoelements.html), so would need more details as how to reproduce this.

**Comment by ye33** [comment]
`li {
  display: flex;

  &::before {
    content: counter(ol0) '. ';
    counter-increment: ol0;
  }

  &:first-child {
    counter-reset: ol0;
  }
}`，we have  the above css, then it happened

**Comment by niklasvh** [comment]
@ye33 can you setup a full example at jsfiddle or codepen? Thanks

**Comment by ye33** [comment]
@niklasvh , http://jsfiddle.net/0ocwLuhy/8/
