### ISSUE TITLE
Need to remove workaround for Webkit CORS bug

### ISSUE THREAD

**Issue by kevinmtrowbridge** [niklasvh/html2canvas#264]
Hi Niklas,

Thanks for your library, it obviously took a good deal of work and with bleeding edge technology as well.

I would really like to use it for my project http://happybirthdayyousuck.com, (my business partner is paranoid so there is a temporary login: hbys / immortality) ... but I am struggling with getting CORS to work with images that are stored on S3.  It's strange because one out of three images appear in the rendered canvas, but the other two do not, and it's not clear to me what the difference between them is.

By setting breakpoints and stepping through the code, I noticed that the images that fail to load, seem to be cached, that is, they are not re-downloading in Chrome's Network tab during the loadImage method.  The image that does load, is re-downloading.

So, to try and move the issue forward, I attached a cachebusting parameter to the method that tries to do the CORS loading, like so:

```
} else if ( supportCORS && !options.allowTaint && options.useCORS ) {
    // attempt to load with CORS

    img.crossOrigin = "anonymous";
    imageObj = images[src] = {
        img: img
    };
    images.numTotal++;
    setImageLoadHandlers(img, imageObj);
    // added 'cachebuster' parameter in line below.
    img.src = src + "?cachebuster=" + new Date().getTime();
```

... at this point the images download, but now I am running into exceptions like:

Uncaught TypeError: Cannot read property 'length' of null 

See screenshot:

![happy birthday you suck -1](https://f.cloud.github.com/assets/486640/1063324/0ad643a6-12a7-11e3-891f-0cf0c57197ef.jpg)

... I comment out more text rendering code until the render call completes with no exceptions, but at this point the canvas is blank (tainted?).

Any advice for getting this to work?  I really appreciate your help.

Thanks,
Kevin

**Comment by gauravmishra24** [comment]
Hi @niklasvh,

I am fetching the images from CMS(Contentful) in my HTML and then trying to generate PDF of that HTML.
But in the generated PDF, images are missing.(seems to be an issue of cross origin).
Please suggest me how can i get rid of this issues.
Below is my code-:

function downloadPDF() {
var canvasToImage = function(canvas){
var img = new Image();
var dataURL = canvas.toDataURL('image/png');
img.crossOrigin = "Anonymous";
img.src = dataURL;
return img;
};

var canvasShiftImage = function(oldCanvas,shiftAmt){
shiftAmt = parseInt(shiftAmt) || 0;
if(!shiftAmt){ return oldCanvas; }

var newCanvas = document.createElement('canvas');
newCanvas.height = oldCanvas.height - shiftAmt;
newCanvas.width = oldCanvas.width;
var ctx = newCanvas.getContext('2d');
ctx.mozImageSmoothingEnabled = false;
ctx.webkitImageSmoothingEnabled = false;
ctx.msImageSmoothingEnabled = false;
ctx.imageSmoothingEnabled = false;

var img = canvasToImage(oldCanvas);
ctx.drawImage(img,0, shiftAmt, img.width, img.height, 0, 0, img.width, img.height);

return newCanvas;
};

var canvasToImageSuccess = function(canvas){
var pdf = new jsPDF('l','px'),
pdfInternals = pdf.internal,
pdfPageSize = pdfInternals.pageSize,
pdfScaleFactor = pdfInternals.scaleFactor,
pdfPageWidth = pdfPageSize.width,
pdfPageHeight = pdfPageSize.height,
totalPdfHeight = 0,
htmlPageHeight = canvas.height,
htmlScaleFactor = canvas.width / (pdfPageWidth * pdfScaleFactor),
safetyNet = 0;

while(totalPdfHeight < htmlPageHeight && safetyNet < 15){
var newCanvas = canvasShiftImage(canvas, totalPdfHeight);
pdf.addImage(newCanvas, 'png', 0, 0, pdfPageWidth, 0, null, 'NONE');
// var alias = Math.random().toString(35);
// pdf.addImage(newCanvas, 0, 0, pdfPageWidth, 0, 'png', alias, 'NONE');

  totalPdfHeight += (pdfPageHeight * pdfScaleFactor * htmlScaleFactor);

  if(totalPdfHeight < htmlPageHeight){
      pdf.addPage();
  }
  safetyNet++;
}

var pageName = document.location.pathname.match(/[^/]+$/)[0];
pdf.save(pageName + '.pdf');
};

html2canvas($('body')[0],
{
onrendered: function(canvas){
canvasToImageSuccess(canvas);
}
});
}

Below is the image in the HTML which is missing from the generated PDF-:

<img crossOrigin="Anonymous" src="{{{cmsImageUrl}}}" alt="{{{cmsImageDesc}}}" title="{{{cmsImageTitle}}}" />

**Comment by gauravmishra24** [comment]
Hi @niklasvh,

I am fetching the images from CMS(Contentful) in my HTML and then trying to generate PDF of that HTML.
But in the generated PDF, images are missing.(seems to be an issue of cross origin).
Please suggest me how can i get rid of this issues.
Below is my code-:

function downloadPDF() {
var canvasToImage = function(canvas){
var img = new Image();
var dataURL = canvas.toDataURL('image/png');
img.crossOrigin = "Anonymous";
img.src = dataURL;
return img;
};

var canvasShiftImage = function(oldCanvas,shiftAmt){
shiftAmt = parseInt(shiftAmt) || 0;
if(!shiftAmt){ return oldCanvas; }

var newCanvas = document.createElement('canvas');
newCanvas.height = oldCanvas.height - shiftAmt;
newCanvas.width = oldCanvas.width;
var ctx = newCanvas.getContext('2d');
ctx.mozImageSmoothingEnabled = false;
ctx.webkitImageSmoothingEnabled = false;
ctx.msImageSmoothingEnabled = false;
ctx.imageSmoothingEnabled = false;

var img = canvasToImage(oldCanvas);
ctx.drawImage(img,0, shiftAmt, img.width, img.height, 0, 0, img.width, img.height);

return newCanvas;
};

var canvasToImageSuccess = function(canvas){
var pdf = new jsPDF('l','px'),
pdfInternals = pdf.internal,
pdfPageSize = pdfInternals.pageSize,
pdfScaleFactor = pdfInternals.scaleFactor,
pdfPageWidth = pdfPageSize.width,
pdfPageHeight = pdfPageSize.height,
totalPdfHeight = 0,
htmlPageHeight = canvas.height,
htmlScaleFactor = canvas.width / (pdfPageWidth * pdfScaleFactor),
safetyNet = 0;

while(totalPdfHeight < htmlPageHeight && safetyNet < 15){
var newCanvas = canvasShiftImage(canvas, totalPdfHeight);
pdf.addImage(newCanvas, 'png', 0, 0, pdfPageWidth, 0, null, 'NONE');
// var alias = Math.random().toString(35);
// pdf.addImage(newCanvas, 0, 0, pdfPageWidth, 0, 'png', alias, 'NONE');

  totalPdfHeight += (pdfPageHeight * pdfScaleFactor * htmlScaleFactor);

  if(totalPdfHeight < htmlPageHeight){
      pdf.addPage();
  }
  safetyNet++;
}

var pageName = document.location.pathname.match(/[^/]+$/)[0];
pdf.save(pageName + '.pdf');
};

html2canvas($('body')[0],
{
onrendered: function(canvas){
canvasToImageSuccess(canvas);
}
});
}

Below is the image in the HTML which is missing from the generated PDF-:

<img crossOrigin="Anonymous" src="cmsImageUrl" />
