### ISSUE TITLE
Bing Maps get broken

### ISSUE THREAD

**Issue by YerayAlonso** [niklasvh/html2canvas#2646]
I'm trying to generate an image from a Bing Maps but it gets broken:

![imagen](https://user-images.githubusercontent.com/1788228/129051541-4597095f-bbda-434b-986a-afdf2c50e6b8.png)

Here the test:
https://jsfiddle.net/norike82/tfm0v54y/

I've tried `useCORS` but it doesn't seem to make any difference.

**Comment by niklasvh** [comment]
Fixed in #2649, with setting `allowTaint: true` https://jsfiddle.net/6zcfu5da/
