### ISSUE TITLE
图片宽度过大时，超出一定宽度部分的所有元素背景颜色和svg无法渲染，显示为透明

### ISSUE THREAD

**Issue by sillypencil** [niklasvh/html2canvas#2647]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

图片宽度过大时，超出一定宽度部分的所有元素背景颜色和svg无法渲染，显示为透明，最大宽度大概在16000像素。
when the target's width is too large,  all the elements's backgroud color and svg elements which beyond limit width can not be rendered and turn out transparent. the limit width is about 16000 pixels
![html2canvas-ziped](https://user-images.githubusercontent.com/20416147/129322602-da82a00c-056e-480c-a21f-7c274126a67d.png)

### Specifications:

 * html2canvas version tested with: 1.0.0
 * Browser & version: chrome 75.0.377.0.142
 * Operating system: windows

**Comment by niklasvh** [comment]
See https://html2canvas.hertzen.com/faq regarding `Why is the produced canvas empty or cuts off half way through?`

**Comment by sillypencil** [comment]
In my case, I didn't hit the  browser limitations for the canvas size, it's 20,511 * 3,959. And I did get a canvas with 20,511 pixels width. 
However, the div elements in the right lose their background color, and the svg elements lose their fill color while border colors and texts are rendered normally.
