### ISSUE TITLE
Problems with background images

### ISSUE THREAD

**Issue by shauchenka** [niklasvh/html2canvas#265]
Hi, guys! 

Thanks for your work, h2c is an awesome tool!
I have one small issue on page: http://king.fi/site/ - background image from 
body { ... background: #070707 url(../img/bg.jpg) no-repeat 50% 0;
doesn't render. With simple calling of h2c:

```
html2canvas($('body'), {
            allowTaint: false,
            logging:true,
            onrendered: function (canvas) {
                document.body.appendChild(canvas);
            }
        });
```

and with your test console http://html2canvas.hertzen.com/screenshots.html I have the same results:

Original:
![screen shot 2013-09-04 at 5 33 03 pm](https://f.cloud.github.com/assets/2790488/1080952/03609458-156f-11e3-9f91-8031f529611a.png)

Rendered:
![screen shot 2013-09-04 at 5 33 11 pm](https://f.cloud.github.com/assets/2790488/1080951/033ef488-156f-11e3-9d1d-f6c1d464b057.png)

html2canvas: 0.4.0
MacOs 10.6 Chrome 29.0.1547.62

Thanks!

**Comment by codegiant2** [comment]
@niklasvh onrendered is deprecated. So what can I use instead? I'm using 0.5.0-alpha1.

Also the background image is not downloading though the images are in the same domain.

html2canvas($("#foredownload table"), {
                logging : true,
                onrendered: function(c) {
                    var myImage = c.toDataURL("images/jpeg");
                    $('#downloadableImage').prop('href', myImage);
                }
            });
Any help will be appreciated. Thanks

**Comment by usmonster** [comment]
@codegiant2 https://github.com/niklasvh/html2canvas#usage .

**Comment by ankitgandhi452** [comment]
Thanx fperich it worked for me!!

**Comment by AndyBoat** [comment]
@fperich 
u help me a lot!Thanks a lot!

**Comment by d-j-a-y** [comment]
I was face of a cropped body background image
(small `bounds.height`  from [`NodeContainer.prototype.parseBackgroundSize`](https://github.com/niklasvh/html2canvas/blob/master/dist/html2canvas.js#L1635) - html2canvas 0.5.0-beta3 ) my 

```
body {
	background-image: url(./res/bg.jpeg);
	background-repeat:no-repeat;
	background-position:center center;
	-o-background-size: cover;
	-moz-background-size: cover;
	-webkit-background-size: cover;
	background-size: cover;
}
```

SOLVED adding
```
html, body {
   margin: 0;
   padding: 0;
   height: 100%;
}
```

> **Thank's niklasvh and all contributor for this nice piece of code!**

**Comment by balajibecs20** [comment]
i am also having same problem ,i am loading from s3 image not showing in canvas,but i am loading locally in my system is working fine how can i solve
![screenshot_34](https://user-images.githubusercontent.com/20084575/27507967-45afac14-58f9-11e7-8ace-909d65ce4092.png)
![screenshot_35](https://user-images.githubusercontent.com/20084575/27507968-45b5b5e6-58f9-11e7-8b81-09fd9f635f9e.png)

**Comment by gopiss** [comment]
me also having the same issue. 
![border-image-issue](https://user-images.githubusercontent.com/29263009/29453029-e3fc7350-8425-11e7-960a-57914a2b0055.png)
background-image failed to load. i am getting error message **Error loading background:**

![here is my console error](https://user-images.githubusercontent.com/29263009/29452914-8829203c-8425-11e7-91d0-9a10b439c819.png)

[jsFiddle here](http://jsfiddle.net/sodofkcs/1042/)

Please help me to fix this issue.
Thanks,

**Comment by fxmontigny** [comment]
Hi @gopiss,

Use corse option.

```
html2canvas(document.body, {
            onrendered: function (canvas) {
.....
            },
            useCORS: true
        });
```

**Comment by gopiss** [comment]
@fxmontigny. 
Still the **border-image** loading issue exist. see my updated [JSFiddle](http://jsfiddle.net/sodofkcs/1047/).
border image not loading only showing black color border. 
![2017-08-23_0317](https://user-images.githubusercontent.com/29263009/29589782-3b37a892-87b4-11e7-8b25-0b8fc4f7f64a.png)

**Comment by hikmat30ce** [comment]
I am facing the same issue. below is logs from chrome console
html2canvas: Preload starts: finding background-images
html2canvas.js:21 html2canvas: start: images: 1 / 1 (failed: 0)
html2canvas.js:21 html2canvas: start: images: 2 / 2 (failed: 0)
html2canvas.js:21 html2canvas: Preload: Finding images
html2canvas.js:21 html2canvas: Preload: Done.
html2canvas.js:21 html2canvas: start: images: 2 / 2 (failed: 0)
html2canvas.js:21 Finished loading images: # 2 (failed: 0)
html2canvas.js:21 html2canvas: Error loading background:
html2canvas.js:21 html2canvas: Renderer: Canvas renderer done - returning canvas obj

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by jacobclarke92** [comment]
Just commenting as this may help someone.
My issue was that locally everything was working but on production it was failing to render css background images.
Reason was that we were using CloudFront -- which means that the urls in the css file were referring to assets on the cloudfront domain, while the JS was being executed on a seperate domain.
However html2canvas log wasn't indicating that it was a cors issue.
'useCORS' doesn't seem to work on its own as I think it requires a proxy url or something.

**Comment by RamyaGonchigar** [comment]
@jacobclarke for me also same issue in local S3 images are capturing But in production it is not capturing the background images. my html2canvas version is v1.0.0

**Comment by AlpeshB08** [comment]
I'm encountering a similar issue where images loaded from Amazon S3 aren't displaying in the canvas, although locally loaded images on my system are functioning correctly. To address this, I've found that converting the S3 images into blob URLs resolves the issue. Here's the code I used to convert HTTPS images from S3:

// Backend Code
```
import { Router } from "express";
const router = Router();
router.route("/fetch-image").get(menuController.fetchImage);

export async function fetchImage(req: Request, res: Response) {
    try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const imageUrl: any = req?.query?.url;
        https
            .get(imageUrl, (imageRes) => {
                const imageData: Buffer[] = [];

                // Setting up CORS headers
                res.setHeader("Access-Control-Allow-Origin", "*");
                imageRes.on("data", (chunk: Buffer) => {
                    imageData.push(chunk);
                });
                imageRes.on("end", () => {
                    const buffer = Buffer.concat(imageData);
                    res.set("Content-Type", "image/png"); // Assuming the image is a PNG. Adjust if necessary.
                    res.send(buffer);
                });
            })
            .on("error", (error) => {
                basicLogger.error("Error fetching image:", {
                    additionalInfo: {
                        error
                    }
                });
                res.status(500).send("Failed to fetch image");
            });
    } catch (error) {
        console.log(error);
        return res.status(500).json({ error: "Something Went Wrong" });
    }
}
```

//Front-end Code
```
const isBlobUrl = (url) => {
    return url.startsWith("blob:");
};
```

// This method allows the app to send HTTP request to the API.

```
const loadImage = async (url: any, callback: any, errorCallback: any) => {
    try {
        const response = await fetch(
            `${
                process.env.REACT_APP_API_URL
            }/menu/fetch-image?url=${encodeURIComponent(url)}`
        );
        if (!response.ok) {
            // if HTTP-status is 200-299
            // throws an Error message
            throw new Error(
                `Could not fetch ${url}, status: ${response.status}`
            );
        }

        const extension = url.split("?")[0].split(".").pop().toLowerCase();
        let image;
        if (extension.toLowerCase() === "svg") {
            const svgText = await response.text();
            image = `data:image/svg+xml,${encodeURIComponent(svgText)}`;
        } else {
            const blob = await response.blob();
            image = URL.createObjectURL(blob);
        }
        callback(image);
    } catch (error) {
        console.log("Error:: ", error);
        errorCallback(error); // This will pass any errors to the errorCallback function.
    }
};
```

// BackgroundUrl is the image URL getting from S3.

```
const [bgImageSrc, setBgImageSrc] = useState(backgroundUrl);

    useEffect(() => {
        if (!isBlobUrl(backgroundUrl)) {
            loadImage(
                backgroundUrl,
                (image) => {
                    setBgImageSrc(image);
                },
                (error) => {
                    console.log(error);
                    setBgImageSrc(backgroundUrl);
                }
            );
        } else {
            setBgImageSrc(backgroundUrl);
        }
    }, [backgroundUrl]);
```
