### ISSUE TITLE
html2canvas "offsets" text when font is big enought and screen is width of mobile screen

### ISSUE THREAD

**Issue by daniel-dia** [niklasvh/html2canvas#2666]
### Bug reports:

html2canvas "offsets" text when font is big enought and screen is mobile;

Tested with a small mobile screen width and font size of 100px;
The problem does not occurs when screen is larger and it does not depends on the size of the container.

sample following

https://codepen.io/daniel-dia/pen/KKmjwEw

Image comparing "original" to "screenshot"

![image](https://user-images.githubusercontent.com/2263037/129822628-5de09d9d-92d1-4e05-9b01-2278839b41f3.png)

### Specifications:

 * html2canvas version tested with: 1.3.2
 * Browser & version: chrome 92, edge 92, firefox developer edition
 * Operating system: windows, android and ios

**Comment by kooriookami** [comment]
I have this problem too. #2597

**Comment by ArvinChen9539** [comment]
change to 1.0.0-rc.1 version
