### ISSUE TITLE
Why does this error happen?

### ISSUE THREAD

**Issue by AlbaSS18** [niklasvh/html2canvas#2669]
### Bug reports:

Hello. I'm using html2canvas in my project with Angular. When I take a screenshot, this error displays in the console.

![image](https://user-images.githubusercontent.com/46462037/130058774-116fc5fc-4037-4e6b-b7cb-ff6c8833c8aa.png)

Why does this error happen?

Despite this error, the pdf is generated well but I don't know why this error display.

I mix html2canvas with jsPDF. This is my code:

 ```
print(event){
    const pdfTable = document.getElementById('table_organizations_service');

    html2canvas(pdfTable).then(canvas => {
        const contentDataURL = canvas.toDataURL('image/png')  
        let pdf = new jsPDF('l', 'cm', 'a4'); //Generates PDF in landscape mode
        pdf.addImage(contentDataURL, 'PNG', 0, 0, 29.7, 21.0);  
        pdf.save('assigment.pdf');   
    });
  }
```

### Specifications:

 * html2canvas version tested with: 1.3.2
 * Browser & version: Firefox - 91.0
 * Operating system: Ubuntu

**Comment by niklasvh** [comment]
Please share a repro on jsfiddle.net
