### ISSUE TITLE
1.3.2 ios Phone text line break,blank space

### ISSUE THREAD

**Issue by yingqiang006** [niklasvh/html2canvas#2670]
1.3.2 ios Phone text line break,blank space
![Uploading 微信图片_20210820190025.jpg…]()

**Comment by yingqiang006** [comment]
Normal condition
测试数据测试数据测
试数据
IOS Abnormal condition
测试数据测试数据测
    试数据

**Comment by emon100** [comment]
所有的字一个个放进span，可以绕过这个问题。

**Comment by laozb** [comment]
> 所有的字一个个放进span，可以绕过这个问题。

多谢，搞了半天终于找到解决方案了

**Comment by chuliul** [comment]
> 所有的字一个个放进span，可以绕过这个问题。

后台返回的富文本内容里有span标签，该如何处理？
