### ISSUE TITLE
Error in simple use case!?!

### ISSUE THREAD

**Issue by agmv** [niklasvh/html2canvas#2693]
Hi!

I'm trying to get html2canvas to download what should be a simple element but the output doesn't match what's in the browser. Not sure if this is a bug or not. Help would be appreciated.
[Example](https://codepen.io/agmv/pen/GRENWxv)

Problem seems to be related with font-size. If I change it to something much smaller, e.g. 32px it works.

**Comment by smilefufu** [comment]
Same issue here, extra large font-size will cause this issue. I have to use smaller font-size and set a css: ```transform: scal(2)``` .
