### ISSUE TITLE
Incorrect text wrapping position

### ISSUE THREAD

**Issue by GOGOGOSIR** [niklasvh/html2canvas#2696]
### describe:
When the text exceeds one line, the position of the text in the generated picture is out of order
### Bug reports:
Rendered dom: 
![issue2](https://user-images.githubusercontent.com/26272801/132493262-bd27b0fe-21f8-47f5-b219-d77955c5d608.jpg)
dom to image by html2canvas:
![issue1](https://user-images.githubusercontent.com/26272801/132493366-e82b8c75-7a22-4cea-9592-46041f9d02ac.jpg)

### Specifications:

 * html2canvas version tested with: v1.3.2
 * Browser & version: safari
 * Operating system: ios 13.6.1

**Comment by jiaotadie** [comment]
同样问题，请问你是如何解决的

**Comment by Tiacx** [comment]
https://github.com/niklasvh/html2canvas/issues/2648
_If i change version to 1.0.0 everything works as expected_

如上所述，使用 1.0.0 版本问题就解决了~
https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0

**Comment by Tiacx** [comment]
用 1.0.0 版本还是有其他问题，脑壳疼(-｡-;。

**Comment by wwh1248** [comment]
我用1.0.0直接空白了，换了好多版本，多多少少都有问题

**Comment by Tiacx** [comment]
> 我用1.0.0直接空白了，换了好多版本，多多少少都有问题

我暂时换了 dom-to-image，不过也有其他问题

**Comment by wwh1248** [comment]
> > 我用1.0.0直接空白了，换了好多版本，多多少少都有问题
> 
> 我暂时换了 dom-to-image，不过也有其他问题

我在issue中看见了这样一个解决方案，每个字符都加上span标签，亲测有效

**Comment by Mrmantou** [comment]
> > After debugging, I found that the bug is in this file https://github.com/niklasvh/html2canvas/blob/master/src/css/layout/bounds.ts In Safari, the first character after the first line behaves strangely. <img alt="QQ20211007-163630" width="640" src="https://user-images.githubusercontent.com/8147066/136350351-a9e5e942-2d17-4111-923d-bd6302eb0cf4.png"> When measure it, `getClientRects()` return two `DOMRect` and the first is empty and incorrect (It's on the end of last line).
> > But bounds.ts now just take the first `DOMRect`.... <img alt="QQ20211007-163715" width="853" src="https://user-images.githubusercontent.com/8147066/136350854-986931df-69fa-4a39-97a3-d51b45b61d44.png">
> 
> Thank you! You just saved my day!
> 
> I'll build a tweaked version for my own use, and waiting for the fix.
> 
> Here is how I tweak it: ![Screen Shot 2021-10-13 at 6 41 29 PM](https://user-images.githubusercontent.com/52536798/137118298-d7b6ceba-ec15-4089-9281-28e2d7754b04.png)

Thanks, you saved my life
