### ISSUE TITLE
In Safari 15 browser, pages using html2canvas will cause the page to fake death and crash. The error is "this web page was reloaded because a problem occurred"

### ISSUE THREAD

**Issue by wyysf123** [niklasvh/html2canvas#2699]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Through troubleshooting, we finally found that the page with problems was caused by using the button tag of the form tag and the placeholder attribute of the input

Please replace this line with a brief summary of your issue **AND** if possible an example on [codesandbox](https://codesandbox.io/s/spring-snow-jmscz?file=/src/App.js).

### Specifications:

 * html2canvas version tested with:last version
 * Browser & version:safari 15 Preview https://developer.apple.com/safari/download/
 * Operating system: macos,ios

**Comment by wugengsong** [comment]
the same iusse

**Comment by smilefufu** [comment]
#2633 remove -apple-system in font-family may help.

**Comment by ArtemisGraphic** [comment]
I'm using an old version and I have this issue, I'm not using chinese fonts however, how do I fix this?

**Comment by Chris55** [comment]
same issue, removing -apple-system changed nothing for me

**Comment by gauravkeerthi** [comment]
I searched all my css / scss files and -apple-system is not in any of them. Still fails on IOS15 device only.

**Comment by ryozm** [comment]
same issue, i change `font-family: -apple-system` => `font-family: PingFangSC-Regular, -apple-system`, everything is fine
