### ISSUE TITLE
SecurityError trying to generate image from Bing Map in a new window

### ISSUE THREAD

**Issue by YerayAlonso** [niklasvh/html2canvas#2704]
Thanks to the help at #2654 and #2646 I could generate an image from a Bing Map and insert it in the same document.  
However, I fail to open the same image in a new tab/window.  
I get a **_SecurityError: The operation is insecure_** error in the console when calling `canvas.toDataURL()`.  
I tried `useCORS` without success.

Here the test:
https://jsfiddle.net/yobm15pt

**Comment by niklasvh** [comment]
You are explicitly allowing html2canvas to taint the canvas with `allowTaint: true`
