### ISSUE TITLE
Support for Flex

### ISSUE THREAD

**Issue by gauravanshul** [niklasvh/html2canvas#2709]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [ ] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

I am implementing screenshot widget on top of html2canvas functionality. I am running into an issue as the markup has used flex extensively and seems that html2canvas module is not supporting flex. So, need help here regarding how to add support for flex while taking screenshot using html2canvas

@niklasvh

### Specifications:

 * html2canvas version tested with: 1.1.4
 * Browser & version: Chrome/ Firefox/ Edge
 * Operating system: Windows

**Comment by niklasvh** [comment]
Please share a repro example on jsfiddle.net
