### ISSUE TITLE
long text lines are shifted badly, only on safari

### ISSUE THREAD

**Issue by Zazcallabah** [niklasvh/html2canvas#2732]
### Bug reports: 

We are seeing a strange text-wrapping bug in safari only. The rendered image text is shifted around compared to the html source, like in this image:
![image](https://user-images.githubusercontent.com/485339/137906768-c84c88b9-6e55-45b2-8960-b9d50293ee38.png)

The upper section is a p-tag/span-tag combo. The lower section is the resulting image. Note how any line long enough to wrap to a new line are shifted to the right, and the end of some lines are cut slightly early.

### Specifications:

 * html2canvas version tested with: 1.3.2
 * Browser & version: Safari
 * Operating system: iphone 12, desktop mac

**Comment by mormormmmr** [comment]
It's the same for me.
It reproduces with html2canvas@1.3.3 and v1.0.0-rc.7.
Versions earlier than html2canvas@1.0.0-rc.6 do not reproduce it.
However, prior to v1.0.0-rc.6, there is another bug that prevents me from using it.

I will be very happy if it is fixed.
Thanks for the great tool and development.

**Comment by dreamvibe1993** [comment]
Almost the same issue right here
![image](https://user-images.githubusercontent.com/68645490/144617572-2c585350-4214-40d5-8cf8-49dc4339baac.png)

**Comment by chea1tei** [comment]
Anyone have any solution to this? Im using contenteditable and my text are having the same issue in safari as

**Comment by niklasvh** [comment]
This should be fixed with https://github.com/niklasvh/html2canvas/pull/2786
