### ISSUE TITLE
Can't eval html2canvas.min.js

### ISSUE THREAD

**Issue by marcusx2** [niklasvh/html2canvas#2735]
I want to add html2canvas to the code without downloading from a URL. I tried using eval on [this code](https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.2/html2canvas.min.js)  but it didn't work. I get the error `Uncaught SyntaxError: Invalid or unexpected token`.  I tried the accepted answer from this [SO post](https://stackoverflow.com/questions/6432984/how-to-add-a-script-element-to-the-dom-and-execute-its-code), but I got the same error. 

Can you help me, please?

**Comment by niklasvh** [comment]
It seems to eval it without issue: https://jsfiddle.net/L95y83ut/1/
