### ISSUE TITLE
Internet Explorer 10 compatibility

### ISSUE THREAD

**Issue by panthar1** [niklasvh/html2canvas#274]
Hi,

We have been trying to get html2canvas to work in IE10, but I imagine this will also apply to IE9.

Here is what I did (without success):

SCRIPT438: Object doesn't support property or method 'getComputedStyle' 
html2canvas.js, line 2399 character 5

So upon further research, this method does not seem to be implemented in IE10, as the only explanation for that error (despite documentaiton saying otherwise). So I found some code from http://www.snipplr.com/view/13523/ which implements the getComputedSyle() if it's not defined in IE10. This works.

However, using that function just creates another issue:

html2canvas.js, line 2401 character 5
SCRIPT5007: Unable to get property 'substr' of undefined or null reference 

This error, is most likely caused by the function on http://www.snipplr.com/view/13523/ not returning what html2canvas expects?

Anyhow, I am looking for a solution here. I would imagine it's just a wrong implementation of getComputedStyle that's not returning the data html2canvas needs, or is there some other trick to getting html2canvas to work with IE10?

There might be other errors, but this is the main issue I have found so far with IE10.

Any help in solving this problem would be much appreciated!

Thanks!

**Comment by usmonster** [comment]
Can you try again with the current version in the `master` branch and report back if it works or not?

(Also, out of curiosity, is the page you're trying to capture in quirks/compatibility mode?)

**Comment by usmonster** [comment]
Again, please try the current version on master. More issues have been fixed with #503.

Also, @lexxinco, the quote from caniuse.com doesn't apply to any of the supported browsers.
