### ISSUE TITLE
browser gets stuck while calling "html2canvas(element).then(function (canvas)"

### ISSUE THREAD

**Issue by umarahsan559** [niklasvh/html2canvas#2741]
Hi, any way to call this function async so that browser does not get stuck for any large div

**Comment by younlok** [comment]
same problem for me

**Comment by niklasvh** [comment]
There aren't any additional async options available

**Comment by ronald2wing** [comment]
Why is this issue closed?

**Comment by jon-c-kl** [comment]
Trash
