### ISSUE TITLE
words are not wrapped correctly

### ISSUE THREAD

**Issue by dreamvibe1993** [niklasvh/html2canvas#2762]
### Bug reports:

I need to make a png from canvas so I used your thing. It's excellent but on the IOS it wraps words wrong. The downgrade to html2canvas version 1.0.0 helped, but not perfect, because some letters have weird spacings.

1.3.3
![image](https://user-images.githubusercontent.com/68645490/144619745-1c2df5b0-8ea4-47f9-8b57-0c196d96fadb.png)

1.0.0
![image](https://user-images.githubusercontent.com/68645490/144621241-9f12cf56-d9d5-4889-9c0f-d950291bc801.png)

1.3.3
Example in english.
![image](https://user-images.githubusercontent.com/68645490/144620689-98b79e13-04e3-45bc-ac2e-dc6d15169916.png)

### Specifications:

 * html2canvas version tested with: 1.3.3
 * Browser & version: Safari 14.1.2
 * Operating system: IOS

**Comment by niklasvh** [comment]
This should be fixed in 1.4.0

**Comment by kkirby** [comment]
I had a similar issue. I can confirm it was fixed by upgrading to the latest. Thank you!
