### ISSUE TITLE
Garbled characters in vue3 use

### ISSUE THREAD

**Issue by likaia** [niklasvh/html2canvas#2763]
I wrote a simple demo, and after running it, I found garbled characters.

![image](https://user-images.githubusercontent.com/35120858/144865777-04d917a0-22a3-40f9-9e99-9085bfec4dde.png)

![image](https://user-images.githubusercontent.com/35120858/144865633-1da17ffa-b237-48a2-aced-50799a3949ea.png)

**Comment by niklasvh** [comment]
Please share a repro on jsfiddle.net
