### ISSUE TITLE
在edge下，生成的图片不会显示文字

### ISSUE THREAD

**Issue by potatoShield** [niklasvh/html2canvas#2770]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

官网案例在edge下，生成的图片不会显示文字

### Specifications:

 * html2canvas version tested with:
 * Browser & version: Edge 44.17763.831.0
 * Operating system: Windows10

**Comment by Zhouyex** [comment]
same question
