### ISSUE TITLE
html2canvas source map file error

### ISSUE THREAD

**Issue by FeiFanLiang** [niklasvh/html2canvas#2774]
### Bug reports:

i use html2canvas via webpackv5,but in `html2canvas.esm.js.map` or `html2canvas.js.map` found many warning, just like `../../src/css/property-descriptors/text-decoration-color.ts` not found,Is it possible to generate a new map file?

### Specifications:

 * html2canvas version tested with:1.3.3
 * Browser & version:
 * Operating system:

**Comment by GowthamiAmp** [comment]
I am encountering the exact same issue.

**Comment by AlexanderKaran** [comment]
Currently using version v1.4.0 and still getting the same issue?
