### ISSUE TITLE
Allow rendering invisible HTML fragments

### ISSUE THREAD

**Issue by JohnM1991** [niklasvh/html2canvas#278]
I would like to use html2canvas as a HTML renderer to HTML5 canvas (I have a HTML5 canvas app but want to show some popup menus to the user which would best be expressed as HTML elements).

So I would pass an HTML String or an invisible element, and get back the canvas which I can hopefully then getImageData() and then putImageData() wherever I want.

The following issue appears related:
https://github.com/niklasvh/html2canvas/issues/107

However, using visibility:hidden (+ hack the code) doesn't work well because elements still take up space, and flickering is also not good.

I appreciate this is not the 'raison d'être' for this library, and perhaps isn't technically feasible, so I will fully understand if this issue gets closed, but if you have any ideas how to peruse a part of html2canvas code to do this, it would be appreciated.

**Comment by niklasvh** [comment]
As described in #107, it isn't possible. html2canvas relies on the browser to calculate the area for the element to be able to render it, and it requires it to not have `display: none`
