### ISSUE TITLE
html2canvas source map issue with webpack5

### ISSUE THREAD

**Issue by GowthamiAmp** [niklasvh/html2canvas#2789]
Bug reports:

I used html2canvas with webpack5. I can found many warnings in html2canvas.js

![image](https://user-images.githubusercontent.com/30386760/147946201-3a3c5c36-fafd-417d-ba81-47d33e874223.png)

### Specifications:

 * html2canvas version tested with: 1.4.0
 * Browser & version:
 * Operating system:

**Comment by maximotejeda** [comment]
The same problem here, 
![screenShoot_01-04](https://user-images.githubusercontent.com/25188792/148135641-6be66561-b21c-4da4-8bc6-3ff167046194.png)


**Working with CRA**

**Comment by AlexanderKaran** [comment]
Got the same issue here, there was a bug fix but it seems to cause and issue with webpack five: #2774

**Comment by GowthamiAmp** [comment]
Any fixes going on this issue?

**Comment by lborie** [comment]
This issue seems to be fixed with this PR : https://github.com/niklasvh/html2canvas/pull/2787 
But it's not included in 1.4.0... 

Next release 1.4.1 ?

**Comment by casparolesen** [comment]
@niklasvh Any plans to release a 1.4.1 soon?

**Comment by niklasvh** [comment]
Fixed in 1.4.1
