### ISSUE TITLE
Every time the html2canvas() is called, the src of the external iframe is requested

### ISSUE THREAD

**Issue by selmalee** [niklasvh/html2canvas#2798]
### troubleshooting:
Every time the `html2canvas()` is called, the `src` of the external iframe (not in the dom should be to canvas) is requested
Here is the code: [codepen](https://codepen.io/seminelee/pen/vYeVjop?editors=1011)
![image](https://user-images.githubusercontent.com/15016665/148942892-e59b48b6-453d-48e6-8704-e7dd26af0334.png)

### Specifications:

 * html2canvas version tested with: http://html2canvas.hertzen.com/dist/html2canvas.js

In our project, we use `iframe` to request some action, so this is a big trouble for us.

**Comment by acroyear** [comment]
This should be expected. The code makes a clone of the DOM, so it creates a new iframe and that will have to be loaded.
