### ISSUE TITLE
Chrome Browser Blank Image issue but works on Chrome Incognito Mode

### ISSUE THREAD

**Issue by ishanighosh9** [niklasvh/html2canvas#2804]
My code to print an image using **html2canvas is working on all browsers except Chrome**. It **even works on Chrome incognito mode** but not in the normal Chrome browser.
Also for new users not using the print feature, it seems to be working on their normal Chrome browsers but older users using the feature are suddenly seeing a blank page. Is it some kind of cache issue?
After debugging I found that the canvas generated by html2canvas is capturing image of wrong dimension even when the entire DOM is loaded for my component.
here is my piece of code :

html2canvas(inputEl, {useCORS: true, allowTaint: false}).then(canvas => {
    const [canvasHeight , canvasWidth] = [canvas.height, canvas.width];
    const imgData = canvas.toDataURL("image/png");
    let canvasImage = new Image();
    canvasImage.onload = onCanvasLoad.bind(this, canvasImage, {...canvasOptions, pdfDocument, canvasHeight, canvasWidth});
    canvasImage.src = imgData;
  });

Settings CORs to true is also didn't help.

Please provide some pointers here.

Specifications:
html2canvas version tested with: 1.0.0-rc.7
Browser & version: Chrome - 97.0.4692.71 (Official Build) (x86_64)
Operating system: macOS Big Sur

**Comment by antonz7600** [comment]
Also reproduced with 
Apple M1 - MacOS Monterey
Safari, Chrome - latest

Could be checked with https://html2canvas.hertzen.com/ -> bottom right corner - photo - capture.

Fixed by using incognito mode.
If you need I can provide additional info

**Comment by ishanighosh9** [comment]
@antonz7600, Yes I can reproduce this using the link Example https://html2canvas.hertzen.com/ -> bottom right corner - photo - capture.
It works in Chrome Incognito Mode but not in Chrome.
Did you find any fix for this?

@niklasvh Can you please help?

**Comment by MO-James** [comment]
@antonz7600 @ishanighosh9 

For me it's related to browser extensions, as Chrome disables browser extensions in incognito mode. Try disabling all your extensions and then re-enabling them one by one. 

Grammerly was the problem extension for me and it's working now that I've disabled it.

**Comment by ishanighosh9** [comment]
Thanks @MO-James, this was very helpful.
It worked for me. @antonz7600, please try this.

For me as well Grammarly was the problem extension.

Is there a workaround without turning off Grammarly?

**Comment by aguilaair** [comment]
Same issue is present in Firefox 96.0.1 with Grammarly, disabled it and seems to be wokring.

**Comment by crisjur** [comment]
Are there any solutions to make this working without turning off Grammarly?

**Comment by niklasvh** [comment]
Without starting to dig into what Grammarly specifically does it's hard to say how fixable this is. Any additional info such as logs, or research into what Grammarly breaks would be helpful.

**Comment by crisjur** [comment]
const input: any = document.getElementById('OverviewPDF');
  const canvas = await html2canvas(input)

    console.log('** canvas width **', canvas.width )
    console.log('** canvas height  **', canvas.height)

== console result when Grammarly turns on ===
** canvas width ** 25
** canvas height  ** 1

== console result when Grammarly turns off ===
** canvas width ** 1880
** canvas height  ** 2400

**Comment by christianiancuya** [comment]
Are there any solutions to make this working in case of that Grammalry turns on? Is it impossible?
Seems like that some node version is breaking this.

**Comment by noahking27** [comment]
Same issue as well. Works fine without grammarly chrome extension, but with it on it messes up the image.

**Comment by tushar32** [comment]
I am also getting same issue. Is this resolved?

**Comment by jezao** [comment]
I got an answer from Grammarly team, and the workaround worked for me :D

> According to our analysis, your software may not be handling Shadow DOM styling properly. Removing the <style>  tag in our custom element also made the problem disappear. [ShadowDOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) style is supposed to be encapsulated by default.

As a workaround, you may try ignoring the elements similar to the one mentioned below: 
`<grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration>`

Just add the code above in your html file.

All the best!

**Comment by mccahan** [comment]
Stumbled across this after we encountered the same issue.

We have two different workaround solutions we've tested, one more specific to Grammarly and one that targets all ShadowDOM elements. I'm not sure whether the latter will break (or fix) anything unexpectedly for other users, while the former would of course only work in Grammarly's case and only if they don't change anything about their custom HTML tag.

The less-specific version that ignores any ShadowDOM elements, which is probably what we want for our situation, but might cause unintended consequences if anybody out there is expecting ShadowDOM cloning:

```js
function fnIgnoreElements(el) {
  if (typeof el.shadowRoot == 'object' && el.shadowRoot !== null) return true
}

html2canvas(document.querySelector("#capture"), { ignoreElements: fnIgnoreElements }).then(canvas => {
    document.body.appendChild(canvas)
});
```

The Grammarly-targeted solution:

```js
function fnIgnoreElements(el) {
  if (el.nodeName.toLowerCase() == 'grammarly-desktop-integration') return true
}

html2canvas(document.querySelector("#capture"), { ignoreElements: fnIgnoreElements }).then(canvas => {
    document.body.appendChild(canvas)
});
```

Their ShadowDOM element CSS isn't namespaced at all (they just use the CSS selector `div`), which is unfortunate and would of course avoid this situation entirely for everyone out there in the world already using html2canvas:

![Screenshot 2022-02-08 at 13 01 28](https://user-images.githubusercontent.com/2308923/153066271-0d772230-d971-41b8-9848-94e455288d41.png)

**Comment by devor** [comment]
> ```js
> function fnIgnoreElements(el) {
>   if (typeof el.shadowRoot == 'object' && el.shadowRoot !== null) return true
> }
> 
> html2canvas(document.querySelector("#capture"), { ignoreElements: fnIgnoreElements }).then(canvas => {
>     document.body.appendChild(canvas)
> });
> ```

This worked great for my use case! Thank you!!

**Comment by jpatel3** [comment]
why this issue started popping up suddenly? is there any recent change which causes it?

**Comment by ShtickBE** [comment]
> ```js
> function fnIgnoreElements(el) {
>   if (typeof el.shadowRoot == 'object' && el.shadowRoot !== null) return true
> }
> 
> html2canvas(document.querySelector("#capture"), { ignoreElements: fnIgnoreElements }).then(canvas => {
>     document.body.appendChild(canvas)
> });
> ```
Exact same issue, worked for me to. Thanks a lot!

**Comment by ishanighosh9** [comment]
@mccahan's solution worked like a charm!
Thanks to folks this really helped!.

I used the following solution as well - 

```
function fnIgnoreElements(el) {
  if (typeof el.shadowRoot == 'object' && el.shadowRoot !== null) return true
}

html2canvas(document.querySelector("#capture"), { ignoreElements: fnIgnoreElements }).then(canvas => {
    document.body.appendChild(canvas)
});
```

Closing the issue.
