### ISSUE TITLE
Save screenshot server-side

### ISSUE THREAD

**Issue by nigina** [niklasvh/html2canvas#283]
Hi, how can i save the screenshot server-side with java? Or is html2canvas only client-side? I am using html2canvas to capture screen shot of website and i need save screenshot server-side. The user must not see screesnhot of website.

Is it possible with this tool?

P.S. Sorry for my English.

**Comment by SemanticBeeng** [comment]
@niklasvh please be kind to explain why one could not get a "real DOM" from PhantomJS on the server side and use html2canvas just like from the client side

Would something like this not work on the server side with html2canvas?

http://stackoverflow.com/questions/12180508/dom-manipulation-with-phantomjs
https://gist.github.com/n1k0/1501173#file-gistfile1-js-L29-L33

Thanks
Nick

**Comment by nithinkolekar** [comment]
@niklasvh 
I think @SemanticBeeng is talking about perform capture with ghost user which may frequently(cron) capture page and save it on directory which is accessible to webserver.

I implemented with PhantomJs same functionality but html2canvas is more convenient IMO.

**Comment by salis77** [comment]
@andresdevsar  and @SemanticBeeng can I use phantomjs or casperjs to get screenshots of the current user page which have been edited? you know! I want to let users take the screenshots of the page they have modified but unfortunately, html2canvas doesn't support the CSS properties and I have to use in that page
and I didn't see these abilities in phantomjs or casperjs ...
guide me please
