### ISSUE TITLE
linear gradient support in IE9 and 10

### ISSUE THREAD

**Issue by aneeshmj** [niklasvh/html2canvas#284]
Hi,

It would be helpful if any one can let me know linear background is supported for IE9 and 10. I tried using it, doesn't seem to work. Tried with svg+xml also, but IE9 crashes.

http://jsfiddle.net/bK3HY/1/ 

Thanking you in advance.

Sincerely,
Aneesh

**Comment by usmonster** [comment]
Possibly fixed in #708. @aneeshmj, can you please check on the master branch?
