### ISSUE TITLE
html2canvas blank on Opera version 84.0.4316.21 date tested: (2/28/2022)

### ISSUE THREAD

**Issue by artanvrajolli** [niklasvh/html2canvas#2848]
html2canvas version tested with:  https://html2canvas.hertzen.com/  Capture button
Browser & version:  Opera 84.0.4316.21
Operating system: windows 10

**Comment by artanvrajolli** [comment]
The problem was
With extension "grammarly" 
disabling, allowed to work html2canvas

**Comment by coder0107git** [comment]
You might want to see issue #2804 where grammarly was also causing html2canvas to not work properly.
