### ISSUE TITLE
生产环境中dom结构使用css背景图片，插件构建时背景图片丢失。本地开发没有此问题

### ISSUE THREAD

**Issue by JavonLuo** [niklasvh/html2canvas#2893]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [ ] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by jiafluo** [comment]
dom结构：
![image](https://user-images.githubusercontent.com/58316770/169990709-a926712a-d0e5-4ea4-9ce8-1c84b79ee729.png)
g构建后的图片：
![image](https://user-images.githubusercontent.com/58316770/169990469-57d3e876-a243-4447-9919-cecc3547a2d5.png)

**Comment by reactjser** [comment]
在配置项中加入useCORS: true。
