### ISSUE TITLE
The capture loses information of the screen that I want to capture

### ISSUE THREAD

**Issue by baarbaracrr** [niklasvh/html2canvas#2964]
I want to make a screenshot that has a leaflet map and I lose the map in the screenshot.

**Comment by nicks258** [comment]
Any updates?

**Comment by baarbaracrr** [comment]
> Any updates?

No. The fact that the map is not visible may be due to its size, but I'm not sure.

**Comment by KS-HTK** [comment]
No, it is probably not due to its size. Make sure to use `allowTaint: true` and most likely also `useCORS: true`.
The other issue you might have is that you are creating the image before all map tiles are loaded.
Running the image generation code on the load event of your tileLayer might not work graet. For me that event fires to early and some Tiles are not fully loaded. If you run it on a Button that should work.

Also any svg elements on your Map may appear at different places. See #2960

**Comment by nicks258** [comment]
Thanks for your message for  me I added `{allowTaint: true, proxy: this.selectedFrame.frameimage,
      useCORS: true}` still I am getting error
`Access to image at 'https://baseUrl.com/media/frame/frame.png' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
can you help?

**Comment by KS-HTK** [comment]
This is probably then an Issue at your 'https://baseUrl.com/media/frame/frame.png' it requires CORS headers, as does your Request. Verify that whatever your Leaflet map is loading has CORS.
I am no expert on CORS, but as I understand it, all requests from a foreign Domain require those headers in request and response.

A Leaflet example Map should work just fine. I use the OpenStreetMap Tiles and have own Icons on the map without any Issue besides the above mentioned one.

```js
  const target = document.querySelector(".leaflet-container");
  const controls = document.querySelector(".leaflet-control-container");
  html2canvas(target, {
    allowTaint: true,
    useCORS: true,
    logging: false,
    ignoreElements: (element) => controls.contains(element)
  })
```
This is what I use to get the Map without control elements.

**Comment by nicks258** [comment]
I am using this in ionic 5 framework. Getting error on both ionic serve as well as on phone.

**Comment by baarbaracrr** [comment]
> ```js
> const target = document.querySelector(".leaflet-container");
>   const controls = document.querySelector(".leaflet-control-container");
>   html2canvas(target, {
>     allowTaint: true,
>     useCORS: true,
>     logging: false,
>     ignoreElements: (element) => controls.contains(element)
>   })
> ```

This works! Thank you very much!

**Comment by baarbaracrr** [comment]
> No, it is probably not due to its size. Make sure to use `allowTaint: true` and most likely also `useCORS: true`. The other issue you might have is that you are creating the image before all map tiles are loaded. Running the image generation code on the load event of your tileLayer might not work graet. For me that event fires to early and some Tiles are not fully loaded. If you run it on a Button that should work.
> 
> Also any svg elements on your Map may appear at different places. See #2960

This works! Thank you.
This helps me load the map. Now the polylines are exported with another position (the white line):
![Graph (27)](https://user-images.githubusercontent.com/31986084/193995832-f8f06806-9cb4-42c2-819e-052105728a8e.png)

**Comment by KS-HTK** [comment]
> > Also any svg elements on your Map may appear at different places. See #2960
> 
> This works! Thank you. This helps me load the map. Now the polylines are exported with another position (the white line): 

That is the mentioned issue #2960 . I created it after having that exact problem. It is not mentioned in the issue that I ran into it with Leaflet. Because as the example there shows it is not an issue related to leaflet, but a issue with transform on svg elements.

Glad I could help.

**Comment by TreehouseNorris** [comment]
When using a capacitor://localhost app to display a preview of https:// images, I converted them to data: via XMLHttpRequest before using html2canvas, as the workaround for an iOS origin error when capacitor:// attempts to read from the browser cache.

**Comment by baarbaracrr** [comment]
I have found this leaflet plugin that has solved the problem:
https://grinat.github.io/leaflet-simple-map-screenshoter/
