### ISSUE TITLE
I want to use html2canvas to vuejs how ? how to use ? please help me. Thank

### ISSUE THREAD

**Issue by chheng-dev** [niklasvh/html2canvas#2976]

**Comment by zkcpps** [comment]
![image](https://user-images.githubusercontent.com/46256924/196115958-0870c72c-4a20-4ca7-8b77-f059a6197770.png)
main page has

**Comment by chheng05** [comment]
<img id="barcode" src="https://api.qrserver.com/v1/create-qr-code/?data=testing&amp;size=90x90" alt="qr-code"
                    title="testing" width="60px" height="60px" class="align-middle" /> 
i use this but when download is empty.
