### ISSUE TITLE
Transformations doesn't stack

### ISSUE THREAD

**Issue by bkralik** [niklasvh/html2canvas#298]
Hi,
I discovered that support for CSS3 transformations is only partial - nested transformations are not supported. However, I need to capture google maps and they use css3 transformations. I wrote some basic support, but at first, there is some bug so it doesn't work in Chrome and at second, I plan to make it even better. I just ask, if you are working on it, so I would write it unnecessarily.
Basic idea can be seen here: https://github.com/bkralik/html2canvas/commit/383e7e1ae950c4738a783174c74b9a67f70460fb
Please ignore build directory in front, I am begginer with git and this is my first commit :-)

Thank you
bkralik

**Comment by ZachSaucier** [comment]
Why was this issue closed? The "known limitations" link is now a 404 and I don't see any explanation of this in the [features list](http://html2canvas.hertzen.com/features).
