### ISSUE TITLE
[Solved] Incorrect layout in the image generated (only Chrome)

### ISSUE THREAD

**Issue by roviury** [niklasvh/html2canvas#302]
source code here:
http://jsfiddle.net/roviury/udwdE/

the width of cells (even fixed by css) should be determined by the widest one.
but the conversion to image in chrome is wrong.

![bggbrgf](https://f.cloud.github.com/assets/6076959/1650090/03a9f252-5a5b-11e3-9276-a4fc7caf1347.png)

**Comment by balraj8** [comment]
I'm also facing the same issue, has anyone resolved it. All the Elements under Table are not plotting properly.

**Comment by roviury** [comment]
This issue is gone due to the update of webkit engine. (without changing JS code)
Chrome >= 57.0.2979.0
Not sure about the exact version that fixed the bug.
