### ISSUE TITLE
Underline problem on child element

### ISSUE THREAD

**Issue by SIUSWHY** [niklasvh/html2canvas#3045]
Hello! 
I am using this [version](https://github.com/niklasvh/html2canvas/releases/tag/v1.4.1) of the library. In this case, the problem is that when I try to get the canvas, my text is displayed without underlining. If the underline hangs on the parent element, then the library ignores this and displays the canvas without the underline.

Example code: https://jsfiddle.net/DaniilPF/7og51s02/10/

**Comment by shubham3246** [comment]
You can simply remove the inner div which doesn't contain any id and it should resolve the issue.

**Comment by SIUSWHY** [comment]
Yes of course, but I can't change this template because I don't create it. They give me ready-made html from which I have to make a pdf

**Comment by fadelun** [comment]
> You can simply remove the inner div which doesn't contain any id and it should resolve the issue.

if you add `font-weight:bold` the underline not same

**Comment by SIUSWHY** [comment]
This code snippet helped me solve my problem. The idea is for child components to inherit the underline in the parent component. In my case I had a table which I passed to a function.

```
let underlineStyle = '';
  function fixUnderline(elem, isNeedUnderline) {
    const isHtmlElement = elem instanceof HTMLElement;
    if (!isHtmlElement) {
      return;
    }
    if (isNeedUnderline) {
      elem.style.textDecoration = underlineStyle;
    }

    const childElements = elem.childNodes;
    const getElementComputedStyle = window.getComputedStyle(elem);
    const isStyleContainUnderline = getElementComputedStyle['textDecorationLine'].includes(
      'underline' || 'solid' || 'none'
    );

    if (isStyleContainUnderline) {
      underlineStyle = getElementComputedStyle['textDecoration'];
      childElements.forEach(function (element) {
        fixUnderline(element, true);
      });
    }

    if (childElements.length && !isNeedUnderline) {
      childElements.forEach(function (element) {
        fixUnderline(element);
      });
    }
  }
```
