### ISSUE TITLE
css border for table in Chrome

### ISSUE THREAD

**Issue by roviury** [niklasvh/html2canvas#310]
if the border of table is set as "border-collapse: collapse;", the image conversion will have a problem in drawing the thickness of border in Chrome.

My computer: Win7 x64, Chrome 31.0.1650.63 m

source code: http://jsfiddle.net/4Z7xd/ 

![fbghnhnh](https://f.cloud.github.com/assets/6076959/1698020/2ef852ec-5f1e-11e3-8b36-21bceb58528c.png)

***** Easy solution is found - see my comment below *****

**Comment by kuna** [comment]
problem still exists, same here. only firefox works well but not chrome and IE11

**Comment by kuna** [comment]
I hotfixed the problem and send pull request but no response :P
https://github.com/kuna/html2canvas/commit/84792eac31e1c747a0529e06517462ed186aa88d

**Comment by roviury** [comment]
In 2017, html2canvas 0.5.0-alpha1 has not fixed it yet.
But I have found a easy solution is found.

In example ( http://jsfiddle.net/4Z7xd/ ),

#table1>tbody>tr>td {
    border: 2px solid #878787;
    padding: 2px 18px;
    text-align: center;
    width: 98px;
}

html2canvas regards it as 4px for border (eg. 2px from left cell + 2px from right cell)
Therefore, 2px in either left or right should be eliminated for the double counting.
#table1>tbody>tr>td+td {
    border-left-width: 0;
}
#table1>tbody>tr+tr>td {
    border-top-width: 0;
}

It solves perfectly without modifying any element or JS code.

**Comment by yaitskov** [comment]
Why it is solved? For  "html2canvas": "^1.0.0-alpha.12", it still there.

**Comment by roviury** [comment]
From my experience, there are new bugs starting from html2canvas-1.0.0-alpha.11.
The code is now modified for html2canvas-1.0.0-alpha.10.

Ver0 - without the additional css:
http://jsfiddle.net/6jukx0jx/0/

Ver1 - with the additional css:
http://jsfiddle.net/6jukx0jx/1/

I can see the blurry border for Firefox but not Opera/Chrome. Anyway, I have updated the code and removed the "solved".

**Comment by bindhyeswari** [comment]
Applying the border styles on the table cell such that the left border is applied for the first table child fixes the issue. Concept is same as in other answers, but it works without a glitch for me: 

```css
.puzzle_td {
  width: 1.5em;
  height: 1.5em;
  vertical-align: middle;
  text-align: center;
  border-right: 2px solid black;
  border-top: 2px solid black;
  border-bottom: 2px solid black;
}
.puzzle_td:first-child {
  border-left: 2px solid black;
}
```
<img width="197" alt="Screen Shot 2020-10-04 at 2 13 15 AM" src="https://user-images.githubusercontent.com/4296957/95011674-2ae27300-05e7-11eb-8dd5-d8c2b732fea7.png">
