### ISSUE TITLE
FontAwesome icons are not rendered in firefox only

### ISSUE THREAD

**Issue by akhil-uddemarri** [niklasvh/html2canvas#314]
FontAwesome http://fontawesome.io/ icons are rendering fine in chrome but not in firefox. It just renders a box.
![rendering font awesome icons](https://f.cloud.github.com/assets/2185656/1770180/ce6e9728-6784-11e3-8cea-bc50f6168f85.png)

**Comment by sweetleon** [comment]
I'm having this problem also. How do I upgrade to html2canvas v0.5? I feel silly asking this, but I don't see such a branch or tag on this repo.

Thanks in advance.

**Comment by sweetleon** [comment]
PS I'm using html2canvas via rails-assets with `gem 'rails-assets-html2canvas` and the following `bower.json` file:

```
{
  "name": "My-App",
  "dependencies": {
    "html2canvas": "https://github.com/niklasvh/html2canvas"
  }
}
```

**Comment by sweetleon** [comment]
From what I see at https://rails-assets.org/components only versions <= 0.4.1 are available for rails-assets. So I've simply added the latest dist/html2canvas.js to my `app/assets/javascripts/vendor/` folder and will use it like that for the time being. Thanks for making this incredibly useful library!

**Comment by fpslater** [comment]
@sweetleon Try swapping your `html2canvas.js` file for the one I modified here. It worked for me. 

https://github.com/fpslater/fix-html2canvas-webkit-font-conversion

**Comment by fpslater** [comment]
@sweetleon Oh nevermind, you've already found a workaround.

**Comment by CoderSquirrel** [comment]
I'mhaving the same problem

**Comment by dpadula** [comment]
The problem with fontawesome still happens in version 'html2canvas 1.0.0-alpha.12'

**Comment by viktordart** [comment]
Any solution? Thanks

**Comment by IAmRC1** [comment]
The problem with fontawesome still happens in version 'html2canvas 1.0.0-rc.5
