### ISSUE TITLE
TypeScript Support for Html2Canvas Now Available

### ISSUE THREAD

**Issue by rwhepburn** [niklasvh/html2canvas#315]
Hi there, 

Firstly, thanks for this great library! 

For anyone using TypeScript and Html2Canvas together, I have added a new TypeScript Definition file to the repository found at https://github.com/borisyankov/DefinitelyTyped 

At some point it would be great to see ownership and maintenance of this definition file assumed by the project authors and included as part of the official Html2Canvas release package. This will make it easier to keep in sync with enhancements over time.

In the meantime, perhaps a link to this could be included in the official documentation?

I hope this is valuable to others.

Cheers

**Comment by jaichandra** [comment]
I tried the above type definition, but still getting error:
https://github.com/niklasvh/html2canvas/issues/960#issuecomment-326646970

**Comment by ramakrishnanjayaraman** [comment]
Is there a latest version of this typescript ? it appears it's not compatible with the latest html2canvas version (1.0.0 alpha versions)

**Comment by Velzar** [comment]
Coudl you please update this one either tell how to manually modify it in order to use with the next html2canvas releases if you abandoned this project.

**Comment by niklasvh** [comment]
If anyone is interested in making a PR for including typescript definitions for html2canvas (based on the [Flow types](https://github.com/niklasvh/html2canvas/blob/master/src/index.js#L11)) I could merge them to this repo.

**Comment by Velzar** [comment]
Well i am interested, because i need it for my project. The thing is i have no idea how to do PR. If you could maybe give some good articles i will try my best. Otherwise it could take longer time for me to do the same thing.
