### ISSUE TITLE
-webkit-transform:scale(0.5) workaround?

### ISSUE THREAD

**Issue by mattiaswelander** [niklasvh/html2canvas#316]
Hello, thank you for this excellent plugin. I notice that html2canvas doesn't work on scaled elements (using css zoom OR the browser transform:scale() (I use webkit).

Is there any workaround for that?

What I do now is to just set the zoom to 1 using JS, but that gives the user a real ugly interface experience as the snapshot is taken, elements flowing out of place etc. It naturally looks quite buggy =)

**Comment by thiagog3** [comment]
@ricricucit any solution or none yet? :-1:

**Comment by brcontainer** [comment]
@thiagog3 Hi!
Intention to implement this feature? Yes
Date release for this? No.

Depending on your needs (if a plugin for example), you can try using the https://github.com/niklasvh/html2canvas/blob/master/dist/html2canvas.svg.min.js

**WARNING:** Canvas work with `<foreignobject>`, but don't support export using `toDataURI` in Webkit/Chrome/Safari/Chromium/Opera/Blink (security issues of WebBrowser and not of html2canvas)

**Comment by niklasvh** [comment]
Transform scale is supported in 1.0.0
