### ISSUE TITLE
Capture part of background on DIV

### ISSUE THREAD

**Issue by josesuarezcordova** [niklasvh/html2canvas#317]
Hi, thank for you tool really very useful, I would like Know If is possible to capture just a part of background in DIV, I mean, I have a page with background on full screen, and I have a DIV of 300x300 this one is on different positions on the screen, I need capture just the area in DIV of the all background, that is possible? thanks a lot!

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
