### ISSUE TITLE
Large border-radius bug

### ISSUE THREAD

**Issue by Grom-S** [niklasvh/html2canvas#318]
When border radis is large it is not rendered properly.
Here is how browser (chrome) renders it:
![image](https://f.cloud.github.com/assets/705787/1870673/dab38ee6-788a-11e3-9865-d425f28c60e6.png)

Here is how html2canvas renders it:
![image](https://f.cloud.github.com/assets/705787/1870686/052c26f6-788b-11e3-8b6d-f62c0a55c365.png)

The dimensions are:

width: 180px
height: 50px
border-radius: 50px

Also position is "absolute" if that is important.

**Comment by ZachSaucier** [comment]
I can make a new issue if I need to, but there seems to be some small rendering error in some circumstances: http://jsfiddle.net/2HqTZ/128/ Notice the white diagonal lines in the corners.
