### ISSUE TITLE
Unhandled Promise Rejection: SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by fiSCIENCES** [niklasvh/html2canvas#3184]
Hi,

Using the last release 1.4.1, I still experienced the following error in all browsers (Safari, Edge + Chrome).

window.getImage = function() {
  html2canvas(document.body,{allowTaint:true,useCORS:true}).then(function(canvas) {
    var convertedImage = canvas.toDataURL(); // !!! SecurityError !!!
    ...
  });
}

Here the HTML file used (did a save as in Safari).
[ConservaWIN.html.zip](https://github.com/user-attachments/files/16233289/ConservaWIN.html.zip)

Thank you.

**Comment by yorickshan** [comment]
Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.7 or the most recent version. :smile:, html2canvas-pro has merged #2911 to fix this issue.

**Comment by fiSCIENCES** [comment]
Wow, great job!
Thank you very much. I don't think this repository is maintained anymore.

**Comment by a-knaw-knee-mus** [comment]
> Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.7 or the most recent version. 😄, html2canvas-pro has merged https://github.com/niklasvh/html2canvas/pull/2911 to fix this issue.

I stumbled across this thread after hours and hours of debugging with the svg's rendering incorrectly (and this security error). Tried many things, but changing `html2canvas`->`html2canvas-pro` solved it all seamlessly. ty you saved me 🙏. I wish I found this sooner

**Comment by IvanSolncev** [comment]
> Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.7 or the most recent version. 😄, html2canvas-pro has merged [#2911](https://github.com/niklasvh/html2canvas/pull/2911) to fix this issue.

@yorickshan 
Your option does solve the problem in Safari, but other issues arise that were not present in the official version.

If there are style changes on the page due to class additions, they are simply ignored during printing, and this happens in both Chrome and Safari.
