### ISSUE TITLE
Chinese text not rendered properly when text-align is center

### ISSUE THREAD

**Issue by Grom-S** [niklasvh/html2canvas#332]
When there is `text-align:center` in styles, the last character of the string is rendered on top of the first character of the next string:

![](http://i.imgur.com/bfRpWfC.png)

Here is the jsfiddle: http://jsfiddle.net/drtru/

**Comment by gto22834** [comment]
I set scale(.9999) and it's work fine for me.
but I'dont know why
http://jsfiddle.net/drtru/

**Comment by gto22834** [comment]
It work fine, when I set scale(.9999).
But I don't know why...
http://jsfiddle.net/drtru/1/

**Comment by Dushusir** [comment]
> It work fine, when I set `scale(.9999)`.
> But I don't know why...
> http://jsfiddle.net/drtru/1/

it works for me!! Thanks a lot!
