### ISSUE TITLE
Canvas is blurry

### ISSUE THREAD

**Issue by luckystairs** [niklasvh/html2canvas#340]
Using the latest version I get blurred canvasses – tried this across chrome, firefox and safari all with the same result. Previously using 0.3.4 this happened sometimes but only (i think) with relatively positioned target elements (eg. if <div id="whatever" > is converted to canvas then if that div is relatively positioned it will possibly, dependent on browser mostly, be blurred) but in this version it seems to happen no matter what. The demos in the currently available version of 0.3.4 and 0.4.0 seem to look for '/build/html2canvas.js' which doesn't exist in these versions so I have only been able to test and compare with the 0.3.4 version I downloaded some time ago. Any ideas on this problem would be greatly appreciated. Many thanks. Please see attached screenshot from 'html2canvas-0.4.1/examples/demo2.html'...
![screen shot 2014-02-15 at 11 38 34 am](https://f.cloud.github.com/assets/3741750/2176032/738ff404-95ca-11e3-97c0-73e91d0c732e.png)

**Comment by DavidHequet** [comment]
Hi,

I had same result when trying to render a bootstrap dialog content, i found that the crop functionnality provider by canvas is faulty when you use float value for left/top crop start.

So i fully render my page with html2canvas then crop my elements providing int value.


you can see result in this jsfiddle so you can update your crop method

http://jsfiddle.net/onclebob/e4rfszpL/12/

**Comment by Paratron** [comment]
I was able to reconstruct the bug - the result is being blurry if you crop the rendered result and not provide integer values for the cropping.

@luckystairs can you confirm that?

**Comment by btm1** [comment]
+1 blurry on retina

**Comment by MisterLamb** [comment]
For those having the issue with retina displays, see my answer in #390

**Comment by niklasvh** [comment]
Fixed in 1.0.0
