### ISSUE TITLE
Image with border-radius does't work

### ISSUE THREAD

**Issue by jorgecasar** [niklasvh/html2canvas#346]
Images with border radius appear as a square. I tryed adding 1px border with color and transparent to force the border.

I also tryed with a wrapper div with the border and overflow:hidden, but it doesn't work either.

Is this a bug? There any CSS trick to solve it?

**Comment by peterzhai** [comment]
@niklasvh hello,I use v1.0.0-alpha.10,and I still have this problem~

**Comment by moothemonkey** [comment]
Has this issue been resolved?  I am trying to download an image from a canvas element that has a border-radius but the saved image (from canvas.todataurl()) is square.

**Comment by KararBarcha** [comment]
**Still not working for me.** "html2canvas": "^1.4.1"
