### ISSUE TITLE
Not hiding overflow:hidden data

### ISSUE THREAD

**Issue by ankur1708** [niklasvh/html2canvas#349]
I am using html2canvas to make 1 image out of 3-4 images. All these images can be zoomed for which i am using jquery zoom. There is one parent div holding all these images.
Overflow is hidden for all these images so that user can set it as per his wish.
Without zooming, on Html2Canvas, i am getting a perfect canvas element. But when any image is zoomed, and then i try HTML2Canvas, the hidden content is shown in canvas created. Is there a solution for this which i may not aware of.
My functionality is similar to http://www.fotor.com/features/collage.html. 
Thanks in Advance.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by Lxiaozhuang** [comment]
请问  这个解决了么  ？  我现在也遇到了这个问题  scale放大后的图片最后在html2canvas生成图片后 隐藏的部分都显示出来了

**Comment by brcontainer** [comment]
@Lxiaozhuang In html2canvas-0.4.1 or in html2canvas-1.0?

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });
