### ISSUE TITLE
IE Browser,no  table borders appear on Canvas

### ISSUE THREAD

**Issue by surajshaha** [niklasvh/html2canvas#350]
Hi,

I have html page returned from server,and it contains one table with border for each th and td in one of the inner table.The plugin is working correctly on Chrome,safari,firefox but IE does not show up the borders of inner table.The borders of outer table are displayed correctly.

Is there any workaround for this ?
Thanks.

**Comment by aju31a** [comment]
I am sorry to say but i am unable solve this issue with the said solution too,can anybody let me know how to do this please its really urgent

**Comment by CarlosHBP** [comment]
I'm using html2canvas 0.5.0-alpha1.

I found a solution. Change the parseInt to parseFloat: 

```javascript
NodeContainer.prototype.cssInt = function(attribute) {
    //var value = parseInt(this.css(attribute), 10);
    var value = parseFloat(this.css(attribute), 10);
    return (isNaN(value)) ? 0 : value; // borders in old IE are throwing 'medium' for demo.html
};
```
IE (and Edge) returned 0.5px when my width was 1px.

I tested on IE 11, Edge and Chrome (Windows).

**Comment by dsauerbrun** [comment]
God damn this was a nasty issue to track down. A client of mine experienced this on windows 8 chrome but not firefox and another client experienced this on windows 10 firefox but not chrome. 

This solution also worked for me... what are the chances that this gets included in the next release?

it appears to be super simple change @niklasvh any thoughts?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by niklasvh** [comment]
@dsauerbrun https://github.com/niklasvh/html2canvas/blob/master/src/parsing/border.js#L42 should be fine in 1.0.0

**Comment by wahyukodar** [comment]
> @dsauerbrun https://github.com/niklasvh/html2canvas/blob/master/src/parsing/border.js#L42 should be fine in 1.0.0

I'm using v1.0.0-alpha.12, That is still error
<img width="1293" alt="screen shot 2018-12-27 at 15 08 46" src="https://user-images.githubusercontent.com/9941259/50471939-5a635500-09e9-11e9-8b1b-aa6ae611d04d.png">
