### ISSUE TITLE
Canvas not rendering background and html5 video/audio controls

### ISSUE THREAD

**Issue by Opariti** [niklasvh/html2canvas#362]
Hi Niklas,
I have used html2canvas for the following chunk (I took out herebelow '< ' and '>' so that to make readable the html):

div id="template_preview"
div class="template-container" style="width: 80%; margin-left: 20%; height: 410.625px;"
div class="template-title" style="text-align: center;" Title /div
div class="row-fluid"
div class="template-choices span5 pull-left" style="height: 270.790625px;">Choices /div
div class="template-media span7 pull-right" style="height: 270.790625px;"
video src="video.mp4" controls="" autoplay="" poster="/Jim/media/pictures/scene_template/video_placeholder.jpg" /
/div
/div
div class="template-statement" style="text-align: center;" Statement /div
/div
/div

The real rendering of the code on the browser is this:

![image](https://cloud.githubusercontent.com/assets/5852904/2540986/c423dbf0-b5d8-11e3-9bcb-c6f80b7a9c32.png)

and the file I get (in jpeg format) is this:

![image](https://cloud.githubusercontent.com/assets/5852904/2541008/00e63092-b5d9-11e3-912e-74ddfba5adcf.png)

The Javascript is:

html2canvas(document.getElementById('template_preview'), {
    onrendered: function(canvas) {
    textToSend = {};
    textToSend['button'] = 'create_template_save';
    textToSend['template_canvas'] =canvas.toDataURL('image/jpeg');
    // code here for ajax
    $.ajax({
        url: document.URL, 
        type: "POST",
        dataType: 'json',
        data: {json_tag:JSON.stringify(textToSend)},
    })
    .done(function(data) {
        if(data.result == 'valid'){  
            alert("Seems ok so far");
        } else {
            alert("Seems not ok!");
        }
    })
    .fail(function() {
        alert( "errorful" );
    });
   }
});

And the PHP is:

$canvasReceived = $objectReceived->template_canvas;
$img = str_replace('data:image/jpeg;base64,','', $canvasReceived);
$img = str_replace(' ', '+', $img);
$data = base64_decode($img);
$file = APPPATH . "media/pictures/scene_template/template" . ".jpeg";
$success = file_put_contents($file, $data);

Please let me know if I hit any limitation (regarding the background color of the region - I ried to put it on option, no work, and the 'canvasing' of the video - also audio - html5 controls). The controls are not rendered even if I save as png.
Thanks

**Comment by prasadKodeInCloud** [comment]
+1

**Comment by mansa-dev** [comment]
+1

**Comment by vishal-px** [comment]
+1
