### ISSUE TITLE
Canvas not rendering for "fill" property

### ISSUE THREAD

**Issue by sameerjoshi** [niklasvh/html2canvas#363]
Hello, I am trying to create a canvas from an SVG. Although the background colors which are added using the "fill" property are not rendered to the canvas.

Working example here - http://jsfiddle.net/illuminatus/Lrpwx/

After creating the canvas, I am saving it as an image using canvas2image which is working fine.

**Comment by rwholey-eb** [comment]
any news on this guy?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
