### ISSUE TITLE
Web-font and icon-font works in firefox but not in chrome. 

### ISSUE THREAD

**Issue by samsonkhisty** [niklasvh/html2canvas#364]
Greetings, 
I tried playing with a very simple project first to try rendering font-awesome and 'Open Sans' web font from google. This works fine on the major browsers. I then moved on to implementing this in my web app (RoR). Currently in localhost, I added logic to convert a simple table to canvas on button click and add the canvas to the document. The table contains some font-icon and the font family. 

I noticed that the canvas renders correctly in firefox but not on chrome or safari. Since my code to convert is called on button click, Am I safe to assume the fonts have been loaded in the DOM? Or is this something to do with localhost?

Attaching some screenshots. 
Original html: 
![screen shot 2014-04-03 at 5 45 55 pm](https://cloud.githubusercontent.com/assets/3254606/2609849/385568ba-bb7c-11e3-9822-ce8239b4a179.png)

Canvas In firefox: 
![screen shot 2014-04-03 at 5 46 10 pm](https://cloud.githubusercontent.com/assets/3254606/2609851/49d436d4-bb7c-11e3-9b3e-0905b40aae07.png)

Canvas in Chrome: 
![screen shot 2014-04-03 at 5 46 31 pm](https://cloud.githubusercontent.com/assets/3254606/2609853/5014d7f6-bb7c-11e3-82fd-ad031138d0f0.png)

Canvas in Chrome after reverting to font-family: "Helvetica Neue", Helvetica, Arial, sans-serif
![screen shot 2014-04-03 at 6 10 09 pm](https://cloud.githubusercontent.com/assets/3254606/2609872/c850cb1c-bb7c-11e3-9413-31b568cbcb46.png)

**Comment by discobanco** [comment]
I tried the one that says "Works on all browsers" and doesn't work on IE for me...

**Comment by AdamTyler** [comment]
Same for me. No demos working on IE11

**Comment by yuepywu** [comment]
I have tried http://samsonkhisty.github.io/html2canvas_fontawesome/examples/demo3.html

on IE11, the rendering result is not showing the font awesome icon correctly, any ideas?

**Comment by the-golden-girl** [comment]
Same for me. On IE, the result is not showing the font awesome icons.
Any solution for this?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
