### ISSUE TITLE
html2canvas not working in iOS 5 devices

### ISSUE THREAD

**Issue by surajshaha** [niklasvh/html2canvas#365]
This library works great in 6.0 and 7.0 devices but unable to render content on canvas in iOS 5 devices.

Any Ideas ? fix ? patch ?
Any help would be greatly appreciated.

--Suraj

**Comment by ianguyue** [comment]
Is it normal to run on IOS 7? I can't normally run on IOS 7.Who khnows the reason?

**Comment by LoLDragon** [comment]
ios7 doesn't work,any solution to fix it?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
