### ISSUE TITLE
Webkit Font Smoothing Support?

### ISSUE THREAD

**Issue by sdnyco** [niklasvh/html2canvas#377]
Hey everyone,

I am building a small tool which requires the output of fonts. 

Fonts look much better in Chrome/Safari using `-webkit-font-smoothing: antialised;`
Unfortunately it doesn't translate to the rendered picture.

Any chance that will be supported in the future? Or has anyone found a way to make it happen?

**Comment by baylock** [comment]
I'm sorry, I'm not very familiar with Github.
I would like to know why this issue has been closed?
It doesn't seem to be resolved and it doesn't seem to be a duplicate neither.
