### ISSUE TITLE
Text overlapping on IE9

### ISSUE THREAD

**Issue by bricesson** [niklasvh/html2canvas#392]
On IE, the text is overlapping. Any idea, what the issue could be?
I'm not using css properties text-spacing or word-spacing and It's working fine on FF and Chrome.

**Comment by ayanakshi** [comment]
Hii.. I am also having the text overlap issue in Internet Explorer 11.
![image](https://user-images.githubusercontent.com/16774643/49439715-cb975a00-f7e7-11e8-9042-67bcab71b1d5.png)

**Comment by KshitijV97** [comment]
Any solution to this?
