### ISSUE TITLE
Feature - Ignore list for elements to be omitted from renderer

### ISSUE THREAD

**Issue by nchinan** [niklasvh/html2canvas#395]
A feature that can omit certain HTML elements from being rendered

for example 
html2canvas(element, { ..., ignore: [".some-class", "#some-id"], ... });

will remove elements matching the ignore array but leave the DOM unaffected.

I have added this feature here

https://github.com/nchinan/html2canvas/commit/62c665c4acf20b1d8924da7bbb4c21335217c0ed

I would like to hear your feedback and suggestions

Regards
Neville

**Comment by brainmonger** [comment]
I'm noticing that with data-html2canvas-ignore, the element is hidden but not actually removed. The result being that there's an empty white space that's left behind where the element used to show. Is there a good way to actually remove that element form the canvas so that there isn't that ugly white space left behind?

**Comment by usmonster** [comment]
See above comment--the way to do this would be to use the `onclone` option to modify the cloned document (e.g. set a class or style on the element that does `display: none`, or just remove said element) before rendering happens. The `data-html2canvas-ignore` doesn't do that by default as it would cause a reflow (expensive) and possibly also significantly change page rendering in unexpected ways.

**Comment by brainmonger** [comment]
Great, thanks. Still having some margin issues on the rendered image but this seems to work as intended. Example:

html2canvas($("body"), {
                    onclone: function(document) {
                        if (options.elementsToIgnore.length) {
                            for (var i = 0; i < options.elementsToIgnore.length; i++) {
                                $(document).find(options.elementsToIgnore[i]).remove();
                            }
                        }
                }}).then(function(canvas) {
                    var imgData = canvas.toDataURL('image/png');
                    var doc = new jsPDF('p', 'pt', 'a4');
                    doc.addImage(imgData, 'PNG', 0, 0);
                    doc.save('sample-file.pdf'); //creates a pdf
                }).catch(function(error) {
                    done(error);
                });

**Comment by Muneem** [comment]
For me its still showing that whitespace. When I add element which I have to show as image then its fine but when I add it with another element then whitespace is being added for ignored element. I tried to remove it from DOM also but no luck
