### ISSUE TITLE
Render a hidden div

### ISSUE THREAD

**Issue by funnykriss10** [niklasvh/html2canvas#396]
I am converting a div into canvas and then saving it into pdf. It works well if the div is visible,But I want the div to be hidden so I made the visibiltiy of the div hidden.Now it shows blank on pdf.

Is there a way to render hidden division?

**Comment by rudda** [comment]
is there any fix? Issue closed but not a have solution

**Comment by rudda** [comment]
@brcontainer could You check #1719 ?
