### ISSUE TITLE
html2canvas border radius not applying to img tag

### ISSUE THREAD

**Issue by faiq-naseem** [niklasvh/html2canvas#399]
Need help, when i apply border radius to image via css, Not rendering.
See demo
http://faiqnaseem.com/html2canvas/

<style>
#mydiv {
    width: 300px;
    height: 200px;
    background:#000;
    
    
}
#mydiv img {
    width: 200px;
    height: 200px;
    border-radius:100%;
    
    
}
</style>

Resultant displayed image not showing border radius,Just without radius i need to apply radius only through this method.

if i used image as background, it works but i need to put image in div tag, it is dynamically adding from database..

![untitled](https://cloud.githubusercontent.com/assets/7893333/3280720/b43fe7e0-f478-11e3-849d-cfaa06a00ad5.png)

**Comment by uaison** [comment]
I met the same problem with you, and then, have you solve the problem?

**Comment by uaison** [comment]
The following functions can solve this problem:
function CanvalHD(canvasThis,ctxThis){
    (function (canvas, ctx) {
        var devicePixelRatio = window.devicePixelRatio || 1;
        var backingStorePixelRatio = ctx.webkitBackingStorePixelRatio ||
                                     ctx.mozBackingStorePixelRatio ||
                                     ctx.msBackingStorePixelRatio ||
                                     ctx.oBackingStorePixelRatio ||
                                     ctx.backingStorePixelRatio || 1;
        var ratio = devicePixelRatio / backingStorePixelRatio;
        if (devicePixelRatio !== backingStorePixelRatio) {
            var oldWidth = canvas.width;
            var oldHeight = canvas.height;
            canvas.width = oldWidth * ratio;
            canvas.height = oldHeight * ratio;
            canvas.style.width = oldWidth + 'px';
            canvas.style.height = oldHeight + 'px';
            ctx.scale(ratio, ratio);
            }
        })(canvasThis, ctxThis);
    }

This is due to the different of screen pixels ratio, iPhone screen is 2, PC display is 1, and Android screen is 1.5, 
See the website:
http://segmentfault.com/q/1010000002533478
