### ISSUE TITLE
html2canvas.js not Working in IE9/10/11

### ISSUE THREAD

**Issue by mahenedram** [niklasvh/html2canvas#409]
We want to capture screenshot of Div (HTML element) which is inside an IFrame. IFrame loads inside another Div at runtime in a html page. For capturing screenshot we are using html2canvas.js API.

Code is working very well with Mozilla and Chrome but not working in IE9/10/11.

The basic requirement is that to capture screenshot of Div and send that image byte-array to Flex application.

Function which captures screenshot is:

function capturImage() {
    html2canvas(document.getElementById('map_canvas'), {
        proxy: "server.js",
        useCORS: true,
        onrenderd: function (canvas) {
            var imageData = canvas.todataURL('image/png', 1.0);
            imageDataOnly = imageData.split(",");
            falshObj.getImage(imageDataOnly[1]);
        }
    });
}

Error In IE:

SCRIPT438: Object doesn't support property or method 'getComputedStyle' File: html2canvas.js, Line: 2269, Column: 5

Please let me know if anyone had similar experience or has any clue in resolving the issue.

**Comment by anujamahamunkar** [comment]
Following is my code not working on internet explorer 9+ .I done implementation part using promise js for supporting promise in internet exploer

step1:
![image](https://user-images.githubusercontent.com/38125670/38407609-cfab3dc8-3997-11e8-9a5a-da679ddbac24.png)
step 2:
![image](https://user-images.githubusercontent.com/38125670/38407646-f37348f4-3997-11e8-8d6a-c05944e6f46f.png)
error in internet explorer :
![error](https://user-images.githubusercontent.com/38125670/38407847-b30dc284-3998-11e8-8b2e-81f91b103d95.png)

Thanks in advance
