### ISSUE TITLE
Meta: rc branch status / repo cleanup

### ISSUE THREAD

**Issue by usmonster** [niklasvh/html2canvas#421]
Hi @niklasvh. Thanks for a great tool! It's really freaking awesome.

I just wanted to know if there's anything we can do to help make the rc branch pass all the build tests, maybe turn the rc branch into the new develop branch (or at least merge it), triage (categorize, close/merge, assign to milestones) all the issues, and get a new version out?

Looks like the last commit was a couple months ago, though it also looks like a bunch of issues have been addressed on the rc branch, even though the build fails. Meanwhile, lots of (possibly-irrelevant) issues against the year-old version continue to be filed.

Do you need collaborators? Or can you make a "helpwanted" label to highlight particular issues that break the build on the rc branch? I know it's not your full-time job, but--whenever you have a chance--feel free to use the crowd to help get everything in ship shape.

Thanks again, and keep up the amazing work!

**Comment by niklasvh** [comment]
Added first prerelease (0.5.0-alpha1) to https://github.com/niklasvh/html2canvas/releases/tag/0.5.0-alpha1

**Comment by niklasvh** [comment]
Closing, #1167
