### ISSUE TITLE
Input box text and checkbox/radio issue

### ISSUE THREAD

**Issue by nileshlets** [niklasvh/html2canvas#425]
Hi,
I am using html 2 canvas and having issue with input fields.
1) Text box text are centred but not showing text in middle it shows stick to the bottom . In html text is set to vertically middle by padding but in canvas it is not looking same.why?
2) checkbox and radio are not displaying in canvas.

Any help will be appreciated.

**Comment by loverdrive** [comment]
Hi, 
i tried the js posted by nileshlets and also the new 0.5 version (alpha 2), but it doesn't display radio button.
In the page where i'm using html2canvas, radio elements are generated by angularjs, i don't know if this could be the problem.

Any help will be appreciated

**Comment by Damdias** [comment]
This help me lot. Thanks

**Comment by RupenAnjaria** [comment]
Damdias: Can you please let us know what helped you? I am facing some issues in conversion.

**Comment by Damdias** [comment]
Hi Rupen,
Initially, Checked boxes are not export correctly. with that version of js file it worked for me

**Comment by RupenAnjaria** [comment]
I am getting while lines around radio buttons (using 5.0)

**Comment by jrivals** [comment]
Hi,

With the 0.5 version (beta 4), it well displays radio buttons except if they are disabled.
Is it the expected behaviour or a bug to fixed ?

**Comment by ashishmangl73** [comment]
I am also facing the same problem
