### ISSUE TITLE
Overlaping vertical and horizontal lines in the canvas

### ISSUE THREAD

**Issue by basnetujwal** [niklasvh/html2canvas#429]
Hi,
I have been using html2canvas.js but my problem is that when I render html to canvas the horizontal and vertical line overlaps the rendered canvas image. Can you have a look at it or give me some advice to remove the lines? I have attached the sample image over here and its in the case of Chrome Browser but in the case of firefox canvas image seems to be blank.

I look forward to hear from you soon.

Thanks,
Ujwal
![canvas image issue](https://cloud.githubusercontent.com/assets/5961912/4026778/c8fe70b2-2c21-11e4-8e2d-984f0f91b4d2.png)

**Comment by russjman** [comment]
I am also having this issue, on FF and IE, not in Chrome. The images are fairly large(800px or so), and also part of a for loop. Not seeing the vertical lines reported by @basnetujwal, only horizontal.

`
function convertElementsToImages(containerSelector) {
                var eles = $(containerSelector + ' > *'),
                q = $q.defer(),
                temp = [];

            //convert to canvas
            angular.forEach(eles, function(ele, eleKey) {
                convertElementToImage(ele).then(function(imageData) {
                    temp[eleKey] = imageData;

                    //last one, hopefully all previous elements have been resolved
                    if (eles.length === eleKey + 1) {
                        q.resolve(temp);
                    }
                });
            });

            return q.promise;
        }

function convertElementToImage(element) {
            var q = $q.defer();

            html2canvas($(element)[0], { // jshint ignore:line
                onrendered: function(canvas) {
                    q.resolve(canvas.toDataURL('image/jpeg'));
                }
            });
            return q.promise;
        }`

**Comment by markadrake** [comment]
I don't think this should be closed, and just for record it's the same (or similar) as #1033
