### ISSUE TITLE
Javascript html2canvas cant get background and Icon

### ISSUE THREAD

**Issue by rajamuthukaruppan** [niklasvh/html2canvas#432]
I'm using html2canvas v0.4.1 for screenshot. I'm facing issues like background css not getting rendered.

I have a div with the css below :
div{
    background: linear-gradient(to bottom, #eeeeee 0%, #bababa 100%) repeat scroll 0 0 rgba(0, 0, 0, 0)
}

This background not getting rendered. Please any one give me the solution.

Thanks

**Comment by prashant22saxena** [comment]
where can i get 0.5 version cdn
