### ISSUE TITLE
Problem with street view

### ISSUE THREAD

**Issue by albecortes** [niklasvh/html2canvas#434]
Hi!
First of all I would like to thank you for this awesome code, I love what you have done in html2canvas!
I am having an issue when trying to capture a street view image, but only in Chrome... in firefox is working correctly.
After looking at the divs generated by Google maps. I see that there are a lot of levels. Attached you can see a screenshot. There are positions like this:

```
//div 0
<div id="map_canvas">
    //div 1
    <div class="gm-style"> </div>    //with the aerial map (z-index:0)
    //div 2
    <div class="gm-style">           //with the street view images (z-index:1)
           //div 2_1
           <div>                     //with a grey background
                  //div 2_1_1
                  <div></div>        //With the street view image I want to print
           </div>  
            ...                      //Other elements in the map, like arrows, address, etc...
    </div>
</div>
```

When I used html2canvas, it is capturing the grey background of the div 2_1. When I print again without the background, it is giving me back the div 1, but never the div 2_1_1. I guess it is a problem with how Chrome is managing the css rules because it is working in Firefox but not in Chrome...
Do you have any idea why is this happening?
Thanks a lot for your support.

![streetview](https://cloud.githubusercontent.com/assets/7578815/4088092/5183a6d0-2f58-11e4-94d1-92847a703501.PNG)

**Comment by cht8687** [comment]
got the same issue when try to save streetview on Chrome...
