### ISSUE TITLE
Unable to crop canvas

### ISSUE THREAD

**Issue by JulianAnthes** [niklasvh/html2canvas#437]
In your old release I was able to crop the canvas by setting width & height, but in your 0.5 rc1 it will be ignored. Have you changed the syntax or anything else?

**Comment by AlonCG** [comment]
Just checking ... were these changes also supposed to be in Alpha2? Seems I am having the same issue, and looking at the source code I have (which does not mean I actually have the latest) ... it appears that some of these changes implemented. (Or that once compiled, my dist html2canvas.js does not match up to the one in the change set.)
