### ISSUE TITLE
 Error loading <img>

### ISSUE THREAD

**Issue by ghost** [niklasvh/html2canvas#444]
Cant get it to work..
Background image is caputerd, but no other images.
I try to capture a div /w unorder list and images in its listitems.

html2canvas: Preload starts: finding background-images html2canvas.js:21
html2canvas: Preload: Finding images html2canvas.js:21
html2canvas: Preload: Done. html2canvas.js:21
html2canvas: start: images: 0 / 0 (failed: 0) html2canvas.js:21
Finished loading images: # 0 (failed: 0) html2canvas.js:21
html2canvas: Error loading <img>:http://mydomain.de/cms_neu/content/modulart/img/confetti.jpg html2canvas.js:21
html2canvas: Renderer: Canvas renderer done - returning canvas obj

**Comment by NikhilRadadiya** [comment]
@brcontainer IF I want to use php proxy where to put that `html2canvasproxy.php` file?. I'm using `html2canvas` with `Angular2`
