### ISSUE TITLE
google maps problem

### ISSUE THREAD

**Issue by felipesmendes** [niklasvh/html2canvas#453]
I tried again to generate image of google maps in a PDF document and got this image:
![google maps](https://cloud.githubusercontent.com/assets/992965/4445158/2e5036da-47f7-11e4-8c51-1ec9d73e5e1b.png)

Log:
217ms html2canvas: Document cloned app.min.js:6
246ms html2canvas: Initialized CanvasRenderer with size 1362 x 840 app.min.js:6
247ms html2canvas: Starting NodeParser app.min.js:6
288ms html2canvas: Fetched nodes, total: 255 app.min.js:6
291ms html2canvas: Added image #1 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24943&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
292ms html2canvas: Added image #2 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24943&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
292ms html2canvas: Added image #3 http://mt0.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24944&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
292ms html2canvas: Added image #4 http://mt0.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24944&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
293ms html2canvas: Added image #5 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24943&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
293ms html2canvas: Added image #6 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24943&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
294ms html2canvas: Added image #7 http://mt0.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24944&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
294ms html2canvas: Added image #8 http://mt0.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24942&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
294ms html2canvas: Added image #9 http://mt1.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24945&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
295ms html2canvas: Added image #10 http://mt0.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24942&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
295ms html2canvas: Added image #11 http://mt1.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24945&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
296ms html2canvas: Added image #12 http://mt0.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24944&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
296ms html2canvas: Added image #13 http://mt1.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24945&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
296ms html2canvas: Added image #14 http://mt0.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24942&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
297ms html2canvas: Added image #15 http://mt0.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24942&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
297ms html2canvas: Added image #16 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24945&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
298ms html2canvas: Added image #17 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24941&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
298ms html2canvas: Added image #18 http://mt0.googleapis.com/vt?lyrs=m@275316444&src=apiv3&hl=pt&x=24946&y=36957&z=16&apistyle=s.t%3A33 app.min.js:6
298ms html2canvas: Added image #19 http://mt0.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24946&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
299ms html2canvas: Added image #20 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24941&y=36956&z=16&apistyle=s.t%3A33 app.min.js:6
300ms html2canvas: Added image #21 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24941&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
300ms html2canvas: Added image #22 http://mt1.googleapis.com/vt?lyrs=m@275000000&src=apiv3&hl=pt&x=24941&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
300ms html2canvas: Added image #23 http://mt0.googleapis.com/vt?lyrs=m@275316444&src=apiv3&hl=pt&x=24946&y=36958&z=16&apistyle=s.t%3A33 app.min.js:6
301ms html2canvas: Added image #24 http://mt0.googleapis.com/vt?lyrs=m@275307942&src=apiv3&hl=pt&x=24946&y=36955&z=16&apistyle=s.t%3A33 app.min.js:6
301ms html2canvas: Added image #25 http://maps.gstatic.com/mapfiles/api-3/images/google_white2.png app.min.js:6
301ms html2canvas: Added image #26 http://maps.gstatic.com/mapfiles/api-3/images/mapcnt3.png app.min.js:6
302ms html2canvas: Added image #27 http://maps.gstatic.com/mapfiles/api-3/images/cb_scout2.png app.min.js:6
314ms html2canvas: Finished searching images app.min.js:6
328ms html2canvas: Succesfully loaded image #27 
x
 app.min.js:6
328ms html2canvas: Succesfully loaded image #26 
x
 app.min.js:6
328ms html2canvas: Succesfully loaded image #25 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #24 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #23 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #22 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #21 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #20 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #19 
x
 app.min.js:6
329ms html2canvas: Succesfully loaded image #18 
x
 app.min.js:6
330ms html2canvas: Succesfully loaded image #17 
x
 app.min.js:6
330ms html2canvas: Succesfully loaded image #16 
x
 app.min.js:6
330ms html2canvas: Succesfully loaded image #15 
x
 app.min.js:6
330ms html2canvas: Succesfully loaded image #14 
x
 app.min.js:6
330ms html2canvas: Succesfully loaded image #13 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #12 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #11 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #10 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #9 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #8 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #7 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #6 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #5 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #4 
x
 app.min.js:6
346ms html2canvas: Succesfully loaded image #3 
x
 app.min.js:6
347ms html2canvas: Succesfully loaded image #2 
x
 app.min.js:6
347ms html2canvas: Succesfully loaded image #1 
x
 app.min.js:6
348ms html2canvas: Images loaded, starting parsing app.min.js:6
348ms html2canvas: Calculate overflow clips app.min.js:6
451ms html2canvas: Creating stacking contexts app.min.js:6
462ms html2canvas: Sorting stacking contexts app.min.js:6
496ms html2canvas: Render queue created with 483 items app.min.js:6
764ms html2canvas: Finished rendering app.min.js:6
765ms html2canvas: Cropping canvas at: left: 251.5 top: 6 width: 1362 height: 840 app.min.js:6
765ms html2canvas: Resulting crop with width 1110.5 and height 834  with x 251.5 and y 6 app.min.js:6
773ms html2canvas: Cleaned up container app.min.js:6

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
