### ISSUE TITLE
net::ERR_INVALID_URL on google chrome ONLY

### ISSUE THREAD

**Issue by ymorin007** [niklasvh/html2canvas#459]
Hi Niklas.

Just recently I get the following error message net::ERR_INVALID_URL but only on chrome and it use to work perfectly on chrome previously. Not sure if its a new release of chrome that could be the issue.

All the images are not captured. But the all css seems to work.

Any ideas?

GET data:application;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQg…+3WvYKW8YhkO4ADdzg7P8A3wKBoKK2dPMhztwoPPQDNSjZIlEghLhZ2G5yvRPck/X0/WpTS//Z net::ERR_INVALID_URL eternit-presentation-script.js?0965D74D8BBC3E9F3766EAF417BED31B:13621window.(anonymous function) eternit-presentation-script.js?0965D74D8BBC3E9F3766EAF417BED31B:13621(anonymous function) proxy.cfm?url=http%3A%2F%2Fmemberfiles.eterni-t.com%2F27%2F50%2Fhistory-796-original-1.jpg&callback…:2

**Comment by Malavala123** [comment]
data:application;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQg…+3WvYKW8YhkO4ADdzg7P8A3wKBoKK2dPMhztwoPPQDNSjZIlEghLhZ2G5yvRPck/X0/WpTS//Z net::ERR_INVALID_URL eternit-presentation-script.js?0965D74D8BBC3E9F3766EAF417BED31B:13621window.(anonymous function) eternit-presentation-script.js?0965D74D8BBC3E9F3766EAF417BED31B:13621(anonymous function) proxy.cfm?url=http%3A%2F%2Fmemberfiles.eterni-t.com%2F27%2F50%2Fhistory-796-original-1.jpg&callback…:2
