### ISSUE TITLE
Objects larger than screen are only rendered to the max screen size

### ISSUE THREAD

**Issue by PaulMcGuinness** [niklasvh/html2canvas#461]
Hi,

I discovered that objects (e.g. a DIV) larger than the screen (e.g. Shown with scroll-bars) would only render to the max dimensions of the screen.

Changing this line:-

```
return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight).then(function(canvas) 
```

to this:-

```
return renderDocument(node.ownerDocument, options, $(node).width(), $(node).height()).then(function(canvas)
```

resolves the issue.

**Comment by sbsnet** [comment]
I've something very similiar to the code above - I have a fixed sized div I am capturing, so I set a static value - and I set BOTH height and width.
It works great on chrome to grab a <div>
If I do the same thing in IE or Firefox and results are different -- It creates an image that is full sized, but the top of the actual graphic starts about 1/2 way down the image and the bottom is cut off.  The image grabbed is more then displays on the screen, but not the entire document... any idea why the grabbed image would get off set halfway down the image?

**Comment by vance** [comment]
Man, that is a bad solution. After calling `ownerDocument.defaultView.innerWidth = xxx;` it unbinds and will no longer respond to the actual resizing of the window. I'm looking for a way to rebind it, but I haven't found a way.

**Comment by vance** [comment]
you have to do it in an iframe with `ownerDocument.defaultView.innerWidth = xxx; `

**Comment by shohoku11wrj** [comment]
cenap's workaround without touching the source code works for me. My html2canvas.js version is 0.5.0 alpha.

**Comment by KarandikarMihir** [comment]
@cenap Thanks! Your solutions seems to be working. Kudos!

**Comment by WiL-dev** [comment]
For my just was to change `height` parameter.

In the html2canvas.min.js (v0.5.0-beta4) around row 7 col 11479 change
`l.ownerDocument.defaultView.innerHeight` for `l.getBoundingClientRect().height` to end with this:
`...d(l.ownerDocument,n,l.ownerDocument.defaultView.innerWidth,l.getBoundingClientRect().height,f)...`

**Comment by WiL-dev** [comment]
For my works just changing the height value `node.ownerDocument.defaultView.innerHeight` for `node.getBoundingClientRect().height`

In the html2canvas.min.js (v0.5.0-beta4) change the `l.ownerDocument.defaultView.innerHeight` for `l.getBoundingClientRect().height` , leaving it in this way.
`...d(l.ownerDocument,n,l.ownerDocument.defaultView.innerWidth,l.getBoundingClientRect().height,f).then(...`

**Comment by gopinath-sixt** [comment]
@cenap : Ur logic... rocked!!! thank a lot
