### ISSUE TITLE
Full Documentation

### ISSUE THREAD

**Issue by MelonHTML5** [niklasvh/html2canvas#468]
Is there a full documentation available somewhere? I just noticed that there are some features of this awesome library missing on the website: http://html2canvas.hertzen.com/documentation.html

Such as use of "data-html2canvas-ignore" attribute and use of .then promise. I've seen them being used, but can't find them in the documentation.

**Comment by niklasvh** [comment]
Documentation has been updated in https://github.com/niklasvh/html2canvas/tree/master/docs and will be deployed to the website shortly as well
