### ISSUE TITLE
problem trying to capture tinymce content

### ISSUE THREAD

**Issue by mpage38** [niklasvh/html2canvas#474]
It is written in the doc: html2canvas cannot capture iframe, but I tried anyway to capture tinymce content ... and it is working quite well. Except lists, that are not correctly rendered. Is that precisely because it is inside an iframe or there is something else ?
Michel

This 
![html2canvas-pb-tinymce](https://cloud.githubusercontent.com/assets/1390747/5007078/27b4e640-6a4d-11e4-9c49-f08c840f8bb4.png)

**Comment by niklasvh** [comment]
Duplicate of #177
