### ISSUE TITLE
Image come white (empty)

### ISSUE THREAD

**Issue by modymok** [niklasvh/html2canvas#482]
Hello, 

i used html2canvas to save the content of div "include Img, input text svg"

when i the button to save as image, it comes white nothing "empty"

![image](https://cloud.githubusercontent.com/assets/10100913/5328959/9177ecf4-7da7-11e4-897f-e62cefc94689.png)

come this 
![myimage](https://cloud.githubusercontent.com/assets/10100913/5328965/b1f254b0-7da7-11e4-8f48-175a747a2ce1.png)

here is may code http://jsfiddle.net/1jLw1jpx/

**Comment by source-creator** [comment]
I see this was closed, but I still have the issue - what was the resolution?
