### ISSUE TITLE
take screenshot of google map using javascript

### ISSUE THREAD

**Issue by hardikshah157** [niklasvh/html2canvas#485]
Hi 

I tried following code: this div "#map-canvas" contents google map.
$('#map-canvas').html2canvas({
        onrendered: function (canvas) {
            var img = canvas.toDataURL("image/png");
            window.open(img);
        }
    });
}

Using this code I am getting blank map.
Please find output of Google map.

Let me know how to overcome with this issue.

![googlemapimageusinghtml2canvas](https://cloud.githubusercontent.com/assets/4085097/5423525/5e972a7a-82e8-11e4-84a8-97fa7f16c4d0.png)

**Comment by smarecha79** [comment]
Here is a ridiculous hack that does the job. But all this is ridiculously ridiculous.
It does a copy of the image in the canvas, which might not be exportable to base64 data due to stupid security reason. So It does a copy of the canvas in a new canvas, and this one is exportable in base 64.

<html>
<head>
<script src="../js/vendor/jquery-1.11.3.min.js"></script>
<script src="html2canvas.js"></script>
<script>
$(document).ready(function(){

$('img').load(function(){
console.log('loaded');
	html2canvas($(this)[0],{
	allowTaint: true,
    	onrendered: function(canvas) {
            $('img').parent().append($(canvas));
			$('img').remove();
				html2canvas(canvas,{
	allowTaint: true,
    	onrendered: function(canvas) {
		console.log(canvas.toDataURL());
        }
    	});
        }
    	});
})
});
</script>
<style>
</style>
</head>
<body>
<img src="https://upload.wikimedia.org/wikipedia/commons/c/c4/PM5544_with_non-PAL_signals.png"/>
</body>
</html>

**Comment by tarekahf** [comment]
I am facing the same issue. Did you find a solution for this? I want to get a screenshot for google maps using html2canvas. Appreciate your reply.

**Comment by smittysmee** [comment]
Bump. Any Updates?

**Comment by orloxx** [comment]
Passing `useCORS: true` in the options fixed the issue for me.

**Comment by NikhilDole** [comment]
I am facing the same issue. I tried using useCORS: true and allowTaint: false in the Map Options but that did not help. I am trying to get the screenshot only after the page is loaded. Am I missing anything?

**Comment by shaji-Dev** [comment]
I'm getting an issue too when taking screenshots of Google Maps, I get this error:
```
ERROR Error: Uncaught (in promise): InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at CanvasRenderer.<anonymous> (html2canvas.js:6289)
    at step (html2canvas.js:83)
    at Object.next (html2canvas.js:64)
    at fulfilled (html2canvas.js:54)
    at ZoneDelegate.invoke (zone-evergreen.js:365)
    at Object.onInvoke (core.js:39698)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:851
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:39679)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at invokeTask (zone-evergreen.js:485)
    at ZoneTask.invoke (zone-evergreen.js:470)```

Please, this is very important.
