### ISSUE TITLE
is there a way to capture iframe content ?  

### ISSUE THREAD

**Issue by AviYafe** [niklasvh/html2canvas#487]
i saw in the limitation that we can't capture iframe of html. but i wonder is there a way to overcome this issue in any other way . 

thanks, Avi

**Comment by kafee651** [comment]
Is there any cross origin iframe capture?

**Comment by hkalex** [comment]
We are having the same problem that we would like to capture the image inside an iframe from different domains. We tried the subdomain and it is not working :( so any cross origin iframe capture solution?

**Comment by niklasvh** [comment]
Cross origin iframes are not possible due to browser security restrictions. You will need a proxy to download the get the contents to the same origin.
