### ISSUE TITLE
using proxy causes error 'Missing Argument'

### ISSUE THREAD

**Issue by AviYafe** [niklasvh/html2canvas#488]
i tried to run local proxy on my machine but  i each request i get and error says 'Missing arguments'

i see that imageur is sent but no callback is sent , is it a configuration issue.

can you help me with this.

**Comment by niklasvh** [comment]
Which proxy are you using?

**Comment by AviYafe** [comment]
@niklasvh i amk using php and node bith of them as the same problem.

**Comment by brcontainer** [comment]
@AviYafe Which proxy are you using?
