### ISSUE TITLE
html2canvas is not working in firfox

### ISSUE THREAD

**Issue by shankarwiz** [niklasvh/html2canvas#491]
Html2canvas is working fine in chrome but it is not working in firefox. in IE and Chrome it is working fine.

Below is my function 
function screenShot(idSet, prodId) {
        debugger;
        var elem = document.getElementById(idSet);
        var elem1 = $("#dvBackgroundImage")[0];
        var obj = "#" + idSet;
        html2canvas($(obj), {
            "onrendered": function (canvas) {
                debugger;
                var img = canvas.toDataURL("image/png");
                var output = img.replace(/^data:image\/(png|jpg);base64,/, "");
                output = output.replace(/\s+/g, '');
                var output = encodeURIComponent(img);
                var Parameters = "image=" + prodId + "," + output;
                $.ajax({
                    url: '@Url.Action("SaveCapturedImage")',
                    type: 'POST',
                    data: Parameters,
                    datatype: 'JSON',
                    success: function (data) { },
                });
            }
        });
    }

I have attached the screenshots for difference chrome and firfox. In chrome options are passing with complete onrendered fucntion where as in firefox it is passing like this "screenShot/<.onrendered(canvas)".
![firefox](https://cloud.githubusercontent.com/assets/10255361/5516188/2c5bec08-88b5-11e4-8311-f0242e82c486.PNG)
![chrome](https://cloud.githubusercontent.com/assets/10255361/5516190/3f30595e-88b5-11e4-82a7-8e23b5f737f4.PNG)

Please let me know what is the wrong in my code.

**Comment by cptdanko** [comment]
I had a problem with Firefox too and I solved it using a simple timeout. I wrote a blog post about it, you can see it in that link,

http://captaindanko.blogspot.com.au/2015/01/capturing-screenshot-of-page-from-your.html

I had also posted a question on Stackoverflow but didn't quite get the answer I was looking for.
http://stackoverflow.com/questions/26604942/cant-draw-the-contents-of-a-div-onto-a-canvas-using-html2canvas-without-a-timeou?noredirect=1#comment41855926_26604942

**Comment by usmonster** [comment]
@cptdanko It's not clear whether the issues reported here are the same or unrelated. Can you provide a link to a jsFiddle/jsbin, or some other publicly-accessible link to a page with running code that demonstrates your exact issue?

**Comment by cptdanko** [comment]
ok I should have been more clear. So i will make it more clear, this is an extract from the original issue description by "shankarwiz"
"Html2canvas is working fine in chrome but it is not working in firefox. in IE and Chrome it is working fine."

I too had the same problem and i solved it by setting a timeout, you can read a description for that in this post,
http://captaindanko.blogspot.com.au/2015/01/capturing-screenshot-of-page-from-your.html

That post also contains snippets of the sort of code that I had written for it.

Now what I could not fully understand is, why did i need to use a timeout to make it work on Firefox? So I do not have an outstanding issue or anything. I just wanted to understand why the timeout should be used. All I have are educated guesses as to why I might need to use it, but not a solid understanding that I can back it up with facts.

**Comment by usmonster** [comment]
@cptdanko Thanks for explaining which issue is affecting you. The problem is that the original issue was also not very clearly described, as "not working" can mean any number of things, and there is no logging output or link to a demo of the issue. The original poster also seems to be using a version that is no longer supported.

I had already seen your blog post and code snippet, but the best way to troubleshoot and get your questions answered is to provide a link to a page that actually runs the code that demonstrates the issue in action, e.g. jsFiddle, jsbin, etc. Feel free to paste your code snippet into one of those sites and check that is still exhibits the same broken behavior in Firefox. (Please also use the `logging: true` option.) Thanks again!

**Comment by cptdanko** [comment]
Ok so I was just commenting on how i resolve the issue reported here, what I have written here is not really an issue affecting me in my work right now, i just want an understanding. The logging is useful, anyway for what I have talked about, I think my stackoverflow question is fairly self-explanatory, 
http://stackoverflow.com/questions/26604942/cant-draw-the-contents-of-a-div-onto-a-canvas-using-html2canvas-without-a-timeou?noredirect=1#comment41855926_26604942
so I am not sure how a jsfiddle or pastbin will help here.

**Comment by usmonster** [comment]
@cptdanko Your timeout workaround should not be necessary, so it should be considered a bug. Including a jsFiddle or jsbin (not pastebin) would help by making it much easier for others to run and troubleshoot your code, which would lead the understanding you seek as well as the possible resolution of the bug for all others who use the library. I understand that you wanted to share your workaround, but a providing a page that runs the code would be a more helpful contribution and more conducive to getting an explanation/answer to your question.

**Comment by niklasvh** [comment]
There's plenty of test cases that work fine with Firefox without a timeout:
 - https://github.com/niklasvh/html2canvas/tree/master/tests/mocha
 - https://github.com/niklasvh/html2canvas/tree/master/tests/cases

So unless you can actually show a case where it wouldn't work without a timeout, there isn't much we can or will do about it. If you run html2canvas on a container before it is present or has content, or the styles for it have been assigned, then obviously it won't work either, but the solution for that would be to wrap it in a window load, content load or domready event.

**Comment by cptdanko** [comment]
I will see if i can put together something to demonstrate this. I am not sure how to reproduce the exact case that i had, mainly because i was using it in a GWT application, and the issue with GWT is that you dont have your traditional html/js code.

**Comment by usmonster** [comment]
@cptdanko It definitely helps knowing that you're in a GWT context. Try using the `-style DETAILED` flag when compiling the app, and then you should be able to copy the relevant parts of the generated JS and reproduce the issue.

**Comment by programmin1** [comment]
If you had to add a timeout, it's most likely something that hasn't loaded. Had you tried putting the code in a window.addEventListener('pageshow', function) instead of window.addEventListener('load', function) ?

**Comment by jasmeetjaggi** [comment]
https://jsfiddle.net/k4yxrfte/2/ Hi please look a the jsfiddle. Unable to take the screenshot.

**Comment by AhmetFUsta** [comment]
I thought FireFox didn't allow this because of security issues. Loading in your html to code can lead to script injection.
