### ISSUE TITLE
iFrame-less option, and other speed improvements

### ISSUE THREAD

**Issue by mudcube** [niklasvh/html2canvas#492]
I'm working towards getting the speed of a basic renderer down, currently the most basic rendering takes over 100ms on my computer. iFrame generation takes 60ms on it's own for me. I bypassed the createWindowClone and rendering still works the same—it looks like the iFrame is for Chrome and "background-images", is that the only reason? Would you be interested in an option to turn iFrame rendering off, e.g. option.useIFrame = false (true by default)

Another thing I'm noticing is there are a lot of objects being created on each render that don't need to be recreated (could be cached). Some of the easiest to cache would be Support, ImageLoader, much of the code inside of Font() could be setup once and cached, and a bunch of other little things like that. What do you think about a way to create a reference to html2canvas that persists: 

var context = new html2canvas();
context.render(document.body).then(function(canvas){ });

**Comment by Robinfr** [comment]
:+1:  all for improving the speed. It's one of the major downsides at the moment that is starting to turn me away from using this.

**Comment by bdely** [comment]
Is there a way to speed up the rendering because it is taking 8 seconds to create the snap shot, and that 8 seconds adds up, because I need it to take anywhere from 15 to 50 snap shots for creating thumb nails of tiles. Is there some way to have it not block the UI for the 8 seconds, I could live with that time if it wouldn't block the UI.

**Comment by programmin1** [comment]
Just curious, in what browser do you notice this? It is a bit slow but I don't think it could use WebWorkers in background threads because DOM isn't thread-safe and allowed from that context?

**Comment by bdely** [comment]
I notice it in every browser. Ya i know it will not work in WebWorkers, wish it could though lol. I have tried to clone the element and put it in an iFrame and have the code in the iFrame run the snap shot so that it would do the work and not the main page but it doesn't seem to work. 

How long does one snap shot take for everyone else?

**Comment by niklasvh** [comment]
@bdely Are you using 0.4.1?

**Comment by bdely** [comment]
I am using 0.5
Just tested the latest build add it takes between 4 and 5 seconds.

**Comment by Bigous** [comment]
Same to me using 0.5-alpha2... 4-6 seconds each snap.

**Comment by Bigous** [comment]
Version 0.4.1 takes 0.7s each snap, but it does not suport svg.

**Comment by bnolan** [comment]
I would absolutely use a version that didn't use iframes, that would be a great example. In SceneVR, I'm rendering dozens or hundreds of divs to canvases, and creating the iframe causes bad lag that results in dropped frames and judder in the oculus rift.

@mudcube do you have a fork with the no-iframe / re-use iframe code patched in? I'm happy to submit a PR, I really need this function. :)

**Comment by bnolan** [comment]
I hacked this up in `scenevr/html2canvas` and the performance for rendering many divs is about 100x faster. Would you accept a PR for `cacheIframe: true`?

**Comment by brcontainer** [comment]
Try create a loader in "overlay", eg with jQuery:

- http://www.jqueryscript.net/loading/Creating-A-Loading-Indicator-with-jQuery-CSS3.html
- Repo: https://github.com/ninjaonsafari/jquery.loading-indicator

**Comment by bnolan** [comment]
I'm about to use html2canvas to create a web texture component for aframevr - has there been any progress on reusing an iframe instead of creating a new one for each render?

**Comment by mudcube** [comment]
One thing to speed things up would be to use a faster Promise implementation. At least, this is what I found back in Dec. It looks like the promise shim was dropped from the dist, which is great. Bluebird will be much faster than native Promises however.

@bnolan Here's a [GIST](https://gist.github.com/mudcube/1a05b8f64dcd118abad9). It's modified from 0.5 alpha-1. It's by no means a complete solution, I may of disabled some features but forget what exactly (there would be an early return). My main interest was in paragraph rendering.
