### ISSUE TITLE
Background images aren't rendering

### ISSUE THREAD

**Issue by Dobz** [niklasvh/html2canvas#496]
Background images aren't rendering in the latest commit, as seen here: http://jsfiddle.net/j7etuy4q/

The JSFiddle was taken from #458 where the issue was supposed to be fixed, although now it seems to be broken again.

Tested in Chrome 39 (Win 64 & OS X 64), Firefox 34 (Win 64 & OS X 64), Safari 8 and Internet Explorer 11. There aren't any error messages in the log, and none of the images are tainted.

**Comment by Dobz** [comment]
This seems to have been introduced in 498527918c3324dce77260057bc47c280cc3324f

**Comment by niklasvh** [comment]
Fixed, thanks!
