### ISSUE TITLE
parsing background images on windows fails

### ISSUE THREAD

**Issue by steno916** [niklasvh/html2canvas#497]
function parseBackgrounds(backgroundImage) fails to parse the block and definition if the file url contains ( or ). 

Given the following url string
url('file:///c:/Program Files(x86)/myApplication/images/ico_graph_off.png')

parseBackgrounds yeilds

block = url('file:///c:/Program Files(x86)/myApplication/images/ico_graph_off.png')
definition ='file:///c:/Program Files(x86)/myApplication/images/ico_graph_off.png'

This fails to load the image because the single quotes have not been removed.

Given the following url string
url(file:///c:/Temp(x86/myApplication/images/ico_graph_off.png)

parseBackgrounds yeilds

block = url(file:///c:/Temp(x86/myApplication/images/ico_graph_off.png)
definition = file:///c:/Temp(x86/myApplication/images/ico_graph_off.png) 

This fails to load the image because of the closing parenthese isn't removed.

**Comment by brcontainer** [comment]
html2canvas should be used with `http://` protocol preferably. Example is Apache ou Nginx.
