### ISSUE TITLE
CanvasRenderer.variables & save/restore state

### ISSUE THREAD

**Issue by mudcube** [niklasvh/html2canvas#498]
I'm noticing that the CanvasRenderer.variables are not being tracked properly with save/restore states. How would you prefer to fix this:

(a)  make this.variables into an array for tracking states, and pop/push when save/restore is run.
(b)  tap into native tracking of variables—e.g.: use "if (this.ctx[property] !== value) {" instead of "if (this.variables[property] !== value) {" in CanvasRenderer.prototype.setVariable

I think option (b) would be easier, and you don't have to worry about things as much. I did a jsperf on the performance gains of using this.variables, and it's negligible on 1,000,000 checks.

This will fix issues with shadow not rendering properly in certain cases, such as this:

  	<div style="font-family: futura; text-shadow: 0 0 5px #0ff, 2px 2px 0 #ccc;">
	  Giant <i style="color: #37a5ff">blue</i> <b style="color: #ff2395; text-decoration: underline">lobsters</b>!!!
	</div>

**Comment by mudcube** [comment]
Here's a couple example images:

if (this.ctx[property] !== value) {
![ctx](https://cloud.githubusercontent.com/assets/101564/5714131/4964c542-9a79-11e4-8e04-8c6d2a73191b.png)

if (this.variables[property] !== value) {
![variables](https://cloud.githubusercontent.com/assets/101564/5714132/4966e548-9a79-11e4-8642-0a9cf2a2fa15.png)

**Comment by mudcube** [comment]
Weeee, multiple text-shadows in HTML2Canvas (editing NodeParser.prototype.paintText):

![screen shot 2015-01-12 at 5 35 03 pm](https://cloud.githubusercontent.com/assets/101564/5714704/63fc783e-9a81-11e4-932f-a87305a65923.png)

**Comment by niklasvh** [comment]
Option b) sounds good assuming the perf diff is negligible. Could you share url to the jsperf you did?

**Comment by mudcube** [comment]
Sorry it wasn't a "jsperf", I was just running a "js perfomance" loop 1,000,000 times. 

Running in jsperf.com, here's there results:  http://jsperf.com/context-vs-variables

Ctx runs 32 million checks per second on my machine, and Variables runs 160 million checks (each test is running 4 checks). To me it's a toss up, as currently Variables is only used for Shadow, and this jsperf is not taking into account the additional overhead of adding a custom save/restore function which would be run on CanvasRenderer.prototype.clip(), as well as some NodeParser.prototype.paint() and NodeParser.prototype.paintNode() calls.

**Comment by niklasvh** [comment]
We can ditch the variable cache for now. There are plenty of pending issues still for 0.5 and many better places to look for perf optimizations.

**Comment by mudcube** [comment]
Closed in #499

**Comment by stursby** [comment]
@mudcube, @niklasvh did this ever get merged? I'm also trying to use multiple text shadows but not having any luck. Here's my working demo --> https://jsfiddle.net/stursby/cb05ucyz/
