### ISSUE TITLE
Flash support?

### ISSUE THREAD

**Issue by rohillion** [niklasvh/html2canvas#5]
Hi! First of all I want to say nice job niklasvh! I just want to know if it support flash already, because I have made some tries and it is not capturing flash stuff.

**Comment by kenef** [comment]
Any progress on this? Thanks in advance.

**Comment by val1984** [comment]
A lot has changed in 7 years since this ticket was closed and as Flash is being phased out, I don't think anyone is gonna spend time on supporting it.

**Comment by kenef** [comment]
val1984 you’re 100% correct. Though flash is still being used for niche applications, such as using articulate storyline to create elearning modules (my current project). So I was hoping someone had picked up the flash side of this and carried the ball a little further over the last 7 years. Oh well.
