### ISSUE TITLE
Taking screenshot breaks layout

### ISSUE THREAD

**Issue by cloakedninjas** [niklasvh/html2canvas#504]
I've been trying out html2canvas for the last couple of days, I'd originally installed it via Bower so had 0.4.1 running. On discovery of a bug with :before elements I manually set Bower to fetch master.

Now when I make a screenshot, my current page loses some styling, I'm screenshotting a SPA so the markup is vast and not easily readable, but I've attached some screenshots:

DOM before screenshotting:
![screen shot 2015-01-15 at 10 10 42](https://cloud.githubusercontent.com/assets/1395013/5755660/2035740a-9c9f-11e4-831b-f0251e3d9b35.png)

DOM after screenshot:
![screen shot 2015-01-15 at 10 11 03](https://cloud.githubusercontent.com/assets/1395013/5755663/29a65842-9c9f-11e4-9cb0-6223b05af493.png)

Any ideas why my existing DOM elements are being affected ?

**Comment by cloakedninjas** [comment]
Ok - so after some investigation - probably not an issue with html2canvas - more an issue with our SPA being re-initialised from inside the iframe context

**Comment by cloakedninjas** [comment]
And after even more investigation it seems to be caused by document.replaceChild and document.adoptNode causing the original DOM to lose style context, some :before and :after nodes would be lost because the CSS that created them was no longer present, even though the <head> remains unchanged.

I've created a workaround by just appending the outerHTML of the cloned document : https://github.com/cloakedninjas/html2canvas/commit/0bfd4a4e1fc92f15ec96a77e38de28729d9548e9

I'll leave this issue closed because I was unable to replicate the issue in JSfiddle, but this might be useful to others in the future.

**Comment by benjstern** [comment]
I experienced the same problem in chrome, with many attached css files. The css of the updated html failed to function properly after the copy. The above code fixed it for me as well.

normal:
![captureworking](https://cloud.githubusercontent.com/assets/1266727/5815048/8d6a323c-a09a-11e4-839a-a6b8947795f5.PNG)

broken after copy:
![capturebroken](https://cloud.githubusercontent.com/assets/1266727/5815046/857022bc-a09a-11e4-93f0-91de65a5f366.PNG)

I looked in the css within the chrome developer tools and when the element was selected it would not show up, in the styles panel, after the update.

@cloakedninjas thanks for the fix.

**Comment by benjstern** [comment]
I also couldn't find a way to replicate the issue but i think the **issue should still be addressed**. As in my case it broke a vast *majority* of the styles.

**Comment by niklasvh** [comment]
@benjstern could you provide a simple test case that can be used to replicate the issue?

**Comment by benjstern** [comment]
@niklasvh I regret to report that as much as i would like to i haven't been able to distill the page i was working on enough to be able to find the cause. So at this time i cannot provide a test case. 

I just wanted it noted that it was still a problem, at least for me anyway in the event someone else comes across the same thing, it only seemed to be in one of the pages i'm working on. I'm sorry i couldn't be more helpful.

**Comment by browselab** [comment]
I experienced the same broken CSS issue in Chrome after html2canvas was called. The outerHTML workaround fixed the issue. Thanks.

**Comment by Krish2512** [comment]
@niklasvh : I have same issue with broken CSS. Fix mentioned by @cloakedninjas worked fine. Can we please move the fix to git so that, we can use it. Please suggest

**Comment by rankinstudio** [comment]
This also breaks the css of my page after export.

**Comment by chulander** [comment]
this solved my issue in safari. Anyone know why the solution by @cloakedninjas wasn't merged in?
