### ISSUE TITLE
audit use of `parseInt`

### ISSUE THREAD

**Issue by usmonster** [niklasvh/html2canvas#505]
There seem to be many places in the code where `parseInt` is used where `parseFloat` might be considered more appropriate/correct. This can result in certain rounding errors and blurry renders, as mentioned in, for example, #340 ([relevant comment](/niklasvh/html2canvas/issues/340#issuecomment-70265757)).

It should also be noted that, according to [the spec(s)](https://developer.mozilla.org/docs/Web/CSS/number), pixel (and most other length/position/dimension/number) values can be floating point numbers, so any regular expressions used to parse number values should probably also be audited to ensure they're checking for a possible decimal part, where appropriate.

**Comment by niklasvh** [comment]
Yes. 

Would help a lot as well if we could gather some unit tests that can be tested against while fixing these.

**Comment by usmonster** [comment]
I also wanted to know if there was a way to get (native) screenshots of the Selenium render tests, so we can see exactly why some tests have very low render accuracy on certain browsers?

**Comment by niklasvh** [comment]
The webdriver tests actually compare native screenshots with the html2canvas renders (that's what the percentage on the https://travis-ci.org/niklasvh/html2canvas results refer to). 

I've been meaning to have some API setup so the screenshots could be stored and viewed after each commit as well, since computer image matching isn't very reliable here.

**Comment by usmonster** [comment]
Yep, I meant the second part of storing and viewing the screenshots. :] That would be extremely valuable, I think.

**Comment by niklasvh** [comment]
Considering the lib has been rewritten, most of these should be fixed
