### ISSUE TITLE
Border radius not capped

### ISSUE THREAD

**Issue by Paratron** [niklasvh/html2canvas#506]
Its possible to apply a "too high" border radius to elements, that is being capped by all browsers if its above a value that makes sense.

For example: You have a container that is 200x200px of size and you want to make it a perfect circle. The correct border radius would be 100px - everything above won't work.

However, its a common case that people will use values much higher - mostly when you don't know exactly how the dimensions of the applied image will be. The browser automatically caps the border radius on the highest possible even value - html2canvas doesnt do that, what leads to strange effects.

Demo of the effect: http://jsfiddle.net/gmz0wnwr/

**Comment by niklasvh** [comment]
Thanks for the report and example! Related #319 #318

**Comment by Paratron** [comment]
Oh, sorry - I didn't know that it was reported already. But #318 suggests that it already should be fixed, right?

**Comment by niklasvh** [comment]
It was reverted, as it broke a lot of the existing cases.

**Comment by Paratron** [comment]
I will try and understand your code in the coming weeks, since I'd like to contribute and improve html2canvas. As mentioned on twitter - I am building a product around it and have strong interest in improving this project :)

**Comment by niklasvh** [comment]
Great!

Feel free to drop by at https://gitter.im/niklasvh/html2canvas if you have any questions navigating the code.
