### ISSUE TITLE
Element scroll positions not preserved on clone

### ISSUE THREAD

**Issue by usmonster** [niklasvh/html2canvas#511]
This makes any overflowed elements that have been scrolled from their default positions appear incorrect (unscrolled) in the canvas:

http://jsfiddle.net/o0uco97c/

It's the Element analogue of the past issues with window scroll position (#57, #254, et al.), and it is a regression ([working example](http://jsfiddle.net/o0uco97c/1/) using v0.4.1)

**Comment by tobya** [comment]
Does anyone have any idea of what the workaround for this might be until it is fixed?  I would even try to do a patch myself if someone pointed me in the right direction?

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/commit/585a96a9181e76d3ea31be2104884f68773558e3

**Comment by usmonster** [comment]
Nice! Though looks like either the order or way of drawing text is a bit off here, since the ascender of the `h` can be seen in the current demo when it should be cut off/hidden: http://jsfiddle.net/o0uco97c/ (looks fine in [v0.4.1](http://jsfiddle.net/o0uco97c/1/)).

**Comment by niklasvh** [comment]
That appears to be an issue with hiding overflown content

**Comment by tobya** [comment]
This seems to have fixed my related issue #542 anyway. 

Thanks.

**Comment by ejlocop** [comment]
guys, im newbee here. i have a problem, 
html2canvas only rendering what's visible on screen.
but what i want is to capture the whole scrolling div into canvas.
![1](https://cloud.githubusercontent.com/assets/12082880/7408808/726c29a6-ef53-11e4-8263-787d03ca7fc6.jpg)
![2](https://cloud.githubusercontent.com/assets/12082880/7408809/726ffedc-ef53-11e4-8886-dbd7d6e71a2e.jpg)

can someone help to resolve this? thank you

**Comment by usmonster** [comment]
@niklasvh, is the remaining part of this bug the same as #349? If so, should this one be closed in favor of that one?
