### ISSUE TITLE
Html2Canvas is not able to render multiple DIVs properly 

### ISSUE THREAD

**Issue by loftykhanna** [niklasvh/html2canvas#513]
Html2Canvas is not able to render multiple DIVs properly when 
1.  The number of DIVs increases significantly, OR
2.  The size of each DIV increases significantly (then it fails with fewer number of DIVs)
I am using Html2Canvas Plugin to convert div (containing image) to canvas. I have implemented a recursive function to convert multiple images at a time (see code below).

JavaScript

``` javascript
//counter 
var div_number = 0;


function image2canvas() {
    var img2canvasObj = {
        logging:true,
        onrendered: function (canvas) {
            canvas.id = "cvs" + div_number;
            $("#canvasid").append(canvas);
     //incrementing the counter
            div_number = div_number + 1;

            if (div_number <= 18) {
                html2canvas($("#tempDivforpublishplan" + div_number), img2canvasObj);

            }
            if (div_number === 19) {
<Some Ajax Call>
            }
        }
    };
    html2canvas($("#Content_to_convert" + div_number), img2canvasObj);
}

```

The HTML for multiple images (which I am converting to canvas) is as follows. Note that I am using images as background of div elements. Each of these elements have a base64 string appended to the image URL which is used to convert the image to canvas.
HTML:

``` javascript
<div id="tempDivforpublishplan0" style='background: url("data:image/png;base64,iVBORw0KGgo…..") 0% 0% / 634px 2266.26px; width: 634px; height: 2266.26px; position: relative; cursor: auto;'> </div>
<div id="tempDivforpublishplan1" style='background: url("data:image/png;base64,iVBORw0KGgo…..") 0% 0% / 634px 2266.26px; width: 634px; height: 2266.26px; position: relative; cursor: auto;'> </div>
.
.
.
<div id="tempDivforpublishplan19" style='background: url("data:image/png;base64,iVBORw0KGgo…..") 0% 0% / 634px 2266.26px; width: 634px; height: 2266.26px; position: relative; cursor: auto;'> </div>
```

When image count is more, or the size and resolution of images is high, only few images are converted properly. Remaining images are either converted partially or not converted at all. Is there any workaround which can be used to fix this issue?

**Comment by usmonster** [comment]
Maybe set the [`imageTimeout`](/niklasvh/html2canvas/blob/ed299b3d/dist/html2canvas.js#L586) option higher? Default is 10000 (10 seconds), and since rendering can be pretty intensive/slow sometimes, perhaps a higher timeout would work for you.

**Comment by loftykhanna** [comment]
I changed imageTimeout to 30000 (30 sec) but still the same issue.

**Comment by loftykhanna** [comment]
Please suggest with other approach

**Comment by usmonster** [comment]
Can you put your code in a jsFiddle or jsbin for easier testing?

**Comment by loftykhanna** [comment]
Hi @usmonster  I tried to convert the code to jsFiddle but jsFiddle crashed, as I it cannot accommodate  that much base64 encoded strings. I have made a demo in which you can test it easily. Please give me your email address will send you the code

**Comment by usmonster** [comment]
Actually, can you just try putting the file(s) in a Gist: https://gist.github.com/
?

**Comment by loftykhanna** [comment]
Hi @usmonster,

Please find the files on https://gist.github.com/loftykhanna/5b3660f188a0bab215ac

Thank you for your help

**Comment by loftykhanna** [comment]
@niklasvh Please help in this issue

**Comment by ccemeraldeyes** [comment]
@niklasvh This may be the same issue I'm seeing, in which case some attention would be much appreciated. I am also using a recursive function to render multiple divs and and finding that they get cut off sometimes (rendered offset like 100mm and so they overflow off the page)

**Comment by atdiff** [comment]
@niklasvh and @loftykhanna - What's the status on this?  I'm running into a similar issue with a page that contains multiple images that I'm trying to capture.  One image works fine, but as soon as I add one or more to that, it goes haywire.  It ends up never capturing the other images, and just uses the first image or parts of it.

**Comment by loftykhanna** [comment]
@atdiff Actually Issue is after certain height this plugin do not render the images, I solved the above problem by placing the multiple images over one another by using z-index property. Try out this once.

**Comment by atdiff** [comment]
@loftykhanna - interesting.  Are you referring to the height of the viewable area, the height of the images, or something else?  I know there are quirks with overflows that can cause issues rendering a full page.
I just tested in Chrome dev tools calling html2canvas on one of my images and that worked fine.  I then did the same with my second image and it was fine.  So calling html2canvas individually/explicitly one at a time worked fine.  However, when I execute both calls to html2canvas at the same time, it results in one image rendered correctly and the other as a jumbled mess.  There seems to be a threading or synchronicity issue or something - perhaps.

**Comment by loftykhanna** [comment]
@atdiff  I am referring to height of viewable area. When you will overlap all the images one over another to the top of the page, it should work. I called the html2canvas on multiple images in a loop ... I think there should be no synchronicity issue. Its very hard to comment or understand what exactly you are trying without looking at the code.

**Comment by atdiff** [comment]
I'm executing these two lines in browser at the same time (i.e. pasting and hitting enter).  When executing separately (first html2canvas hit enter, etc.), that works fine.  My divs do contain images, svgs, and some other content, so they're not simple elements.  But I wouldn't expect the quirkiness I'm getting currently.  I've added imageTimeout and timeout with no results, so I'm confident that it's not an image load issue - especially when the elements work fine when done separately.  My "mapone" and "maptwo" are on the same page, one below the other, but I've adjusted the overflow so that they do appear and do get rendered by html2canvas.

> html2canvas($('#mapone'), 
{
   useCORS: true,
   allowTaint: false,
   letterRendering: true,
   logging:true,
   onrendered: function (canvas) {
      var img = canvas.toDataURL('image/jpeg');
          alert('rendered one');
          window.open(img);
          return img;
}});

> html2canvas($('#maptwo'), 
{
   useCORS: true,
   allowTaint: false,
   letterRendering: true,
   logging:true,
   onrendered: function (canvas) {
      var img = canvas.toDataURL('image/jpeg');
          alert('rendered two');
          window.open(img);
          return img;
}});

**Comment by loftykhanna** [comment]
this is because onrendered function will be called once ...

**Comment by atdiff** [comment]
@loftykhanna onrendered is getting called multiple times, it's just not rendering everything correctly.  That link is referring to Meteor which I'm presuming is something totally different.

**Comment by loftykhanna** [comment]
oops sorry for the last comment, there was something else going in my mind....  I used ur code in JS fiddle .... https://jsfiddle.net/udk5yd91/ check this out ...  removed the return statement and its rendering both the divs .. and its working fine ...

**Comment by atdiff** [comment]
@loftykhanna interesting. Maybe it's an issue with the complexity of the content I'm having it render.  My page has multiple leaflet.js maps on it with leaflet-markerclusters, SVG's, and more on it.  One of the maps renders perfectly fine but the other one only ends up containing one or two tiles and those tiles are from whichever map is sent to html2canvas first - and the rest of the image is a black box.  It's very weird.
If I execute the html2canvas calls individually one after the other in the browser, everything is fine.  But if I put them both in together in the console, it blunders every time.

**Comment by atdiff** [comment]
@loftykhanna - I noticed you used version 0.4.1 in your code, so I switched mine to use that instead of the newer 0.5 alpha versions and that worked better for me.
So there must be something with the alpha versions that's causing it.  My SVG's aren't rendered but at least my content is more correct with each map actually displaying and not random pieces.
I wonder if there's an issue with the promise/subscriber logic the it's using now or something with the new SVG logic or something else.

**Comment by maiasmith** [comment]
I had a similar issue, where the contents of only one div were rendering, and I fixed it by setting "position: fixed" on the div that wasn't rendering.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by harshan355** [comment]
I'm running into a similar issue with a page that contains multiple images that I'm trying to capture. 
I m getting incomplete images from html2canvas promise. could you please look into it

**Comment by firzx77** [comment]
@harshan355 @atdiff I was faced the same problem with this.

In my case, I'm calling html2canvas in for loop. The problem occurs when html2canvas start capturing all the canvas, and I scrolled up & down within the page, it causes the html2canvas capturing wrong canvas -- I guess. So I've fixed this by disabling the browser scroll during html2canvas capturing process.

**Comment by harshitverma-dev** [comment]
async takeScreenshot() {
            let id = "#LqsAnalyser" + this.asinData
            html2canvas(document.querySelector(id), { useCORS: true , }).then(function (canvas) {
                canvas.style.display = "none"
                document.body.appendChild(canvas);
                const image = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
                const a = document.createElement("a");
                a.setAttribute("download", "weavr-lqs.png");
                a.setAttribute("href", image);
                a.click();
            });
        },
      
       <span class="ml-2" @click="takeScreenshot"><i class="fa fa-download cursor-pointer text-primary bg-black px-2 py-1 border rounded" aria-hidden="true" ></i>
                    </span>

html2canvas is not working fine. 
it's taking only first screenshot properly and remaining screenshots are coming blank.
please suggest any solution for this problems.
