### ISSUE TITLE
audit places where rejection callbacks should be passed along with the resolve callbacks

### ISSUE THREAD

**Issue by usmonster** [niklasvh/html2canvas#514]
There are currently many instances in the code where a "resolve" handler is passed in an invocation of a Promise's `.then` method without passing a second function to handle the rejection case. This can lead to situations that result in a silent failure.

I would recommend passing basic rejection handlers in these cases, which can simply log the rejection reason (and execution context) by default, and possibly also handle the rejection if possible or desirable, depending upon the case. (There are already uses of `.catch`, but rejection cases will never reach those functions if they don't throw an uncaught error.)

**Comment by niklasvh** [comment]
Should be more permissive in 1.0.0
