### ISSUE TITLE
Element partially rendered

### ISSUE THREAD

**Issue by bdely** [niklasvh/html2canvas#515]
For ver. 0.5.0-alpha1
When I take a screen shot of a element that is partial out of screen because of the amount of item in the parent, it is only taking a screen shot of what is visible when you are scrolled all the way to the left (horizontal scrolling div), but the canvas is the actual size if the element but the rest is just blank. this happens even if I scroll so that the element is fully visible on the screen when I take the screen shot.

What the element looks like
![visualize-test](https://cloud.githubusercontent.com/assets/2165209/5859383/d1a85418-a227-11e4-8fb8-56e16408a822.png)

what the screen shot outputs
![download](https://cloud.githubusercontent.com/assets/2165209/5859386/d4e07e3a-a227-11e4-923a-75cccebcc4ab.png)

It also does the same with ver. 0.4.1

**Comment by bdely** [comment]
Found out that a friend added code to change the css left property and didn't tell me, so it was reading that.

**Comment by usmonster** [comment]
You might want to look at https://github.com/niklasvh/html2canvas/pull/508#issuecomment-70539743 for a solution.

**Comment by bdely** [comment]
Thanks, the only problem with setting a class, is that the left property is being set on the element itself, and that would over write any style in the class.
