### ISSUE TITLE
Unable to use proxy for Java server

### ISSUE THREAD

**Issue by Malleswari103095** [niklasvh/html2canvas#516]
Hi. 

html2canvas is a great plugin to capture the webpages. It helped us a lot. However, I'm facing some problems with capturing images in the webpages which have rendered online. 

I read about proxies which makes cross domain images also render well. But, unluckily I could not get benefited from it as I was not using either of the servers you mentioned. (python, node.js, php, asp.net (c#), asp classic (vbscript), python)

Instead I'm using, Java Server. Could you please assist me how can I achieve cross domain images to be captured in the canvas by html2canvas. 

Any help from your end is greatly appreciated and needed. Thank you :)

**Comment by gupta515** [comment]
HI Malleswari,
I could solve this issue, instead of setting proxy I used "useCORS : true" option which was mentioned in the html2Canvas documentation - http://html2canvas.hertzen.com/documentation.html.
I think this may help you out.

**Comment by eyeofbri** [comment]
Why am I recieving this email?

On Monday, June 29, 2015, Samba Siva Gupta <notifications@github.com> wrote:

> HI Malleswari,
> I could solve this issue, instead of setting proxy I used "useCORS : true"
> option which was mentioned in the html2Canvas documentation -
> http://html2canvas.hertzen.com/documentation.html.
> I think this may help you out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niklasvh/html2canvas/issues/516#issuecomment-116596954>
> .
>


-- 
* Brian McLendon II *
mclendon.brian@gmail.com
brian.teenzombie.com
609.213.3356
