### ISSUE TITLE
Chrome stretches background images with 'auto' or single attributes

### ISSUE THREAD

**Issue by JulianKingman** [niklasvh/html2canvas#517]
You can see in this fiddle here: http://jsfiddle.net/fdx8uucj/

In chrome (maybe other webkit browsers, didn't check), html2canvas stretches the image if background size is declared with either shorthand:
background-size: 200%;
or with auto:
background-size: 200% auto;
There is no problem if it's explicit:
background size: 200% 200%;

I just upgraded from 0.4.1 to 0.5.0 and the problem appeared.

Thanks for a great script!

**Comment by niklasvh** [comment]
Thanks for the report and example, will get it fixed

**Comment by JulianKingman** [comment]
Thanks!
-- 
Julian Kingman

On January 26, 2015 at 3:39:26 PM, Niklas von Hertzen (notifications@github.com) wrote:

Thanks for the report and example, will get it fixed
