### ISSUE TITLE
Firefox - 'colorStopMatch is null'. Fiddle inside. 

### ISSUE THREAD

**Issue by samsonkhisty** [niklasvh/html2canvas#519]
Greetings again, 

With the latest version of the js file, I receive the below error in Firefox only.

    TypeError: colorStopMatch is null

Here is JsFiddle with the latest copy of js. http://jsfiddle.net/fuggfuggfugg/8gudy2am/5/. 

It was also working with 0.4 (http://jsfiddle.net/fuggfuggfugg/8gudy2am/3/) which had a weird gradient stacking issue that was fixed in 0.5.

**Comment by brcontainer** [comment]
Sound likes a problem with the `transparent` value.

Before `TypeError` the log shows:

> " transparent 60%" /((?:rgb|rgba)\(\d{1,3},\s\d{1,3},\s\d{1,3}(?:,\s[0-9\.]+)?\))\s*(\d{1,3})?(%|px)?/

Code used:
```
...
    this.colorStops = imageData.args.slice(hasDirection ? 1 : 0).map(function(colorStop) {
        var colorStopMatch = colorStop.match(this.stepRegExp);
        console.log(colorStop, this.stepRegExp);
        return {
            color: new Color(colorStopMatch[1]),
            stop: colorStopMatch[3] === "%" ? colorStopMatch[2] / 100 : null
        };
    }, this);
...
```

**Comment by samsonkhisty** [comment]
Thanks for looking into further. I noticed that error while debugging, sorry I should have mentioned. 

However v0.4 example (http://jsfiddle.net/fuggfuggfugg/8gudy2am/3/) works fine with the transparency. 

I tried looking into more and figure if I could compare the code and try fixing, but I was incapable to do so.

**Comment by usmonster** [comment]
Sounds like the issue I'm already working on fixing--see #469 and work-in-progress at 6af1874dc04c81d1aba5d6e8e6c8ef69681a2e49 (note: the dist files haven't been updated, but you can run `grunt buid` and see if the result works for you).

Feel free to close this and follow the other one if you think it's the same issue.

**Comment by samsonkhisty** [comment]
Thanks for your assistance.
