### ISSUE TITLE
html2canvas is not working 

### ISSUE THREAD

**Issue by cnelindiahwe** [niklasvh/html2canvas#521]
Please help me it's really urgent.

**Comment by niklasvh** [comment]
It is working https://travis-ci.org/niklasvh/html2canvas

**Comment by cnelindiahwe** [comment]
it's not working in ipad please hellp i am stuck

**Comment by cnelindiahwe** [comment]
please help i need your help

**Comment by programmin1** [comment]
@cnelindiahwe Unless you can detail specifically what is broken about your usage of html2canvas, it's unlikely Mr. Hertzen or any other developers on the project will be able to help. Can you give a specific jsfiddle of breaky behavior with this library?

**Comment by cnelindiahwe** [comment]
actually i am trying to take screenshot of http://testing.fantasyfootballfirst.co.uk/wp-content/uploads/2015/01/1421750633979021472.png this type image and bar chart but it's not working

**Comment by cnelindiahwe** [comment]
does it work for bar chart in ipad . Please help me i really want to use this script.
i request you to help meeeeeeeeeee
