### ISSUE TITLE
SVG rendering issues

### ISSUE THREAD

**Issue by nikolang** [niklasvh/html2canvas#523]
http://jsfiddle.net/nikolang/b22L8d6k/9/

You can see that the image is always rendered on the second try. But when its rendered its looks more like a black potatoe than a nice pie chart ;)

**Comment by DavidBruchmann** [comment]
mhm, potatoe is looking different but it could be a black pumpkin :D

**Comment by ndcreativity** [comment]
@nikolang hi, did you found any solution for this, becouse I have same proble? Thanks

**Comment by nikolang** [comment]
@ndcreativity I managed to find a workaround for SVG images. I saved the SVG on the Server and drawed it into the canvas.

img.src = "./ajax/images/xxx.svg";
img.onload = function() {
        ctx.drawImage(img, 0, 0);
 }

Problem is that the rest of the HTML around the SVG is not rendered.

**Comment by ndcreativity** [comment]
@niklasvh hmm, thanks... I trying to get whole page, and that export to pdf :)

**Comment by npmuller** [comment]
My comment in #602 shows that as of v1.0.0-alpha.9, <image>s that include their base64-encoded image data as the data in xlink:href attribute will show up on the html2canvas-generated canvas, while images that use a relative path or link will not.  Possible workaround for now until they get this fixed.
