### ISSUE TITLE
LinearGradientContainer doesn't work with transparency

### ISSUE THREAD

**Issue by chrisranderson** [niklasvh/html2canvas#526]
I think. :) It dies at this point:

![transparentgradient](https://cloud.githubusercontent.com/assets/5461398/6026298/de92ed1e-ab96-11e4-9fd6-1be6941d692d.png)

The page I was trying to use is http://en.wikipedia.org/wiki/Color.

update: This seems to stop it from crashing: 
       if (!colorStopMatch) {
            return {
                color: new Color('0,0,0,0'),
                stop: null
            }
        }

**Comment by usmonster** [comment]
This is because of #469--please feel free to subscribe to and follow the issue there until it's implemented (should be soon). This issue can be closed.

**Comment by niklasvh** [comment]
https://github.com/niklasvh/html2canvas/commit/46078acf71972af9a966e27b5558c06612d56335
