### ISSUE TITLE
orverflow of rotated img

### ISSUE THREAD

**Issue by taizan** [niklasvh/html2canvas#527]
I have a rotated image element , which wrapped by orverflow: hidden　div.
In brouser , the image will be rotated before cutting orverflowed part.
but html2canvas cut overflowed part before rotate obj.

**Comment by brcontainer** [comment]
jsfiddle example please?

**Comment by Meliorik** [comment]
I had the same error. Corrected as follows:
Line 1960:
var clip = (container.css ('overflow') === "hidden")? [container.borders.clip]: [];
Replace with
var clip = [];

I do not know what other problems it will cause, but my project works.
