### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by j4ys0n** [niklasvh/html2canvas#528]
Hello,

Could you please make this compatible with AMD API so that we can use this with Require?

Thanks!

**Comment by niklasvh** [comment]
Will get it added for 0.5.0 release

**Comment by j4ys0n** [comment]
Awesome. Thank you!



—
Instagram: @jayssface
Twitter: @jayssface

**Comment by davidbau** [comment]
Hello @niklasvh - we'd like to use the library in an AMD application - looks like the 5.0 alpha doesn't yet support AMD, but maybe we'd add it as a patch.  Any thoughts on the way you'd like to support it?

**Comment by xinan** [comment]
Hi @niklasvh ! 
I realise that you are switching to use `browserify`. I am just curious about how would you make it AMD compatible when you use `browserify`? Thanks!

**Comment by finetype** [comment]
What's the story on this? Require.js compatibility?

**Comment by niklasvh** [comment]
Should be fully supported now with the fixes in https://github.com/niklasvh/html2canvas/commit/4ebe9c5fcca8fbdb411f7d03c17b8212866fc1ab and https://github.com/niklasvh/html2canvas/commit/a4aa0c64447e3ad5298783da2a8511d537892bf2
