### ISSUE TITLE
SVG rendering with embedded/external css not working

### ISSUE THREAD

**Issue by arzyu** [niklasvh/html2canvas#530]
[jsfiddle](http://jsfiddle.net/arzyu/L9hqxww4/1/)

**Comment by usmonster** [comment]
See also #95.

**Comment by NPC** [comment]
Seeing the same—externally included fill rule is ignored, black is rendered instead. This also affects stroke external style. Writing them directly in SVG as attributes makes it work.

**Comment by n1try** [comment]
Is there another way to get this working besides writing all styles directly into the SVG?
