### ISSUE TITLE
proxy saves external image in a different folder instead of embedding them inside the result

### ISSUE THREAD

**Issue by silooz** [niklasvh/html2canvas#531]
I use the php proxy

function screenShot(oElement) {
    var html2obj = html2canvas(oElement,{logging: true, proxy:' html2canvasproxy.php'});
    var queue  = html2obj.parse();
    var canvas = html2obj.render(queue);
    var img = canvas.toDataURL();
    return img;
}

screenShot($('#newDiv'));

**Comment by brcontainer** [comment]
If you using https://github.com/brcontainer/html2canvas-php-proxy note that the only thing it does is display the url in the response, the images are saved in `images` folder, for change:

Replace this line https://github.com/brcontainer/html2canvas-php-proxy/blob/master/html2canvasproxy.php#L14 :

    define('PATH', 'images');//relative folder where the images are saved
