### ISSUE TITLE
Image capture on element with border-radius

### ISSUE THREAD

**Issue by mattdell** [niklasvh/html2canvas#532]
Hello, I've got html2canvas working on my site but the radio button styling isn't exactly on par. It does a sort of spirograph design instead.

![example](https://cloud.githubusercontent.com/assets/2536442/6148997/77abba96-b1fd-11e4-8453-f0bc9ad57644.png)

I am styling a span with the actual radio input elements hidden, so effectively I have a span with border-radius: 50% which means it's not exactly a radio-button issue but more of an issue with border-radius.

Here is the relevent CSS
border-radius: 50%;
background-clip: padding-box;
border: 2px solid #000;

Setting the border-radius to 0 or simply removing it will render the span as a square and html2canvas will render it just fine as a square. 50% will do the spirograph thing. Anywhere in between (say 40%) will still do the spirograph but not as extreme.

Is this a bug or am I doing something wrong?

**Comment by mattdell** [comment]
I've figured it out thanks to a previous issue raised: https://github.com/niklasvh/html2canvas/issues/506

It's caused by using too high of a border-radius; their JSFiddle helped me narrow down the issue: http://jsfiddle.net/gmz0wnwr/

And here is mine working: http://jsfiddle.net/gmz0wnwr/1/

**Comment by niklasvh** [comment]
Fixed in 1.0.0
