### ISSUE TITLE
Give progress feedback

### ISSUE THREAD

**Issue by Paratron** [niklasvh/html2canvas#535]
It would be nice if html2canvas could give feedback about the progress of the rendering process. Especially on slower/mobile devices, the rendering process can take a couple of seconds (especially with downloading resources) and it would be nice to display a progress to the user.

The promise pattern should already deliver a good API for that kind of feature with passing a third callback to the then method:  `.then(success, failure, progress)`

**Comment by usmonster** [comment]
A problem with the third callback is that it doesn't yet seem universally supported. I'm all for a way to indicate progress, though.

**Comment by DanialV** [comment]
Any update on this issue?

**Comment by dgwyer** [comment]
Is there a way to display progress yet? I'd like to include this too.
