### ISSUE TITLE
Content of iframes that should not be rendered is still requested

### ISSUE THREAD

**Issue by Paratron** [niklasvh/html2canvas#536]
I have an iframe element marked with data-html2canvas-ignore="true"

Upon page rendering, the iframe is still replicated by html2canvas and the frame document is requested again from the server. The frame is NOT rendered, but its contents are re-requested from the server.

I have created a fiddle which shows the described behaviour. A frame is embedded in the page which fires an alert box. When you render the page, the alert box is called again.

http://jsfiddle.net/g5doru24/

@niklasvh already stated that the iframe tag still has to be copied/scanned to get its dimensions, even if its not rendered. Thats true but I think its easy (without knowing the code) to avoid requesting the frame contents by clearing the `src` attribute when cloning a iframe with a do-not-render-flag.

**Comment by usmonster** [comment]
:+1:

**Comment by niklasvh** [comment]
Fixed in 1.0.0 http://jsfiddle.net/h3mzp5ye/
