### ISSUE TITLE
hi i am getting problem with html2canvas 

### ISSUE THREAD

**Issue by nikunj231991** [niklasvh/html2canvas#537]
i can't render full page with all image 
Problem image : 
https://cloud.githubusercontent.com/assets/6532636/6211397/811470e0-b596-11e4-8fcb-9bb417e01ed4.jpg

original image : https://cloud.githubusercontent.com/assets/6532636/6211404/a25e7f66-b596-11e4-8e4c-806af3451a29.png

**Comment by usmonster** [comment]
It looks like the page uses some gradients, so I suspect this might be solved when #469 is fixed (should be very soon). Please feel free to subscribe to that issue in the meantime.

**Comment by nikunj231991** [comment]
Thanks for your reply but i resolve problem by change background-position:bottom to background-position:100% 100%
