### ISSUE TITLE
Stack ordering with float elements

### ISSUE THREAD

**Issue by kirrukirru** [niklasvh/html2canvas#539]
Hi,

Thanks for the amazing work you did!
The image in the following link is not rendered in screenshot example.
As per my debug, the element containing the text is rendered on top of the image. The image has float:right.

http://www.camoni.co.il/index.php?idr=400&p=210948

Is it a limitation?

Regards

**Comment by kirrukirru** [comment]
Another site with similar issue: http://www.iab.net/

**Comment by niklasvh** [comment]
Fixed in 1.0.0
