### ISSUE TITLE
how does the proxy parameter work to load external images?

### ISSUE THREAD

**Issue by jmrodriguez** [niklasvh/html2canvas#540]
Hi I would appreciate some insights on how exactly the proxy parameter works to load external images.

Is it a url to a "page" I host somewhere?

If so, what should that page do/look like?

Thanks in advance

**Comment by EpicVoyage** [comment]
The proxy "page" should look similar to one of these: https://github.com/niklasvh/html2canvas/wiki/Proxies

**Comment by Cristy94** [comment]
So, does proxy work with 0.5 ?
