### ISSUE TITLE
Rendering multiple ChartJS canvas charts results in blank generated canvas

### ISSUE THREAD

**Issue by SamHH** [niklasvh/html2canvas#544]
Bug present in 0.5.0-alpha1 but not 0.4.1.

Rendering one works fine, two+ results in empty canvas (or in the case of surrounding markup, the ChartJS canvas element's space will be blank).

If you're wondering why I'm rendering ChartJS canvas charts into new canvases it's because I'm including some surrounding markup. This bug however is present irrespective of the surrounding markup.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by SamHH** [comment]
Unfortunately I have no idea, I'm about two jobs and a few dozen projects into the future and I've lost all mental context for this issue. :-( If nobody else has reported an issue and you can't reproduce I guess you can close this.

**Comment by niklasvh** [comment]
That's understandable. Sorry for not getting to it earlier. Will close it and if someone has similar issue they can open a new issue for it :)
