### ISSUE TITLE
Undocumented option "view"

### ISSUE THREAD

**Issue by stluit01** [niklasvh/html2canvas#546]
While debugging html2canvas, just to understand how it works, I found an option that is not listed in the documentation on "http://html2canvas.hertzen.com/documentation.html". Is there a reason for it? Cause this options seems to do exactly what I need, to render only the currently visible html content instead of the whole body.

**Comment by usmonster** [comment]
Documenting all the options and usage is on the list for the v0.5 milestone and can be followed at #468. Feel free to subscribe to that issue and close this one.
