### ISSUE TITLE
Render content from iframe

### ISSUE THREAD

**Issue by Cristy94** [niklasvh/html2canvas#549]
I know that the script can not render iframes, but I only need to render the content of an iframe. I have access to the iframe (I can add the html2canvas library inside it and also make the render call from inside it) but how would I use proxy in this case? The server that hosts the iframe is not the same with the one that hosts the proxy.

And, my final question, will it correctly render the iframe if the html2canvas call is done from inside the iframe?

**LE**: The problem right know, with calling the draw on the iframe contents body is that the URL of the resources is wrong. Instead of getting iframeUrl/res/image.jpg it tries to get the file from currentUrl/res/image.jpg, and fails to find it as the res folder is on the iframeUrl domain. Any fix for this?

**Comment by oliver-bauer** [comment]
Hi together, I'm facing the same issue here with my project. When taking an image inside an iFrame (with correct permission etc.), html2canvas is calling the wrong base URL. It uses the base URL of the parent window and not the one of the iFrame.

How to correct for that? Thanks!

**Comment by ValBerthe** [comment]
I have the exact same issue as @oliver-bauer. Would be awesome if you could figure out something for this !

html2canvas@0.5.0-beta4

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
