### ISSUE TITLE
Scroll position of child div is not reflected in the image.

### ISSUE THREAD

**Issue by ravi-star** [niklasvh/html2canvas#550]
Hi,

First of all thanks a lot for developing this wonderful library!

I tried to capture some area of my web page (which has multiple divs, some with a scrollbar) and the scroll positions (of those child divs) in image produced are not in sync with live page.

Please suggest if that is possible and how

Thanks in advance!

**Comment by crashnick16** [comment]
+1

**Comment by usmonster** [comment]
Duplicate of #511. Feel free to follow that one and close this one (also make sure you're using the most recent version from the master branch, there was a partial fix a few days ago).
