### ISSUE TITLE
Pseudo-elements

### ISSUE THREAD

**Issue by BramVanroy** [niklasvh/html2canvas#551]
I am trying to allow users to snap family trees that are build with CSS -- based on [this plugin](http://thecodeplayer.com/walkthrough/css3-family-tree). Unfortunately, something goes wrong when running html2canvas:

![download](https://cloud.githubusercontent.com/assets/2779410/6651357/f9dfcd0a-ca3e-11e4-8e32-c16d824d9110.png)

Whereas the expected result would look like this:
![knipsel](https://cloud.githubusercontent.com/assets/2779410/6651369/5f056c12-ca3f-11e4-96d7-55ec120e9665.PNG)

As the rest of the CSS is rather straight forward, it seems to me that there's some problems with `:after` and `:before` and there positioning. Is that possible, or am I looking in the wrong direction?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by kiran-pillai** [comment]
I am facing this same issue
