### ISSUE TITLE
callback not appended to proxy call 

### ISSUE THREAD

**Issue by xqin1** [niklasvh/html2canvas#555]
with v0.5-alpha2, the callback is not appended to the proxy call, sample code: https://gist.github.com/xqin1/cb67da4d3410b784fb3a , load the code in Chrome, and type 'createMapImage()' in console, examine the console and you can see the request is sent to proxy but the callback is not appended.

with v0.4, the callback is appended to the proxy call correctly.

**Comment by Cristy94** [comment]
I don't know if this is the problem, but in my case (after searching for about 1 hour) I found this solutions to get the proxy working (it successfully displayed a cross-origin image): https://github.com/niklasvh/html2canvas/pull/554

**Comment by xqin1** [comment]
@Cristy94, your branch does fix the problem thanks
