### ISSUE TITLE
Export as SVG

### ISSUE THREAD

**Issue by jmariett** [niklasvh/html2canvas#557]
I already use html2canvas in order to export an html div as png, but I would like to do the same to produce a svg file. The documentation is quiete poor on this library and I have hard time understanding how to do this! 
There is any way to do it ?
thanks,
Jeroem

**Comment by Cristy94** [comment]
Well, you can save the canvas as SVG yourself, I think that is beyond the point of this library. Search online for canvas to svg, or javascript img to svg libraries.
