### ISSUE TITLE
not support svg element Path and Line? Or Css "stroke-width" & "stroke"?

### ISSUE THREAD

**Issue by liudy1991** [niklasvh/html2canvas#558]
I found that when I use html2canvas to render the svg element,  the svg element "line" or "path" is always rendered wrongly. Maybe it doesn't support css style "stroke-width" and "stroke"?

How can I fix it?

**Comment by rahmatullah** [comment]
Hi,
I also have the same problem.
When get screenshot it does lnot support [polyline in leaflet].

**Comment by rahmatullah** [comment]
Solved!!!!!!!
It is done. make "L_PREFER_CANVAS=true and L_DIABLE_3D=true prior to the leaflet include.
