### ISSUE TITLE
Target element is partially rendered due to stylesheet

### ISSUE THREAD

**Issue by asmafarhat2006** [niklasvh/html2canvas#561]
Hi!

Firstly, great work done for making this .
My issue is : 
I have a webpage which contain several widgets,One of the widget im trying to capture is an HTML table which contains Highcharts (piecharts etc), what i have done is, i have converted the Highcharts in the table using CANVG library to the data uri images.
But when i am converting the resultant HTML using HTML2canvas it crops a little portion of the html from the table. So far i have figured out, that my stylesheet is causing it to crop , removing it from the code shows the complete table, but i want the css to be intact ofcourse 

Here is the jsFiddle link  http://jsfiddle.net/8ypxW/999/.
Im using the latest alpha release of html2canvas

it will show u the HTML i want to capture , cllick on the "SavePNG" button and then u can see the output image.

**Comment by niklasvh** [comment]
Fixed in 1.0.0
