### ISSUE TITLE
Font-Face doesn't appear to work on Windows. (Works on Mac)

### ISSUE THREAD

**Issue by brandonkboswell** [niklasvh/html2canvas#566]
Our site uses @font-face fonts. When using html2canvas everything works great on the Mac, but on windows all text comes out in a default serif font. Here is a fiddle that demonstrates this (http://jsfiddle.net/omne8o2L/1/). On the Mac both lines will be "Raleway Bold" (A San-serif font), on windows the top line (Real text) will be formatted correctly, but not the image.

Here are screenshots of the results of the Fiddle.

Mac (Correct)

![screenshot 2015-04-07 14 52 27](https://cloud.githubusercontent.com/assets/921925/7031004/9975ec00-dd36-11e4-9e89-58d125aadc7c.png)

Windows (Incorrect)
![windowshtml2canvas](https://cloud.githubusercontent.com/assets/921925/7031007/a1d03bb2-dd36-11e4-8640-e1e5aab1e642.png)

I've tested this in Firefox and Chrome on Windows and get the same result. Any ideas?

**Comment by brandonkboswell** [comment]
Upon further investigation and another JsFiddle (http://jsfiddle.net/omne8o2L/3/) turns out the bug we're experiencing is due to the letterRendering option being turned on.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by sangyoo91** [comment]
I'm having the same issue.
