### ISSUE TITLE
Incompatibility with prototype.js

### ISSUE THREAD

**Issue by codefactor** [niklasvh/html2canvas#568]
If you include prototype.js

https://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js

This overrides Array.prototype.filter

NodeParser.prototype.getChildren has an issue calling prototype's implementation of [].filter on a NodeList.

I suppose this could be considered a bug in prototype.js, but it might be a good idea to modify NodeParser.prototype.getChildren to use a different way to filter the array.

**Comment by codefactor** [comment]
Here is one way to fix it

    NodeParser.prototype.getChildren = function(parentContainer) {
    return flatten((function(fn){
        var arr = [];
        for (var i=0, len=this.length; i<len; i++) {
            var val = this[i];
            if (fn(val)) {
                arr.push(val);
            }
        }
        return arr;
    }).call(parentContainer.node.childNodes, renderableNode).map(function(node) {
        var container = [node.nodeType === Node.TEXT_NODE ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
        return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
    }, this));
    };

**Comment by codefactor** [comment]
The resulting behavior is that the callback is never called, an exception is thrown, and the iframe html2canvas creates is left in the document.

**Comment by codefactor** [comment]
I found another incompatibility with Array.prototype.map - I have created 2 bugs in prototype

https://github.com/sstephenson/prototype/issues/293
https://github.com/sstephenson/prototype/issues/292

**Comment by walacy** [comment]
This incompatibility occurs only on version 1.6.0.3. To resolve, you can put the function "each" on the prototype.js.

<code>
Object.extend(Array.prototype, {

// Extract from version 1.7
 each: function (iterator, context) {
    for (var i = 0, length = this.length >>> 0; i < length; i++) {
      if (i in this) iterator.call(context, this[i], i, this);
    }
  },
</code>

I'm using JSF richfaces 3.3.3... In my case, is impossible to solve by this way (can't update prototype).
Please, if possible, solve this incompatibility on next build =)

Thks all.

**Comment by airbr** [comment]
I appear to be running into the same incompatibility issue with Prototype in a more legacy application and using html2canvas getting `Uncaught (in promise) TypeError: this.each is not a function`
