### ISSUE TITLE
html2canvas.Parse() page scrolls to top 

### ISSUE THREAD

**Issue by imrannaqvi** [niklasvh/html2canvas#57]
Hi, i am using v0.30. When html2canvas.Parse() is called the page automatically scrolls to top, I have also spotted it in v0.32.

**Comment by derekm** [comment]
The fix in 0.5-alpha may be tested, but it isn't well-tested and it isn't fool-proof. I'm attaching two screenshoots, one from the latest stable release and another from the latest alpha release.

I'm using Highcharts, Gridstack, and canvg.

Latest stable release:

![dashboard_thumb_69_1440783278](https://cloud.githubusercontent.com/assets/379469/9552938/594351d4-4d81-11e5-9f2f-242d91043476.png)

Latest alpha release:

![dashboard_thumb_69_1440781895](https://cloud.githubusercontent.com/assets/379469/9552941/6387c8fa-4d81-11e5-84b5-4da46e6e0e00.png)
