### ISSUE TITLE
Yandex map

### ISSUE THREAD

**Issue by tselishev-semen** [niklasvh/html2canvas#570]
Hi, thanks for good lib. I try to capture screenshot yandex map. But nothing works:(
I found the solution to https://github.com/nickbewley/Google-Maps-Client-Screenshot. But, when i capture yandex map, i get a screenshot, with a capital red letter 'Я'
How i can do it?

**Comment by tselishev-semen** [comment]
This problem only for yandex maps version 2.x. For yandex  1.x it;s work

**Comment by UksusoFF** [comment]
Have you solve issue?

**Comment by tselishev-semen** [comment]
@UksusoFF  You can see solution in my repository  https://github.com/tselishev-semen/yandex-screenshot

**Comment by UksusoFF** [comment]
Thanks, but I'll already implement with Static API and some php code https://tech.yandex.ru/maps/staticapi/
