### ISSUE TITLE
Error loading Images with html2canvas-php-proxy

### ISSUE THREAD

**Issue by joyco** [niklasvh/html2canvas#571]
I am facing issue were images are not getting rendered with php proxy. I was trying to setup on my locals i took code from this link https://github.com/brcontainer/html2canvas-php-proxy/blob/master/examples/google-maps.html

I have attached image with log. Please let me know what I have missed.

![error](https://cloud.githubusercontent.com/assets/11994122/7202175/82c4e11a-e52d-11e4-8e31-b63631dc2301.PNG)

**Comment by brcontainer** [comment]
@joyco show me piece code usage.

**Comment by brcontainer** [comment]
@joyco show me a relevant piece of code.

**Comment by joyco** [comment]
I have used code from this link.
https://github.com/brcontainer/html2canvas-php-proxy/blob/master/examples/google-maps.html

I am trying to setup on my local server.

**Comment by brcontainer** [comment]
@joyco I think you put the *html2canvasproxy.php* in the wrong folder.

**Comment by joyco** [comment]
I have kept html2canvasproxy.pnp in same folder where test page is present.

Html code:
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Google Maps and html2canvas</title>
    <style type="text/css">
    #map_canvas{
        height: 400px;
        width: 600px;
        border: 1px #c0c0c0 solid;
    }
    </style>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script type="text/javascript">
    var map = null;
     function initialize() {
        var parametreCarteVillage = {
            zoom                        : 9,
            center                      : new google.maps.LatLng(38.959409, -87.289124),
            disableDoubleClickZoom      : false,
            draggable                   : true,
            scrollwheel                 : true,
            panControl                  : false,
            disableDefaultUI            : true,
            mapTypeControl              : true,
            keyboardShortcuts           : true,
            mapTypeId                   : google.maps.MapTypeId.ROADMAP
        }
        map = new google.maps.Map(document.getElementById('map_canvas'), parametreCarteVillage);


      var marker = new google.maps.Marker({
          position:new google.maps.LatLng(38.959409,-87.289124),
          map: map,
          title: 'Title!'
      });
    }

    window.onload = function () {
        initialize();

        function convert(target) {
            html2canvas(target, {
                "proxy": "html2canvasproxy.php",
                "logging": true, //Enable log (use Web Console for get Errors and Warnings)
                "onrendered": function(canvas) {
                    var img = new Image();
                        img.onload = function () {
                            img.onload = null;
                            document.getElementById("output").appendChild(img);
                        };
                        img.src = canvas.toDataURL("image/png");
                }
            });
        }

        document.getElementById("save1").onclick = function () {
            convert(document.getElementById("map_canvas"));
        };

        document.getElementById("save2").onclick = function () {
            convert(document.getElementById("container"));
        };
    };
    </script>
</head>
    <body>
        <h1>Google Maps with html2canvas</h1>
        <p>Tested on Chrome and Firefox</p>

        <div id="container">
            <h1>Maps example:</h1>
            <div id="map_canvas"></div>
            <div>
                <button id="save1">Save #map_canvas</button>
                <button id="save2">Save #container</button>
            </div>
        </div>

        <div id="output">
            <h1>Output results:</h1>
        </div>
    </body>
</html>

**Comment by brcontainer** [comment]
@joyco Go to network tab in console (https://github.com/brcontainer/html2canvas-php-proxy#using-web-console) and reload your page, open any url that appears on the "tab network" in browser (double click and it will open), eg. acess this url in your browser `http://[DOMAIN]/[PATH]/html2canvasproxy.php?url=http%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fcenter%3D40.714728%2C-73.998672%26zoom%3D12%26size%3D800x600%26maptype%3Droadmap%26sensor%3Dfalse%261&callback=html2canvas_0` 

Replace `[DOMAIN]` by your domain (eg. 127.0.0.1) and replace `[PATH]` by your project folder (eg. project-1/test), something like:

http://localhost/project-1/test/html2canvasproxy.php?url=http%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fcenter%3D40.714728%2C-73.998672%26zoom%3D12%26size%3D800x600%26maptype%3Droadmap%26sensor%3Dfalse%261&callback=html2canvas_0
