### ISSUE TITLE
0.5.0-alpha2 will stop render / no callback on certain pages (Wikipedia)

### ISSUE THREAD

**Issue by RyanBrainerd** [niklasvh/html2canvas#574]
I was testing on Wikipedia and found that I couldn't get any article pages to render.
Other web pages I tested rendered perfectly (google.com, etc.)

When looking at the html2canvas log in the web console it would simply stop during the
image phase. Finally, it seemed the promise would neither be fulfilled nor rejected, so I 
had no further insight as to the cause because there was no error message to catch on the
calling end.

A specific page to try: http://en.wikipedia.org/wiki/Ohio
However, in my testing, I couldn't get any Wikipedia article to render, no matter which one I tried.
Hopefully, this gives insight as to the general error so it can be prevented on other sites.

**Comment by usmonster** [comment]
This sounds like an instance of  #514. Can you check if that seems the case and, if so, feel free to subscribe to that issue and close this one?
