### ISSUE TITLE
Blurry image fix

### ISSUE THREAD

**Issue by graham73may** [niklasvh/html2canvas#576]
Recently had an issue with images exporting and looking incredibly blurry. 

Looking at the html2canvas logs I saw the x position and crop position were returning as 174.5. This half a pixel was causing the images to render with an excessive amount of blur. 

To force this to stop (as I couldn't think of a reason this would be the desired outcome) I have added **Math.floor()** to the **top, bottom, right, left** positions.  (I did not have any issues with width and height.). 

``` php
    function getBounds (node) {
        if (node.getBoundingClientRect) {
            var clientRect = node.getBoundingClientRect();
            var width = node.offsetWidth == null ? clientRect.width : node.offsetWidth;
            return {
                top   : Math.floor(clientRect.top),
                bottom: Math.floor(clientRect.bottom || (clientRect.top + clientRect.height)),
                right : Math.floor(clientRect.left + width),
                left  : Math.floor(clientRect.left),
                width : width,
                height: node.offsetHeight == null ? clientRect.height : node.offsetHeight
            };
        }
        return {};
    }
```

**Comment by usmonster** [comment]
On what browser(s) were you experiencing the blur? It may be related to canvas antialiasing (#171, #206, #158, et al.).

Rounding here is more of a workaround than a fix as it may cause other issues, since bounds should support subpixel values. Some better workarounds might be found here: http://stackoverflow.com/q/195262 .

**Comment by graham73may** [comment]
The blur caused by the decimal points made the images unusable, for us it was a case of floor the values or disable any kind of export functionality. 

Is there somewhere more suitable to implement a fix?

**Comment by simogeo** [comment]
Same problem here with Firefox 38.0. Images are just perfects with Chrome 18.0.102

**Comment by rusllonrails** [comment]
@graham73may many thanks man. :beers: 
Your fix works as a briliant :+1: 
I spent about 2 days in order to fix this in Firefox.
I'm happy that found your post. :tada:

**Comment by zzolo** [comment]
This worked for my issue (which was not a retina related issue).

It would be nice to be able to have this as an option, or if it can be pinned down to specific browsers some specific checks.

**Comment by seemasingh123** [comment]
<script type="text/javascript">	
		$(function(){	
			
			//here is the hero, after the capture button is clicked
			//he will take the screen shot of the div and save it as image.
			$('#PDFTABLE11').mouseover(function(){
				//get the div content
				
				div_content = document.querySelector("#container2")
				
				//make it as html5 canvas
				html2canvas(div_content).then(function(canvas) {
					//change the canvas to jpeg image
					data = canvas.toDataURL('image/png?');
					
					//then call a super hero php to save the image
					save_img(data);
				});
			});			
		});
		
		
		//to save the canvas image
		function save_img(data){
			//ajax method.
			$.post('save_jpg.php', {data: data}, function(res){
				//if the file saved properly, trigger a popup to the user.
				if(res != ''){
					
					if(yes){
						location.href =phe.php;
					}
				}
				else{
					alert('something wrong');
				}
			});
		}
    </script>
![image](https://cloud.githubusercontent.com/assets/26019097/23328868/dec8c206-fb51-11e6-93a5-ae21fc0954d6.png)

**Comment by seemasingh123** [comment]
please help me, what should do?
here is the another code of file save_jpg.php.
<?php 

//just a random name for the image file
$random = rand(100,1000);

//$_POST[data][1] has the base64 encrypted binary codes. 
//convert the binary to image using file_put_contents
$savefile = @file_put_contents("image.png", base64_decode(explode(",", $_POST['data'])[1]));

//if the file saved properly, print the file name
if($savefile){
	echo $random;
}
?>

**Comment by graham73may** [comment]
@seemasingh123 how is this related to my original issue? Not sure this is the right place for this.

**Comment by seemasingh123** [comment]
what is your original issue sir?? is it not related to blurry image?

**Comment by graham73may** [comment]
I've no idea what it's related to because all you've put is a screenshot, some code and said "please help".

**Comment by hoangtuan438** [comment]
@graham73may Thank you so much. My issue was solved
👍

**Comment by FlorianLeitgeb** [comment]
I am also experiencing blurry images with IE, but in Chrome it is working perfectly. How do I use this with my following code?
`        html2canvas(document.getElementById("myHTMLNode"), {
            onrendered: function (canvas) {
                // var width = Math.floor(canvas.width * 0.264583);
                // var height = Math.floor(canvas.height * 0.264583);

                var imgData = canvas.toDataURL(
                    'image/png');
                var doc = new jsPDF("p", "mm", "a4");
                doc.deletePage(1);
                //doc.addPage(width, height);
                doc.addPage(250, 300);
                doc.addImage(imgData, 'PNG', 10, 10);
                doc.save('WebSiteScreen.pdf');
            }
        });
`

**Comment by graham73may** [comment]
@FlorianLeitgeb The code block in my original post is a modification to html2canvas. If you want to try my fix you need to modify html2canvas's code, not your own.

**Comment by FlorianLeitgeb** [comment]
Big thank you. It is working like a charm!

**Comment by CKGrafico** [comment]
Okey this simply works. Where is the PR? html2canvas should fix that.

**Comment by graham73may** [comment]
@CKGrafico This was not PR'd as one of the html2canvas contributors sees this as a workaround and not a proper solution. - https://github.com/niklasvh/html2canvas/issues/576#issuecomment-97814373

**Comment by CKGrafico** [comment]
And after two years they don't have found anything better 👏

**Comment by Khemendra** [comment]
RESOLVED :)
Please use below code:

  onrendered: function (canvas) {
                    setpixelated(canvas.getContext('2d'));    // For More Clear Images in all browsers
.......


function setpixelated(context) {
            context['imageSmoothingEnabled'] = false;       /* standard */
            context['mozImageSmoothingEnabled'] = false;    /* Firefox */
            context['oImageSmoothingEnabled'] = false;      /* Opera */
            context['webkitImageSmoothingEnabled'] = false; /* Safari */
            context['msImageSmoothingEnabled'] = false;     /* IE */
        }

**Comment by CKGrafico** [comment]
@Khemendra can you add this to the PR? https://github.com/niklasvh/html2canvas/pull/1153

**Comment by NoLdman** [comment]
Why was @graham73may problem discarded? - The floating point issue is valid. It occurs in Chrome (but not Firefox) and has nothing to do with image-smoothing.

To elaborate: It occurs when the bounding rectangle not only has floating-points in height/width, but also has floating-points in `x` and `y`. (BTW: I'm not sure if that is a bug of Chrome itself...)

(For the time being i worked around by position my html-element fixed, while the canvas is generated.)

**Comment by niklasvh** [comment]
@NoLdman are you experiencing the issue with 1.0.0 as well?

**Comment by NoLdman** [comment]
@niklasvh are you referring to 5dbb197a820ad6ad4083c765ff7a6194f90540a1? - Since there is no official release yet, I built that commit with webpack myself. Unfortunately, I'm getting a bunch of errors with that built, e.g. `Unable to load image Failed to fetch image  with status code 404`.  
I think that has something to do with the fact that I'm using html2canvas within the shadow-dom (a Polymer app), but this needs further investigation and most likely it's own issue ticket.

**Comment by niklasvh** [comment]
Releases are available on npm and https://github.com/niklasvh/html2canvas/releases now

**Comment by bdegley4789** [comment]
window.devicePixelRatio = 2;

I put this before I did html2canvas and it worked for me

**Comment by MianZaid** [comment]
Here is the complete js file after replacing @graham73may function.
[html2canvas](https://bitbucket.org/snippets/zaidbinkhalid/Me4nAb)

**Comment by benzara-tahar** [comment]
I used this and it fixed the issue 
`html2canvas(domElement, { scale: 2 });`

**Comment by AnatuGreen** [comment]
> I used this and it fixed the issue `html2canvas(domElement, { scale: 2 });`

I did this too but still got a blurry result. Even scaling up to 10 (which gives a heavy file) still got a blurry image.

**Comment by AnatuGreen** [comment]
> Here is the complete js file after replacing @graham73may function. [html2canvas](https://bitbucket.org/snippets/zaidbinkhalid/Me4nAb)

I am using this in React. Which of the files should I edit?
 Thank you

**Comment by mianzaid** [comment]
> > Here is the complete js file after replacing @graham73may function. [html2canvas](https://bitbucket.org/snippets/zaidbinkhalid/Me4nAb)
> 
> I am using this in React. Which of the files should I edit? Thank you

JS file click on html2canvas link and edit the JS as per your need. There is no one answer, you will find many ways try all or write your on logic to fix the issue.
