### ISSUE TITLE
window.html2canvas

### ISSUE THREAD

**Issue by mattdell** [niklasvh/html2canvas#577]
I was prototyping with 5.0-alpha1 a few months ago and we got the all clear to put it into production so today I've added html2canvas back into our node packages list and now we have 5.0-alpha2. Using my exact same code as previously, I am getting loads of errors about window.html2canvas being undefined.

The easiest way I found to trigger this is by trying to turn on logging.
```javascript
var Html2Canvas = require('html2canvas');

var ScreenshotUtils = {

	takeScreenshot: function() {

		Html2Canvas(document.body, {
			onrendered: function(canvas) {
				// Do something
			},
			logging: true
		});
	},
};

module.exports = ScreenshotUtils;
```

When I execute ScreenshotUtils.takeScreenshot() I get the following error:
```javascript
Uncaught TypeError: Cannot set property 'logging' of undefined
```

Which gets thrown on this line of the html2canvas source code:
```javascript
function html2canvas(nodeList, options) {
    var index = html2canvasCloneIndex++;
    options = options || {};
    if (options.logging) {
        window.html2canvas.logging = true; // <--- Error here!
        window.html2canvas.start = Date.now();
    }
    ...
```

Is it just me? Does html2canvas really need to exist on window?

Any feedback would be greatly appreciated!

**Comment by usmonster** [comment]
Related: #563?

**Comment by mattdell** [comment]
Yeah, that does look related.

Can you look into this @niklasvh?

**Comment by joelwilliamsmith** [comment]
Not just you @mattdell, I'm seeing this issue as well. Would be much better if `html2canvas` was not on `window`.

**Comment by sgratzl** [comment]
I 'm using html2canvas in a require-js environment. While the automatic detection works, it still assumes that it stored as a window variable. 

If you disable logging it still fails, due to this line:
``` 
if (window.html2canvas.logging && window.console && window.console.log) {
```

**Comment by mattdell** [comment]
I ended up doing

````
var html2canvas = require('html2canvas');
window.html2canvas = html2canvas;
````
and called it a day.

**Comment by dictions** [comment]
This is quite annoying.

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/commit/4ebe9c5fcca8fbdb411f7d03c17b8212866fc1ab
