### ISSUE TITLE
adding elements to cloned canvas?

### ISSUE THREAD

**Issue by brainmonger** [niklasvh/html2canvas#578]
I'm trying to add elements to the canvas before generating the image and pdf.

I must be missing something obvious here.. because I can remove elements with no problem. Why am I not able to see added elements in the generated image??

Example:
```javascript    
    html2canvas($(targetElement), {
        onclone: function(document) {
            $(document).find(elementsToIgnore).remove(); //works
            $('<p>TEST</p>').insertAfter($(document)); //doesn't work!
        }
    });
```

**Comment by niklasvh** [comment]
`document` is the page `document`, not the the `targetElement`

**Comment by brainmonger** [comment]
Got it. This works, thanks!

```javascript
var targetElem = $(document).find('#pageContent'); //the element to append to
$('<p>TEST</p>').insertAfter(targetElem);
```
