### ISSUE TITLE
convert pdf to img not work

### ISSUE THREAD

**Issue by fabi0w** [niklasvh/html2canvas#579]
[div class="form-group"]
                      [div id="capture"]
                        [object class="form-controlPDF" data="my.pdf" type="application/pdf"]
                        alt : <a href="my.pdf">test.pdf</a>
                        [/object]
                      [/div]
                    [/div]

anyone have a solution? tks!

**Comment by usmonster** [comment]
From http://html2canvas.hertzen.com/documentation.html#limitations :

> The script doesn't render plugin content...

The PDF is rendered by the PDF plugin used by the browser and is thus not accessible to or parsable by html2canvas. You may want to check out https://github.com/mozilla/pdf.js .
