### ISSUE TITLE
background-position issue

### ISSUE THREAD

**Issue by kuna** [niklasvh/html2canvas#581]
CSS3 style background-position, such as background-position: right 10px top 10px;
is not working.

**Comment by kuna** [comment]
I think I fixed the problem, also works correctly on IE/Chrome/FF.
https://github.com/kuna/html2canvas/commit/2e943739b827ea923faf13ea7de7d2b189004e95
NodeContainer.prototype.parseBackgroundPosition was fixed.

**Comment by niklasvh** [comment]
Fixed in 1.0.0
