### ISSUE TITLE
Third party API function caching?

### ISSUE THREAD

**Issue by Bristoled** [niklasvh/html2canvas#586]
With latest release 0.5.0 have strange issue - will try to explain step-by-step:
1) Have button, when user clicks - it fires third party social portal API call (app request popup)
2) When user clicks on second button (it makes canvas and store image to server) and when gets callback from server it fires third party API call (but this time share request popup)... and here starts the strangest thing - when user clicks on this second button somehow it fires that first action again and a bit later (when finishes to make canvas and saves to server) it calls also that second action (share request popup). 

I was trying different ways and checked my code million times. When changing to html2canvas 0.4.1 this issue disappears (but 0.4.1 have other issues for example problem with multiple images and scaling, so can not use 0.4.1). What Im thinking that maybe there is some caching or callback function have same name...

**Comment by usmonster** [comment]
My guess is it's because of the fact that html2canvas 0.5 clones the document into an iframe, and perhaps some JS is being re-triggered after the clone.

What navigator are you using? Also, can you provide a jsbin/jsfiddle with a simplified example of the problem?

**Comment by Bristoled** [comment]
Your guess makes sense, but how we can get rid (or delete) that triggered function?
Im using Chrome, but also on other browsers are same result.

I made sample... its not showing social portal popups, but You can see there, that social portal api call is fired twice:
https://jsfiddle.net/sqvmvnqj/3/

Tip:
1. Click button1. You will see in console error message about security. Because on button1 is api call to social portal function (for opening invite popup).
2.Click button2 and You will see that error message appears again. BUT as you see in javascript code - in button2 there is no api calls, only html2canvas creator...

**Comment by Bristoled** [comment]
p.s. offtopic - we can also see another error - html2canvas not rendering accurately that yellow field...

**Comment by hyojin** [comment]
Hi, @Bristoled 
Have you solved this problem?
try [this](https://github.com/hyojin/html2canvas/tree/remove-js-and-iframe)  with javascriptEnabled options
```
javascriptEnabled = false
```
※Note: It will remove all iframe tags in your document. if you want to control this problem perfectly you'd better use a server-side proxy

And, I think the rendering problem is similar to #599
