### ISSUE TITLE
Image is clipped when html2canvas is called when scroll position is not on top

### ISSUE THREAD

**Issue by nishchhalshrestha** [niklasvh/html2canvas#588]
If html2canvas is called when window scroll top is 0px, image is not clipped and everything is fine. If html2canvas is called when window scroll top is not 0px (i.e. is scrolled down), image is clipped and everything breaks.

**Comment by usmonster** [comment]
Which browser(s)? Also possibly related: #511, #167, et al., though there have been relatively-recent partial fixes to at least one of those.

**Comment by nishchhalshrestha** [comment]
Its happening in all browser. Here is the link to the page http://techplusart.com/staging/estebartin.com/design-a-shirt?fabricId=25 we are working on.
Step 1: Click on Collar under Customize your shirt
Step 2: Scroll down a little and choose Classic
you will realize that shirt buttons are misaligned and the shirt image goes little bit down.
If you scroll up and choose a different collar, the canvas gets rendered correctly.
Css translations have been used for positioning shirt buttons and different parts of shirt are overlayed on one another in a div. The div itself has opacity 0. The div is then exported to canvas and image is extracted from canvas and displayed.

**Comment by usmonster** [comment]
Yep, this does look like just like #167. A workaround could be to save the scroll position and set it to 0 just before the invocation of html2canvas, and then restore in the .`then` callback.

**Comment by nishchhalshrestha** [comment]
Okay. Will do as in issue #167
