### ISSUE TITLE
Rotated td is showing only first 3 letters

### ISSUE THREAD

**Issue by aju31a** [niklasvh/html2canvas#589]
Hi Everyone,

I am really stuck with this issue for more than a week now so please help me asap.
I tried using htmltocanvas to make png of selected html in my web page, though its giving perfect output but i am facing few issues which are as follows:

1) Rotated td's in which text is coming through knockout is showing only first 3 letters in the converted image via html2canvas.
2) dotted borders are coming as solid borders.

Please try to answer asap as we are really facing troubles regarding this :(

Regards,
AJ

**Comment by aju31a** [comment]
![image](https://cloud.githubusercontent.com/assets/7719945/7676709/daa9b722-fd63-11e4-8f24-fdf32dad41a1.png)
![orignal](https://cloud.githubusercontent.com/assets/7719945/7676713/e28010ae-fd63-11e4-85b9-b2b97fe0318f.png)

**Comment by aju31a** [comment]
Please see both the issues in above screenshots.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
