### ISSUE TITLE
Offscreen parts on scrollable page are black

### ISSUE THREAD

**Issue by nosbabananos** [niklasvh/html2canvas#590]
Hi everyone,

I'm developing angular.js app which is using chart.js for charts and I need to export charts to image. 

I use html2canvas on a div which contains charts and it works fine for me when all of the charts are visible within a window. But, when charts cannot fit on a window, offscreen parts of div are black after in an image file. I googled and googled and I can find a solution. Any sugestion?

**Comment by dhustlerz** [comment]
Hi ,
I have the similar issue.

**Comment by ufologist** [comment]
html2canvas snapshot invisible DOM in a scrollable div
[html2canvas-snapshot-invisible.html](http://rawgit.com/ufologist/6864d941263c6cdf52294e1e70060704/raw/cae265a3089e91ea234b8d3bae66b4d415b583cd/html2canvas-snapshot-invisible.html)

blog: [fix html2canvas snapshot invisible DOM](https://www.douban.com/note/561316552/) Chinese

**Comment by Chima1707** [comment]
@ufologist, dont you have an English version of your block

**Comment by shohoku11wrj** [comment]
This thread has two solutions: 1. fix source code; 2. workaround without touching source. https://github.com/niklasvh/html2canvas/issues/461

**Comment by kkxlkkxllb** [comment]
```
      $el = $htmlEl.clone().css
        position: 'fixed'
        top: 0
        left: 0
        padding: 0
        height: 'auto'
      $el.appendTo $('body')
      ow = $htmlEl[0].clientWidth
      w = $el[0].clientWidth
      if w > ow
        w = ow
        $el.css
          width: w
      h = $el[0].clientHeight
      html2canvas $el
```
clone your element to body, set some css to calculate width and height

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
