### ISSUE TITLE
NS_ERROR_NOT_AVAILABLE in Firefox 38.0.1

### ISSUE THREAD

**Issue by hoxu** [niklasvh/html2canvas#591]
html2canvas does not seem to work in Firefox 38.0.1. To reproduce, it's enough to simply run:

```
html2canvas(document.body);
```

Chrome seems to still work, so the problem shouldn't be in my setup.

**Comment by usmonster** [comment]
Probably #95. Is this on any particular page?

**Comment by hoxu** [comment]
It's indeed on a page that contains SVG, custom fonts, etc.

**Comment by cobexer** [comment]
NS_ERROR_NOT_AVAILABLE: this is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=700533 (AFAICT) there is a testpage that highlights the issue (linked from the bug) http://phrogz.net/SVG/svg_to_png.xhtml

A workaround / fix would be greatly appreciated. Or maybe someone could poke somebody @mozilla to get this fixed :)

@hoxu : Try adding width and height attributes to the svg images if you can - that should make them work in Firefox too.

**Comment by cobexer** [comment]
Also moving the drawImage call from https://github.com/niklasvh/html2canvas/blob/f3b6df267e24aa9e38730ac304c352a5c743be53/src/renderers/canvas.js#L51 into the try below it would actually improve the bahavior in that the screenshot would continue without the broken image.
