### ISSUE TITLE
The text is obscured

### ISSUE THREAD

**Issue by dieuhd** [niklasvh/html2canvas#595]
I used html5canvas to Screenshot a graph that i used gantt, but the text is obsured.
![screen shot 2015-05-29 at 2 44 50 pm](https://cloud.githubusercontent.com/assets/3165692/7877164/69597010-0611-11e5-801f-85dd53d3fa89.png)

How to solve this problem ? Please help me.

**Comment by davidoxley** [comment]
Try set the line-height for the text div or class

**Comment by dieuhd** [comment]
@davidoxley : thanks, but not work. I modified overflow in my css, now it work.

**Comment by brcontainer** [comment]
Please, show a workable example of problem is jsfiddle. Thanks
