### ISSUE TITLE
After conversion of div into canvas the images inside the div get shrink

### ISSUE THREAD

**Issue by jadhavanant85** [niklasvh/html2canvas#596]
I have the div inside the div there is a table and inside the table each td contain the images.
after successful conversion of canvas all the images gives blank space at the bottom.
So what I have to do it?
Please need help....

**Comment by davidoxley** [comment]
Have you tried setting td {padding-bottom:0;} and td {margin-bottom:0; }?

**Comment by jadhavanant85** [comment]
Yes I have  tried for this.
Even if I have taken the images 1 after another still its doing the same thing
