### ISSUE TITLE
DOM elemetn box Shadow in screenshot

### ISSUE THREAD

**Issue by bernatfortet** [niklasvh/html2canvas#597]
The dom object that I'm taking a screenshot of has a box shadow and it's not captured in the screenshot.
Is there any workaround for it?

Thanks!

**Comment by jstnjstn** [comment]
I also would like box-shadow to be supported particularly box-shadow:inset
html2canvas is a great tool. Thanks for your/your team's work on this code.
Best wishes.

**Comment by brcontainer** [comment]
Duplicate from:

- https://github.com/niklasvh/html2canvas/issues/114
- https://github.com/niklasvh/html2canvas/issues/221
- https://github.com/niklasvh/html2canvas/issues/246
- https://github.com/niklasvh/html2canvas/issues/430

**Comment by usmonster** [comment]
(Note: #430 is actually unrelated and talks about the [shadow DOM](https://developer.mozilla.org/docs/Web/Web_Components/Shadow_DOM), which is unrelated to CSS *shadow properties.)

**Comment by diegocerdan** [comment]
Would be cool this to be solved.

**Comment by niklasvh** [comment]
Closing as duplicate
