### ISSUE TITLE
Icon font is not displaying in Firefox

### ISSUE THREAD

**Issue by djonatanb** [niklasvh/html2canvas#598]
I have created a custom icon font to be able to handle the color of the icon. For Chrome and Safari it works ok, a bit blurry but ok. When I try to use it on Firefox it renders a square. What should I try ?

**Comment by brcontainer** [comment]
**Duplicate from:**
- https://github.com/niklasvh/html2canvas/issues/364
- https://github.com/niklasvh/html2canvas/issues/490
