### ISSUE TITLE
HTML circle is rendering funny in Chrome/Safari

### ISSUE THREAD

**Issue by djonatanb** [niklasvh/html2canvas#599]
I have added some circles to the div that I want to send to the canvas with this CSS:
`height: 20px;
  width: 20px;
  border-radius: 20px;
  position: absolute;
  top: -8px;`

http://www.awesomescreenshot.com/image/297705/8c3f811182dc5a909c9c1cbd270dabd2
looks like this.

Works well on Firefox though.

**Comment by hyojin** [comment]
Here is my quick fix
try [this](https://github.com/hyojin/html2canvas/tree/fix-%23599)

**Comment by brcontainer** [comment]
Related: https://github.com/niklasvh/html2canvas/issues/624
