### ISSUE TITLE
How to render full of hidden part in 'overflow:auto' div

### ISSUE THREAD

**Issue by ghost** [niklasvh/html2canvas#60]
I have a div which contains all the elements that have to be converted into an image. And that div is set to 'overflow:auto'. I want to know how I can export all the elements(even hidden in the scrolling) to an image. I appreciate and welcome all your comments and  answers...... Thanks in advance...

**Comment by ejlocop** [comment]
what version did you guys used?.. i can find onparsed and onpreloaded method in my version..
im using html2canvas-0.5.0-alpha1

**Comment by usmonster** [comment]
@ejlocop This issue was filed years ago for a previous version and may not be relevant for your use case (#511).

**Comment by Alebqto** [comment]
They solved the problem? paraa solution I 'm looking for something with my Gantt chart , I need you out completely ...
![overflow](https://cloud.githubusercontent.com/assets/16739405/12375564/40c8d3ee-bc9a-11e5-8a02-1edc9b404bc6.png)

**Comment by uriklar** [comment]
Any news on this issue? I've tried many variations of overflow: visible and height: auto and no success...

**Comment by pkpatels** [comment]
it's not working.

http://jsfiddle.net/fMeRC/368/

**Comment by uriklar** [comment]
@pkpatels Why not working? I ran your fiddle and the sentences where rendered without cutting off...

**Comment by pkpatels** [comment]
@uriklar It's working for horizontal scroll not for vertical. Checkout my div. There are three different elements there.

**Comment by pkpatels** [comment]
@uriklar the solution you suggest is also not working when i scroll down the div and click on totally visible.
<img width="513" alt="screen shot 2016-03-16 at 1 41 09 pm" src="https://cloud.githubusercontent.com/assets/7530957/13805700/cb18e064-eb7c-11e5-8250-1032928571ca.png">

**Comment by uriklar** [comment]
What about setting the height of #text div to auto before render and resetting it after? That will work.

**Comment by ddykhoff** [comment]
I was still having issues with overflow in the most recent release (0.5.0-beta4). I took @usmonster's workaround and adapted it to the recent changes to h2c and Promises (as described in @usmonster's note):

> Note: The aforementioned workaround would not work with the newest version that is currently in master. I haven't tested, but it looks like you would need to make use of the oncloned option instead, and the overflow parent reset would now be called in your callback to .then(). (It should also be possible to exclusively make the parent's overflow visible inside the cloned document and not worry about resetting anything at all.)

So without altering the actual DOM of your webpage, you can alter the cloned document used for rendering by h2c utilizing the `onclone` callback. It's pretty simple actually, here's my h2c call:

```
var renderingPromise = html2canvas($(item), {
    width: item.clientWidth,
    height: item.clientHeight,
    onclone: function(clone) {
    	    $(clone).find('.grid-stack-item-content')
    		    .css('overflow-x', 'auto')
		    .css('overflow-y', 'auto');
	    return true;
    }
}).then(
    function(c) {/* success */},
    function() {/* fail */}
);
```

**Comment by jordan314** [comment]
The only thing that worked for me was putting the canvas in an iframe, calling html2canvas inside that, calling toDataURL() on the canvas, and then passing that image back to the top window using a callback. I suppose you could also pass back a canvas object.

**Comment by xzw123** [comment]
`return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {
        if (typeof(options.onrendered) === "function") {
            log("options.onrendered is deprecated, html2canvas returns a Promise containing the canvas");
            options.onrendered(canvas);
        }
        return canvas;
    });`
change to 
`var width = options.width != null ? options.width : node.ownerDocument.defaultView.innerWidth;
    var height = options.height != null ? options.height+node.ownerDocument.defaultView.innerHeight : node.ownerDocument.defaultView.innerHeight;
    return renderDocument(node.ownerDocument, options, width, height, index).then(function (canvas) {
        if (typeof(options.onrendered) === "function") {
            log("options.onrendered is deprecated, html2canvas returns a Promise containing the canvas");
            options.onrendered(canvas);
        }
        return canvas;
    });`

This can solute the question about overflow of screen.
But it's only effective by height, width is invalid.

**Comment by vance** [comment]
xzw123 has a bad solution: setting `ownerDocument.defaultView.innerHeight` manually causes it to unbind from actual window sizing events. I think it would be best to do this in an iframe. I'm keen on trying Jordan's solution.

**Comment by vance** [comment]
Jordan, how did you end up using canvas in an iframe?

**Comment by vance** [comment]
Ah yes, doing it in an iframe with `window.postMessage(myData, ... ) ` does the trick. You can post back the whole data url of the rendered pixels.

**Comment by arjunasuresh3** [comment]
+1

**Comment by simonmysun** [comment]
Hi. After searching for solutions and observing how the code run, I write my own tricky solution. 

https://gist.github.com/simonmysun/c6da13ce2827a374e71ccf07d9f08e2d

It work for me and I hope it will help someone who needs. 

However, I still hope it can be supported in this library in the future.

**Comment by KingGeneral** [comment]
i still not get it, but for my issue is the image get cut off. when using chrome Version 54.0.2840.99 m 
(half image got screenshotted, but the other half got black screen)

but when using Mozilla 50.0.2, its working fine. (100% image), 

i dont know why.

> code :
```
var zenleft = $("#leftPanel").width();
var zenright = $(".dataPanel").width();
var after = zenright + zenleft + 250;
$("#timelineTarget").css({"background-color":"white","width":after});
```

![image](https://cloud.githubusercontent.com/assets/9468485/21132351/10914470-c146-11e6-8919-8db27943ed85.png)

**Comment by KingGeneral** [comment]
Finally i solve this issue by adding 

`$("body").css({"width": "+="+after}); //after is a total of the width of the element i want to view`

so

```
var zenleft = $("#leftPanel").width();  //calculate left side
var zenright = $(".dataPanel").width();  //calculate right side
var after = zenright + zenleft + 250;  // add all
$("body").css({"width": "+="+after});  //add the body

//add the css, even after add overflow still not working
$("#timelineTarget").css({"background-color":"white","width":after});   

 html2canvas(canvTimeline, {
    onrendered: function (canvas) {
            $("#previewImage").html(canvas);
            $("body").css({"width": "-="+after});   //turn it back
            getCanvas = canvas;
   }
});
```

hope it solve your own issue.

**Comment by wQueryLoveMm** [comment]
**onclone** maybe be the correct method. You can change css to get what you want....

**Comment by ruthraprakash** [comment]
Hi All, I have div which is scrollable. When i send the div input as canvas parameter, it just rendering what is avialable in viewport. I gone through all solutions. I didnt understand. Can anyone tell how to take entire content in div as screenshot.

**Comment by voracity** [comment]
@ruthraprakash, I had a similar issue. This works for my simple purposes on the latest version:

```js
function fullhtml2canvas(el) {
	return new Promise(resolve => {
		html2canvas(el, {
			width: el.scrollWidth,
			height: el.scrollHeight,
		}).then(canvas => {
			resolve(canvas);
		});
	});
}
```

**Comment by zakapong** [comment]
I have an issue with taking a screenshot of the timeline chart. I am not geeting the x axis value. it is just creating the image of the timline chart.
`  demoFromHTML(e) {
      e.preventDefault();

     
     
      let input = window.document.getElementById('divToPDF');
    
  
      html2canvas(input)
      .then((canvas) => {
      
        const imgData = canvas.toDataURL('image/jpeg');
  
        const pdf = new pdfConverter("l", "pt");
        pdf.addImage(imgData, 'JPEG', 15, 110, 800, 250);
        pdf.save('test.pdf');
      });
   

    }
`



- [ https://ibb.co/g9VwZYL] #1. url

**Comment by shasu01** [comment]
> I tried for a long time... But it makes a lot of problem... I could not achieve what you said. I found out that it works well when it is 'body' even if there is scrolling... I want to achieve the same for a div which has elements with scrolling... If you could help me out with this issue it would be of great help for me... I am looking forward to your comments...

Please can you show me how you got body to work

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
      -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
      
       
        html2canvas(document.querySelector(".pdfHTML"), {
            width: 1350, windowWidth: 1350
        }).then(canvas => {
            base64stringpdf = canvas.toDataURL("image/jpeg");
        });

**Comment by nishantgupta11** [comment]
-> Add CSS **overflow-y: scroll**; to HTML element **pdfHTML**
  -> Add attribute **width** & **windowWidth** to html2canvas method, which should be equal to width of **pdfHTML** Div
  
   
    html2canvas(document.querySelector(".pdfHTML"), {
        width: 1350, windowWidth: 1350
    }).then(canvas => {
        base64stringpdf = canvas.toDataURL("image/jpeg");
    });

**Comment by d4rkr3pt0r** [comment]
```
const canvas = await html2canvas(document.body, {
  width: window.innerWidth,
  windowWidth: window.innerWidth,
  height: window.innerHeight,
  useCORS: false,
  allowTaint: true,
  scale: 1,
});
```

**Comment by weiyang001** [comment]
> ```
> const canvas = await html2canvas(document.body, {
>   width: window.innerWidth,
>   windowWidth: window.innerWidth,
>   height: window.innerHeight,
>   useCORS: false,
>   allowTaint: true,
>   scale: 1,
> });
> ```

This is a current answer! “ windowWidth: window.innerWidth ” This configuration can address the display problem associated with overflow: auto"👍
