### ISSUE TITLE
Seems like not work for img tag.

### ISSUE THREAD

**Issue by poppinlp** [niklasvh/html2canvas#601]
Hi

This is a great tool. But seems like it's not working for `img` tag which `src` attribute is URL. And it's ok when `src` attribute is base64 encoded image.

I know canvas can't use image with no CORS, so maybe support this when it's ok and show some error message when it's not ok.

Want some help. THX.

You could check this demo for "not working":
[http://poppinlp.github.io/demos/html2image.html](http://poppinlp.github.io/demos/html2image.html)

**Comment by hyojin** [comment]
Try with allowTaint option
```
allowTaint: true
```
This will allow to draw cross-origin images

**Comment by poppinlp** [comment]
Got it. THX.
Forgot to look for options in the documentation. Sorry, my fault.
