### ISSUE TITLE
Rendering iframe parent.

### ISSUE THREAD

**Issue by Miroku87** [niklasvh/html2canvas#609]
I have html2canvas inside an iframe and I want to render the top document (same domain).
So as the dom element to screenshot I pass "top.document.body"
When I try I get the right image but then I see an error 

```
Uncaught (in promise) TypeError: Cannot read property 'removeAttribute' of null
    at html2canvas.js:620:41
```

And it starts a loop where I see the attribute on the body node appearing and disappearing continuosly as if the library keeps taking screenshots without stopping (fortunately it doesn't)

**Comment by arivera12** [comment]
I have the same issue I just commented line 620 and screenshots started working again
