### ISSUE TITLE
Html2Canvas repository

### ISSUE THREAD

**Issue by Cristy94** [niklasvh/html2canvas#610]
Is this repository still maintained? There have been like 3 months without an update, should we create another repo? The author did not have any contributions on github since the last update here :(

**Comment by usmonster** [comment]
He's still active on github, but not necessarily on this project at the moment. I don't think there are any plans to stop work on this, though single-maintainer open source projects can be slow sometimes.

**Comment by niklasvh** [comment]
#1167
