### ISSUE TITLE
canvas elements intermittently rendering wrong

### ISSUE THREAD

**Issue by ccemeraldeyes** [niklasvh/html2canvas#611]
I find that (at least with recursive function calls, haven't tried with just 1 image per page), images will periodically render incorrectly -- they'll be misaligned and, in some cases, stretched.

This seems to happen particularly often when the page has been sitting idle for a few minutes.

I've isolated the issue to html2canvas by appending the canvas elements to the page and seeing that they render incorrectly.

I'm using the most recent version of html2canvas and find this issue in every browser.

**Comment by hyojin** [comment]
Can you provide a example of the problem?

**Comment by ccemeraldeyes** [comment]
a picture or a fiddle? If fiddle, is there a base fiddle with all the script references I can modify?

For a picture, see attached -- the image on the left is substantially shifted to the right from where it should be.

![screen shot 2015-06-18 at 6 32 52 pm](https://cloud.githubusercontent.com/assets/920090/8245776/8149e970-15e8-11e5-8acd-2869a1ffaf63.png)

**Comment by hyojin** [comment]
a jsfiddle with a simplified example please.
I'm new to jsfiddle, what's base fiddle?
we can just add any resources by clicking [External Resources] on the left side bar.

**Comment by ccemeraldeyes** [comment]
I meant a fiddle that had the external resources prepopulated since I'm not
sure where to link to.

On Thu, Jun 18, 2015 at 7:31 PM, Hyojin Kwak <notifications@github.com>
wrote:

> a jsfiddle with a simplified example please.
> I'm new to jsfiddle, what's base fiddle?
> we can just add any resources by clicking [External Resources] on the left
> side bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niklasvh/html2canvas/issues/611#issuecomment-113345409>
> .
>



-- 
~Colleen Briant

**Comment by ccemeraldeyes** [comment]
I made a fiddle but am unable to repro. There's a lot going on with my page so I don't know if I'd ever be able to get it to repro in a fiddle.

I've narrowed it down to bounds.left sometimes being wrong, though. It's as if it's treating an ancestor container as the document instead of the real document. Any ideas?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by hh29077106** [comment]
I have run into the same thing while batch convert my webpage( based on vue2.0+) into canvas
During my run, a small percent of the output canvas are stretched
