### ISSUE TITLE
How to limit how much site to parse

### ISSUE THREAD

**Issue by Miroku87** [niklasvh/html2canvas#612]
Hey everybody,
I would like to make a screenshot of the body of a page, but since it's very long and the parsing take a while I would like to restrain the height to scan.
How can I do that?

**Comment by hyojin** [comment]
Did you try `height` option?

**Comment by Miroku87** [comment]
I did. 
But the canvas that is returned is something like 7000 px height.

**Comment by hyojin** [comment]
I see. If you provide a jsfiddle example, maybe I can help you.

**Comment by Miroku87** [comment]
Unfortunately I can't create a fiddle since the situation is quite complicated.
I'm running on a large site inside an HTML5 Rich Media format and can't reproduce it on jsfiddle.
I can provide you a preview link:
http://2.229.52.99/previewer/files/campaigns/3325847858/25/IT_leonardo.it_mobile_201207_index.html
If you look at the JS console you can see a few log.
I also print the returned canvas which is very tall.

If you want to look at the code please use the Chrome dev tools and go to the Sources Tab > previewer/files > campaigns/3325847858/25 > js > interstitiallib.js 
In the function at row 140 I am injecting Javascript Code to the top of the document since I'm in an iframe.
In the injected code I have the html2canvas init script.

Thank you for your patience!

**Comment by DavidBruchmann** [comment]
Andrea,
you've to adjust the base-url being public. it's a local IP in the moment.

**Comment by Miroku87** [comment]
Uhmm strange that's our public ip!
Our local ones are in the form 192.168.1.xxx
What error do you get by opening it?

**Comment by DavidBruchmann** [comment]
I can open the page but some files are not loaded because in the source you
can see:


<base href="
http://192.168.1.193/previewer/files/templates//IT/leonardo.it_mobile_201207/
">

**Comment by Miroku87** [comment]
I see! let me fix that.

**Comment by Miroku87** [comment]
Fixed.

**Comment by DavidBruchmann** [comment]
you've any server-cache?
the local IP is still active.

**Comment by Miroku87** [comment]
That could be, but I'm not in power of clearing that cache =\

**Comment by hyojin** [comment]
@Miroku87 
I can't get `interstitiallib.js `. As @DavidBruchmann said, It seems like cache issue.
I can't figure out, but which element did you try to render?
I've checked `renderWindow` function. If you've tried `body` or `document`, height option wouldn't work.
```
 if (options.type === "view") {
            canvas = crop(renderer.canvas, {width: renderer.canvas.width, height: renderer.canvas.height, top: 0, left: 0, x: 0, y: 0});
        } else if (node === clonedWindow.document.body || node === clonedWindow.document.documentElement || options.canvas != null) {
            canvas = renderer.canvas;
        } else {
            canvas = crop(renderer.canvas, {width:  options.width != null ? options.width : bounds.width, height: options.height != null ? options.height : bounds.height, top: bounds.top, left: bounds.left, x: clonedWindow.pageXOffset, y: clonedWindow.pageYOffset});
        }
```

**Comment by Miroku87** [comment]
Why if I want to render the body I can't crop it?
And another thing: if I want a cropped screenshot, isn't it a waste of resources to render ALL the DOM Element and THEN crop just the returned canvas?
I need to speed up the render time by telling the lib to render all the document until it reaches a DOM Element which is positioned under a given pixel value.
Something like:
```javascript
if(currentDOMelement.y >= options.height)
{
    stopParsing();
    startRendering();
}
```

**Comment by fatihhayri** [comment]
canvas element limit 

http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

change code 

``function renderWindow(node, container, options, windowWidth, windowHeight) {
    var clonedWindow = container.contentWindow;
    var support = new Support(clonedWindow.document);
    var imageLoader = new ImageLoader(options, support);
    var bounds = getBounds(node);
    var width = options.type === "view" ? windowWidth : documentWidth(clonedWindow.document);
    var height = options.type === "view" ? windowHeight : documentHeight(clonedWindow.document);

    if (detectIE()) {
        height = (height > 8000) ? 8000 : height ;
    } else if (isMobile) {
        var canvasSizeMobil = 5000000 / width; // 5 megapixels limit
        height = (height > canvasSizeMobil) ? canvasSizeMobil : height ;
    } else {
        height = (height > 32000) ? 32000 : height ;
    }


.....
....
// device detection
if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)
    || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))) isMobile = true;

function detectIE() {
    var ua = window.navigator.userAgent;

    var msie = ua.indexOf('MSIE ');
    if (msie > 0) {
        // IE 10 or older => return version number
        return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
    }

    var trident = ua.indexOf('Trident/');
    if (trident > 0) {
        // IE 11 => return version number
        var rv = ua.indexOf('rv:');
        return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
    }

    var edge = ua.indexOf('Edge/');
    if (edge > 0) {
       // IE 12 (aka Edge) => return version number
       return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
    }

    // other browser
    return false;
}
``
