### ISSUE TITLE
No canvas for websites

### ISSUE THREAD

**Issue by a1Gupta** [niklasvh/html2canvas#613]
For these set of urls [ acer.com, drive.google.com,icloud.com,onedrive.live.com,mega.nz ] no canvas is rendered .

**Comment by brcontainer** [comment]
- `acer.com` redirect to `http://us.acer.com/ac/en/US/content/home`
- `drive.google.com` redirect to login page


then the problem is the redirects, to work have to use canonical urls.

**Comment by a1Gupta** [comment]
Okay
