### ISSUE TITLE
rendered body is not clipped as if width and height options were ignored

### ISSUE THREAD

**Issue by noopole** [niklasvh/html2canvas#617]
I downloaded html2canvas.js and could reproduce locally the homepage examples.

It worked fine with a full-page snapshot, but the width and height are not taken in account.

```
    html2canvas( document.body, {
        onrendered: function ( canvas )
        {
            document.body.appendChild( canvas )
        },
        width: 200,
        height: 200
    } )
```

I get the same behavior with IE 11, FF 38, Chrome 43 on Windows 7.

However when I pass to the function a div instead of 'document.body' it's fine.

Is it a normal behavior or a bug?

**Comment by hyojin** [comment]
It seems like a normal behavior.
#612

**Comment by awerlang** [comment]
Based on the second example from the page https://html2canvas.hertzen.com/examples.html, I understand this is a regression (the sample uses v0.4.1, current is v0.5.0-alpha1).
