### ISSUE TITLE
SVG render in general seems a bit limited

### ISSUE THREAD

**Issue by btm1** [niklasvh/html2canvas#618]
Currently I use canvg.js to accomplish converting svg to canvas and if you inline the styles yourself it does this almost flawlessly. I'm excited that you guys are trying to tackle svg to canvas rendering because then html + svg will be possible with this library. Please give canvg a look though to get pointers on how to make yours more accurate.  Right now the newly released svg rendering for html2canvas isn't there yet and I can't use it in production :(

**Comment by btm1** [comment]
Even if I inline the styles and use the new html2canvas.svg thing get rendered correctly but there are ghosts and things are duplicated and then overlapping in the exported canvas

**Comment by ccemeraldeyes** [comment]
+1 I also see duplicates and overlapping (though I think only in Firefox)
