### ISSUE TITLE
blurry on retina display

### ISSUE THREAD

**Issue by btm1** [niklasvh/html2canvas#621]
This issue has been around for a while in many different forms / issues. Any fix for this yet?  This isn't just a retina thing as much as it's just a high resolution display issue.

**Comment by btm1** [comment]
can someone please review this and then translate it into alpha release? https://github.com/niklasvh/html2canvas/commit/32deeac07a443a1665fbac583b8957593b06bf9e

**Comment by brcontainer** [comment]
Duplicate from: https://github.com/niklasvh/html2canvas/issues/390

**Comment by niklasvh** [comment]
Fixed in 1.0.0
