### ISSUE TITLE
Only renders what's in view

### ISSUE THREAD

**Issue by btm1** [niklasvh/html2canvas#622]
It would appear the resulting image size is as big as all of the window content including what's overflowed but what's actually visible limited only to the viewport.

This is with me taking overflow off of everything that I could possible take it off of. So there is no css interfering with this. Is it possible to get a content that is outside of the viewport included in the image? I've noticed that even if i scroll the page down and then try it again the result won't even pick up what's in the scrolled viewport but instead still contains what's in the viewport at scrollheight 0.

![campaignperformance 30](https://cloud.githubusercontent.com/assets/4110944/8360804/fefbecde-1b23-11e5-84a9-3a907975fc96.png)

**Comment by btm1** [comment]
Somehow on your examples on the homepage it shows everything in the body even what's not in view... how did you do that?

**Comment by brcontainer** [comment]
Possible duplicate: https://github.com/niklasvh/html2canvas/issues/117

**Comment by justein** [comment]
So ，I want to know how can capture an specifed element? do anyone has solution？

**Comment by brcontainer** [comment]
@justein Try this

```html
<div id="test-case">Test-me</div>
```

```js
html2canvas(document.getElementById("test-case")).then(function(canvas) {
    document.body.appendChild(canvas);
});
```

**Comment by cchubb** [comment]
I can confirm this behavior with the latest version. It will render the correct size of the object asked for, but will not actually render to the canvas anything that is off-screen of the current viewport. So if the 

    <div id="test-case">Test-me</div>

is currently visible in the browser, it will render. If it's off-screen, the canvas is blank (but the right size). Partially visible: Partially rendered. Mine doesn't act like scrollHeight = 0, it renders whatever is visible when the code is executed. (My button is at the bottom). 

Like btm's comment, I would like to know how it's done on the example site. Could it be requiring something in Angular or Bootstrap to get the off screen resources?

**Comment by brcontainer** [comment]
@cchubb  I do not understand what Angle and Bootstrap has to do with this. The problem of John, seems to me a matter of rendering a specific element.

If you want render which is outside the view-port, just use
```
html2canvas(document.body).then(function (canvas) {});
```
If you want to render elements "overflow" remove the "overflow" at runtime and add again after the process using javascript for add className, like this:
```
.no-scroll {
     overflow: visible !important;
}

#main {
     overflow: auto;
     height: 200px;
}

<div id="main">
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
</div>

document.getElementById("main").className = "no-scroll";
html2canvas(document.body).then(function (canvas) {
      document.getElementById("main").className = "";
});
```
Or just point the html2canvas to render the element within the element with "overflow", like this:
```
#parent {
     overflow: auto;
     height: 200px;
}

#child {
background-color: #fc0;
height: 600px;
}
<div id="parent">
<div id="main">
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
test<br> test<br> test<br> test<br> test<br> test<br> test<br> test<br> 
</div>
</div>

html2canvas(document.getElementById("main")).then(function (canvas) {});
```

Really has many suggestions for features that are unnecessary from my point of view, simply target the correct DOM elements and use the "CSS" to their favor.

**Comment by cchubb** [comment]
I figured it out. You fixed it in 0.5.0-alpha2. If I use the 0.5.0-alpha1 version it clips, but the alpha2 version does not. I didn't even notice that alpha2 was available because the releases page was focusing on alpha1. 

Here is a fiddle that demonstrates it working now with alpha2. https://jsfiddle.net/cchubb/fy7tw7ek/1/  if you change the external resource back to alpha1, it will clip when the bottom link is clicked. (You need to save the download file as .png to view it, fiddles won't let me change the output window href to data.)

@btm1, try upgrading to Alpha2.

**Comment by btm1** [comment]
@cchubb I'll give this a shot.

**Comment by btm1** [comment]
@cchubb the underlying issue is fixed in alpha 2 and you're right it's well hidden I didn't even notice there was an alpha 2.

**Comment by NPC** [comment]
Hmm, for me even in alpha2 still only the part of the element which is "visible" in the viewport is rendereded. See http://jsfiddle.net/NPC42/ykvL6a17/ for a demonstration—html2canvas exports only those rows that are scrolled into viewport (regardless of whether they are visible in scrolled container div or not).

Am I calling html2canvas wrong somehow? When I test it on my actual code (not the JSFiddle one, which I created just for the demo), this suggestion helps render the whole element: https://github.com/niklasvh/html2canvas/issues/650, but I hope to avoid hacking the library.

**Comment by btm1** [comment]
@NPC It won't just render what's not in view without you doing anything you have to change it to overflow visible --->export really quickly ---> then change it back to scroll again or it won't work. Not ideal IMO i think there should be an option to just have it work but at least it does.

**Comment by NPC** [comment]
@btm1, yes, I assume that's not intentional, since I pass in the element that is within the scrolled one, the element itself doesn't have any overflow trimming. 

For now in my app I found that I need to reattach my whole element to body, forcing specific width/height on it (since is contains absolutely positioned elements), in the meantime covering all this kitchen by a full-screen "Preparing export, please wait" overlay, because html2canvas takes 10+ seconds to render it all. After render is done—I attach it back to original location (inside a scrolled container), unsetting width/height.

Cumbersome, but it works.

**Comment by bianjp** [comment]
Strangely, it only renders from the currently visible top boundary of the given element.

Try https://jsfiddle.net/bianjp/bpc3nq69/1/. Scroll to "Print Screen" and click it. The generated image won't include top lines that are not visible when clicked.
Using version 0.5.0.beta4.

Solution is to call `$('html, body').scrollTop(0)` (or any other way to make the top of the element to render visible) before calling html2canvas.

**Comment by simogeo** [comment]
thanks @bianjp !

> Strangely, it only renders from the currently visible top boundary of the given element.

Is that a normal behavior ... It appears very strange to me !

**Comment by Brieg** [comment]
+1

**Comment by maiasmith** [comment]
[This S.O. answer](https://stackoverflow.com/a/25536879/3005925) worked for me.

**Comment by ziyoung** [comment]
Before calling html2canvas, scroll the element you want to render into viewport.
```js
const el = document.querySelector('#test')
el.scrollIntoView()
setTimeout(function () {
  html2canvas(el, {
    onrendered: function (canvas) {
      document.body.appendChild(canvas)
    },
    useCORS: true
  })
}, 10)
```
It works for me.
Using version is 0.5.0-beta4.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by Tholem98** [comment]
That work on desktop but it doesn't work on mobile

**Comment by scionGbh** [comment]
What I did is `windows.scrolTo(0,0) `before call htmltocanvas(), if you are on top of screen the div is printed complete
