### ISSUE TITLE
at new 0.5.0 release , chinese font rendered not the same in chrome~

### ISSUE THREAD

**Issue by nihaoqkl** [niklasvh/html2canvas#623]
but at 0.4.1 is the same~!

**Comment by eyeofbri** [comment]
Not sure why I received this email....

On Monday, June 29, 2015, nihaoqkl <notifications@github.com> wrote:

> but at 0.4.1 is the same~!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niklasvh/html2canvas/issues/623>.
>


-- 
* Brian McLendon II *
mclendon.brian@gmail.com
brian.teenzombie.com
609.213.3356

**Comment by brcontainer** [comment]
Firefox vs Chrome? Your question is not clear.
