### ISSUE TITLE
Anti-Aliasing on border radius

### ISSUE THREAD

**Issue by Mullvinn** [niklasvh/html2canvas#624]
When applyed border radius, the border is very ugly.
Like this:
![2015-06-29 10 32 27](https://cloud.githubusercontent.com/assets/4125903/8410119/c9ddd114-1eae-11e5-8b72-17e0666159e2.png)
And this:
![2015-06-29 10 32 33](https://cloud.githubusercontent.com/assets/4125903/8410126/ced0020a-1eae-11e5-9cac-5a9508756d41.png)

Please fix this, thanks.

**Comment by brcontainer** [comment]
Work fine for me, show an example in fiddle of problem (**reproduce** the problem on the fiddle)

**Comment by MiincGu** [comment]
http://jsfiddle.net/f7ey6erp/4/

Here's the code snippet.
Browser: Chrome v45

**Comment by hyojin** [comment]
It seems like a Chrome's problem.
It works perfectly in Firefox and Safari.
