### ISSUE TITLE
html2Canvas does not render shadow in css property

### ISSUE THREAD

**Issue by thinksysuser** [niklasvh/html2canvas#628]
Hi,

If the user provide a text-shadow effect to the text to highlight it and more readable format, then html2Canvas doesn't render this highlight CSS in image. Image only contains simple text, not the highlighted one. Kindly resolve this ASAP.

Thanks Avneesh

**Comment by brcontainer** [comment]
Duplicate from https://github.com/niklasvh/html2canvas/issues/114 https://github.com/niklasvh/html2canvas/issues/221 https://github.com/niklasvh/html2canvas/issues/246 and https://github.com/niklasvh/html2canvas/issues/430

Read: https://github.com/niklasvh/html2canvas#browser-compatibility

**Comment by usmonster** [comment]
(Note: #430 is actually unrelated and talks about the [shadow DOM](https://developer.mozilla.org/docs/Web/Web_Components/Shadow_DOM), which is unrelated to CSS *shadow properties.)
