### ISSUE TITLE
Html2Canvas delay in rendering images and not in a sequence

### ISSUE THREAD

**Issue by jyotiverma0310** [niklasvh/html2canvas#629]
`I` am having problems with Html2canvas render as i want to take multiple screenshots of an image and send the same to the selected contacts in a sequence but Html2canvas is rendering images in a delayed and unsequential way, which in return is not able to send the image to corresponding selected contact. Below is my code it is running successfully but the delay and unsequential output is creating a lot of problem.

```
function printCards(calle, eventID){
    var cards = new Array();

```
var checkboxArray = $("input[name='contactsParty']:checked");

$('#inviteContactName').html($(checkboxArray[0]).parent().prev().children('label').text());

    //  iterating selected checkboxes for invitation
    checkboxArray.each(function(index, value){

        //  getting name of next contact selected
        var name = $(checkboxArray[index+1]).parents().eq(1).find('label').text();

        //  Getting invitation card
        var invitationCard;
        $.when(invitationCard = getImage(name)).promise().done(function(){
            //  saving the printed invitation
            cards.push(invitationCard);
        });

    });

return cards;   
```

}

//  printing invitation card with contact name
function getImage(name){

```
var invitationCard = new Image();

    html2canvas($("#invitationData"), {
```

//          logging : true,
            onrendered: function(canvas) {
                //  For image`enter code here`
                var ctx=canvas.getContext("2d");
//              ctx.webkitImageSmoothingEnabled = false;
//              ctx.mozImageSmoothingEnabled = false;
                ctx.imageSmoothingEnabled = false;

```
            var convertedImage;
            $.when(convertedImage = canvas.toDataURL('image/jpg')).promise().done(function(){
                invitationCard.src = convertedImage;
                $('#inviteContactName').html(name);
            });  
```

//              setTimeout(function (){}, 500);
            }

```
    });

return invitationCard;
```

}
```

**Comment by atdiff** [comment]
@testjava03 were you ever able to figure this out?

**Comment by jyotiverma0310** [comment]
It's very late but i was not able to figure this out.

**Comment by jlahare** [comment]
why this issue is closed ? is it resolved ?
