### ISSUE TITLE
Not Allowing the html2canvas screenshot to appear in the visual force page

### ISSUE THREAD

**Issue by Subhrajn** [niklasvh/html2canvas#630]
Hi

![withoutradios](https://cloud.githubusercontent.com/assets/13269268/8613575/1583c6a8-26fe-11e5-8195-4b450cd3a939.JPG)

The picture of my vf page is given above, first one is the original vf fields and second one is the screenshot of the page generated using html2Canvas. I donot want the screenshot to appear in the vf page though the screenshot of the  vf page should be taken in background.
Please help me with this.

I am generating screenshot using this below-
window.onload=function(){
            html2canvas(document.body,
            {
                useCORS: true,
                onrendered: function(canvas)
                {
          //           document.getElementById("mapDiv").style.display = 'none';
                    document.body.appendChild(canvas);

```
            }
        });
    }
```

**Comment by hyojin** [comment]
I'm not sure what is vf page and what is your problem. but, you mean, you want to exclude specific element in screenshot of your page? If my guess is right, set to hide before capturing your page.

**Comment by hyojin** [comment]
Here is a better solution.
#464
