### ISSUE TITLE
Does not work with browserify / requirejs

### ISSUE THREAD

**Issue by xinan** [niklasvh/html2canvas#632]
The `alpha2` or the latest master only work if I include it as a global script. It doesn't work if I import it with browserify or requirejs. Without any log or error in the console. 

But the `alpha1` works. No idea why yet, probably related to the switching to browserify for building. 

Could anyone look at it? Thanks!

**Comment by hyojin** [comment]
Try [this.](https://github.com/hyojin/html2canvas/tree/fix-%23632) 
(you need to build)

**Comment by hyojin** [comment]
I updated my code. now, you can use logging option.
But, It is still temporary, Not support AMD.

**Comment by xinan** [comment]
Thank you @hyojin ! I guess I will just stick to `alpha1` first. :smile_cat:

**Comment by indapublic** [comment]
@hyojin Trying to require your html2canvas, but no success :(

```html
<html>
	<head>
		<meta charset="UTF-8">
	</head>
	<body>
	</body>
	<!--
	<script type="text/javascript" src="html2canvas.min.js"></script>
	-->
	<script type="text/javascript" src="require.min.js"></script>
	<script type="text/javascript">
		require(['html2canvas.min'], function () {
			console.log(typeof html2canvas); /* undefined */
		});
	</script>
</html>
```

With direct tag script all working

**Comment by hyojin** [comment]
@indapublic I only checked with browserify. I'm sorry to forget to mention it.
And I'm a beginner to requirejs. But normally, don't we have to set the parameters in the callback to reference modules?
```
require(['html2canvas.min'], function (html2canvas) {
    console.log(typeof html2canvas);
});
```

**Comment by niklasvh** [comment]
Shoudl be fixed with https://github.com/niklasvh/html2canvas/commit/4b37909f09c3892ab5fc1b1a306059bc33a76a3d
