### ISSUE TITLE
html2canvas not converting images

### ISSUE THREAD

**Issue by tfnsw-spatial** [niklasvh/html2canvas#636]
I've noticed that images are not converted in this scenario : 
![image](https://cloud.githubusercontent.com/assets/10526222/8717501/8c205476-2bdf-11e5-85e4-97100b2a040d.png)

Is it because the images are referenced from different origin ?

thank you

**Comment by brcontainer** [comment]
Duplicate from:
- https://github.com/niklasvh/html2canvas/issues/485
- https://github.com/niklasvh/html2canvas/issues/462
- https://github.com/niklasvh/html2canvas/issues/244
- https://github.com/niklasvh/html2canvas/issues/345
- https://github.com/niklasvh/html2canvas/issues/453

**Comment by tarekahf** [comment]
Was this issue resolved?

Tarek
