### ISSUE TITLE
Handle error caused by instability of `Range.getBoundingClientRect()`

### ISSUE THREAD

**Issue by xinan** [niklasvh/html2canvas#637]
`html2canvas` is giving me intermittent errors, especially when I run my `mocha` + `phantomjs` tests on Travis. 

The error message is

```
'null' is not an object (evaluating 'rangeBounds.height')
```

where the place that this error comes from is 

```
Support.prototype.testRangeBounds = function(document) {
    var range, testElement, rangeBounds, rangeHeight, support = false;

    if (document.createRange) {
        range = document.createRange();
        if (range.getBoundingClientRect) {
            testElement = document.createElement('boundtest');
            testElement.style.height = "123px";
            testElement.style.display = "block";
            document.body.appendChild(testElement);

            range.selectNode(testElement);
            rangeBounds = range.getBoundingClientRect();
            rangeHeight = rangeBounds.height;

            if (rangeHeight === 123) {
                support = true;
            }
            document.body.removeChild(testElement);
        }
    }

    return support;
};
```

Example of this issue: https://github.com/PencilCode/pencilcode/pull/162
Note that across most of the commits, the code doesn't really change, I was just changing the comments to force Travis to re-run it while at the same time keep the log for every time it runs. It can be seen that it has a significant possibility to fail, and failure was because the code above threw an error. 

After some investigation, I suspect that this might be caused by the instability of `Range.getBoundingClientRect()`. It is an experimental feature according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Range/getBoundingClientRect). And it is returning `null` sometimes even though it shouldn't return `null` in all situation according to its [specification](http://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect). 

So before this issue is fixed by the browsers / whatever. We should have some error handling for it. I'm crafting a PR for that :smile:

**Comment by davidbau** [comment]
Yes, here is an example travis run where html2canvas crashes in PhantomJS due to this null-dereference.

https://travis-ci.org/PencilCode/pencilcode/builds/71617977

It's odd that this is an intermittent problem; but it seems that html2canvas should check getBoundingClientRect() != null before dereferencing it here.

**Comment by drewzh** [comment]
@davidbau Did you ever find a workaround for this?

**Comment by davidbau** [comment]
As far as I know, we do not have yet have a workaround for this intermittent failure.

**Comment by drewzh** [comment]
@davidbau Ok thanks, I might have to switch back to 4.0, my problem isn't intermittent, but happens any time my printing service is called.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
