### ISSUE TITLE
Canvas won't properly render if window isn't scrolled to the top

### ISSUE THREAD

**Issue by mrbrainz** [niklasvh/html2canvas#639]
Hi,

So I'm rendering a Div that's one of my last elements on the page. What I found was that if I scroll down the page and render the canvas, the canvas will be padded by the amount I've scrolled down. My fix has been to force a scroll to the top of the window before rendering, but all the jumping about won't be good for people's eyes.

Any idea why this behaviour exists? Is there some CSS trickery that I can do to prevent it.

Apologies if this is a dup, I did look for any other tickets mentioning this but couldn't find one.

Cheers,

Greg

**Comment by samsonkhisty** [comment]
I've had this exact issue. From my experience, the scrollbar should exist on the viewport/window. Your target div should not be inside another div that has scrollbars. Hope this helps.
