### ISSUE TITLE
Glitches on rendering a canvas based off on SVG

### ISSUE THREAD

**Issue by sigurdvh** [niklasvh/html2canvas#640]
Hi,

It is great to see that version 0.5.0 already includes support for SVGs. Thank you! From my initial testing, I noticed two artifacts when trying to use the 0.5.0-alpha1 drop. Please look at the following sample:

http://plnkr.co/edit/mDH2WxYo4k6PIY6zFEGO

1) Image generated is somewhat blurry
![blurriness](https://cloud.githubusercontent.com/assets/6758403/8921230/e659a360-3487-11e5-9b00-d6ce3c1bc10b.png)

2) In some cases, I see the text elements in the SVG duplicated (seems to be related to the size of the container)
![duplicatedentries](https://cloud.githubusercontent.com/assets/6758403/8921238/f0687084-3487-11e5-9965-3e4b5f90e964.png)

Thanks!

**Comment by brcontainer** [comment]
Duplicate image sounds like bug in `DocumentFragment`, I will try create a patch.

**Comment by ncoquelet** [comment]
there is a fix for this bug
Test it

https://github.com/niklasvh/html2canvas/issues/541
