### ISSUE TITLE
Unable  to capture div elements style as "position:absolute"

### ISSUE THREAD

**Issue by matt212** [niklasvh/html2canvas#641]
Hi, 
Thanks for awesome plugin .
a.I am unable to capture elements of div where i have applied "position:absolute" in style class.please find attached copies of screenshot for  reference 
1. base.png.

![base](https://cloud.githubusercontent.com/assets/1698139/8924434/4ae362c4-351b-11e5-9057-6497e9cef068.png)

2.no render.png.

![no render](https://cloud.githubusercontent.com/assets/1698139/8924433/4ae24678-351b-11e5-9858-bd8cc22e6912.png)

b. However if i remove the class the rendering for screenshot works seamlessly 
1. working.png
![working](https://cloud.githubusercontent.com/assets/1698139/8924441/5d6cbc2e-351b-11e5-99ad-dce71893c602.png)

Could you please provide some pointer how can i resolve the issue 
 I am using updated version of plugin

**Comment by erickbarbosa** [comment]
What's the solution?

**Comment by AmirAshvins** [comment]
+1
