### ISSUE TITLE
Can't get background image to render...no matter what I try.

### ISSUE THREAD

**Issue by DeliciousPickle** [niklasvh/html2canvas#644]
I'm using 64-bit Ubuntu Linux, trying Opera, Chrome, and Firefox browsers.  I've Googled extensively and read through all of the issues posted here.  No matter what I try, I always get a white background instead of a background image.  Is there any way to get background image rendering to work????

**Comment by samsonkhisty** [comment]
I'll leave some examples I did recently, uses background-image 

1: https://jsfiddle.net/fuggfuggfugg/n5zqfsjy/1/
2: http://codepen.io/fuggfuggfugg/pen/ZYyBRv

Hope it helps

**Comment by gfaceless** [comment]
Very possibly you are using `background-size: cover` along with `background-image`,
If that is the case you should use dev version instead.

**Comment by JoeDMitchell** [comment]
Having the same problem, anymore help with this or did you get it working in the end?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
