### ISSUE TITLE
inline-block not work with opacity

### ISSUE THREAD

**Issue by benpaobenpao** [niklasvh/html2canvas#647]
设计效果如下图：
![default](https://cloud.githubusercontent.com/assets/1629413/9105140/7f755c9e-3c47-11e5-8f76-52a61fa70316.jpg)

html2canvas 生成效果如下图：
![default](https://cloud.githubusercontent.com/assets/1629413/9105149/9c16cd6a-3c47-11e5-9938-d585b0df86df.png)

求解释？

**Comment by brcontainer** [comment]
Show code please, without code is difficult to know the source of the problem.

**Comment by benpaobenpao** [comment]
原因是因为字体采用css伪类的时候，伪类设置为display:inlline-block; 字体半透明有效果，当设置为display:block;字体透明效果不起作用了。
例子：http://www.godgiftgame.com/static/can/examples/demo3.html
源代码：
![000111](https://cloud.githubusercontent.com/assets/1629413/9301083/69cc8cae-44fe-11e5-8857-813341992577.jpg)

效果图：
![000123](https://cloud.githubusercontent.com/assets/1629413/9301078/622870f8-44fe-11e5-91e2-bbb6af99e3b2.jpg)

**Comment by brcontainer** [comment]
Please, edite issue title to "inline-block not work with opacity".
