### ISSUE TITLE
Bootstrap's carousel scrolling controls rendered wrong

### ISSUE THREAD

**Issue by nosuchip** [niklasvh/html2canvas#649]
I am using adopted bootstrap carousel with a bit smaller prev/next arrows. Now I found that html2canvas renders it wrong when its size less then 27-28px (on that sizes rendring artifacts already visible). My controls have size 20px so it is displayed on resulting image awfully.

![zalkknz](https://cloud.githubusercontent.com/assets/418073/9128660/2025c326-3cd5-11e5-9d5b-48e418dc2f3c.png)

Here is sample fiddle: http://jsfiddle.net/qkungcm9/ (it does not matter that on jsfiddle images not rendered, on my dev region it displayed fine)

**Comment by hyojin** [comment]
Try [this](https://github.com/hyojin/html2canvas/tree/fix%23599).

**Comment by nosuchip** [comment]
@hyojin thanks fo rparticipation, but your fix did nothing. Buttons still looks ugly.
![image](https://cloud.githubusercontent.com/assets/418073/12416598/6988325a-beb3-11e5-9a48-2b6e9e47fd63.png)

**Comment by hyojin** [comment]
![2016-02-10 22 48 48](https://cloud.githubusercontent.com/assets/3413183/12948930/937fe73c-d048-11e5-98a9-a46f1c26ffb3.png)

@nosuchip It works better, at least me. Have you built with grunt command?

**Comment by nosuchip** [comment]
@hyojin no, I haven't built anything. Just linked this two files:
https://github.com/hyojin/html2canvas/blob/fix%23599/dist/html2canvas.js
and
https://github.com/hyojin/html2canvas/blob/fix%23599/dist/html2canvas.svg.js

and tried again.

**Comment by hyojin** [comment]
It was merged already. Try latest html2canvas.
