### ISSUE TITLE
missing bottom off element/screenshot!

### ISSUE THREAD

**Issue by coolbombom** [niklasvh/html2canvas#650]
Hi Niklas

thank you for an amazing framework! I'm currently using html2canvas 0.5.0 and my issue is that the bottom of the div element that I convert is missing in the image if I make the window smaller than the div! The div is scrollable!

I tried changing a little in the code, and changing the following code in window.html2canvas function fixes the problem:

original:
return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight, index).then(function(canvas) {

changed (added + 1000 to height):
return renderDocument(node.ownerDocument, options, node.ownerDocument.defaultView.innerWidth, node.ownerDocument.defaultView.innerHeight + 1000, index).then(function(canvas) {

I noticed that the smaller I make the window the higher the number needs to be to include the bottom off the div.

I was hoping you could tell me what I’m doing wrong or maby come up with a better solution.

cheers
c_bb

**Comment by maiasmith** [comment]
[This answer](https://stackoverflow.com/a/25536879/3005925) worked for me.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
