### ISSUE TITLE
Funny svg rendering on ff and ie

### ISSUE THREAD

**Issue by ncoquelet** [niklasvh/html2canvas#651]
I try to export a highcharts donut and i have a strange rendering on firefox and IE.

Look by yourself, no problem on chrome
http://jsfiddle.net/atzjLjLn/5/

If i try to extract the works of html2canvas, this same example works on all browser 
http://jsfiddle.net/khy7h6zf/5/

I have read a lot of line of the html2canvas js, do some debugging but i can't point the problem !
Any helps are appreciated !

**Comment by niklasvh** [comment]
Fixed in 1.0.0
