### ISSUE TITLE
Crops incorrectly when scrolled

### ISSUE THREAD

**Issue by PixelsCommander** [niklasvh/html2canvas#652]
Image on resulting canvas appears scrolled when document.body is scrolled.

**Comment by dineshgh** [comment]
I am calculating the containers h/w by interrogating the boundingRects of child elements, and get 342 w X 171 h. This is what I pass in options.

But html2canvas computes a shorter height, truncating the content

211ms html2canvas: Document cloned
217ms html2canvas: Initialized CanvasRenderer with size 366 x 748
218ms html2canvas: Starting NodeParser
238ms html2canvas: Fetched nodes, total: 73
239ms html2canvas: Calculate overflow clips
262ms html2canvas: Start fetching images
265ms html2canvas: Finished searching images
266ms html2canvas: Images loaded, starting parsing
267ms html2canvas: Creating stacking contexts
272ms html2canvas: Sorting stacking contexts
274ms html2canvas: Render queue created with 42 items
309ms html2canvas: Finished rendering
310ms html2canvas: Cropping canvas at: left: 9.390625 top: 622.765625 width: 342 height: 125.234375
310ms html2canvas: Resulting crop with width 342 and height 171  with x 9.390625 and y 622.765625
321ms html2canvas: Cleaned up container
322ms html2canvas: options.onrendered is deprecated, html2canvas returns a Promise containing the canvas

The height it picks up is 125 (the true height is 171). How do I fix this? It is the last in a scrolled list (using ionic-framework). Thanks.

**Comment by niklasvh** [comment]
Fixed in 1.0.0
