### ISSUE TITLE
Is there a way to 'trick' the window width?

### ISSUE THREAD

**Issue by cobyrne09** [niklasvh/html2canvas#653]
I am trying to create an image of a web page for export to PDF, but It will be relatively useless unless I can get it to fit the dimensions of a standard PDF page, 8 1/2 x 11.

I have tried the width option, but it seems that it just cleaves an image of the full window width.

Sincere thanks for any help or suggestions.

**Comment by niklasvh** [comment]
1.0.0 has the option to define window width/height
