### ISSUE TITLE
html2canvas disturbing other scripts

### ISSUE THREAD

**Issue by shehroze37** [niklasvh/html2canvas#655]
html2canvas script is disturbing other scripts and function for example one problem is that when I use html2canvas bootstrap modal function is affected. It gives error that ".modal function is not defined" !

When I comment out the html2canvas script everything else if fine !
So how do I fix this issue ?

**Comment by tobya** [comment]
Try posting a question on stackoverflow.com and tagging it html2canvas

**Comment by defbug** [comment]
This is also happening to me. facebook script is being called everytime html2canvas is called.
