### ISSUE TITLE
Table is not getting rendering to image if the rows has rowspan attribute

### ISSUE THREAD

**Issue by madhav1306** [niklasvh/html2canvas#656]
Table is not getting rendered as expected in the png image, when the rows has rowspan attribute. Please provide the workaround to fix this issue

**Comment by Nimesh-Soni** [comment]
![1](https://user-images.githubusercontent.com/2369790/28108613-c25c51a4-6709-11e7-823e-cc1a9f29d0e1.png)
![2](https://user-images.githubusercontent.com/2369790/28108614-c26056b4-6709-11e7-9dd6-6abc2f71441c.png)

**Comment by Nimesh-Soni** [comment]
html2canvas([document.getElementById('mydiv')], {
		onrendered: function (canvas) {
			document.getElementById('canvas').appendChild(canvas);
			var data = canvas.toDataURL('image/png');
                 }
});

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by jopassaldevar20** [comment]
The provided [jsfiddle](http://jsfiddle.net/az5j0766/230/) is now populated with the code to reproduce the issue. It seems that there is a problem if you set the background color of the <tr>.

**Comment by byc233518** [comment]
> The provided [jsfiddle](http://jsfiddle.net/az5j0766/230/) is now populated with the code to reproduce the issue. It seems that there is a problem if you set the background color of the `<tr>`.

感谢！ 解决了我的问题。

**Comment by ShawshankLin** [comment]
> > The provided [jsfiddle](http://jsfiddle.net/az5j0766/230/) is now populated with the code to reproduce the issue. It seems that there is a problem if you set the background color of the `<tr>`.
> 
> 感谢！ 解决了我的问题。

但是我就是需要给行加背景色，怎么办？

**Comment by zhaydexxa** [comment]
> > > The provided [jsfiddle](http://jsfiddle.net/az5j0766/230/) is now populated with the code to reproduce the issue. It seems that there is a problem if you set the background color of the `<tr>`.
> > 
> > 
> > 感谢！ 解决了我的问题。
> 
> 但是我就是需要给行加背景色，怎么办？

change the background color from tr to td

**Comment by periyasamy1986** [comment]
Hi All In the table td you can add the css  "vertical-align: baseline;" it will work.
