### ISSUE TITLE
Text not appearing inside of svg on export.

### ISSUE THREAD

**Issue by JAPiasente** [niklasvh/html2canvas#657]
When trying to export a bar chart with text inside the bar chart which I created in d3.js, the text is not appearing.  Also on other examples all of the text is appearing bunched up above the top bar.. I have created a jsfiddle to show what is happening http://jsfiddle.net/japiasente/chvj19po/

**Comment by CraigVA** [comment]
The text shows up for me in Chrome FF and IE, but in Chrome it's so small that it's illegible.  html2canvas has trouble recognizing CSS styles sometimes, but it works if you set them explicitly:

http://jsfiddle.net/haf2tc1t/2/

(The extra click code is so that it can work in IE too.)
