### ISSUE TITLE
Each click renders a different result.

### ISSUE THREAD

**Issue by brunomonteiro3** [niklasvh/html2canvas#660]
Hello,

I'm experiencing a issue with html2canvas plugin. For some reason, when I ask to generate the canvas, each click generate a different result.

As you can see here, 10 different tests generate different results: 
http://i.imgur.com/wNg9Txq.png

The expected result is:
http://i.imgur.com/IP2BRDy.png

I'm not using any CSS3 advanced attribute, and this is a very simple HTML page.

Any ideas on what may be happening? The same problem happens if I ask to generate a base64 image on another browser tab.

I'm testing on Firefox 40 for Mac OS X.

Thanks!

**Comment by brcontainer** [comment]
Post a jsfiddle example.

**Comment by programmin1** [comment]
Were you html-to-canvas-rendering while another html-to-canvas-rendering was running?

**Comment by brunomonteiro3** [comment]
Hello everyone,

For some reason, it only happens when I'm working on localhost and with Firefox. I have uploaded all my files to a server and it seems to be working fine.
