### ISSUE TITLE
html2canvas appears to modify dom's textnode

### ISSUE THREAD

**Issue by marksandler2** [niklasvh/html2canvas#663]
Hi, html2canvas appears to modify textnodes inside the dom under certain circumstance, which is a big no-no, essentially we end up with screwed up document.

More specifically: 

```
function supportRangeBounds() 
```

seems to return false under certain circumstances, because the measured client rect ends up being 122.99, rather than 123. 

As a result this function: 

``` javascript
function getTextBounds(state, text, textDecoration, isLast, transform) {
    var bounds;
    if (support.rangeBounds && !transform) {
      if (textDecoration !== "none" || Util.trimText(text).length !== 0) {
        bounds = textRangeBounds(text, state.node, state.textOffset);
      }
      state.textOffset += text.length;
    } else if (state.node && typeof state.node.nodeValue === "string" ){
      var newTextNode = (isLast) ? state.node.splitText(text.length) : null;
      bounds = textWrapperBounds(state.node, transform);
      state.node = newTextNode;
    }
    return bounds;
  }
```

ends up doing a textNode.splitText rather than use textRangeBounds. The former is inplace operation, so we end up with broken document dom.

**Comment by niklasvh** [comment]
Fixed
