### ISSUE TITLE
Can Disable crop option?

### ISSUE THREAD

**Issue by gdeliz** [niklasvh/html2canvas#665]
Hi,

I have a stage 1280x720 and a div named "holders" again 1280x720 that contains images.

When I am trying to render the div, I am getting an image 1280x720 , but the rendered image is cropped about 587x296px and the rest of the image is black (I suppose that the black color is because in the HTML I have black background).

![file 6](https://cloud.githubusercontent.com/assets/6683444/9479142/8ffd4e7c-4b84-11e5-97f9-68825ea3a36e.jpg)

How is possible to disable the crop function, in order to have the whole div as an image of 1280x720?

**Comment by niklasvh** [comment]
Crop options have been expanded in 1.0.0
