### ISSUE TITLE
overflow: "auto"

### ISSUE THREAD

**Issue by itozer** [niklasvh/html2canvas#666]
If the html is an an element with the css property "overflow: auto", then the canvas only renders what is currently visible.

**Comment by zhump** [comment]
I am also in distress

**Comment by fatihhayri** [comment]
I resolved 

var clip = (container.css('overflow') === "hidden") ? [container.borders.clip] : [];

change

var clip = (["hidden", "scroll", "auto"].indexOf(container.css('overflow')) !== -1) ? [container.borders.clip] : [];
