### ISSUE TITLE
css transform: rotate();

### ISSUE THREAD

**Issue by itozer** [niklasvh/html2canvas#667]
Text that has the css property "transform: rotate()" is not being rendered to the canvas properly.

**Comment by brunomonteiro3** [comment]
Are you setting the browser prefix?

**Comment by XigenBen** [comment]
Possible duplicate #220

**Comment by naganathH** [comment]
Text that has the css property "transform: rotate()" is not being rendered to the canvas properly.

**Comment by naganathH** [comment]
<img width="27" alt="verticaltext" src="https://user-images.githubusercontent.com/32845143/38579020-5bebb2aa-3ccb-11e8-97fd-6ccb6472c62d.png">
