### ISSUE TITLE
Screenshot from element fail

### ISSUE THREAD

**Issue by Thiagocfn** [niklasvh/html2canvas#668]
If call html2canvas to another element than document.body, method fail on html2canvas.js line 602

**Comment by Thiagocfn** [comment]
anything like this will fail:

html2canvas($("#toPrint")., {
                onrendered: function (canvas) {
                    ...
                }
            });

**Comment by CraigVA** [comment]
Try document.getElementById("toPrint") .  jQuery objects aren't always the same as document objects.  Also it looks like you have an extra period before the comma.

**Comment by Thiagocfn** [comment]
Same problem @CraigVA.
This happens, because core.js at line 43: 
var node = ((nodeList === undefined) ? [document.documentElement] : ((nodeList.length) ? nodeList : [nodeList]))[0];

if object is a single element he try get "first element of the list".
I fixed it at #669

**Comment by Thiagocfn** [comment]
@CraigVA  - "Also it looks like you have an extra period before the comma."

Yeah. My mistake on writing this example. But the problem is the same.
