### ISSUE TITLE
Screen capturing working on any device but iPhone

### ISSUE THREAD

**Issue by aliasltb** [niklasvh/html2canvas#670]
Hey,

I have an overlay, which has a fixed position. Within this overlay I have a canvas styled with some css (blur and opacity) on which users can draw something. After that I'll capture the drawing with its css stylings by using html2canvas. So I copy content of a canvas to a new canvas.

This actually works in all browsers and android devices, so basically in general. For some reason on some iPhones this doesn't work, like iPhone 6 (plus). iPhone 5 for example does work.

Do you have any ideas, if the fixed overlay or using html2canvas on mobile devices could cause issues or especially this issue?

Would be great if you can help me!

I am using the latest version.

// I read that it might be a problem rendering high res images on iOS?

**Comment by zqcloveping** [comment]
hi aliasltb, I also have this problem.When it runs on high resolution devices, there will be problems.

**Comment by mukeshcp** [comment]
I have same Issue in Iphone 6 & above. Its working in Iphone 5.
Please do needful if anybody having idea.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by aliasltb** [comment]
Are you serious? After 2 years, I am asked to provide an example and 6 hours later the topic is closed since there has been no response for more info from me?!

Made my day..
