### ISSUE TITLE
Canvas elements in the html are not properly converted in to the result canvas.

### ISSUE THREAD

**Issue by prasad4491** [niklasvh/html2canvas#671]
Polygon in the map is drawn using canvas. I am trying to convert into canvas. but i  unable to convert it properly. 
Actual result:
![mapscreenshot](https://cloud.githubusercontent.com/assets/8524977/9513956/5ea6411e-4cb3-11e5-8617-bdbe11c8bcce.png)
Expected Output should be like this
![actualscreenshot](https://cloud.githubusercontent.com/assets/8524977/9514045/040487ba-4cb4-11e5-9cf7-1b4e44856dd5.png)

**Comment by brunomonteiro3** [comment]
If you are working on localhost, test your code on Google Chrome, otherwise it will fail. If you can't test on Chrome, try uploading your files in a server.
