### ISSUE TITLE
Opacity and SVG issue

### ISSUE THREAD

**Issue by jwhite3328** [niklasvh/html2canvas#672]
Hello everyone, I am hoping someone may have found a solution to the problem I have encountered. I know that SVG support in version 0.4.1 was being worked on and that in version 0.5.0 it has been addressed with the full rewrite. However here is the issue I have ran into. My web tool has the option to select a parcel to obtain information about the result as seen in the folllowing picture.

![image](https://cloud.githubusercontent.com/assets/14114211/9666899/a4492720-522d-11e5-8771-bc3746303d0b.png)

Now when you use version 0.4.1 you are able to get the screen capture and the opacity of the information remains, but the graphic on the map itself does not show as seen next:

![image](https://cloud.githubusercontent.com/assets/14114211/9666945/e5f4e330-522d-11e5-8b43-8edd5254374c.png)

So I then attempted to use the 0.5.0 prerelease version and I was able to get the graphic to show, but now all the transparencies for what was in the map are now lost as seen in the next image:

![image](https://cloud.githubusercontent.com/assets/14114211/9667054/7a36bf32-522e-11e5-86a3-814303624a23.png)

Has anyone been able to resolve this issue with either version and/or have any ideas on how one might be able to combine the opacity ability of version 0.4.1 with the graphic/SVG display that is found in version 0.5.0. I am at a loss right now and I am opting to go with version 0.4.1 so my users can at least print the page with 90% of the functionality needed, but getting that last 10% of getting the graphic to show would be greatly appreciated.

For access to the full code please feel free to visit: http://gis.florenceaz.gov/Web_Maps/Address_Search.html

**Comment by chughes87** [comment]
It seems like html2canvas doesn't handle the intersections of SVGs and CSS styles. You can fix issues like this by setting the opacity attribute on the given element or adding a style tag to your svg. Maybe html2canvas will handle this issue in the future, but for now these are workarounds.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
