### ISSUE TITLE
box-shadow css property is not rendering once converted to image

### ISSUE THREAD

**Issue by manulohiya** [niklasvh/html2canvas#673]
Any tips for workarounds? 

CSS code: 
p span {
  line-height: 1;
  display: inline-block;
  margin: 0 4px 8px 0;
  background-color: #efefef;
  padding: .4em;
  -webkit-box-shadow: 3px 3px 0px 0px rgba(50, 50, 50, 1);
  -moz-box-shadow: 3px 3px 0px 0px rgba(50, 50, 50, 1);
  box-shadow: 3px 3px 0px 0px rgba(50, 50, 50, 1);
}

Original:
![screenshot 2015-09-05 12 09 19](https://cloud.githubusercontent.com/assets/12042227/9700825/fe40dc2e-53c6-11e5-9657-81d12a0a72b9.png)

with HTML2Canvas
![screenshot 2015-09-05 12 10 32](https://cloud.githubusercontent.com/assets/12042227/9700830/23b14084-53c7-11e5-9ed0-d6133aa8d8eb.png)

**Comment by brunomonteiro3** [comment]
Try running your code on a server. I had the same issue but when I was running the code on localhost.

**Comment by Aznbai** [comment]
**same problem**  
``` text-shadow``` and ``` background-clip: text;``` are being displayed wrong, as you can see below.

 running it on a local grunt server
![gub](https://cloud.githubusercontent.com/assets/1290615/10036668/bc794104-61aa-11e5-81f7-90c8b3104c5c.jpg)

**Comment by aju31a** [comment]
yes this is a issue in please help if anybody knows something about it urgently.

**Comment by brcontainer** [comment]
Hi @Aznbai read this https://github.com/niklasvh/html2canvas#javascript-html-renderer and https://github.com/niklasvh/html2canvas#browser-compatibility
> As each CSS property needs to be manually built to be supported, there are a number of properties that are not yet supported.

-------

**Duplicate from:**

- https://github.com/niklasvh/html2canvas/issues/114
- https://github.com/niklasvh/html2canvas/issues/221
- https://github.com/niklasvh/html2canvas/issues/246
- https://github.com/niklasvh/html2canvas/issues/430

**Comment by usmonster** [comment]
(Note: #430 is actually unrelated and talks about the [shadow DOM](https://developer.mozilla.org/docs/Web/Web_Components/Shadow_DOM), which is unrelated to CSS *shadow properties.)

**Comment by aaronfrost** [comment]
Love this library, so I hate to comment here and sound ungrateful. I am, however, wondering if this is a thing that people are looking into?

**Comment by niklasvh** [comment]
Closing as duplicate
