### ISSUE TITLE
Seems this library not render page with flexbox properly

### ISSUE THREAD

**Issue by greybax** [niklasvh/html2canvas#676]

**Comment by brcontainer** [comment]
Maybe ?

> As each CSS property needs to be manually built to be supported, there are a number of > properties that are not yet supported.
> - https://github.com/niklasvh/html2canvas#browser-compatibility

???

**Comment by joseiriarte1982** [comment]
Rotate worked form me but with a span I used one of the answers above. Here is what I did in my style I put 	a class 

.vertical {
    position: absolute;
    left: -50px;
    top: 0px;
    width: 120px;
    height: 20px;
    font-size:12px;
    color:#333;
    transform: rotate(270deg);
}

the in my element a div position inline styled relative and whithin the div a span with class vertical. 

<div style="width:100%;float:left;text-align:left;height: 80px;margin-left:25px;border-left:1px solid #000;height: 100px;font-size:12px;position:relative;"><span class="vertical" style="top:20px;">Articulo No.</span></div>

Hope it helps someone, saludos
