### ISSUE TITLE
Issue with html2canvas + gridster + edge

### ISSUE THREAD

**Issue by jarroda** [niklasvh/html2canvas#679]
When html2canvas is ran on a [gridster.js](http://gridster.net/) element that has the resize option enabled, the entire page reloads in Microsoft Edge.  Cue the 'edge case' joke, but this may be a major issue for my app.  Not sure if it is a bug in html2canvas or Edge.  Here is a fiddle that reproduces the issue for me. (Running Edge in Windows 10).

https://jsfiddle.net/7ybndo5L/61/

**Comment by owennewo** [comment]
I ran across the same issue.  It is not specific to gridster.  I don't think html2canvas claim support for edge but on the whole it works.  However if html2canvas is run on a page that has a div with a background-image that is an svg then Edge will currently crash.

I've raised a report with Microsoft Edge Team.
https://connect.microsoft.com/IE/Feedback/Details/1979758

The html2canvas developers may want to not process this type of element on Edge until the bug is fixed.  I've described a couple of workarounds on the Edge report above.

**Comment by owennewo** [comment]
If you can edit the page - then you might want to look at setting data-html2canvas-ignore="true" on this element.  This will cause html2canvas to ignore the element and I can confirm avoids the crash.  It is possible to do this for Edge only if you do some browser detection.

**Comment by jarroda** [comment]
So does SVG come into plan when html2canvas runs?  I'm not specifically using any SVG in my app.  

I just realized my example fiddle was broken since the html2canvas.js file had moved in the repo.  I have updated it and now it works again.  The background image here is just a jpg.

https://jsfiddle.net/7ybndo5L/61/

**Comment by owennewo** [comment]
gridster has added a span tag after the javascript called add_widget.  you can see it if you inspect the html elements.  That dynamic span has a class that has an svg on it.

.gs-resize-handle-both {
    width: 20px;
    height: 20px;
    bottom: -8px;
    right: -8px;
    background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/…yIDAgTCA2IDAgTCA2IDYgTCA2IDYgWiIgZmlsbD0iIzAwMDAwMCIvPg0JPC9nPg08L3N2Zz4=');
    background-position: top left;
    background-repeat: no-repeat;
    cursor: se-resize;
    z-index: 20;
}

I reckon there is a good chance that if you provide a custom style sheet that overides the gridster css it will no longer crash, e.g. untested css below.
.gs-resize-handle-both {
background-image: initial;
}

**Comment by jarroda** [comment]
Yep you're exactly right.  I just tried it and the issue is gone.  This workaround will work for us.  Thanks alot!.  

I'll close this issue since its not caused by html2canvas.
