### ISSUE TITLE
ios 8.12, iPad, empty canvas on larger pages 

### ISSUE THREAD

**Issue by ghost** [niklasvh/html2canvas#680]
No issues on Android or desktop browsers, but get empty canvas for larger pages on iPad with IOS 8.1.2.  Without setting height and width canvas.toDataUrl() only returns the data header with no base64 value.  However, if I set the height and width to 800X600, it does return a base64 image.  However the image is transparent.  

This is an excellent piece of work and I don't want to search for an alternative.  Is there anything I can do to help get this bug fixed?

**Comment by brcontainer** [comment]
Read this: http://stackoverflow.com/a/11585939/1518921

-------------

Possible duplica from:
- https://github.com/niklasvh/html2canvas/issues/394
- https://github.com/niklasvh/html2canvas/issues/183
- https://github.com/niklasvh/html2canvas/issues/331
