### ISSUE TITLE
html2canvas triggers refresh button

### ISSUE THREAD

**Issue by defbug** [niklasvh/html2canvas#681]
Everytime html2canvas is called the refresh button in the browser triggers. It does not refresh the page but it triggers the button like when you click on it. Why is this happening?

Thanks,

**Comment by brcontainer** [comment]
jsfiddle example please?

**Comment by cbranje** [comment]
This is happening with me as well.

**Comment by cbranje** [comment]
The following code make the refresh button flicker.

`<!DOCTYPE html>
<html>
  <head>
  <script type="text/javascript" src="dist/jquery.js"></script>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style>
      .feedback-overlay-black{
        background-color:#000;
        opacity:0.5;
        position:absolute;
        top:0;
        left:0;
        width:100%;
        height:100%;
        margin:0;
      }

    </style>

    <style>
      div{
        padding:20px;
        margin:0 auto;
        border:5px solid black;
      }

      h1{
        border-bottom:2px solid white;
      }

      h2{
        background: #efefef;
        padding:10px;
      }


    </style>
  </head>
  <body>
    <div style="background:red;">
      <div style="background:green;">
        <div style="background:blue;border-color:white;">
          <div style="background:yellow;"><div style="background:orange;"><h1>Heading</h1>
              Text that isn't wrapped in anything.
              <p>Followed by some text wrapped in a <b>&lt;p&gt; paragraph.</b> </p>
              Maybe add a <a href="#">link</a> or a different style of <a href="#" style="background:white;" id="highlight">link with a highlight</a>.
              <hr />
              <h2>More content</h2>
              <div style="width:10px;height:10px;border-width:10px;padding:0;">a</div>
            </div></div>

        </div>

      </div>
    </div>
    <script type="text/javascript" src="dist/html2canvas.js"></script>
    <script type="text/javascript">
	var timecode = 0;
	setInterval(captureScreen, 1000);
	
	function captureScreen() {
   		timecode = timecode + 500;
		
        html2canvas(document.body).then(function(canvas) {
            //document.body.appendChild(canvas);
			
			var dataURL = canvas.toDataURL();
			
			$.ajax(
			{
				  type: "POST",
				  url: "uploadCanvas.php",
				  timecode: timecode,
				  data: { 
					 imgBase64: dataURL
				  }
				  
				}).done(function( data) {
				  console.log(data); 
				  // If you want the file to be visible in the browser 
				  // - please modify the callback in javascript. All you
				  // need is to return the url to the file, you just saved 
				  // and than put the image in your browser.
				});
        	});
	
	}
	
    </script>
  </body>
</html>`

**Comment by muhammet** [comment]
+1 same problem

**Comment by brcontainer** [comment]
@defbug  @muhammet html2canvas creates an iframe, which is used to work the gift, the refresh button seems to shoot, but in fact the only thing making this load is the iframe, this does not affect at all page functionality.
