### ISSUE TITLE
Problems with Diagonal Background

### ISSUE THREAD

**Issue by stefanoschrs** [niklasvh/html2canvas#682]
Hello I am trying to print a page with diagonal background using the :before trick but the canvas won't render that

the html looks like this:
![selection_003](https://cloud.githubusercontent.com/assets/4215699/10077173/d5e3de18-62e7-11e5-92d0-c6b3291c9cfb.jpg)
but the rendered image looks like this:
![selection_002](https://cloud.githubusercontent.com/assets/4215699/10077148/bb1f5b02-62e7-11e5-9618-a8ddb8315516.jpg)

I tried to replicate the code in a CodePen
http://codepen.io/stefanoschrs/pen/EVgRVO

**Comment by brcontainer** [comment]
Possible duplicate from: https://github.com/niklasvh/html2canvas/issues/551
