### ISSUE TITLE
Tainted canvas in Safari with same origin images

### ISSUE THREAD

**Issue by rpmaps** [niklasvh/html2canvas#687]
I'm trying use html2canvas to render a div containing css layered png images into a printable canvas.  The user has the ability to toggle the various layers on/off and print the resultant view.  Works fine in Firefox, IE11, Chrome.   Safari will not render the image, even if I try a single png image local to the html page.  Trying to print in Safari return the following console output

Unable to get image data from canvas because the canvas has been tainted by cross-origin data.

I'm not using any cross-origin data as all files are local and tried setting allowTaint to true with no luck. Issue persists both locally and running off server.

Here is a sample of the <div> that I need to print:

div id="map-outer-wrap" class="map-outer-wrap"
                    div class="map-inner-wrap"
                        img class="map-layer-0" src="./images/708m-base.png" alt="base map" />
                        img class="map-layer-1" src="./images/708m-red-burst.png" alt="British victory" />
                        img class="map-layer-2" src="./images/708m-british-retreat.png" alt="British retreat" />
                        img class="map-layer-3" src="./images/708m-british-advance.png" alt="British advance" />
                        img class="map-layer-4" src="./images/708m-british-troops.png" alt="British troops" />
                        img class="map-layer-5" src="./images/708m-american-troops.png" alt="American troops" />
                        img class="map-layer-6" src="./images/708m-american-retreat.png" alt="American retreat" />
                        img class="map-layer-7" src="./images/708m-american-advance.png" alt="American advance" />
        
                        <canvas id="colors-sketch" height="705px" width="950px"></canvas> 
                        <div id="draw-cover"></div>
                    </div> 
                    <div id="compass-rose">
                        <img id="compass-img" src="./images/708m-compass.png" alt="compass rose" />
                    </div> 
                </div> 

and print function:

function createCanvasToPrint(link) {
	var myImage; // the new image to be printed
	var printContent; // html content to be printed
	var printW; // new print window
	
     html2canvas($("#map-outer-wrap"), {
            onrendered: function(canvas) {
                // canvas is the final rendered <canvas> element
                myImage = canvas.toDataURL("image/png");
                //Print the rendered <canvas> element
                printContent = "<!DOCTYPE html>";
                printContent += "<html><head><title>" + mapTitle + "</title></head><body>";
                printContent += "<img src='"+myImage+"'/>";
                printContent += "</body></html>";
                printW = window.open();
                printW.document.write(printContent);
                printW.document.close();
                printW.focus();
                printW.print();
                printW.close();
            }
        });
}; // end createCanvasToPrint

**Comment by brcontainer** [comment]
Hi, Safari6, Safari7 or Safari8?

**Comment by rpmaps** [comment]
I"m getting same issue with Safari 6, 7, 8 and now 9.

**Comment by rpmaps** [comment]
I changed my html2canvas call to use the promise callback rather than onRendered: and have activated the logging option.  The log outputs that all images have been successfully loaded (tainted: null).  However when the Safari print dialog opens the image is the broken link icon instead of resultant canvas image (myImage = canvas.toDataURL("image/png")).  So now I'm not sure if its a Safari issue rather than html2canvas.

**Comment by rpmaps** [comment]
Closing this issue.  Problem is with Safari needing time to render the content prior to printing, although elements outside of my target div are being rendered in my print output.  Found my answer in this post:
http://stackoverflow.com/questions/19678236/javascript-print-div-not-working-in-safari
