### ISSUE TITLE
No render button class from bootstrap

### ISSUE THREAD

**Issue by diturriza** [niklasvh/html2canvas#689]
I have a implementation using html2canvas for take screenshots to a form page. It has few buttons with bootstrap class (default).
![screenshot1](https://cloud.githubusercontent.com/assets/4779298/10263229/fdc5968c-69af-11e5-8bd4-e58254bed75c.png)

But when I take screenshot using html2canvas, return this:
![screenshot2](https://cloud.githubusercontent.com/assets/4779298/10263231/12750e46-69b0-11e5-8740-8fa32c61302e.png)

If you see, the style button has disappeared.

I have not idea but it happen with any button 

I hope you can help me from someone!

thanks!

**Comment by JuanPareles** [comment]
Hi! I have a similar issue, some buttons with boostrap styles looks fine but others looks just like the @diturriza 's image. Another issue is that the screenshot doesn’t take the rounded border of the buttons

Please help!

**Comment by brcontainer** [comment]
@diturriza @JuanPareles 

Note bootstrap uses advanced css features, but html2canvas don't support all features from css, read:
- https://github.com/niklasvh/html2canvas#browser-compatibility

**Comment by brcontainer** [comment]
**Duplicate from:**

- https://github.com/niklasvh/html2canvas/issues/172 (possible duplicate)
- https://github.com/niklasvh/html2canvas/issues/284 (possible duplicate)
- https://github.com/niklasvh/html2canvas/issues/538 (possible duplicate)

Read more: https://github.com/niklasvh/html2canvas/search?utf8=✓&q=linear-gradient&type=Issues
