### ISSUE TITLE
screenshot from external url

### ISSUE THREAD

**Issue by ucitelot** [niklasvh/html2canvas#690]
Like on the test
http://html2canvas.hertzen.com/screenshots.html

i cant make it working, can someone give me the code, 

thanks

**Comment by brcontainer** [comment]
@ucitelot
First call proxy by main url:

`http://yourwebsite/html2canvas.php?callback=CALLBACK_JAVASCRIPT&url=http%3A%2F%2Fwww.yahoo.com%2F`

Use `var websiteRenderFragment = document.createElementFragment` for "render" downloaded html and use like this:

```javascript
html2canvas(websiteRenderFragment, {
    "logging": true, //Enable log (use Web Console for get Errors and Warnings)
    "proxy":"http://mywebsite.com/html2canvasproxy.php"
}).done(function() {});
```

Go to http://stackoverflow.com and try open a question.

Good luck!

**Comment by ucitelot** [comment]
this return me 
http://localhost/html2canvas-php-proxy-master/html2canvasproxy.php?callback=CALLBACK_JAVASCRIPT&url=http://www.w3schools.com/html/html_iframe.asp

CALLBACK_JAVASCRIPT("http:\/\/localhost\/html2canvas-php-proxy-master\/images\/h2c_8cbbe60c9fa123d228c688b7088247ac5f70e1be
![iframe](https://cloud.githubusercontent.com/assets/182839/10375912/514eb118-6dfb-11e5-9dc2-f5fd718ba756.jpg)
.html");

how can i make like on the example with input field and to grab url from that field

can you help me with some code
thanks a lot

p.s. the output image its blank

**Comment by ucitelot** [comment]
here is nise example of external url
byt i couldnt make it working with html2canvasproxy.php
http://jsfiddle.net/RbY4E/

**Comment by shartoo** [comment]
Any avaible solution? Screenshot a external page with this repo?
