### ISSUE TITLE
SVG: offsets applied twice

### ISSUE THREAD

**Issue by nafur** [niklasvh/html2canvas#695]
I have SVGs that have a style with top (or left) and it seems that the offset is applied twice.

A working example can be found here: http://cipher-code.de/conceptmap/mwe.php

As you can see, the svg element is moved (50,50) by it's style attribute while the path element goes from (0,0) to (100,100). This is shown as expected by the browser.
When you use html2canvas however (click on Screenshot), you can see that the path is moved by another (50,50). This not only leads to incorrect positioning, but also to the path element being cropped.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by nafur** [comment]
It seems that I reused the referenced mwe.php file in the meantime for something else and I honestly do not remember what exactly this was about.

The screenshot method I used was this one: https://github.com/nafur/conceptmap/blob/b7d091c67fa33db5733973e4bcdb7eabdb3e7ad9/static/conceptmap.js#L165

**Comment by niklasvh** [comment]
Thanks for the reply! In that case, I'll close this for now. Feel free to open another issue if it is still relevant with 1.0.0
