### ISSUE TITLE
How can I save the image locally?

### ISSUE THREAD

**Issue by McFarts** [niklasvh/html2canvas#699]
For example, I'm using this plugin to do map overlays for my action rpg game:

![](https://i.gyazo.com/6b74bc3238e45ee0f74a07250538af8c.jpg)

It creates the map in the canvas

But I would like it to save it locally as a .png file instead of manually right clicking :)

code:

```
 var canvas = document.querySelector("canvas");
    var ctx = canvas.getContext("2d");

 

    document.querySelector("button").addEventListener("click", function() {
        html2canvas(document.querySelector("#content"), {canvas: canvas}).then(function(canvas) {
            console.log('Drew on the existing canvas');
			var ctx = canvas.getContext("2d");
console.log(ctx); // CanvasRenderingContext2D { ... 
        });
    }, false);

```

**Comment by niklasvh** [comment]
Save it where/how exactly?

**Comment by McFarts** [comment]
I'm an idiot, was thinking of something else. Sorry aobut this

**Comment by deadstar1** [comment]
@niklasvh how about saving the generated image on database?? is this possible?
