### ISSUE TITLE
Beta2: IE 11 'Promise' is undefined

### ISSUE THREAD

**Issue by Bart-Holland** [niklasvh/html2canvas#705]
html2canvas beta2 seems to work in FireFox, and even in chrome, but doesn't seem to work in IE.
When running I will get the error: "'Promise' is undefined"

The promise started here is in Line: 615, Column: 9

I tried rerunning the the npm install and the grunt but this didn't work.
I can't seem to find where to resolve this in the code. It does seem that alpha1 does work with this promise (but not with other things I seem to need which are in beta2) 

regards,

Bart

**Comment by niklasvh** [comment]
As mentioned in the readme, to support browsers without native `Promise` support, you'll need to include some `Promise` polyfill before including `html2canvas`. The reason html2canvas doesn't bundle one by default is that many applications might not need one and the type of Promise polyfill that gets included should be left up to the application.
