### ISSUE TITLE
Dist files missing in prereleases.

### ISSUE THREAD

**Issue by akovalyov** [niklasvh/html2canvas#706]
The last release with dist files was [0.5.0-alpha1](https://github.com/niklasvh/html2canvas/releases/tag/0.5.0-alpha1)
All next releases ([0.5.0-alpha2](https://github.com/niklasvh/html2canvas/releases/tag/0.5.0-alpha2), [v0.5.0-beta1](https://github.com/niklasvh/html2canvas/releases/tag/v0.5.0-beta1), [v0.5.0-beta2](https://github.com/niklasvh/html2canvas/releases/tag/v0.5.0-beta2)) miss it.

**Comment by usmonster** [comment]
See also #711.

**Comment by niklasvh** [comment]
Re-added them for now https://github.com/niklasvh/html2canvas/commit/47a7240d6b0c804b0783ed41469abdc313ce0139
