### ISSUE TITLE
Are external images still not supported?

### ISSUE THREAD

**Issue by braisNQ** [niklasvh/html2canvas#707]
Hi,
I saw you made several pushes in last days, and while i was reading last issues i saw you saying that you haven't updated the documentation.

Is it possible that external images are now supported but not documented? (i hope so)
In case they aren't, is there any JS proxy I could use for the proxy parameter in html2canvas() ?

thanks!

**Comment by niklasvh** [comment]
External images that are cors enabled or loaded through proxy work as before
