### ISSUE TITLE
Can't get main file with bower (dist/html2canvas.js)

### ISSUE THREAD

**Issue by driver-by** [niklasvh/html2canvas#710]
This happens because 'dist' directory was excluded from git

**Comment by driver-by** [comment]
P.S. Relative to v0.5

**Comment by akovalyov** [comment]
@driver-by I have already reported it in #706. Which means that more and more users hit this issue. 
@niklasvh could you take a look on it? It is pretty critical to have distributable files for beta testers before stable release is published.

**Comment by niklasvh** [comment]
Re-added them for now https://github.com/niklasvh/html2canvas/commit/47a7240d6b0c804b0783ed41469abdc313ce0139
