### ISSUE TITLE
External Images

### ISSUE THREAD

**Issue by spandzgit** [niklasvh/html2canvas#712]
I'm trying to load external images and get a snapshot using html2canvas but its failing.

Have tried both the options
1) useCORS: true
2) proxy: ...

The page at .... was allowed to display insecure content from .... 
cloneNode html2canvas.js:1638:108

TypeError: null is not an object (evaluating 'nodeList.length')

**Comment by brcontainer** [comment]
No offense, but this question has already been written here several times, do not use proxy and usecors the same time, or use one or other uses.

This message sounds like an issue with a page tried use resources without ssl in a page with ssl (or the opposite)

> was allowed to display insecure content from

See proxy list https://github.com/niklasvh/html2canvas/wiki/Proxies


**Duplicate from:**

- https://github.com/niklasvh/html2canvas/issues/205

**Comment by spandzgit** [comment]
thanks!
