### ISSUE TITLE
Cant get canvas correctly with style="float: left"

### ISSUE THREAD

**Issue by jimflo82** [niklasvh/html2canvas#714]
I have this primefaces panelgrid:

< p: panelGrid id="gpnl" columns="1" cellpadding="5" styleClass="panelGridCenter" style="float: left; display:block; text-align:center">
              < h: outputText value="#{movil.marca} #{movil.modelo}" />
< /p: panelGrid>

With html2canvas I get a canvas with no children, however when I delete float: left; it works correctly.

Any idea?

Thanks in advance.

**Comment by jimflo82** [comment]
Working OK with display: inline-block; instead float: left;

**Comment by brcontainer** [comment]
float: left work for me, your code is primefaces and not html, try get generated html and post in a jsfiddle example.

The example has to work and "demonstrate" the problem.
