### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object DOMException]     (No stack trace)

### ISSUE THREAD

**Issue by rofrol** [niklasvh/html2canvas#718]
I don't have a stacktrace when `IndexSizeError` occurs in IE11.

When catching:

```
promise.then(function(canvas) {
...
).catch(function(error) {
    console.log(error.stack);
}
```

I got `undefined`.

I'm not sure if it's bug in html2canvas or just IE throwing error without stack.

I'm using `html2canvas-0.5.0-beta2` and `bluebird-3.0.5`.

Here is some information about errors without stack http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error.

**Comment by brcontainer** [comment]
Hi, this is a problem with the size limitation by webbrowser and has already been discussed several times

**Duplicate from:**

- https://github.com/niklasvh/html2canvas/issues/331
- https://github.com/niklasvh/html2canvas/issues/625
- https://github.com/niklasvh/html2canvas/issues/183
- https://github.com/niklasvh/html2canvas/issues/680

**Comment by rofrol** [comment]
I know it was. What I'm talking about that there is no stack in the error returned, so it's hard to triage the bug. So I am wondering what is the cause that the stack is empty, html2canvas or IE?
