### ISSUE TITLE
html2canvas not renders angularjs gridster

### ISSUE THREAD

**Issue by konopiux** [niklasvh/html2canvas#721]
I have issue when I am trying to take screenshot of field where angular gridster is placed, I get it invisible. I van see all parent elements like forms and body but the space  where is gridster is empty.
This is gridster I am talking about: https://github.com/ManifestWebDesign/angular-gridster

What I expect.
![screen](https://cloud.githubusercontent.com/assets/13664971/11028690/0bb58300-86c1-11e5-8e80-a27edc4a5155.PNG)
What I get.
![screen2](https://cloud.githubusercontent.com/assets/13664971/11028693/0e57fb56-86c1-11e5-91c3-4c701f91697c.PNG)

Example: http://jsfiddle.net/s3229t77/10/

**Comment by konopiux** [comment]
anybody hear?

**Comment by deepender87** [comment]
@niklasvh I am facing the same issue. This is not capturing properly in case of gridster is being used. Please let me know how we can fix this?

**Comment by id1945** [comment]
I am also using angular-gridster2 and it is having the same problem as you.
It does not capture all the pictures on the screen

**Comment by anil957** [comment]
> Hi @konopiux @deepender87 I solved the problem by removing the transition. I added following css rule on the global scope:
> 
> .gridster-item { ` `transition: unset !important; }
> 
> Error => https://imgur.com/X0XskSZ Pass => https://imgur.com/LmoLWSV

i add css but It's not working

**Comment by messaoudi-mounir** [comment]
i add css but It's not working.
tested on html2canvas v1.3.2

Any help is welcome.

**Comment by Pooja-Khandelwal** [comment]
Is the issue resolved?
I am facing same issue when i upgraded my project from angular 6 to 9. 
Any help is much appreciated..

**Comment by anil957** [comment]
Hi Pooja,

for that iam using dom-to-image npm packages
