### ISSUE TITLE
New JS File

### ISSUE THREAD

**Issue by GertVen** [niklasvh/html2canvas#726]
Can somebody please give a link for the distribution JS files (the ones included within a software application) for the beta v0.5.0-beta2 version? There doesn't seem to be one in the current Git repository and I seem to be unable to build one myself.

Thanks!

**Comment by tbertran** [comment]
+1

**Comment by NPC** [comment]
I hope I am not breaking any spoken or unspoken rules, here are the dist files I built: http://ge.tt/8FMX52S2?c

**Comment by GertVen** [comment]
Thank you for the files NPC. Works beautifully in Chrome but having some trouble in IE. Crashes at the following code, saying "Promise" is undefined:

    return new Promise(function(resolve) {
        var documentClone = container.contentWindow.document;

        /* Chrome doesn't detect relative background-images assigned in inline <style> sheets when fetched through getComputedStyle
         if window url is about:blank, we can assign the url to current by writing onto the document
         */
        container.contentWindow.onload = container.onload = function() {
            var interval = setInterval(function() {
                if (documentClone.body.childNodes.length > 0) {
                    initNode(documentClone.documentElement);
                    clearInterval(interval);
                    if (options.type === "view") {
                        container.contentWindow.scrollTo(x, y);
                        if ((/(iPad|iPhone|iPod)/g).test(navigator.userAgent) && (container.contentWindow.scrollY !== y || container.contentWindow.scrollX !== x)) {
                            documentClone.documentElement.style.top = (-y) + "px";
                            documentClone.documentElement.style.left = (-x) + "px";
                            documentClone.documentElement.style.position = 'absolute';
                        }
                    }
                    resolve(container);
                }
            }, 50);
        };

        documentClone.open();
        documentClone.write("<!DOCTYPE html><html></html>");
        // Chrome scrolls the parent document for some reason after the write to the cloned window???
        restoreOwnerScroll(ownerDocument, x, y);
        documentClone.replaceChild(documentClone.adoptNode(documentElement), documentClone.documentElement);
        documentClone.close();
    });
};

**Comment by NPC** [comment]
GertVen, check out the usage instructions here: https://github.com/niklasvh/html2canvas#usage

Promise polyfill was dropped from the latest version, so you need to include an external polyfill (I use es6-promise, as suggested) for browser which don't have native Promise support (IE, yes).

**Comment by GertVen** [comment]
Thank you NPC, that got everything up and running

**Comment by arpittiwarigate6** [comment]
Hello, we are getting the same error as mentioned above on IE 10. Trying to include the es6-promise js before and after html2canvas.js also didn't helped (https://raw.githubusercontent.com/stefanpenner/es6-promise/master/dist/es6-promise.js)

Any more instructions on this issue ?
