### ISSUE TITLE
How to make the button that will trigger html2canvas?

### ISSUE THREAD

**Issue by kickthemooon** [niklasvh/html2canvas#728]
I was looking at the examples on the html2canvas homepage but I cannot understand how to make a button that triggers the screen capture
![html2canvasbutton](https://cloud.githubusercontent.com/assets/7913974/11151864/b2a0caf0-8a2f-11e5-89ba-a5cab02a71dc.jpg)
 like on the examples.

**Comment by NPC** [comment]
You can call html2canvas() function in the “click” event handler of the button.

**Comment by brcontainer** [comment]
Your problem is to learn javascript and not html2canvas, I recommend you start from the basic.

- https://www.codecademy.com/learn/javascript
- https://developer.mozilla.org/en-US/Learn/JavaScript

Here is dedicated to the exclusive html2canvas problems.
