### ISSUE TITLE
Rotate text not working

### ISSUE THREAD

**Issue by bhumiradixweb** [niklasvh/html2canvas#729]
When rotate text,its position changed so it is not displaying correctly. Sometimes not displaying in canvas.

```
-ms-transform: rotate(45deg); /* IE 9 */
-webkit-transform: rotate(45deg); /* Chrome, Safari, Opera */
transform: rotate(45deg);
```

Can you update your js as it is not supporting basic rotate functionality which is commonly required?

Thanks
Bhumi Shah

**Comment by sp00n** [comment]
Rotated images don't work either. Sometimes they don't show up at all, sometimes only part of the image renders where it should, it seems to be shifted from its original position.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
