### ISSUE TITLE
Not capturing the screenshot of div with large size images more than 20kb

### ISSUE THREAD

**Issue by vijaysaklani** [niklasvh/html2canvas#731]
It is working fine with the text but not working with the images.

**Comment by Grief89** [comment]
I try use html2canvas for leaflet.js, but all images is empty, also if I get one image of them

**Comment by jayantbh** [comment]
I'm not getting any images either. Don't know about the 20kb thing, I'm just not getting any images when trying to screenshot a tweet.

![stream-item-tweet-670397195221241856 2](https://cloud.githubusercontent.com/assets/7949047/11449388/2bfcd546-9599-11e5-9dcf-4f26870c2393.png)

**Comment by programmin1** [comment]
Are you sure those images can be grabbed, they are not cross-origin?

**Comment by jayantbh** [comment]
@programmin1 yeah, sorry about that. :| Fixed for me, was a CORS problem.

For anyone stumbled along here looking for the same problem as me, there's a useCORS parameter available:

```
html2canvas(tweet, {
    onrendered: function (canvas) {
        // do stuff
    },
    useCORS: true         
});
```

**Comment by salimazhar** [comment]
In file Html2Canvas.js on line 65 

Change following line from
 /* Highest positive signed 32-bit float value /
/maxInt = 2147483647, // aka. 0x7FFFFFFF or 2^31-1

to as Below
 maxInt = Number.MAX_VALUE,

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
