### ISSUE TITLE
IE 11 renders twice slower than Chrome, safari & Firefox

### ISSUE THREAD

**Issue by Rahmicc** [niklasvh/html2canvas#736]
We are exploring the possibilities of using html2canvas. However, when we test the library from http://html2canvas.hertzen.com/screenshots.html with "YAHOO" test page, IE renders very slowly where as CHROME and SAFARI renders in reasonable durations. In fact we observe the same slow behaviour in other URLs. We are using IE11.

Does anyone have the same slow rendering experience in IE? BR.

**Comment by bedrierol** [comment]
same slowness here . :(

**Comment by hisenberg1** [comment]
I am using beta 3 and it crashes on IE11.  Works perfect on Chrome.
Here is the error I get:
Unhandled exception at line 7, column 4550 in  html2canvas-0.5.0-beta3/dist/html2canvas.min.js?_=1450910397829

0x800a1391 - JavaScript runtime error: 'Promise' is undefined

**Comment by IanYates** [comment]
@hisenberg1  - you'll need to include a promise library / polyfill.

**Comment by martin-liu** [comment]
Very slow when there're lots of text
