### ISSUE TITLE
Image comes out unfinished in Chrome

### ISSUE THREAD

**Issue by Bialnsk** [niklasvh/html2canvas#737]
I'm using html2canvas version 0.4.1.

The image occasionally comes out like this
![like this](https://cloud.githubusercontent.com/assets/15880836/11374345/c2124c12-92bc-11e5-8a49-8ead47ea697f.png) on Chrome. Notice the blurred part at the bottom.

I thought it could be a problem with my application,  but it works perfectly on Firefox.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
