### ISSUE TITLE
HTML2CANVAS not working with large images ex. 200-300 kb

### ISSUE THREAD

**Issue by mzksol** [niklasvh/html2canvas#739]
I have 8-9 imgaes on my webpage of size 200-300 kb each. but HTML2CANVAS is not working with single image of this size. Please look into the matter.

My HTML Code is here(With script):
[design.txt](https://github.com/niklasvh/html2canvas/files/44623/design.txt)

**Comment by jokase** [comment]
@mzksol - Without a working demo of the bug it's difficult to understand what you mean by "is not working with single image of this size".

You should add your code to jsfiddle and get a working demo hosted there.
(like I have done for https://github.com/niklasvh/html2canvas/issues/748)

**Comment by peterchealse** [comment]
i have the same problem in ie10 when capturing a map where the size is big
