### ISSUE TITLE
border-radius on img tag doesn't render as expected

### ISSUE THREAD

**Issue by stormeyes** [niklasvh/html2canvas#744]
My code is following:

```
<!DOCTYPE html>
<html>
<head></head>
<body>
    <img src="my_local_img.jpg" style="border-radius: 50%;">
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.5.0-beta1/html2canvas.js"></script>
<script>
html2canvas(document.body, {
                  "logging": true,
                  "onrendered": function(canvas) {
                      var img = new Image();
                      img.onload = function() {
                          img.onload = null;
                          window.open(img.src)
                      };
                      img.onerror = function() {
                          img.onerror = null;
                          if(window.console.log) {
                              window.console.log("Not loaded image from canvas.toDataURL");
                          } else {
                              alert("Not loaded image from canvas.toDataURL");
                          }
                      };
                      img.src = canvas.toDataURL("image/png");
                  }
              });
</script>
</html>

```

original:

![image](https://cloud.githubusercontent.com/assets/5072174/11581430/e72db3c0-9a7c-11e5-99e1-cdb61945b8e8.png)

the result:
![image](https://cloud.githubusercontent.com/assets/5072174/11581445/087833ac-9a7d-11e5-99cc-b753df299400.png)

Is it a bug? how should i fix it?

**Comment by katfa** [comment]
Here's another example of a problem with `border-radius`.
The original:
![screen shot 2016-01-18 at 1 39 22 pm](https://cloud.githubusercontent.com/assets/1636583/12404388/fff0d112-bdef-11e5-9f6e-0dd3e4f24952.png)

The result in the PNG:
<img width="470" alt="screen shot 2016-01-18 at 2 30 53 pm" src="https://cloud.githubusercontent.com/assets/1636583/12404396/1a93347e-bdf0-11e5-9711-f010c3193a69.png">

**Comment by Suresh-Baskaran** [comment]
I am also facing the above mentioned problem. Is this issue fixed?

**Comment by stormeyes** [comment]
@Suresh-Baskaran Nope. I gave up finally

**Comment by Suresh-Baskaran** [comment]
Hi   Mr.Niklasch

                     I am using html2Canvas to convert div to image in my project,I am using border-radius:50 here,In browser output comes  exactly
But while exporting I get below issue.

In Brower

[cid:image002.png@01D19A52.4D37E6C0]
In Export Image:

[cid:image001.png@01D19A51.4A635F70]

Kindly advise me how to solve this issue.

Thanks in advance
Suresh Baskaran

**Comment by katfa** [comment]
We ended up not using this library.

**Comment by reddyabhishek** [comment]
Increase the border-radius value to a point where you get desired results. I once had to put 120% for a circle.

**Comment by jagannathswi** [comment]
In my case, it fixed with border-radius 70%.
