### ISSUE TITLE
map image position change

### ISSUE THREAD

**Issue by sajid-verveba** [niklasvh/html2canvas#746]
I have used this lib & loved it.
Its working great but only one problem i am facing, When i convert my html to canvas  it converts but
map showing as half & map image shifted lo little right. Please check in map1.png

![map1](https://cloud.githubusercontent.com/assets/11550366/11679120/136e6182-9e74-11e5-812c-38528ac0f6c1.png)

On my html page when i zoom it & converted to html2canvas then again one problem  occurred.
Please check map2.png

![map2](https://cloud.githubusercontent.com/assets/11550366/11679121/137235f0-9e74-11e5-8e2f-449cd3bbc0e1.png)

**Comment by 404157386** [comment]
Same issue occurred...
my map is reference of ArcGIS API, but can't transfer to canvas correctly...
It always offsets right or left after i move or zoom my map, only works when the map first time loads.

**Comment by someoneHere** [comment]
@404157386 
I had the same issue again, can you tell me which version solved this problem?
