### ISSUE TITLE
scroll breaks html2canvas v0.5.0-beta3

### ISSUE THREAD

**Issue by jokase** [niklasvh/html2canvas#748]
See http://jsfiddle.net/8jv1qeu0/1/

1. scroll down the capture button
2. click.
3. The content of the canvas is clipped to what is visible in the current viewport.

**Comment by hisenberg1** [comment]
I am having the exact same issue.
I have a "button" that initiates the html2canvas and opens the image in a new windows.
When I place the button above the image, there is no need to scroll down.  The image in the windows is fine.
But if the button is below the image and I have to scroll down to it, then resulting image is clipped.  Actually, it shows a large transparent area above the image and shows only the top part of the image at the bottom of the window.

**Comment by finetype** [comment]
Experiencing this same issue, I've been going crazy for the last 45 minutes trying to figure this out. Just knowing I can put the button at the top of the page is good enough for now, I think, at least that's a way to 'fix' the output.

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/commit/3b49cba21cad12d756103ffa106cdeb903dbf8a0

**Comment by jokase** [comment]
@niklasvh - hi, but sorry - it doesn't appear to be fixed see http://jsfiddle.net/ec549yt3/2/

**Comment by sureshkoduri** [comment]
Hi, I have the same issue.

**Comment by zhangjunxia** [comment]
Hi, I also have the same issue. Do you  solve the problem?
