### ISSUE TITLE
warning in using webpack in 0.5.0-alpha

### ISSUE THREAD

**Issue by cht8687** [niklasvh/html2canvas#749]
I am using webpack. when import html2canvas, I got following warning:

WARNING in ./~/html2canvas/dist/html2canvas.js
Critical dependencies:
8: 484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get beter results.

**Comment by IAkumaI** [comment]
Yeah, same warning.

**Comment by brabadu** [comment]
It would be great if npm package had source code, not only prebuilt files. So we could `import` from the source with webpack

**Comment by basilfx** [comment]
Certainly not *the* solution, but I did the following:

- Create a local repository clone.
- Edit `.npmignore` and remove the line with `src/`.
- Edit `package.json` and change the `"main": "dist/html2canvas.js"` to `"main": "src/core.js"`.
- Install package using `npm install /path/to/repo`.

Until a better solution exists, this works for me. It silences the warnings and yields a better optimized bundle.

**Comment by brabadu** [comment]
Yeah, that's one way to fix it. It is not very handy for my build process though. I added `html2canvas` as `noParse` to webpack config file

```
module: {
        noParse: [/html2canvas/, ]
},
```
Hope this issue would be fixed so I could remove it.

**Comment by uriklar** [comment]
@brabadu Thanks for the solution. Can I ask a question? 
How do you go about import html2canvas using es6 import syntax? Is it possible?

**Comment by brabadu** [comment]
@uriklar Sure, this works for me

```
import html2canvas from 'html2canvas';
html2canvas(document.body).then(...)
```

**Comment by uriklar** [comment]
Indeed it works :-)  silly me, digging into source code instead of trying the obvious...
Thanks you very much!

**Comment by arufian** [comment]
As @basilfx said, the maintainers should declare the library index on their package.json. Since they published it on npm, they should treat the library as a module.

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/tree/v1.0.0
