### ISSUE TITLE
capture Googlemap not working in IE9, IE10....

### ISSUE THREAD

**Issue by cht8687** [niklasvh/html2canvas#750]
Working on all other browsers except for IE9, IE10...

IE9, IE10...
![capture](https://cloud.githubusercontent.com/assets/4587603/11781765/36e63b30-a2c0-11e5-8c5e-8e5d7ae7e65e.PNG)

IE11, Edge, Chrome, Firefox...

![capture2](https://cloud.githubusercontent.com/assets/4587603/11781697/ab15bedc-a2bf-11e5-8bd3-6e10a7dd4988.PNG)

version:`0.5.0-alpha`

```
window.html2canvas(googlemapDiv, {
    useCORS: true,
    onrendered: function(canvas) {
      const img = canvas.toDataURL("image/png");               
      base64Img = img;
      base64Img = base64Img.replace('data:image/png;base64,', '');
      resolve(base64Img);
    }
  });
```

**Comment by TehNrd** [comment]
IE 9 and 10 do not support CORS for images in canvas, http://caniuse.com/#feat=cors.

You will need to use a proxy if you want to support these browsers.
