### ISSUE TITLE
Text fileds and Table data is not rendering properly when using Html2canvas screen capture

### ISSUE THREAD

**Issue by NareshKumarManne** [niklasvh/html2canvas#751]
Hi,
Iam using Html2canvas.js for my screen capture. It is working fine for all the elements except for text fileds and table elements. The text fileds as well as table element alignments are missing in captured screen shot. Is there any solution to fix this issue.

**Comment by Kirancloudnix** [comment]
Same issue I'm facing, table with colspan not rendering

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
