### ISSUE TITLE
GUJARATI TEXT not recognise correctly in HTML TO CANVAS PROJECT

### ISSUE THREAD

**Issue by maktechwebsol** [niklasvh/html2canvas#752]
Dear Niklas Von Hertzen,

Your work is amazing for the beginners in this technology world. 

Salute to you for providing such help to the developers of current technology.

Thanking you. 

I go through your post on html2canvas project. Its worked fine. But there are small problems while Capture image in GUJARATI Language. Please Do needful to me to solve out this problems ASAP. 

I hope You give positive response. 

https://translate.google.com/#en/gu/Gujarati not work in your code.

https://translate.google.com/#en/gu/Gujarati work fine in other API like http://grabz.it & http://websnaps.co & http://www.browshot.com

**Comment by srnthkp** [comment]
may be you are using a style 'text-align:center;' it wasn't working for me when I used it for other languages. You can use 'left' / 'right' .

**Comment by maktechwebsol** [comment]
Thanks for reply... @srnthkp #srnthkp

I applied as you told. But Still having issue with gujarati text.. 

Please check my link http://aaraxan.com/demo/

text not recognise well.. Please do needful

**Comment by maktechwebsol** [comment]
Thanks for reply... @srnthkp #srnthkp

I applied as you told. But Still having issue with gujarati text.. 

Please check my link http://www.aaraxan.com/demo/

text not recognise well.. Please do needful

**Comment by maktechwebsol** [comment]
Thanks for reply... @srnthkp 

Its worked fine.. Thanks a lot... Heartly thank you dude...

**Comment by srnthkp** [comment]
Cool ... :) :) I am glad that you tried it.. good luck.. :)

**Comment by maktechwebsol** [comment]
Dear @srnthkp  

Not work any more... I just tested on your example code. But still Not work.. Please help me to find out issue regarding this code.. Please see this link.. Its not work for me even I use text-align property 

http://www.aaraxan.com/demo/html2canvas-master/examples/demo2.html
![www aaraxan com demo html2canvas master examples demo2 html](https://cloud.githubusercontent.com/assets/16346237/12030034/e0b4c98e-ae1d-11e5-8988-cc888fc4ce29.png)
![2015-12-29 11-18-51](https://cloud.githubusercontent.com/assets/16346237/12030042/ffabf51a-ae1d-11e5-89bd-0eb8437620be.jpeg)

**Comment by maktechwebsol** [comment]
Dear @srnthkp <https://github.com/srnthkp>

Not work any more... I just tested on your example code. But still Not
work.. Please help me to find out issue regarding this code.. Please see
this link.. Its not work for me even I use text-align property

http://www.aaraxan.com/demo/html2canvas-master/examples/demo2.html

*Krunal Bhingradiya,*
*Web developer, Sec Inverse Lab*

**Comment by maktechwebsol** [comment]
Dear @srnthkp <https://github.com/srnthkp>

Not work any more... I just tested on your example code. But still Not
work.. Please help me to find out issue regarding this code.. Please see
this link.. Its not work for me even I use text-align property

http://www.aaraxan.com/demo/html2canvas-master/examples/demo2.html

**Comment by maktechwebsol** [comment]
Dear Sir, can you resolve problem?

*Krunal Bhingradiya,*
*Web developer, Sec Inverse Lab*

**Comment by srnthkp** [comment]
Hi,
Sorry for the delay, I have tried with your code
And i got it working. I copied your html and style. used the following code.

// put an outer div with id guj and a separate div that is outside guj with id image


![gujissue](https://cloud.githubusercontent.com/assets/16388816/12069838/b6cc3b42-b076-11e5-84d2-3ae7afb5c4f6.png)

html2canvas([document.getElementById('guj')], { 
        useCORS: true,
        onrendered: function (canvas) {
            var ctx = canvas.getContext('2d');

            ctx.imageSmoothingEnabled = false;
            ctx.mozImageSmoothingEnabled = false;
            var data = canvas.toDataURL('image/png');
            var image = new Image();
            image.src = data;
            //var img = document.createElement("a");

            //img.href = data;
            //img.download = "chart.png";
            //img.click();
            document.getElementById('image').appendChild(image);
        }
    });


Hope this finds an answer to you and pls don't call me sir !! :)

**Comment by maktechwebsol** [comment]
Dear Sir,

Thanks for your full affords to solve this issue. Still I face issue.. Not work for me.. 

I do as you say but cant work for me...

<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style>
      .feedback-overlay-black{
        background-color:#000;
        opacity:0.5;
        position:absolute;
        top:0;
        left:0;
        width:100%;
        height:100%;
        margin:0;
      }

    </style>

    <style>
      div{
        padding:20px;
        margin:0 auto;
        border:5px solid black;
      }

      h1{
        border-bottom:2px solid white;
      }

      h2{
        background: #efefef;
        padding:10px;
      }
    </style>
  </head>
  <body>
    <div id="guj" style="background:red;">
      <div style="background:green;">
        <div style="background:blue;border-color:white;">
            <div style="background:yellow;"><div style="background:orange;"><h1 style="text-align: left">મંગલ પરિણય</h1>
              મંગલ પરિણય
              
            </div></div>

        </div>

      </div>
    </div>
      <div id="image"></div>
    <script type="text/javascript" src="../dist/html2canvas.js"></script>
    <script type="text/javascript">
        html2canvas([document.getElementById('guj')], { 
        useCORS: true,
        onrendered: function (canvas) {
        var ctx = canvas.getContext('2d');

        ctx.imageSmoothingEnabled = false;
        ctx.mozImageSmoothingEnabled = false;
        var data = canvas.toDataURL('image/png');
        var image = new Image();
        image.src = data;
        //var img = document.createElement("a");

        //img.href = data;
        //img.download = "chart.png";
        //img.click();
        document.getElementById('image').appendChild(image);
    }
});
    </script>
  </body>
</html>


Can you give me full simple 1 page Gujarati text example?

**Comment by maktechwebsol** [comment]
Dear Sir,

Thanks for your full affords to solve this issue. Still I face issue.. Not work for me..

I do as you say but cant work for me...

Please can you send me Working example with gujarati text code?
