### ISSUE TITLE
Crashes on IE11

### ISSUE THREAD

**Issue by hisenberg1** [niklasvh/html2canvas#753]
I am using beta 3 and it crashes on IE11.  Works perfect on Chrome.
Here is the error I get:
Unhandled exception at line 7, column 4550 in  html2canvas-0.5.0-beta3/dist/html2canvas.min.js?_=1450910397829

0x800a1391 - JavaScript runtime error: 'Promise' is undefined

**Comment by IanYates** [comment]
@hisenberg1  - you'll need to include a promise library / polyfill.
