### ISSUE TITLE
Error on require/usage

### ISSUE THREAD

**Issue by Industrial** [niklasvh/html2canvas#755]
```
Error: Cannot find module './log' from '/home/tom/Code/myproject/node_modules/html2canvas/dist'
```

**Comment by Industrial** [comment]
Seems this library does not work with browserify. Even if I load the file manually in the index.html ...

**Comment by mqklin** [comment]
+1

**Comment by niklasvh** [comment]
RequireJS should be fixed with https://github.com/niklasvh/html2canvas/commit/4ebe9c5fcca8fbdb411f7d03c17b8212866fc1ab and https://github.com/niklasvh/html2canvas/commit/a4aa0c64447e3ad5298783da2a8511d537892bf2

Let me know if you run into any more issues with using html2canvas with requirejs.
