### ISSUE TITLE
<td> border rendering issue / border collapse

### ISSUE THREAD

**Issue by turigeza** [niklasvh/html2canvas#756]
Hi There,

Thank you for the effort you put into the project.

I come across with a very basic table rendering issue where column collapse is not behaving as expected  or maybe the border calculation is wrong.

There are two files which should work if you download them into a folder.
https://drive.google.com/folderview?id=0B7VdYIkRLxQWU2daS2Rob2lxcms&usp=sharing

Basic issue explained in images:

This is what it looks like as html:
<img width="419" alt="nativescreenshot" src="https://cloud.githubusercontent.com/assets/9335740/12080449/4f89302e-b252-11e5-8a09-0dae94915bd7.png">

And this is how html2canvas renders the html
![renderedimage](https://cloud.githubusercontent.com/assets/9335740/12080457/812595a0-b252-11e5-99e3-a76be4caa2c0.png)

Thank you!

All best,

Geza

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by fancsali** [comment]
Still present, please see #1777...

**Comment by davinma** [comment]
see #2194
