### ISSUE TITLE
Is there no support for -webkit-text-stroke 

### ISSUE THREAD

**Issue by premreddyn** [niklasvh/html2canvas#759]
I like html2canvas.But it looks like it's not supporting text stroke.Is there any way i could find a solution for this?

**Comment by nnootens** [comment]
Is there support or a solution for including the -webkit-text-stroke in the screenshot that html2canvas takes?

**Comment by ivictbor** [comment]
Thanks a lot @arzynik , I've published your branch to npm: https://www.npmjs.com/package/html2canvas-stroke , it unblocked https://github.com/devforth/painterro text-stroke feature (though html2canvas-stroke is very updated, probably someone has time capacity to merge a new changes or needs this, poke me)

**Comment by KupinFB** [comment]
Hey, I forked the branch 1.0.0-rc.7 and implemented -webkit-text-stroke-width, -webkit-text-stroke-color, paint-order supporting (based on https://github.com/niklasvh/html2canvas/pull/1540).
Link: https://github.com/KupinFB/html2canvas
Also I've published it to be able to use.
Link: https://www.npmjs.com/package/html2canvas-stroke2
Can i keep it?
