### ISSUE TITLE
It does not work with NodeJs 0.12.7

### ISSUE THREAD

**Issue by mikeyjm145** [niklasvh/html2canvas#767]
This does not seem to work in node 0.12.7 even though I downloaded with npm install and required "html2canvas" into my application. It does not recognize html2canvas variable in my js files.

**Comment by EriksKlotins** [comment]
more details needed. What exactly you are trying to do?

html2canvas uses DOM to render the image, however node.js is DOMless. Or am I wrong?

**Comment by mikeyjm145** [comment]
You are right. I need to close this issue. Sorry for bothering you.
