### ISSUE TITLE
Googles Street View Capture not working on Chrome

### ISSUE THREAD

**Issue by madhu-lemosys** [niklasvh/html2canvas#769]
I am trying to capture google street view, works well on Firefox but not working on chrome. 

I tried the same code on default map view and it is working. Can you help out, below is my code.

``` javascript
function capture(){
   jQuery('#location_image_before').val('');
   jQuery('#mapcanvas').html('<i class="fa fa-spinner fa-3x fa-spin"></i>');
   jQuery('#btnFormSubmit').attr('disabled',true);
   html2canvas(jQuery('#map'), {
      useCORS: true,
      onrendered: function(canvas) {
         jQuery('#btnFormSubmit').attr('disabled',false);
         var canvasURL = canvas.toDataURL("image/jpeg");       
         jQuery('#location_image_before').val(canvasURL);
         var mapcanvasImage = jQuery('<img />',{
            src: canvasURL,
            class: 'img-responsive'
         });
         jQuery('#mapcanvas').html(mapcanvasImage);
         jQuery('#btnCaptureImage').html('<i class="fa fa-camera"></i> Image Captured');
      }
   });
}
```

**Comment by cht8687** [comment]
When you initialize the streetview, add 'html4' mode, will solve the issue for Chrome:

     panorama = new google.maps.StreetViewPanorama(
      document.getElementById('street-view'),
      {
        position: {lat: 37.869260, lng: -122.254811},
        pov: {heading: 165, pitch: 0},
        zoom: 1,
        mode : "html4",
      });
