### ISSUE TITLE
RequireJS Issue

### ISSUE THREAD

**Issue by mikejr83** [niklasvh/html2canvas#770]
In beta2, when using the module loaded with RequireJS the following code is run:

    window.html2canvas.logging

Since it was loaded as a module ````window.html2canvas```` is undefined which causes a bad error when looking for the ````logging```` method.

I found this line twice in the minified code. I'll see if I can do a pull of the repository and fix the issue.

**Comment by finetype** [comment]
Did removing that line from the minified code fix the issue?

**Comment by sumt-mgardner** [comment]
I haven't checked. I wanted the code to still be there, but I need to figure out how to "require" that logging module. We're right at the end of a release cycle so I may not be able to get that much work other than trying removing the line till we have some free time.

Thanks for the tip! I'll try to remove the line tomorrow and post the results.

**Comment by finetype** [comment]
Let me know, I'm working on this same issue today for production code where I'm at. We use requireJS, would be nice not to have to hotload this in there and break convention!

**Comment by niklasvh** [comment]
This issue has been fixed in https://github.com/niklasvh/html2canvas/commit/4ebe9c5fcca8fbdb411f7d03c17b8212866fc1ab. Let me know if you are still facing issues with using the lib with requirejs
