### ISSUE TITLE
multiline text background-color is not working properly.

### ISSUE THREAD

**Issue by premreddyn** [niklasvh/html2canvas#771]
Getting the text-background-color for this multi-line text is not properly rendering.The problem is if there are two lines with span background-color then if first line is longer than second line.It comes like this.
![lyq7z](https://cloud.githubusercontent.com/assets/5550542/12441271/5c610bb6-bf6b-11e5-83aa-0f702f656138.jpg)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
