### ISSUE TITLE
Incorrect image captured when the page is scrolled (only for some pages) - Need help for debugging.

### ISSUE THREAD

**Issue by skadali** [niklasvh/html2canvas#772]
Hi All,

I have been trying to take screenshot for our home page. The image is captured correctly when there is no page scrolling. Here is the captured image:

![home1](https://cloud.githubusercontent.com/assets/15055129/12464742/56f03706-bf7f-11e5-9c8b-5c8ae9a0087c.png)

But once the page is scrolled, the image is not captured correctly, It mixes the tiles on the page. Here is the captured image:

![home2](https://cloud.githubusercontent.com/assets/15055129/12464889/40b732fe-bf80-11e5-9fef-38a726185a5b.png)

But the image captured should as follows:

![correctimage](https://cloud.githubusercontent.com/assets/15055129/12465331/5b3353fe-bf82-11e5-8937-d2fac0b8a962.png)

I have tried other webpages with page scrolling, and all of them are captured correctly with the page scroll.

I have tried to debug the code. 

I see that in the method initNode node.scrollTop and node.scrollLeft is assigned correctly (example node.scrollTop = 150, node.scrollLeft = 0). 

function initNode(node) {
    if (node.nodeType === 1) {
        node.scrollTop = node._scrollTop;
        node.scrollLeft = node._scrollLeft;

```
    var child = node.firstChild;
    while(child) {
        initNode(child);
        child = child.nextSibling;
    }
}
```

}

Can you please help me debug through the code. I am not able to understand how the dom elements only displayed on the page (i.e viewport) is rendered, Is there any specific method I need to debug, I tried to put breakpoint on the method NodeParser.prototype.paintElement, I see that all the dom elements are painted using that method, whether they are displayed on the viewport or not. I am using the latest version beta3.

Regards,
Sri

**Comment by skadali** [comment]
@usmonster @niklasvh can you please help me with this? I am trying to debug the code, I need some pointers on where to look in the code that builds the current viewport dom elements. As I mention, it works in other web pages with tables etc after page scrolling, Only for this particular page, it is not working, It works when the page is not scrolled, but once the page is scrolled to a particular scrollTop position, then the image capture is messed up. Is there any particular method I could debug, Any pointers on this, trying to understand how it is programmed. Thank you for all your work.

**Comment by niklasvh** [comment]
@skadali Please take a look if https://github.com/niklasvh/html2canvas/commit/3b49cba21cad12d756103ffa106cdeb903dbf8a0 fixed the issue for you. If not, please provide a minimal test example on jsfiddle

**Comment by skadali** [comment]
@niklasvh it didn't fix the issue for me. The tiles shown is that above example uses absolute position, and each tile is a div that uses style transform. The first tile has style transform: translate3d(0px, 0px, 0px); second tile has transform translate3d(192px, 0px, 0px), third tile in the row will have translate3d(300px, 0px, 0px) and so on.

When there is no scrolling, image is captured correctly, i.e. renderer.canvas returns the canvas correctly, then the crop function gets called. 

In the above case, renderer.canvas itself is not returned correctly i.e. even before the crop function is called. It somehow displays the first tiles correctly on scrolling, but the rest of the tiles with translate3d(192px,0px,0px) etc are not displayed, instead the tiles from the previous divs are displayed. 

I am using framework i.e SAP UI5 that generated the above html code, so it might be difficult to give a test example on jsfiddle, but I thought I might get some pointers on debugging the code if you can point me in the right direction. But will try to create an example.

**Comment by skadali** [comment]
@niklasvh 
I have created test examples on jsfiddle.
Here is the example where scrolling is not captured at all. The screenshot is captured from the top of the page even with the page scrolling
Here id="viewPortContainer" has style transform:translateX(-52%)
id="leftViewPort" display is block
id="rightViewPort" display is block

https://jsfiddle.net/skadali/bqn7hwad/4/

Here is another example of same web page where scrolling is captured but content is mixed up. I had to change the above original css styles from our web page as below to make the scrolling work in most of our other pages, but the only page that doesn't work with this hack is this below page with the tiles.
Here is the diff in styles from the above example:
id="viewPortContainer" has style transform:none
id="leftViewPort" display:none
id="rightViewPort" display:none
https://jsfiddle.net/skadali/aovLqamp/

Without scrolling, every page is working for our web app. 

Please let me know if you need more information.

Regards,
Sri

**Comment by skadali** [comment]
@niklasvh @usmonster 
I have provided the test example as requested. Did you have a chance to look into this?
Thanks for your help.

**Comment by skadali** [comment]
@niklasvh @usmonster can you please provide your inputs on this?

**Comment by skadali** [comment]
@niklasvh @usmonster @brcontainer I am waiting since long time. Any update on this? Just wanted to know if any one looking into this? 

Thanks.
Sri

**Comment by zhangya5847** [comment]
I have the same problem.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
