### ISSUE TITLE
change log doesn't reflect current version

### ISSUE THREAD

**Issue by finetype** [niklasvh/html2canvas#773]
latest version discussed on changelog is 0.5.0 alpha 2, but you guys are on beta 3. Keep us up to date, yo! Some of us are hanging on the edge of our seats for the latest changes. Hard to get involved or use the new stuff if we don't know about it!

Thanks for all the code, just make sure to tell me about it! :)

:+1: 

(As for me personally: looking for use of require.js/amd compatibility. See something mentioned about browserify... also I have the 'must be scrolled to top when function runs' glitch going on.)

**Comment by niklasvh** [comment]
Updated the changelog https://github.com/niklasvh/html2canvas/commit/3c7c3ddf605d760b68a62f4d9703fee2ea8bafee

Both the requirejs/scroll issue should be fixed as well.

**Comment by finetype** [comment]
Nice! Thanks!
