### ISSUE TITLE
html2canvas-beta-4 not capturing entire screen

### ISSUE THREAD

**Issue by matthew-rister** [niklasvh/html2canvas#774]
I'm been noticing consistent issues (in html2canvas 0.5-beta versions) with screenshot capturing when the page is very long vertically. What appears to happening is that only the portion of the page which is actually within range of the viewport is captured while the rest is cut off.

**Comment by finetype** [comment]
You might try making sure the page is scrolled to the top when calling html2canvas. I have this problem if I put the button at the bottom of the page, but if the button is at the top of the page and the user is scrolled up, all of the page is captured.

**Comment by TheJson** [comment]
I'm using the html2canvas v.0.5.0-beta4 so I don't understand because not capturing full view. It capture only window size. Did you found a solution? Thanks
