### ISSUE TITLE
Multi-column Layout rendering

### ISSUE THREAD

**Issue by huliciou** [niklasvh/html2canvas#776]
Hi~

I encountered a  problem with rendering a DIV with  multi-column layout to canvas....

especially  when setting background-color for some text  and  these text exactly step cross  columns.

like picture below...

the first  is the original DIV

and the second is  the canvas from the above DIV

it doesn't  render correctly.....

thanks very  much

![original](https://cloud.githubusercontent.com/assets/15030587/12572134/324ad2e6-c423-11e5-8346-90f6ec0cd8fd.PNG)
![2canvas](https://cloud.githubusercontent.com/assets/15030587/12572135/3b62e65c-c423-11e5-8e3f-a5fa9419e5a3.PNG)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
