### ISSUE TITLE
dist/html2canvas.min.js says it is still version beta-3, not 4... has it been updated?

### ISSUE THREAD

**Issue by finetype** [niklasvh/html2canvas#780]
/*
  html2canvas 0.5.0-beta3 http://html2canvas.hertzen.com
  Copyright (c) 2016 Niklas von Hertzen

  Released under  License
*/

is the header on the current minified dist file. Is it wrong, or has it not been updated?

Same for the non minified file...

**Comment by niklasvh** [comment]
The file is correct, header is wrong

**Comment by finetype** [comment]
thanks! figured, since it said updated 5 days ago, wanted to be sure though.
