### ISSUE TITLE
Allow left/top option

### ISSUE THREAD

**Issue by kodonnell** [niklasvh/html2canvas#781]
My use case: I'm trying to take a screenshot of the same aspect ratio, regardless of which screen it is being run on. I calculate the required screen dimensions (left, top, width, height), but html2canvas only seems to support the latter arguments - i.e. it always "crops" starting from left = 0 and top = 0. Given the code in core.js seems to support left/top arguments, could we add support for providing left/top options?

**Comment by cht8687** [comment]
This will be extremely useful. I am currently trying to print a really giant div which exceeds canvas max supported size.
