### ISSUE TITLE
SVGElement.offsetWidth Warning in Chrome

### ISSUE THREAD

**Issue by thomasbird1984** [niklasvh/html2canvas#787]
I recently started receiving the following console warnings while using your plugin: 

<img width="452" alt="screen shot 2016-02-02 at 7 13 10 pm" src="https://cloud.githubusercontent.com/assets/1638025/12768875/1a897540-c9e1-11e5-955f-7f14497c9c08.png">

The code resulting in these warnings originates from `/src/Core.js` lines `162-163`. While this isn't a bug but an issue of supporting legacy code. It appears to only be an issue on Chrome

**Comment by Taxman972** [comment]
That will be an issue in Chrome 50 in April 2016.

**Comment by niklasvh** [comment]
html2canvas doesn't use offsetWidth on SVG's anymore.
