### ISSUE TITLE
SVG chart won't export correctly in IE 11

### ISSUE THREAD

**Issue by allenTP** [niklasvh/html2canvas#788]
I used html2canvas 0.5.0- beta3 to export svg chart. It does very well in Chrome, but I don't have same luck when I run it in IE11. the shape of the pie chart is totally off and some text is not on the right position.
I guess it still has a long way to go for IE. May I have any hint to get a solution for it?  If it is necessary, I could trace the html2canvas.js to try to find a solution for it. 
Thank you very much.

![wrongsvg_exporiet](https://cloud.githubusercontent.com/assets/5168282/12785182/3eb1cb3e-ca59-11e5-89f3-17eeef52d6b7.jpg)

Below is the pie chart svg code, I think the d attribute is not able to parse correctly.

`<svg xmlns="http://www.w3.org/2000/svg" width="358px" height="192">
<g>
    <g class="dimple-axis" style="font-family: sans-serif; font-size: 10px;" />
        <path class="dimple-series-0 dimple-pie dimple-ah3n2" 
               id="AH3N2____" 
               opacity="1" 
               fill="#f70c0c" 
               stroke="#f70c0c" 
               transform="translate(204 91)" 
               d="M 3.73517e-015 -61 A 61 61 0 1 1 -33.901 -50.7121 L 0 0 Z" />
        <path class="dimple-series-0 dimple-pie dimple-b" 
                id="B____" opacity="1" 
                fill="#008837" 
                stroke="#008837" 
                transform="translate(204 91)" 
                d="M -33.901 -50.7121 A 61 61 0 0 1 -3.51681 -60.8985 L 0 0 Z" />
        <path class="dimple-series-0 dimple-pie dimple-a-unk" 
                id="A-Unk____" 
                opacity="1" 
                fill="#ecf70c" 
                stroke="#ecf70c" 
                transform="translate(204 91)" 
                d="M -3.51681 -60.8985 A 61 61 0 0 1 -0.29774 -60.9993 L 0 0 Z" />
        <path class="dimple-series-0 dimple-pie dimple-ah1swine" 
                id="AH1SWINE____" 
                opacity="1" 
                fill="#ed9c11" 
                stroke="#ed9c11" 
                transform="translate(204 91)" 
                d="M -0.29774 -60.9993 A 61 61 0 0 1 -1.12055e-014 -61 L 0 0 Z" />
        <path class="dimple-series-0 dimple-pie dimple-ah1n1" 
                id="AH1N1____" 
                opacity="1" 
                fill="#200cf7" 
                stroke="#200cf7" 
                transform="translate(204 91)" 
                d="M -1.12055e-014 -61 A 61 61 0 0 1 -1.12055e-014 -61 L 0 0 Z" />
                /* legend code works fine, not show here */
    </g>
</g>
</svg>`

**Comment by bautistaaa** [comment]
have you found any workaround for this?
