### ISSUE TITLE
Won't render horizontal lines or vector symbols generated by katex.js

### ISSUE THREAD

**Issue by SirFizX** [niklasvh/html2canvas#789]
Most TeX commands rendered to HTML via katex.js result in proper canvas rendering via html2canvas.js with a notable exception of horizontal lines as in \frac{x}{y} which fails to render the horizontal line in the fraction as in the following example generated by <a href='http://jsdo.it/ELHS/katex2image' target='_blank'>this implementation</a>.

<img src='http://m14.imgup.net/ScreenShot2856.png'/>

Here is an HTML rendering using katex.js.

<img src='http://a58.imgup.net/ScreenShot46ea.png' />

Here is a canvas rendering using html2canvas.js via katex.js.

<img src='http://x43.imgup.net/ScreenShot554e.png' />

Here you can see the HTML encoding generated by katex.js for the TeX code \overline{a}.  Perhaps this reveals why the horizontal line is not being rendered in the canvas with html2canvas.js.

<img src='http://o06.imgup.net/ScreenShot4bb0.png' />

html2canvas.js also does not render vector symbols generated by katex.js.  Here you can see the HTML rendering and the canvas rendering below.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
