### ISSUE TITLE
Issue with printing when scrolled

### ISSUE THREAD

**Issue by blackmambahk** [niklasvh/html2canvas#790]
Using the latest dist. 

I am trying to print the whole document

If the window is scrolled when I print, the output image is missing the part of the window scrolled off the screen.

The only way I can see around it is top scrollTo(0,0) before printing and then back again after rendering is complete.

Although this works you get an ugly 'flash' as the window scroll to the top and back again. 

Is there a better way around this

Rob

**Comment by powerbot15** [comment]
I have the same issue. And when I tried to turn off the line `window.scrollTo(0, 0)` the library started to render empty images if area to capture is out of the visible part of screen

**Comment by mattwintercorn** [comment]
I've seen that a couple of people have been having this issue. I solved this by modifying the code to take into consideration the window.scrollTop or document.documentElement.scrollTop (for IE). I'll probably set up a pull request but here are my changes:

```
function posTop() {`
    return typeof window.pageYOffset != 'undefined' ? window.pageYOffset : document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop ? document.body.scrollTop : 0;
}

exports.getBounds = function(node) {
    if (node.getBoundingClientRect) {
        var clientRect = node.getBoundingClientRect();
        var width = node.offsetWidth == null ? clientRect.width : node.offsetWidth;
+        var offsetY = node.scrollTop || posTop() || node._scrollTop || 0.0;
+        var offsetX = node.scrollLeft || window.scrollX || node._scrollLeft || 0.0;
        return {
!          top: clientRect.top + offsetY,
!          bottom: (clientRect.bottom + offsetY) || (clientRect.top + clientRect.height + offsetY),
!          right: clientRect.left + offsetX + width,
!           left: clientRect.left + offsetX,
            width:  width,
            height: node.offsetHeight == null ? clientRect.height : node.offsetHeight
        };
    }
    return {};
};
```

**Comment by BrainFeeder** [comment]
I tried @mattwintercorn 's solution, It sure fixed position of all divs.. But the text still is out of position. 
![2016-11-18 12_58_54 feedback-5f84758e0f4e71d6748499635bce049e](https://cloud.githubusercontent.com/assets/4141465/20429492/4da103a2-ad8f-11e6-9d5a-4fb599a43b39.png)
