### ISSUE TITLE
Div gets cut

### ISSUE THREAD

**Issue by mathi1993** [niklasvh/html2canvas#793]
Hey guys,

i use the latest beta 4 Plugin and now the top of my div gets cut off if iit is not in the viewport.
If I use the alpha 1 plugin, this doesn't happen.

Thanks and regards,
Mathias

**Comment by michito** [comment]
I'm having the same problem.

**Comment by sbryfcz** [comment]
Same here....let me know if anyone finds a solution (besides using alpha 1)

**Comment by Flecket** [comment]
Always had the same problem, luckily a solution for mine was to scroll into view and then take the picture. Works well if the div isn't too high in the first place.

**Comment by mattwintercorn** [comment]
https://github.com/niklasvh/html2canvas/issues/790#issuecomment-221985352
