### ISSUE TITLE
doesn't support font-family property with multiple value

### ISSUE THREAD

**Issue by rayax86** [niklasvh/html2canvas#796]
Using 0.5.0-beta4, thanks so much for this great module!

The problem I am having is, say I have a class
`.class {
    font-family: "somefont", "Arial"
}`
where "somefont" doesn't apply, the end result is elements that are .class would be rendered using Arial in the page, but in the canvas the default font is applied instead.

Any idea?

**Comment by eZ0** [comment]
I'm having the same issue.

**Comment by eZ0** [comment]
I found the reason: parent of canvas has to have the font declaration like so:
`.container {
  font-family: Roboto, "Helvetica Neue", sans-serif;
}`

**Comment by jordan314** [comment]
The join/split in CanvasRenderer.prototype.font was stripping out additional fonts. I submitted a fix for it

**Comment by rsbondi** [comment]
I am not sure if this is related, but [here](http://plnkr.co/edit/cQH03OO02BFq8TaxXoNw?p=preview) I think I am seeing the font rendered correctly, but then layered over with an erroneous font?

**Comment by getJv** [comment]
@eZ0 you correct! Thank you!
 As you said, i put `font-family: arial` at canvas parent element and works!. 

Thank you! Thank you!

**Comment by faiq-sudoers** [comment]
Try make the text element like span, h1, h2 ... to display:block

**Comment by ruslankonev** [comment]
not work, I got the same error
![image](https://user-images.githubusercontent.com/2588730/46677010-5e51b900-cbea-11e8-94e2-3cc53a72cbde.png)

rendered by

```
html2canvas(this.$refs.iFr, { useCORS: true }).then(canvas => {
        console.log(canvas)

        document.body.appendChild(canvas)

        canvas.toBlob(function(blob) {
          saveAs(blob, 'Dashboard.png')
        })
      })
```

**Comment by camohub** [comment]
I have the same problem. You can fix it via clone callback and style it separately.

```
               onclone: (document) => {
                        document.querySelectorAll('.button span').forEach(element => {
                            element.style['font-family'] = 'sans-serif';
                        });
		}
```
