### ISSUE TITLE
Image to Canvas Issue

### ISSUE THREAD

**Issue by Anzak** [niklasvh/html2canvas#797]
I'm trying to use your library to convert an image from a mobile camera to a html canvas but the orientation of the exported image is incorrect. The photos are taken portrait but the data used to render the image seem to be landscape

I'm capturing the camera image using the following:
 <input id="cameraInput" name="originalImage" type="file" accept="image/*" capture="camera" onchange="handleFileSelected();">

Once the image is selected its loaded into an <img> tag  
...
function handleFileSelected() {
    var count = document.getElementById('cameraInput').files.length;
    if (count > 0){
        // Only interested in the first image
        var file = document.getElementById('cameraInput').files[0];
        // Use the file reader to get the data for an image object
        var reader = new FileReader();
        // Add an event listener for when it loads
        reader.onload = function (e) {
            // Update the camera image div with the actual object
            var cameraImageDiv = document.getElementById("cameraImage");
            cameraImageDiv.setAttribute('src', e.target.result);
        }
        // Begin the url read
        reader.readAsDataURL(file);
    }
}
...
<img id="cameraImage" class="img-responsive" onload="handleImageLoaded()"/>
...

I'm using a standard method to convert the div
...
    html2canvas($("#markupWrapper"), {
        onrendered: function(canvas) {
            $("#finalImageDiv").append(canvas);
        }
    });
...

The results - the original 
![69269dd7-103b-468e-a873-dcf2f657c758](https://cloud.githubusercontent.com/assets/771813/13062450/b6f80ce8-d436-11e5-93f0-d2086318562b.png)
- the canvas
  ![2797586a-4971-4b61-9c53-79c34ce5562c](https://cloud.githubusercontent.com/assets/771813/13062444/ae2ff5e4-d436-11e5-9e77-dd4c443ae540.png)

Could anyone let me know what I am doing wrong or is this a bug?

**Comment by Anzak** [comment]
Missed the code
`<input id="cameraInput" name="originalImage" type="file" accept="image/*" capture="camera" onchange="handleFileSelected();">`

`<img id="cameraImage" class="img-responsive" onload="handleImageLoaded()"/>`

**Comment by Anzak** [comment]
Also, this code works completely fine on a standard browser. Is there extra handling for mobile devices?

**Comment by emetselaar** [comment]
I seem to have orientation issues with camera use as well. Only on iOS BTW - on Android it works OK for me.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
