### ISSUE TITLE
not capturing entire screen shot & not proper

### ISSUE THREAD

**Issue by mukeshcp** [niklasvh/html2canvas#801]
Hi,
  When capturing  screen shot of Element div using html2canvas,not capturing entire screen shot & not proper.

  I am using iframe, html2canvas 0.5.0-alpha1 & applied transform:scale(1.15) to div Element.

  Please find attachments of screen shots: Original.png & issueswithpng.png
![original](https://cloud.githubusercontent.com/assets/12266888/13176222/645e31bc-d736-11e5-92f7-057270d25dba.png)
![issueswithpng](https://cloud.githubusercontent.com/assets/12266888/13176225/6d692bc2-d736-11e5-8628-de62dc83852b.png)

**Comment by mukeshcp** [comment]
Any update ont it?

**Comment by ainy2016** [comment]
Hi, i am facing the same issue on chrome any solution??

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
