### ISSUE TITLE
SVG offsetWidth, offsetHeight deprecated in Chrome

### ISSUE THREAD

**Issue by wowpages** [niklasvh/html2canvas#805]
I recently started getting these error notices in Chrome in the console:

`'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.   html2canvas.min.js:11`

Not sure how critical this is.

**Comment by omerRS** [comment]
Same here. Any plans of solving this before Chrome removes support?

**Comment by niklasvh** [comment]
Fixed in 1.0.0
