### ISSUE TITLE
Problem with Bootstrap Checkbox

### ISSUE THREAD

**Issue by mikeyaremenko** [niklasvh/html2canvas#806]
Hello,

I am using library https://github.com/flatlogic/awesome-bootstrap-checkbox for pretty checkboxes.
When I am rendering an image and saving it, then I have some problems with it.
![image](https://cloud.githubusercontent.com/assets/4247800/13221110/eafa45f4-d979-11e5-88bc-36bb7e2ed307.png)

Thank you in advance

**Comment by liuxd** [comment]
@mikeyaremenko 

Hello,

__I met the same problem.__

The real page is like this:
![real](https://cloud.githubusercontent.com/assets/678977/14490125/85268c90-01a3-11e6-8958-a58acaffc0f0.png)
But the screenshot is like this:
![screenshot](https://cloud.githubusercontent.com/assets/678977/14490136/9611eb62-01a3-11e6-8e58-2299541f13bf.png)

My Boostrap version is `v3.3.2`.

Have you got the solution?

Thanks.

**Comment by mikeyaremenko** [comment]
I did not manage to fix that bug with styles, because I decided just to
hide styles for pretty checkboxes before screenshot and return them
afterwards. It is not the best solution but it works.

Allen <notifications@github.com> schrieb am Mi., 13. Apr. 2016 um 12:17 Uhr:
