### ISSUE TITLE
Scale dom element does not effect result image

### ISSUE THREAD

**Issue by DQvsRA** [niklasvh/html2canvas#807]
Hello everyone :)
How can i scale and render dom element?
I need to scale html content to specific size, and fit it to screen (or container size).
I try this code, but the result image is not scaled. 
Please help me with that

```
  let div = $('<div>');
  div.html(html).width(300)
     .appendTo(document.body)
     .css({
        "transform":"scale(3,3)",
        "transform-origin":"top left"
     });

  let canvas = document.createElement("canvas");
  document.body.appendChild(canvas);

  html2canvas(div.get(0), {
     height: div.height(),
     width: div.width(),
     onrendered: function(canvas) {
        let dataURL = canvas.toDataURL();
        document.body.appendChild(canvas);
        //document.body.removeChild(div);
        //callback(dataURL);
     }
  });
```

**Comment by CallMeAnil** [comment]
Same issue here ...

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
