### ISSUE TITLE
Radial Gradient not working in background

### ISSUE THREAD

**Issue by kmkmehra** [niklasvh/html2canvas#808]
Hi there.

What a nice librairy!!

But I have a problem rendering radial gradient. I checked in the code and the case "radial-gradient" is actually missing.

I have to implement radial gradient there.

Any idea how to implement this?

**Comment by topwood** [comment]
+1

**Comment by VincentBlouin** [comment]
+1

**Comment by niklasvh** [comment]
Added in 1.0.0
