### ISSUE TITLE
beta version effects to designing portions on mouse hover in chrome

### ISSUE THREAD

**Issue by mukeshcp** [niklasvh/html2canvas#813]
Hi,

I am using v0.5.0 beta4. Its working in Mozilla. but not properly work in chrome (Version 48.0.2564.116 m). It effects to other designing portions on mouse hover.

Please help me  to work with chrome.

**Comment by ainy2016** [comment]
getting issue in rendering svg image's clipping too, in chrome 49.0. any help??

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
