### ISSUE TITLE
canvas.toDataURL() is not giving proper data in firefox 44.0.2

### ISSUE THREAD

**Issue by AishSenthil** [niklasvh/html2canvas#814]
Hi,am using html2canvas for taking screenshots along with sahi testing automation tool.In Chrome, am able to get the b64 data from canvas consistently.But in firefox , there is inconsistent behaviour of this b64 data - means , sometimes am able to see the full b64 data but sometimes , am just seeing a blank b64 data like "data:,".So am unable to get the image out of it.Am using javascript callback function of canvas to another function and am processing canvas data in that function scope.In certain websites like apple.com am getting security error(because of CORS) and tried using useCORS and allowtaint options but no luck.So please let me know if there is any solution to make the above said scenarios workable ?

**Comment by liujiusheng** [comment]
Your problem has been solved？

**Comment by ShirlyChan** [comment]
Your problem has been solved？ I got the same question.

**Comment by yrl** [comment]
I got the same question,please tell me,thank you.
