### ISSUE TITLE
Trying to print a div with svg panels

### ISSUE THREAD

**Issue by ohrlando** [niklasvh/html2canvas#815]
it returns a blank image, sometimes cutted. if I scroll and back to div, it gets me something, not right but something

![cutted](https://cloud.githubusercontent.com/assets/7155740/13529544/9425e8b6-e1fb-11e5-8ebe-6233b4b874e5.jpg)
![div-svgs](https://cloud.githubusercontent.com/assets/7155740/13529545/942d47dc-e1fb-11e5-810b-85b9b4107841.png)

**Comment by tamisy** [comment]
Hi
I have the same issue , do you find any solution ?

**Comment by ohrlando** [comment]
not yet

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
