### ISSUE TITLE
Rendering no content when window is scrolled

### ISSUE THREAD

**Issue by jimliang** [niklasvh/html2canvas#820]
Using the last dist to draw the one node when window is scrolled，
it print blank content.
I saw  https://github.com/niklasvh/html2canvas/commit/3b49cba21cad12d756103ffa106cdeb903dbf8a0
but it not fixed!

**Comment by stevenvegt** [comment]
I experience the same behaviour. Using v5-beta4 in combination with angularjs 1.3.x.

I'm trying out this lib and want to use it for signing contracts in a healthcare environment. Would be cool if we can use it to provide 'evidence' for the signature. Do you think we rather should use the stable v4 version, or can we expect bugfixes for this problem any time soon? Thanks!

**Comment by jimliang** [comment]
@stevenvegt  You can use `$(window).scrollTop(0)` to resolve this temporary.

**Comment by stevenvegt** [comment]
@jimliang Thanks, that's working :+1:

**Comment by mattwintercorn** [comment]
related to https://github.com/niklasvh/html2canvas/issues/790#issuecomment-221985352?

**Comment by mintplo** [comment]
I wrote comment why it happened.
Check #893

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by stevenvegt** [comment]
To be honest, we tried another approach, but really cool to see you picked up the project! I hope to use this lib in our support tool one day 👍

**Comment by BoleLee** [comment]
Temp Fix it by: `window.scrollTo({ top: 0 })` before rendering canvas
