### ISSUE TITLE
about Android problem

### ISSUE THREAD

**Issue by zhn4** [niklasvh/html2canvas#821]
It's my code

```
html2canvas(document.body, {
  onrendered: function(canvas) {
    document.body.appendChild(canvas);
    var dt = canvas.toDataURL('image/jpeg', 0.85);
    var test_image = document.createElement('img');
    test_image.src = dt;
    document.getElementById('box').insertAdjacentHTML('beforeend', '<img src="' + dt + '" alt="test-image" />');
  }
});
```

In Android, that image has big problem, top of the image will has a  black block.
In iPhone, no problem.
Why? It's Android BUG!?

**Comment by infeng** [comment]
i have same problem.in android, the image can not save in phone

**Comment by zhn4** [comment]
@infeng 在安卓手机情况下，其实主要问题是安卓手机的输入法问题，例如你需要生成的图片的区域需要输入文字，输入法会把截图区域顶上去，截图区域不在页面可视区域，所以生成的图片顶部会产生黑块。

解决思路是保持截图区域在页面可视区域内，我的解决办法是在生成截图的按钮上绑定一个页面滚到顶部的功能：
```html
<a href="javascript:scroll(0, 0);">生成截图</a>
```

**Comment by infeng** [comment]
@zhn4 我这边生成图片的区域是没有输入文字，而且是在页面可以区域内的

**Comment by QShengW** [comment]
i have same problem.in android, the image can not save in phone。 A whole picture is full of iPhone.

**Comment by qiupanfeng** [comment]
same problem
