### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by dijs** [niklasvh/html2canvas#826]
When i pass a node I get from `ReactDOM.findDOMNode` to html2canvas, I am getting a:

`Uncaught (in promise) TypeError: Cannot read property 'removeAttribute' of null(…`

Although, I did notice that for some reason, if I use it's node.parentNode, that works without!

Very odd, I would really like to be able to render my plain node.

**Comment by ouqinglai** [comment]
+1

**Comment by Qti3e** [comment]
Same error after (1 year + 1 day)!
Should I always append the node to main html document?

**Comment by jlag34** [comment]
@Qti3e  are you passing a ref to ReactDOM.findDOMNode()?

**Comment by Qti3e** [comment]
I don't use React, but I've got same error when I passed a dom that I did not appended to the document

I fixed this issue by adding a loading status to my program when I want to render a document I use a loading screen (position: fixed;top:0;left:0;right:0;bottom:0;) and then I append my dom to document, after rendering I remove both loading and the dom it self and save the result canvas.
