### ISSUE TITLE
linear-gradient 

### ISSUE THREAD

**Issue by czwanmmwhh** [niklasvh/html2canvas#827]
linear-gradient(90deg, rgba(242, 242, 242, 0) 0%, rgba(242, 242, 242, 1) 50%, rgba(242, 242, 242, 0) 100%)  
90deg  has not rendered

**Comment by mpcallahan** [comment]
No non-browser-specific gradients seem to work for me: https://jsfiddle.net/afL5ey7j/

**Comment by niklasvh** [comment]
Fixed in 1.0.0 https://jsfiddle.net/afL5ey7j/1/
