### ISSUE TITLE
Ruby Proxy - or generally, what should be included in the proxy's response?

### ISSUE THREAD

**Issue by pipbeard** [niklasvh/html2canvas#828]
Firstly, this library is awesome!

I'm working on a rails app that will use this to generate images that users can share. As with most use cases, I'm sure, I have a need for users to be able to include external images, so I'm using a proxy.

I can get all proxies that others have written to work, but I'd really like to keep my proxy internal to my rails app so I don't need to initiate another server just for the proxy.  

I've written this very simple module, which as far as I can tell returns the exact same JSONP string as any of the existing proxies that others have written (for Node.js, PHP or Python), and I'm setting headers to match on the rails controller that uses this module:

``` ruby
require 'base64'
require 'open-uri'
require 'json'

module ImageProxy
  def self.generate( url, callback = "callback" )

    data = {content: "", type: ""}
    file = open( url, 'r')

    if ( file )

      content_type = file.content_type

      if ( content_type == "image/jpeg" || content_type == "image/png" || content_type == "image/jpg" || content_type == "image/gif" )

        base64_data = Base64.encode64( file.read.chomp ).gsub("\n", "")
        data["content"] = base64_data
        data["type"] = content_type

      end
    end

    return "/**/ typeof #{callback} === 'function' && #{callback}(#{data.to_json});"
    #=> /**/ typeof callback = 'function' && callback({"content":"/9j/4AAQSkBase64String ... ", "type": "image/jpeg"});

  end
end
```

And here are the headers I'm setting on the controller.

``` ruby
response.headers['Access-Control-Max-Age'] = (5*60*60).to_s
response.headers['Access-Control-Allow-Origin'] = "*"
response.headers['Access-Control-Request-Method'] = "*"
response.headers['Access-Control-Allow-Methods'] = "OPTIONS, GET"
response.headers['Access-Control-Allow-Headers'] = "*"
response.headers['Connection'] = "keep-alive"
response.headers['Content-Type'] = "application/javascript"
```

However, it won't load the image.  I feel like I've ruled most other things out, but is it important that the proxy runs on a different port than the app? Anything sacred about :8082? Anything else I'm overlooking?

Really appreciate any feedback others can give, or in general details about what specific things need to be true in the response that html2canvas expects from the proxy.  Thanks!!

**Comment by unChaz** [comment]
Here's your controller method

`
require 'base64'
require 'net/http'

def proxy_image
   url = URI.parse(params[:url])
    image = Net::HTTP.get_response(url)
    render json: data_url(image).to_json, callback: params[:callback]
 end`
