### ISSUE TITLE
Textareas don't have user line breaks when screenshotted

### ISSUE THREAD

**Issue by marywilliamson** [niklasvh/html2canvas#83]
Hi -

If I put in text with returns in it, the screenshot doesn't contain the returns [just looks collapsed in a string with the carriage returns]. I lasted pulled this code a few [say 3] mos ago. Has that been fixed or is it still an issue?

**Comment by savokiss** [comment]
I‘ve found a solution here: http://stackoverflow.com/questions/22317823/html2canvas-remove-multiple-spaces-and-line-break
It use `<div contenteditable="true"></div>` to replace `textarea`.

But I use angular and I must find out the `ng-model` issue.

`UPD`
I found the solution about using `ng-model` on a `div' here: http://mehrantm.blogspot.com/2013/10/how-make-two-way-binding-to-your.html
Hope it can help someone~

**Comment by zhangshichun** [comment]
maybe we can only replace textarea to div before use html2canvas?and after that changge the div back

**Comment by rafaelpereira97** [comment]
I solved this problem by using this function: 

            $('textarea').each(function() {
                if(!$(this).hasClass('d-none')){
                    $(this).replaceWith("<div contenteditable=\"true\">"+$(this).html()+"</div>")
                }
            });

Paste the function before call html2canvas and your problem will by solved :)
