### ISSUE TITLE
 Promise is not a constructor

### ISSUE THREAD

**Issue by sungwoncho** [niklasvh/html2canvas#831]
I am using v0.5.0-beta4 on Chrome 49.0.2623.87 (64-bit).

When I do:

```
    html2canvas($('.slide')).then(function (canvas) {
      document.getElementsByClassName('foo').appendChild(canvas);
    });
```

I get 

```
TypeError: Promise is not a constructor
```

The problem persists even when I am passing callback, not using promise.

**Comment by hyojin** [comment]
@sungwoncho I can't reproduce it. What library do you use except jquery and html2canvas?

**Comment by kartboy16** [comment]
@sungwoncho Just started getting this too.  Did you end up solving the issue?

**Comment by kartboy16** [comment]
Fixed my issue.  I'm using Meteor and had to update to the 1.4.2

**Comment by sungwoncho** [comment]
@hyojin I will close this for now due to inactivity.
