### ISSUE TITLE
when image was appended , ios won't load it

### ISSUE THREAD

**Issue by TrentXie** [niklasvh/html2canvas#833]
When i uploaded image to html page, html2canvas can't work properly in iphone6. Because image don't loaded, html2canvas has ran.I found iframe's onload went wrong in iphone

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
