### ISSUE TITLE
window.html2canvas is undefined if a module loader is used

### ISSUE THREAD

**Issue by rrutkows** [niklasvh/html2canvas#834]
Because html2canvas and html2canvas.svg are bundled as UMD, window.html2canvas will be undefined in applications that use a module loader.

**Comment by rrutkows** [comment]
As a result you get a 

> "Unable to get property 'svg' of undefined or null reference"

 error in IE, whenever it tries to use fabric.

An AMD workaround:
```javascript
require(["html2canvas", "html2canvas.svg"], function(html2canvas, svg) {
  window.html2canvas = {
    svg: svg
  };
```

**Comment by nearwood** [comment]
And if you're using babel/es6:

```
  import html2canvas from 'html2canvas';
  window.html2canvas = {
    svg: html2canvas.svg
  };
```

**Comment by oizie** [comment]
Tried to do this and I am getting an blank image..any idea of what could be causing this? 
I am using version 0.5.0-beta4. and doing:
 ```
html2canvas(captureTarget, {
            allowTaint: true
        }).then(canvas => {
            let imagex64 = canvas.toDataURL(); });
```
