### ISSUE TITLE
Rendering Large Pages Block UI

### ISSUE THREAD

**Issue by islamElbanna** [niklasvh/html2canvas#835]
render large page takes long time and block UI
ex. https://hbase.apache.org/book.html

I'm using this code
`html2canvas($("body"), {
        onrendered: function(canvas) {
            // canvas is the final rendered <canvas> element
            var myImage = canvas.toDataURL("image/jpeg", quality);
        },
          useCORS: true,
          width: width(),
          height: height()
    });`

**Comment by Demon1110** [comment]
I want to know how to solve，Especially in the IE

**Comment by islamElbanna** [comment]
This is a chrome extension so there is no IE.
I solved it by prevent parsing large pages for now till we get an upgrade from HTML2Canvas

**Comment by islamElbanna** [comment]
Any updates??

**Comment by Nomia** [comment]
Same here. 
New version html2canvas might have optimization on this by using iframe. But when you wanna render 40 or more  dom, it'll create 40 iframe, this will cause the tab title bar refresh 40 times, which is not user-friendly, and most importantly, manage too many iframe will cause some bugs(I've submitted this issue). So I choose to use the old version(not using iframe).
