### ISSUE TITLE
Not Rendering ligatures

### ISSUE THREAD

**Issue by chadwtkns** [niklasvh/html2canvas#838]
Hi Im using html2canvas to generate a jpeg but "ff", "fl", and "fi"s are not rendering. See images below. Any reason why or has anyone else encountered this?

<img width="171" alt="screen shot 2016-03-30 at 11 20 53 am" src="https://cloud.githubusercontent.com/assets/5611546/14151115/a0bdca30-f669-11e5-919d-8b0ccd992c45.png">
<img width="217" alt="screen shot 2016-03-30 at 11 21 00 am" src="https://cloud.githubusercontent.com/assets/5611546/14151116/a0c0a732-f669-11e5-9eda-9125c7c90c2f.png">

**Comment by floDroidCoder** [comment]
Hi, I've also encountered the same issue.
I'm using the v0.4.1 - 7.9.2013 version of html2canvas and solved it by replacing line 1214 :
      textList = (!options.letterRendering && /^(left|right|justify|auto)$/.test(textAlign) && noLetterSpacing(getCSS(el, "letterSpacing"))) ?

with
      textList = (!options.letterRendering && /^(left|right|justify|auto**|start|end|center**)$/.test(textAlign) && noLetterSpacing(getCSS(el, "letterSpacing"))) ?

**Comment by gurigurico** [comment]
This doesn't work if css letter spacing is applied on the text...

**Comment by burtontanner** [comment]
Could anyone tell me the css that I would need to remove to get this to work for me as well? @mtskf

**Comment by burtontanner** [comment]
if i change this:

textList = (!options.letterRendering && /^(left|right|justify|auto)$/.test(textAlign) && noLetterSpacing(getCSS(el, "letterSpacing"))) ?
      textNode.nodeValue.split(/(\b| )/)
      : textNode.nodeValue.split("");
to this:

      textList = true ?
      textNode.nodeValue.split(/(\b| )/)
      : textNode.nodeValue.split("");

and that seemed to work for me

**Comment by cscouto** [comment]
I solve this problem using a condition to check if the word has "fi"
` textList = ((!options.letterRendering && /^(left|right|justify|auto)$/.test(textAlign) && noLetterSpacing(getCSS(el, "letterSpacing"))) || (textNode.nodeValue.indexOf("fi") !== -1) ) ?`

**Comment by eKoopmans** [comment]
### The problem

The problem (pointed out in the title) is with [ligatures](https://en.wikipedia.org/wiki/Typographic_ligature#Stylistic_ligatures). Some fonts combine certain letters into a single character, especially `fi`, `fl`, and `ff`.

When `html2canvas` renders text letter-by-letter (triggered by having custom letter-spacing), it asks for the position of each letter, and when it gets to `fi` it gets the same location for the `f` and the `i` character, so it draws them on top of each other. You can find this in the code if you search for `NodeParser.prototype.getRangeBounds`.

### The solution

The easiest solution is to use the CSS style `font-feature-settings: "liga" 0` on the root element that you're capturing. You can do this programmatically just before you run `html2canvas`:

```js
var el = document.getElementById('myElement');
el.style.fontFeatureSettings = '"liga" 0';
html2canvas(el, options);
```

The [support for font-feature-settings](http://caniuse.com/#feat=font-feature) is alright but not perfect; a better alternative would be `font-variant-ligatures: none`, but that's causing a strange interaction with `html2canvas`'s parsing of `fontVariant` that I haven't figured out yet. For now, `font-feature-settings` does the job!

**Comment by gpazo** [comment]
I'm still seeing this in 1.0.0-alpha.12 with the changes above on chrome, works fine out of the box on firefox

**Comment by zxr3680166** [comment]
same problem
![image](https://user-images.githubusercontent.com/4338858/60407446-6a086400-9bed-11e9-8eb8-b514a8425385.png)
