### ISSUE TITLE
html2canvas component creates distorted images after X number of calls 

### ISSUE THREAD

**Issue by MartinStengard** [niklasvh/html2canvas#844]
I'm creating jpeg images out of jquery plot charts. There are numerous charts in page and each chart has its own "create image button".

This works fine 5-10 times but then starts creating canvas images with black background and wrong dimensions.

Is this a known issue?
Is there a way around this problem?
Clearing memory or reset instance of html2canvas lib?

**Comment by MartinStengard** [comment]
This issue only appears if I've scrolled down on page and triggered my method for creating an image.

Solved it by scrolling to top of document window.scrollTo(0,0) just before calling html2canvas. Added a callback to scroll back to origin position after canvas is created.

Any one have a better way to solve this issue?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
