### ISSUE TITLE
Canvas to image outputs black images on device with low RAM

### ISSUE THREAD

**Issue by TestDS1** [niklasvh/html2canvas#845]
I'm trying to export my page to PDF. Everywhere it works fine, but on Macbook Air the browser (tested chrome and firefox, newest versions) freezes and after a while it gives me pdf with just first one or two pages that looks ok and rest is black.

I know that this is not really html2canvas problem, I'm just hoping you have encoutered similiar problem already and can help me somehow.

My steps:
1. preformat markup to pages, so it will be aligned to pdf pages exatly as I want
2. convert markup via html2canvas to canvas
3. export canvas to images via `canvas.toDataURL("image/jpeg", 0.9)`
4. put these images into jsPDF

The problem occurs in the moment when I try export canvas to image. Canvases are fine, and after export the last few images are black. I'm pretty desperate here, because I don't even know how to detect that user is low on RAM and disable this feature for him.

Any help/suggestion appretiated.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
