### ISSUE TITLE
Element having overflow auto doesn't render properly-Overlap Contents

### ISSUE THREAD

**Issue by banajit** [niklasvh/html2canvas#847]
I have two consecutive div with overflow auto. Structure is something below

`<div class="item-1" style="height:100px;overflow:auto">
List of Items
</div>   
``
<div class="item-1" style="height:100px;overflow:auto">
List of Items
</div>`
When I tried to render it in canvas, first div contents overlap on second div contents.
This happens only with versions of 0.5.0-*
For earlier versions it works.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
