### ISSUE TITLE
have problem with character "-" when convert html to canvas

### ISSUE THREAD

**Issue by byOMG** [niklasvh/html2canvas#849]
i'm have a problem when convert html to canvas when in string have a "-" symbol.
html : http://take.ms/yg3BT
canvas : http://take.ms/0yJb9
it's working fine in other case:
html : http://take.ms/jnBSh
canvas : http://take.ms/JYiO3

structure html/css of two cases it's same code.
Thanks.

**Comment by sighgor** [comment]
Have the same issue, still no info or workarounds?

**Comment by sighgor** [comment]
Well, maybe this would be useful. Described problem occurs only when we have whitespace before the minus symbol. I.e. "-1" renders fine, while minus in " -1" overlaps following symbols

**Comment by sandrewh** [comment]
using `letterRendering: true` fixed this for me

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
