### ISSUE TITLE
Bad Crop / Rendering

### ISSUE THREAD

**Issue by grka** [niklasvh/html2canvas#857]
Hi, 

Sometimes i have bad crop / rendering in my images. 
It results with a black part on the bottom of the image.
Many times it works but sometimes it doesn't. 

Here is a case, with the log, the html code, the jquery code and the screenshot of the page

Someone have an idea ? 

Thank's in advance, 

Quentin 

Edit : I'm under html2canvas 0.5b4

![html2canvascreen](https://cloud.githubusercontent.com/assets/8752759/14700527/70868a80-07a0-11e6-8ddd-95fed0ab5d63.PNG)
![0362981001461221603_00000](https://cloud.githubusercontent.com/assets/8752759/14700465/0322636a-07a0-11e6-8d42-46c27643f27c.jpg)
[log_html2canvas.txt](https://github.com/niklasvh/html2canvas/files/229343/log_html2canvas.txt)
[htmlcode.txt](https://github.com/niklasvh/html2canvas/files/229361/htmlcode.txt)
[javascript_code.txt](https://github.com/niklasvh/html2canvas/files/229362/javascript_code.txt)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
