### ISSUE TITLE
my firefox don't support svg when capture

### ISSUE THREAD

**Issue by joyme123** [niklasvh/html2canvas#860]
when i want get a screenshot of page with firefox(or safari,Microsoft Edge),I found that svg is missing.i can't find out the problem.but the chrome is ok.
like this page: http://www.xinhuotech.com:8086/generTest/testsvg.html
or this:http://www.xinhuotech.com:8086/generTest/show.html?id=176

click the button "**导出图片**" ,it will capture the screen

can i  get some help from u?

**Comment by sureshkoduri** [comment]
Bro, I have the same problem. How can you solved this? Please help me bro.

**Comment by joyme123** [comment]
`function exportImg() {
	var ua = navigator.userAgent.toLowerCase();
	//ie要打个引号。。。。。。
	if(isIe())
	{
		alert("IE 不支持导出图片，请使用最新版的webkit内核(chrome,opera),Gecko内核(firefox)等浏览器访问导出");	
		return 0;
	}
	if(ua.match("edge")!=null)
	{
		alert("edge 不支持导出图片，请使用最新版的webkit内核(chrome,opera),Gecko内核(firefox)等浏览器访问导出");
		return 0;
	}
	$("#chart").css("display","block");
	$("#chart").css("width",$(".placeholder").css("width"));
	$("#chart").css("height",$(".placeholder").css("height"));

        /********TAKE NOTICE OF HERE*********/
       // I copy the svg content into a new div "chart", capture the "chart" div, the problem solved,then delete  "chart". 
	$("#chart").html($("#basicdiagram").html());


	var svgElements = $("#chart").find('svg');
			svgElements.each(function() {
				var canvas, xml;

				// canvg doesn't cope very well with em font sizes so find the calculated size in pixels and replace it in the element.
				$.each($(this).find('[style*=em]'), function(index, el) {
				  $(this).css('font-size', getStyle(el, 'font-size'));
				});

				canvas = document.createElement("canvas");
				canvas.className = "screenShotTempCanvas";
				//convert SVG into a XML string
				xml = (new XMLSerializer()).serializeToString(this);

				// Removing the name space as IE throws an error
				xml = xml.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/, '');

				//draw the SVG onto a canvas
				canvg(canvas, xml);
				$(canvas).insertAfter(this);
				//hide the SVG element
				////this.className = "tempHide";
				$(this).attr('class', 'tempHide');
				$(this).hide();
			  });
			html2canvas($("#chart"), {
				onrendered: function(canvas) {
					//Canvas2Image.saveAsPNG(canvas, 2000, 1000);
				  	var imgData = canvas.toDataURL('image/png');
					$("#option").append("<li><a class='btn btn-default' id='downloadImg' href='"+imgData+"' download='tree.png' >download image</a></li>");
					$("#downloadImg")[0].click();
					$("#downloadImg").remove();
				  
				}
			  });

	$("#chart").css("display","none");
}`
