### ISSUE TITLE
SVG not rendering properly on canvas

### ISSUE THREAD

**Issue by tvau** [niklasvh/html2canvas#866]
On chrome (Version 50.0.2661.86 (64-bit)) or Safari some svgs are not properly rendered on a canvas whereas other svgs render fine.

Open the following html page to reproduce the issue. The bottom svg is the svg rendered by html2canvas on a canvas :
[test.html.zip](https://github.com/niklasvh/html2canvas/files/242324/test.html.zip)

Used version of html2canvas is 0.5.0-alpha1. You can replace the src attribute to use a local file of the library such as the v0.5.0-beta4 or the dist version from the sources, but the issue remains.

**Comment by sumigoma** [comment]
Duplicate of https://github.com/niklasvh/html2canvas/issues/871

**Comment by sumigoma** [comment]
and https://github.com/niklasvh/html2canvas/issues/846

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
