### ISSUE TITLE
CSS: background-size not supported

### ISSUE THREAD

**Issue by gcpantazis** [niklasvh/html2canvas#87]
Looks like html2canvas doesn't consider the CSS3 background-size attribute for background images. I got a fix mostly working with 'contain', but would need to expand it out for 'cover', percentages, pixel widths, etc. And feature-detect for support, of course.

I'll keep working on it over the next few weeks and submit a pull request when it's stable.

**Comment by Rubioli** [comment]
for anyone reading this. If you are able to use `background-size: 100% 100%` instead of `background-size: cover`, everything will work fine!
