### ISSUE TITLE
Select with size attribute is not working while using html2canvas

### ISSUE THREAD

**Issue by suneerpa** [niklasvh/html2canvas#875]
Select with size attribute is not working while using html2canvas

I have a  list box as shown below.while am trying to convert this to image using html2canvas the items test1,test2 etc are not showing in image.If i remove the size it will work .Is there any way to accomplish this?
    `<select  size="4"  >
        <option value="test1">test1</option>
        <option value="test2">test2</option>
        <option value="test3">test3</option>
        <option value="test4">test4</option>
        </select>`

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by mparizeau-pdftron** [comment]
Yes this is still a problem. Here is a jsfiddle: https://jsfiddle.net/xto6oa8s/
