### ISSUE TITLE
If an image is out of the screen, it will not be included, setting height works, but width does not

### ISSUE THREAD

**Issue by nigel-dewar** [niklasvh/html2canvas#876]
Hi There,

First of all great work by the way. I have been trying to use your library to take a snapshop of a table. We made it large because otherwise the resolution was poor. 

The problem is the width, anything not on the screen gets cut off when we take a snapshot. The hieght is not an issue though. 
We set the hieght and width to huge values, even if we set width to 100000 it makes no diff
width: 3000,
height: 1500

The snaptshot still gets cut off,

Can you please advise if we are doing some thing wrong or if this is a bug? Any help would be greatly appreciated, I have invested 4 days trying to get this right.

Cheers

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
