### ISSUE TITLE
I am using html2canvas to generate screen short for chart. The font which I am using for chart is not rendering in the screenshot.

### ISSUE THREAD

**Issue by devender85** [niklasvh/html2canvas#879]

**Comment by Dayjo** [comment]
Can you provide an example? If not, can you give us any more information, i.e. what's the font, what's the css you're using. What's your javascript call, is the font on another server - so should you be using 'CORS'?

**Comment by arsen2010** [comment]
I solve the solution by using setTimeout  at  function "createWindowClone" ,
This is  the code:
function createWindowClone(ownerDocument, containerDocument, width, height, options, x, y) {
        labelCanvasElements(ownerDocument);
        var documentElement = isIE9() ? cloneNodeIE9(ownerDocument.documentElement, options.javascriptEnabled) : ownerDocument.documentElement.cloneNode(true);
        var container = containerDocument.createElement("iframe");

        container.className = "html2canvas-container";
        container.style.visibility = "hidden";
        container.style.position = "fixed";
        container.style.left = "-10000px";
        container.style.top = "0px";
        container.style.border = "0";
        container.width = width;
        container.height = height;
        container.scrolling = "no"; // ios won't scroll without it
        containerDocument.body.appendChild(container);

        return new Promise(function (resolve) {
            //here
            setTimeout(function () {
                //
                var documentClone = container.contentWindow.document;

                cloneNodeValues(ownerDocument.documentElement, documentElement, "textarea");
                cloneNodeValues(ownerDocument.documentElement, documentElement, "select");

                /* Chrome doesn't detect relative background-images assigned in inline <style> sheets when fetched through getComputedStyle
                if window url is about:blank, we can assign the url to current by writing onto the document
                */
                container.contentWindow.onload = container.onload = function () {
                    var interval = setInterval(function () {
                        if (documentClone.body.childNodes.length > 0) {
                            cloneCanvasContents(ownerDocument, documentClone);
                            clearInterval(interval);
                            if (options.type === "view") {
                                container.contentWindow.scrollTo(x, y);
                            }
                            resolve(container);
                        }
                    }, 50);
                };

                documentClone.open();
                documentClone.write("<!DOCTYPE html><html></html>");
                // Chrome scrolls the parent document for some reason after the write to the cloned window???
                restoreOwnerScroll(ownerDocument, x, y);
                documentClone.replaceChild(options.javascriptEnabled === true ? documentClone.adoptNode(documentElement) : removeScriptNodes(documentClone.adoptNode(documentElement)), documentClone.documentElement);
                documentClone.close();
                //
            }, 1000);
        });
    }
