### ISSUE TITLE
Clip-path css doens't render ?

### ISSUE THREAD

**Issue by tibewww** [niklasvh/html2canvas#885]
Hi,

I'm using various image genretated by CSS with some clip path such as:

```
.rec.one{
position: absolute;
float:left;
    -webkit-clip-path: polygon(0 0, 27% 26%, 27% 100%, 0% 100%);
clip-path:  polygon(0 0, 27% 26%, 27% 100%, 0% 100%);
}
```

```
<div class="rec one">

                 <img src="pattern/purple.jpg" height="500">

            </div>
```

The problem I'm having is when i render the canvas as an img, it render the full image ( not masked anymore via the clip path)

Is there anyway to make this work by any chance ? It would be incredible !

Thanks a lot!

**Comment by abdullahknz** [comment]
Is solved ?

**Comment by Ferhat55** [comment]
I'm having the same issue except with background-color instead of an image (html2canvas 0.5.0-alpha1)

**Comment by Photix** [comment]
Use dom-to-image instead
https://github.com/tsayen/dom-to-image

It allows save image from DOM elements with clip-path css property.

**Comment by abdullahknz** [comment]
Thank you so much. It is work for me. Actually it is not work for <img src="https://www.blabla.com/example.jpeg" so not render image url from another server.

**Comment by AnthonyCrowcroft** [comment]
is this actually resolved or not sorry?

**Comment by olivermen** [comment]
Thanks. DOM-TO-IMAGE works for me.
