### ISSUE TITLE
Doesn't capture the image. 

### ISSUE THREAD

**Issue by viraj89** [niklasvh/html2canvas#886]
Have a div, which captures a base64 image and stores in a variable say, `var image` . 

Further, I am trying to capture the image of image, but it isn't showing me the image, instead it display the empty div. 

html2canvas do support such case? Thanks.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
