### ISSUE TITLE
Rendered Image showing mysterious vector lines

### ISSUE THREAD

**Issue by eahrold** [niklasvh/html2canvas#887]
I've got a page that is generating a grid type layout, no external images.

Most everything is positioned `<div>`'s. 
The grey background is a <canvas> element.

The suspect circular objects are `<div>`'s as well, and I'm not sure how these vectors are getting displayed.

Here's an example of one
```HTML
<div id="valve-13" data-num="13" class="valve" style="left: 442.031px; top: 180.557px;"></div>
```

Attached are the original and the rendered.

I've tried disabling border-radius, and border altogether (using the inspector), but that doesn't seem to have any effect.

Any advice as to where to begin digging in is greatly appreciated.
Thanks.

![html2canvas-actual](https://cloud.githubusercontent.com/assets/3740088/15936328/3bf8171e-2e30-11e6-9a89-263a4262d3f5.png)

![html2canvas-render](https://cloud.githubusercontent.com/assets/3740088/15936346/428dc5a6-2e30-11e6-8387-51092198bbcc.png)

**Comment by MSCAU** [comment]
I had the same when I used border-radius: 50%. When I changed it to a pixel value (equal to half the height of the DIV), html2canvas rendered it the same as normal. I'd rather use the percentage value but - hey - it works.

**Comment by eahrold** [comment]
@MSCAU Awesome! That did it. Thanks.

On a side note, for any future seekers, html2canvas did not seem to pick up changes when the props were enabled/disabled in the inspector, it required updating the style sheet and reloading the page.
