### ISSUE TITLE
Index Size Error on IE10/IE11

### ISSUE THREAD

**Issue by royarin** [niklasvh/html2canvas#891]
Index size error on IE10/IE11 when cropping image. Happens when element passed has width 100%.

Fiddle: http://jsfiddle.net/royarin/pLp7nje1/3/

**Comment by petertflem** [comment]
@royarin I think I have the same problem, but in the jsfiddle I can't fix it by setting the width smaller than 100%. How can I get it working? I'm testing with IE11.
