### ISSUE TITLE
long-time rendering with images

### ISSUE THREAD

**Issue by chy996633** [niklasvh/html2canvas#895]
when i render a node with 11 images (each size is about 2MB ), it takes about 80s in Chrome and about the same in Firefox .
i wonder how to improve it or know more about my problem. Thanks!

page is here http://cschurch.date/hib/movie/
it's written in chinese, you can put image with 「上传」 button ，and then click 「生成截图」

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
