### ISSUE TITLE
Image and Border for Pseudo Element is not rendering.

### ISSUE THREAD

**Issue by subrat07** [niklasvh/html2canvas#896]
While creating canvas object of DOM, images and border for Pseudo element is not rendering. We can see the issue  https://jsfiddle.net/subrat07/k7scaaur/2/

Browser: Chrome, Firefox, Internet Explorer

JS used:
html2canvas.js : 0.5.0-beta4
jquery.js

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by JEEVANJGA** [comment]
Hi,
Facing similar issue => #1683

**Comment by basithmiet** [comment]
Hi,
Facing same issue in IE 11+
