### ISSUE TITLE
Background trouble

### ISSUE THREAD

**Issue by DarkApocalypse** [niklasvh/html2canvas#897]
Hello,
I found an issue with background image.
I made an example in this zip to show it.
Click on "Show Image" button and it will open an tab with the canvas showing the body rendered with the background image not rendered
[test-html2canvas.zip](https://github.com/niklasvh/html2canvas/files/327396/test-html2canvas.zip)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
