### ISSUE TITLE
Throw an exception   "Uncaught TypeError: Cannot read property 'polyfill' of undefined"

### ISSUE THREAD

**Issue by editcue** [niklasvh/html2canvas#899]
After I use webpack for package html2canvas into project and run it on browser.
It throw an exception 
`Uncaught TypeError: Cannot read property 'polyfill' of undefined`
 at html2canvas.js line 29 
`window.ES6Promise.polyfill();`
how can I fix it?

**Comment by editcue** [comment]
I just modifed it (see below) . It's fixed temperary . Without any other test. It only works in my envirment.
`window&&typeof window.ES6Promise != 'undefined'&&typeof window.ES6Promise.polyfill === 'function'&&window.ES6Promise.polyfill();`

**Comment by ycscholes** [comment]
You can use the master branch rather than the alpha1 release files. It's beta4 now.
