### ISSUE TITLE
radio buttons

### ISSUE THREAD

**Issue by benbro** [niklasvh/html2canvas#9]
When a page has radio buttons it renders as blank rectangles:
http://html2canvas.hertzen.com/demo2.html

Is it possible to replace radio buttons and other browser / OS specific UI elements with images on the server?

**Comment by winweb** [comment]
please kindly share the example to solve this problem.

**Comment by niklasvh** [comment]
Working example available at https://github.com/niklasvh/html2canvas/blob/master/tests/cases/forms.html

**Comment by winweb** [comment]
thanks
