### ISSUE TITLE
font issue with greek fonts, different in every Operating System!

### ISSUE THREAD

**Issue by bilios** [niklasvh/html2canvas#906]
Hello, 

i am trying to create screenshots with html2canvas, my screenshots have greek text inside. I recently discovered that html2canvas reacts differently in any operating system.

If i will create my image in a macintosh machine, fonts render perfectly..

If i will create my image in a windows machine, fonts transform into a generic font that i dont want..

The think is that i have a tons of fonts in my server, but i dont think it is there the problem..

Can you please tell me why i cant specify the fonts i want html2canvas to use?

Why it renders differently according to OS?

Thank you very much for your help!

**Comment by PatrickHuetter** [comment]
I can confirm this issue.
