### ISSUE TITLE
Multi page does not work on iOS with jsPDF

### ISSUE THREAD

**Issue by gwhenne** [niklasvh/html2canvas#910]
I'm using htm2canvas with jsPDF. It works fine on all platforms if I am outputting a single page.

If I make a two page document (using either html2canvas's pagesplit option, or jsPDF's addPage), it fails silently on iOS only. The PDF does not open after it is saved by jsPDF. Other platforms work properly.

Is there a workaround, or is a fix needed?

**Comment by atdiff** [comment]
@nsbasic do you have a jsfiddle example of how you've integrated html2canvas and jsPDF?  I'm trying to do the same, but running into huge hurdles with html2canvas and how it renders (or doesn't) the images I have on my page.  Just curious how you're doing it.

**Comment by nsbasic** [comment]
I'm not doing any images - just styled DIVs with text in them.

**Comment by ianguyue** [comment]
Html2canvas is ok in ios 7 system? I can run it in ios 7 system
