### ISSUE TITLE
Html2canvas with plotly

### ISSUE THREAD

**Issue by NithyaRani** [niklasvh/html2canvas#916]
Plotly graph legend and yaxis is not getting convert to image while we are using thehtml2canvas

Below is my code for the same

<head>
  
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
      <script src="jquery-2.2.1.js"></script>
  <script src="html2canvas.js"></script>

<script src="html2canvas.svg.js"></script>

</head>

<body>
  <input id="btn-Preview-Image" type="button" value="Preview">
  <div id="myDiv" style="width: 480px; height: 400px;"></div>
  <script>
var trace1 = {
  x: [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012], 
  y: [219, 146, 112, 127, 124, 180, 236, 207, 236, 263, 350, 430, 474, 526, 488, 537, 500, 439], 
  name: 'Rest of world', 
  marker: {color: 'rgb(55, 83, 109)'}, 
  type: 'bar'
};

var trace2 = {
  x: [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012], 
  y: [16, 13, 10, 11, 28, 37, 43, 55, 56, 88, 105, 156, 270, 299, 340, 403, 549, 499], 
  name: 'China', 
  marker: {color: 'rgb(26, 118, 255)'}, 
  type: 'bar'
};

var data = [trace1, trace2];

var layout = {
  title: 'US Export of Plastic Scrap',
  xaxis: {tickfont: {
      size: 14, 
      color: 'rgb(107, 107, 107)'
    }}, 
  yaxis: {
    title: 'USD (millions)',
    titlefont: {
      size: 16, 
      color: 'rgb(107, 107, 107)'
    }, 
    tickfont: {
      size: 14, 
      color: "rgb(107, 107, 107)"
    }
  }, 
  legend: {
    x: 0, 
    y: 1.0, 
    bgcolor: 'rgba(255, 255, 255, 0)',
    bordercolor: 'rgba(255, 255, 255, 0)'
  }, 
  barmode: 'group', 
  bargap: 0.15, 
  bargroupgap: 0.1
};

Plotly.newPlot('myDiv', data, layout);
$(document).ready(function () {
        var element = $("#myDiv"); // global variable
        var getCanvas; // global variable

```
    $("#btn-Preview-Image").on('click', function () {       

        debugger;

        html2canvas(element, {
            allowTaint: false,
            background: "#fff",
            //height : 500,
            letterRendering:true,
            //logging: true,
            //flashcanvas: "flashcanvas.min.js",                
            profile: true,
            useCORS: true,              
            onrendered: function (canvas) {
                var imgageData = canvas.toDataURL();                    
                window.open(imgageData);                    
            }
        });


    });    
});
```

  </script>
</body>

**Comment by Rudresh-Ajgaonkar** [comment]
Hey Even i am stuck on a similar issue. I am trying to capture plotly graph into my webapp but i am unable to do so. Were you able to capture the basic plot ? Email: rudreshajgaonkar@gmail.com

**Comment by NithyaRani** [comment]
Hey i am able to capture graph. But only one issue is yaxis labels and legend are not displaying the correct location its because of 2 svg tags.

**Comment by amalinafz** [comment]
HI, mind to share how you able to capture the graph?
