### ISSUE TITLE
it's not working properly in .net mvc project at Edge,IE Browser

### ISSUE THREAD

**Issue by whdk999** [niklasvh/html2canvas#923]
i put the html2canvas-alpha1's script file in my mvc project 
like this
![image](https://cloud.githubusercontent.com/assets/7695098/17423350/1e54c44a-5af5-11e6-92f5-dcb96219b20f.png)
then create view page(demo2.cshtml) that is created by(your sample demo2.html) 
like this
**-demo2.cshtml file**
![image](https://cloud.githubusercontent.com/assets/7695098/17423424/798bdd62-5af5-11e6-889f-5abd230f18ff.png)
**-capture.js file**
![image](https://cloud.githubusercontent.com/assets/7695098/17423443/99c184a6-5af5-11e6-8839-54a968e37a2f.png)

As a result, it's not working properly at Edge,IE Browser
![image](https://cloud.githubusercontent.com/assets/7695098/17423534/413146fe-5af6-11e6-803e-c73db47b45e6.png)

Actually it works very well at all of borwser, when i test it normally in html file
but when it's in MVC View Page(.cshtml), it's not working ....

I guess this problem it's 'cause the style tag is in cshtml file
if I create css file for the styles and get rid of them in cshtml, it's working well

so, i hope to know why it works differently 

if it can not be helped
please let me know how can i do for this when i put style tags in cshtml file

**Comment by bliet** [comment]
I can confirm that html2canvas doesn't work probably in MS Edge. 
In my case it doesn't rendered some pictures. In other browsers it works.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
