### ISSUE TITLE
Random Results when Generating Image after a CSS background change

### ISSUE THREAD

**Issue by projecz** [niklasvh/html2canvas#925]
When I generate an image, just before I call html2canvas I change the background color of a div. 90% of the time it is fine. But for some users the background stay the same.

It feels like the image generation is happening before the CSS changes comes into effect.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
