### ISSUE TITLE
Problem when using the library offline

### ISSUE THREAD

**Issue by andremiguelaa** [niklasvh/html2canvas#926]
I have a website that works offline (appacache) and, when I use the library offline, the generated image doesn't respect the css styles.
It renders like I don't have any css in the page.
Online works greats.
Any idea of what is causing this issue?

**Comment by andremiguelaa** [comment]
?

**Comment by AntonioDeCusatiNesea** [comment]
How you have solved this problem?

**Comment by andremiguelaa** [comment]
I didn't...
