### ISSUE TITLE
Rotatable and Resizeable not working

### ISSUE THREAD

**Issue by MohammadTF** [niklasvh/html2canvas#927]
I made a div and used jquery resizable but then it doesn't show the required output.
Below is the image of before using html2canvas
![one](https://cloud.githubusercontent.com/assets/11040247/17808995/f716757a-662c-11e6-90c9-74514f5c1ecd.PNG)

Below is the image of after using html2canvas
![two](https://cloud.githubusercontent.com/assets/11040247/17809009/141f0eac-662d-11e6-9d85-33d9a3c361a1.PNG)

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
