### ISSUE TITLE
Svg Image Render Custom Font 

### ISSUE THREAD

**Issue by bsharma20** [niklasvh/html2canvas#931]
Dear Sir/ Madam,

I need to create an image from highchart chart svg, I am able to create the same but it is not rendering custom font. Do i need to do anything different to achieve the same ?

Can you please help in this regard..

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
