### ISSUE TITLE
Rotate Individual Element in Html

### ISSUE THREAD

**Issue by bsharma20** [niklasvh/html2canvas#932]
Dear Sir/ Madam,

I am rendering some element using html2Canvas.. There is one element with transform property to -90 degree.. 

In result image i dont get element with rotation .. I could trace element get printed from paintFormValue but transform/ rotation is not applied.. Can you please advise how i can apply explicit transformation/ rotation ?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
