### ISSUE TITLE
Not support an  external style sheet for svg?

### ISSUE THREAD

**Issue by wwwjun** [niklasvh/html2canvas#934]
I write an external style sheet for svg(use **d3.js**),it does not work.Should I set the style in my js use D3.js as the attribute of an svg element
![image](https://cloud.githubusercontent.com/assets/11974533/18192268/384f4d68-7105-11e6-9bef-fb88d0e6c49e.png)
![image](https://cloud.githubusercontent.com/assets/11974533/18192285/5f6e05f6-7105-11e6-848b-4c7f8be1e037.png)

![image](https://cloud.githubusercontent.com/assets/11974533/18192311/aacb0012-7105-11e6-9a95-8834d618a36c.png)

**Comment by wwwjun** [comment]
I have solved the problem

**Comment by NPC** [comment]
@wwwjun can you please share how you did it? I couldn't find a solution other than embedding styles in the SVG.

**Comment by wwwjun** [comment]
@NPC I just set the styles when I use d3.js to append an element in my javascript file.
Just like .style('stroke','#ccc').

**Comment by NPC** [comment]
@wwwjun OK, thanks, so external stylesheets are still not an option as far as we know.

**Comment by wwwjun** [comment]
@NPC It is my pleasure,hope it will support external stylesheets.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
