### ISSUE TITLE
cant export image from google street view in Chrome

### ISSUE THREAD

**Issue by fmoris** [niklasvh/html2canvas#935]
I have this code

$scope.pdf = function () {
            $scope.loading = 1;
            html2canvas($("#street > ng-map"), {
                useCORS: true
                , onrendered: function (canvas) {
                    var dataUrl = canvas.toDataURL("image/jpeg", 1.0);
                    var doc = new jsPDF('l', 'cm', [$scope.ancho, $scope.alto]);  
                    var specialElementHandlers = {
                        '#ignorePDF': function (element, renderer) {
                            return true
                        }
                    };
                    doc.addImage(dataUrl, 'JPEG', 0, 0, $scope.ancho, $scope.alto);
                    if($scope.navegador){
                         window.open(doc.output('save', 'StreetView.pdf'),'_parent');
                    }else{
                       doc.save('StreetView.pdf');
                    }
                    $scope.loading = 0;
                    $('#modal1').closeModal();
                }
            });
        };
It worked but a few weeks ago stopped working, now export PDF with black screen
[StreetView (32).pdf](https://github.com/niklasvh/html2canvas/files/452011/StreetView.32.pdf)

**Comment by nereae** [comment]
Something similar is happening to me when I create an image (.png) from a div which contains a Google Maps´ map and download it by clicking a button in ASP.NET. I can see the markers I have created but not the controls and the maps itself.

JAVASCRIPT
-------------
html2canvas($("#grafico"), {
            onrendered: function(canvas) {                                  
                    //For all browsers
                    document.body.appendChild(canvas);
                    // Convert and download as image                    
                    var base64 = canvas.toDataURL();
                    document.getElementById("HiddenFieldImagen").value = base64;
                    document.getElementById("ButtonExportar").click();
                }
            });

ASP.NET
---------
protected void ButtonExportar_Click(object sender, EventArgs e)
    {
        string base64 = HiddenFieldImagen.Value.Split(',')[1];
        byte[] bytes = Convert.FromBase64String(base64);

        Response.Clear();
        Response.ContentType = "image/png";
        Response.AddHeader("Content-Disposition", "attachment;filename=map.png");
        Response.Buffer = true;
        Response.Cache.SetCacheability(HttpCacheability.NoCache);
        Response.BinaryWrite(bytes);
        Response.End();
    }    


Have you found any solution to this issue??

![divgooglemapstopng](https://cloud.githubusercontent.com/assets/22005701/18248782/ae5a4630-737a-11e6-8831-2b8954549cc3.png)

**Comment by nereae** [comment]
As html2canvas doesn't load cross-origin images by default but if you use the useCORS parameter it works properly.
useCORS	boolean	false	Whether to attempt to load cross-origin images as CORS served, before reverting back to proxy


html2canvas($("#grafico"), {
    useCORS:true,
    onrendered: function(canvas) {
    //For all browsers
   document.body.appendChild(canvas);
   // Convert and download as image

   var base64 = canvas.toDataURL();
   document.getElementById("HiddenFieldImagen").value = base64;
   document.getElementById("ButtonExportar").click();
}
});

**Comment by andreslon** [comment]
Any solution?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by AnjuLalson** [comment]
Hai @fmoris , Did you find any solution for this issue? I am facing the same issue
