### ISSUE TITLE
WARNING in ./~/html2canvas/dist/html2canvas.js

### ISSUE THREAD

**Issue by dpadron2** [niklasvh/html2canvas#936]
Hello,
As I can resolve this warning?

you can help me..

WARNING in ./~/html2canvas/dist/html2canvas.js
Critical dependencies:
8:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/html2canvas/dist/html2canvas.js 8:484-491
webpack: bundle is now VALID.

**Comment by thfontaine** [comment]
Temporary resolutions in #749
