### ISSUE TITLE
hi iam using html2canvas image upload to php server problem

### ISSUE THREAD

**Issue by optimusbrain** [niklasvh/html2canvas#942]
cannot upload 1mb < size images php server , 
html:-

<form method="POST" enctype="multipart/form-data" action="work_cards.php" id="myForm">
<input type="hidden" name="img_val" id="img_val" value="" />
</form>

<input type="submit" id="order_btn" onclick="capture();" class="btn btn-primary btn-lg pull-right" value="Order"/>

function:-
function capture() {
        $('#content-container,#popup_div').html2canvas({
            onrendered: function (canvas) {
                //Set hidden field's value to image data (base-64 string)

```
            $('#img_val').val(canvas.toDataURL("image/jpeg").replace("image/jpeg", "image/octet-stream"));
            //Submit the form manually
            document.getElementById("myForm").submit();
        }
    });
}
```

save_php file:-
<?php
//Get the base-64 string from data

$filteredData=substr($_POST['img_val'], strpos($_POST['img_val'], ",")+1);

//Decode the string
$unencodedData=base64_decode($filteredData);

//count the order of download
$select_query_sales = "select \* from down_order";
$run_sales = mysqli_query($con,$select_query_sales);

$user_sales = mysqli_num_rows($run_sales);

$url = "Kings_design_".$user_sales;

//Save the image
file_put_contents('img/order/'.$url.'.jpeg', $unencodedData);

?>
please help me canot uploade to large image to php server .

**Comment by euneuber** [comment]
Hi,
can you confirm, that you have appropriate settings in your php.ini?
See: http://stackoverflow.com/questions/7754133/php-post-max-size-overrides-upload-max-filesize
