### ISSUE TITLE
Alpha version: inconsistent rendering

### ISSUE THREAD

**Issue by mwirobruiz** [niklasvh/html2canvas#944]
Sometimes it renders if perfects, others it just returns a thin line of black pixels. I started using the newer alpha as it seemed to be rendering layered absolute positioned divs better than the latest production build, but I am having to revert for this reason. 

Is this thing still being developed. It looks like it's been almost a year since the last update to the alpha.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
