### ISSUE TITLE
checkbox position misplaced when contain element scroll

### ISSUE THREAD

**Issue by aoyk** [niklasvh/html2canvas#945]
<img width="960" alt="0 5 0_beta4" src="https://cloud.githubusercontent.com/assets/16873480/18613668/e2668d44-7db1-11e6-935e-b1b9dc9fccad.PNG">
html2canvas version: 0.5.0 beta4
browser version: chrome 52.0.2743.116 m

just as the image shows.
source html elements are above the separator, and four snap-shots by html2canvas below.

there're two checkbox in a containing element (overflow: auto) and content is higher than the container. if not scroll down, only the first checkbox can be seen.
it seems html2canvas only make snap-shots for the first checkbox, but missed the second one and misplace the first one.

here's my code:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>HTML2CANVAS TEST</title>
</head>
<body>
    <div id="shot_me" style="height:200px; width:300px; border:1px solid #ddd; overflow:auto;">
        <div style="width:150px; height:150px; background-color:white;">
            <p>I AM WHITE</p>
            <input type="checkbox" style="transform:scale(2.0,2.0);" value="i_am_checkbox"/>
        </div>
        <div style="width:150px; height:150px; background-color:grey;">
            <p>I AM GREY</p>
            <input type="checkbox" style="transform:scale(2.0,2.0);" value="i_am_checkbox"/>
        </div>
    </div>
    <button id="shot">SHOT</button>
    <hr/>
    <script type="text/javascript" src="./html2canvas_0.5.0_beta4.js"></script> 
    <script type="text/javascript">
        document.getElementById('shot').onclick=function(){
            html2canvas(document.getElementById('shot_me')).then(
                canvas => {document.body.appendChild(canvas)}
            );
        }
    </script>
</body>
</html>
```

I didn't find any similar issues or resolution, or I just missed.
thanks a lot if any help

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
