### ISSUE TITLE
Arabic font rendering

### ISSUE THREAD

**Issue by vali-mint** [niklasvh/html2canvas#948]
Hey guys, I've seen this issue opened before, however I can't get it to work properly for a custom Arabic font. 

Here is how the HTML looks: http://prntscr.com/ckxcp3

And how the html2canvas `0.5.0-alpha1` looks: http://prnt.sc/ckxd1v

As you can see, the characters are all tangled up. Any ideas? 

Update: 
On line 2321 I replaced `!hasUnicode` with `hasUnicode`, which works almost perfect:
http://prnt.sc/ckxnjo
Now the font looks perfect, but normal characters "!" and "(" have wrong direction.

Update2: 
Managed to find a fix based on n-a-g-r-o-m' solution [https://github.com/niklasvh/html2canvas/issues/686]

**Comment by Ali492** [comment]
check out 
http://stackoverflow.com/questions/30555379/html2canvas-image-capturing-issue-with-utf-8-characters

similar issue

**Comment by RashwanSharif** [comment]
For version  0.5.0-beta3

Change:
var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) 

To:
var textList = (!this.options.letterRendering || noLetterSpacing(container)) || !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) 

Change the **&& to ||** 

And it works perfect for Arabic without any CSS modifications

**Comment by S4Mi** [comment]
sounds like the problem is fixed, 
just be ware of `word-wrap : break-word` style, it still splits the Arabic/Persian words into separate characters.

**Comment by FireWall-e** [comment]
> For version 0.5.0-beta3
> 
> Change:
> var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character)
> 
> To:
> var textList = (!this.options.letterRendering || noLetterSpacing(container)) || !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character)
> 
> Change the **&& to ||**
> 
> And it works perfect for Arabic without any CSS modifications

Worked for me along with `letter-spacing: normal`

**Comment by sevenLee** [comment]
don't use `word-break: break-word;`

**Comment by niklasvh** [comment]
RTL support added in https://github.com/niklasvh/html2canvas/pull/2653

**Comment by TarekAlQaddy** [comment]
I faced the same issue in version 1.4.1 and fixed it by using
```
letter-spacing: normal;
```
in the wrapping element
