### ISSUE TITLE
div to image not working 

### ISSUE THREAD

**Issue by darkworks** [niklasvh/html2canvas#949]
am trying to convert div to image with code on bottle image which have gif in background and new layers with colors are added dynamically :: https://www.makethatvape.com/ejuicecalc/

```
	    html2canvas($("#widget")).then(function(canvas) {
           bimg = canvas.toDataURL();
});
```
however its not working specially when new color layer is added through form button , which mean html2canvas do not work with dynmically created content ..

so i think there should be reload feature in html2canvas which could be triggered to read DOM as new content as added before processing to convert div to canvas 

thanks

**Comment by almeidap** [comment]
@darkworks, you should probably pass a native `HTMLElement` to `html2canvas()` instead of a jQuery collection, i.e.:

    html2canvas($("#widget")[0])

_or_

    html2canvas(document.getElementById("#widget"))

**Comment by darkworks** [comment]
ya i fixed , it was div height issue ...
