### ISSUE TITLE
CORS issue, using Rack-cors gem with cloudfront assets

### ISSUE THREAD

**Issue by fuggfuggfugg** [niklasvh/html2canvas#951]
I have a rails 4 app hosted on AWS with assets served on cloudfront. I use the [rack-cors gem ](https://github.com/cyu/rack-cors) to add cors headers. My rack-cors settings allows only check for my domain hence cannot provide jsfiddle example. 

`curl -H "Origin:https://staging.beenlightened.com" -I https://d3czu6zp3f06wr.cloudfront.net/assets/vitality4-064f8c9848768917287e1a7dbcec1749.png`

![screen shot 2016-10-02 at 4 06 08 pm](https://cloud.githubusercontent.com/assets/5616123/19023336/9aff5134-88ba-11e6-8676-9340f99b99d6.png)

Notice CORS headers are added correctly. However html2canvas still complains about cors headers not being present. 

![screen shot 2016-10-02 at 4 25 06 pm](https://cloud.githubusercontent.com/assets/5616123/19023469/ebecb94a-88bc-11e6-9f57-a58a9333e6fb.png)

**Comment by BaptWaels** [comment]
I've got the same problem but with AWS EC2. Is the problem solved for you ?

**Comment by fuggfuggfugg** [comment]
From what I remember: When the page loads the first time, the browser caches the image. Since the domain is the same, the CORS headers are not present. So now when I try to print the image it used the cached image and html2canvas complained about CORS headers not present.

My only solution was to add a timestamp in the ImageContainer method inside the library like so: 

    if (cors) {
            self.image.crossOrigin = "anonymous";
            // special check for cloudfront images only.
            if (src.toLowerCase().includes("cloudfront")){
              src = src + '?123';
            }
        }


I've spent ages on this damn thing. Hope it works for you man.

**Comment by BaptWaels** [comment]
Thank you for your answer 👍  I've already spent ages on this CORS problem. Even if I add your suggestion, it's not working. Maybe I don't configure well CORS on EC2

**Comment by fuggfuggfugg** [comment]
When your page loads, use your image link to test here --> http://www.test-cors.org/ and make sure the CORS header is added.  If it's not then this is something you can start with. 

Good luck.

**Comment by NikhilRadadiya** [comment]
@fuggfuggfugg  I have smae issue, I've images from other domain, it loads succussfully but doesn't print in pdf.
can you help me here?
Before it was showing CORS error and images was not loading

**Comment by fuggfuggfugg** [comment]
Ensure the images from the other domain do have the CORS headers. Another alternative is passing allowTaint: true but it has limitations.

**Comment by NikhilRadadiya** [comment]
@fuggfuggfugg  I'm not using CORS currently but still its loading, before it was not loading.
still image not printing to pdf

**Comment by fuggfuggfugg** [comment]
Can you make an example on codepen or jsfiddle?
