### ISSUE TITLE
Why is my text so blurry?

### ISSUE THREAD

**Issue by PhpSriptKiddie** [niklasvh/html2canvas#952]
When using Html2canvas my text gets really blurry. What can I do to make it sharper?

Example: http://tiny.cc/nstify (use the orange "print" button)

**Comment by MacGWik** [comment]
I get this problem too.. But, when I'm zoom out to 90%, the font is fine...

Here's the example

100% zoom page
![iridium by templated](https://cloud.githubusercontent.com/assets/12266489/19212049/b3af63d2-8d73-11e6-8fa4-6870eb78636f.png)

90% zoom page (screenshot when the page 100% again)
![iridium by templated](https://cloud.githubusercontent.com/assets/12266489/19212075/18daf9b0-8d74-11e6-873d-309780f601b6.png)

**Comment by tmonte** [comment]
Same problem here. Is anyone even maintaining html2canvas? It seems like the last update was more than a year ago

**Comment by Tusko** [comment]
+++

**Comment by bdegley4789** [comment]
window.devicePixelRatio = 2;

I put this before I did html2canvas and it worked for me
