### ISSUE TITLE
in HTML other Font and in rendered Screenshot other

### ISSUE THREAD

**Issue by svanskivar** [niklasvh/html2canvas#953]
Hi,
I have in HTML as font-family: " Helvetica Neue",Helvetica,Arial,sans-serif " , but rendered Font-Family ist not the same, also Text in Screenshot is a bit blurry. IMG hier to compare both: [![FontPRoblem.png](https://s16.postimg.org/mzfwhwpyd/Font_PRoblem.png)](https://postimg.org/image/axkinrgpt/) 

This is very important for me and thanks in advance.
P.S. Language is German and I have the latest Version of html2canvas.

**Comment by nickkapoor** [comment]
Remove the  Helvetica Neue from the font-family and try it.  html2canvas gets tripped around the double quotes around "Helvetica Neue"

**Comment by gnattu** [comment]
I can reproduce this on 0.5.0b4. What's more, the fonts seems to work properly on version 0.4.x.
My font-family: `"Ubuntu", "Helvetica Neue", "Helvetica", "Arial", "Heiti SC", "WenQuanYi Micro Hei", "Microsoft YaHei", "Droid Sans Fallback", sans-serif`

**Comment by eggers** [comment]
@svanskivar Was this a custom font-face? I'm experiencing issues with font-faces on safari.

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/commit/77d258f1d8eeccf7e38235463a293b512c1ca3d0
