### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by rahuljadav** [niklasvh/html2canvas#957]
My below code is not working in IE11 browser.

html2canvas($canvasContainer, {
                        onrendered: function(canvas) {
                            document.body.appendChild(canvas);
                            var href = canvas.toDataURL(),
                                filename = 'report.png';
                            $downloadBtn.prop('href',href);
                            $downloadBtn.prop('download',filename);
                        }
                    });

**Comment by Prabhat2404** [comment]
Still not working in IE 11. 

Trying with sample code: 

html2canvas(document.body).then(canvas => {
            document.body.appendChild(canvas)
        });
