### ISSUE TITLE
html2canvas not able to print images which are hyperlinked to other server

### ISSUE THREAD

**Issue by vishalmaske7787** [niklasvh/html2canvas#959]
eg. if page contains image from other server like this http://www.free-avatars.com/data/media/79/Snowman-Cartoon.jpg . Then html2canvas is not able to render it but it leaves a blank white patch. It means function is not waiting for remote image to load.

**Comment by weavermedia** [comment]
This is intended behavior and described in the documentation:

"Limitations: All the images that the script uses need to reside under the same origin for it to be able to read them without the assistance of a proxy."

However, if the images on the other server are being served with proper CORS headers you can set the `useCORS: true` option and it will include the images.
