### ISSUE TITLE
How can I use html2canvas with Angular 2?

### ISSUE THREAD

**Issue by TheNightbear** [niklasvh/html2canvas#960]
Can someone please explain how to use html2canvas properly with Angular 2?

It can be installed with `npm install html2canvas` but it does not contain any TypeScript code.
@niklasvh , will you provide a version we can easily use with Angular 2?

**Comment by Tarek-Adra** [comment]
Check this answer 
[Here](http://stackoverflow.com/questions/38998844/html2canvas-to-render-document-pdf-with-css-styling-using-angular2-typescript)

**Comment by da45** [comment]
Any news please? did someone fix this issue?

**Comment by Brieg** [comment]
In u'r component below Imports add:

`declare let html2canvas: any;`

Then u can use html2canvas normaly

**Comment by jexobejas** [comment]
@Tarek-Adra Sorry that link didn't work for me.

```
/Applications/MAMP/htdocs/html5-banner/src/app/selected-banner/selected-banner.component.ts (64,10): Argument of type '{ onrendered: (canvas: any) => void; }' is not assignable to parameter of type 'Html2CanvasOptions'.
  Object literal may only specify known properties, and 'onrendered' does not exist in type 'Html2CanvasOptions'.
```

**Comment by adrianowead** [comment]
I'm using with Ionic2 + Angular 2.

```typescript
import * as html2canvas from 'html2canvas';
```

And use like:

```typescript
myClickFunction( event: any ){
  html2canvas( event.target )
    .then((canvas) => {
      console.log( canvas );
    })
    .catch(err => {
      console.log("error canvas", err);
    });
}
```

**Comment by jaichandra** [comment]
I am trying this in Angular 4 and I get below error:
`Uncaught (in promise): Error: Can't resolve all parameters for ImageService: (?).`
I have installed the typings from `"@types/html2canvas"`

**Comment by thescientist13** [comment]
@jaichandra 
I am also seeing something similar using Angular 5.  Trying to build a minimum test case at the moment.
