### ISSUE TITLE
Sub-canvas is narrower

### ISSUE THREAD

**Issue by chriscfox** [niklasvh/html2canvas#961]
I have a situation where I overlay a canvas over some HTML in order to draw lines between some of the HTML boxes.
This works fine in the browser.
However, when I render the combined HTML and canvas using html2canvas, the overlaid canvas seems to be slightly narrower than it is in the browser. This means that the lines to 'join' the boxes properly.

Any ideas what would cause this and what I can do about it?

**Comment by Dayjo** [comment]
Does the canvas have dimensions set explicitly?

**Comment by chriscfox** [comment]
Yes, the canvas has margin-top, margin-left height and width set explicitly in order to overlay the HTML boxes.

Here is what it looks like in the browser:
![image](https://cloud.githubusercontent.com/assets/17232444/19919118/8173ecfe-a0c8-11e6-9e19-4535400d7f5e.png)

And here is the rendered PNG file from html2canvas:
![image 42](https://cloud.githubusercontent.com/assets/17232444/19919209/196e8fc8-a0c9-11e6-9413-68ebed9bdcbb.png)

See how the lines joining the boxes are offset to the left.

To see this in action, register at https://strategiclearningapp.com, then select Analysis -> Add -> McKinsey 7S. This will show you the browser version. To convert to PNG, click on the 'gears' icon (top right) and select 'download' (however, you will note that I have currently excluded the lines from the download, rather than including them incorrectly.)

Many thanks.

**Comment by chriscfox** [comment]
Note, in the examples posted above, it is intended that the buttons shown on the browser rendered version are not shown in the html2canvas PNG version.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
