### ISSUE TITLE
Sub canvas in HTML can not be screenshot in IE

### ISSUE THREAD

**Issue by junhao3687** [niklasvh/html2canvas#963]
In my HTML page contains sub canvas code (use echart to generate some graphs). 
It works fine in brwoser.
But when i try to use html2canvas to screenshot the page to png, i find that some IE browser is OK, and some is not OK, the IE version is the some version -- IE11, and i also compare the setting of IE - no different.
The issue is the sub-canvas part in HTML can not display correctly, i'm not sure what's the problem.
Any ideas what would cause this and that I can do about it?
Following is my code:
`<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="gbk">
        <title>ECharts</title>
    <script src="./es6-promise.js"></script>
    <script src="./echarts.min.js"></script>
    <script src="./jquery-2.0.0.js"></script>
    <script src="./html2canvas.js"></script>
    <script src="./canvas2image.js"></script>
</head>
<body>
    <button type='button' onclick='screenshot();'>Screenshot</button>
        <div id="main" style="width: 600px;height:400px;"></div>
    <div id="imgs"></div>
        <script type="text/javascript">
        var myChart = echarts.init(document.getElementById('main'));
        var option = {
            title: {    
                text: 'ECharts example'
            },
            tooltip: {},
            legend: {
                data:['Color']
            },
            xAxis: {
                data: ["red","blue","yellow","white","black","green"]
            },
            yAxis: {},
            series: [{
                name: 'Value',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };
        myChart.setOption(option);
        function screenshot(){
            html2canvas( document.body ,{   
                onrendered: function(canvas){
                    var strData = canvas.toDataURL();
                    //console.log(strData);
                    //console.log(strData.length);
                    var img = document.createElement('img');
                    img.src = strData;
                    $("#imgs").append(img);
                }
            });
        }
    </script>
</body>
</html>`

**Comment by aifeiji** [comment]
hello, junhao3687,  i met the same question, please tell me how resolve, thank you very much
