### ISSUE TITLE
Why html2canvas interception of the map when it will intercept it ?

### ISSUE THREAD

**Issue by janisfu** [niklasvh/html2canvas#964]
Why html2canvas interception of the map when it will intercept it ?
Example:
Original map：
![image](https://cloud.githubusercontent.com/assets/12291202/19585912/1dd32d34-9783-11e6-9d2a-bb2c45be63ea.png)
Intercepted map picture:
![image](https://cloud.githubusercontent.com/assets/12291202/19585927/322439fe-9783-11e6-9955-9a5c05de2441.png)

**Comment by LeiHen** [comment]
应该是图片跨域导致的，我也遇到了

**Comment by janisfu** [comment]
你解决了吗？

**Comment by LeiHen** [comment]
并没有

**Comment by LeiHen** [comment]
并没有，不过里面有个属性 是代理跨域图片地址
proxy
Url to the proxy which is to be used for loading cross-origin images. If left empty, cross-origin images won't be loaded.
我使用了 但是好像也无效，不过也可能是我格式不对

**Comment by janisfu** [comment]
恩恩，我一直都是用的代理，刚开始几天完全可以截图完整，后面就发生了截图不全的问题，不知是html2canvas本身的问题还是怎么的，换了几个版本的html2canvas都不得行

**Comment by LeiHen** [comment]
我用代理 一张图片 就可以 用多张就不行 ，
都替换成同一张了。
你代理怎么写的？
我是这么写的：
proxy:"http://xxx.com/images/img-01.jpg"

而还有个问题 就是 只截图了 当前页面显示的内容，显示内容之外的截取不到

**Comment by janisfu** [comment]
java代理：
/**
	 * 地图截图内容下载代理
	 * @param request
	 * @param response
	 */
	@RequestMapping(value="/proxy", method = RequestMethod.GET)
    public void  getJwd(HttpServletRequest request,HttpServletResponse response){
        String url = request.getParameter("url");
        System.out.println(url);
        String callback = request.getParameter("callback");
        if(url != "" && callback != ""){
            try {
                URL urlInfo = new URL(url);
                if(urlInfo.getProtocol().equals("http") || urlInfo.getProtocol().equals("https")){
                    HttpURLConnection conn = (HttpURLConnection) urlInfo.openConnection();
                    String contentType = conn.getContentType();
                    if(contentType.equals("image/png") || contentType.equals("image/jpg") || contentType.equals("image/jpeg") || contentType.equals("image/gif") || contentType.equals("text/html") || contentType.equals("application/xhtml")){
                        if(request.getParameter("xhr2") != null){
                            response.setHeader("Access-Control-Allow-Origin", "*");
                    		response.setHeader("Access-Control-Allow-Credentials", "true");
                            response.setContentType(contentType);
                            DataInputStream input = new DataInputStream(conn.getInputStream());
                            BufferedOutputStream bout = new BufferedOutputStream(response.getOutputStream());
                            try {
                              byte b[] = new byte[1024];
                              int len = input.read(b);
                              while (len > 0) {
                                bout.write(b, 0, len);
                                len = input.read(b);
                              }
                            } catch (Exception e) {
                              e.printStackTrace();
                            } finally {
                              bout.close();
                              input.close();
                            }
                        }else{
                            response.setContentType("application/javascript");
                            if(contentType.equals("text/html") || contentType.equals("application/xhtml")){
                            }else{
                                // 获取数据流生成byte字节
                                DataInputStream input = new DataInputStream(conn.getInputStream());
                                input.toString();
                                byte[] buffer = new byte[1024 * 8];
                                 
                                ByteArrayOutputStream bos = new ByteArrayOutputStream(1000);
                                byte[] b = new byte[1024 * 8];
                                int n; 
                                while ((n = input.read(b)) != -1) { 
                                    bos.write(b, 0, n); 
                                } 
                                input.close(); 
                                bos.close();
                                buffer = bos.toByteArray(); 
                                // 将byte转成base64
                                Base64 encode=new Base64();
                                String base64data = encode.encodeToString(buffer);
                                base64data = base64data.replaceAll("\r\n","");
                                response.getWriter().write(callback+"('"+ "data:" + contentType + ";base64," + base64data +"')");
                            }
                        }
                    }
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
	}
js代码：
html2canvas(document.getElementById("container"),{
		            "logging": false,
		            "proxy": "${ctx}/openLine/openLine/proxy",
		            "onrendered": function(canvas) {
		            	closeTip();
		                var img = new Image();
		                img.crossOrigin = "*";
		                img.width=700;
		                img.height=900;
		                img.onload = function() {
		                    img.onload = null;
		                    $("#pic").val(img.src);
		                    if(img.src!=null&&img.src!=""){
		                    	$("#messageBox_success").show();
		                    }else{
		                    	$("#messageBox_error").show();
		                    }
		                };
		                img.onerror = function() {
		                    img.onerror = null;
		                    if(window.console.log) {
		                        window.console.log("Not loaded image from canvas.toDataURL");
		                    } else {
		                        alert("Not loaded image from canvas.toDataURL");
		                    }
		                };
		                img.src = canvas.toDataURL("image/png");
		            }
				});

**Comment by janisfu** [comment]
之前截取出来的和原图一模一样，但后来就成后面的效果了，真奇葩！

**Comment by LeiHen** [comment]
"proxy": "${ctx}/openLine/openLine/proxy"
你这里文件夹下对应一张图，还是多张图？
还有你能截取到显示区域外的内容么？

**Comment by LeiHen** [comment]
你试试 多加个 
useCORS:true
应该就可以

**Comment by LeiHen** [comment]
问题搞定了 ，但是又发现了 。。。
另外一个问题：无法截取到区域外的内容

**Comment by LeiHen** [comment]
你试试 多加个 
useCORS:true
应该就可以
@janisfu

**Comment by janisfu** [comment]
加了useCORS:true也不行 @LeiHen

**Comment by LeiHen** [comment]
你跨几个域，我测试过 跨一个是可以，多个还没测试

**Comment by janisfu** [comment]
就高德一个啊，所有的图片都是其下的

**Comment by janisfu** [comment]
图片倒是都截取到了的，地图里面的其他样式没有了，例如道路走向、建筑什么的

**Comment by LeiHen** [comment]
是不是 样式还没加载完 就截屏了

**Comment by janisfu** [comment]
不是，我是按钮点击事件截图的 @LeiHen

**Comment by LeiHen** [comment]
![image](https://cloud.githubusercontent.com/assets/4099706/20340093/d8be7bd4-ac1a-11e6-9f20-4a34148b1347.png)

有具体的截图看么？
（想象不出来到底结果是什么样子的）

**Comment by janisfu** [comment]
就是我问题的内容啊

**Comment by janisfu** [comment]
![image](https://cloud.githubusercontent.com/assets/12291202/20340644/88f6ea48-ac1d-11e6-8c0a-b431302a3fa6.png)
![image](https://cloud.githubusercontent.com/assets/12291202/20340647/8ecda4e8-ac1d-11e6-981c-4c794e4ad8c1.png)

**Comment by LeiHen** [comment]
你不是说 图片出来了么？
底部那些 是图片来的
你这样图还是没出来
