### ISSUE TITLE
Html2canvas letterrendering with space and sankey chart Google

### ISSUE THREAD

**Issue by Fraaud** [niklasvh/html2canvas#968]
Hello,

I have created this html file with sankey graph and two button png save image and jpg, these two buttons convert the div html-content-holde into a canvas and image with html2canvas, and it work. But i have a problem with space between 'A b' into sankey rows,( i set option letterRendering: true in html2canvas) , if I leave the space between two letters in the image I have repeated twice 'A b', if i write 'A_b' everything works. do you have some proposals?

html & java file in zip file

**Comment by Fraaud** [comment]
[sankey.zip](https://github.com/niklasvh/html2canvas/files/549761/sankey.zip)

**Comment by ASardar** [comment]
Hi Fraaud,

Were you able so solve the double text issue? I am having the same issue.

**Comment by MostafaHamidian** [comment]
html2canvas: 
parent node set display: table; 
child node set display: table-cell; vertical-align: middle  | top | ...
