### ISSUE TITLE
Blurred image and text on Mobile H5C3

### ISSUE THREAD

**Issue by week2k** [niklasvh/html2canvas#972]
Hello, there. I just integrated the html2canvas to my H5C3 project and found the generated image is quite blurred with blitch at the edge. The text is also not very clear also.

I had set the option "letterRendering:true", but it also looks ugly and unacceptable.

I have met the canvas ratio issue on Mobile H5C3, so I rebuild the project with some modification and it worked.

I want to share it as below:

> In the src/renderers/canvas.js

`var Renderer = require('../renderer');
var LinearGradientContainer = require('../lineargradientcontainer');
var log = require('../log');

function CanvasRenderer(width, height) {
    Renderer.apply(this, arguments);
    this.canvas = this.options.canvas || this.document.createElement("canvas");
    if (!this.options.canvas) {
        this.canvas.width = width;
        this.canvas.height = height;
    }
    var origWidth = this.canvas.width;
    var origHeight = this.canvas.height;  
    this.ratio = this.getCanvasPixelRatio(this.canvas);  
    this.canvas.width = origWidth \* this.ratio;
    this.canvas.height = origHeight \* this.ratio;
    this.ctx = this.canvas.getContext("2d");
    this.ctx.scale(this.ratio, this.ratio);
    this.canvas.originalDevicePixelRatio = this.canvas.originalDevicePixelRatio || this.ratio;
    //this.canvas.width = origWidth;
    //this.canvas.height = origHeight;
    this.taintCtx = this.document.createElement("canvas").getContext("2d");
    this.ctx.textBaseline = "bottom";
    this.variables = {};
    log("Initialized CanvasRenderer with size", width, "x", height);
}

CanvasRenderer.prototype = Object.create(Renderer.prototype);

CanvasRenderer.prototype.ratio = null;

CanvasRenderer.prototype.getCanvasPixelRatio = function (canvas) {
    var ctx = canvas.getContext("2d"),
            dpr = window.devicePixelRatio || 1,
            bsr = ctx.webkitBackingStorePixelRatio ||
            ctx.mozBackingStorePixelRatio ||
            ctx.msBackingStorePixelRatio ||
            ctx.oBackingStorePixelRatio ||
            ctx.backingStorePixelRatio || 1;

```
return dpr / bsr;
```

};
`

I hope it can help.

**Comment by cuitianze** [comment]
iphone 6plus
dpr 3
bsr  1

it doesn't work
