### ISSUE TITLE
MIT missing in licence (0.5.0 b3)

### ISSUE THREAD

**Issue by d-j-a-y** [niklasvh/html2canvas#974]
in ./dist/html2canvas.min.js L5
`>>>  Released under  License`
`<<<  Released under MIT License`

https://github.com/niklasvh/html2canvas/blob/master/dist/html2canvas.min.js#L5

_very nice work! (i use html2canvas to capture huge gif composition in [WeAreGifAnimals project](https://github.com/d-j-a-y/WeAreGifAnimals))_

**Comment by makc** [comment]
it's b4 but it still sys b3, too
