### ISSUE TITLE
When for loop 50 doms, 46th throw:  html2canvas.js:619 Uncaught (in promise) TypeError: Cannot read property 'document' of null

### ISSUE THREAD

**Issue by Nomia** [niklasvh/html2canvas#975]
This is a great canvas tool. Thank u very much. I used this plugin quite often.

But today I got a problem with it. What i want to do is to get 50 canvas for 50 dom nodes by using html2canvas. But it stopped at 46, when I reverse the dom array, it still stopped at 46. 

I took a look at the error stack, it has something todo with iframe that html2canvas has created when generate the canvas. But the iframe cannot find when comes to a certain point.

source code and error attached as below:

```
            // generate canvas for every dom node
            // dompages are self generated div dom nodes, they have their style
            $(dompages).each(function(i, pageDom){
                pageDom = $(pageDom).clone().get(0);

                $hiddenContainer.append(pageDom);
                width = pageDom.offsetWidth;
                height = pageDom.offsetHeight;

                html2canvas(pageDom, {
                    onrendered: function(canvas) {

                    }
                });
            });
```

stack trace:
![image](https://cloud.githubusercontent.com/assets/1707818/19828829/64739568-9e03-11e6-86d6-476d52ba07ba.png)

html2canvas.js:619
![image](https://cloud.githubusercontent.com/assets/1707818/19828834/8d7db4c0-9e03-11e6-922c-beea47a6c4ea.png)

html2canvas.js:969
![image](https://cloud.githubusercontent.com/assets/1707818/19828837/a68d9962-9e03-11e6-9dc4-b6d56c0bc1ad.png)

**Comment by bilazik** [comment]
Did you solve the problem? I have exactly the same error, but the customer requires 56 DOM elements.

**Comment by eKoopmans** [comment]
Hi @Nomia and @bilazik, could either of you please make a jsFiddle that illustrates the problem? I'd be happy to take a look at it for you. You can use [this template](https://jsfiddle.net/69kc2t2y/) as a starting point, it has the latest `html2canvas` loaded as an external resource already so you just need to put in some HTML/CSS/JS. Thanks!

**Comment by Nomia** [comment]
Hi, @eKoopmans @bilazik I turned to old version of this plugin.

**Comment by teja551** [comment]
@Nomia and @bilazik,@eKoopmans I am also facing same problem please guide me how to resolve this issue.
