### ISSUE TITLE
html2canvas some how stop rendering image

### ISSUE THREAD

**Issue by raaaas** [niklasvh/html2canvas#976]
hello everyone, 

ive installed/added html2canvas to my project and after few working around everything was okay but right after my boss start testing it my project for no reason stop rendering imgs 

here is example : 
![index](https://cloud.githubusercontent.com/assets/7237781/19837734/28d91294-9ed5-11e6-97ef-4478a2184e9d.png)
it was befor my boss testing

and here is after my boss tested 
![canvas](https://cloud.githubusercontent.com/assets/7237781/19837739/401e0e46-9ed5-11e6-9ab8-18dda8172f7a.png)

my code  :
`   $('#cmd').click(function () {
        var width = doc.internal.pageSize.width;  
        var height = doc.internal.pageSize.height
        var screenshot = '';

```
    html2canvas($(".warpper")).then(function(canvas) {
        document.body.appendChild(canvas);
    });

    /*,{
            "logging": true,allowTaint: true,
        onrendered: function(canvas) {
            //doc.addImage(canvas, 'png', 0, 0, width, height,undefined,'slow');
            //doc.save('vito.pdf');
            document.body.appendChild(canvas);

            }
             });
             */
```

 });`

note : im useing latest version : v0.5zip 
im useing it with laravel - backpack 

ps : if anyone could give me help on fixing unicode bug that would be awesome too.

**Comment by raaaas** [comment]
ok wiredly enough problem cused by jspf 

i just change order of jspdf to be loaded befor html2canvas and it fixed 

fot charecter bug i just did this

line 2321 : 
    var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {

just changed it to 
    var textList = (!this.options.letterRendering || noLetterSpacing(container)) && hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {


everything work just fine right now

**Comment by BilalAdhi** [comment]
In Which file i have to change the following Code?

line 2321 :
var textList = (!this.options.letterRendering || noLetterSpacing(container)) && !hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {

just changed it to
var textList = (!this.options.letterRendering || noLetterSpacing(container)) && hasUnicode(container.node.data) ? getWords(characters) : characters.map(function(character) {
