### ISSUE TITLE
render 50 doms to canvas, the canvas result will change(blank) as the width  and the height change. 

### ISSUE THREAD

**Issue by Nomia** [niklasvh/html2canvas#977]
render 50 doms to canvas, the canvas result will change(blank) as the width  and the height change. When I set the width or the height to 700px, the canvas in the onrendered callback will be blank.

Here is my simple code:
http://jsbin.com/renuyirimo/edit?html,js,output

**Comment by Nomia** [comment]
![image](https://cloud.githubusercontent.com/assets/1707818/19847462/0b658df2-9f82-11e6-897e-82040fd54d6f.png)

the demo will result in 50 blank canvas which is not expected.

but 

you can change the width to 600 or change the loop to 5 instead of 50, the canvas will not be blank, which is expected

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
