### ISSUE TITLE
I want to show an image that exceeds the area is cut.

### ISSUE THREAD

**Issue by dykim1004** [niklasvh/html2canvas#978]
The transform css was using translate, rotate, scale.
JI GIL as a result of its wish to draw on the canvas.

html2canvas 0.5.0-alpha1 

-- result --

![html2canvas 0 5 0-alpha1](https://cloud.githubusercontent.com/assets/16068092/19855274/f6d97fee-9fb6-11e6-871c-29ad6762ef0d.png)

custom souce ... 

CanvasRenderer.prototype.clip = function(shapes, callback, context) {
    //this.ctx.save();
    shapes.filter(hasEntries).forEach(function(shape) {
        this.shape(shape).clip();
    }, this);
    callback.call(context);
    //this.ctx.restore();
};

-- result --

![customimg](https://cloud.githubusercontent.com/assets/16068092/19855340/58381e76-9fb7-11e6-831f-11261515e81f.png)

I do wonder sikijineun edits an error occurred in the utility function.
Otherwise, when the corresponding overflow hidden in one version, the car I want to provide an option to be able to cut img screent shot. Thank you

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
