### ISSUE TITLE
CSS styles not loaded with image

### ISSUE THREAD

**Issue by krisjans27** [niklasvh/html2canvas#979]
Hi,

I am trying to convert html table to image and in the process using Html2Canvas for the conversion. Conversion of the image works fine in firefox, where as in chrome and IE the content of the table is  loaded but the styles applied for the table borders are missing.

Did anyone come across this issue?

Thanks,
 Kris

**Comment by Zeladgolan** [comment]
Yes, I have the same issue.. 
I'm  still trying to resolve this.
Have you worked it out?
