### ISSUE TITLE
Duplicated SVG text element with @font-face

### ISSUE THREAD

**Issue by AndreLovichi** [niklasvh/html2canvas#983]
Dear all,

I'm trying to use html2canvas.js to take screenshots with JavaScript, and it's great, but I have a problem when the page contains SVG text elements.

As you can see on this JSFiddle (https://jsfiddle.net/AndreLovichi/571t86u4/), the text element is duplicated (and only one of the copies keep the right font family).

I've beed looking for similar issue, and I've found this one: http://stackoverflow.com/questions/29597242/svg-text-attribute-is-doubling-html2canvas.
However, the patch on NodeParser.prototype.getChildren didn't work for me: the remaining text element had the wrong font family.

I've also posted this question on StackOverflow: http://stackoverflow.com/questions/40469672/how-to-convert-svg-text-element-with-font-face-to-canvas-using-html2canvas-js

Thanks a lot !

**Comment by aamir1995** [comment]
@AndreLovichi I think the problem is with SVG element, if you use simple div, it will work fine,  see https://jsfiddle.net/dqm6L7jk/

**Comment by AndreLovichi** [comment]
Hi Aamir!

Thanks a lot for your answer!

Unfortunately, I have to use SVG element (I took a very basic example on my JSFiddle, but the real case is much more complex).

Do you have any hint for SVG elements?

Thanks again!

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by AndreLovichi** [comment]
Dear @Niklasvh,

Thanks a lot for your answer!

I've tried with v1.0.0-alpha.8, but unfortunately, I still have the same issue.
Here is the JSFiddle: https://jsfiddle.net/AndreLovichi/zq6y3y0t/1/

Remark: I've tried with and without the html2canvas.svg.js file.

Thanks for your help, and best regards!

**Comment by eggers** [comment]
@AndreLovichi I was able to fix it in the previous version through a few things. Staring with this:
https://github.com/hyojin/html2canvas/commit/79f50bb3c0992aa1fd52a26e72d13010c515cb90

Also this change:

```js
@@ -2031,7 +2031,10 @@ NodeParser.prototype.getPseudoElement = function(container, type) {

 NodeParser.prototype.getChildren = function(parentContainer) {
     return flatten([].filter.call(parentContainer.node.childNodes, renderableNode).map(function(node) {
-        var container = [node.nodeType === Node.TEXT_NODE && !(node.parentNode instanceof SVGElement) ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
+        if (node.nodeType === Node.TEXT_NODE && node.parentNode instanceof SVGElement)  {
+            return [];
+        }
+        var container = [node.nodeType === Node.TEXT_NODE ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
         return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
     }, this));
 };
```

Finally for firefox I did this:

```js
@@ -3470,7 +3470,7 @@ function SVGNodeContainer(node, _native) {
         self.image = new Image();
         self.image.onload = resolve;
         self.image.onerror = reject;
-        self.image.src = "data:image/svg+xml," + (new XMLSerializer()).serializeToString(node);
+        self.image.src = "data:image/svg+xml," + encodeURIComponent((new XMLSerializer()).serializeToString(node));
         if (self.image.complete === true) {
             resolve(self.image);
         }
```
