### ISSUE TITLE
Not image inside iframe gives 404 error

### ISSUE THREAD

**Issue by bastole** [niklasvh/html2canvas#988]
On https://github.com/niklasvh/html2canvas/blob/master/tests/cases/iframe.html

When image.jpg is added to the same path as iframe.html as below, image.jpg won't get captured and gives 404 Error.
image.jpg:1 GET http://localhost:8080/tests/cases/image.jpg 404 (Not Found).

Is it not possible to have images on the same path as iframe.html ?

```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>frame 1</title>
    <style>
        body {
            background: green;
            color: red;
        }
    </style>
</head>
<body>
this is the content of frame1
<img src="image.jpg"/>
</body>
</html>

```

**Comment by rparree** [comment]
I had the same problem today. Hopefully  this will work in the future. 

Meanwhile had a look at this temporary workaround where you load the html using xhr, use regex for search and replace. You then create a link to a `Blob` using `URL.createObjectURL`. You can then use that URL to create a temporary iframe. 

https://gist.github.com/rparree/3d842494e1ebeef041b1e9423921e013

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
