### ISSUE TITLE
对页面元素截图时，截取的图片不会包含子元素的内容。

### ISSUE THREAD

**Issue by lxhao** [niklasvh/html2canvas#989]
比如我在一个div里面放置了几个子div，截取出来的图片就是最外层div的背景，几个子div的内容都没有截取到，如果我希望截取时能包含子元素，应该怎么做？谢谢！

**Comment by momognu** [comment]
我倒是没遇到这样的问题，它会自动截取所有子元素，但是我在手机上不知道怎么保存图片它canvas.toDataURL()生成的url在手机浏览器打不开

**Comment by python-tool** [comment]
是不是动态加载的元素无法识别，问题解决了吗
