### ISSUE TITLE
0.5.0 Alpha - SVG charts are not displayed on canvas. 

### ISSUE THREAD

**Issue by AndreyKad90** [niklasvh/html2canvas#990]
Hi! We'd been using the 0.4.1 version until we came across a problem with icons in Firefox. We didn't have any issues with SVG charts - we convert every chart to an image and draw the image on a canvas, and then every svg is replaced with a corresponding canvas.

I encounter that the version 0.5.0 alpha contains a solution for icons in Firebox. I updated the version. The icons are drawn and shown in the end, but the problem with 'empty' svg emerged.

Is it only my problem in 0.5.0?

**Comment by NoelBroda** [comment]
+1
I have the same issue with charts that render the lines using SCG.
I'm using `NVD3`. This `NVD3` version is using `d3` version 3.4.13

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
