### ISSUE TITLE
How to solve the problem of img cross domain

### ISSUE THREAD

**Issue by LeiHen** [niklasvh/html2canvas#993]
How to solve the problem of img cross domain?
Img cross-domain save don't show.

**Comment by developeryashraj** [comment]
You need to provide a proxy setting for that. written here in [FAQ](https://html2canvas.hertzen.com/faq.html) You will find proxy option in [Available Options](https://html2canvas.hertzen.com/documentation.html#available-options) list. Hope this will help you.

**Comment by NikhilRadadiya** [comment]
@developeryashraj having same issue tried to use 
`"proxy": "http://mydomain.com",`
Still it didn't work for me also having cross-origin header issue
