### ISSUE TITLE
firefox svg "Failed loading image"

### ISSUE THREAD

**Issue by wackowizzard** [niklasvh/html2canvas#995]
In Firefox I can't get this to work : the svg images are left out (it works in Safari & Chrome).

        html2canvas($(document.body), {
            onrendered : function (canvas) {
                document.body.appendChild(canvas);
            },
            allowTaint : true,
            logging : true,
            useCORS : true
        }); 

In log:
html2canvas: Failed loading image #3 Object { src: <svg>, image: <img>, promise: Promise } error { target: <img>, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1479322233213764, originalTarget: <img>, explicitOriginalTarget: <img>, NONE: 0, CAPTURING_PHASE: 1 } 1 html2canvas.js:1487:9

example svg:
    <svg xmlns="http://www.w3.org/2000/svg" width="213" height="213" viewBox="0 0 212.6 212.6"><style>.a{clip-path:url(#SVGID_2_);fill:#0079C1;}.b{clip-path:url(#SVGID_2_);fill:#EF3F38;}</style><defs><rect width="212.6" height="212.6"/></defs><clipPath><use xlink:href="#SVGID_1_"/></clipPath><path d="M105.9 25.3c46.9 0 84.9 14.5 84.9 51.8 0 37.3-38 109.1-84.9 109.1 -46.9 0-84.9-71.9-84.9-109.1C21 39.8 59 25.3 105.9 25.3" style="clip-path:url(#SVGID_2_);fill:#FFF"/><path d="M105.9 188.5c-12.6 0-37.3-5.4-61.9-41.6 -15.1-22.2-25.3-50.3-25.3-69.8 0-34.3 31.8-54 87.2-54 55.4 0 87.2 19.7 87.2 54 0 19.5-10.2 47.6-25.3 69.8C143.3 183.1 118.5 188.5 105.9 188.5M105.9 27.5c-24.5 0-44.9 4-59 11.6 -15.7 8.5-23.7 21.2-23.7 37.9 0 18.7 9.8 45.7 24.5 67.3 10 14.8 31 39.6 58.2 39.6 45.2 0 82.7-70.8 82.7-106.9 0-16.7-8-29.4-23.7-37.9C150.8 31.6 130.4 27.5 105.9 27.5" class="a"/><polygon points="86.5 162.9 125.3 162.9 125.3 63.4 86.5 90.6 " class="a"/><polygon points="66.9 99.2 61.9 102.6 54.4 91.7 51.9 96.1 48.6 91.3 52.1 85.4 55.7 83 " class="a"/><path d="M62.5 90.2c-3.4-4.9-2.9-10.4 1.3-13.3 4.2-2.9 9.4-1.4 12.9 3.5 3.4 4.9 2.9 10.4-1.3 13.3C71.2 96.6 65.9 95.2 62.5 90.2M67.5 86.8c1.4 2 3.3 3.5 4.9 2.5 1.6-1.1 0.8-3.4-0.6-5.4 -1.4-2-3.3-3.6-4.8-2.5C65.3 82.5 66.1 84.8 67.5 86.8" class="a"/><path d="M77.1 80.2c-3.4-4.9-2.9-10.4 1.3-13.3 4.2-2.9 9.4-1.4 12.9 3.5 3.4 4.9 2.9 10.4-1.3 13.3C85.7 86.6 80.5 85.1 77.1 80.2M82 76.8c1.4 2 3.3 3.6 4.9 2.5 1.6-1.1 0.8-3.4-0.6-5.4 -1.4-2-3.3-3.6-4.8-2.5C79.8 72.5 80.6 74.8 82 76.8" class="a"/><path d="M108.2 70.6c-4.9 3.4-10.6 2.1-13.9-2.7 -3.4-4.9-2.5-10.7 2.4-14 4.9-3.4 10.6-2.1 14 2.7C113.9 61.4 113 67.3 108.2 70.6M99.7 58.3c-1.8 1.2-2 3.6-0.3 6 1.7 2.4 3.9 3.1 5.7 1.8 1.8-1.2 2-3.6 0.3-6C103.8 57.7 101.5 57.1 99.7 58.3" class="b"/><path d="M118.9 56.3l3.1 4.4 -5 3.5 -11.2-16.2 7.6-5.2c3.6-2.5 7.6-2.1 10.2 1.7 2.6 3.8 1.6 7.6-2 10.1L118.9 56.3zM115.6 47.5l-1.9 1.3 2.3 3.3 1.9-1.3c1.3-0.9 1.4-1.9 0.7-2.9C117.8 46.8 116.9 46.6 115.6 47.5" class="b"/></svg>
            
Please help!

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
