### ISSUE TITLE
Not working on some pages

### ISSUE THREAD

**Issue by premreddyn** [niklasvh/html2canvas#996]
I made an extension on the base of html2canvas which will insert a div and takes a snapshot of that.It worked on some webpages but not rendering on lotta webpages.I finally took those and started looking at common patterns, I found that those pages have so much in height(in px as in >30000) of their body.Could that be the reason that html2canvas can't take snapshot of that much bigger document?
Help me achieve this on any webpage.

**Comment by niklasvh** [comment]
With extensions you could use elevated permissions from the browser to take real screenshots instead of use html2canvas. Most browsers also have size limits for canvas sizes, https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element/11585939#11585939
