### ISSUE TITLE
Blank image generated when using option "type: view" and scroll down to the middle of the page

### ISSUE THREAD

**Issue by jludev1** [niklasvh/html2canvas#997]
The "type: view" option tells html2canvas to generate the screeenshot of the current viewport.
But on some websites if you scroll down beyond the content in the first page, the screenshot will be blank. 
This can be reproduced with cnn.com.

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
